### ISSUE TITLE
KSQL CLI docker image does not show output for ksql-migrations

### ISSUE THREAD

**Issue by cbcoutinho** [confluentinc/ksql#10091]
**Describe the bug**
The `cp-ksqldb-cli` image does not show any output when running any of the CLI commands as described in the documentation. The strange thing is, the latest `ksqldb-cli` image does print logs - can explain to me what the difference is?

**To Reproduce**

Using the Confluent Platform (official?) image I get no response:

```bash
$ docker run -v ./migrations:/migrations --entrypoint sh confluentinc/cp-ksqldb-cli ksql-migrations -c /migrations/ksql-migrations.properties info
*** NOTHING ***
```

Now run the same command with the non `cp-` image:

```bash
$ docker run --rm -it -v ./migrations:/migrations --entrypoint sh confluentinc/ksqldb-cli ksql-migrations -c /migrations/ksql-migrations.properties info
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Current migration version: 24
-------------------------------------------------------------------------------------------------------------------------------------------------------
 Version | Name                               | State    | Previous Version | Started On                  | Completed On                | Error Reason
-------------------------------------------------------------------------------------------------------------------------------------------------------
.
.
.
```

**Expected behavior**
All CLI commands send their output to STDOUT/STDERR on completion

**Actual behaviour**
See above.

**Additional context**

**Comment by cbcoutinho** [comment]
The issue is that the two images have differing log4j.properties files. I've updated the properties files to log to STDOUT so I'll close the ticket.

**Comment by filpano** [comment]
This seems to still be an issue as of `confluentinc/cp-ksqldb-cli:7.6.1` for practically all commands including `validate` and `apply -a`.

**Comment by dtoledanojc** [comment]
I too am having this issue with cp-ksqldb-cli:7.5.7. Is there a fix?
