### ISSUE TITLE
4.1.x Interoperability matrix has not been updated.

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#1018]
The following docs don't cover v4.1's 

https://github.com/confluentinc/ksql/blob/5953b6c9a3dfbb6b6728565a4517ac42212de18e/docs-rst/README.md

https://github.com/confluentinc/ksql/blob/82991dd842ab42b0072e58fc0820151e55a0407e/docs/README.md

I'm not sure if this is because these md files are now defunct or not, but we should either remove them or update them to avoid confusing people, (like me!)

Also this page:

https://github.com/confluentinc/ksql/blob/5953b6c9a3dfbb6b6728565a4517ac42212de18e/docs-rst/installation/index.rst

Has an `Interoperability` section, which doesn't cover _Interoperability_! ;)

**Comment by joel-hamill** [comment]
.md files are now out of date and will be replaced once the 4.1.x docs go live. the files you have referenced appear to be a test by @ewencp https://github.com/confluentinc/ksql/commit/5953b6c9a3dfbb6b6728565a4517ac42212de18e.
