### ISSUE TITLE
Clarify avro support in docs

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#1028]
On https://github.com/confluentinc/ksql/blob/4.1.x/docs/faq.rst#can-i-use-ksql-with-my-favorite-data-format-e-g-json-avro 

1. so we should be removing “Support for Apache Avro is expected soon.“
2.  add a clear note that support for Avro is for message values only, and that Avro keys are not supported (c.f. #824 )

**Comment by miguno** [comment]
> 1. so we should be removing “Support for Apache Avro is expected soon.“

This has already been fixed since.

> 2. add a clear note that support for Avro is for message values only, and that Avro keys are not supported (c.f. #824 )

@joel-hamill : Could you take a look at that?

**Comment by miguno** [comment]
Btw, KSQL does have some (limited) support for keys in JSON format, see @rodesai's answer at https://stackoverflow.com/questions/49844380/ksql-kafka-formatting-of-keys.

**Comment by joel-hamill** [comment]
@rmoff @miguno see https://github.com/confluentinc/ksql/pull/1152
