### ISSUE TITLE
get a timestamp column in a group by select

### ISSUE THREAD

**Issue by gjimher** [confluentinc/ksql#1048]
This query runs fine:

SELECT SUM(CPU_PCT)/COUNT(*) AS CPU, HOST FROM KS_METRICS_JAVA WINDOW TUMBLING (SIZE 10 SECOND) GROUP BY HOST;

I want to add a timestamp column with the window initial time.
The nearest I get is with the query:

SELECT SUM(CPU_PCT)/COUNT(HOST) AS CPU, ROWTIME AS "timestamp"  FROM KS_METRICS_JAVA WINDOW TUMBLING (SIZE 10 SECOND) GROUP BY HOST;

But I lose the HOST column. If I add it I get an error from QueryAnalyzer.java/enforceAggregateRules: ""Group by elements should match the SELECT expressions." (There are two columns, HOST and ROWTIME, which  have no aggregations function, and there is only one "group by" column). 

Isn't this enforcement too strict? Shouldn't we remove it?

**Comment by big-andy-coates** [comment]
Hi @gjimher,

If you want to add a timestamp column to the output then you need tell _which_ record's timestamp you want to output. Remember, as you're using a `GROUP BY` command, there can be many rows in the window with the same HOST. Do you want the average timestamp? the min? the max?

So, for example, if you wanted to timestamp of the last row to fall within the window, then you can run something like this:

```
SELECT HOST, SUM(CPU_PCT)/COUNT(HOST) AS CPU, MAX(ROWTIME) AS "timestamp" FROM KS_METRICS_JAVA WINDOW TUMBLING (SIZE 10 SECOND) GROUP BY HOST;
```

Interestingly, I would have expected this query to fail too:

> SELECT SUM(CPU_PCT)/COUNT(HOST) AS CPU, ROWTIME AS "timestamp" FROM KS_METRICS_JAVA WINDOW TUMBLING (SIZE 10 SECOND) GROUP BY HOST;

As `HOST` is not part of the select statement. But it doesn't fail.   I've raised #1061 to track.

**Comment by gjimher** [comment]
It is the window initial time I am insterested in. It is not MIN(ROWTIME) (they would be the same if I had events every millisecond)

I played a little since I wrote it, and realized that ROWTIME is the initial event time (not the initial aggregation window time).

I finally managed to get it creating a CTAS, and then do a SELECT on it with its ROWTIME.
Thanks!
