### ISSUE TITLE
Misleading error message

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#1052]
In this statement, the join is failing because the left object is not aliased, and thus `L.USER_MAC` is not valid. 

```
ksql> SELECT TIMESTAMPTOSTRING(L.ROWTIME, 'yyyy-MM-dd HH:mm:ss') , L.AP_NAME, U.NAME FROM UBNT_SYSLOG_AP_CONNECTS2 LEFT JOIN UBNT_USER U ON L.USER_MAC = U.MAC LIMIT 5;
 Line: 1, Col: 146 : Invalid join criteria (L.USER_MAC = U.MAC). Key for UBNT_SYSLOG_AP_CONNECTS2 is not set correctly.
```

Whilst "`Invalid join criteria (L.USER_MAC = U.MAC)`" is correct, the second part of the error is very misleading since it suggests there is a problem with the key `Key for UBNT_SYSLOG_AP_CONNECTS2 is not set correctly.`. Given the key requirements around successful joins to TABLE objects, it is easy to see how this is going to confuse people into thinking there's an issue with the underlying topic key. 

Something like "Cannot determine join column for object `UBNT_SYSLOG_AP_CONNECTS2`" might be less ambiguous?

**Comment by big-andy-coates** [comment]
Duplicate of #839??

**Comment by rmoff** [comment]
Yes. And yours had a more informative title too, apologies :) Closing.
