### ISSUE TITLE
Need to document use case for `PARTITION BY` for aggregations

### ISSUE THREAD

**Issue by ybyzek** [confluentinc/ksql#1053]
Aggregations like `TOPK` get results per partition.  To get results across all partitions, users need to use `PARTITION BY` with some fixed key.  This needs to be documented

example

```
create stream allplaycounts as select "fixed_key" as key, * from playcountsstream partition by "fixed_key";
```

**Comment by miguno** [comment]
@JimGalasyn : Is this documented already?

**Comment by JimGalasyn** [comment]
@miguno @ybyzek I'm pretty sure we don't have this in docs -- I'll open a ticket.

**Comment by big-andy-coates** [comment]
Adding to 0.11 milestone to get it some love.

**Comment by JimGalasyn** [comment]
Fixed in https://github.com/confluentinc/ksql/pull/6434.
