### ISSUE TITLE
NullPointerException during SUM, MIN, MAX aggregation on values of MAP<varchar, double>

### ISSUE THREAD

**Issue by poojaKarande13** [confluentinc/ksql#1054]
I face issue when performing SUM, MIN or MAX aggregation on the values of a Map<varchar, double>.

```
ksql> SELECT sum(data['some_key']), id FROM raw_event WINDOW TUMBLING (SIZE 20 SECONDS) GROUP BY id;
ServerError:java.lang.NullPointerException
```

data is of type  Map<varchar, double>
e.g. data = {'some_key': 3.45}

Count aggregation works fine!

**Comment by miguno** [comment]
Which version of KSQL are you using @poojaKarande13 ?

- The KSQL server prints the version on startup (for recent KSQL versions).
- In the KSQL CLI (`ksql>`) you can type `VERSION` to get the version info.

**Comment by PoojaKarande** [comment]
Version: 0.4

**Comment by poojaKarande13** [comment]
Hello @miguno The version is **0.4**

**Comment by rodesai** [comment]
Can you include: 
- The output from `describe extended raw_event` ?
- Are there any NPE stack traces in the ksql server log?

**Comment by PoojaKarande** [comment]
- Raw event

  Field      | Type                        
------------------------------------------
 ROWTIME    | BIGINT           (system)   
 ROWKEY     | VARCHAR(STRING)  (system)   
 ID | VARCHAR(STRING)             
 TIMESTAMP  | VARCHAR(STRING)             
 DATA       | MAP[VARCHAR(STRING),DOUBLE] 
------------------------------------------

**Comment by rodesai** [comment]
Thanks! I was able to reproduce this locally. Looks like a bug in our aggregator. Should have an update soon.

**Comment by rodesai** [comment]
We are still working on a fix. As a workaround you can extract your map entry into a separate column first and then running your aggregation? For example:

```sql
CREATE STREAM extracted as select id, data['some_key']) as data_some_key FROM raw_event;
SELECT sum(data_some_key), id FROM raw_event WINDOW TUMBLING (SIZE 20 SECONDS) GROUP BY id;
```

**Comment by PoojaKarande** [comment]
Thank you @rodesai ! I tried the work around for now and it works fine.
I have a question, can I perform windowing on a table which itself is windowed?
eg. 
```
CREATE TABLE table1 AS SELECT id1, id2, max('some_key') AS SomeKey FROM some_stream WINDOW TUMBLING (SIZE 10 SECONDS) GROUP BY id1, id2;

SELECT id1, sum(SomeKey) FROM table1 WINDOW TUMBLING (SIZE 300 SECONDS/) GROUP BY id1;
```
I tried doing this but I got this error
org.apache.kafka.streams.kstream.Windowed cannot be cast to java.lang.String

**Comment by apurvam** [comment]
Unfortunately, we don't currently support aggregates on tables, so your first query above doesn't work. Here is an issue to track this limitation: #778 .

**Comment by PoojaKarande** [comment]
Error still persists
ServerError:java.lang.NullPointerException

**Comment by apurvam** [comment]
Which version are you using?

**Comment by Oegma2** [comment]
Just tried a count(*) in query - very basic query and also getting - I also check my data in the table and can't find any "null" values...so no sure how this error is triggered - happy to provide more details but the error msg is:

> ServerError:java.lang.NullPointerException

Using command line KSQL Version: **4.1.1**

**Comment by poojaKarande13** [comment]
@Oegma2 I am using the confluent v5.0 and the Group By functions work now. Let me know if you want more details.
