### ISSUE TITLE
Issue when recreating a CSAS that includes a left join

### ISSUE THREAD

**Issue by vahidhashemian** [confluentinc/ksql#1055]
I have a stream `cart_event (type, session, product, timestamp)` and a table `product (id, name, price)`. When I join these two:
```
ksql> create stream cart_event_product as select ce.type, ce.session, ce.timestamp, ce.product, p.name, p.price from cart_event ce left join product p on ce.product=p.id;
```
and run
```
ksql> select * from cart_event_product;
```
I get proper result back.

If I drop the stream, however, recreate it
```
ksql> drop stream cart_event_product;
ksql> create stream cart_event_product as select ce.type, ce.session, ce.timestamp, ce.product, p.name, p.price from cart_event ce left join product p on ce.product=p.id;
```
and run
```
ksql> select * from cart_event_product;
```
Table columns associated with recently joined rowed come back as `null`. This seems to have roots in some traces left from the first time table was created. The workaround for me was to refresh my Kafka environment and start over, as I wanted to stick with that stream name. Creating a `cart_event_product2` stream (note the new name) works fine though.

**Comment by big-andy-coates** [comment]
Hi @vahidhashemian,

Thanks for taking the time to raise this issue. I've tried recreating this locally in a test and so far I've failed.  What version of KSQL are you using? Would you be willing to try and recreate this on the latest branch? (Either master or 4.1.x).

If you can recreate, then can you run the following commands at the end and paste the output in here please?

`show tables;`
`show streams;`
`show queries;`

Thanks.

**Comment by vahidhashemian** [comment]
@big-andy-coates, thanks for your response. I just tried this again in my environment and was able to reproduce the issue. I am running the latest codebase on `master` branch (commit 7449f3d).

Here's some more info about my stream and table:
```
ksql> describe extended cart_event;

Type                 : STREAM
Key field            : 
Timestamp field      : Not set - using <ROWTIME>
Key format           : STRING
Value format         : AVRO
Kafka output topic   : cart-event (partitions: 1, replication: 1)

 Field     | Type                      
---------------------------------------
 ROWTIME   | BIGINT           (system) 
 ROWKEY    | VARCHAR(STRING)  (system) 
 TYPE      | VARCHAR(STRING)           
 SESSION   | VARCHAR(STRING)           
 PRODUCT   | INTEGER                   
 TIMESTAMP | BIGINT                    
---------------------------------------
...

ksql> describe extended product;

Type                 : TABLE
Key field            : ID
Timestamp field      : Not set - using <ROWTIME>
Key format           : STRING
Value format         : JSON
Kafka output topic   : product (partitions: 1, replication: 1)

 Field   | Type                      
-------------------------------------
 ROWTIME | BIGINT           (system) 
 ROWKEY  | VARCHAR(STRING)  (system) 
 ID      | INTEGER                   
 NAME    | VARCHAR(STRING)           
 PRICE   | DOUBLE                    
-------------------------------------
...
```
This is the other info you requested:
```
ksql> show tables;

 Table Name | Kafka Topic | Format | Windowed 
----------------------------------------------
 PRODUCT    | product     | JSON   | false    
 SESSION    | session     | AVRO   | false    
----------------------------------------------
ksql> show streams;

 Stream Name        | Kafka Topic        | Format 
--------------------------------------------------
 CART_EVENT         | cart-event         | AVRO   
 CART_EVENT_PRODUCT | CART_EVENT_PRODUCT | AVRO   
--------------------------------------------------
ksql> show queries;

 Query ID                | Kafka Topic        | Query String                                                                                                                                                         
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CSAS_CART_EVENT_PRODUCT | CART_EVENT_PRODUCT | create stream cart_event_product as select ce.type, ce.session, ce.timestamp, ce.product, p.name, p.price from cart_event ce left join product p on ce.product=p.id; 
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
For detailed information on a Query run: EXPLAIN <Query ID>;
```

I am running this in a dev environment along with Kafka 1.0.0 and Schema Registry all in one Ubuntu VM. The content of ksql.log can be seen here: https://www.codepile.net/pile/VlRgAp4j.

Please let me know if you need any additional info. Thanks!

**Comment by robertrbruno** [comment]
I believe I am seeing similar issues when I drop and recreate join streams.  Here are more details on what I am seeing.

https://github.com/confluentinc/ksql/issues/1265

**Comment by agavra** [comment]
Closing this issue because all of the work items are being tracked separately (see the follow-up on #1365). Feel free to re-open or create a new issue if those don't address your scenario.
