### ISSUE TITLE
ksql-cli won't start under java 10

### ISSUE THREAD

**Issue by larsp** [confluentinc/ksql#1065]
```
$ > ksql-cli
Unrecognized VM option 'UseParNewGC'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

> The command-line flag -XX:+UseParNewGC no longer has an effect. The ParNew flag can be used only with CMS and CMS requires ParNew. Thus, the -XX:+UseParNewGC flag has been deprecated and is eligible for removal in a future release.

**Comment by big-andy-coates** [comment]
Thanks for reporting @larsp.  To my knowledge, KSQL hasn't officially been tested with Java 10. However, I've raised a PR to remove the redundant cmd line param.

**Comment by big-andy-coates** [comment]
Fixed in master branch,
