### ISSUE TITLE
ksql-rest-app doc

### ISSUE THREAD

**Issue by JozeFe** [confluentinc/ksql#1067]
Please where can I found any documentation for KSQL REST API, 
eg. endpoints, response formats, quick start

Thank you.

**Comment by cricket007** [comment]
Related to #304

**Comment by big-andy-coates** [comment]
Hi @JozeFe , I'm closing this as it's a duplicate of #304.  REST API docs are coming... ;)

**Comment by JozeFe** [comment]
@big-andy-coates Thank you for fast reply. :)
