### ISSUE TITLE
FIlter/whitelist the properties that can be get/set for queries

### ISSUE THREAD

**Issue by rodesai** [confluentinc/ksql#1083]
`list properties` currently returns all the properties that the ksql engine is aware of, many of which are not relevant to the user (e.g. `com.sun.management.jmxremote.authenticate`).

We should restrict what's returned to just the ksql engine properties.

**Comment by apurvam** [comment]
It would also be nice to show the other settings and mark them out as 'not being overridable from the CLI'.

**Comment by agavra** [comment]
Closing out this ticket because the most recent versions only return KSQL prefixed properties (the bug is fixed) - we can create a new ticket for the new feature enhancement ticket @apurvam mentioned as "not overridable".
