### ISSUE TITLE
cannot run execution plan, null in CTAS from CTAS

### ISSUE THREAD

**Issue by gjimher** [confluentinc/ksql#1088]
I have a stream of events. I want to calculate the SUM of a VAL field each hour in a performant way.
I want to use a table grouped by GRP field. Let the table update the SUM of the GRP each 2 seconds, and sum everything in another table grouped by the time window initial time.

CREATE TABLE SUM1 AS SELECT GRP, SUM(VAL) AS SUM_GRP FROM MY_STREAM WINDOW TUMBLING (SIZE 1 HOUR) GROUP BY GRP;
CREATE TABLE SUM2 AS SELECT ROWTIME, SUM(SUM_GRP) AS SUM_TOT FROM SUM1 GROUP BY ROWTIME;

I looked at kafka streams api and I think those queries could make sense:
 KStream.groupBy->KGroupedStream.windowedBy->TimeWindowedKStream.aggregate/reduce->KTable<Windowed<K>,V>.groupBy->KGroupedTable.aggregate

I get the following error:

  "Cannot RUN execution plan for this statement ... Caused by: null"
    stackTrace: 
      - "io.confluent.ksql.rest.server.resources.KsqlResource.getStatementExecutionPlan(KsqlResource.java:473)"
      - "io.confluent.ksql.rest.server.resources.KsqlResource.validateStatement(KsqlResource.java:256)"
      - "io.confluent.ksql.rest.server.resources.KsqlResource.executeStatement(KsqlResource.java:232)"
      - "io.confluent.ksql.rest.server.resources.KsqlResource.handleKsqlStatements(KsqlResource.java:148)"

**Comment by rodesai** [comment]
Currently KSQL does not support aggregations on tables. The latest master should return a better error message than what you see above. We're tracking the aggregates on tables feature in this issue: https://github.com/confluentinc/ksql/issues/778 . Feel free to give it a +1 to help us track demand!
