### ISSUE TITLE
How to do "group by map['key']" query in KSQL?

### ISSUE THREAD

**Issue by ChenShuai1981** [confluentinc/ksql#1099]
I have a schema which contains a userInfo map, and an "age" field in userInfo map, now I want to do aggregation query on `userInfo['age']` column, the ksql complains 

```
ServerError:java.lang.NullPointerException
```

while group by `userInfo` column is well, why?

**Comment by apurvam** [comment]
Unfortunately, you seem to be hitting #1054. Try the work around suggested [here](https://github.com/confluentinc/ksql/issues/1054#issuecomment-377297688).

**Comment by apurvam** [comment]
Closing this. If it a different issue, please reopen.
