### ISSUE TITLE
Tombstones in a stream produces errors in the log

### ISSUE THREAD

**Issue by fuyar** [confluentinc/ksql#1100]
Hello,

So I have a topic that is being written by Debezium (a CDC). It produces tombstones when the line is deleted on the DB.

I created a stream over this topic and just tried to select something out of it.
Each time the consumers read a tombstone an error is triggered and written into the logs : 

```
[2018-03-30 08:34:54,055] ERROR  (io.confluent.ksql.structured.SqlPredicate:134)
java.lang.NullPointerException
[2018-03-30 08:34:54,056] ERROR Invalid format: 195087119 : null (io.confluent.ksql.structured.SqlPredicate:136)
```

In the topic here's the message : 
```
{
  "topic": "test",
  "partition": "17",
  "offset": "7249898",
  "timestamp": "1521763952610",
  "key": 195087119,
  "value": null
}

```

**Comment by agavra** [comment]
I believe this has been fixed in more recent versions (see https://github.com/confluentinc/ksql/issues/2186) so I'm closing this out to keep our backlog clean. Please feel free to re-open or issue a new ticket if the problem persists!
