### ISSUE TITLE
Handle requests to /ksql with chained queries

### ISSUE THREAD

**Issue by rodesai** [confluentinc/ksql#1104]
Consider the following set of chained queries:

```sql
create stream a as select * from source;
create stream b as select * from a;
```

If I issue them from the same API call to /ksql the server responds with an error indicating that `A does not exist`. This is because all the queries are validated against the same copy of the metastore without updating after each query. We should instead update the copy of the metastore after validating each query.

**Comment by agavra** [comment]
This feature is supported in more recent versions of KSQL! 🎉
