### ISSUE TITLE
Stream Table join won't work on huge topics

### ISSUE THREAD

**Issue by fuyar** [confluentinc/ksql#1110]
Hello,

I'm trying to join a stream and a table based on 2 huge topics with the same cardinality (200M+ messages).

In the resulting topic, there's a lot of non joined messages while they should have been.

I can find the keys on the table topic for these messages.
I dont understand how KSQL can start writing messages while the table topic is not read fully (to be sure to have the last entry for each key before joining).

**Comment by rodesai** [comment]
Couple possibilities here:

1. Your stream and table are not keyed correctly. In the current version of KSQL there is a restriction that the kafka message keys for the messages in your tables must be the same as your key column, and that that column have type `VARCHAR/STRING`. If you declare a key column for a stream, then that must also meet these requirements. We are still finishing up the docs for GA, which will include details about this restriction, and how you can use KSQL to workaround it. You can check out the current version of that doc here: https://github.com/confluentinc/ksql/blob/4.1.x/docs/key-constraints.rst

2. Kafka Streams will try and synchronize the join using the timestamps in the kafka messages. So if a record in your stream has an earlier timestamp than the record in the table with the matching key, then the result of the join will be null.

**Comment by apurvam** [comment]
Another possibility: when you start a join query, the changelog topic of the input table is read from the beginning and the input stream is read from the end by default. So if key K is written to both input topics at around the same time, it means that the output will be null, because the table would not have been populated yet.

Do the incidence of null joins reduce after a while?

**Comment by apurvam** [comment]
I'm going to close this for now. Please open if you think your question was not answered, @fuyar .
