### ISSUE TITLE
Need SQL Average (AVG) Aggregation Function

### ISSUE THREAD

**Issue by tomlinsonr** [confluentinc/ksql#1123]
Trying to figure out average of X within a given window for a BI visualization. KSQL supports MAX, MIN, .... but why not `AVG`?

Super common BI use case.

**Comment by rodesai** [comment]
Until an AVG is implemented you can use SUM and COUNT e.g. ```SELECT x, SUM(y) / COUNT(*) FROM foo GROUP BY x;```

**Comment by tomlinsonr** [comment]
Thanks @rodesai, so this is on the roadmap?

**Comment by rodesai** [comment]
A richer set of udfs is in the works, though no concrete date for that yet.

**Comment by miguno** [comment]
Contributions are welcome, @tomlinsonr :)

**Comment by lssilva** [comment]
> A richer set of built-in functions is in the works, though no concrete date for that yet.
That would be great. Looking forward!!

**Comment by holgerbrandl** [comment]
Is there a more specific date for the richer set of built-in functions @rodesai ?

Or is there maybe a third-party repo with custom UDFs that includes AVG and other functions to make SQL even more fun (such as LAST, FIRST, LAG, etc)?

**Comment by agavra** [comment]
@holgerbrandl - take a look at #3302! The next release should have average and the ability to build more complicated custom UDFs thanks to @vpapavas
