### ISSUE TITLE
Handle queries that try to join a table with a table by returning a meaningful error

### ISSUE THREAD

**Issue by tomlinsonr** [confluentinc/ksql#1133]
Trying to run the following query:

SELECT TA_0.USERNAME as USERNAME FROM CLICK_USER_SESSIONS TA_0 LEFT OUTER JOIN WEB_USERS TA_1 ON ( TA_0.USERNAME=TA_1.USERNAME );

But get:

ServerError:java.lang.NullPointerException

I'm pretty sure this is legit KSQL.... Is this a bug or something else?

**Comment by rodesai** [comment]
Is CLICK_USER_SESSIONS a table? We currently do not support table-table joins. That said, KSQL of course shouldn't fail with an NPE. So the error message is certainly a bug.

**Comment by tomlinsonr** [comment]
Thanks @rodesai. It is an attempt to join table to table. We would like to request this for a future release - do you have another ticket for this currently? I'd imagine its a common request.

Up to you if you want to keep this issue open for the error message. Would be good to see something like "Table to table joins not currently supported in KSQL" or similar.

**Comment by rodesai** [comment]
Yep - here's the ticket for that feature https://github.com/confluentinc/ksql/issues/760. It is indeed a popular request.

I'll leave this open to track the error message. Thanks!

**Comment by tomlinsonr** [comment]
@rodesai I would like to expand this ticket to error messages for any type of join - not just table to table but also table to stream when the stream is built from a table. For example using the clickstream demo:

`ksql> select * from CLICK_USER_SESSIONS_TS LEFT JOIN WEB_USERS ON CLICK_USER_SESSIONS_TS.username=WEB_USERS.username ;
 ServerError:java.lang.NullPointerException
Query terminated`

CLICK_USER_SESSIONS_TS is a stream built on a table. We should have a more intuitive error message if this join is not currently supported.

**Comment by agavra** [comment]
It seems that table-table joins are now valid (https://github.com/confluentinc/ksql/pull/1417) and we've improved our error handling quite dramatically since, so I'm closing out this ticket to cleanup our backlog! Please feel free to re-open if you run into any similar issues.
