### ISSUE TITLE
No easy way to detect whether it is possible/supported to join a table and specific type of stream

### ISSUE THREAD

**Issue by tomlinsonr** [confluentinc/ksql#1142]
KSQL supports joining streams and tables, but if the stream is based on a table (e.g. CLICK_USER_SESSIONS_TS in the clickstream demo) the join is not currently supported (?)

We are writing a UI that encourages users to join tables and streams but in the situation above we get a ServerError:java.lang.NullPointerException when we try and join with WEB_USERS table. We need to be able to know in advance whether the stream is a pure stream or a table based stream so we know whether we can let users attempt the join or not.

I hope that makes sense :)

**Comment by rodesai** [comment]
You should be able to join any kind of stream with a table. If its not working then its a bug.

**Comment by tomlinsonr** [comment]
OK, that's strange - See below:
`ksql> list streams;

 Stream Name               | Kafka Topic               | Format
----------------------------------------------------------------
 USER_CLICKSTREAM          | USER_CLICKSTREAM          | JSON
 ENRICHED_ERROR_CODES      | ENRICHED_ERROR_CODES      | JSON
 CLICK_USER_SESSIONS_TS    | CLICK_USER_SESSIONS_TS    | JSON
 USER_IP_ACTIVITY_TS       | USER_IP_ACTIVITY_TS       | JSON
 CUSTOMER_CLICKSTREAM      | CUSTOMER_CLICKSTREAM      | JSON
 CLICKSTREAM               | clickstream               | JSON
 EVENTS_PER_MIN_MAX_AVG_TS | EVENTS_PER_MIN_MAX_AVG_TS | JSON
 CUSTOMER_CLICKSTREAM_TIME | CUSTOMER_CLICKSTREAM_TIME | JSON
 ERRORS_PER_MIN_TS         | ERRORS_PER_MIN_TS         | JSON
 EVENTS_PER_MIN_TS         | EVENTS_PER_MIN_TS         | JSON
 ERRORS_PER_MIN_ALERT_TS   | ERRORS_PER_MIN_ALERT_TS   | JSON
 PAGES_PER_MIN_TS          | PAGES_PER_MIN_TS          | JSON
 ENRICHED_ERROR_CODES_TS   | ENRICHED_ERROR_CODES_TS   | JSON
 CLICKSTREAM_TIME          | CLICKSTREAM_TIME          | JSON
----------------------------------------------------------------`

**Comment by tomlinsonr** [comment]
BTW - I did raise another ticket to request the bug fix here: https://github.com/confluentinc/ksql/issues/1143

This is more on the error message.

**Comment by rodesai** [comment]
What docker image are you running the clickstream from?

**Comment by tomlinsonr** [comment]
Just the stuff from following the instructions here: https://github.com/confluentinc/ksql/blob/v0.5/ksql-clickstream-demo/docker-clickstream.md#clickstream-analysis-using-docker

I'm on a mac.

**Comment by rodesai** [comment]
Ah - looks like a bug from 0.5 that's fixed on master and in the upcoming GA release. Unfortunately we don't have an updated docker image at the moment. Hopefully we can publish those in the next week or so.

**Comment by tomlinsonr** [comment]
Ok no problem at all. Thanks for letting me know. I guess we can close this and 1143 out? LMK and I will close.

**Comment by rodesai** [comment]
I'm just going to go ahead and close these
