### ISSUE TITLE
after running query in ksql sometime , it will be down suddenly ,

### ISSUE THREAD

**Issue by ws2003gq** [confluentinc/ksql#1146]
You can see the img below, "Local runtime statistics" is empty now. 
1. How can I recover it?
2. if the data will lose ? 
3. How to avoid it happen again?

Now I always to recover it by delete the old query and create a new one.

![image](https://user-images.githubusercontent.com/1281382/38786143-a2fe3500-4158-11e8-9873-a42f2de56146.png)

**Comment by ws2003gq** [comment]
At begging, It worked well, stream_nori_log can be processed by the query.
For a long while (almost 3~5days), the query died as above img.
Yes I confirm there has some dirty messages in stream_nori_log(json-decode failed).
But I can not find any useful ERROR messages about this terminal queries unusual.
The import things that I have 5 node of ksql and they were down together.

**Comment by miguno** [comment]
@ws2003gq : Did you inspect the KSQL log files?  Any information in there?

**Comment by ws2003gq** [comment]
The coordinator is not aware of this member
![image](https://user-images.githubusercontent.com/1281382/38842864-f6067250-421e-11e8-8166-e34242eeeb48.png)
I found some messages like this.

**Comment by miguno** [comment]
Any follow-up on this @ws2003gq ?  It looks to be an issue (perhaps configuration) with your Kafka and/or KSQL environment.

**Comment by agavra** [comment]
Hello @ws2003gq - since there hasn't been any activity on this ticket for a while, I'm closing this ticket out as part of an effort to cleanup our backlog. If you are still running into this issue feel free to re-open and we'll take another look!
