### ISSUE TITLE
REST Call waits for response forever

### ISSUE THREAD

**Issue by sagarshah71193** [confluentinc/ksql#1149]
ISSUES: 
(1) I was trying to get data from KStream and KTable using REST call but it looks like it waits and waits for the response from KSQL and eventually I get time out error. 
For example, I created a stream and a table from topic users (as described in Quick Start) and pass following query using REST call.
Query  is
```
"{ \"ksql\" : \"SELECT * FROM userTable2 WHERE userid='User_4';\", \"streamsProperties\": {} }"
```
where userTable2 is a table created from topic "users".
this does not return anything (keeps waiting for response).

(2) if I add LIMIT in the query, it returns response after limit+1 data has matched the query.
for example
```
"{ \"ksql\" : \"SELECT * FROM userTable2 WHERE userid='User_4' LIMIT 1;\", \"streamsProperties\": {} }"
```
this would get me a response if there are at least 2 rows with userid=User_4.

(3) In the WHERE clause if the condition doesn't match any records, it still keeps on waiting and I get time out error eventually.
for example:
```
"{ \"ksql\" : \"SELECT * FROM userTable2 WHERE userid='User_11';\", \"streamsProperties\": {} }"
```
here there is no column with User_11, so I was expecting to get NULL (like in database) but instead, it waits forever. 

so my question is how can I make it return whatever is there in stream/table or NULL if condition doesn't match any records, instead of waiting for response?

Thanks

**Comment by miguno** [comment]
This is expected behavior in the world of streaming -- a streaming SQL query will run continuously, i.e. 24x7, until you explicitly terminate the query.  This is the case particularly because there is always new data arriving.

And yes, this behavior is different from SQL in the RDBMS world.
