### ISSUE TITLE
Lacking ARGMAX

### ISSUE THREAD

**Issue by vjache** [confluentinc/ksql#1157]
Hi guys! 
I tried to use KSQL to produce "candles" and it seems it is "near impossible". To produce a "1min candle" from e.g. trades( i.e. (timestamp, price)), it is required to compute a four aggregates in a 1 min window (tumbling): min price, max price, open price, close price. It is easy to make an aggregates like "min price" & "max price", but not "open price" & "close price" . "open price" is just the price of the very first event in a time slot (1min), and "close price" is the very last one. 

I think it would be great to have not only MAX/MIN agg ops in arsenal but also ARGMIN(Col2Compare, Col2Take)/ARGMAX(Col2Compare, Col2Take). 

I would have also a chance to compute "open" / "close" if MAX & MIN would accept STRING type, because in such a case I would just CONCAT(TIMESTAMP, PRICE), and then use MAX/MIN.

P.S. Or am I missing something and there are other way to do what I want?
P.P.S. Is it easy to write custom agg operation like MIN/MAX and feed to KSQL?

**Comment by apurvam** [comment]
I believe you are asking for two missing features:

FIRST and LAST aggregate functions: #1128 
Allow true UDFs: #678 

If those cover your asks, maybe up vote those tickets and then close this? 

Thanks!

**Comment by vjache** [comment]
Thank you for references! This ticket can be closed.
