### ISSUE TITLE
Confluent 4.1.0 KSQL Issue (Cannot override property 'bootstrap.servers')

### ISSUE THREAD

**Issue by zamirarif** [confluentinc/ksql#1180]
I can start the KSQL Server as shown below :
![confluent-4-1](https://user-images.githubusercontent.com/11668609/38996932-89cc20ce-43ec-11e8-83d3-fe4c986685ca.PNG)

I can start the ksql client and create a stream as shown below.
![ksql-start](https://user-images.githubusercontent.com/11668609/38996976-a0970a26-43ec-11e8-8e6e-2dca8b55e8b8.PNG)

When I try to query the streams or create new streams I am getting following error.

![ksql-error](https://user-images.githubusercontent.com/11668609/38997012-b4488ab8-43ec-11e8-9f41-d5f5b7e72281.PNG)

I have verified all the config and it looks good.

Please help me resolve this issue ASAP because its a blocker for us. We never get such error in 0.5 version.

**Comment by apurvam** [comment]
You are using the servers bootstrap.properties for the CLI. Please have a look at [this document](https://docs.confluent.io/current/ksql/docs/installation/cli-config.html) to learn about which configurations you can override in the CLI. 

I recommend that you don't specify a config file to the CLI at all unless you really need to override one of the overriable properties.

**Comment by zamirarif** [comment]
Hi @apurvam 
Thanks for the quick response. You saved my day. I just started the KSQL with server name and it works. 
Anyways when checked the properties it shows it's using the same properties file which I am passing to start CLI. I guess when you pass your configFile it means you are overriding the props. 

When I start with following command it works. 
./bin/ksql -- http://127.0.0.1:9195

Thanks alot I appreciate your help....

cheers.
