### ISSUE TITLE
Specify embedded characters on STRINGTOTIMESTAMP function

### ISSUE THREAD

**Issue by ardlema** [confluentinc/ksql#1194]
I'm trying to convert a date as string to timestamp using the STRINGTOTIMESTAMP function. See below the format of my string field:
```
ksql> SELECT * FROM SALES;                          
1524494345267 | null | 2018-04-16T16:16:29.255Z | 650.45 | Majadahonda | Alimentacion | Pan de molde
```
When I use the STRINGTOTIMESTAMP function I'm getting a null value:
```
ksql> SELECT STRINGTOTIMESTAMP(fechaventa, 'yyyy-MM-ddTHH:mm:ss.SSSZ') FROM sales;                       
null
```
I've tried to define the embedded characters with different options but no luck so far:
```
ksql> SELECT STRINGTOTIMESTAMP(fechaventa, "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'") FROM sales;
Column yyyy-MM-dd'T'HH:mm:ss.SSS'Z' cannot be resolved.
ksql> SELECT STRINGTOTIMESTAMP(fechaventa, 'yyyy-MM-dd`T`HH:mm:ss.SSS`Z`') FROM sales;                   
null
```
As per the StringToTimeStamp unit tests it seems that the function might admit such characters but no idea how to define them through the command line.

Any ideas?

**Comment by rodesai** [comment]
Have you tried `'yyyy-MM-dd''T''HH:mm:ss.SSSX'`?

**Comment by ardlema** [comment]
That did the trick @rodesai Thank you very much!
