### ISSUE TITLE
Support ksql-gen for custom data sets

### ISSUE THREAD

**Issue by kaiwaehner** [confluentinc/ksql#1200]
Can I use ksql-datagen for my own data sets? Looks like I can only use one of 'orders', 'users', or 'pageviews'? Is there a way to use custom data (at least workaround for now)? I think this would also be very helpful for community to generate test data for kafka...

**Comment by apurvam** [comment]
Yes you can. If you create an avro schema and pass it to datagen, it will generate random data according to that schema: `./ksql-datagen schema=impressions.avro format=delimited topic=impressions key=impressionid`.

`impressions.avro` could look like [this](https://github.com/apurvam/streams-prototyping/blob/master/src/main/resources/impressions.avro).

**Comment by Guzel2001** [comment]
Where is located the pageviews ? 
In documentation this command generate data with spesical format. 
 /home/lenovo/apache/confluent/bin/ksql-datagen quickstart=pageviews format=delimited topic=pageviews maxInterval=100 propertiesFile=/home/lenovo/apache/confluent/etc/ksql/datagen.properties

**Comment by apurvam** [comment]
@Guzel2001 https://github.com/confluentinc/ksql/blob/master/ksql-examples/src/main/resources/pageviews_schema.avro

**Comment by Guzel2001** [comment]
I'm new in this topic. Can I only use the ksql - example for generating  my own data sets with the special structure like IP, timestamp, and value data?

**Comment by apurvam** [comment]
Yes. You can create your own avro schema and pass it to `ksql-datagen` as exemplified a few messages above.

**Comment by phisco** [comment]
@apurvam, is `pageviews_schema.avro` an avro schema file? I can't find any specification about the fields used in it or in the other files provided, they are not in the official avro specification as far as i can tell, but I didn't find any clear documentation about them

**Comment by rmoff** [comment]
See also https://docs.confluent.io/current/ksql/docs/tutorials/generate-custom-test-data.html

**Comment by bajaj-varun** [comment]
Is there any documentation available for supported "arg.properties" field of ksql-datagen tool. I want data need to be generate from given predefined values (enums) but didn;t find suitable option.

Trying following code but not working - 

```
{
 "name": "gender",
 "type": {
               "type":["null", "string"],
               "arg.properties":{
                        "regex": "{MALE|FEMALE|OTHER}"
                }
          }
}
```

# Command
`ksql-datagen topic=users schema=users.avsc format=avro key=userid`

# Error -
```
Exception in thread "main" org.apache.avro.SchemaParseException: org.codehaus.jackson.JsonParseException: Unexpected character ('}' (code 125)): was expecting a colon to separate field name and value
```

**Comment by phisco** [comment]
@bajaj-varun https://github.com/confluentinc/avro-random-generator maybe here you can find what you are looking for

**Comment by zaidyahya** [comment]
Where is the avro file to be located if one is running everything via docker container through [this](https://github.com/confluentinc/cp-all-in-one/blob/5.5.1-post/cp-all-in-one-community/docker-compose.yml) docker file? I have placed my avro file in both **connect** and **broker** containers, and given path as _schema=club.avsc_, but still get a 'File not found' error.

**Comment by feboz** [comment]
I'm receiving the following error when trying to create the generator:

root@ksql-datagen:/# ksql-datagen schema=ProcedureAvroSchema.avro format=avro topic=procedures key=procedureid
[2020-10-19 13:43:50,894] INFO AvroDataConfig values: 
        connect.meta.data = true
        enhanced.avro.schema.support = false
        schemas.cache.config = 1000
 (io.confluent.connect.avro.AvroDataConfig:347)
[2020-10-19 13:43:50,941] INFO JsonSchemaDataConfig values: 
        decimal.format = BASE64
        schemas.cache.size = 1000
 (io.confluent.connect.json.JsonSchemaDataConfig:179)
[2020-10-19 13:43:50,943] INFO JsonSchemaDataConfig values: 
        decimal.format = BASE64
        schemas.cache.size = 1000
 (io.confluent.connect.json.JsonSchemaDataConfig:179)
[2020-10-19 13:43:50,949] INFO ProtobufDataConfig values: 
        schemas.cache.config = 1000
 (io.confluent.connect.protobuf.ProtobufDataConfig:179)
[2020-10-19 13:43:50,989] INFO KsqlConfig values: 
        ksql.access.validator.enable = auto
        ksql.authorization.cache.expiry.time.secs = 30
        ksql.authorization.cache.max.entries = 10000
        ksql.connect.url = http://localhost:8083
        ksql.connect.worker.config = 
        ksql.extension.dir = ext
        ksql.hidden.topics = [_confluent.*, __confluent.*, _schemas, __consumer_offsets, __transaction_state, connect-configs, connect-offsets, connect-status, connect-statuses]
        ksql.insert.into.values.enabled = true
        ksql.internal.topic.min.insync.replicas = 1
        ksql.internal.topic.replicas = 1
        ksql.metric.reporters = []
        ksql.metrics.extension = null
        ksql.metrics.tags.custom = 
        ksql.new.api.enabled = false
        ksql.output.topic.name.prefix = 
        ksql.persistence.wrap.single.values = true
        ksql.persistent.prefix = query_
        ksql.pull.queries.enable = true
        ksql.query.persistent.active.limit = 2147483647
        ksql.query.pull.enable.standby.reads = false
        ksql.query.pull.max.allowed.offset.lag = 9223372036854775807
        ksql.readonly.topics = [_confluent.*, __confluent.*, _schemas, __consumer_offsets, __transaction_state, connect-configs, connect-offsets, connect-status, connect-statuses]
        ksql.schema.registry.url = http://localhost:8081
        ksql.security.extension.class = null
        ksql.service.id = default_
        ksql.sink.window.change.log.additional.retention = 1000000
        ksql.streams.shutdown.timeout.ms = 300000
        ksql.transient.prefix = transient_
        ksql.udf.collect.metrics = false
        ksql.udf.enable.security.manager = true
        ksql.udfs.enabled = true
        ssl.cipher.suites = null
        ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
        ssl.endpoint.identification.algorithm = https
        ssl.key.password = null
        ssl.keymanager.algorithm = SunX509
        ssl.keystore.location = null
        ssl.keystore.password = null
        ssl.keystore.type = JKS
        ssl.protocol = TLS
        ssl.provider = null
        ssl.secure.random.implementation = null
        ssl.trustmanager.algorithm = PKIX
        ssl.truststore.location = null
        ssl.truststore.password = null
        ssl.truststore.type = JKS
 (io.confluent.ksql.util.KsqlConfig:347)
java.lang.IllegalArgumentException: Key field does not exist:procedureid
        at io.confluent.ksql.datagen.DataGenProducer.populateTopic(DataGenProducer.java:62)
        at io.confluent.ksql.datagen.DataGen.lambda$getProducerTask$1(DataGen.java:111)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)


So seems the Key argument value should be something already loaded somewhere. Where can I found it?
Thank you
Fabio
