### ISSUE TITLE
Rename ksql-cli docker image in tutorial

### ISSUE THREAD

**Issue by ybyzek** [confluentinc/ksql#1204]
https://github.com/confluentinc/ksql/blob/master/docs/tutorials/docker-compose.yml#L144

Use docker-compose feature `container_name` to rename `ksql-cli` to `ksql`.  This will reduce confusion since ksql-cli is now gone.

**Comment by miguno** [comment]
We are currently working on new docker images, where the CLI image will have the name `cp-ksql-cli`.  IMHO we should stick to this -- most users are new to KSQL and will not have used the previous `ksql-cli` command anyways.

Ping @apurvam -- what do you think (as you are working on new server/CLI Docker images)?

- https://github.com/confluentinc/ksql/pull/1347 (CLI docker image)
- https://github.com/confluentinc/ksql/pull/1322 (server docker image)

**Comment by miguno** [comment]
This has been fixed/superseded since.
