### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by rsilvestre** [confluentinc/ksql#1228]
https://github.com/confluentinc/ksql/blob/1cb8e5744a56fabae14975ba9e48d6a4cb46ac18/ksql-clickstream-demo/demo/clickstream-schema.sql#L24

Hi, I'm running the last 4.1 KSQL server and cli, and I experience an issue when i try to run those queries on my production data.

as if I run this query `select uid, count(*) from tracker_page group by uid;` on the table I have an error `ServerError:java.lang.NullPointerException`

this is the instruction I try to execute:
```
DROP TABLE events_per_min;
CREATE table events_per_min AS SELECT uid, count(*) AS events FROM tracker_page window TUMBLING (size 60 second) GROUP BY uid;

-- VIEW
DROP TABLE events_per_min_max_avg;
CREATE TABLE events_per_min_max_avg AS SELECT uid, min(events) AS min, max(events) AS max, sum(events)/count(events) AS avg from events_per_min  WINDOW TUMBLING (size 60 second) GROUP BY uid;
```

I get this error:  
```
Cannot RUN execution plan for this statement, CreateTableAsSelect{name=EVENTS_PER_MIN_MAX_AVG, query=Query{queryBody=QuerySpecification{select=Select{distinct=false, selectItems=[EVENTS_PER_MIN.UID UID, MIN(EVENTS_PER_MIN.EVENTS) MIN, MAX(EVENTS_PER_MIN.EVENTS) MAX, (SUM(EVENTS_PER_MIN.EVENTS) / COUNT(EVENTS_PER_MIN.EVENTS)) AVG]}, from=AliasedRelation{relation=EVENTS_PER_MIN, alias=EVENTS_PER_MIN}, = WINDOW STREAMWINDOW  TUMBLING ( SIZE 60 SECONDS ) , where=null, groupBy=Optional[GroupBy{isDistinct=false, groupingElements=[SimpleGroupBy{columns=[EVENTS_PER_MIN.UID]}]}], having=null, limit=null}}, notExists=false, properties={}}
```

Here the description of the original stream i use to create the table.
```
ksql> describe extended tracker_page;
Type                 : STREAM
Key field            :
Timestamp field      : Not set - using <ROWTIME>
Key format           : STRING
Value format         : JSON
Kafka output topic   : TRACKER_PAGE (partitions: 4, replication: 1)

 Field           | Type
---------------------------------------------
 ROWTIME         | BIGINT           (system)
 ROWKEY          | VARCHAR(STRING)  (system)
 UID             | VARCHAR(STRING)
 USER_AGENT      | VARCHAR(STRING)
 X_FORWARDED_FOR | VARCHAR(STRING)
 TIMESTAMP       | VARCHAR(STRING)
 SCREEN_PATH     | VARCHAR(STRING)
 SCREEN_TYPE     | VARCHAR(STRING)
 SCREEN_ID       | VARCHAR(STRING)
 ACTION          | VARCHAR(STRING)
 NAVIGATION      | VARCHAR(STRING)
 TAGS            | VARCHAR(STRING)
 SID             | VARCHAR(STRING)
---------------------------------------------

Queries that write into this STREAM
-----------------------------------
id:CSAS_TRACKER_PAGE - CREATE STREAM tracker_page as   select EXTRACTJSONFIELD(data,'$.uid') AS uid,    EXTRACTJSONFIELD(data,'$.context.header.user_agent') AS user_agent,    EXTRACTJSONFIELD(data,'$.context.header.x_forwarded_for') AS x_forwarded_for,    EXTRACTJSONFIELD(data,'$.context.timestamp') AS timestamp,    EXTRACTJSONFIELD(data,'$.screen.path') AS screen_path,    EXTRACTJSONFIELD(data,'$.screen.type') AS screen_type,    EXTRACTJSONFIELD(data,'$.screen.id') AS screen_id,    EXTRACTJSONFIELD(data,'$.action') AS action,    EXTRACTJSONFIELD(data,'$.time.navigation') AS navigation,    EXTRACTJSONFIELD(data,'$.tags') AS tags,    EXTRACTJSONFIELD(data,'$.sid') AS sid  from tracker_raw  where type='page';

For query topology and execution plan please run: EXPLAIN <QueryId>

Local runtime statistics
------------------------
c-total-message-bytes: 443081603 c-total-messages:    753784 messages-per-sec:    247.00   total-messages:   1669039     last-message: 4/27/18 1:56:29 PM UTC
c-failed-messages:         0  failed-messages:         0 failed-messages-per-sec:         0      last-failed:       n/a
(Statistics of the local KSQL server interaction with the Kafka topic TRACKER_PAGE)
```

I read here : https://github.com/confluentinc/ksql/issues/1133 that there is a `NullPointerException` when we try to join 2 tables together. May be it's linked ?

I didn't try to reproduce it with the last ksql master version.

**Comment by rodesai** [comment]
Yikes there is a bunch of stuff going wrong here.

1. Currently KSQL does not support aggregations on tables (this functionality is coming very soon, though only for the un-windowed case). You should be getting a cleaner error message though. What version are you running?

2. It looks like this query comes from the clickstream demo. We should remove it since it doesn't actually work.

3. The clickstream demo when run via `run script` doesn't actually report any errors. I think this is because `run script` doesn't validate the statements contained in the script. We should change the implementation to do so.

**Comment by rsilvestre** [comment]
Hi @rodesai,

1. I'm actually running the version 4.1

2. Sure you should remove it the time you fix the issue

3. It would be nice to improve the `run script` and the ksql-cli.

Thank you for your answers.

I will wait for the next version of KSQL. It's still too new and need to be more stable.

Regards

**Comment by agavra** [comment]
Hello @rsilvestre - there have been tons of improvements in KSQL since this issue, and I think most of the follow-ups have been addressed. Since this ticket seems to be very specific to a single use case, I'm going to close it out to keep our backlog clean. If you ever get a chance to play around with more recent KSQL version and find some issues please feel free to report them as new issues or reopen this one!
