### ISSUE TITLE
Add built-in functions for URL parsing

### ISSUE THREAD

**Issue by blueedgenick** [confluentinc/ksql#1236]
To allow processing of things like http-server log files it would be great to have access to a set of URL-parsing functions. Examples might include dedicated functions to extract the host/parameters/port/protocol/query-string from a url field.  Also url encoding and decoding would be handy.

See also #981 which introduces a request for IP address handling functions.

**Comment by agavra** [comment]
This is done! https://github.com/confluentinc/ksql/pull/2354
