### ISSUE TITLE
Substring function Null handling

### ISSUE THREAD

**Issue by uwegeercken** [confluentinc/ksql#1241]
when trying to use the substring function with a null value, a NullPointerException is thrown on the KSQL server side. Naturally, when you have lots of null values in the column a lot of exception output goes to the server.

I would like to propose this function to catch a null value and simply to return null.

I also find it important that null handling in general should be documented so that the user understands exactly the behavior of a function.

**Comment by agavra** [comment]
I believe this is the current behavior in the most recent version of KSQL, so I'm going to close out this ticket. Please feel free to re-open if the functionality is not addressed!
