### ISSUE TITLE
Add SHOW TOPICS EXTENDED

### ISSUE THREAD

**Issue by apurvam** [confluentinc/ksql#1268]
Currently the `SHOW TOPICS` command does a lot of work:

1. List topics -- 1 API call.
2. List consumer groups -- 1 API call
3. For each consumer group get number of active consumers -- 1 API call per consumer group.

This takes a long time, particularly when there are many consumer groups.

We should add a `show topics extended` command which returns the consumer group information.

**Comment by miguno** [comment]
To clarify: I suppose you mean to (1) change `SHOW TOPICS` to only show #1 above, and (2) add `SHOW TOPICS EXTENDED` to show #1-#3 above?
