### ISSUE TITLE
Error occurred when I run script in ksql console with confluent version 4.1.0

### ISSUE THREAD

**Issue by osenv** [confluentinc/ksql#1269]
```
ksql> run script 'ksql-clickstream-demo/demo/clickstream-schema.sql';
Error reading entity from input stream.
Caused by: Missing type id when trying to resolve subtype of [simple type, class io.confluent.ksql.rest.entity.KsqlEntity]: missing type id property '@type'
 at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 1879] (through reference chain: io.confluent.ksql.rest.entity.KsqlEntityList[0])
```

**Comment by apurvam** [comment]
Which version of the CLI are you using?

**Comment by apurvam** [comment]
and which version of the server?

**Comment by lecodet** [comment]
Hi apurvam, 

Thanks for your reply. I am using the Confluent Open Source: 4.1.0.

**Comment by rmoff** [comment]
@lecodet : 

1) Does this happen with every SQL file, or just this particular one? If the latter, are you able to share the contents of the file? 
2) Have you tried it on 5.0?

**Comment by fjbsantiago** [comment]
> Which version of the CLI are you using?

This was my problem. I ran the docker client without specifying a version and it fetched 'latest'.

**Comment by agavra** [comment]
Since this has been fixed in more recent versions (and more-so, we've deprecated runscript in favor of multiple statements) I'm going to close out this issue as part of an effort to clean up our backlog. Please let me know if this issue persists in more recent versions!
