### ISSUE TITLE
DESCRIBE EXTENDED : change 'Kafka output topic' label

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#1273]
In `DESCRIBE EXTENDED` we have the label `Kafka output topic`. For stream/tables that are just registered on top of existing topics, this is pretty misleading, since KSQL is not outputting anything. 
For CSAS/CTAS it does make sense. 

I'd suggest either: 

1. Change the label dynamically, to either `Kafka input topic`, or as currently `Kafka output topic` (for CSAS/CTAS)
2. Just call it `Kafka topic` for all

**Comment by miguno** [comment]
Duplicate of https://github.com/confluentinc/ksql/pull/1137 I think, which was already merged to `master` about two weeks ago?
