### ISSUE TITLE
Delete consumer groups when a query is terminated

### ISSUE THREAD

**Issue by apurvam** [confluentinc/ksql#1283]
Right now, when a query is terminated, we use the streams reset tool which just resets the committed offsets for the consumer group used by the application id. 

However, for KSQL, the consumer group should really be deleted. 

Now that KIP-222 is available (https://cwiki.apache.org/confluence/display/KAFKA/KIP-222+-+Add+Consumer+Group+operations+to+Admin+API), we can delete  the consumer group once terminate is called using the Java AdminClient.

**Comment by big-andy-coates** [comment]
+1

**Comment by big-andy-coates** [comment]
Marking as P1 as all these consumer groups show up in UIs, making it hard for people to find the actual valid / live consumer groups.

**Comment by apurvam** [comment]
Bumping this up to a p0, as it has come up multiple times now in the last few weeks and is causing quite a lot of  confusion.
