### ISSUE TITLE
compile failure , v5.0.0-beta1

### ISSUE THREAD

**Issue by nankingrider** [confluentinc/ksql#1290]
can not find package in any repo

[ERROR]   The project io.confluent.ksql:ksql-parent:5.0.0-beta1 (C:\Users\t00199885\Downloads\ksql-5.0.0-beta1\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for io.confluent.ksql:ksql-parent:5.0.0-beta1: Could not find artifact io.confluent:rest-utils-parent:pom:5.0.0-beta1 in confluent (http://packages.confluent.io/maven/) and 'parent.relativePath' points at wrong local POM @ line 7, column 13 -> [Help 2]

**Comment by nankingrider** [comment]
update:

4.1 release compiles failure too... with error 

[ERROR]   WelcomeMsgUtilsTest.shouldOutputShortWelcomeMessageIfConsoleNotWideEnough:77 
Expected: is "KSQL, Copyright 2017 Confluent Inc.\n\n"
     but: was "KSQL, Copyright 2017 Confluent Inc.\r\n\r\n"

**Comment by rodesai** [comment]
You can get the preview release building by replacing `packages.confluent.io/maven` in the parent pom.xml with `packages.conflient.io/maven-beta`:

```bash
$ git diff
diff --git a/pom.xml b/pom.xml
index 509929d1..f7782fea 100644
--- a/pom.xml
+++ b/pom.xml
@@ -43,7 +43,7 @@
     <repositories>
         <repository>
             <id>confluent</id>
-            <url>http://packages.confluent.io/maven/</url>
+            <url>http://packages.confluent.io/maven-beta/</url>
         </repository>
         <repository>
             <id>confluent-snapshots</id>
@@ -54,7 +54,7 @@
     <pluginRepositories>
         <pluginRepository>
             <id>confluent</id>
-            <url>http://packages.confluent.io/maven/</url>
+            <url>http://packages.confluent.io/maven-beta/</url>
         </pluginRepository>
         <pluginRepository>
             <id>confluent-snapshots</id>
```

We'll look at how to make this work without modifications for future preview releases.

**Comment by nankingrider** [comment]
Great  , thank you for replying  :)

**Comment by douglarek** [comment]
Should 5.0.0-beta branch sync with v5.0.0 beta tags ?
