### ISSUE TITLE
ksql experimental UI 'Show Example' link 404s

### ISSUE THREAD

**Issue by lhayhurst** [confluentinc/ksql#1298]
Hi, when you click on the 'Show Example' link in the web UI, the link 404s.

URL target is: https://github.com/confluentinc/ksql/blob/master/docs/examples.md#examples

URL target should be? https://github.com/confluentinc/ksql/blob/master/docs/tutorials/examples.rst 

Cheers

**Comment by miguno** [comment]
Thanks for reporting, @lhayhurst.

FYI: The upcoming UI for KSQL in Confluent Control Center looks quite different to the experimental UI (which was a stop gap) and has much more functionality. See example screenshot at https://www.confluent.io/blog/level-up-your-ksql/.

**Comment by lhayhurst** [comment]
Looking forward to it, thanks @miguno  !
