### ISSUE TITLE
ksql cli - No response to select query on a table created on stream

### ISSUE THREAD

**Issue by ReddyTunga** [confluentinc/ksql#1300]
Issue # No data populating from table and it hangs there on as below and no response

```
ksql> select * from TBL1 limit 5;
```

![ksql-table_describe](https://user-images.githubusercontent.com/39238218/39967461-285bf338-56c4-11e8-90d1-b2a2930718ca.PNG)
![ksql-version_streams_tables_topics](https://user-images.githubusercontent.com/39238218/39967573-8ab3c270-56c6-11e8-879b-bcca1b829612.PNG)

**Comment by rodesai** [comment]
Are there records being written into the stream ST1?

**Comment by akastanis** [comment]
Same here:
**Data:**
cat ande.json 
{"messageId" : "1", "type": "accepted", "country": "US"}
{"messageId" : "2", "type": "accepted", "country": "GB"}
{"messageId" : "4", "type": "accepted", "country": "IN"}

**Load the data to a topic:**
kafka-console-producer --broker-list localhost:9092 --topic ande-events < ande.json

**View the data**
ksql> print 'ande-events' from beginning;
Format:JSON
{"ROWTIME":1528396289738,"ROWKEY":"null","messageId":"1","type":"accepted","country":"US"}
{"ROWTIME":1528396289744,"ROWKEY":"null","messageId":"2","type":"accepted","country":"GB"}
{"ROWTIME":1528396289744,"ROWKEY":"null","messageId":"4","type":"accepted","country":"IN"}

**Stream creation:**
CREATE STREAM countrycodestream (messageId VARCHAR, country VARCHAR) WITH (KAFKA_TOPIC='ande-events', VALUE_FORMAT='JSON', KEY='messageId');

**Table creation:**
CREATE TABLE countrycodes (messageId VARCHAR, country VARCHAR)  WITH (KAFKA_TOPIC='ande-events',  VALUE_FORMAT='JSON', KEY='messageId');

**Select from stream works:**
ksql> select * from countrycodestream;
1528396289738 | null | 1 | US
1528396289744 | null | 2 | GB
1528396289744 | null | 4 | IN

**Select from table doesn't work (hangs, no response):**
ksql> select * from countrycodes;


Are there any workarounds for this?  

Is it not possible to join data in confluent/ksql currently?

**Comment by ReddyTunga** [comment]
CREATE STREAM querymaster_st1 (SQL_ID varchar, USERNAME varchar, LAST_ACTIVE_TIME varchar, MODULE varchar, MACHINE varchar, PROGRAM varchar, SQL_TEXT varchar, PARSING_SCHEMA_NAME varchar) WITH (value_format='json', kafka_topic='querymaster' );

CREATE TABLE querymaster_gp AS SELECT sql_id, count(*) FROM querymaster_st1 GROUP BY sql_id;

CREATE STREAM queryall_st1 (DBNAME varchar, SQL_ID varchar, SQL_TEXT varchar, FIRST_LOAD_TIME bigint, USERNAME varchar, LAST_ACTIVE_TIME varchar, PROGRAM varchar, MODULE varchar, MACHINE varchar, ROWS_PROCESSED varchar, COMMAND_TYPE varchar, PARSING_SCHEMA_NAME varchar) WITH (value_format='json', kafka_topic='queryall');

CREATE STREAM QUERY_JOIN_ST1 AS SELECT A.SQL_ID, M.SQL_ID, A.SQL_TEXT, A.USERNAME, A.MACHINE, A.MODULE, A.LAST_ACTIVE_TIME FROM queryall_st1  A LEFT JOIN querymaster_gp M ON A.SQL_ID=M.SQL_ID;

I have done this. It works... Am using confluent 4.1.0 sw pack. 
try using with clause in lower "WITH (value_format='json', kafka_topic='querymaster' )"

**Comment by u-phoria** [comment]
Same problem (Confluent 4.1.1). Replicated @akastanis' example and behaviour (thanks).
Stream queries on `countrycodestream` work fine once `auto.offset.reset` is set to `earliest` as expected.
Table queries on `countrycodes` hang without returning any data.

**Comment by rmoff** [comment]
Above issues are hitting this issue: https://github.com/confluentinc/ksql/issues/1405
