### ISSUE TITLE
restart query which has terminated

### ISSUE THREAD

**Issue by yasinasama** [confluentinc/ksql#1308]
When I stop one query use:
`terminate query_id`
Can I restart this?

**Comment by miguno** [comment]
No, you can't.  Once a query is terminated you must re-create the query if/when needed.

**Comment by miguno** [comment]
Was there a reason or use case that caused you to ask this question?

**Comment by yasinasama** [comment]
Thanks for reply！I just realized that maybe i can restart this query quickly than re-create.Because i must delete the stream/table which was created by this query before re-create.

**Comment by miguno** [comment]
Thanks for clarifying, @yasinasama !
