### ISSUE TITLE
Unify `executeWithRetries` implementation

### ISSUE THREAD

**Issue by hjafarpour** [confluentinc/ksql#1314]
We use `executeWithRetries` in couple of places including in KafkaTopicClient and DataSourceCommand. It's better to have a single implementation that can accept both KafkaFuture and Map of KafkaFuture objects so we can use it in anyplace we need `executeWithRetries`.

**Comment by apurvam** [comment]
See https://github.com/confluentinc/ksql/pull/1277#discussion_r188136251 for context.

**Comment by uurl** [comment]
Hello, could you assign me this issue? Thanks.

**Comment by apurvam** [comment]
@uurl sure. Feel free to pick it up. Thanks!

**Comment by uurl** [comment]
Ready, thanks @hjafarpour @apurvam
