### ISSUE TITLE
Add support for LIMIT to PRINT

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#1316]
`PRINT` statement should provide a way to show just the first <x> messages from a topic. To keep in line with the existing `SELECT` syntax it would make sense to support `LIMIT`

**Comment by miguno** [comment]
@rmoff : The syntax for `PRINT` is:

> PRINT qualifiedName (FROM BEGINNING)? ((INTERVAL | SAMPLE) number)?

Doesn't e.g. the `SAMPLE number` allow you to do what you want?

**Comment by rmoff** [comment]
Well, the docs don't say :) (I have logged an internal issue for this)
When I use it `SAMPLE` appears to show every <x> messages, and doesn't accept non-integers. So on a large topic when I literally want to see just one or two, it's not possible. Hence, `LIMIT` would be usefull.

**Comment by rmoff** [comment]
Just revisiting this - `LIMIT` would also be useful for demos, tutorials etc when we want the command to return control. At the moment `PRINT`, even with `SAMPLE`, will continue to execute and has to be cancelled. Often all we want is to show the first few messages in a topic, which `PRINT 'topic' FROM BEGINNING LIMIT 3;' would be great for

**Comment by theoDiefenthal** [comment]
+1: First steps in KSQL and I just wanted to checkout my existing kafka topics with their very lenghty messages (Lots of characters/lines). Hard to figure out where one message begins and the other ends and using print just immediately pollutes my terminal, even if I directly CTRL+C.

**Comment by rmoff** [comment]
@agavra which release will this be in? 5.2?

**Comment by apurvam** [comment]
@rmoff yes.

**Comment by rmoff** [comment]
https://asciinema.org/a/bS7WQ30WSCYl2DmrSiiNoTyAx
