### ISSUE TITLE
Provide workaround for showing aggregate windows in a SELECT

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#1318]
Currently when performing aggregate queries, if you want to see the aggregate timestamp, you have to persist the query as CTAS and then use `ROWTIME` to get the window: 

```
ksql> CREATE TABLE PURCHASE_COUNT_BY_CITY_PER_30MIN AS SELECT city,COUNT(*) FROM Purchase_enriched WINDOW TUMBLING (SIZE 30 MINUTES) GROUP BY city;

ksql> SELECT TIMESTAMPTOSTRING(ROWTIME, 'yyyy-MM-dd HH:mm:ss') , CITY, PURCHASE_COUNT FROM PURCHASE_COUNT_BY_CITY_PER_30MIN;
2018-05-17 14:30:00 | Paris La Défense | 2
2018-05-17 14:30:00 | Remiremont | 1
```

It would make exploring data in KSQL much easier if there was a way to expose this timestamp as part of a `SELECT` only, without requiring a `TABLE` to be created. Since the timestamp window is there in the result of the `SELECT` query, could we maybe have a session variable that enabled the printing of timestamp windows to the console? Similar to how it's possible to customise the output format betwen tabular, json, etc.

**Comment by mjsax** [comment]
@rmoff is this still an issue?

**Comment by MichaelDrogalis** [comment]
Closing - all pseudocolumns are selectable in both contexts now.
