### ISSUE TITLE
The KSQL window confuse 

### ISSUE THREAD

**Issue by yasinasama** [confluentinc/ksql#1336]
The table click_users_five_seconds created by below way,with window  tumbling(size 5 seconds),and the clickstream was a stream create by clickstream (the example KSQL apply).
`create table click_users_five_seconds as select ip,count(*) from clickstream window tumbling(size 5 seconds) group by ip;`

I got the result below with executing 
`select TIMESTAMPTOSTRING(ROWTIME, 'yyyy-MM-dd HH:mm:ss'),* from click_users_five_seconds ;`

![image](https://user-images.githubusercontent.com/15014408/40410945-96d70444-5ea1-11e8-945a-b349c65f19cd.png)

What I confuse were two rad boxes.The second box seemed belong to window(2018-05-23 07:21:00),but the count(ip) value not begin with 1 Instead of 3 inherited from the result window(2018-05-23 07:20:55).

Does I misunderstand with window or something wrong?

**Comment by cricket007** [comment]
See - https://kafka.apache.org/11/documentation/streams/developer-guide/dsl-api.html#tumbling-time-windows

Those are different windows, so you're counting IPs within that 5 second interval.

If anything, the second box and very last line of that image seem to be the same IP in the same window.

**Comment by agavra** [comment]
Thanks for the question @yasinasama - please let me know if the documentation linked above answered your question. I'm going to close out this ticket in order to help clean up our backlog, but feel free to re-open or reach out to us if there is still some confusion!
