### ISSUE TITLE
Support anonymous top level columns, i.e. JSON Array.

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#1351]
As per: 

https://groups.google.com/forum/#!topic/confluent-platform/XMvBUZEdVTg

If the input topic contains a JSON message that is an array, e.g.

```
[
   {"nested": 1}
]
```

We currently don't have a way to access the JSON data.

Hoping this is fixed by #638

**Comment by rodesai** [comment]
This won't get fixed automatically by the struct work (#638). KSQL still needs some way to know how to map the record value to a column. Some options:
     - If a schema consists of a single column, and the data in the record is not structured (e.g. an avro record, json object), and the data is compatible with the type in the column, then assign the data in the record to that column
     - Add special syntax for specifying that a column maps to the whole record.
     - Have an implicit ROWVALUE column that contains the whole recorded value.

**Comment by miguno** [comment]
@rodesai : Could we address this with a new function similar to EXTRACTJSONFIELD for pulling the data out of the JSON array to get it into a STRUCT, for example?

**Comment by almazik** [comment]
What about a single ARRAY<STRUCT<>> field? Not sure if it will be useful though...
