### ISSUE TITLE
How to run a ksql statement in java application?

### ISSUE THREAD

**Issue by coderztf** [confluentinc/ksql#1352]
I want to run a ksql statement in java application like in ksql cli which could continuously get result .
I tried to run a ksql statement with REST API  , but it couldn't give me results in real-time , if  no LIMIT was specified in the statement . 
Is there the other way to run a ksql statement in java application that can get data in real-time?

**Comment by apurvam** [comment]
Did you have a look at https://docs.confluent.io/current/ksql/docs/api.html#run-a-query-and-stream-back-the-output ?

**Comment by miguno** [comment]
> I tried to run a ksql statement with REST API , but it couldn't give me results in real-time , if no LIMIT was specified in the statement .

Can you elaborate on what your problem was?  The REST API does stream results in real-time, see the link that @apurvam shared above.

> Is there the other way to run a ksql statement in java application that can get data in real-time?

FYI: Beyond the existing KSQL REST API, we are also collecting user feedback on https://github.com/confluentinc/ksql/issues/734 (using KSQL as a library).

**Comment by coderztf** [comment]
@apurvam @miguno 
thx , it works ! That's my fault ! I used postman to send a post request , and didn't give me the result in real-time, but if I send request by my java application, it does work in real-time.

**Comment by miguno** [comment]
Great, happy to hear it works now!

**Comment by Worm4047** [comment]
Hi, I am trying to make a select query to ksql api but no result is being returned. I tried running that command through command prompt, then it displays the output. Can you help me out regarding that

**Comment by miguno** [comment]
@Worm4047 : Could you please create a separate ticket for this?  Also, please provide us with more information / context on your environment.  Which version of KSQL? Which exact SQL query?  What is the command you use to run the query against the KSQL REST API?  What is the input data?  What information is in the KSQL log files? etc.

**Comment by mohitagrawal-crest** [comment]
@coderztf  could you please tell me how did it work for you in java.
Thanks

**Comment by rahuladatt** [comment]
@miguno @coderztf Can you please suggest  me how to write the ksql quires in java code. I checked every were for a example like this, but i did't get any suggestion. 

Please any one help. I am working in a use case where this ksql quires in java will help me more.   

Thanks.

**Comment by mayankbharti26** [comment]
> @miguno @coderztf Can you please suggest me how to write the ksql quires in java code. I checked every were for a example like this, but i did't get any suggestion.
> 
> Please any one help. I am working in a use case where this ksql quires in java will help me more.
> 
> Thanks.

@rahuladatt I am also looking for same, Have you found the solution?
