### ISSUE TITLE
Add scalar functions for data-masking (anonymization)

### ISSUE THREAD

**Issue by blueedgenick** [confluentinc/ksql#1357]
Capturing a couple of recent asks for functions to anonymize or mask either the entire or partial content of specific fields from a record.

Common use-case examples include substituting `XXXX` for portions of a credit card or account number.

**Comment by miguno** [comment]
This is also useful in the context of GDPR.

**Comment by stefanofrigerio** [comment]
I think also a salted hash (field A salted with field B) will be useful.

**Comment by ZacharyWhitley** [comment]
No need for anything specific for anonymization. A simple string function would do like Apache Commons StringUtils overlay method. https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html#overlay-java.lang.String-java.lang.String-int-int-

I think most of what's in StringUtils would be a good candidate for a UDF. Any thoughts about namespacing functions? It's going to get crowded in there really quick.

**Comment by blueedgenick** [comment]
closed by PR 1482
