### ISSUE TITLE
Topics associated to a dropped stream persists even after being explicitly dropped

### ISSUE THREAD

**Issue by rugging24** [confluentinc/ksql#1364]
Hello ,
I recently created a number of streams and associating tables with KSQL. Everything works as expected except the cleanups. Each time a discard off a table or stream and delete the associating topics, they reappear after restarting the ksql server. Looking at the metadata topic for ksql _confluent-ksql-xxx topic , it shows the streams/table should be deleted in the correct precedence.
Could someone please point out to me what I might be doing wrong ?

thanks.

**Comment by agavra** [comment]
This has been fixed in KSQL versions 5.3+ - we no longer create any topics during startup as they are created on the rest server only when you first issue the command! Please feel free to re-open if the issue persists in more recent KSQL versions.
