### ISSUE TITLE
UDAFs that return the First and Last data record in a window

### ISSUE THREAD

**Issue by sgulati89** [confluentinc/ksql#1373]
Hi,
Currently, KSQL does provide any UDAF for getting the first and last element  in window. 

I can create these UDAFs . Please suggest which branch  should I use to develop?

**Comment by sgulati89** [comment]
Please reply

**Comment by apurvam** [comment]
Have you seen https://github.com/confluentinc/ksql/blob/master/CONTRIBUTING.md ?

Also, you can use this as a reference: https://github.com/confluentinc/ksql/pull/1467

**Comment by blueedgenick** [comment]
There was also some discussion of this feature earlier over on #1128

**Comment by miguno** [comment]
This is related to the recently merged support for returning the **start time** and **end time** of a window, see https://github.com/confluentinc/ksql/pull/1993.

In contrast, this ticket is about the **first data record** and the **last data record** in the window.

**Comment by agavra** [comment]
Closing as a duplicate of https://github.com/confluentinc/ksql/issues/1128, please follow that ticket for any updates!
