### ISSUE TITLE
doesn't support Binary field type ?

### ISSUE THREAD

**Issue by goldenKeyHu** [confluentinc/ksql#1377]
Hi, ALL:
      I have went through the document of KSQL，I found binary field type is not supported，So,What should do if I get a binary field of my table. I'm Looking forward to your reply.

**Comment by miguno** [comment]
You can use `BIGINT` for bytes.  Have you tried that?

**Comment by apurvam** [comment]
Seems like a dup of #1282

**Comment by goldenKeyHu** [comment]
@miguno 
 Mr Noll，Thanks for ur reply，May I know how long the bigint type in KSQL is，I'd like to store business object as binary，which can be as large as 12Mb

**Comment by miguno** [comment]
Duplicate of https://github.com/confluentinc/ksql/issues/1742.
