### ISSUE TITLE
KSQL parse error throws NPE

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#1387]
The following statement should, of course, have a table or stream specified - but the error given is a NPE. 

```
ksql> SELECT FOO;
io.confluent.ksql.parser.exception.ParseFailedException
Caused by: java.lang.NullPointerException
ksql>
```

At best, let's tell the user they've missed the object from which to select. At very least, report that it's not valid SQL (and don't throw the NPE)

**Comment by rodesai** [comment]
This doesn't happen on 5.1.x:

```
ksql> SELECT FOO;
line 1:11: mismatched input ';' expecting {',', 'FROM', 'INTO'}
Caused by: org.antlr.v4.runtime.InputMismatchException
ksql>
```
