### ISSUE TITLE
Add a data type reference to documentation

### ISSUE THREAD

**Issue by rodesai** [confluentinc/ksql#1391]
We should add a reference that details the different data types and how to use them. The hive docs are a good example: https://www.cloudera.com/documentation/enterprise/5-8-x/topics/impala_datatypes.html

This reference should also specify how to declare KSQL schemas for different formats (a.g. AVRO, JSON), and how each KSQL type is translated to the underlying format when serialized. The reference should also specify how underlying schemas are inferred for formats that support schema inference (currently just AVRO).

**Comment by miguno** [comment]
cc @JimGalasyn (goes back to KSQL docs refactoring)

**Comment by JimGalasyn** [comment]
@rodesai @miguno This is defs high on the list for refactoring the KSQL docs!

**Comment by MichaelDrogalis** [comment]
This is done. :-) https://docs.ksqldb.io/en/latest/reference/sql/data-types/
