### ISSUE TITLE
Do not support in clause or double left join in KSQL

### ISSUE THREAD

**Issue by yasinasama** [confluentinc/ksql#1392]
Stream A: 
```
s1 varchar
s2 varchar
```

Table B:
`t1 varchar`

Can I filter the records that A.s1 in B.t1 OR A.s2 in B.t1?

 I try below SQLs (like do in mysql) but both failed:

```
select * from A where A.s1 in (select t1 from B) or A.s2 in (select t1 from B)
select * from A left join B on A.s1=B.t1 left join B BB on A.s2=BB.t1 where B.t1 is not null or BB.t1 is not null
```
Any magic solution for this situation?

**Comment by rodesai** [comment]
The INSERT INTO statement introduced in the June preview release should solve this for you:

```sql
CREATE STREAM A_ENRICHED AS SELECT * FROM A LEFT JOIN B ON A.s1=B.t1;
INSERT INTO A_ENRICHED  SELECT * FROM A LEFT JOIN B ON A.s2=B.t1 WHERE A.s2 != A.s1
```

INSERT INTO takes the result of a query and writes it into an existing stream. The example statements above gives you a stream called A_ENRICHED that contains all records from A where s1 or s2 match B.t1. =

**Comment by yasinasama** [comment]
Thanks @rodesai !

And the INSERT INTO statement can be a completely solution for this situation.Very creative !!

By the way,why do not we support the IN clause OR the double/or more LEFT JOIN  for KSQL?They should be useful in some situation.Whether they will appear in future releases or are not suitable for support because of some reasons.Thanks for your answer!
