### ISSUE TITLE
How to show window end from windowed key

### ISSUE THREAD

**Issue by ChenShuai1981** [confluentinc/ksql#1404]
When I query windowed table, it just shows window start time but no window end time, how can I achieve it? I found a related pull request https://github.com/confluentinc/ksql/pull/198/commits/0384d3a7de861d4143faff257d218527b00444ac. 
But not understand why hide window end.

1528708320000 | 2557 : Window{start=1528708320000 end=-} | 2557 | 3 | 1528708320000

**Comment by rodesai** [comment]
Currently the window end time is not present in the output of a windowed aggregation. You can compute it from the window size of the source query.

**Comment by agavra** [comment]
I believe you can use `WINDOWSTART()` and `WINDOWEND()` UDAFs to create columns with these values:
```
 CREATE TABLE LOGIN_BY_WINDOW AS SELECT windowStart() as windowStart, windowEnd() as windowEnd, username, count(*) as COUNT FROM LOGINS WINDOW HOPPING (SIZE 1 minute, ADVANCE BY 1 SECOND) GROUP BY username;
```
Then you can select windowstart/windowend from the records that are produced. Feel free to re-open this ticket if that solution doesn't work for you!
