### ISSUE TITLE
variable length lists

### ISSUE THREAD

**Issue by r2evans** [confluentinc/ksql#1413]
Is there a way to easily deal with variable-length lists in a stream?

For example, if a stream contained data like

```json
{"id":1,"quux":[{"x":1,"y":2},{"x":3,"y":4},{"x":5,"y":6}]}
```

(where the number of dict-entries in `"quux"` was not fixed), is there a way to iterate over or somehow process all elements? I imagine one way would be to have another JSON helper function that could expand this into:

```json
{"id":1,"quux":{"x":1,"y":2}}
{"id":1,"quux":{"x":3,"y":4}}
{"id":1,"quux":{"x":5,"y":6}}
```

Perhaps a function such as:

```sql
create stream newstream as
select JSONEXPLODE('id','quux') as ...
```

where I can see two possible interpretations of the arguments:

1. all of them except one are scalars, and the remaining is a list; or
2. all are either scalars, lists of length 1 (effectively scalars), or lists of length `n` where `n` is the same for all lists (essentially a "zipper").

Thanks.

**Comment by rmoff** [comment]
Related: #1324 , #527

**Comment by r2evans** [comment]
@rmoff, I think this is enough like #527 to be considered a duplicate, so I'll close. Feel free to reopen (or comment) if you think there is something to save here. Thanks.
