### ISSUE TITLE
Can convert Stream to Table directly ?

### ISSUE THREAD

**Issue by yunhappy** [confluentinc/ksql#1419]
like stream api do this:
https://docs.confluent.io/current/streams/faq.html#how-can-i-convert-a-kstream-to-a-ktable-without-an-aggregation-step

**Comment by rodesai** [comment]
In lieu of KSQL syntax to accomplish this directly you could declare a table over the underlying topic like so:

```CREATE TABLE <name> (<schema>) WITH (kafka_topic='stream topic', ...)```

**Comment by rmoff** [comment]
@yunhappy Does the syntax that @rodesai suggests match what you had in mind? Please reopen if not. thanks.
