### ISSUE TITLE
drop table hang issue

### ISSUE THREAD

**Issue by ChenShuai1981** [confluentinc/ksql#1420]
I created many tables by ksql but found 2 of them can NOT be dropped due to hang. 
Question: if I deleted topic of table backend, can I delete the table? Is there any "force" option to drop table/stream by ksql?

```
CLI v0.3, Server v0.3

ksql> drop table DEV_MONITOR_RULESET_2557_1440_58_TABLE;
_
```

**Comment by miguno** [comment]
First, may I suggest to upgrade to the latest stable KSQL version (4.1) and trying again?  You are using a very old, preview version.

**Comment by agavra** [comment]
Closing this ticket out as part of a backlog cleanup effort - if this issue persists on more recent KSQL versions please feel free to re-open or submit a new ticket!

**Comment by big-andy-coates** [comment]
Possibly related to https://github.com/confluentinc/ksql/issues/860

We'd need more info to investigate more...
