### ISSUE TITLE
String index out of range -1

### ISSUE THREAD

**Issue by aswiftproduction** [confluentinc/ksql#1432]
After running confluent start from the CLI, I try to start a KSQL session, but as soon as I run KSQL or KSQL local my terminal is instantly bombarded with a never-ending stream of "String index out of range -1" 
<img width="791" alt="screen shot 2018-06-13 at 6 19 35 pm" src="https://user-images.githubusercontent.com/10914325/41381612-9c19e976-6f36-11e8-9147-28c5229e8b33.png">

**Comment by aswiftproduction** [comment]
@rmoff I am using Confluent Open Source 4.1.1

The issue resolved itself after I ran confluent destroy following me forcefully shutting down my vm. I could not run confluent status because the terminal would not respond after going into this endless loop, Ctrl-C would not shut down the process, I do think suspending with Ctrl-Z worked.

 I am following your guide Processing with Apache Kafka and KSQL—Part 1: Filtering. I am utilizing the syslog connect plugin to build out an analytics tool, it seems as though Jeremy Custenborder took the plugin off of his GitHub because the link is dead in the article, do you know of any alternatives to consuming syslogs or should I just write the connector myself?

**Comment by rmoff** [comment]
@aswiftproduction I'm glad it's working for you now. 
Re. @jcustenborder's  syslog connector, keep an eye on hub.confluent.io - it should be back soon
