### ISSUE TITLE
Fix misleading error if schema is not supported

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#1436]
Per https://confluentcommunity.slack.com/archives/C6UJNMY67/p1528987470000729?thread_ts=1528981250.000585&cid=C6UJNMY67

If KSQL does not support a schema, it throws this error: 

    Could not fetch the AVRO schema from schema registry. Cannot find correct type for avro type: my_topic.Value

This is confusing, as we say "Could not fetch the AVRO schema from schema registry", even though we *have* fetched the schema. 

We should remove this part of the error, and replace it with something like "This Avro schema is not yet supported by KSQL: <reason>"

**Comment by rmoff** [comment]
Related ? #707

**Comment by apurvam** [comment]
@rmoff is this addressed by #1569 ?

**Comment by rmoff** [comment]
@apurvam yes I think so.
