### ISSUE TITLE
Real time issues using confluent KSQL connector:

### ISSUE THREAD

**Issue by shivasagar4d** [confluentinc/ksql#1437]
1.	Date functions are not available for calculations.(For e.g.: we don’t have the capability retrieve the last 15,20,30 min of streaming data).
2.	Very limited visuals are applicable once we choose real-time connectivity.(for E.g.  Map would recognize only based n latitude and longitude but not on State ,country, zip code etc., No bubble, charts,) 
3.	How do you pass parameters from arcadia to confluent Kafka? For E.g.: if I want to get the history of records KSQL table which are not streaming, I would need to set offset parameter to earliest by using command  'auto.offset.reset' = 'earliest';
4.	No option to create a table/dataset/materializedview,logicalview  from the custom queries(SQL) which is available in other connectors. 
5.	Analytical views are not applicable for this connector. we don’t see any option to create a summarized table/view and get the detail data when I drill through.

Generic Issues with Real-time and other connectors(Hive/Arcadia):

1.	How do you enable hierarchies in Arcadia. For e.g.: if I define an hierarchy and define levels, we do not see any option to enable drill up and drilldown once we have the hierarchies created.
2.	No option to enable filters as prompts to individual visuals. Option is available only at dashboard level which would apply to all the visual at once.
3.	No option to define the conditional styles(for e.g.: To define the threshold value and change the color in the visual based on the threshold value)
4.	How do you restrict the detail level data to display only selected columns rather than all columns from the table.
5.	No option to integrate multiple visuals into a single visual.(For E g: Combine Rich text visual to Pie chart visual for effective presentation)

**Comment by rmoff** [comment]
@shivasagar4d thanks for raising this issue. Most of these seem related to Arcadia's tool - you're better off raising them there. I'm going to close this for now; if there are specific issues for KSQL then please do raise them (and better as one per item, making it easier to discuss & track).
