### ISSUE TITLE
Support collect_list function to collect records into a list in group by

### ISSUE THREAD

**Issue by cloudbow** [confluentinc/ksql#1447]
GroupBy is used in general case to group by multiple columns and then select the non grouped records into a collection . Something like the following. 

Table - m  with 6 records 
```
x |  y|  z| a|  b| c
=====================
x1| y1| z1| a1| b1| c1
x1| y1| z1| a2| b2| c2 

```
and the final table after group by needs to be like

```
x|   y|  z| collect_list_a, collect_list_b, collect_list_c
====================================
x1| y1| z1| [a1,a2] | [b1,b2] | [c1,c2]
```

This can be created using a single aggregate function like collect_list.
```
e.g.: select x,y,z, collect_list(a), collect_list(b), collect_list(c) from m group by x,y,z
```

**Comment by agavra** [comment]
The newer versions of KSQL have this UDAF (collect_list)! Feel free to re-open this ticket if that UDAF doesn't fit your needs.
