### ISSUE TITLE
KSQL does not support nested Avro; misleading error message

### ISSUE THREAD

**Issue by swamigee** [confluentinc/ksql#1450]
When using Postgres Debezium connector, AvroConverter creates subject in schema registry with '-' 
 e.g locationdb.location_data.**customers-value**
 
 But when creating a stream for topics in KSQL, getting error:
  Could not fetch the AVRO schema from schema registry. Cannot find correct type for avro type: locationdb.cust.customers.**Value**
**KSQL server uses '.'notation with an upper case Value.**

**Getting error when creating a stream in KSQL cli.**

```
Caused by: org.apache.kafka.common.errors.SerializationException: Error registering Avro schema: {"type":"record","name":"Key","namespace":"locationdb.location_data.state_code","fields":[{"name":"state_code","type":"string"}],"connect.name":"locationdb.location_data.state_code.Key"}
Caused by: io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException:
Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: (sun.net.www.protocol.http.HttpURLConnection$HttpInputStream); line: 1, column: 2]; error code: 50005

``` 
In Kql cli:
```
CREATE STREAM customersstream \
  WITH (KAFKA_TOPIC='locationdb.location_data.customers', \
        VALUE_FORMAT='AVRO');
```

**The schema is not nested. The topic name created looks like nested.** Customers table is a simple one, has 3 columns
Schema in Schema Registry:
http://schema-registry-host:8081/subjects/locationdb.location_data.customers-value/versions/2

`{"subject":"locationdb.location_data.customers-value","version":2,"id":686,"schema":"{\"type\":\"record\",\"name\":\"Envelope\",\"namespace\":\"locationdb.location_data.customers\",\"fields\":[{\"name\":\"before\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Value\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"first_name\",\"type\":\"string\"},{\"name\":\"last_name\",\"type\":\"string\"},{\"name\":\"email\",\"type\":\"string\"}],\"connect.name\":\"locationdb.location_data.customers.Value\"}],\"default\":null},{\"name\":\"after\",\"type\":[\"null\",\"Value\"],\"default\":null},{\"name\":\"source\",\"type\":{\"type\":\"record\",\"name\":\"Source\",\"namespace\":\"io.debezium.connector.postgresql\",\"fields\":[{\"name\":\"version\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"ts_usec\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"txId\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"lsn\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"snapshot\",\"type\":[{\"type\":\"boolean\",\"connect.default\":false},\"null\"],\"default\":false},{\"name\":\"last_snapshot_record\",\"type\":[\"null\",\"boolean\"],\"default\":null}],\"connect.name\":\"io.debezium.connector.postgresql.Source\"}},{\"name\":\"op\",\"type\":\"string\"},{\"name\":\"ts_ms\",\"type\":[\"null\",\"long\"],\"default\":null}],\"connect.name\":\"locationdb.location_data.customers.Envelope\"}"}
`

**Comment by rmoff** [comment]
Looking at the schema, it is nested, which KSQL does not yet support

```
{
  "type": "record",
  "name": "Envelope",
  "namespace": "locationdb.location_data.customers",
  "fields": [
    {
      "name": "before",
      "type": [
        "null",
        {
          "type": "record",
          "name": "Value",
          "fields": [
            {
              "name": "id",
              "type": "int"
            },
            {
              "name": "first_name",
              "type": "string"
            },
            {
              "name": "last_name",
              "type": "string"
            },
            {
              "name": "email",
              "type": "string"
            }
          ],
          "connect.name": "locationdb.location_data.customers.Value"
        }
      ],
      "default": null
    },
    {
      "name": "after",
      "type": [
        "null",
        "Value"
      ],
      "default": null
    },
    {
      "name": "source",
      "type": {
        "type": "record",
        "name": "Source",
        "namespace": "io.debezium.connector.postgresql",
        "fields": [
          {
            "name": "version",
            "type": [
              "null",
              "string"
            ],
            "default": null
          },
          {
            "name": "name",
            "type": "string"
          },
          {
            "name": "ts_usec",
            "type": [
              "null",
              "long"
            ],
            "default": null
          },
          {
            "name": "txId",
            "type": [
              "null",
              "int"
            ],
            "default": null
          },
          {
            "name": "lsn",
            "type": [
              "null",
              "long"
            ],
            "default": null
          },
          {
            "name": "snapshot",
            "type": [
              {
                "type": "boolean",
                "connect.default": false
              },
              "null"
            ],
            "default": false
          },
          {
            "name": "last_snapshot_record",
            "type": [
              "null",
              "boolean"
            ],
            "default": null
          }
        ],
        "connect.name": "io.debezium.connector.postgresql.Source"
      }
    },
    {
      "name": "op",
      "type": "string"
    },
    {
      "name": "ts_ms",
      "type": [
        "null",
        "long"
      ],
      "default": null
    }
  ],
  "connect.name": "locationdb.location_data.customers.Envelope"
}
```

The error message that you're getting is very misleading, I agree, and there is an open issue for this (#1436). 

Until KSQL does support nested Avro (which will be soon) you can work around this issue by flattening your schema using Debezium's `io.debezium.transforms.UnwrapFromEnvelope` Single Message Transform - there's an example of this in action here: https://rmoff.net/2018/03/24/streaming-data-from-mysql-into-kafka-with-kafka-connect-and-debezium/
