### ISSUE TITLE
Error when partitions or replication is a mismatch is ambiguous

### ISSUE THREAD

**Issue by cjmatta** [confluentinc/ksql#1454]
When the number of partitions or replicas specified in a statement is different from those required by KSQL you get the following error:

`io.confluent.ksql.exception.KafkaTopicException: Topic 'ratings-with-customer-data' does not conform to the requirements Partitions:1 v 4. Replication: 1 v 1`

It's not clear which number is the required and which is the specified, it would be clearer like this:

`io.confluent.ksql.exception.KafkaTopicException: Topic 'ratings-with-customer-data' does not conform to the requirements Partitions required: 1, Partitions specified: 4; Replication required: 1, Replication specified: 1`

**Comment by rmoff** [comment]
Dup of #865
