### ISSUE TITLE
Change KsqlFunction so we can get the return type

### ISSUE THREAD

**Issue by hjafarpour** [confluentinc/ksql#1460]
Now that we have Struct type we need to be able to specify the return type for KsqlFunction such that we have full schema (including the nested fields for struct case) of the return type.

**Comment by rodesai** [comment]
It needs to be possible to determine this as a function of the literal arguments. E.g., the function should be able to implement an interface that, given the schemas of its arguments and values of any literal arguments returns the return schema. Right?

**Comment by dguy** [comment]
@rodesai that is correct

**Comment by dguy** [comment]
This has been fixed in the UDF Prs
