### ISSUE TITLE
Operator "<=" not allowed on reference operands

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#1474]
Reproduced in `KSQL 5.0.0-SNAPSHOT` and `KSQL 4.1.1`

KSQL throws an error if a predicate is attempted on a MAP. 

Source data: 

    echo '{"id":"a42","category":"foo","timestamp":"2018-06-21 10:04:57 BST","deviceID":42,"deviceProperties":{"status":"false","foo":"bar"}}'| \
    kafkacat -b localhost:9092 -t test_map2 -P

Define stream: 

    CREATE STREAM fakeData22 (Id VARCHAR, category VARCHAR, timeStamp VARCHAR, deviceID INTEGER, deviceProperties MAP<VARCHAR, VARCHAR>) WITH (KAFKA_TOPIC='test_map2', VALUE_FORMAT='JSON');

Standard predicate: 

    ksql> select * from fakedata22 where deviceid=42;
    1529572405759 | null | a42 | foo | 2018-06-21 10:04:57 BST | 42 | {foo=bar, status=false}

MAP predicate: 

```
ksql> select * from fakedata22 where deviceproperties['foo']='bar';
Failed to generate code for SqlPredicate.filterExpression: (FAKEDATA22.DEVICEPROPERTIES['foo'] = 'bar')schema:org.apache.kafka.connect.data.SchemaBuilder@6636ccb2isWindowedKey:false
Caused by: Line 1, Column 168: Operator "<=" not allowed on reference operands
```

**Comment by big-andy-coates** [comment]
How does this differ from this PR:

https://github.com/confluentinc/ksql/pull/1476

That suggests this does work on master, (and I tested 5.0 too)?  It definitely doesn't work on 4.1.

**Comment by rmoff** [comment]
@big-andy-coates just catching up on this - it is the same issue, we both logged it :) If it works on master, then we can close this 👍
