### ISSUE TITLE
Support of Join predicate to non table keys.

### ISSUE THREAD

**Issue by kumarhanu** [confluentinc/ksql#1485]
Came to know that currently the join predicate can only be on equality of the respective table keys. Will it be extended to non table keys also? When it will be available?

**Comment by rmoff** [comment]
For now, you can use KSQL to re-partition the table's topic onto the key on which you do want to join. There's an example of this here https://github.com/confluentinc/quickstart-demos/blob/master/ksql-workshop/ksql-workshop.adoc#102-re-key-customers-topic

**Comment by mjsax** [comment]
Tracked via https://github.com/confluentinc/ksql/issues/4424

Closing this ticket.
