### ISSUE TITLE
REST API: SELECT result should include columns metadata into answer

### ISSUE THREAD

**Issue by alexott** [confluentinc/ksql#1487]
Right now, when performing `SELECT` on the data via REST API, the answer doesn't contain any metadata about columns - only the values:

```
> curl -H 'Content-Type: application/json' http://localhost:8088/query -d '{"ksql":"select id,text,lang from tweets limit 5;"}' 
{"row":{"columns":[1010831441544994817,"@alokdesh @the_hindu @tragicosmicomic https://t.co/KfLkWq6NNB","und"]},"errorMessage":null}
{"row":{"columns":[1010831441553285122,"@towawannko12345 わーい＼＼\\\\٩( 'ω' )و //／／\n恋人だろうと女子会だろうと楽し ければリア充の仲間入りだからね！w","ja"]},"errorMessage":null}
{"row":{"columns":[1010831441536614400,"if You are from CASTE of 90% WORKING CLASS❗️TAXES & FEES\uD83E\uDDD0is APPLIED  2 YOU @ long You Live❗️if You are from CASTE o… https://t.co/dcaLPjP0WN","en"]},"errorMessage":null}
```

This makes integration with external systems much harder:

- in case of `SELECT *` you can obtain list of columns from the table's description, but in the worse case you'll need to perform an additional REST call on every `SELECT` as table's structure can change
- in case of `SELECT column, column, ...` you'll need to parse SELECT statement itself, and this could be even harder in case of supporting of aliases, etc.

It would be nice to extend the output of the query API to include necessary metadata about returned columns.

P.S. I'm trying to build an interpreter for Apache Zeppelin...

**Comment by apurvam** [comment]
I believe this feature request is a dup of https://github.com/confluentinc/ksql/issues/1343

Please close if you agree.

**Comment by alexott** [comment]
Yes, it's for 1st case that I described, but not for second... But I'll close mine in favor of already existing

Thank you!
