### ISSUE TITLE
Query REST API: Don't report error when reaching LIMIT

### ISSUE THREAD

**Issue by alexott** [confluentinc/ksql#1488]
Right now, if the query uses `LIMIT` clause, the last row is always an error:

```
{"row":null,"errorMessage":{"message":"LIMIT reached for the partition.","stackTrace"....
```

Although, from SQL point of view that's isn't an error. It would be nice to hide this from the user, and simply stop delivering the data, reporting only the actual errors.

**Comment by miguno** [comment]
@rodesai : Is this still the case in KSQL 5.0+?

**Comment by rodesai** [comment]
Nope - we now return a field "finalMessage" that indicates that the limit has been reached.

**Comment by alexott** [comment]
Yes, it's fixed, and I'm using it in the updated KSQL integration

**Comment by miguno** [comment]
Thanks for reporting back, @alexott !
