### ISSUE TITLE
Error issuing GET to KSQL server

### ISSUE THREAD

**Issue by todorovc** [confluentinc/ksql#1493]
With KSQL  CLI v4.1.1 (local installation) I have the following error.

```
**************** WARNING ******************
Remote server address may not be valid:
Error issuing GET to KSQL server
Caused by: URI is not absolute
Caused by: URI is not absolute
*******************************************
```

It is a clean UBUNTU installation  (sudo apt-get install confluent-platform-2.11)

Steps:
```
$ ksql

ksql> list topics;
```

**Comment by apurvam** [comment]
How did you start your server? How did you start your client?

**Comment by seua** [comment]
Same problem, start by 
./bin/ksql-server-start /****/ksql-server.properties

**Comment by miguno** [comment]
@seua : Can you share the contents of your `ksql-server.properties`?

**Comment by todorovc** [comment]
Hi,
It was fixed when sufficient permissions were granted to kafka users and proper firewall settings.

Platform OS debian-9  vagrant and puppet 3.5

**Comment by miguno** [comment]
Thanks for sharing the resolution of your problem, @todorovc !  Closing this ticket.
