### ISSUE TITLE
LEFT JOIN intermittently fails to return matching values

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#1510]
Based on [steps here](https://github.com/confluentinc/ksql-workshop/blob/master/ksql-workshop.adoc) and using docker image `confluentinc/ksql-cli:5.0.0-beta30` one of the workshop participants found that they would intermittently get failures in the join when they added the join key into the `SELECT` criteria. The below session output is in time order, with no other commands run in between: 

This works: 
```
ksql> SELECT R.MESSAGE, C.FIRST_NAME, C.LAST_NAME \
> FROM RATINGS R LEFT JOIN CUSTOMERS C \
> ON R.USER_ID = C.ID \
> LIMIT 5;
your team here rocks! | Mirilla | Orwin
why is it so difficult to keep the bathrooms clean ? | Gianina | Mixhel
is this as good as it gets? really ? | Annemarie | Arent
Surprisingly good, maybe you are getting your mojo back at long last! | Mirilla | Orwin
worst. flight. ever. #neveragain | null | null
Limit Reached
Query terminated
```

User then wants to see the `USER_ID` for which a single `null` was returned above, so adds `R.USER_ID` to the `SELECT`—now _none_ of the left join (`CUSTOMERS`) values return: 

```
ksql> SELECT R.MESSAGE,R.USER_ID, C.FIRST_NAME, C.LAST_NAME \
> FROM RATINGS R LEFT JOIN CUSTOMERS C \
> ON R.USER_ID = C.ID \
> LIMIT 5;
your team here rocks! | 3 | null | null
why is it so difficult to keep the bathrooms clean ? | 8 | null | null
is this as good as it gets? really ? | 1 | null | null
Surprisingly good, maybe you are getting your mojo back at long last! | 3 | null | null
worst. flight. ever. #neveragain | 18 | null | null
Limit Reached
Query terminated
```

That's odd, let's rerun the original query - nope, looks fine, there's definitely join results:

```
ksql> SELECT R.MESSAGE, C.FIRST_NAME, C.LAST_NAME \
> FROM RATINGS R LEFT JOIN CUSTOMERS C \
> ON R.USER_ID = C.ID \
> LIMIT 5;
your team here rocks! | Mirilla | Orwin
why is it so difficult to keep the bathrooms clean ? | Gianina | Mixhel
is this as good as it gets? really ? | Annemarie | Arent
Surprisingly good, maybe you are getting your mojo back at long last! | Mirilla | Orwin
worst. flight. ever. #neveragain | null | null
Limit Reached
Query terminated
```

Add the user id column back in - we get join results this time: 
```
ksql> SELECT R.MESSAGE,R.USER_ID, C.FIRST_NAME, C.LAST_NAME \
> FROM RATINGS R LEFT JOIN CUSTOMERS C \
> ON R.USER_ID = C.ID \
> LIMIT 5;
your team here rocks! | 3 | Mirilla | Orwin
why is it so difficult to keep the bathrooms clean ? | 8 | Gianina | Mixhel
is this as good as it gets? really ? | 1 | Annemarie | Arent
Surprisingly good, maybe you are getting your mojo back at long last! | 3 | Mirilla | Orwin
worst. flight. ever. #neveragain | 18 | null | null
Limit Reached
Query terminated
```

Re-run it - now we don't
```
ksql> SELECT R.MESSAGE,R.USER_ID, C.FIRST_NAME, C.LAST_NAME \
> FROM RATINGS R LEFT JOIN CUSTOMERS C \
> ON R.USER_ID = C.ID \
> LIMIT 5;
your team here rocks! | 3 | null | null
why is it so difficult to keep the bathrooms clean ? | 8 | null | null
is this as good as it gets? really ? | 1 | null | null
Surprisingly good, maybe you are getting your mojo back at long last! | 3 | null | null
worst. flight. ever. #neveragain | 18 | null | null
Limit Reached
Query terminated
```

and now we don't: 
```
ksql> SELECT R.MESSAGE,R.USER_ID, C.FIRST_NAME, C.LAST_NAME \
> FROM RATINGS R LEFT JOIN CUSTOMERS C \
> ON R.USER_ID = C.ID \
> LIMIT 5;
your team here rocks! | 3 | Mirilla | Orwin
why is it so difficult to keep the bathrooms clean ? | 8 | Gianina | Mixhel
is this as good as it gets? really ? | 1 | Annemarie | Arent
Surprisingly good, maybe you are getting your mojo back at long last! | 3 | Mirilla | Orwin
worst. flight. ever. #neveragain | 18 | null | null
Limit Reached
Query terminated
ksql>
```

**Comment by apurvam** [comment]
Followed up offline. In this case the table data is being populated after the stream data. This increases the likelihood of null joins because records are processed in timestamp order as far as possible. So the stream data will be processed first, find no matching table records, and hence emit a null join.

This is not 100% deterministic. So it could happen that the table records get processed first some of the time. Hence the inconsistency in the output above.

The solution is to always produce the table data first, and then the stream data.

**Comment by apurvam** [comment]
I am going to close this for now, as it isn't a new issue.

**Comment by ftison** [comment]
I don’t understand the reason why this behavior is considered correct.
Maybe you can point me some resource to understand this Kafka behavior ?

**Comment by apurvam** [comment]
It isn't considered correct, but has to do with the mechanics of streaming joins. There is some work being considered to mitigate the issue, and those options are being discussed here: https://issues.apache.org/jira/browse/KAFKA-3514

But on the limit, when you are at the end of the log, or if you have out of order data, you are going ot have some amount of null joins in a non deterministic fashion.
