### ISSUE TITLE
Headless KSQL to support schema inference (Avro)

### ISSUE THREAD

**Issue by miguno** [confluentinc/ksql#1530]
Schema inference doesn't work when using headless KSQL. For example, when your input data is in Avro format, you must still enter column names/types manually  (when KSQL is run in headless config).

The problem with headless (non-interactive mode) is that the engine _parses_ all the queries in the set up front, and fails if any of the fields are not found in the meta store. The schema inference is done during _execution_, which happens _after_ parsing. So if a subsequent query refers to an inferred field, it will fail with the parse exception. 

* The workaround is to manually specify the columns.
* The solution is to parse and execute queries one by one in all modes.

# Related Issues

We also have other issues because of this dichotomy between the way our interactive and non-interactive modes operate.

- https://github.com/confluentinc/ksql/issues/1320 (KSQL in headless mode doesn't do the same validation on input queries as the interactive mode)
- https://github.com/confluentinc/ksql/issues/1031 (Avro limitation for commands in `run script` versus interactive)

**Comment by miguno** [comment]
cc @ybyzek @rmoff

**Comment by rmoff** [comment]
This is an important thing for us to fix to enable people to painlessly move from dev through to production.

**Comment by big-andy-coates** [comment]
+1 from me - this is a biggie for production.

**Comment by yunhappy** [comment]
+1 from me , 
offset set to earliest can not work ?

**Comment by miguno** [comment]
@yunhappy : Please upvote (+1 / thumbs-up) the first comment in this thread, this way we can track the number of upvotes more easily.

**Comment by big-andy-coates** [comment]
This is in direct conflict with issue https://github.com/confluentinc/ksql/issues/2205.

The issue with supporting avro field inference in headless mode is that the schema could change over time. So we might start KSQL only to find the schema has changed, with columns added / removed.  How should KSQL handle such a change? 

Currently, in interactive mode, the schema is queried _once_ and then baked into the command topic.  We could support something similar for headless. I know @rodesai is looking to store other system metadata in a topic in headless mode. Maybe this could be too.

Alternatively, we can look at _supporting_ schema evolution in both headless and interactive. But this is a larger piece of work and probably a more long term goal / feature.

**Comment by dhanasgit** [comment]
+1

**Comment by miguno** [comment]
Closing this issue. If there are future requests similar to this, please reopen or create a new issue.

**Comment by miguno** [comment]
Closing this issue. If there are future requests similar to this, please reopen or create a new issue.
