### ISSUE TITLE
RUN SCRIPT error on missing file needs improving

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#1534]
```
ksql> RUN SCRIPT '/foo/bar';
 Could not read statements from file: /foo/bar. Details: /foo/bar
Caused by: /foo/bar
ksql>
```

The `Details` and `Caused by` don't really enlighten the user. Can we float up to the user the reason the filesystem reported here? (not found, permissions, etc)

**Comment by hjafarpour** [comment]
@rmoff how about something like this:
`NoSuchFileException: Could not read statements from the provided script file: /foo/bar.`
`Make sure the file exists and can be read by KSQL CLI.`

**Comment by rmoff** [comment]
Sounds good, except I'd rearrange it slightly: 

    Could not read statements from the provided script file /foo/bar: NoSuchFileException
    Make sure the file exists and can be read by KSQL CLI.

**Comment by rmoff** [comment]
+1'ing my own issue here, just hit the poor error again.

**Comment by uurl** [comment]
@rmoff @hjafarpour Ready 👍
