### ISSUE TITLE
Unify the query execution logic across all modes (interactive, headless)

### ISSUE THREAD

**Issue by ybyzek** [confluentinc/ksql#1544]
Unify the query execution logic across interactive mode, non interactive mode, and RUN SCRIPT.

This issue is desirable as it relates to:
https://github.com/confluentinc/ksql/issues/1031
https://github.com/confluentinc/ksql/issues/1320

**Comment by apurvam** [comment]
@big-andy-coates assigning this to you since you are already looking into this problem. It would be good to unify the behavior of the line continuation character `\` across all modes as well.

**Comment by miguno** [comment]
Also, @hjafarpour recently completed [Sync Application(headless) mode behavior with the interactive mode. #1599](https://github.com/confluentinc/ksql/pull/1599). Has that PR improved the situation described in this ticket?

Lastly, there is the related ticket [Avro limitation for commands in `run script` versus interactive #1031](https://github.com/confluentinc/ksql/issues/1031) -- similar to @apurvam's comment above about `RUN SCRIPT`.

**Comment by big-andy-coates** [comment]
This is done now.  The only piece of the puzzle left to do is proper support for schema inference in headless mode, i.e. storing the KSQL schema somewhere so things do not get messed up if schemas evolve in the schema registry.
