### ISSUE TITLE
Null check for comparison fails for negative values

### ISSUE THREAD

**Issue by hjafarpour** [confluentinc/ksql#1546]
When having a comparison expression with a negative literal, the null check in code gen fails for negative values:
`select orderunits from orders where orderunits > -9.9;`
Generates wrong code.

**Comment by apurvam** [comment]
Can you share the error message that is raised as well?

**Comment by ouertani** [comment]
@apurvam should be closed ?

**Comment by agavra** [comment]
Closing at it seems that #1547 has fixed this issue.
