### ISSUE TITLE
The key field of table-table join result is null

### ISSUE THREAD

**Issue by ZhiXingHeYiApple** [confluentinc/ksql#1550]
KSQL version: 5.0.x (which has merged new-joins patch)
The picture below show the detail of my table-table join operation.
![image](https://user-images.githubusercontent.com/20380664/42406095-a537ee5e-81d3-11e8-97a9-7222a9709239.png)
Why the join result of table-table-join has no key field? How can I select one field of join result as the record's key? If the join result is stream, we can implement it by PARTITION BY clause. But I don't know how to do when the join result is table.
Appreciate for your suggestion or help!

**Comment by apurvam** [comment]
This should be addressed by #1697
