### ISSUE TITLE
Docker 4.1 image for cp-ksql-server 

### ISSUE THREAD

**Issue by gopalakrishnan-subramani** [confluentinc/ksql#1551]
I am looking for docker image https://hub.docker.com/r/confluentinc/cp-ksql-server/ for CP KSQL 4.1 versions, I could not find the 4.1 versions in the tags. 

I would like to know if we have cp-ksql-server 4.1 in docker or should we run with 5.0 beta versions?

Thanks

**Comment by apurvam** [comment]
These images dont exist for 4.1. The are available for the May and June preview releases, and will be available in 5.0 ( eta early August).

I’m going to close this. Please reopen if your question is not answered.
