### ISSUE TITLE
Can CTAS support PARTITION BY ?

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#1557]
```
ksql> SHOW TABLES;

 Table Name | Kafka Topic | Format | Windowed
----------------------------------------------
 CUSTOMERS  | customers2  | JSON   | false
----------------------------------------------

ksql> CREATE TABLE CUSTOMERS_BY_STATUS AS SELECT * FROM CUSTOMERS PARTITION BY CLUB_STATUS;
line 1:61: mismatched input 'PARTITION' expecting ';'
Caused by: org.antlr.v4.runtime.InputMismatchException
ksql>
```

Is there a technical or semantic reason why a TABLE can't be re-partitioned? Currently the workaround would be to take the underlying Kafka topic, register it as a stream, re-partition that, and then register a table on top of it.

**Comment by ZhiXingHeYiApple** [comment]
I think that it should also support PARTITION BY clause for CTAS.What's more, PARTITION BY clause should only be repartition and not specify the column as record's key. As describe in the [kafak stream document](https://docs.confluent.io/current/streams/faq.html#how-can-i-convert-a-kstream-to-a-ktable-without-an-aggregation-step), we have two options to convert kstream to ktable.

**Comment by hjafarpour** [comment]
No, repartitioning a table will violate the semantics of Table. Consider the `CUSTOMER` table in the above example. In Table order of events are important and when you repartition a table we have no control on the order of values for the new key and they can come from any other partition.

**Comment by agavra** [comment]
Closing as Hojjat's answer explains this limitation well.
