### ISSUE TITLE
Add more extensive tests for SqlFormatter

### ISSUE THREAD

**Issue by rodesai** [confluentinc/ksql#1571]
SqlFormatter converts a parsed sql statement back in to the sql text. KSQL uses this to generate statement text to be written to the command topic after inferring schemas. This class is not adequately tested atm. One option suggested by @apurvam is to extend the QueryValidationTests to test this by having them rewrite each query and ensure that the valid outputs are produced.

**Comment by agavra** [comment]
This is done as part of #3037
