### ISSUE TITLE
creating a stream out of a kafka-connect-jdbc source topic

### ISSUE THREAD

**Issue by harbya** [confluentinc/ksql#1574]
Hi Everyone,

I have been using kafka connect jdbc connectors performing source and sink with no issues at all. Now I want to create a KSQL Stream using the topic created by the kafka-connect source jdbc driver. I have tried value_format= 'json' and 'delimited' but doesn't seems to work. Can someone advise what should be the  right value_format in this scenario. Thanks a lot...

**Comment by cricket007** [comment]
What converter are you using for the source connector?

**Comment by harbya** [comment]
I didn't specify any converter for the source connector. I  was assuming  because of the use of a JDBC connector capable of pick up/work out  data types from different RDBMS then I thought I might not needed but I can see I was wrong. :) Below is the command I did use to create the source connector: 

`curl -XPOST localhost:8083/connectors -H "Content-Type: application/json"       
       -d "{
              \"name\": \"db2-bank-source-connector\",
             \"config\": {
               \"connector.class\": \"io.confluent.connect.jdbc.JdbcSourceConnector\",
               \"tasks.max\": \"1\",
               \"connection.user\": \"db2\",
               \"connection.password\": \"hariza11\",
               \"topic.prefix\": \"source.\",
               \"mode\": \"timestamp\",
               \"table.whitelist\": \"CUSTOMER_DETAILS\",
               \"timestamp.column.name\": \"INSERTED_TIME\",
               \"validate.non.null\": \"false\",
               \"connection.url\": \"jdbc:db2://127.0.0.1:50000/source\"
              }
           }"  `

**Comment by cricket007** [comment]
If you didn't specify it there, then it's using those specified in the property file when you started the connect server

**Comment by harbya** [comment]
ok yes is using the Json converter...

**Comment by cricket007** [comment]
I would encourage using the AvroConverter, if possible. Then you're not required to define your topic schema within KSQL.

Its not very clear what specific error you have received, but if you are using the JsonConverter, then JSON is the correct value format, not DELIMITED

**Comment by harbya** [comment]
Thanks ... I got it working now but I am using the value_format=avro: 

ksql> create stream customer_details (s_no int ,age int ,job string,marital string,education string,mdefault string,balance bigint,housing string ,loan string ,contact string,day string,month string,duration int,campaign int,pdays int,previous int ,poutcome string,y string) with (kafka_topic='source.CUSTOMER_DETAILS',value_format='avro',key='s_no');

and now I can get the data out the stream:
ksql> select * from customer_details limit 5;
1532593334406 | null | 2944 | 36 | blue-collar | married | secondary | no | 688 | yes | no | unknown | 6 | may | 174 | 2 | -1 | 0 | unknown | no
1532593334406 | null | 2945 | 45 | management | married | tertiary | no | 242 | no | no | cellular | 30 | apr | 587 | 1 | -1 | 0 | unknown | yes
1532593334406 | null | 2946 | 27 | student | single | tertiary | no | 118 | no | no | cellular | 25 | may | 112 | 1 | -1 | 0 | unknown | no
1532593334406 | null | 2947 | 45 | admin. | married | secondary | no | -388 | yes | no | cellular | 14 | jul | 175 | 2 | -1 | 0 | unknown | no
1532593334406 | null | 2948 | 40 | self-employed | married | tertiary | no | 1603 | no | no | unknown | 17 | jun | 279 | 1 | -1 | 0 | unknown | no

**Comment by agavra** [comment]
I'm glad this worked out for you! You may also want to see the recent work regarding connect/ksql integration https://github.com/confluentinc/ksql/blob/master/docs/developer-guide/ksql-connect.rst.

Closing out this issue, but feel free to reopen if there's anything else that needs answer.
