### ISSUE TITLE
KSQL CLI fails to handle BIGINTs

### ISSUE THREAD

**Issue by IDispose** [confluentinc/ksql#1576]
When I issue `select * from MY_STREAM where RECORDED_TIMESTAMP =1530601330000;` I get an error

`line 1:1: Invalid numeric literal 1530601330000`

Changing the query to `select * from MY_STREAM where RECORDED_TIMESTAMP/1000=1530601330;` works.

**Comment by apurvam** [comment]
Which version is this? Did this work in 4.1 ?

**Comment by IDispose** [comment]
This was in version 5 (Beta)
Works in 4.1

**Comment by apurvam** [comment]
Thanks! @rodesai this seems to be another issue with handling different int types in the new internal representation. Can you verify?

**Comment by apurvam** [comment]
Fixed by #1617
