### ISSUE TITLE
Build failure with ksql-5.0.0-beta180702222458

### ISSUE THREAD

**Issue by lmontrieux** [confluentinc/ksql#1579]
I can't seem to be able to build the latest preview release.
The output of `mvn -e -DskipTests=true clean install` is in this gist: https://gist.github.com/lmontrieux/67f746c3bc09290dda973ff0969d5e5d

`$ javac -version`
`javac 1.8.0_111`

**Comment by apurvam** [comment]
@confluentinc/tools , it looks like preview releases are not publicly buildable. Is it possible to fix this? 

@lmontrieux in the mean time, you can download the binaries directly or use docker. Thanks!

**Comment by maxzheng** [comment]
@lmontrieux You will need to setup a mirror in ~/.m2/settings.xml for 'confluent' repo id to point to http://packages.confluent.io/beta2018June/maven/ to resolve the dependencies. Let me know how that goes.

**Comment by apurvam** [comment]
Thanks for the follow up @maxzheng !

**Comment by lmontrieux** [comment]
Thank you @maxzheng , I was able to build KSQL after setting up a mirror. I will leave the relevant part of my `settings.xml` in [this gist](https://gist.github.com/lmontrieux/d26daba999b8dffff09eff680168596e), if it can be useful to someone.

@apurvam where can I get the binaries for this beta version?

**Comment by apurvam** [comment]
@lmontrieux https://www.confluent.io/preview-release

**Comment by apurvam** [comment]
I'm going to close this out. Please reopen if your question isn't answered.
