### ISSUE TITLE
Clearer error message for multi-way joins.

### ISSUE THREAD

**Issue by rodesai** [confluentinc/ksql#1612]
Currently, if a user tries to join multiple sources in a single statement, KSQL returns the error:

```
ServerError:io.confluent.ksql.parser.exception.ParseFailedException
Caused by: null
```

We should have a clearer error that explains that multi-way joins are not supported atm.

**Comment by rmoff** [comment]
Current error message on an attempted S-T-T join is 

    mismatched input 'inner' expecting ';'

Which is maybe slightly better, but ideally we should still make an explicit statement that multi-joins are not yet supported. 

ref #1891
