### ISSUE TITLE
Support multiple Kafka clusters

### ISSUE THREAD

**Issue by lmontrieux** [confluentinc/ksql#1613]
We have a use case where we have several Kafka clusters, and we'd like to run queries with topics in different clusters. For example:
* use a Table from a topic in cluster A, and write the output to a topic in cluster B
* make a join between a topic in cluster A and a topic in cluster B, and write the output to a topic in cluster C

How much effort would be required to achieve this? We might be able to dedicate some resources to help implement it, if it is feasible.

**Comment by cricket007** [comment]
Kafka Streams itself would need to support this feature, no?

I think the general strategy is using MirrorMaker or Confluent Replicator to replicate the source topics into the required cluster, then do the operations within a single cluster. 

The output topic can optionally be replicated to a destination cluster

**Comment by lmontrieux** [comment]
Thank you for your response, we'll look into using mirrormaker.
