### ISSUE TITLE
NPE when piping to ksql

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#1639]
Version: 5.0.0-rc3 (Docker)

Based on https://docs.confluent.io/current/ksql/docs/tutorials/examples.html#running-ksql-statements-from-the-command-line: 

	$ echo -e "SHOW TOPICS;\nexit" |docker run --network tutorials_default  \
	       confluentinc/cp-ksql-cli:5.0.0-rc3 \
	       http://ksql-server:8088
	Jul 26, 2018 4:01:51 PM org.jline.utils.Log logr
	WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
	KSQL, Copyright 2017-2018 Confluent Inc.

	CLI v5.0.0, Server v5.0.0 located at http://ksql-server:8088

	Having trouble? Type 'help' (case-insensitive) for a rundown of how things work!

	ksql> java.lang.NullPointerException
	ksql> java.lang.NullPointerException
	ksql> java.lang.NullPointerException
	ksql> java.lang.NullPointerException
	ksql> java.lang.NullPointerException
	ksql> java.lang.NullPointerException
	ksql> java.lang.NullPointerException
	ksql> java.lang.NullPointerException
	ksql> java.lang.NullPointerException
	ksql> java.lang.NullPointerException
	[... repeats forever ...]

**Comment by rmoff** [comment]
Bug still present in 5.0.0

**Comment by sneko** [comment]
Same for me just by connecting to the KSQL Server

KSQL CLI: 5.0.0

**Comment by rmoff** [comment]
Still present in 5.0.1.
