### ISSUE TITLE
Readme images

### ISSUE THREAD

**Issue by sriramsub** [confluentinc/ksql#164]
![picture1](https://user-images.githubusercontent.com/2977624/29090610-f4b11096-7c34-11e7-8a63-85c9ead22bc3.png)
![picture2](https://user-images.githubusercontent.com/2977624/29090617-fab5e930-7c34-11e7-9eee-0554192854d5.png)

**Comment by joel-hamill** [comment]
@sriramsub can this be closed?

**Comment by sriramsub** [comment]
if this asset is not used anywhere we can close it
