### ISSUE TITLE
KSQL Functions and Arrays should use 1-based indexing

### ISSUE THREAD

**Issue by blueedgenick** [confluentinc/ksql#1659]
Almost all common SQL systems count character-positions within strings starting from one, not zero. (Hive is the only common exception, which kinda betrays it's origins as a tool of java programmers). KSQL should also follow this common pattern in order to ease adoption.
Additionally, those "newer" SQL-based systems which support more complex types like Arrays - e.g. Presto - will count element positions within those arrays also starting at position one, not zero. 

Looking at what's currently implemented / requested / in-flight in KSQL, this seems to impact the following:

- String Functions
  - SUBSTRING (already exists, zero-based)
  - STRPOS / INSTR / POSITION (not yet implemented but requested)
  - SPLIT_PART (not yet implemented)

- Arrays
   - access-by-index e.g. my_array[0] (already implemented as zero-based)
   - ELEMENT function (in PR #1611 )
   - ARRAY_REMOVE function (not yet implemented but likely to be added to #1611 )
   - ARRAY_POSITION function (not yet implemented)

**Comment by big-andy-coates** [comment]
How about adding a single property `ksql.functions.index.base.legacy` or something, (which defaults to false, but people wanting old functionality can change to true), and this setting should only affect `SUBSTRING` and array access-by-index, i.e. only the ones we haven't released yet. All the pending ones just work in an _SQLy_ way for the get go.

Personally, I prefer this to having some property to control what if the index-base is one or zero. Which would require all new functions added to adhere to this too.

**Comment by big-andy-coates** [comment]
This is related to #1634, whose PR looks to fix SUBSTRING

**Comment by almazik** [comment]
I would prefer the current implementation with 0-based indexes and notes in the documentation reminding that
