### ISSUE TITLE
build error -  Failed during checkstyle configuration

### ISSUE THREAD

**Issue by xueyumusic** [confluentinc/ksql#1663]
when I git clone into local and run `mvn clean package -DskipTest`, it reports error:

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (validate) on project ksql-parent: Failed during checkstyle configuration: cannot initialize module TreeWalker - TreeWalker is not allowed as a parent of SuppressionCommentFilter -> [Help 1]
`

**Comment by apurvam** [comment]
Which branch? Is it repeatable? I just did a clean build of master on a public build and it works just fine.

**Comment by xueyumusic** [comment]
@apurvam , The branch is https://github.com/xueyumusic/ksql which was forked several days ago, and I could repeat.  Os is Windows7, maven is 3.5.4, the error is
![image](https://user-images.githubusercontent.com/95261/43560234-12b3d40a-9644-11e8-8c26-6d1994eaa9b8.png)

**Comment by apurvam** [comment]
Is this still an issue? Currently any support for building on windows is best effort. I am going to close this out. Please reopen if this is an issue on linux or mac os.
