### ISSUE TITLE
Unable to query stream created on UNION avro schema on top level

### ISSUE THREAD

**Issue by vasiliybondarenko** [confluentinc/ksql#1665]
Let's say we have topic _Test_ witch the following schema: 
`[
{"type":"record","name":"myrecord1","fields":[{"name":"f1","type":"string"}]}, {"type":"record","name":"myrecord2","fields":[{"name":"f2","type":"string"}]}
]`

after creating a stream with a command: 
`create stream test (f1 VARCHAR) with (VALUE_FORMAT='AVRO', KAFKA_TOPIC='Test');`

*test* stream cannot be queried:
running `select f1 from test;` results in null values regardless the topic contains records with non-null *f1* field.

Creating table with 
`CREATE TABLE test  WITH (KAFKA_TOPIC='test', VALUE_FORMAT='AVRO', KEY='name');`

results in error message saying that union is not supported

**Comment by apurvam** [comment]
Can you share the the contents of the `ksql.log` file?

**Comment by apurvam** [comment]
Please reopen when you have the log information, so we can make progress.
