### ISSUE TITLE
Add a UDF to extract the window start time from the message key

### ISSUE THREAD

**Issue by apurvam** [confluentinc/ksql#1674]
We should add a `WINDOWSTARTTIME()` UDF which returns the start time of the window if the underlying topic is windowed, or else return some sentinel value (like LONG_MAX) if it isn't.

Getting access to the window start time is generally useful, and we can't depend on `ROWTIME` for this piece of information. See #1497

**Comment by zlex7** [comment]
Hey, I'm new to contributing. Can I try adding this?

**Comment by rodesai** [comment]
@zlex7 go for it!

**Comment by apurvam** [comment]
yes. thanks @zlex7 . I am assigning this to you.

**Comment by apurvam** [comment]
Actually, I can't assign it to you for some reason. In any case, feel free to take a stab at it. You can follow the example from here to add a new UDF: https://github.com/confluentinc/ksql/pull/1611/files

**Comment by miguno** [comment]
Thanks for taking a stab at this, @zlex7 !

**Comment by rmoff** [comment]
would be good to include `WINDOWENDTIME` for completeness :)

**Comment by mjsax** [comment]
I would recommend to return `NULL` if the UDF is applied to a non-windowed column. A sentinel value as `LONG_MAX` might not make much sense IMHO and could be miss-leading downstream.

**Comment by rmoff** [comment]
@blueedgenick IMO a UDF would be a useful stop-gap solution for something that has in effect caused a regression in functionality. I think the discussion around UDF vs system column did take place, and TBH so long as we get it built sooner than later either would be fine :)

**Comment by apurvam** [comment]
@big-andy-coates said he would take this on.

**Comment by big-andy-coates** [comment]
Yep, I'm working on this... it's more involved than it might look.
