### ISSUE TITLE
clarify the usage of streamsProperties "ksql.streams.auto.offset.reset"

### ISSUE THREAD

**Issue by sebastianneubauer** [confluentinc/ksql#1680]
I am currently trying to implement that streamsProperties can be used in the python client https://github.com/bryanyang0528/ksql-python/pull/31 but I can't get it working as I would expect it to work.
In detail, I want to set `{"ksql.streams.auto.offset.reset": "earliest"}` in the creation of a stream. 

```                
        stream_name = "test_ksql_create_stream"
        ksql_string = "CREATE STREAM {} (ORDER_ID INT, TOTAL_AMOUNT DOUBLE, CUSTOMER_NAME VARCHAR) \
                       WITH (kafka_topic='{}', value_format='JSON');".format(stream_name, topic)
        streamProperties = {"ksql.streams.auto.offset.reset": "earliest"}
        r = self.api_client.ksql(ksql_string, stream_properties=streamProperties)
```

the streamsProperties are sent correcly to the server: 

```
'{"ksql": "CREATE STREAM test_ksql_create_stream (ORDER_ID INT, TOTAL_AMOUNT
      DOUBLE, CUSTOMER_NAME VARCHAR)                        WITH (kafka_topic=''exist_topic'',
      value_format=''JSON'');", "streamsProperties": {"ksql.streams.auto.offset.reset":
      "earliest"}}'
```

But when I query the created stream after generating some messages, the query starts with offset "latest" and not "earliest".

So I guess I just do not understand how the  `"ksql.streams.auto.offset.reset": "earliest"` can be set in a way my expectations are met.

Some questions I would have are:
* is  the offset a property of the stream or the topic or neither of both?
* if it is a property, how can I see what value is set currently? 
* can I change the offset at query time?
* how is the relation to the global offset configured in kafka, is it overwritten?

It would be awesome if you could provide a minimal example using the REST API and not using the ksql cli `ksql> SET 'auto.offset.reset' = 'earliest';`.

**Comment by apurvam** [comment]
The `streamsProperties` you have should be sent with _every_ request. In particular, you need to send it with your `select * from test_ksql_create_stream` query as well. 

When you do `SET 'auto.offset.reset' = 'earliest'` in the CLI, the client is caching that property and sending it with every subsequent request.

**Comment by sebastianneubauer** [comment]
Ah, or is it even, that it is sufficient to add it to the query request? So it is not at all a property of the stream or the query, right?

**Comment by rodesai** [comment]
It is a property of the query. If I run `CREATE STREAM B AS SELECT * FROM A` with `'auto.offset.reset'='earliest'`, then KSQL will populate B with all the records from the beginning of A. When you run `SELECT * FROM B` with `'auto.offset.reset'='earliest'`, KSQL will read from the beginning of B.

**Comment by sebastianneubauer** [comment]
Thanks, that helps, I forgot that a `create as` is a query too!

**Comment by apurvam** [comment]
Glad to hear that your issue is resolved @sebastianneubauer . Closing this out.

**Comment by merlinsundar16** [comment]
Hi, I tried the method of Select * FRom B with auto.offset property, but could not get it working. Only when some file is being pushed right now into topic, the code seems to work, else it fails. Please suggest some method to get the ksql to run from earliest
