### ISSUE TITLE
Add a way to specify the desired timezone for TIMESTAMPTOSTRING

### ISSUE THREAD

**Issue by rodesai** [confluentinc/ksql#1685]
Currently, TIMESTAMPTOSTRING generates a time string with the timezone set to the local time zone. We should allow this to be configurable via an additional optional parameter.

**Comment by yashbmewada** [comment]
Hi @rodesai , I would like to take up this issue to solve it. Also, Can you tell me a little bit more about what can be an alternate time zone rather than the local time zone? It would help me solve it appropriately.

**Comment by yashbmewada** [comment]
Thanks for the detailed explanation. Will try to solve it soon.

**Comment by uurl** [comment]
@rodesai ready
