### ISSUE TITLE
REST API: Drop of not existing topic isn't reported correctly

### ISSUE THREAD

**Issue by alexott** [confluentinc/ksql#1698]
Per [REST API documentation](https://docs.confluent.io/current/ksql/docs/api.html#run-a-ksql-statement), the error when deleting non-existing topic should be reported as object with `@type` equal to `currentStatus`, and `commandStatus.status` equal to `ERROR`. But in KSQL from Confluence Platform 5.0 it's reported as an error:

```
{"@type":"statement_error","error_code":40001,
"message":"Source TWEETS3 does not exist.",
"stackTrace":["io.confluent.ksql.ddl.commands.DropSourceCommand.run(DropSourceCommand.java:66)",
"io.confluent.ksql.ddl.commands.DdlCommandExec.executeOnMetaStore(DdlCommandExec.java:61)",
"io.confluent.ksql.ddl.commands.DdlCommandExec.execute(DdlCommandExec.java:54)"]}
```

**Comment by vcrfxia** [comment]
Looking at the 5.0 REST API documentation I can't find anything that suggests "the error when deleting non-existing topic should be reported as object with `@type` equal to `currentStatus`, and `commandStatus.status` equal to `ERROR`" as stated above. Rather, it seems appropriate for a drop source command issued for a non-existent source to result in a statement error.

Closing this issue for now. Please reopen if I've missed something (cc @JimGalasyn).
