### ISSUE TITLE
drop stream don't work after drop topic

### ISSUE THREAD

**Issue by clojurians-org** [confluentinc/ksql#1701]
when i drop topic. i can't drop stream after that.

```bash
ksql> drop stream HOP_SDK_APM_CRASH ;
No topic with name HOP_SDK_APM_CRASH was registered.
```

**Comment by apurvam** [comment]
How did you run `DROP TOPIC`?

**Comment by clojurians-org** [comment]
yes. i did it. then those streams can't be deleted.

**Comment by spena** [comment]
@clojurians-org Is this issue still happening?

I will close this issue as it is over 1 year old. If you still see this happening, feel free to re-open this ticket.
