### ISSUE TITLE
how to convert bigint to timestamp type?

### ISSUE THREAD

**Issue by clojurians-org** [confluentinc/ksql#1702]
i have no idea how to do it as the STRINGTOTIMESTAMP just return bigint type.
for jdbc sink, i refer to https://docs.confluent.io/current/connect/connect-jdbc/docs/sink_connector.html
```bash
ksql> SELECT STRINGTOTIMESTAMP('2018-01-01 11:11:11', 'yyyy-MM-dd HH:mm:ss')  FROM logi_hop_sdk_apm limit 1 ;
1514776271000
Limit Reached
Query terminated
ksql> 
ksql> 
ksql> SELECT cast(STRINGTOTIMESTAMP('2018-01-01 11:11:11', 'yyyy-MM-dd HH:mm:ss')  as timestamp) FROM logi_hop_sdk_apm limit 1 ;
Invalid primitive column type: TIMESTAMP
```

**Comment by apurvam** [comment]
The `CAST` function needs the target type as an operand. Here is what you should run:

```
SELECT cast(STRINGTOTIMESTAMP('2018-01-01 11:11:11', 'yyyy-MM-dd HH:mm:ss') as bigint)  as timestamp FROM logi_hop_sdk_apm limit 1 ;
```

Please reopen if that doesn't work.

**Comment by clojurians-org** [comment]
it's still bigint type, i need the timestamp type.

**Comment by clojurians-org** [comment]
kafka connect sink to postgres will become bigint  type for this field when it's bigint type,  i need mapping to timestamp type. currently i can use postgres trigger to handle it.
