### ISSUE TITLE
Recovery from a changelog topic is really slow

### ISSUE THREAD

**Issue by lmontrieux** [confluentinc/ksql#1709]
I'm having issues with KSQL and internal topics when restarting a broker. Reading from the changelog topic for a table-table join is really slow, and so far, tweaking the consumer settings hasn't helped much.

Here is the issue in more detail. I am running a KSQL instance, with a single query, that does a table-table join, on AWS. There is quite a bit of traffic on the input topics, so I need to be able to process data quickly. If I terminate the KSQL instance and launch a new one, my understanding is that the new KSQL instance, on startup, will start reading from the changelog topic for my join query, and then continue where the previous instance left off. The problem is that reading from that topic is really, really slow. As you can see on [this screenshot from our monitoring system,](https://ibb.co/npuegK) there are just over 2k messages read per second (measured with the following JMX metric: `io.confluent.ksql.metrics:type=ksql-engine-*['messages-consumed-per-sec']`), as you can see on the 'Messages per Second' graph in the middle row. The problem is that there are over 100 million messages to read, so it takes forever (bottom left graph, JMX metric `records-lag-max`). It also seems to slow down over time. You can see that the CPU is mostly idle (top left, the green line is CPU usage, blue line iowait), and the network is under-used as well (middle left, blue is bytes out, green is bytes in).

I tried tweaking the kafka consumer settings. Increasing fetch.max.bytes 5-fold more or less doubled the number of messages per second, but that is still orders of magnitude too slow. Once KSQL starts processing the joins again, I can see that the bottleneck becomes iowait and CPU usage, which is what I expect given the number of keys to keep in rocksdb. There doesn't seem to be any bottlenecks on the Kafka cluster either.

Am I monitoring the right thing?
How can I increase the consumption speed for the changelog topic? Are internal topics somehow configured separately?

KSQL version: 5.0.0
Kafka version: 1.1.1

**Comment by rodesai** [comment]
Can you add your JVM parameters and GC log here?

**Comment by apurvam** [comment]
Thanks @lmontrieux .

It would be good to collect the `consumer-fetch-manager-metrics`, particular the attributes below:

```
kafka.consumer:type=consumer-fetch-manager-metrics,client-id=.*
  - records-consumed-rate
  - bytes-consumed-rate
  - fetch-rate
```

**Comment by lmontrieux** [comment]
@rodesai I will post them tomorrow morning (CET), unfortunately I don't have access to it right this moment.
@apurvam Thank you for the suggestion, I will add that to our monitoring dashboard

**Comment by apurvam** [comment]
Thanks @lmontrieux . Also, what is the 'memory utilization' graph? JVM memory utilization or system memory utilization?

**Comment by lmontrieux** [comment]
@rodesai here is the GC log: https://gist.github.com/lmontrieux/6b6148539752928384f1dc3064f07726

I didn't change the JVM parameters initially. Increasing -Xmx and -Xms doesn't seem to help (`KSQL_HEAP_OPTS: "-Xmx15G -Xms15G"`). I'm going to look more into the memory usage and garbage collection.

Our ksql-server.properties is here: https://gist.github.com/lmontrieux/6e6e337cc5f6bdbcb94b870482cabdff
We start KSQL with the following arguments:
`KSQL_OPTS: "-Dbootstrap.servers={{Arguments.BootstrapServers}} -Dksql.streams.state.dir={{Arguments.StreamsStateDir}} -javaagent:/tmp/jolokia-jvm-agent.jar=host=0.0.0.0"`


I should also add that the join we are doing is over two giant tables, each with hundreds of columns. I'm trying to solve a user's use case, where they publish giant events with a very loose json schema.

**Comment by lmontrieux** [comment]
@apurvam Fortunately I was already capturing these metrics, you can find them here: https://ibb.co/cPfJAe

  - records-consumed-rate on the bottom left
  - bytes-consumed-rate on the bottom right
  - fetch-rate top row, second from the right (4 is for the StreamThread-1-restore-consumer thread)

**Comment by apurvam** [comment]
Hi @lmontrieux , you only shared a part of the GC log, which doesn't allow us to make a full analysis. If it is hard to upload the full log and share it, a backup would be to upload it to http://www.gceasy.io/ and share the report.

**Comment by apurvam** [comment]
Also, for the records consumed rate, can you share the consumer information for the different colored lines?

**Comment by lmontrieux** [comment]
@apurvam apologies, that file is really large. Here is the gceasy report: http://www.gceasy.io/my-gc-report.jsp?p=c2hhcmVkLzIwMTgvMDgvOC8tLWtzcWwtc2VydmVyLWdjLmxvZy4wLmN1cnJlbnQtLTE4LTE5LTUy

**Comment by lmontrieux** [comment]
@apurvam the yellow line is `_confluent-ksql-default_query_CTAS_LTT_PRODUCT_RELATIONS_0-5ebbc2a9-e452-47b9-9a36-cbdd26bca570-StreamThread-1-restore-consumer.records-consumed-rate`

The green line is `_confluent-ksql-default_query_CTAS_LTT_PRODUCT_RELATIONS_0-5ebbc2a9-e452-47b9-9a36-cbdd26bca570-StreamThread-1-consumer.records-consumed-rate`

**Comment by lmontrieux** [comment]
@apurvam I re-generated a report, this time only for the time period during which KSQL was reading from the changelog topic. You can find it here: http://www.gceasy.io/my-gc-report.jsp?p=c2hhcmVkLzIwMTgvMDgvOS8tLWtzcWwtc2VydmVyLWdvLmxvZy5jYXRjaHVwLS01LTUwLTM3

**Comment by apurvam** [comment]
thanks @lmontrieux .

Looking at both GC reports, it doesn't seem like you have a GC issue when consuming from the changelog topic. 

It seems like the restore consumer is making progress, but is capping out at 3k records/s. You don't seem to be IO bound (IO/wait is low), or network bound (network utilization is low), or memory bound (no real GC pressure).

There must be some artificial bottleneck introduced by the restore consumer. Can you share you complete KSQL Config and the broker config?

Thanks,
Apurva

**Comment by lmontrieux** [comment]
@apurvam thank you for looking into this. You can find the KSQL and Kafka broker configurations in this gist: https://gist.github.com/lmontrieux/bcd6d12bc2b91205a218f288f9050952

**Comment by big-andy-coates** [comment]
Hi @lmontrieux,

Can we try something a little more low-level to check the basics please?  Can you check the raw consumer performance from the Kafka brokers to the server you're running KSQL on please? 

i.e. can you run something like the following from the KSQL server box, (you may need to grab a Kafka deployment to get the script installed on the KSQL box):

```
kafka-consumer-perf-test --topic my-change-log-topic --broker-list bootstrap.servers=some-server:9092 --group perf-test-12445 --messages 150000000 --print-metrics --show-detailed-stats
```

You'll need to set the `topic` name to the name of the change log topic, and the `broker-list` appropriately. Set the `messages` count to something high enough to give you a few minutes of the consumer running. Then paste the results in here.

Also, can you give us a little more information on your set up? e.g. 
- how big is your Kafka cluster?
- where is your Kafka cluster?
- how big is your KSQL cluster?
- where is your KSQL cluster?
- how many partitions are there in the change log topic?

Can you also provide the output of the describe call on the change log topic too? e.g. the output of something like:

```
kafka-topics --describe --topic ChangeLog --zookeeper localhost:2181
```

With appropriate topic and zookeeper details. (You can run this on the Kafka broker box).

**Comment by apurvam** [comment]
Good call @big-andy-coates . It could very well be that the kafka cluster is not able to serve more than 3000 records/s. The consumer perf test from the same client machine should inform us of how much capacity there really is.

**Comment by lmontrieux** [comment]
Hi @big-andy-coates ,

My Kafka cluster has 6 brokers. Everything runs in AWS. The brokers are in the same region, but spread across 3 availability zones.
The KSQL cluster has 2 brokers. They run on the same AWS account, same VPC, same region.

Specs for the Kafka brokers:
- m4.4xlarge instances: 16vCPUs, 64GB RAM, "high" network performance
- 2TB EBS gp2

Specs for the KSQL brokers:
- i3.xlarge instances: 4vCPUs, 30.5GB RAM, "Up to 10 Gigabit" network
- attached SSDs

The query we are discussing is the only one we ever ran on this KSQL cluster (except for transient queries). In Kafka there are 2 changelog topics (except transient):
```
_confluent-ksql-default_query_CTAS_LTT_PRODUCT_RELATIONS_0-KSTREAM-AGGREGATE-STATE-STORE-0000000004-changelog
_confluent-ksql-default_query_CTAS_LTT_PRODUCT_RELATIONS_0-KSTREAM-AGGREGATE-STATE-STORE-0000000010-changelog
```
The output of describe is:
```
Topic:_confluent-ksql-default_query_CTAS_LTT_PRODUCT_RELATIONS_0-KSTREAM-AGGREGATE-STATE-STORE-0000000004-changelog	PartitionCount:1	ReplicationFactor:3	Configs:cleanup.policy=compact
	Topic: _confluent-ksql-default_query_CTAS_LTT_PRODUCT_RELATIONS_0-KSTREAM-AGGREGATE-STATE-STORE-0000000004-changelog	Partition: 0	Leader: 67108869	Replicas: 67108869,67108872,67108866	Isr: 67108869,67108866,67108872
```
and
```
Topic:_confluent-ksql-default_query_CTAS_LTT_PRODUCT_RELATIONS_0-KSTREAM-AGGREGATE-STATE-STORE-0000000010-changelog	PartitionCount:1	ReplicationFactor:3	Configs:cleanup.policy=compact
	Topic: _confluent-ksql-default_query_CTAS_LTT_PRODUCT_RELATIONS_0-KSTREAM-AGGREGATE-STATE-STORE-0000000010-changelog	Partition: 0	Leader: 67108869	Replicas: 67108869,67108871,67108867	Isr: 67108869,67108871,67108867
```

I also ran the perf test on both changelog topics. Something strange happened though: it completed within a few seconds, even though I set a very high number of messages, it completes in a few seconds (around 5). Maybe I am doing something incorrect? Here are the results: https://gist.github.com/lmontrieux/6289cc0808c3410850953ffd03041722

**Comment by apurvam** [comment]
Thanks @lmontrieux . From the results of the perf test, it looks like the restore from the `_confluent-ksql-default_query_CTAS_LTT_PRODUCT_RELATIONS_0-KSTREAM-AGGREGATE-STATE-STORE-0000000004-changelog` topic is around 4000 records/s. Also, this topic had only 132k messages. So it would take around 30 seconds.

The restore from the `_confluent-ksql-default_query_CTAS_LTT_PRODUCT_RELATIONS_0-KSTREAM-AGGREGATE-STATE-STORE-0000000010-changelog` topic is around 1800 records/s.
This topic had 57k messages. So it should take around 30 seconds as well.

On average, it seems to match what ksql is doing.

**Comment by miguno** [comment]
Any further comments, @lmontrieux ?

**Comment by lmontrieux** [comment]
Unfortunately I had to stop this experiment due to other priorities. I will close this ticket now. If in the future we notice a similar behaviour again, I will re-open it and provide further details.

**Comment by okouyad** [comment]
Would be nice to hear your finding after all those years. We are currently experiencing some restoration issue ourself.
