### ISSUE TITLE
KSQL show different speed  between local and remote kafka producer and ksql servers

### ISSUE THREAD

**Issue by FengJinghHua** [confluentinc/ksql#1716]
As the title say, I find KSQL show different speed  between local and remote kafka producer and ksql servers.   
If my kafka producer program runs in local kafka server,which is the ksql server too, the ksql works so fast, Convering  data just cost 0.90s，kafka producer will push 200000/s data，but some of kafka threads will be waitting and alive thread push data become slow. If I use another remote alone client to start kafka producer server，the kafka producer threads run normal，but ksql convers data become very slow，more than 1minutes，what is the cause？**How should I increase the ksql convert data speed .**

**Comment by apurvam** [comment]
I am not sure I understand the question. Are you saying that when the KSQL server is colocated with the Kafka broker, it is very fast, but when they run on different servers, it is slow? What is the bandwidth of the network link between KSQL and kafka?

**Comment by FengJinghHua** [comment]
Yes ， It solved，because of high usage of CPU.

**Comment by apurvam** [comment]
Great. Closing this out.
