### ISSUE TITLE
it's feasible to use constant expression without table?

### ISSUE THREAD

**Issue by clojurians-org** [confluentinc/ksql#1717]
i write udf for test. so i want to run expression with table.
```
select my_first('abc') ;
```

**Comment by apurvam** [comment]
Please provide more details. What does your UDF do? Can you write the complete query you want to execute? Can you share the schema of the table you want to run a query against?

**Comment by clojurians-org** [comment]
i just want a system table with one line data named dual.
so i can test my udf like this:
```sql
SELECT comp("bs2str.b64-encode.gzip.str2bs", "larluo") from dual ;
```
current i use ksql-datagen, then select limit 1 to test.
```sql
ksql-datagen quickstart=users format=json topic=user maxInterval=1000
SELECT comp("bs2str.b64-encode.gzip.str2bs", "larluo") from USERS  LIMIT 1;
```

i update the related udf to another issue: https://github.com/confluentinc/ksql/issues/1722

**Comment by spena** [comment]
In the interest of keeping our issue backlog tidy I'm going to close this issue. Please feel free to reopen with more details if the answer does not fully answer your question of if you have a follow up question. Thanks for using KSQL!
