### ISSUE TITLE
Incorrect formatting logging schema type error in ConnectSchemaTranslator

### ISSUE THREAD

**Issue by andybryant** [confluentinc/ksql#1731]
Currently when KSQL parses a schema type it doesn't support it prints error messages like...

```
[2018-08-13 04:14:45,351] ERROR Error inferring schema at field %s: %s (io.confluent.ksql.serde.connect.ConnectSchemaTranslator:96)
```

The argument replacement isn't working as it's using the java `Formatter` syntax for parameter substitution instead of the slf4j version on `ConnectSchemaTranslator.java:108`

```
        log.error("Error inferring schema at field %s: %s", field.name(), e.getMessage());
```

The correct syntax is...

```
        log.error("Error inferring schema at field {}: {}", field.name(), e.getMessage());
```

**Comment by spena** [comment]
This issue is fixed by https://github.com/confluentinc/ksql/pull/1732
