### ISSUE TITLE
Switch defaults for SUBSTRING and ARRAY access

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#1734]
#1635 saw SUBSTRING supporting a new more SQL-like mode and #1682 saw the ability to switch to more SQL-like base-1 indexing of arrays. Both of these changes use configuration settings to control the mode.  Both currently default to the old / legacy way of working, to avoid a breaking change. However, we should switch the defaults at some point in the future so that new users get the new way of working.

**Comment by big-andy-coates** [comment]
Adding to v1 project to ensure this is done before that release. I think one of these already has.  @agavra ?

**Comment by agavra** [comment]
Yup - this is done!
