### ISSUE TITLE
Update the KSQL UDF documentation with the proper dependency and import

### ISSUE THREAD

**Issue by stewartbryson** [confluentinc/ksql#1737]
The code samples for UDFs in the documentation do not identify the JAR dependency and the required imports to make this work.

Using Gradle, the dependency is: 
`compile 'io.confluent.ksql:ksql-udf:5.0.0'` or `compile 'io.confluent.ksql:ksql-udf:+'` for the most recent.

And the import is:
`import io.confluent.ksql.function.udf.*` to make all the required Annotations available.

Perhaps I just missed it in the documentation, but I certainly couldn't find it.

**Comment by miguno** [comment]
cc @JimGalasyn

**Comment by miguno** [comment]
Thanks  for reporting, @stewartbryson !

**Comment by JimGalasyn** [comment]
Thanks for the feedback, @stewartbryson! I'm tracking this issue with internal ticket KSQL-1430.

**Comment by stewartbryson** [comment]
Thanks for responding so quickly team.

**Comment by spena** [comment]
This is fixed by https://github.com/confluentinc/ksql/pull/2312
