### ISSUE TITLE
The confused config of rotate.interval.ms ， rotate.schedule.interval.ms，and partition.duration.ms  

### ISSUE THREAD

**Issue by FengJinghHua** [confluentinc/ksql#1756]
I think the docs for these options might be a bit confusing ，what is the detail and specified explanation about the diffrence of **rotate.interval.ms , rotate.schedule.interval.ms and partition.duration.ms** ,I really confused,please explan or set some links to solve my confusion? 

I set up  rotate.schedule.interval.ms=8000 and rotate.interval.ms=3000, partition.duration.ms =8000, it will committed files every 8s,but if I stop the producer program, the last files will wait more than 8s(some times cost more 20s~60s),and it will log some message like **"committing files after waiting for rotateIntervalMs time but less than flush.size"**, but the rotate.interval.ms is 3000ms, why the last files committed cost so much time?

If the configs sets like this: rotate.schedule.interval.ms=8000 and rotate.interval.ms=3000, partition.duration.ms =5000, I find the the batch files will be committed every 5000ms , It seems  rotate.schedule.interval.ms is not work? Is my understanding wrong? I  really need some detail explanation about above configs， Thanks a lot.

**Comment by apurvam** [comment]
These are settings for the HDFS connector: https://docs.confluent.io/current/connect/connect-hdfs/docs/configuration_options.html and don't apply to ksql.

Please retarget your question to: https://github.com/confluentinc/kafka-connect-storage-cloud
