### ISSUE TITLE
Whitespace after line continuation character causes it to be ignored

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#1758]
`\` as the final char on a line works: 

```
ksql> SHOW \
> STREAMS;

 Stream Name | Kafka Topic | Format
------------------------------------
 SHIPMENTS   | shipments   | JSON
------------------------------------
```

However if some whitespace (e.g. a space or tab) exists after the `\`, the continuation is not honoured and KSQL throws an error because it just parses the input on that line. 

This is something that will commonly occur in copying and pasting snippets from tutorials, emails, etc etc. 

See https://asciinema.org/a/HMx5H3d4KaVBRYeYgHtHG4g7c for an illustration of this. 

[![asciicast](https://asciinema.org/a/HMx5H3d4KaVBRYeYgHtHG4g7c.png)](https://asciinema.org/a/HMx5H3d4KaVBRYeYgHtHG4g7c)

Related: #1425

**Comment by uurl** [comment]
@rmoff Fixed ;)
