### ISSUE TITLE
SqlBaseLexer and SqlBaseBaseVisitor clasess 

### ISSUE THREAD

**Issue by Guzel2001** [confluentinc/ksql#1762]
Hello, everyone. 
I downloaded this project and try to execute, but it doesn't work because of two classes such as SqlBaseLexer and SqlBaseBaseVisitor miss. 
Where are located? 
Thank you a lot!

**Comment by apurvam** [comment]
How did you download and execute ksql?

**Comment by spena** [comment]
Closing this as this issue has over a year old. Feel free to re-open it if you still have questions about it.
