### ISSUE TITLE
Unexpected Output from Clickstream Data Analysis Pipeline Using KSQL Demo

### ISSUE THREAD

**Issue by dthomas-trimble** [confluentinc/ksql#1766]
The [Clickstream Data Analysis Pipeline Using KSQL](https://docs.confluent.io/current/ksql/docs/tutorials/clickstream-docker.html#ksql-clickstream-docker) Demo returns unexpected output.

I ran the demo on macOS and downloaded the following container:

```
$ docker run -p 33000:3000 -it confluentinc/ksql-clickstream-demo:5.0.0 bash
...
Digest: sha256:89305d28733c743d43c26e97b516609dd80e6f813b0e74fbb81b1f88c22c54b9
```

Starting elasticsearch and grafana both reported errors, although subsequent attempts to start the services showed they were already running:

```
root@728052971d18:/# /etc/init.d/elasticsearch start
[....] Starting Elasticsearch Server:/etc/init.d/elasticsearch: line 151: sysctl: command not found
/usr/share/elasticsearch/bin/elasticsearch: line 201: ps: command not found
 failed!
root@728052971d18:/# /etc/init.d/grafana-server start
[FAIL] Starting Grafana Server: failed!

root@728052971d18:/# /etc/init.d/elasticsearch start
[ ok ] Starting Elasticsearch Server:[....] Already running..
root@728052971d18:/# /etc/init.d/grafana-server start
[ ok ] Starting Grafana Server:[....] Already running..
```

There is also a problem with the clickstream-schema.sql file.  It reports an error and fails to create the tables:

```
ksql> RUN SCRIPT '/usr/share/doc/ksql-clickstream-demo/clickstream-schema.sql';
io.confluent.ksql.parser.exception.ParseFailedException: Exception while processing statements :Invalid primitive column type: LONG
ksql> list TABLES;

 Table Name | Kafka Topic | Format | Windowed
----------------------------------------------
----------------------------------------------
```

I changed the primitive type from LONG to BIGINT.  Next the script generated a io.confluent.ksql.util.KsqlException so I had to remove the "set property" calls from the script and perform them directly:

```
-- lets the windows accumulate more data
set 'commit.interval.ms'='2000';
set 'cache.max.bytes.buffering'='10000000';
set 'auto.offset.reset'='earliest';
```

After that I was able to complete the demo.

**Comment by zmmille2** [comment]
Ran into the same.  The rest of the demo worked, but I wasn't able to get connect to start, so grafana didn't work.  Did you end up running into that as well?

**Comment by dthomas-trimble** [comment]
@zmmille2 Yes, I was able to get Grafana to work.

**Comment by big-andy-coates** [comment]
Thanks for reporting @dthomas-trimble.

@rmoff is this fixed with your recent switch to compose and my recent fix of 'long' -> 'bigint'?

**Comment by dthomas-trimble** [comment]
I ran into an error when I tried to run the dlickstream-schema.sql script:

```
ksql> RUN SCRIPT '/usr/share/doc/ksql-clickstream-demo/clickstream-schema.sql';
 Could not read statements from file: /usr/share/doc/ksql-clickstream-demo/clickstream-schema.sql. Details: /usr/share/doc/ksql-clickstream-demo/clickstream-schema.sql
Caused by: /usr/share/doc/ksql-clickstream-demo/clickstream-schema.sql
```

I did not try to figure out the cause of the problem, but I was able to successfully execute all of the commands in the script manually.  By doing that I was able to complete the demo without any problems (including viewing Grafana).

**Comment by rmoff** [comment]
Which version (git branch) of the demo were you running?

**Comment by dthomas-trimble** [comment]
My apologies.  I was on `origin/master` and not on `5.0.0-post` as specified by the demo.

I'll have to try the demo again later.

**Comment by dthomas-trimble** [comment]
The demo worked as expected when I used the `5.0.0-post` version.

**Comment by miguno** [comment]
Great to hear you could sort out the issue @dthomas-trimble.  I'll close the ticket.  Feel free to re-open in case something still isn't clear.
