### ISSUE TITLE
Group by elements should match the SELECT expressions

### ISSUE THREAD

**Issue by markteehan** [confluentinc/ksql#1774]
```
CREATE STREAM S10 
AS SELECT 
   Day as L1
, 'Day' as L1_NAME
, Actor1countryCode as L2
, 'COUNTRY' as L2_NAME
, count(*) as events
, avg(avgtone) as avgtone
FROM GDELT_STREAM
GROUP BY Day,Actor1countryCode;
```
fails with the error message "Group by elements should match the SELECT expressions"

This statement is syntactically correct so this error message is non-standard. The GROUP BY does not need to match the SELECT expression because constants (in this case L1_NAME and L2_NAME) do not need to be included in a GROUP BY. It is important to be able to select constants with any SELECT statement; whether or not it aggregates using a GROUP BY.

A workaround is to do it in two phases: create a stream to include the columns with constants (and GROUP BY) followed by a table with the aggregation. This works.

```
CREATE STREAM S11
AS SELECT 
   Day as L1          , 'Day' as L1_NAME
, Actor1countryCode as L2 , 'COUNTRY' as L2_NAME
, avgtone
FROM GDELT_STREAM;

CREATE TABLE S12
AS SELECT L1,  L1_NAME,  L2,  L2_NAME, count(*) as events, SUM(avgtone) / count(*) as avgtone
FROM S11
GROUP BY L1,L1_NAME,L2,L2_NAME;
```

**Comment by rmoff** [comment]
I'm not sure I agree. In standard SQL you would also need to `GROUP BY` all non-aggregate-function columns too I think. The workaround you have is the correct way of doing it. 
Closing for now, but please re-open if I've misunderstood.
