### ISSUE TITLE
KSQL CLI "show topics;" Command Hangs

### ISSUE THREAD

**Issue by dthomas-trimble** [confluentinc/ksql#1777]
I downloaded the Confluent Platform and completed the [Quick Start Guide](https://docs.confluent.io/current/quickstart/cos-quickstart.html#cos-quickstart).  I then created my own topic and filled in some data:

```
$ kafka-topics --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic pageviews

$ kafka-console-producer --broker-list localhost:9092 --topic pageviews --property "parse.key=true" --property "key.separator=|"
>{"id": "1"}|{"id": "1", "page": "google.com"}
>{"id": "2"}|{"id": "2", "page": "amazon.com"}
>{"id": "3"}|{"id": "3", "page": "google.com"}
```

I verified that the topic existed by running: `$ kafka-topics --list --zookeeper localhost:2181`.  I then opened the KSQL CLI and tried to run "show topics;".  The result is as follows:

```
ksql> show topics;
Failed to retrieve Kafka Topic names
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting to send the call.
Caused by: Timed out waiting to send the call.
```

The log file starts with:

> [2018-08-23 14:03:43,004] ERROR Failed to retrieve Kafka Topic names
> Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting to send the call.
> Caused by: Timed out waiting to send the call.
> io.confluent.ksql.util.KafkaTopicClientImpl.listTopicNames(KafkaTopicClientImpl.java:125)
> io.confluent.ksql.util.KafkaTopicClientImpl.listNonInternalTopicNames(KafkaTopicClientImpl.java:131)
> io.confluent.ksql.rest.server.resources.KsqlResource.listTopics(KsqlResource.java:398)
> io.confluent.ksql.rest.server.resources.KsqlResource.executeStatement(KsqlResource.java:300)
> io.confluent.ksql.rest.server.resources.KsqlResource.handleKsqlStatements(KsqlResource.java:200)
> sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source)
> sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> java.lang.reflect.Method.invoke(Method.java:498)

Finally, I tried deleting the topic, but that did not solve the problem.  I could try re-installing the Confluent platform, but I could like to understand why the problem happened and how to avoid it in the future.  Especially for environments where deleting everything and starting over is not an option.

**Comment by dthomas-trimble** [comment]
The `kafka-topics` script showed that `pageviews` existed.  

If it was a timeout, it was happening repeatedly.  Eventually I power cycled the laptop.  I had to recreate the topic, but after that I was able to successfully execute `show topics;` from KSQL.

**Comment by dthomas-trimble** [comment]
The problem is back:

Running the following:
`$ confluent stop ; confluent destroy ; confluent start`

Results in:

> Using CONFLUENT_CURRENT: /var/folders/mn/jpxtz4r15ss_1m1flkc7vf6rkp6vqb/T/confluent.TBqZEAMC
> Starting zookeeper
> zookeeper is [UP]
> Starting kafka
> kafka is [UP]
> Starting schema-registry
> schema-registry is [UP]
> Starting kafka-rest
> kafka-rest is [UP]
> Starting connect
> connect is [UP]
> Starting ksql-server
> ksql-server is [UP]

I can then verify the initial list of topics:

```
$ kafka-topics --zookeeper localhost:2181 --list
__confluent.support.metrics
__consumer_offsets
_confluent-ksql-default__command_topic
_schemas
connect-configs
connect-offsets
connect-statuses
```

Running `SHOW TOPICS;` from KSQL hangs.  Running `confluent status` shows that the ksql-server is down:

> ksql-server is [DOWN]
> connect is [UP]
> kafka-rest is [UP]
> schema-registry is [UP]
> kafka is [UP]
> zookeeper is [UP]

Unfortunately, this is all the log contains:
```
$ cat cli-180827-104830.log
[2018-08-27 10:48:30,426] WARN Writing to metrics Kafka topic will be disabled (io.confluent.support.metrics.PhoneHomeConfig:61)
[2018-08-27 10:48:30,429] WARN Enforcing customer ID 'anonymous' (io.confluent.support.metrics.PhoneHomeConfig:66)
[2018-08-27 10:48:30,439] WARN Please note that the version check feature of KSQL is enabled.  With this enabled, this instance is configured to collect and report anonymously the version information to Confluent, Inc. ("Confluent") or its parent, subsidiaries, affiliates or service providers every 24hours.  This Metadata may be transferred to any country in which Confluent maintains facilities.  For a more in depth discussion of how Confluent processes such information, please read our Privacy Policy located at http://www.confluent.io/privacy. By proceeding with `confluent.support.metrics.enable=true`, you agree to all such collection, transfer and use of Version information by Confluent. You can turn the version check  feature off by setting `confluent.support.metrics.enable=false` in the KSQL configuration and restarting the KSQL.  See the Confluent Platform documentation for further information. (io.confluent.ksql.version.metrics.KsqlVersionCheckerAgent:68)
```

**Comment by miguno** [comment]
Sorry we didn't get back to you sooner, @dthomas-trimble.  Any news from your side since your last comment?

**Comment by dthomas-trimble** [comment]
@miguno It hasn't happened again and I don't know if I can recreate the problem.  The best I can figure is that schema-registry either did not start cleanly or that it went down soon after KSQL was started.

I've created a lot of topics since then without any issue.  Although I am now running the Landoop Schema Registry UI v0.9.5 so it's possible I've entirely side-stepped whatever caused the issue.

**Comment by miguno** [comment]
Ok, thanks @dthomas-trimble!  Let's close this ticket for now, and reopen later if need be.
