### ISSUE TITLE
"Cannot look up fields on non-struct type" when query key in MAP type field

### ISSUE THREAD

**Issue by ChenShuai1981** [confluentinc/ksql#1778]
I have a kafka topic whose avro schema contains "INPUT" field and the value has schema MAP<STRING, VARCHAR(STRING)>, I query "NAME" value in "INPUT" field by executing ksql "SELECT INPUT->NAME FROM MYSTREAM", but it raised "Cannot look up fields on non-struct type" error. Want to check if it is the expected behavior and how can I query field in MAP struct type by KSQL? Thanks!

**Comment by apurvam** [comment]
If the type is a map, the way to query by key is `SELECT INPUT['NAME']`. If `INPUT` was of type `STRUCT` you would use the `->` to dereference. See [this page](https://docs.confluent.io/current/ksql/docs/tutorials/examples.html#working-with-arrays-and-maps) for examples.

Please reopen if this continues to be an issue.
