### ISSUE TITLE
UDF does not support List as a return type

### ISSUE THREAD

**Issue by Lesprit-de-lescalier** [confluentinc/ksql#1791]
When I try implement a UDF that returns a list of elements I receive KsqlException: Type is not supported: java.util.List.
It is generated in [SchemaUtil.java#L446](https://github.com/confluentinc/ksql/blob/v5.0.0/ksql-common/src/main/java/io/confluent/ksql/util/SchemaUtil.java#L446)

**Comment by miguno** [comment]
@Lesprit-de-lescalier : Thanks for reporting.

To help us better understand, could you explain your use case?  Where/why would need `j.u.List` as a return type?

**Comment by Lesprit-de-lescalier** [comment]
I would like to create UDF that takes array as an input and return another array.
As far as I understand based on https://docs.confluent.io/current/ksql/docs/developer-guide/udf.html#supported-types there should be a support for a List interface as a return value from UDF.

Regarding usecases, I would like to transform data. For example let's  assume that there is a stream/table that contains fields/column with array of numbers. I would like to create UDF to get only even values and write them to a different stream/table.

PLAYERS_DATA:

Player_ID | Points
------------ | -------------
00001 | [1, 7, 13, 2]
00002 | [135, 6, 4]
00003 | [12, 6, 9]

I would like to be able to run the following querry with GET_EVEN UDF to transform data:
SELECT Player_ID, GET_EVEN(Points) as EvenPoints FROM PLAYERS_DATA and receive the following result:

Player_ID | EvenPoints
------------ | -------------
00001 | [2]
00002 | [6, 4]
00003 | [12, 6]

The other usecases that are important for me are:
- sorting values

Initial values | Transformed
------------ | -------------
[0, 5, 4] | [0, 4, 5]
[0, 100, 1, 10] | [0, 1, 10, 100]
- normalizing values

Initial values | Transformed
------------ | -------------
[0, 2, 4] | [0, 0.5, 1]
[0, 100, 1] | [0, 1, 0.01]
- removing duplicates
- get all values for a given percentile etc...

Please let me know if you need further details.

**Comment by apurvam** [comment]
Is this not fixed by #2029?

**Comment by blueedgenick** [comment]
@apurvam no, it's not. #2029 allows you to declare a UDF with signature containing collection-of-concrete-type but not any kind of wild-card. 
For example `public List<String> my_udf(List<String> input)` is ok thanks to #2029, but `public List<?> my_udf_to_work_on_any_list(List<?> input)` won't work. 
According to my quick testing, UdfLoader.java#L261 calls out to SchemaUtil.getSchemaFromType, which is prematurely trying to convert the declared Udf method signature into concrete Connect Schema types, hence the fail.

**Comment by agavra** [comment]
@blueedgenick - this should now be fixed with #3054. feel free to re-open if that doesn't address this!
