### ISSUE TITLE
Exception JsonParseException: Unexpected Character ('n') was expecting double-quote to start field name at [Source: (String)"{nestedelem1=YYY, nestedelem2=YY1}"

### ISSUE THREAD

**Issue by mquraishi** [confluentinc/ksql#1802]
If the value is json and one of the elements is another nested json object, creating a stream turns the nested json into some dictionary key=value object, resulting in `KsqlFunctionException: Invalid JSON Format` errors.

Given a json message:

```json
{"element1":"xxx", "element2":"XX1", "payload":{"nestedelem1":"YYY","nestedelem2":"YY1"}}
```

Create a STREAM:
```sql
create stream prev_stream (element1 varchar, element varchar, payload varchar) with (kafka_topic='topic', value_format='json');
```

Create a second Stream:
```sql
create stream some_name as select extractjsonfield(payload, '$.nestedelem1') as elem1, element1 from prev_stream;
```
----

```sql
select * from some_name;
```
returns:
```
Exception JsonParseException: Unexpected Character ('n') was expecting double-quote to start field name **at [Source: (String)"{nestedelem1=YYY, nestedelem2=YY1}"**
ERROR calculating column with index nestedelem1
```

```sql
select extractjsonfield(payload, '$.nestedelem1') from prev_stream;
```
Returns the same error.

NOTE THAT: Bolded "at [Source..." is listing not the nested json payload but a key=value of that representation without the double quotes and valid json.  I didn't cause that. That was internal conversion.

Also, in create statement can't use an element as a column that is in the nested json.  payload.nestedelem1 for instance.

**Comment by mquraishi** [comment]
Just more clarification.  I realize that the internal conversion is to a struct from some reason.  But it really needs to stay a json object.

**Comment by miguno** [comment]
Hi @mquraishi, which version of KSQL are you using?

Also, FYI: KSQL v5.0 has added support for a `STRUCT` data type, which makes reading and working with nested JSON much easier than the `EXTRACTJSONFIELD` function.

**Comment by mquraishi** [comment]
Hi @miguno KSQL server and client v5.0.0.  I am using the struct data type and notation -> to add elements.

**Comment by mquraishi** [comment]
Hello @miguno, would you consider this one a feature request, an issue or something that doesn't need any more improvement?  Thank you.

**Comment by spena** [comment]
@mquraishi This issue is fixed. I'm unsure in which version it was fixed, but the latest master branch does not produce the error you have.

```
ksql> select extractjsonfield(payload, '$.nestedelem1') from prev_stream emit changes;
+------------------------------------------------------------------------------------------------------------------------------------------+
|KSQL_COL_0                                                                                                                                |
+------------------------------------------------------------------------------------------------------------------------------------------+
|YYY
```

I will close this issue.
