### ISSUE TITLE
Change KafkaConsumerGroupClient to use the new Admin Client

### ISSUE THREAD

**Issue by dguy** [confluentinc/ksql#1806]
It currently uses the old scala implementation and it doesn't respect any of the config provided by ksql. This means that we can't adjust timeouts etc which have an impact when trying to connect to remote kafka servers.

**Comment by apurvam** [comment]
Seems to be a dup of #642

**Comment by spena** [comment]
@dguy Seems this is already fixed. I noticed the `KafkaConsumerGroupClientImpl` class uses the new `Admin` client, and such client is created when initializing the KSQL server.

Could you confirm this is what you were looking for and close the issue?

**Comment by big-andy-coates** [comment]
done.
