### ISSUE TITLE
Unexpected Results from Kafka Console Producer and KSQL

### ISSUE THREAD

**Issue by dthomas-trimble** [confluentinc/ksql#1807]
The `kafka-console-producer` only produces serialized string data and this is not easily digestible for KSQL which builds steams and topics using AVRO, JSON, and CSV data.

To recreate the scenario, create a topic and add some "JSON-like" data to it:

```
$ kafka-topics --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic users
Created topic "users".
$ kafka-console-producer --broker-list localhost:9092 --topic users --property "parse.key=true" --property "key.separator=|"
>{"id": 1}|{"id": 1, “name”: “Alpha”}
>{"id": 2}|{"id": 2, “name”: “Bravo”}
>{"id": 3}|{"id": 3, “name”: “Charlie”}
```
Open KQL and print the output from the topic:

```
ksql> print 'users' from beginning;
Format:STRING
8/30/18 7:52:56 AM CDT , {"id": 1} , {"id": 1, \xE2\x80\x9Cname\xE2\x80\x9D: \xE2\x80\x9CAlpha\xE2\x80\x9D}
8/30/18 7:53:03 AM CDT , {"id": 2} , {"id": 2, \xE2\x80\x9Cname\xE2\x80\x9D: \xE2\x80\x9CBravo\xE2\x80\x9D}
8/30/18 7:53:10 AM CDT , {"id": 3} , {"id": 3, \xE2\x80\x9Cname\xE2\x80\x9D: \xE2\x80\x9CCharlie\xE2\x80\x9D}
```
Set the auto.offset.reset property and create a stream from the topic.  Note we select JSON here because that is what was attempted to be passed to the console producer.
```
ksql> SET 'auto.offset.reset' = 'earliest';
ksql> create stream users_stream (id INT, name VARCHAR) WITH(KAFKA_TOPIC='users', value_format='json');
```

Running a `ksql> select * from users_stream limit 3;` on the stream does not produce any results.  Likely because the stream does not contain any JSON data, only string data.

**Comment by blueedgenick** [comment]
Hi Daren - looks like you have a problem in the source you are copying that user data from - the clue is the `\xE2\x80\x9C` in your topic output, which is actually the UTF-8 character code for a strangely-printed double-quote cahracter **which isn't the 'normal' double-quote**! You can actually see this if you look very closely at the way your data is rendered in the issue description above - see how the quotes around "name" and "alpha" look a little dofferent than those around "id" ? That's the root of this data not being properly interpreted as JSON.  
Once that's corrected, then the technique you are using to get some simulated data into your topic should work fine.
In case it helps, i personally use a slight twist on that particular technique so i don't have to keep re-typing the json:
`cat ~/dev/users_data.json | bin/kafka-console-producer --topic users --broker-list localhost:9092  --property "parse.key=true" --property "key.separator=:"`

**Comment by dthomas-trimble** [comment]
@blueedgenick Thanks, that cleared up some of the issues!  That's what I get for copying from VIM to macOS Notes and then back into a terminal when I'm trying to maintain context on a number of different tasks.

Now with the new and improved data, I see the following for the topic (with JSON as the format):
```
print 'users' from beginning;
Format:JSON
{"ROWTIME":1535657299754,"ROWKEY":"{\"id\": 1}","id":1,"name":"Alpha"}
{"ROWTIME":1535657306459,"ROWKEY":"{\"id\": 2}","id":2,"name":"Bravo"}
{"ROWTIME":1535657315803,"ROWKEY":"{\"id\": 3}","id":3,"name":"Charlie"}
```
A stream created from the topic looks like this:
```
ksql> select * from users_stream limit 3;
1535657299754 | {"id": 1} | 1 | Alpha
1535657306459 | {"id": 2} | 2 | Bravo
1535657315803 | {"id": 3} | 3 | Charlie
```
So the message is parsed as JSON, but the key is not, even if I specify that the key is "id" in the stream/table creation.  

I find that a bit strange because I can do something similar with an AVRO message and select new keys.  Perhaps the AVRO message works because I'm not generating a corresponding AVRO key.

**Comment by spena** [comment]
@dthomas-trimble Currently, KSQL only supports strings as the stream/table key. However, there is a feature request to support structured or generic keys using JSON or AVRO in the streams.

See https://github.com/confluentinc/ksql/issues/824

I will close this issue.
