### ISSUE TITLE
Geo_Distance function erroneously ignores southern hemisphere locations

### ISSUE THREAD

**Issue by blueedgenick** [confluentinc/ksql#1809]
UDF checks for latitude values in the range 0 to 90 decimal degrees, should be -90 to +90.
Test cases only compare pairs of points in the northern hemisphere :-(

(Longitude checking is correct at -180 to +180).

**Comment by kclulow** [comment]
Wait... there's a southern hemisphere?!

**Comment by uurl** [comment]
@blueedgenick @miguno Fixed 👍
