### ISSUE TITLE
Only support WINDOW TUMBLING in KSQL?

### ISSUE THREAD

**Issue by sangli00** [confluentinc/ksql#1814]
If i need used sliding window? 
how to  create it?

**Comment by miguno** [comment]
Sliding window is called "hopping window" in KSQL, e.g. `WINDOW HOPPING (SIZE 20 SECONDS, ADVANCE BY 5 SECONDS)`.

See https://docs.confluent.io/current/ksql/docs/syntax-reference.html#select.

**Comment by sangli00** [comment]
@miguno  Thanks
