### ISSUE TITLE
KSQL UDF doesn't support returning multiple output values

### ISSUE THREAD

**Issue by ChenShuai1981** [confluentinc/ksql#1819]
For example, parsing ip address into latitude and longitude. 
Here is my UDF method signature:

> @UdfDescription(name = "geoip2", description = "parse ip address")
> public class GeoIP2 {
>     @Udf(description = "get latitude and longitude of geo parsed by ip.")
>     public double[] geoip2(final String ip)
> }

The result of usage is:
> ksql> select geoip2(ip) from ipstream;
> Function 'geoip2' does not accept parameters of types:[VARCHAR(STRING)]

In fact, what I **expected** to use is the following sql, but seems ksql doesn't support it yet.
> ksql> **select geoip2(ip) as (latitude, longitude) from ipstream;**
> line 1:29: extraneous input '(' expecting {'ADD', 'APPROXIMATE'... }

**Comment by udf** [comment]
Nice issue.

**Comment by miguno** [comment]
Yes, this is currently not supported.  This will probably be done when adding UDTFs to KSQL (see e.g. https://github.com/confluentinc/ksql/issues/527).

**Comment by big-andy-coates** [comment]
This doesn't look like it requires UDTF. This looks like it requires a UDF that can return a `STRUCT< latitude BIGINT, longitude  BIGINT>`, or an `Array<BIGINT>`.

This is possible on the master branch of KSQL, and will be available in the 5.4.0 release, by using the `@UdfSchemaProvider` annotation on the UDF to supply the schema of the returned struct.

Secondly, you'd need support the aliasing of the two fields, i.e. the `as (latitude, longitude)` part, which KSQL does not yet support.

However, with the latest version of KSQL you should be able to at least get the functionality you require, if not quite the nice syntax you'd like.

**Comment by big-andy-coates** [comment]
I've raised a separate issue for the second part,  i.e. the as (latitude, longitude) part, so I'm going to close this issue.
