### ISSUE TITLE
Unable to separate KSQL Rest SSL Authentication from Kafka Broker SSL Authentication (Confluent Cloud)

### ISSUE THREAD

**Issue by joncourt** [confluentinc/ksql#1821]
The ksql settings `ssl.truststore.*` impact both the connection to the kafka brokers (ccloud in this case) and setup the KSQL Rest API authentication and there doesn't seem to be a way to separate them (as there is in kafka-rest-proxy and kafka-connect Rest API). 

With Confluent Cloud the broker security is SASL_SSL with PLAINTEXT - it breaks when i specify the `ssl.truststore.*` properties.

Is there a way to achieve this? Doesn't seem to be in stalking through the ksql and rest-utils code but perhaps I'm missing something.

Regards,
Jon

**Comment by purplefox** [comment]
Hi @joncourt 

Currently ksqlDB doesn't support using different truststores for the REST client connections and the connections from ksqlDb to Kafka. 

However, as a workaround it should be possible to write a script that takes your two trust stores and combines them into a single trust store that ksqlDB can use.

Something like:

1. Copy one of your trust stores to a temporary directory
2. Use keytool - importkeystore to import certs from the other trust store
3. Set ssl.truststore.location to the location of the temporary trust store.

This could be added to your ksqlDb start-up script so it's done automatically when the server is started.

**Comment by big-andy-coates** [comment]
Closing this as an answer has been provided. @joncourt feel free to re-open if you have follow on questions.  @purplefox do you think it's worth updating the docs with an example script?

**Comment by vcrfxia** [comment]
Adding a note for posterity: this is a duplicate of https://github.com/confluentinc/ksql/issues/8512 which has since been fixed by https://github.com/confluentinc/ksql/pull/8514.
