### ISSUE TITLE
Support UDTF (user defined tabular functions)

### ISSUE THREAD

**Issue by miguno** [confluentinc/ksql#1830]
In this ticket, we want to allow KSQL users to create their own tabular functions via UDTFs, similar to the existing support for UDFs and UDAFs.

Functions such as `EXPLODE` (not yet supported out of the box) are examples of functions in the UDTF category.  Another example is `flatMap` in the Kafka Streams DSL and in Scala.

# UDTF vs. UDF vs. UDAF

What's the difference between UDF (supported since 5.0), UDAF (supported since 5.0), and UDTF?

- **UDF**: user defined function (ex: SUBSTRING)
    - Takes 1 input record, produces 1 output record
- **UDAF**: user defined aggregate function (ex: SUM, COUNT)
    - Takes N input records, produces 1 output record
- **UDTF (this ticket)**: user defined tabular function
    - Takes 1 input record, produces 0,1, or N output records

# Related tickets

- [GH-1819: KSQL UDF doesn't support returning multiple output values](https://github.com/confluentinc/ksql/issues/1819)
- [GH-527: Support EXPLODE function (UDTF) for handling array columns](https://github.com/confluentinc/ksql/issues/527)
- #2373

**Comment by purplefox** [comment]
I am going to close this as a duplicate, as most of the discussion is going on here https://github.com/confluentinc/ksql/issues/527
