### ISSUE TITLE
Partition by not working CREATE STREAM AS SELECT 

### ISSUE THREAD

**Issue by sgulati89** [confluentinc/ksql#1835]
Hi,
I am not trying to create following streams:
CREATE STREAM test1 (entity string,id string,timeinmills bigint ) WITH (kafka_topic='my_topic',value_format='JSON');
CREATE STREAM test2 WITH (TIMESTAMP='timeinmills',partition_by='entity') as select entity,name, timeinmills from test1;

Getting following error:
io.confluent.ksql.util.KsqlException: Column 'entity' does not exist in the result schema. Error in Partition By clause

I tried using 'Key' field but it did not work and I am getting same error as given on following issue so changed it to partition_by
https://github.com/confluentinc/ksql/issues/279

Please advice..

**Comment by mayur1286** [comment]
Partition by in the with clause of a create stream is not supported. 

Try this instead. 
CREATE STREAM test2 WITH (TIMESTAMP='timeinmills') as select entity,name, timeinmills from test1
partition_by entity;
It will key the stream with the column specified in the partition by clause.

**Comment by sgulati89** [comment]
Thanks Mayur. It works fine

**Comment by miguno** [comment]
Related:

[CTAS allows 'partition_by' to be specified in the WITH clause. #1909](https://github.com/confluentinc/ksql/issues/1909)

**Comment by rajbhino** [comment]
Are lower case field names supported? It defaults to uppercase and when I specify in quotes it does not resolve when used in PARTITION BY
