### ISSUE TITLE
Handle KafkaStreams topology compatibility

### ISSUE THREAD

**Issue by rodesai** [confluentinc/ksql#1837]
KafkaStreams is adding some features to allow developers to ensure that their topologies are compatible across versions. We need to leverage these to make sure queries continue to work across KSQL versions (which each use the latest Kafka Streams version).

Specifically:
For queries built in 5.0, we need to ensure that optimizations are disabled in Kafka Streams by setting a TBD streams config.
For queries built in 5.1 onwards, we need to specify the following:
    - names for all state stores, using the Materialized.as API. These names need to be stable across builds of a query.
    - names for all repartition topics, using a tbd API in Kafka Streams. These names need to be stable. These names need to be stable across builds of a query.

**Comment by apurvam** [comment]
For completeness, can you link to the streams KIP/JIRA where then we configs are being discussed and documented?

**Comment by miguno** [comment]
Ping @rodesai ?

**Comment by rodesai** [comment]
KIP for optimization config: https://cwiki.apache.org/confluence/display/KAFKA/KIP-295%3A+Add+Streams+Configuration+Allowing+for+Optional+Topology+Optimization
KIP for internal topic naming: https://cwiki.apache.org/confluence/display/KAFKA/KIP-372%3A+Naming+Repartition+Topics+for+Joins+and+Grouping

**Comment by vcrfxia** [comment]
Closing since this has since been done.
