### ISSUE TITLE
[Enhancement] Add standard UDF for converting Kafka Connect Dates to/from Strings 

### ISSUE THREAD

**Issue by andybryant** [confluentinc/ksql#1851]
When importing data into Kafka via Kafka Connect, the `Date` objects are stored as `int` in Avro representing days since epoch (see https://github.com/apache/kafka/blob/trunk/connect/api/src/main/java/org/apache/kafka/connect/data/Date.java).

It would be handy to include a standard UDF for converting this to and from String format, much like `TimestampToString` and `StringToTimestamp` do now for `Timestamp` values.

Here's a working example of how these would look:
https://gist.github.com/andybryant/a90140772cae586a98e3d7975b379b26

The syntax is
`select datetostring(end_date , 'yyyy-MM-dd') from my_table;`

Happy to convert to a PR with tests if you would like to include in the standard library.
If you agree with the approach, I'd suggest using this approach for the existing `TimestampToString` and `StringToTimestamp` UDFs to switch to the cleaner published UDF style and to support dynamic values for the format pattern, which the current implementation doesn't.

**Comment by miguno** [comment]
Thanks for reporting and your offer to contribute, Andy!

> Happy to convert to a PR with tests if you would like to include in the standard library.

I'm +1.

> If you agree with the approach, I'd suggest using this approach for the existing TimestampToString and StringToTimestamp UDFs to switch to the cleaner published UDF style and to support dynamic values for the format pattern, which the current implementation doesn't.

FWIW, I'm +1 here, too.  What's important though is to discuss backwards compatibility, because I am not sure whether you are referring to internal refactoring of `TimestampToString` and `StringToTimestamp` (= changes not visible to users) or whether it's about changing the user-facing API of those functions.

**Comment by big-andy-coates** [comment]
HI @andybryant,

Fantastic that you're looking to get stuck in!

I've given this a quick scan and it looks good to me.  I like the support non-constant format strings.

Need to think if we care about the possibility of that map having unbounded size. We probably should. Maybe some large max size? 10K just to stop something going crazy if misused. Or switch to a Guava size limited cache maybe?

The only other change I'd suggest is change the wording to not be Kafka Connect specific. This is just converting between epoch days and a date string.  

Of course, we'd appreciate some tests in the actual PR as well. To help the non-java users, its generally worth also adding a SQL test case or two too. Take a look at something like https://github.com/confluentinc/ksql/blob/5def8c4679558ffb6922fd2406c670b4f26a95eb/ksql-engine/src/test/resources/query-validation-tests/stringtimestamp.json for an example.

Thanks!

**Comment by andybryant** [comment]
Getting painful rebasing to master every few days - any chance of a review? Thx

**Comment by miguno** [comment]
Support for this feature was merged.  See PR information above.
