### ISSUE TITLE
KSQL returning NULL when trying to EXTRACTJSONFIELD from a nested object

### ISSUE THREAD

**Issue by gsadhana** [confluentinc/ksql#1864]
We are on version 5.0.0

I'm trying to create a stream that includes partial data from a topic's record.

Records in topic look like this:

```json
{
    "Body": {
        "Shipment": {
            "ShipmentId": "key",
            "ActivityDate": "2018-09-11T14:52:37"
        }
    }
}
```

I first created a stream from the topic:

```sql
CREATE STREAM events_original(body VARCHAR)
WITH (KAFKA_TOPIC='shipment_events', VALUE_FORMAT='JSON');
```

Then, I tried to `SELECT` the shipment from the stream, but I keep getting null. Any ideas?

```sql
SELECT EXTRACTJSONFIELD(Body, '$.Shipment') AS shipment
FROM events_original 
LIMIT 1;
```

**Comment by alexbeltran** [comment]
Also was experiencing this. A workaround is to convert the value using a MAP<VARCHAR, VARCHAR>.

So:
```
CREATE STREAM events_original(body MAP<VARCHAR,VARCHAR>)
WITH (KAFKA_TOPIC='shipment_events', VALUE_FORMAT='JSON');
```

```
SELECT body['shipment'] AS shipment
FROM events_original
LIMIT 1;
```

This doesn't help with the several nested maps though.

**Comment by tpanagos** [comment]
I think this is a piece with issue #1562.

**Comment by rmoff** [comment]
Should be fixed by https://github.com/confluentinc/ksql/pull/1962
