### ISSUE TITLE
KSQL not working in Confluent Control Center

### ISSUE THREAD

**Issue by ikovalyov** [confluentinc/ksql#1873]
Standard docker-compose setup from examples. Wait untill everything loads. Open the ksql tab. You'll see 

```
KSQL not configured
Control Center is unable to connect to any KSQL clusters
You need to configure the Control Center app so it knows how to connect to your KSQL cluster(s). Once you do this, you’ll be able to submit and get info on your KSQL Streams, Tables, and Queries all from the Control Center UI.

If you need help or need more information on how to configure Control Center, check out our documentation.
```

message. If you go to the container and check configuration you'll see

```
bootstrap.servers=broker:9092
zookeeper.connect=zookeeper:2181
confluent.controlcenter.data.dir=/var/lib/confluent-control-center
confluent.monitoring.interceptor.topic.replication=1
confluent.controlcenter.internal.topics.replication=1
confluent.controlcenter.command.topic.replication=1
confluent.metrics.topic.replication=1

confluent.controlcenter.internal.topics.partitions=1
confluent.monitoring.interceptor.topic.partitions=1
confluent.metrics.topic.replication=1
confluent.controlcenter.config.dir=/etc/confluent-control-center
confluent.controlcenter.connect.cluster=connect:8083
confluent.controlcenter.replication.factor=1
confluent.controlcenter.ksql.endpoint=http://ksql-server:8088
```

So ksql is confugired but not working in control panel.

The reason is invalid status request sent by control panel. It uses `http://localhost:9021/api/ksql/localhost:8088/info` url to get the ksql version instead of `localhost:8088/info` or `http://ksql-server:8088`

Uncommenting `      CONTROL_CENTER_KSQL_URL: "http://ksql-server:8088"` line in the docker-compose file fixes this issue.

**Comment by miguno** [comment]
@ikovalyov: Sorry for the belated reply.

Can you share more information about your environment?  Which versions of KSQL and Confluent Control Center, for example?

Also:
> Standard docker-compose setup from examples.

Which examples exactly?  Could you share a link to the docker-compose file?

**Comment by miguno** [comment]
Any updates or feedback, @ikovalyov ?

**Comment by varadhvig** [comment]
Hi, I m facing same issue in the confluent 5.3 version.  Error message in the Control center for KSQL:

**```
KSQL not configured
Control Center is unable to connect to any KSQL clusters
You need to configure the Control Center app so it knows how to connect to your KSQL cluster(s). Once you do this, you’ll be able to submit and get info on your KSQL Streams, Tables, and Queries all from the Control Center UI.

If you need help or need more information on how to configure Control Center, check out our documentation.
```**

**Comment by vcrfxia** [comment]
Hi @ikovalyov @varadhvig are you still seeing this issue? If so, could you send us your Confluent Control Center properties file so we may try to reproduce?

I'm closing this issue for now as it's been inactive for a while, but please reopen if the issue is still occurring. Thanks!
