### ISSUE TITLE
Support multiple joins in a single statement

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#1891]
Currently KSQL only supports single joins in a statement. We should add the ability to join between multiple objects in a single query. 

This works: 

```
 select                                                                 \
    d.DocumentName, d.FileExtension, dv.ViewedAt                               \
  from documentViewStream  dv                                           \
  inner join documentTable d                                            \
    on dv.DocumentID = d.DocumentID;
```

But it would be better if we supported; 

```
select                                                                 \
    u.UserName, d.DocumentName, d.FileExtension, dv.ViewedAt           \
  from documentViewStream  dv                                          \
  inner join documentTable d                                           \
    on dv.DocumentID = d.DocumentID;
  inner join userTable u                                                \
    on uv.UserID = dv.UserID;
 ```

The above query currently throws `mismatched input 'inner' expecting ';'` (#1612 for improving the message)

In this example it would be a STREAM-TABLE-TABLE join. Currently the workaround would be to resolve the joins separately in multiple queries.

**Comment by miguno** [comment]
Related to https://github.com/confluentinc/ksql/issues/1532.

**Comment by csurepeddi** [comment]
I was wondering if this issue has been fixed? If not is there is a timeline on this? thank you

**Comment by avanchasr** [comment]
@rmoff I have the same scenario. We are getting into KAFKA streams and we have multiple table joins scenario. Any idea on when this will be addressed?

**Comment by avanchasr** [comment]
+1

**Comment by mente** [comment]
This would be really great to have multi-joins. Otherwise i have to spam kafka with additional intermediate topics which don't have meanin on it's own and brings headache to our team responsible for kafka cluster :)

**Comment by sebastianvaczi** [comment]
+1

**Comment by reneveyj** [comment]
+1 desperately

**Comment by demandous** [comment]
+ 1. reducing the need to create intermediately topics will help in our adoption

**Comment by MariamLogvinenko** [comment]
+1

**Comment by SangeetaVKalyani** [comment]
+1. Is this functionality available?

**Comment by LampicJ15** [comment]
+1

**Comment by MichaelDrogalis** [comment]
We're starting to work on this. ❤️

**Comment by alenpesikan** [comment]
In which version of ksqldb will this be published?

**Comment by MichaelDrogalis** [comment]
@alenpesikan 0.9.0, which will be out in a couple of days.

**Comment by mente** [comment]
For people not following release version changes by confluent: what does 0.9.0 mean if we have 5.4.1 now?

**Comment by MichaelDrogalis** [comment]
[Here's a quick explanation](https://github.com/confluentinc/ksql/issues/5111). We published a [version compatibility matrix](https://docs.confluent.io/current/installation/versions-interoperability.html#ksqldb) on Confluent's site. We're going to add a page to ksqldb.io to make the relationship extra clear - it's admittedly a little confusing now.
