### ISSUE TITLE
Ambiguity around auto.offset.reset values

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#1896]
ksql> SET 'auto.offset.reset'='earliest';
    Successfully changed local property 'auto.offset.reset' from 'null' to 'earliest'

If it was `null`, let's try changing it back to that

    ksql> SET 'auto.offset.reset'='null';
    Successfully changed local property 'auto.offset.reset' from 'earliest' to 'null'
    ksql> SELECT rating_id, user_id, message FROM RATINGS;
    Invalid value null for configuration auto.offset.reset: String must be one of: latest, earliest, none

OK, let's try `none` as listed in the error: 

```
ksql> SET 'auto.offset.reset'='none';
Successfully changed local property 'auto.offset.reset' from 'null' to 'none'
ksql> SELECT rating_id, user_id, message FROM RATINGS;
No valid committed offset found for input topic ratings (partition 0) and no valid reset policy configured. You need to set configuration parameter "auto.offset.reset" or specify a topic specific reset policy via StreamsBuilder#stream(..., Consumed.with(Topology.AutoOffsetReset)) or StreamsBuilder#table(..., Consumed.with(Topology.AutoOffsetReset))
Caused by: Undefined offset with no reset policy for partitions: [ratings-0]
Query terminated
```

I suggest that `none` be dropped from the list of options given if the offset is set to an invalid value, and maybe change the text of the first message from 

    Successfully changed local property 'auto.offset.reset' from 'null' to 'earliest'

to

    Successfully changed local property 'auto.offset.reset' from NULL to 'earliest'

to make it clear that it's not a valid string value to try setting it back to.

**Comment by big-andy-coates** [comment]
Hi @rmoff ,

It's easy enough to switch the `'null'` to a `NULL`. However, the handling of the `none` is more tricky as its not be handled / reported by KSQL, but by the stock Kafka Client.  You see `none` _is_ a valid value for `auto.offset.reset` - it's basically saying 'fail if there aren't any offsets stored already', which can be valid and what a user wants in some situations.  It's just that it won't work in KSQL for _new_ queries and probably isn't something we'd want users to set in KSQL.

I'll raise a PR for the `NULL` change. Plus add a message about using `unset` to clear the property.  

For the `none` side of things, changing the error message that lists the valid values, i.e. the `must be one of` statement, would be convoluted. However, I could explicitly reject a `set 'auto.offset.reset'='none'` statement with a message.

**Comment by rmoff** [comment]
Thanks Andy. I've put a comment on the PR before reading this about the `none`. As a user, it's really not great to be told "you used the wrong config, here are the valid options…X Y Z" "-> nope, Z isn't actually valid".
