### ISSUE TITLE
How to use IN statement in KSQL?

### ISSUE THREAD

**Issue by sangli00** [confluentinc/ksql#1903]
eg:
select columns from stream where col1 in (1,2);
how to write this sql in KSQL?

**Comment by sangli00** [comment]
Now KSQL support ```count(distinct  column)```?

**Comment by miguno** [comment]
KSQL does not support `DISTINCT` yet.

We are tracking the feature request for adding `DISTINCT` at:
[GH-506: Support SELECT DISTINCT COUNT(*) BY GROUP](https://github.com/confluentinc/ksql/issues/506)

**Comment by sangli00** [comment]
@miguno If i need use ```DISTINCT```,How to dev in KSQL?   UDF is OK?
I need get website ```UV```.
Thanks

**Comment by sangli00** [comment]
@miguno  How to get Array size
eg:
```[1,2,3]``` size=3
I can't find any function get array size.

**Comment by big-andy-coates** [comment]
Hi @sangli00 

>  If i need use DISTINCT,How to dev in KSQL? UDF is OK?

Yes, you could add your own 'count_distinct' UDF.

As @miguno said, we're already aware of the lack of DISTINCT at the moment and will implement it, though we can't give any timelines unfortunately.  So any UDF you build would just be an interim measure for yourself.

> How to get Array size

There is not currently a built in way to do this. Again, you could build your own UDF for this. This one could also be committed back, if you wanted.

**Comment by sangli00** [comment]
@big-andy-coates Thanks so much.
