### ISSUE TITLE
Port KSQL CLI to use the websocket endpoints

### ISSUE THREAD

**Issue by blueedgenick** [confluentinc/ksql#1937]
Background: The current CLI record-stream-fetching code makes use of a 'long-poll' mechanism to fetch records in response to interactive queries and print statements. Since that code was originally written a newer websocket-based endpoint was added.

This issue requests that the CLI be switched to that newer mechanism to improve resilience and responsiveness of result streaming.

In tandem it would be great to move the REST API docs to make use of teh ws endpoint too and then we can deprecate the current mechanism, putting it on a path to redundancy and removal.

**Comment by agavra** [comment]
closing this ancient ticket in favor of #6269
