### ISSUE TITLE
GEO_DISTANCE function broken by new UDF Invoker

### ISSUE THREAD

**Issue by blueedgenick** [confluentinc/ksql#1938]
The scalar functions which existed prior to the introduction of the new UDF support could make use of null-checking on their trailing input arguments to provide support for optional parameters. (i.e. if the last 2 parameteres are considered optional, and the function code correctly handles them being null, everything works as intended).

When we introduced the new UDF framework, and moved to using it to invoke the older functions too, in 5.0 the support for this functionality was broken and replaced by an assumption that any function wanting to support optional parameters would implement a separate constructor per parameter-permutation it wanted to support.

A quick pass through the codebase shows only 2 functions impacted by this, `substring` and `geo_distance`, and `substring` was fixed during the UDF migration. This leaves `geo_distance` to fix up to allow its last parameter to be treated as optional once again.

**Comment by miguno** [comment]
@blueedgenick to clarify: What you're saying is that what needs to be done is just to fix the `geo_distance` function?

**Comment by blueedgenick** [comment]
> @blueedgenick to clarify: What you're saying is that what needs to be done is just to fix the `geo_distance` function?

yes, that's my understanding. we'd have to change the implementatin of that function to be the new-style UDFs. i could probably help with this one - it's the size of thing that's do-able on an upcoming short flight ;)
