### ISSUE TITLE
Creating queries from rest api is not returning 'query_id'. In case of deleting a query how should I figure out which query to delete ?  as there is no id returned on creation/

### ISSUE THREAD

**Issue by afterlifenirvana** [confluentinc/ksql#1944]
on creation 

```
[{'@type': 'currentStatus',
  'statementText': "INSERT INTO ALERTS_STREAM SELECT *, 'alert' TYPE  FROM events WHERE data['user']='USER';",
  'commandId': 'stream/ALERTS_STREAM/create',
  'commandStatus': {'status': 'SUCCESS',
   'message': 'Insert Into query is running.'}}]
```

now to delete this running query i need the query id which is displayed on running show queries; 
If there is a way to get id while creation help me out. Otherwise i think this should be added.

**Comment by apurvam** [comment]
The rest API doesn't return the query id in the response to a create right now. Going to mark this as an enhancement request

**Comment by afterlifenirvana** [comment]
Ok I will be waiting for this to happen as i need this in my project. -.-

**Comment by afterlifenirvana** [comment]
Thanks for replying.

**Comment by mbrancato** [comment]
I think there are two issues here (and maybe could make a cleaner title for the issue). I've run into this as well.

* The returned `commandId` is not unique. `INSERT INTO` queries return an existing stream identifier.
* There is no way to use the `/status` endpoint to evaluate a query status. Queries get an identifier like `InsertQuery_0` but this isn't helpful right now in the API.

**Comment by vcrfxia** [comment]
Closing as this has since been fixed. For example, issuing a `CREATE TABLE ... AS SELECT` on the latest `master` results in:
```
ksql> create table orders_enriched as select o.product_id, sum(cast(p.product_price as double)) as total_purchased from orders o left outer join products p on p.product_id = o.product_id group by o.product_id;

 Message
---------------------------------------------------------------------------------------------------
 Table ORDERS_ENRICHED created and running. Created by query with query ID: CTAS_ORDERS_ENRICHED_5
---------------------------------------------------------------------------------------------------
```
