### ISSUE TITLE
Ability to delete rows from table based on stream data

### ISSUE THREAD

**Issue by almazik** [confluentinc/ksql#1945]
Please add the ability to delete rows from the table based on the stream data the table is built upon. 

Example: if I have a stream of orders with a field "Status", I want to delete the order from ActiveOrders table as soon as the status of the entity becomes "completed", "cancelled" or "removed".

It might be a good idea to add a similar semantic to the streaming syntax - ability to emit a NULL-body message based on the input stream value.

**Comment by kevinpthorne** [comment]
Is there currently any alternative for resetting connect-offsets for a specific topics?

**Comment by vcrfxia** [comment]
@almazik you can mimic your desired behavior by creating a query to filter your table based on the criteria you'd like to use to delete entries. For example, suppose I have a table foo for which I'd like to delete records that have `status=done`:
```
ksql> create table foo (status varchar, msg varchar) with (kafka_topic='foo_table', value_Format='json', key='msg', partitions=1, replicas=1);

 Message
---------------
 Table created
---------------
```
I can create a new table with the filter:
```
ksql> create table bar as select * from foo where status != 'done';

 Message
----------------------------------------------------------------------------
 Table BAR created and running. Created by query with query ID: CTAS_BAR_13
----------------------------------------------------------------------------
```
and populate some dummy data to see what happens:
```
ksql> insert into foo (status, msg) values ('pending', 'test');
ksql> set 'auto.offset.reset'='earliest';
Successfully changed local property 'auto.offset.reset' to 'earliest'. Use the UNSET command to revert your change.
ksql> select * from foo emit changes;
+-------------------------------------------------+-------------------------------------------------+-------------------------------------------------+-------------------------------------------------+
|ROWTIME                                          |ROWKEY                                           |STATUS                                           |MSG                                              |
+-------------------------------------------------+-------------------------------------------------+-------------------------------------------------+-------------------------------------------------+
|1572574751317                                    |test                                             |pending                                          |test                                             |
^CQuery terminated
ksql> select * from bar emit changes;
+-------------------------------------------------+-------------------------------------------------+-------------------------------------------------+-------------------------------------------------+
|ROWTIME                                          |ROWKEY                                           |STATUS                                           |MSG                                              |
+-------------------------------------------------+-------------------------------------------------+-------------------------------------------------+-------------------------------------------------+
|1572574751317                                    |test                                             |pending                                          |test                                             |
^CQuery terminated
```
Above I see that the entry was propagated to `bar` as expected. Now I can update `foo` with a message that I want to trigger a delete in `bar`:
```
ksql> insert into foo (status, msg) values ('done', 'test');
```
and verify that `foo` contains the update but `bar` saw the update as a delete:
```
ksql> select * from foo emit changes;
+-------------------------------------------------+-------------------------------------------------+-------------------------------------------------+-------------------------------------------------+
|ROWTIME                                          |ROWKEY                                           |STATUS                                           |MSG                                              |
+-------------------------------------------------+-------------------------------------------------+-------------------------------------------------+-------------------------------------------------+
|1572574794164                                    |test                                             |done                                             |test                                             |
^CQuery terminated
ksql> select * from bar emit changes;
+-------------------------------------------------+-------------------------------------------------+-------------------------------------------------+-------------------------------------------------+
|ROWTIME                                          |ROWKEY                                           |STATUS                                           |MSG                                              |
+-------------------------------------------------+-------------------------------------------------+-------------------------------------------------+-------------------------------------------------+
^CQuery terminated
```
In particular, `bar` is now empty.

I will close this issue for now, but please reopen if the workaround does not meet your needs.

@kevinpthorne could you please open a new issue with your question, or take it to the #ksql channel of our [Community Slack](https://app.slack.com/client/T47H7EWH0/C6UJNMY67)? It'd be nice to keep these issues targeted. Thanks!

**Comment by jhovell** [comment]
For anyone looking for an up-to-date answer I think this was eventually added

 https://docs.ksqldb.io/en/latest/developer-guide/aggregate-streaming-data/#tombstone-records

```
An important difference between tables and streams is that a record with a non-null key and a null value has a special semantic meaning: in a table, this kind of record is a tombstone, which tells ksqlDB to "DELETE this key from the table". For a stream, null is a value like any other, with no special meaning.
```

**Comment by luisvillarreal** [comment]
This is brilliant! I was looking for this feature all over the place. Thanks.

**Comment by shrugal** [comment]
@vcrfxia I just tried your example on the latest ksqlDB version, and it doesn't seem to work anymore. The where clause filters out messages from the source table (foo) but doesn't delete them in the result table (bar). Is this intended? If so, is there another way to produce tombstones for records that don't pass the filter anymore?

**Comment by jorinvo** [comment]
Hi, I am just stopping by to say thanks to you all in this thread. It helped me solve my problem. In my case a `where` clause was not what I needed though, but a `having` clause helped to remove the value from the table, plus the downstream Postgres table. Thank you :)

**Comment by kehao95** [comment]
Hi there, I was facing the same challenge but in my case I was not able to insert tombstone events into the stream. 
I managed to get it working but have no confidence if it's a hacking or not.

So I want to find the active sessions from an `event_stream(sessionid,timestamp,payload)`. 
By **active**, it means the session should have at least one event during the past minute.
So I wrote the query using `having` clause to check the last timestamp with current `UNIX_TIMESTAMP`
```sql
create table active_sessions
as select 
	sessionid as k,
	earliest_by_offset(sessionid) as sessionid
        collect_list(payload) as events,
	earliest_by_offset(timestamp) as inital_timestamp,
	latest_by_offset(timestamp) as last_timestamp
from event_stream 
group by id
having UNIX_TIMESTAMP() - latest_by_offset(timestamp) < 60000  # remove session once inactive for 1 min
emit changes;
```

It works like a charm, the table only holds the recent sessions and remove the inactive one once it pass 1min threshold.  
But I wonder how it works? Is this a good practice or a hack that happened to work?
* It is indicating that `having` clause will generate a `tombstone` event when evaluating false?
* And is the evaluation triggered by new event from upstream. ( if so, then the session may not expire when there is new events coming, to trigger re-evaluation?)

**Comment by mjsax** [comment]
It seems the original issue is different than what @kehao95 tries to advice. The original issue about an active "delete message", while @kehao95 tries to produce a tombstone base on time progress (without an input record).

> It is indicating that having clause will generate a tombstone event when evaluating false?

Yes, that is how `HAVING` semantics are defined.

> And is the evaluation triggered by new event from upstream.  (if so, then the session may not expire when there is new events coming, to trigger re-evaluation?)

Correct. Overall the approach is not doing what you think it does: it does not send a tombstone for anything that is expiring, but for each input record, `HAVING` is evaluated. Thus, for an update that is recent enough, the update just passed the filter. And for an update that is older than 60sec, the update is just dropped and replaced with a tombstone.

Btw: I am just discovering this old ticket, and I am totally in favor to add flexible delete semantics for tables, instead of just relying on tombstones.
