### ISSUE TITLE
Operations on ARRAY<>

### ISSUE THREAD

**Issue by almazik** [confluentinc/ksql#1947]
What operations besides addressing an element by index can I perform on ARRAY<> fields (of primitive types or structs)?

E.g. if I have a stream of Order messages with a collection of OrderItems in each order, I would like to have the following options:

1. Produce a new stream of OrderItems enriched with Order fields and OrderItem index in the array
2. Calculate the total value of order by summing up individual values of OrderItems (potentially calculated as a price*count)
3. Filter out some of the OrderItems based on their fields
4. Join OrderItems on Products table to enrich the data

**Comment by miguno** [comment]
Closing this question, @almazik.  Feel free to re-open if needed.
