### ISSUE TITLE
Use kafka topic name to get metrics for DESCRIBE EXTENDED

### ISSUE THREAD

**Issue by rodesai** [confluentinc/ksql#1980]
We're using the ksql internal topic name to reference metrics for descriptions. The metrics collectors track metrics using the kafka topic name. So we should switch the API to use the kafka topic name instead.

**Comment by rmoff** [comment]
@rodesai this is fixed by #1979, right?

**Comment by rodesai** [comment]
@rmoff that's right.

**Comment by rmoff** [comment]
@rodesai this caught me today, using 5.0.1 - I have a CSAS that targets a topic of a different name, and the `Local runtime statistics` are blank. Is this now fixed, and if so, which release will it be in? Thanks.
