### ISSUE TITLE
Misleading error message in JOIN if fields don't exist

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#1998]
Example 1: Select the same column from both sides of a JOIN, fine: 
```

ksql> SELECT X.ATM, Y.ATM FROM ATM_TXNS X \
>          INNER JOIN ATM_TXNS_02 Y \
>          WITHIN 5 MINUTES \
>          ON X.account_id = Y.account_id LIMIT 1;
Swipe | Swipe
Limit Reached
Query terminated
```

Example 2: Select the same *non-existant* column from both sides of a JOIN: 

```
ksql> SELECT X.FOO, Y.FOO FROM ATM_TXNS X \
>          INNER JOIN ATM_TXNS_02 Y \
>          WITHIN 5 MINUTES \
>          ON X.account_id = Y.account_id LIMIT 1;
Cannot create field because of field name duplication FOO

```
The error here is that the field doesn't exist - the above example shows that duplicating a field name in the SELECT itself isn't a problem.

Example 3: If different incorrect fields are selected, the error message is correct: 

```
ksql> SELECT X.FOO, Y.BAR FROM ATM_TXNS X \
>          INNER JOIN ATM_TXNS_02 Y \
>          WITHIN 5 MINUTES \
>          ON X.account_id = Y.account_id LIMIT 1;
Column X.FOO cannot be resolved.
```

--- 

-> Desired behaviour: In example 2, KSQL should report that the field doesn't exist (per example 3), not complain about a duplicate field name.

**Comment by vcrfxia** [comment]
Closing as this is resolved on the latest master:
```
ksql> select o.foo, p.foo from orders o inner join products p on o.product_id = p.product_id;
Column 'O.FOO' cannot be resolved.
```
