### ISSUE TITLE
RUN SCRIPT incorrectly reporting error while running create table statements

### ISSUE THREAD

**Issue by leighherman** [confluentinc/ksql#2021]
Hello,
I'm running into an issue with create table statements and using `run script` on the released KSQL 5.0 version.  
When running a create table statement through the run script command, the following error is received:
> io.confluent.ksql.parser.exception.ParseFailedException: Exception while processing statements :No column with the provided key column name in the WITH clause, ITEM_ID, exists in the defined schema.

However, running the same statement via the ksql client results in the table being created successfully.  I am able to recreate the issue on demand via the following steps:
1. Create a Kafka topic via command line
`kafka-topics --zookeeper <zookeeper server> --create --topic leigh_test --partitions 1 --replication-factor 1`
2. Use Postman to post data to the topic.  In this case, just a simple json message
`{
  "records": [
    {
      "key": "36102",
      "value": {
      "item_id": "36106",
      "descr": "Test Item 2"
}
    }
  ]
}`
3. Run the statements in the attached text file
[test.txt](https://github.com/confluentinc/ksql/files/2454476/test.txt)

If the create table statement is commented out of the file, the streams create as expected.  The create table statement causes the error to be reported when run as part of the script or alone in a separate file.  

It was suggested that I post an issue with steps to recreate, to see if it had already been fixed in a previous pull request.  I'm also curious if this issue presents itself in the  headless `--queries-file`.

**Comment by apurvam** [comment]
Hi @leighherman . are you saying that your attached file runs verbatim when the commands are copy pasted in the CLI, but fails to create the table when run through run script?

**Comment by leighherman** [comment]
>Hi @leighherman . are you saying that your attached file runs verbatim when the commands are copy pasted in the CLI, but fails to create the table when run through `RUN SCRIPT`?

@apurvam yes, that is the behavior I’m seeing. I can copy/paste the statements into the ksql cli and they run without error. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by leighherman** [comment]
My apologies for closing and reopening, I was click happy and clicked the wrong button 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by leighherman** [comment]
Some additional information, the issue can be worked around be explicitly defining the columns with their data types in the create table statement

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by miguno** [comment]
@leighherman : Could this be related to [Headless KSQL to support schema inference (Avro) #1530](https://github.com/confluentinc/ksql/issues/1530)?

**Comment by leighherman** [comment]
>@leighherman : Could this be related to [Headless KSQL to support schema inference (Avro) #1530](https://github.com/confluentinc/ksql/issues/1530)?

@miguno I believe it could be related, yes. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rodesai** [comment]
This issue should be fixed in KSQL 5.3
