### ISSUE TITLE
Publish a template UDF/UDAF project

### ISSUE THREAD

**Issue by rodesai** [confluentinc/ksql#2028]
We should publish a template UDF/UDAF maven project that produces a UDF/UDAF jar as output. Its a bit of a pain to set up a new maven project, and manually building the jar can lead to some head-scratching if things don't work (e.g. your class files aren't loaded because they're not in the right directory).

**Comment by ZacharyWhitley** [comment]
Like a Maven archetype?

**Comment by miguno** [comment]
@ZacharyWhitley : A maven archetype is one such option, yes.

For Kafka Streams we have created a similar setup to help users write their first Kafka Streams application: https://kafka.apache.org/20/documentation/streams/tutorial

**Comment by mitch-seymour** [comment]
I have started working on this and should have a PR up by the end of this week

**Comment by apurvam** [comment]
thanks @mitch-seymour !
