### ISSUE TITLE
Ruby client for KSQL

### ISSUE THREAD

**Issue by abhisheksarka** [confluentinc/ksql#2046]
Hi,

I just started with KSQL and I wanted to integrate this into a rails application. Do we have a ruby client for this? Any pointers would be helpful

**Comment by apurvam** [comment]
We have a rest API you can use to build a ruby client. There is no ksql specific ruby client that I know of.

**Comment by etam-flipp** [comment]
@apurvam Could you kindly provide a link to the documentation for the REST API? Thanks in advance.

**Comment by rodesai** [comment]
KSQL API reference: https://docs.confluent.io/current/ksql/docs/developer-guide/api.html
