### ISSUE TITLE
How to reuse query?

### ISSUE THREAD

**Issue by sangli00** [confluentinc/ksql#2057]
eg:

```
create stream stream1(col1 varchar) with(kafka_topic='myopic',value_format='json');
```

table:
```
create table tab as select count(*) as cun,url from stream1 group by url;
```

I need drop stream ```stream1```,recreate this stream.
```
terminate tab_query_id;
drop stream stream1;
create stream stream1(col1 varchar) with(kafka_topic='myopic',value_format='json');
```

table ```tab``` is cannot work.

if I terminate ```tab``` query_id,How to reuse tab? need recreate this?

**Comment by rodesai** [comment]
Ideally you'd be able to evolve stream1, tab, and the query populating tab. However, this is currently not supported by KSQL. If you're ok with dropping your current results, you can delete `tab` and recreate everything:

```
terminate tab_query_id;
drop tab delete topic;  # this will delete the data in tab
drop stream stream1;
# recreate
```
