### ISSUE TITLE
Track the DDL statement in the metastore

### ISSUE THREAD

**Issue by ybyzek** [confluentinc/ksql#2081]
We can list streams/tables and we can describe streams/tables, but we don't know the original DDL statement that created the stream/table.  This GH issue to keep track of the DDL statement in the metastore so we can show them in describe.

**Comment by rodesai** [comment]
We actually do have the sql statement in the metastore, so it should just be a matter of surfacing it in the API/CLI.

**Comment by stevenpyzhang** [comment]
This was added https://github.com/confluentinc/ksql/pull/4134
