### ISSUE TITLE
KStream parse wrong sign when value_format='JSON'

### ISSUE THREAD

**Issue by beckxie** [confluentinc/ksql#2095]
# confluent version: 5.0.0 OSS

1. Here is KSQL stream that I defined:
```
CREATE STREAM s_example \
(payload varchar) \
WITH (KAFKA_TOPIC='example', \
 VALUE_FORMAT='JSON');
```

2. Create a topic and produce some records:
```
bin/kafka-console-producer --broker-list kafka-1:9092 --topic example
>{"payload":{"ID": 12345,"Type": 1 }}
>{"payload":{"ID": 12346,"Type": 1 }}
>{"payload":{"ID": 12347,"Type": 2 }}
>{"payload":{"ID": 12348,"Type": 3 }}
```

3. Query data from stream:
```
SET 'auto.offset.reset' = 'earliest';
select payload from s_example;
select EXTRACTJSONFIELD(payload,'$.ID'),EXTRACTJSONFIELD(payload,'$.Type') from s_example;
```
![confluent-5-0-0](https://user-images.githubusercontent.com/20741391/47502843-4ee59780-d89b-11e8-940e-e519e65d44ee.png)

--------

# confluent version: 4.1.1 OSS
However, I have tried on version 4.1.1,the result was correct:
![confluent-4 1 1](https://user-images.githubusercontent.com/20741391/47503222-2dd17680-d89c-11e8-906f-a975d230efb1.png)

**Comment by cricket007** [comment]
Have you tried to define `payload` as a STRUCT with two nested int fields?

Confluent 5.0 added nested field support, which changes how messages get parsed.

Since your input contains an object within an object, it wouldn't be appropriate to consider it as a single varchar record

**Comment by beckxie** [comment]
@cricket007  Sorry for my late reply. 
It worked! Thanks!
