### ISSUE TITLE
How to name a columns with keyword

### ISSUE THREAD

**Issue by kanonlemon** [confluentinc/ksql#2110]
my json struct have a field name 'last'
so i cannot use  create stream(last double) with...
how to solve it?

**Comment by apurvam** [comment]
Unfortunately we don't yet have a way to use source data which has columns that collide with reserved works. one option is to not include that column in the schema for your stream or table. But if you need to use that column in your query, you are out of luck. The issue to track the enhancement request is here: https://github.com/confluentinc/ksql/issues/1537

**Comment by apurvam** [comment]
I am going to close this since it is a dup of #1537. If you think it's not a dup, please reopen and share more details.

**Comment by kanonlemon** [comment]
thanks
