### ISSUE TITLE
Improve KSQL functionality to better support enterprise application code deployments

### ISSUE THREAD

**Issue by DW-Pete** [confluentinc/ksql#2114]
In many corporate environments it is important for reasons of audit, compliance and risk management to use structured and reproducible methods to promote code from development trough TEST, STAGE (Pre-production) and Production environments. One common method used is to pull artifacts (in this case KSQL scripts) from source control and use a tool such as gradle or jenkins to deploy that code, either as full re-deployments or as incremental deployments (perhaps limited to a small subset of the code base).

From recent projects we have seen some problems with current KSQL 5.0 functionality that limits what we can achieve.

- Headless KSQL can use a startup script file to load a full deployed ksql script code base. However it is not possible to use this in most non-trivial cases as the file is pre-parsed before any streams or tables are created. This causes failures if a script references derived columns in a subsequent object, for example create stream1 with a calculated column C1, then create stream2 from stream1 referring to C1 fails as C1 does not exist. A similar problem exists in KSL-CLI 'run scripts'.
- Headless does NOT support incremental builds for example adding a new feature of independent streams and tables requires a full redeployment.

To work around these issues we use the REST API and a gradle process to deploy scripts on an object by object basis. This is not ideal as it potentially exposes a CLI in production systems. However, even then there are problems with KSQL functionality:
- Using REST is always an incremental approach.
- each object create needs to be preceded with an object drop. We can do this automatically in our deploy process but it adds complexity and does not work in all cases
- there is no ability to drop a stream/table with the termination of associated queries. We had to code 'try drop and capture dependant query ids, terminate any found and then retry drop' 
- We needed to include a small delay between executing script steps to allow for previous command to "work" 

I hope this can start a discussion on what is needed to automate code promotion processes. Please add any other things missing from this starter doc

**Comment by gnschenker** [comment]
Headless also does not allow to configure the number of threads per query which can be problematic when trying to tune KSQL Server for a multi query app.

**Comment by apurvam** [comment]
Thanks for the detailed report @DW-Pete. The gaps between interactive and non interactive mode are well known. This PR https://github.com/confluentinc/ksql/pull/1599 addresses some of them.

@big-andy-coates is looking at continuing the work to make sure that both modes behave identically. The latter work should be part of the march release.

As for your point about incremental builds, I am not sure I get the problem: yes you have to redeploy and restart all the queries if you change only one in non-interactive mode. Are you basically saying that this is too heavy an operation?

**Comment by DW-Pete** [comment]
> As for your point about incremental builds, I am not sure I get the problem: yes you have to redeploy and restart all the queries if you change only one in non-interactive mode. Are you basically saying that this is too heavy an operation?

The restart of all is not the issue. The issue is that our development process will create multiple KSQL files for the various features we build in. Having to stitch all of the files together into a single file introduces risk, though we have done this in the past using gradle.  Surely it is better to pull all of our master git KSQL repo to a file system and to play them one by one in a multi-file start up?

**Comment by big-andy-coates** [comment]
Thanks for raising this @DW-Pete - we are currently gathering customer feedback on this very subject, so your ticket is well timed!

> - Headless KSQL can use a startup script file to load a full deployed ksql script code base. However it is not possible to use this in most non-trivial cases as the file is pre-parsed before any streams or tables are created. This causes failures if a script references derived columns in a subsequent object, for example create stream1 with a calculated column C1, then create stream2 from stream1 referring to C1 fails as C1 does not exist. A similar problem exists in KSL-CLI 'run scripts'.

This is a straight up bug. This should be supported. I'm working in this area at the moment and will ensure this works as expected.

> - Headless does NOT support incremental builds for example adding a new feature of independent streams and tables requires a full redeployment.

I take it by this you are alluding to the fact that KSQL currently runs from a _single_ script on start up, as opposed to loading a directory structure of scripts?  The latter model allowing a new query to be deployed without changing any of the existing files.

Supporting multiple files is not something we're looking to support, i.e. it's not on our roadmap. However, as I've said above, we are keen to gather feedback from customers on KSQL deployment, and will use this to influence our future direction. You're not the first person to look for something like this, so we'll certainly take this on board. 

However, I wonder if this isn't better supported by something outside of KSQL. There is already a [third party gradle plugin](https://github.com/RedPillAnalytics/gradle-confluent) which can munge your separate .sql files together, ready for KSQL to use. Maybe that is of use to you?

> - Using REST is always an incremental approach.
> - each object create needs to be preceded with an object drop. We can do this automatically in our deploy process but it adds complexity and does not work in all cases

Agreed, though this is its intended use. If we fix the bugs in the headless mode, does it give you the functionality you need to move forward?

> - there is no ability to drop a stream/table with the termination of associated queries. We had to code 'try drop and capture dependant query ids, terminate any found and then retry drop' 

Yeah, I'm with you on this one. I think what we need is a `DROP [STREAM|TABLE]` command that supports a notion of  terminating any queries that were started as part of the create statement.

I've raised #2177 to track this.

> - We needed to include a small delay between executing script steps to allow for previous command to "work" 

We have some work in progress at the moment that should resolve this. Basically, when you submit a rest request you'll get back an Id that you can use in your next request, which will ensure the previous request has been fulfilled.

@gnschenker 
> Headless also does not allow to configure the number of threads per query which can be problematic when trying to tune KSQL Server for a multi query app.

You should be able to configure this using the `SET` statement in your script. Is this not the case?

**Comment by DW-Pete** [comment]
@big-andy-coates I know that gradle plug in - we wrote it! :)  we needed to work around our deploy issues - the first pass at this plugin was indeed a simple file munge to create a single, ordered, file from the individual GIT-versioned SQL files. However it hit the pre-parse issue so our gradle deploy was modified to support object-by-object using the REST API.

Fixing Headless to support non-trivial ksql files will be a great step forward for me - it will allow us to remove CLI/REST from the higher (test/pre-prod/prod) environments. Does the work on this include making sure the previous command executed successfully (the delay piece above)? 

We will continue developing our gradle plugin to work with both REST and script generation. Currently, we use this to deploy UDF jars and sql scripting either from a pull of Master or (on development) a pull of a feature branch.

**Comment by miguno** [comment]
@DW-Pete:  FYI, @rmoff and I reached out to @stewartbryson by email a few days ago, we're happy to chat f2f about KSQL and also this particular feedback with the two of you.

**Comment by big-andy-coates** [comment]
> @big-andy-coates I know that gradle plug in - we wrote it! :)

Lol! 

> Fixing Headless to support non-trivial ksql files will be a great step forward for me... Does the work on this include making sure the previous command executed successfully (the delay piece above)?

Well, its two separate bits of work. But both in progress at the moment.  There are PRs open currently that are the start of both parts.

**Comment by big-andy-coates** [comment]
@DW-Pete  I'd like to look into the issues you're seeing around the Headless mode that's stopping you using it.  I've found and fixed one issue relating to `TERMINATE` and `DROP STREAM`. (See https://github.com/confluentinc/ksql/issues/2420).  Can you give any other examples of things that don't work?

**Comment by big-andy-coates** [comment]
@DW-Pete I think you'll be interested in this PR: https://github.com/confluentinc/ksql/pull/2428

**Comment by MichaelDrogalis** [comment]
Going to close this one out. This is now well-covered by [migrations](https://www.confluent.io/blog/easily-manage-database-migrations-with-evolving-schemas-in-ksqldb/).
