### ISSUE TITLE
issue with LIMIT more then number of records 

### ISSUE THREAD

**Issue by wilsonshamim** [confluentinc/ksql#2115]
I am able to use ksql rest api using python script to fetch data. I have just inserted 10 records in my stream. When I run the query with LIMIT 5 or LIMIT 10 it displays the output with the records. If I give the limit as 25 it does not display the result

data = '{"ksql": "select * from stream1 LIMIT 25;",' \
       '  "streamsProperties": {  ' \
       '  "auto.offset.reset": "earliest"  }}'
headers = {"Accept": "application/vnd.ksql.v1+json","Content-Type":"application/json"}

is this behavior expected?

**Comment by big-andy-coates** [comment]
I'm assuming you're issuing this SELECT request to the `/query` websocket.  This should stream back the first 10 rows, but will then remain open awaiting the next 15 rows.

The KQL CLI does exactly this and works.  

I wonder if maybe your handling code on the websocket isn't outputting anything until the websocket is closed or similar?
