### ISSUE TITLE
Support auto-repartition when joining on subcomponent of composite key

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#2160]
This came up in a discussion with a customer:

Given a stream with a composite key, e.g. `Struct<X INT, Y INT>`, KSQL should allow a join on the sub components of the key:

```
SELECT * from A join B on A.ROWKEY.x = B.ROWKEY.y;
```

This discussion was outside the context of structured key support, but it seems it would need this support first.

**Comment by miguno** [comment]
See https://github.com/confluentinc/ksql/issues/824 for structured key support.

**Comment by mjsax** [comment]
Given the work on structure keys, this should be supported now. Closing this ticket.
