### ISSUE TITLE
Support querying a table's current value for a key

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#2192]
Say I have a running topology / query:

```sql
CREATE TABLE some_table AS SELECT x, COUNT(*) FROM some_stream GROUP BY x;
```

There is no current way in KSQL to query the current value for a key. If I say:

```sql
SELECT * FROM some_table WHERE ROWKEY = 'foo';
```

It will only show me _updates_ to the key, or, if I `SET 'auto.offset.reset'='earliest'` it will show all updates to the key.  But what I want is the _current_ value...

KStreams supports access to the internal key-value stores of a running topology. We could leverage this so that a key based query from a table will first go and get the current value from the kv store, (assuming `auto.offset.reset` is _not `earliest` of course).

So then I can run this command to get the current value for a key:

```sql
SELECT * FROM some_table WHERE ROWKEY='blah' LIMIT 1;
```

And I can run this statement to get the current value and then wait for updates:

```sql
SELECT * FROM some_table WHERE ROWKEY='blah';
```

This can be supported for some key based access, e.g. `ROWKEY=x`, `ROWKEY in(x, y, z` (when we support `IN`. Not sure if we can do filters or scans though, would need to look into the APIs available.

**Comment by rmoff** [comment]
I don't follow the need for this, because you wouldn't run: 

    CREATE TABLE some_table AS SELECT * FROM some_stream GROUP BY what_ever;

You'd run: 

    CREATE TABLE some_table AS SELECT foo_key,COUNT(*) as foo_count FROM some_stream GROUP BY foo_key;

and then be able to run 

    SELECT foo_key, foo_count FROM some_table; 

to see the value of it. 

Same in [this case](https://github.com/confluentinc/demo-scene/blob/master/mysql-debezium-ksql-elasticsearch/mysql-debezium-ksql-elasticsearch-docker.adoc#examine-changing-reference-data) where `ID` is the table key, and the current value for that key is accessed: 

    SELECT * FROM RATINGS_WITH_CUSTOMER_DATA WHERE ID=2;

What am I missing @big-andy-coates ? :)

**Comment by big-andy-coates** [comment]
OK, so my SQL was a bit off. You're right, it would be more along the lines of:

```sql
CREATE TABLE some_table AS SELECT foo_key,COUNT(*) as foo_count FROM some_stream GROUP BY foo_key;
```

This causes the KSQL servers to build up a table in-memory / on-disk and output the result to Kafka.  

However, I've heard questions from users like `how do I see the current value of a certain key?` and the answer is `you can't`.  You can consume the output topic and dump it into a key-value store and access it that way. You can consume the whole output topic and find the key you want. But you can't ask KSQL, even though it knows the answer. 

Currently if you run:

```
SELECT * FROM some_table where ROWKEY = 2 LIMIT 1;
```

While there are no updates coming it, it will just sit there.  Wouldn't it be nice if it just told you what the current value is?

Yes, this can also work with `ID` if the table was created with `WITH(KEY='ID')`, but I didn't bother covering that explicitly as using ROWKEY makes the examples more explicit.

**Comment by big-andy-coates** [comment]
Yep, pretty much. The term 'point in time query' just confused me as it suggests being able to query the table state at _any_ point in time.   Suggest we rename!

**Comment by rmoff** [comment]
Thanks @big-andy-coates, makes sense to me now
