### ISSUE TITLE
KsqlEngine.buildMultipleQueries can fail after building some queries

### ISSUE THREAD

**Issue by rodesai** [confluentinc/ksql#2202]
KsqlEngine.buildMultipleQueries can fail after building some queries. In this case we never return the list of queries to the caller, and they are not started but exist in the engine/meta-store. We should either clean up before exiting on exception, or just change the api to only accept one statement at a time.

**Comment by big-andy-coates** [comment]
Even if we change the API to only take one line at a time there is still the possibility that the metastore has been updated but the query does not pass validation. This can mean the query isn't registered or stopped.

E.g. fire of a statement that creates a avro stream which breaks evolvability.
