### ISSUE TITLE
Broken: config parameters for HTTPS to Confluent Schema Registry

### ISSUE THREAD

**Issue by ybyzek** [confluentinc/ksql#2206]
https://github.com/confluentinc/ksql/pull/1049 provides te ability to use configuration parameters to configure properties for HTTPS to Confluent Schema Registry (instead of passing in through Java args)

However, in trying to use this feature, it looks like KSQL server is not picking up the configs, even though I have added this to the `ksql-server.properties` properties file:

```bash
ksql.schema.registry.url="https://localhost:8082"
ksql.schema.registry.security.protocol="ssl"
ksql.schema.registry.truststore.location="/etc/kafka/secrets/kafka.client.truststore.jks.foo2"
ksql.schema.registry.truststore.password="confluent2"
ksql.schema.registry.keystore.location="/etc/kafka/secrets/kafka.client.keystore.jks.foo2"
ksql.schema.registry.keystore.password="confluent2"```

**Comment by big-andy-coates** [comment]
Try this config:

```
ksql.schema.registry.url=https://localhost:8082
ksql.schema.registry.ssl.protocol=BLAH
ksql.schema.registry.ssl.truststore.location=/etc/kafka/secrets/kafka.client.truststore.jks.foo2
ksql.schema.registry.ssl.truststore.password=confluent2
ksql.schema.registry.ssl.keystore.location=/etc/kafka/secrets/kafka.client.keystore.jks.foo2
ksql.schema.registry.ssl.keystore.password=confluent2
```

- I've stripped the quotes off the values as they are taken literally.
- SSL config for the SR needs the `ssl` in the property name

**Comment by Sarvesh27Sharma** [comment]
Hi @ybyzek ,
Did you manage to resolve this issue as I am also getting the same error. I am providing all th ksql.schema.registry.ssl parameters in my ksql.properties file but those are not picked up.
I have added them as per @big-andy-coates suggested.

**Comment by ybyzek** [comment]
@Sarvesh27Sharma yes it's working in this Docker-based demo: https://github.com/confluentinc/cp-demo/blob/5.4.0-post/docker-compose.yml#L417
