### ISSUE TITLE
KTable not showing keyed data in topic

### ISSUE THREAD

**Issue by sfrobish** [confluentinc/ksql#2224]

**Comment by sfrobish** [comment]
Having followed #1405 advice and followed the proposed solution.  We still don't see data in ktable.

For example:
```
CREATE STREAM foo                                   \
  with (KAFKA_TOPIC='foo', VALUE_FORMAT='JSON', PARTITIONS=10, REPLICAS=3)   \
  as select colA as key, colB
from raw_foo
partition by key;

CREATE TABLE foo_tbl (               \
  key                         string,   \
  colB                        string,   \
)\
WITH (KAFKA_TOPIC='foo', VALUE_FORMAT='JSON', KEY='key');
```

Printing the 'foo' topic contents we see:
```
{"ROWTIME":1541036111802,"ROWKEY":"56|245918568","KEY":"56|245918568","colB":245918568 ...
```

Selecting anything from foo_tbl does not return any values:

```
set 'auto.offset.reset'='earliest';
select * from foo_tbl limit 3;
```

However selecting from the foo stream does return results:

```
select * from foo limit 3;
[ 1540958025544, "56|245257572", 245257572 ]
[ 1540958025584, "56|246088752", 246088752 ]
[ 1540958025585, "56|246088771", 246088771 ]
```

**Comment by mjsax** [comment]
This should work on newer versions of ksqlDB. Btw, the `PARTITION BY` clause would need to use `PARTITION BY colA` (ie, a column name from the _input_ stream schema, not the later assigned alias `key`.

Closing this ticket for now. Feel free to re-open if my assessment is incorrect.
