### ISSUE TITLE
Add maven repo info to UDF docs

### ISSUE THREAD

**Issue by blueedgenick** [confluentinc/ksql#2231]
The first step of building your own UDF is to setup the appropriate Java project, which has to include a maven reference to the `ksql-udf-x.y.z.jar` jar. Unfortunately we don't tell you either the name of this jar or it's maven coordinates, which is made more difficult by the fact that the confluent maven repo continues to be non-browsable so you can't discover it for yourself either. 
Let's add a little section in the UDF guide to show you the relevant snippet to add to your `pom.xml` file.

**Comment by Strech** [comment]
@blueedgenick Can you share quick workaround now?

**Comment by blueedgenick** [comment]
@Strech - looks like the docs are now updated and we missed to close this ticket out. The info you need can now be found at [https://docs.confluent.io/current/ksql/docs/developer-guide/implement-a-udf.html]

Also pasting it here for your convenience (change the version number, `5.1.1` in this example, to match your KSQL version).
`   

    <dependencies>
        
        <dependency>
            <groupId>io.confluent.ksql</groupId>
            <artifactId>ksql-udf</artifactId>
            <version>5.1.1</version>
        </dependency>
    </dependencies>
`

**Comment by Strech** [comment]
@blueedgenick Awesome, thanks!
