### ISSUE TITLE
Incorrect ROWKEY generated for windowed aggregation 

### ISSUE THREAD

**Issue by amleung21** [confluentinc/ksql#2233]
When performing a windowed aggregate on a stream:
```
kqsl> create table average_bid1sec as \
  SELECT \
    ticker, \
    exch, \
    WindowStart(), \
    WindowEnd(), \
    SUM(bid1) / COUNT(*) AS average_bid1, \
    SUM(bid2) / COUNT(*) AS average_bid2 \
  FROM combined_bid_stream \
  WINDOW TUMBLING (size 1 seconds) \
  GROUP BY ticker, exch; 
```
The following table is generated:
```
ksql> print average_bid1sec;
Format:JSON
{"ROWTIME":1003,"ROWKEY":"ticker3|+|10\u0000\u0000\u0000\u0000\u0000\u0000\u0003","TICKER":"ticker3","EXCH":10,"KSQL_COL_2":1000,"KSQL_COL_3":2000,"AVERAGE_BID1":1.5,"AVERAGE_BID2":1.6500000000000001}
{"ROWTIME":3000,"ROWKEY":"ticker3|+|10\u0000\u0000\u0000\u0000\u0000\u0000\u000B","TICKER":"ticker3","EXCH":10,"KSQL_COL_2":3000,"KSQL_COL_3":4000,"AVERAGE_BID1":3.0,"AVERAGE_BID2":3.1}
```
According to Rohan in the Slack channel, the ROWKEYs above are incorrect and should have been something like `ticker3|+|10|Window{start=<start> end=<end>}`

I'm using the docker-compose from here: https://docs.confluent.io/current/ksql/docs/tutorials/basics-docker.html. i.e. image: confluentinc/cp-ksql-server:5.0.1.

**Comment by rodesai** [comment]
I goofed - the key is actually what it's supposed to be here. To serialized windowed keys, we currently use the Kafka Streams TimeWindowedSerde, with StringSerde for the key. A windowed key consists of a key and a window start time. TimeWindowedSerde serializes these into a byte buffer, where the first x bytes are the key as serialized by the key serde (in this case StringSerde), and the last 8 bytes are the window start time, as a long. That said, the binary value for the timestamp doesn't look right. Not sure what's going on there. Perhaps KSQL is not rendering it correctly when handling `print`.

**Comment by killpigger** [comment]
Is there any SMT to convert windowed keys into string when writing into external DB such as elasticsearch? Is there any example

**Comment by rmoff** [comment]
@killpigger you can use `"key.converter": "org.apache.kafka.connect.storage.StringConverter",` and this will work just fine with the Elasticsearch sink. 

@amleung21 @rodesai looking at this ticket I'm not clear if this is an actual issue, or just KSQL behaving as designed. Please confirm if it can be closed, or clarify what the outstanding issue is.

**Comment by big-andy-coates** [comment]
Closing due to lack of response. Please feel free to re-open if you feel the issue is not resolved!
