### ISSUE TITLE
Table-Table left join returns records before left join operation

### ISSUE THREAD

**Issue by tee-tan** [confluentinc/ksql#2247]
I'm using KSQL and I've created two tables with only one record each, when I performed LEFT JOIN I got two records as the result (so I guess ksql returns rows before and after the left join operation)
```
ksql> SELECT * FROM TBL_REGISTRATION_BOOK_PROVINCE r LEFT JOIN TBL_TU_PROVINCE p ON r.PROVINCE_ID=p.PRO_ID;
1544172148906 | 10 | 1 | 10 | null | null | null | null
1544172148906 | 10 | 1 | 10 | 1544172169665 | 10 | 10 | Bangkok
```
When perform normal (inner) join the result seems correct, but of course I'd need the left join.
```
ksql> SELECT * FROM TBL_REGISTRATION_BOOK_PROVINCE r JOIN TBL_TU_PROVINCE p ON r.PROVINCE_ID=p.PRO_ID;
1544172148906 | 10 | 1 | 10 | 1544172169665 | 10 | 10 | Bangkok
```
I'm not sure If I missed something as this should be very common use-case. Please advice.

I'm using docker-compose from `cp-all-in-one` the ksql-cli image is `confluentinc/cp-ksql-cli:5.0.1`
I've set `SET 'auto.offset.reset' = 'earliest';`

The tables are as following
```
Name                 : TBL_REGISTRATION_BOOK_PROVINCE
 Field       | Type                      
-----------------------------------------
 ROWTIME     | BIGINT           (system) 
 ROWKEY      | VARCHAR(STRING)  (system) 
 CONTRACT_NO | INTEGER                   
 PROVINCE_ID | INTEGER                   
-----------------------------------------
ksql> select * from tbl_registration_book_province;
1544172148906 | 10 | 1 | 10
```
```
Name                 : TBL_TU_PROVINCE
 Field    | Type                      
--------------------------------------
 ROWTIME  | BIGINT           (system) 
 ROWKEY   | VARCHAR(STRING)  (system) 
 PRO_ID   | INTEGER                   
 PRO_DESC | VARCHAR(STRING)           
--------------------------------------
ksql> select * from tbl_tu_province;
1544172169665 | 10 | 10 | Bangkok
```

**Comment by mjsax** [comment]
KSQL execute the join continuously and the output is a _changelog_ for the _result_ table. Furthermore, records are processed in timestamp order.

Thus, if the left-table record has a smaller timestamp than the right-table record, the left-table record will be processed first: it will be inserted into the left table and it will be joined against the empty right table, producing a left-join result. Afterwards the right-table record is processed: it will be inserted into the right table and joined against the left table, producer the second inner-join result.

If the timestamps order would be reverse, the right-table record would be processed first. For this case, it would be inserted into the right table, and no join result is emitted (it's not a full outer join). Next, the left-table record is processed, updating the left table and producing an inner join result.

By default, timestamp synchronization between two inputs might not be perfect, and you can increase the config `max.taskl.idle.ms` (default config is zero) to a larger value to improve timestamp synchronization if necessary.

Closing this ticket for now. Feel free to reopen if the question is not answered.
