### ISSUE TITLE
org.apache.kafka.streams.errors.ProcessorStateException:

### ISSUE THREAD

**Issue by waltercarmona9** [confluentinc/ksql#2262]
My Open Source Confluent Platform is UP but the second statement fail, can you help me?  

CREATE STREAM pageviews   (viewtime BIGINT,    userid VARCHAR,    pageid VARCHAR)   WITH 
(KAFKA_TOPIC='pageviews',         VALUE_FORMAT='DELIMITED');

SELECT pageid FROM pageviews LIMIT 3;

org.apache.kafka.streams.errors.ProcessorStateException: base state directory [/var/lib/kafka-streams] doesn't exist and couldn't be created

ksql> SHOW STREAMS;
 Stream Name        | Kafka Topic | Format
----------------------------------------------
 PAGEVIEWS          | pageviews   | DELIMITED
----------------------------------------------

**Comment by apurvam** [comment]
You can try updating the ksql-server.properties file and setting the `ksql.streams.state.dir` config to a writable location. For instance `ksql.streams.state.dir=/tmp/kafka-streams`. That should fix the error above.

**Comment by apurvam** [comment]
I'm going to close this. Please reopen if the issue persists once you set the state directory location to somewhere writable by the KSQL process.
