### ISSUE TITLE
Rest APIs should wait for previous commands to complete by default.

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#2268]
The initial work done to expose the `command sequence` to users defaults to no waiting for any previous commands to fail if not command sequence is provided with the request.

We should default to the safest option, which would be to wait for all previous requests to complete.

**Comment by big-andy-coates** [comment]
Has this been done @vcrfxia ?

**Comment by vcrfxia** [comment]
Yep, though it was done via transactional produces to the command topic (https://github.com/confluentinc/ksql/pull/3660) rather than using the command sequence number functionality.
