### ISSUE TITLE
KsqlConfig fails to propagate monitoring interceptor configs prefixed with "producer." or "consumer."

### ISSUE THREAD

**Issue by vcrfxia** [confluentinc/ksql#2279]
Configs prefixed with `confluent.monitoring.interceptor.` are successfully passed by KSQL to KStreams, as evidenced by this [test](https://github.com/confluentinc/ksql/blob/06877712f9bd2b8535f5f1af7d0b12df7597e43b/ksql-common/src/test/java/io/confluent/ksql/util/KsqlConfigTest.java#L197), but configs prefixed with `producer.confluent.monitoring.interceptor.` or `consumer.confluent.monitoring.interceptor.` fail to be passed through.

Thus, users with the same producer and consumer monitoring interceptor configs have the workaround of using the `confluent.monitoring.interceptor.` prefix, rather than `producer.confluent.monitoring.interceptor.` and `consumer.confluent.monitoring.interceptor.` separately, but this bug should be fixed so users may set different configs for the producer and consumer monitoring interceptors.

**Comment by stevenpyzhang** [comment]
I think the regression occurred as a result of changes in the resolveStreamConfig that filtered out unresolved `producer.` and `consumer.` prefixed configs.
https://github.com/confluentinc/ksql/blob/5.0.3-post/ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java#L317

https://github.com/confluentinc/ksql/blob/5.1.0-post/ksql-common/src/main/java/io/confluent/ksql/config/KsqlConfigResolver.java#L74

Are there any examples of configs using `producer.confluent.monitoring.interceptor.` and `consumer.confluent.monitoring.interceptor.` as a prefix? I couldn't find any in the documentation for those. I did find docs on `producer.interceptor.classes` and `consumer.interceptor.classes`
Is this something separate from this issue or are these the actual config values that should be used?
https://docs.confluent.io/current/control-center/installation/clients.html#kstreams

`confluent.monitoring.interceptor.` has some examples here
https://docs.confluent.io/current/control-center/installation/clients.html#general-options

On another note: `confluent.monitoring.interceptor.` prefixed configs are actually not resolved properly in the resolveStreamConfig function, but will still be passed through if the strict flag is false.
https://github.com/confluentinc/ksql/blob/5.1.0-post/ksql-common/src/test/java/io/confluent/ksql/config/KsqlConfigResolverTest.java#L166

**Comment by slepkin** [comment]
This still seems to be a problem in 5.2.2. When starting the server, we see `KsqlConfig` and `StreamsConfig`, but no `ProducerConfig` or `ConsumerConfig`. This makes it impossible to change the value of `acks`, which makes it difficult to guarantee at-least-once processing.

**Comment by big-andy-coates** [comment]
> This still seems to be a problem in 5.2.2. When starting the server, we see `KsqlConfig` and `StreamsConfig`, but no `ProducerConfig` or `ConsumerConfig`. This makes it impossible to change the value of `acks`, which makes it difficult to guarantee at-least-once processing.

hi @slepkin 

I'm not sure this is the case. We actually have a test to ensure you can set the acks, see https://github.com/confluentinc/ksql/blob/97fc956fb11bd35a156fa9377164fe389d489d0f/ksql-common/src/test/java/io/confluent/ksql/util/KsqlConfigTest.java#L581

If after double checking you're still having issues setting the ack level, can you raise a new Github issue please, as I don't believe your issue and this issue are related. Please include relevant info, e.g. KSQL version,  ksql-server.properties, commands youi're running, logs etc.

Thanks!
