### ISSUE TITLE
 Run mvn install get an error

### ISSUE THREAD

**Issue by chenxuefeng1207** [confluentinc/ksql#2298]
I git clone this code and run mvn clean install -X checkstyle:check integration-test but got an error:
java version:1.8.0_191
confluent version: 5.2.0-SNAPSHOT
<img width="1219" alt="2018-12-21 10 11 09" src="https://user-images.githubusercontent.com/23326132/50320853-31ceed00-0509-11e9-871d-fb182a778afd.png">

**Comment by spena** [comment]
I will close this issue as it is not seen any other ksql member. If you continue having problems, then re-open it or create a new issue.
