### ISSUE TITLE
Joining two streams with delay

### ISSUE THREAD

**Issue by eksantrik** [confluentinc/ksql#2306]
I have two streams that I want to join. Topic A and B to enrich my data. The challenge is that the records in B may arrive with some delay (up to an hour); and also not all the records in A may have a corresponding record in topic B because they are provided for the transactions optionally.

When I write my JOIN statement like this:
CREATE STREAM A_B AS SELECT A.*,B.* FROM A FULL OUTER JOIN B WITHIN 2 HOURS ON A.id = B.id;

I notice that the JOIN is conducted as soon as new A's arrive. My initial expectation was that "WITHIN 2 HOURS" phrase creates a specific window during which I should not expect any JOIN results before the time is up.

Is this the expected behavior? Did I run into a known issue? What would be the best option for me if:
- I do not want to miss any A records
- I do not want to miss any B records
- I do not want to miss any matches between A and B

Thanks,

**Comment by mjsax** [comment]
You won't miss any records and it's correct that you get a window of 2 hours. However, the join is executed eagerly (not delayed). For an outer join, this implies that a record A is first emitted as `A-null` but later when B arrives, A is still joined with B an `A-B` is emitted.

Read this blog post for more details: https://www.confluent.io/blog/crossing-streams-joins-apache-kafka/

**Comment by eksantrik** [comment]
Thank you. That really helped me.

I am also planning on using KTABLE to pull the STREAM results and write them in a Kafka Topic that will have the latest results of the JOIN based on a key. My goal is to be able to overwrite the JOINs with NULL on the right side with valid ones when the new B's arrive. 

I am having a hard time understanding how KSQL keeps a track of the latest values for a key. Do I have to use "Windows" to achieve this? Does this actually mean that I can expect to see only a single value in the Kafka Topic for a key if I use KTABLEs.

**Comment by blueedgenick** [comment]
> I am having a hard time understanding how KSQL keeps a track of the latest values for a key. Do I have to use "Windows" to achieve this? Does this actually mean that I can expect to see only a single value in the Kafka Topic for a key if I use KTABLEs.
Your last sentence there is correct - there's no need to use windowing to track "the latest value for a given key" as this is exactly what the KTABLE construct does: it keeps listening on a topic to build up the 'table' and retains within it only the latest record for each key. Note that this doesn't change _what's written in the source topic_, it's a logical construct.
Hope that helps!

**Comment by eksantrik** [comment]
Thanks. Yes, it does help but I am starting to think that what I am trying to achieve is not possible. In my case, when I do left joins between A and B with 1-hour window, I end up getting one event with (A1,null) first. When the B record arrives at my Kafka topic (5 minutes later), there is another join resulting with (A1,B1). So I end up with two events. My ultimate goal is to have a kafka topic to present my consumers only (A1,B1); not (A1,B1), (A1,null). If there is no B1, I will be ok having a single (A1,null) in my kafka topic, but if a B1 comes in, I will expect to see only (A1,B1).

My idea was to pull the kafka topic with (A1,B1), (A1,null) into a KTABLE with a proper key and write it back into a new kafka topic with (A1,B1) only. I see two challenges here 1) my Ktable will keep growing because most of my join records will be new records 2) KSQL won't be able to know when to stop expecting any new matches for A1 because there is no time limit.

Are there any features to support what I am trying to do?

Thanks

**Comment by mjsax** [comment]
It might be better to use a custom `transform()` with key-value store. Each time you receive a `(A1,null)` record, you put it into the store. If you get a `(A1,B1)` later, you delete the `(A1,null)` from the store and just forward `(A1,B1)`. Additionally, you can register a punctuation that emits `(A1,null)` at some point if no `(A1,B1)` was received.

**Comment by blueedgenick** [comment]
You're correct @eksantrik , KSQL doesn't know when your "last" record has arrived at the table, so what you end up with in the topic is *all* the output records the join has produced. There will be a future enhancement to support something closer to what you want, with a configurable "time to wait before sending out the latest join result record", but it's not currently scheduled to get worked on for the next version of KSQL. 
What i have seen some folks do in this situation is a simple KStreams program, similar to what Matthias described, if you're comfortable with a little java coding.

**Comment by apurvam** [comment]
FYI I created an issue to track the enhancement to support the KStreams suppress operator which should help here: https://github.com/confluentinc/ksql/issues/2315

**Comment by miguno** [comment]
Does that cover your questions thus far, @eksantrik ?

**Comment by eksantrik** [comment]
Yes, it does. Thank you
