### ISSUE TITLE
Add support for the KStreams suppress operator

### ISSUE THREAD

**Issue by apurvam** [confluentinc/ksql#2315]
Since the Apache Kafka 2.1.0 release, Kafka Streams has added the "suppress" operator, which enables users to emit the single aggregation value per window at a configurable point in time after the window elapses. Details here: https://cwiki.apache.org/confluence/display/KAFKA/KIP-328%3A+Ability+to+suppress+updates+for+KTables

We should add support for this operator and the associated semantics to KSQL as well.

**Comment by blueedgenick** [comment]
lots of related discussion in #1030 also.

**Comment by miguno** [comment]
@apurvam : IMHO this ticket here is a duplicate of https://github.com/confluentinc/ksql/issues/1030.

**Comment by apurvam** [comment]
@miguno indeed. Closing this out.
