### ISSUE TITLE
KSQL Rest API - Not Worked When Create Stream from Topic

### ISSUE THREAD

**Issue by ChenShuai1981** [confluentinc/ksql#2326]
I can execute the following ksql script in ksql cli shell, but when I switch to use ksql rest api, it reported error. Why? Is this my usage way problem? Thanks!

`ksql> CREATE STREAM DEV_DATASOURCE_JIAYIN_TAXCREDIT_STM WITH (KAFKA_TOPIC='dev_datasource_jiayin-taxcredit', VALUE_FORMAT='AVRO', TIMESTAMP='requestTime');

 Message        
----------------
 Stream created 
----------------`

`curl -X POST -H "Content-Type: application/vnd.ksql.v1+json" --data '{"ksql": "CREATE STREAM DEV_DATASOURCE_JIAYIN_TAXCREDIT_STM WITH (KAFKA_TOPIC='dev_datasource_jiayin-taxcredit', VALUE_FORMAT='AVRO', TIMESTAMP='requestTime');", "streamsProperties":{}}' http://xxxx:8088/ksql
`

> {"@type":"generic_error","error_code":40000,"message":"name is null","stackTrace":["io.confluent.ksql.parser.KsqlParser.buildAst(KsqlParser.java:66)","io.confluent.ksql.KsqlEngine.getStatements(KsqlEngine.java:501)","io.confluent.ksql.rest.server.resources.KsqlResource.handleKsqlStatements(KsqlResource.java:167)","sun.reflect.GeneratedMethodAccessor232.invoke(Unknown Source)","sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)","java.lang.reflect.Method.invoke(Method.java:498)","org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76)","org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148)","org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191)","org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:200)","org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)","org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)","org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)","org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)","org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)","org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)","org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)","org.glassfish.jersey.internal.Errors.process(Errors.java:316)","org.glassfish.jersey.internal.Errors.process(Errors.java:298)","org.glassfish.jersey.internal.Errors.process(Errors.java:268)","org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)","org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)","org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)","org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416)","org.glassfish.jersey.servlet.ServletContainer.serviceImpl(ServletContainer.java:409)","org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:584)","org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:525)","org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:462)","org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)","org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)","org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)","org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)","org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)","org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317)","org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)","org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)","org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)","org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)","org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219)","org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)","org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)","org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)","org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)","org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)","org.eclipse.jetty.server.Server.handle(Server.java:531)","org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)","org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)","org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)","org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)","org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)","org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)","org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)","org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)","org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)","org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)","org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)","org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)","java.lang.Thread.run(Thread.java:748)"]}

**Comment by blueedgenick** [comment]
i guess you'll have to escape the single quotes in sections like this: `KAFKA_TOPIC='dev_datasource_jiayin-taxcredit'` because you are also using single-quote characters to surround the request payload (`--data '{"ksql": ...}'`

**Comment by ChenShuai1981** [comment]
Thank you blueedgenick's suggestion. After change to use double-quote characters to surround the request payload with escape inner double-quote characters and keep single-quote characters it works now.

`curl -X POST -H "Content-Type: application/vnd.ksql.v1+json" --data "{\"ksql\": \"CREATE STREAM DEV_DATASOURCE_JIAYIN_TAXCREDIT_STM WITH (KAFKA_TOPIC='dev_datasource_jiayin-taxcredit', VALUE_FORMAT='AVRO', TIMESTAMP='requestTime');\", \"streamsProperties\":{}}' http://xxxx:8088/ksql`

**Comment by vdweij** [comment]
awesome... was looking for this... 

I do think you're escaping too much though... only the value in ksql needs to be escaped:

`
curl -X POST -H "Content-Type: application/vnd.ksql.v1+json" --data '{"ksql": "CREATE STREAM DEV_DATASOURCE_JIAYIN_TAXCREDIT_STM WITH (KAFKA_TOPIC=\'dev_datasource_jiayin-taxcredit\', VALUE_FORMAT=\'AVRO\', TIMESTAMP=\'requestTime\');", "streamsProperties":{}}' http://xxxx:8088/ksql
`
