### ISSUE TITLE
Join window having timed out triggers a new message to separate topic

### ISSUE THREAD

**Issue by danrooke** [confluentinc/ksql#2343]
I have two topics that I want to join for a particular set of use cases but for these use cases I only care about the scenario where I've received a message on topic A but not received a message on topic B at the end of the given time window for the join. If this condition is met, then I should be able to define a message that is produced to a third topic C. The data type for this new message, the schema (if applicable), the key, number of partitions, replication factor and the field values (perhaps some static values not from the input topics) need to be able to be specified.

An example would be:

Topic A: messages stating that customer has browsed item page
Topic B: messages stating that customer has placed an order for item

Minute 0: Customer browses item page, triggering message to be produced to topic A and triggers the start of 30 minute window
Minute 30: 30 minute window has finished and customer has still not placed an order for the item and new message is produced to topic C stating that customer has not placed an order for item but has browsed item page more than 30 minutes ago
Minute 30: Topic C message for customer is consumed by a notification sending service to encourage customer to place the order

I don't believe there is any way to achieve this currently with KSQL so I'm raising this as a feature request. If there is a way to do this already, then please let me know.

Thanks,
Dan

**Comment by miguno** [comment]
Thanks for the feature request and the good summary, @danrooke.

Quick question: How would you expect late-arriving records to be handled in this scenario?

Imagine that a late-arriving record in topic B ("customer has placed an order for item") with a timestamp of 25 minutes, which means it falls into the closed 30min window.  What should happen to this record?

**Comment by mjsax** [comment]
@danrooke It seems you would want to do a stream-stream left-join, and filter all "inner join" results, and only emit "left join" result. In current releases, there is one issue with "spurious" left/outer join results, but this issue was fixed in Apache Kafka recently, and should be shipped with ksqlDB 0.19 (cf https://issues.apache.org/jira/browse/KAFKA-10847).

Closing this ticket as it seems it will be possible soon to do this. Feel free to re-open or follow up with questions/comments.
