### ISSUE TITLE
Add SPLIT function

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#2349]
It would be useful for data wrangling if KSQL supported a `SPLIT` function. Given this source JSON message: 

```
{
"timestamp": "2019-01-14T14:34:47.617Z",
"message": "20190114T063447-0800,dm-2,SSD2T-backarea,1.99,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00",
"node": "hostnameA"
}
```

it is desirable to be able to separate the `message` field into separate components delimited by comma, e.g.

`SELECT SPLIT(MESSAGE,',')[0], SPLIT(MESSAGE,',')[1], SPLIT(MESSAGE,',')[2] FROM FOO` 

would return

field1 |field2 |field3 
-|-|-
20190114T063447-0800|dm-2|SSD2T-backarea

**Comment by superwhykz** [comment]
Thank Robin!

**Comment by spena** [comment]
Should regular expressions be allowed on the split() UDF?

**Comment by spena** [comment]
What about the resulted array? Some RDBMS return empty characters in the array if the separator string is present in the beginning of the source string. For instance:

split("--y", "-") will return ["", "", "y"]

Should those initial empty strings omitted or left there?

Btw, I see there exists a EXTRACTJSONFIELD() UDF in KSQL. Would that work for the use case you're proposing?
