### ISSUE TITLE
Incorrect error message - 'Topic already registered' should be "Stream"

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#2374]
If a **Stream** already exists with the same name, the error message returned uses the term `Topic`, which is incorrect. 

```
ksql> SHOW STREAMS;

 Stream Name     | Kafka Topic     | Format
--------------------------------------------
 MixedCaseStream | MixedCaseStream | JSON
 PCAP            | localpcap       | JSON
 SOURCE          | SOURCE          | JSON
 CASE01          | CASE01          | JSON
--------------------------------------------

ksql> CREATE STREAM PCAP (layers struct<frame struct<frame_frame_interface_id varchar>>) WITH (KAFKA_TOPIC='localPCAP', VALUE_FORMAT='JSON');
Topic already registered: PCAP
```

This should read at the very least: 

```
Stream already registered: PCAP
```

Or perhaps "Stream already exists: PCAP". 

This is important because otherwise, it implies to the user that a topic can only be registered once, which is not the case.

**Comment by big-andy-coates** [comment]
I don't think it should say:

> Stream already registered: PCAP

PCAP is the name of the registered topic, and that may be there because a _table_ registered it, or that the user is using the undocumented `REGISTER TOPIC` functionality. At least I think that is the case. @hjafarpour care to comment more? 

That being the case, I think a better error would be:

> Failed to create stream because there is already an entity named PCAP registered.

Or if we don't care about `REGISTER TOPIC` then maybe:

> Failed to create stream because there is already a stream or table named PCAP registered.

Or simply:

> Name already in use: PCAP

We can even query the metastore to work out what type it is..

> Name already in use: Table PCAP.

Thoughts?

**Comment by rmoff** [comment]
To be clear: 

* The object I'm creating is `PCAP`
* The topic from which it is created is `localPCAP`. 

So at the moment the error is point-blank wrong

    Topic already registered: PCAP

The *topic* is `localPCAP`, not `PCAP`. 


Any of your alternatives sound fine to me, my preference is probably the nice and clear: 

    Failed to create stream because there is already a stream or table named PCAP registered.

Ideally we should try to fix this for 5.2 if possible even if that means a simpler fix (vs. querying the metastore etc etc).

**Comment by big-andy-coates** [comment]
To be clear: ;) . 
* KSQL has the concept of a registered topic. (It's not documented by the syntax supports `REGISTER TOPIC` statements and the code base is littered with the implementation.
* So the error talking about a KSQL _registered_ topic called `PCAP`, that maps to a _Kafka_ topic called `localPCAP`.

Hence the misleading error message.

@spena is looking to fix this in 5.2.

**Comment by rmoff** [comment]
Makes sense, clear now ;-)
Thanks @big-andy-coates

**Comment by spena** [comment]
So just to confirm, I will choose the `Failed to create stream because there is already a stream or table named PCAP registered.` message when the stream already exists. 

Does this happen when attempting to create a table too? If so, I may fix the message for tables in the same patch.

**Comment by apurvam** [comment]
@spena are you still waiting for info here? It will be trivial to test if the issue also exists for tables (I assume it does), and fixing both together makes sense.

**Comment by apurvam** [comment]
NVM, I see you have a PR out already :)

**Comment by rmoff** [comment]
@spena I'm seeing this in 5.2.1 when I try to create a table that already exists: 

```
ksql> CREATE TABLE STANOX WITH (KAFKA_TOPIC='CORPUS_BY_STANOX', VALUE_FORMAT='AVRO', KEY='STANOX');
Topic already registered: STANOX
```

Should this already be fixed per above discussion? thanks.

**Comment by spena** [comment]
And probably this was a dummy mistake from my side. The PR was merged in the `master` branch only, which belonged to the `5.3.0-SNAPSHOT`. 5.2.x versions do not have this fix.

Do you want a backport to 5.2.2 or is fine to wait until 5.3.0 is released?

**Comment by rmoff** [comment]
It can probably wait until 5.3 since it's just an annoyance than missing functionality. Thanks @spena.
