### ISSUE TITLE
System generated names do not check for conflicts

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#2401]
Create a stream with a new column, no name supplied: 

    ksql> CREATE STREAM DLQ_06_MONITOR AS SELECT 1, MSG FROM dlq_file_sink_06__01;

    Message
    ----------------------------
    Stream created and running
    ----------------------------

New column is called `KSQL_COL_0`. 

    ksql> DESCRIBE DLQ_06_MONITOR;

    Name                 : DLQ_06_MONITOR
    Field      | Type
    ----------------------------------------
    ROWTIME    | BIGINT           (system)
    ROWKEY     | VARCHAR(STRING)  (system)
    KSQL_COL_0 | INTEGER
    MSG        | VARCHAR(STRING)
    ----------------------------------------
    For runtime statistics and query details run: DESCRIBE EXTENDED <Stream,Table>;

If a new query is created from this with _another_ new column, KSQL doesn't pick an available column name (e.g. `KSQL_COL_1`) but defaults to `KSQL_COL_0` which is already used: 

Example 1: 

    ksql> CREATE STREAM FOO AS SELECT 1, KSQL_COL_0, MSG FROM DLQ_06_MONITOR;
    Cannot create field because of field name duplication KSQL_COL_0
    ksql> CREATE STREAM FOO AS SELECT 1 AS MANUAL_COLUMN_NAME, KSQL_COL_0, MSG FROM DLQ_06_MONITOR;

    Message
    ----------------------------
    Stream created and running
    ----------------------------
    ksql>

Example 2: 

    ksql> SELECT WINDOWSTART(),KSQL_COL_0, COUNT(*) FROM DLQ_06_MONITOR WINDOW TUMBLING (SIZE 1 MINUTE) GROUP BY KSQL_COL_0;
    Failed to prepare statement: Cannot create field because of field name duplication KSQL_COL_0
    Caused by: Cannot create field because of field name duplication KSQL_COL_0

    ksql> SELECT WINDOWSTART() AS START_TS, KSQL_COL_0, COUNT(*) FROM DLQ_06_MONITOR WINDOW TUMBLING (SIZE 1 MINUTE) GROUP BY KSQL_COL_0;
    1548644460000 | 1 | 9
    1548645120000 | 1 | 4

**Comment by vpapavas** [comment]
In PSQL, multiple non-aliased items (literals, function calls) are allowed in the SELECT clause but not when used in a CREATE AS. So, example 1 from above fails correctly. Example 2 however would not fail in PSQL.

Summary of differences between PSQL and KSQL: 1) PSQL uses the same reserved keyword (?column?) for all columns corresponding to non-aliased literals. 2) PSQL uses the function name for non-aliased function calls. 3) PSQL allows the appearance of the same column name in the result of a SELECT clause as long as it is not used in a CREATE statement.  5) Creating a table with multiple non-aliased literal columns or function calls is not permitted in PSQL.  KSQL however allows it.
 
Below I describe similarities and differences with examples. 

**Similarities**

Example 1 (same error): 
```
psql> CREATE TABLE test AS SELECT  '?column?',1;
2019-08-08 13:59:08.769 PDT [8252] ERROR:  column "?column?" specified more than once
```

```
ksql> CREATE TABLE test AS SELECT  1,KSQL_COL_0 FROM literals;
Cannot create field because of field name duplication KSQL_COL_0
```

**Differences**

Example 2 (no error in PSQL):
```
>psql SELECT "?column?",'?column?' FROM literals;
 ?column? | ?column?
----------+----------
        1 | ?column?
(1 row)
```

```
ksql> SELECT 'KSQL_COL_0', "KSQL_COL_0" FROM literals;
Cannot create field because of field name duplication KSQL_COL_0
```

Example 3 (No error in KSQL):

```
psql> CREATE TABLE test AS SELECT 1,2 FROM literals;
2019-08-08 13:35:21.366 PDT [8252] ERROR:  column "?column?" specified more than once
```
```
ksql> CREATE TABLE  test AS SELECT 1,2 FROM literals;
 Message
---------------------------
 Table created and running
---------------------------
```

**Comment by big-andy-coates** [comment]
Hi all,

@vpapavas, are you maybe getting hung up on the example @rmoff has used to highlight an issue, rather than the issue being highlighted?   The issue Robin is pointing out is that ksqlDB is not ensuring system generated column names are unique in C*AS statements, not that non-aliased literals are allowed in C*AS statements.

Let's rewrite the example without literals:

```sql
CREATE STREAM DLQ_06_MONITOR AS SELECT LEN(MSG), MSG FROM dlq_file_sink_06__01;
-- schema: ROWKEY -> KSQL_COL_0, MSG

CREATE STREAM FOO AS SELECT SUBSTRING(0, 1, MSG), KSQL_COL_0, MSG FROM DLQ_06_MONITOR;
-- Fails because system generated name for `SUBSTRING(0, 1, MSG)` clashes with existing column in `DLQ_06_MONITOR`.
```

Luckily however, I've already fixed this recently as part of the `any key name` feature and there are QTT tests covering this, e.g. 

```json
{
      "name": "should handle sources with generated column names",
      "statements": [
        "CREATE STREAM INPUT (KSQL_COL_3 INT KEY, KSQL_COL_2 INT, KSQL_COL_4 INT) WITH (kafka_topic='input', value_format='JSON');",
        "CREATE STREAM OUTPUT as SELECT KSQL_COL_3, KSQL_COL_2, ABS(KSQL_COL_2), ABS(KSQL_COL_2), ABS(KSQL_COL_2) FROM INPUT;"
      ],
      "inputs": [
        {"topic": "input", "key": 1, "value": {"KSQL_COL_2": 2, "KSQL_COL_4": 4}}
      ],
      "outputs": [
        {"topic": "OUTPUT", "key": 1, "value": {"KSQL_COL_2": 2, "KSQL_COL_0": 2, "KSQL_COL_1": 2, "KSQL_COL_5": 2}}
      ]
    }
```

However, as @vpapavas points out, ksqlDB does not require literals to be aliased in C*AS statements. Personally, I don't see an issue with this, however, maybe others do - if so, maybe raise a github issue to track that specific issue?
