### ISSUE TITLE
Add date arithmetic support to KSQL

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#2413]
It would be useful if KSQL supported date arithmetic. This would serve at least two cases: 

1. Compare a date to offset current date (requires #2412) "is the record within the last day"
2. Compare two dates in a record "is field x more than two days after field y"

See also #1968 

Refs: 
* MySQL: supports [`TIMESTAMPADD`](https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_timestampadd) (plus a bunch of others)
* Postgres: Does a lot of calculations natively, with support for [`INTERVAL`](https://www.postgresql.org/docs/9/functions-datetime.html)

**Comment by robert-ostensen** [comment]
interval support would be amazing. I would also like to see something like date_trunc from postgres, it is currently possible by casting to string then re-parsing but that seems less than ideal for both readability and a performance

**Comment by agavra** [comment]
@jzaralim is this complete?

**Comment by jzaralim** [comment]
This is complete!
