### ISSUE TITLE
Clarify error message

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#2455]
(c.f. https://stackoverflow.com/questions/54754828/how-to-get-partition-key-or-other-columns-when-group-by-is-used-in-ksql/54765619#54765619)

The error message:  

> Group by elements should match the SELECT expressions.

could be improved: 

1. Consistent casing of statements, i.e. `GROUP BY` not `Group by`
2. Consistent terminology; `elements` vs `expressions`

**Comment by big-andy-coates** [comment]
Hey Robin,

New error message that comes with the above PR would be:

```
Non-aggregate SELECT expression(s) must be part of GROUP BY: [event_stream.event_id]
```

Happy to take feedback on improving this...

**Comment by rmoff** [comment]
@big-andy-coates I think this looks good! Closing.
