### ISSUE TITLE
Consecutive calls to register topic should fail before enqueueing

### ISSUE THREAD

**Issue by agavra** [confluentinc/ksql#2460]
**Issue**: With `KsqlResource` it is possible that the same client can issue a `REGISTER TOPIC` command for the same topic with different parameters and both will be enqueued onto the command topic if the first has not yet been updated in the meta store. This potentially extends to all other distributed commands that have metastore implications (CTAS/CSAS).

**Correct Behavior**: only the first of the two succeeds

**Possible Fix**: _Every_ command, including those that are distributed, should wait for previous command to finish (e.g. call `waitForPreviousDistributedStatementToBeHandled`)

**Comment by stevenpyzhang** [comment]
https://github.com/confluentinc/ksql/pull/3660 fixes this. The DistributingExecutor waits for all previous commands to finish before enqueueing new commands.
