### ISSUE TITLE
Stream-table LEFT JOIN with ROWKEY from GROUP BY field1, field2

### ISSUE THREAD

**Issue by delemercier** [confluentinc/ksql#2479]
Hello,

I want to join a stream with a table containing a group by with multiple fields.

The keys are identical but the group by with multiple fields generated a ROWKEY with concatenated fields.
The ROWKEY being different, the join is KO with the error:

```
Source table (TP) key column (KSQL_INTERNAL_COL_0|+|KSQL_INTERNAL_COL_1) is not the column used in the join criteria (USERID).
```

Is it the normal behaviour ?

Here are quick steps to reproduce (version tried: 5.1.1 and 5.1.2) :
```
./bin/ksql-datagen quickstart=users
./bin/ksql-datagen quickstart=pageviews
./bin/ksql
```

```sql
CREATE STREAM s_pageviews \
  (userid VARCHAR, \
   registertime BIGINT, \
   pageid VARCHAR) \
  WITH (KAFKA_TOPIC='pageviews_kafka_topic_json', \
        VALUE_FORMAT='JSON', \
        TIMESTAMP='registertime', \
        KEY = 'userid');

CREATE TABLE t_pageviews AS \
SELECT userid, pageid, count(*) as count \
FROM s_pageviews \
GROUP BY userid, pageid;

CREATE STREAM s_users \
  (userid VARCHAR, \
   registertime BIGINT, \
   regionid VARCHAR) \
  WITH (KAFKA_TOPIC='users_kafka_topic_json', \
        VALUE_FORMAT='JSON', \
        TIMESTAMP='registertime', \
        KEY = 'userid');

SELECT tp.userid, su.regionid \
FROM s_users su \
LEFT JOIN t_pageviews tp ON tp.userid = su.userid;
```

**Keys detail:**

```
ksql> select ROWKEY, userid from s_users;
User_5 | User_5
User_8 | User_8
User_5 | User_5

ksql> select ROWKEY, userid from t_pageviews;
User_4|+|Page_91 | User_4
User_6|+|Page_99 | User_6
User_4|+|Page_58 | User_4
```

Thanks for your work, KSQL is pretty amazing !

**Comment by miguno** [comment]
This is, unfortunately for your example, the expected behavior of KSQL today.  See https://docs.confluent.io/current/ksql/docs/developer-guide/partition-data.html#partition-data-to-enable-joins.

As you showed, the ROWKEYs don't match.  That's because the key (= Kafka message key) for `t_pageviews` is a composite of `userid` and `pageid`, as defined via `GROUP BY userid, pageid` in the table's CREATE statement.

```
ksql> select ROWKEY, userid from s_users;
User_5 | User_5
User_8 | User_8
User_5 | User_5

ksql> select ROWKEY, userid from t_pageviews;
User_4|+|Page_91 | User_4
User_6|+|Page_99 | User_6
User_4|+|Page_58 | User_4
```

**Comment by delemercier** [comment]
Thanks for you answer.

Is there a way in KSQL to create a topic from the table topic which does not have the concatenated ROWKEY ?

I tried to create a STREAM with partition by and a TABLE but without success, the ROWKEY is still the same.

**Comment by big-andy-coates** [comment]
HI @delemercier,

What you're asking is possible in your example by dropping the `pageid` from the `select` and `group by` clauses of the `create table` statement, as `pageid` is ultimately not required in the join. 

However, I have a feeling this doesn't answer your question as I have a feeling your _real_ problem is different and you're just using the demo topics to make raising the issue easier.

What you look to be doing is creating a table with two non-aggregate fields, 'userId' and 'pageId' in your example.  Both fields _must_ be in the ROWKEY for this to work.  Tables are backed by [compacted topics](https://kafka.apache.org/documentation/#compaction) in Kafka.  If only one field was in the key, say the 'userId', then after compaction had run only one record for that userId would exist in the topic, and hence only one row in the KSQL table.

It doesn't actually make conceptual sense to join a table with two keys against a stream with one key.   This is why KSQL is rejecting it.

If you want you can raise a new issue, (and link to this one), with the details of the actual problem you're trying to solve and we may be able to help more.
