### ISSUE TITLE
use ksql query other kafka cluster but not in Confluent Platform 

### ISSUE THREAD

**Issue by Knight-Wu** [confluentinc/ksql#2495]
Hi, i want to use ksql to query other kafka cluster 's topic which is already started,  by using the PRINT statement, Is there any ways to do this ? 
I dont want to use the kafka and zk in Confluent Platform , because these clusters are already existed, i  just want to use somehow like sql to query data between serveral  topics in production environment , and output , so i can be sure about the production data form, then i can make my jstorm code more Reliable.
Thank you first !

**Comment by rmoff** [comment]
Yes, you can point your KSQL server at other Kafka clusters, by using a different `bootstrap.servers` value. See https://docs.confluent.io/current/ksql/docs/installation/server-config/index.html. 

Your other Kafka cluster must be of a supported version: https://docs.confluent.io/current/ksql/docs/installation/installing.html#supported-versions-and-interoperability

**Comment by Knight-Wu** [comment]
@rmoff thank you, i also want to find out whether  ksql stream or table impact on kafka cluster performance? Is there any report or blog ?
