### ISSUE TITLE
Docs and follow-up to sink partitions/replicas change

### ISSUE THREAD

**Issue by vcrfxia** [confluentinc/ksql#2539]
Follow-up work is needed for [this PR](https://github.com/confluentinc/ksql/pull/1930):

- Docs updates. Docs/files that need to be updated include docs/installation/server-config/config-reference.rst, docs/installation/cli-config.rst, and [this one](https://docs.confluent.io/current/cloud/connect/ksql-cloud-config.html), also the upgrade notes, and the comments in KsqlConfig.java. Need to make it explicit that users should no longer set the properties `ksql.sink.partitions` and `ksql.sink.replicas`.

- Explicitly disallow setting `ksql.sink.partitions` and/or `ksql.sink.replicas` through the CLI (and print an error message if a user tries to do this).

- Explicitly disallow setting `ksql.sink.partitions` and/or `ksql.sink.replicas` in server configs (and log a warning message if a user tries to do this).

- Verify that users are unable to set `ksql.sink.partitions` and/or `ksql.sink.replicas` as part of a headless mode script.

- Add a new config property (e.g., `KSQL_INTERNAL_TOPIC_REPLICAS`) which users can set to control the number of replicas for KSQL topics such as the command topic and config topic. Add docs around these. This is required because the number of replicas for these topics is currently determined by the `ksql.sink.replicas` config, which we are trying to deprecate.

- Once the new config property mentioned above has been added, update the muckrake system tests to use this new config rather than the legacy ones.

These changes are required before the next release because currently, if a user has either `ksql.sink.replicas` or `ksql.sink.partitions` set but **not both**, any CSAS/CTAS statement they run (without specifying PARTITIONS or REPLICAS in the WITH clause) results in a `NullPointerException` in `KsqlStructuredDataOutputNode#getSinkTopicPropertiesLegacyWay()`. (Additional discussion [here](https://github.com/confluentinc/ksql/pull/2535).)

**Comment by hjafarpour** [comment]
Thanks @vcrfxia  for filing the issue. As we discussed I will update the docs in a follow up PR.
For the remaining items, I will add fixes once I finalize the design.
