### ISSUE TITLE
Extend ROUND() and FLOOR() to include number of decimal places to round up/down

### ISSUE THREAD

**Issue by spena** [confluentinc/ksql#2583]
The functions ROUND() and FLOOR() currently accepts one single argument which will be rounded up or down to an integer.

We should extend these functions to accept a second argument that specifies the number of decimal places to round the value. This will be useful when users want to convert DECIMAL types (See https://github.com/confluentinc/ksql/issues/842) and a default rounding happens during conversion to a smaller scale.

Syntax to support:
- ROUND(n [, d]) where _n_ is the value to round up, and _d_ is a number indicating up to how many decimal places In will be rounded.
i.e.
> ROUND(3.6456, 3) = 3.646
> ROUND(3.6456, 2) = 3.65
> ROUND(3.6456) = 4

- FLOOR(n [, d]) where _n_ is the value to round down, and _d_ a number indicating the number of places after the decimal to which to round downward.
i.e
> FLOOR(3.6456, 3) = 3.645
> FLOOR(3.6456, 2) = 3.64
> FLOOR(3.6456) = 3

**Comment by agavra** [comment]
This was fixed by #3404 - thanks @purplefox !
