### ISSUE TITLE
Fix identifiers in KSQL.

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#2589]
KSQL can't handle some identifiers, (stream/table/topic/column names), e.g. this is because identifiers need to be valid Java identifiers, which is an avoidable restriction.  To make matters worse, quoted identifiers aren't fully supported and we actually recommend NOT using them because of this.

This restricts the data KSQL can work with.

**Comment by apurvam** [comment]
Related to #677

**Comment by big-andy-coates** [comment]
closing, as covered by quoted identifiers work

**Comment by robcowart** [comment]
@big-andy-coates this issue and a few others that I have come across while trying to solve problems with fields name that are the same as KSQL keywords have been closed with the reason "closing, as covered by quoted identifiers work".

Can you please mention the issue IDs of this "quoted identifiers work", so other like myself don't hit dead ends like this?

Thanks.

**Comment by agavra** [comment]
@robcowart - I don't think there's a single ticket that describes all the work that was done (there are a ton of issues such as #677 #1287 #1446 #1537 #1765 #1888 #2121 #2171 etc...). Rather, if there's any issue you are running into where the statement doesn't allow you to use reserved names, you should add either double quotes `"` or backticks \` to your column name (e.g. `CREATE STREAM foo ("STREAM" VARCHAR)`)
