### ISSUE TITLE
Have a statement for registering types in KSQL

### ISSUE THREAD

**Issue by rodesai** [confluentinc/ksql#2597]
We should add a statement for registering custom types in KSQL. Something like:

```
REGISTER TYPE COOL_CUSTOM_TYPE STRUCT<X INT, Y STRING>;
```

Then, support using the type in your DDLs:

```
CREATE STREAM FOO (COL COOL_CUSTOM_TYPE) WITH (...);
```

It seems likely that some complex types will be reused frequently by users/organizations, and it can be really cumbersome to have to type these out manually every time. This would also come in handy when we want to support statements for registering custom functions.

**Comment by agavra** [comment]
This is implemented and will be released in the next KSQL version.
