### ISSUE TITLE
Roadmap for additional serialization formats

### ISSUE THREAD

**Issue by martinxsliu** [confluentinc/ksql#260]
Hi there, I'm super excited for the potential ksql can bring. I'm curious to hear what the roadmap looks like for adding new serialization formats. In particular we would require protobuf support to integrate with our existing topics.

**Comment by hjafarpour** [comment]
Hi Martin,

We have been talking about adding more format support. Currently we have JSON and Delimited and Avro is coming soon. No ETA on protobuf yet but I would encourage you to contribute it :)
You can check the serde package for JSON, DELIMITED and AVRO in 'io.confluent.ksql.serde' under ksql-core for example.
Please let me know if you are interested in contributing.
Thanks,
--Hojjat

**Comment by rmoff** [comment]
Protobuf proposal: https://github.com/confluentinc/ksql/pull/1472
