### ISSUE TITLE
KSQL 5.2.X breaks CAST(bigint_col as DOUBLE) if there are NULL values

### ISSUE THREAD

**Issue by jiriklein** [confluentinc/ksql#2632]
Hi, I upgraded our platform from 5.1.2 to 5.2.1 and noticed that some of our streams stopped passing data. I isolated this to the CAST function, specifically CAST(bigint_column as DOUBLE) - first few entries in my stream had null value in the bigint_column and this causes the ksql to silently "fail" and not pass any data. 
However, when I run select cast(bigint_column as DOUBLE) from mystream where bigint_column is not null, this query works perfectly. 
Please note my queries work on version 5.1.2, but not on 5.2.0 or 5.2.1.
Hope this helps

**Comment by jiriklein** [comment]
I get the same behaviour as if I am running `select another_column, cast(cast(null as varchar) as double)` from my stream. In other words, no results whatsoever. Running `select cast(null as double)` directly gives NullPointerException.

**Comment by rmoff** [comment]
Hi @jiriklein , thanks for reporting this. Do you happen to have the data and queries to reproduce this?

**Comment by jiriklein** [comment]
Hi @rmoff,
Yes, happy to provide a sample:

```
ksql> print 'gps_stream' from beginning limit 2;
Format:JSON
{"ROWTIME":1554409256334,"ROWKEY":"payload","status":["value1", "value2"],"id":"3"}
{"ROWTIME":1554409256334,"ROWKEY":"payload","lat":34406310,"lon":-69094580,"id":"3"}

ksql> describe gps_stream;
Name                 : GPS_STREAM
 Field   | Type                      
-----------------------------------------
 ROWTIME | BIGINT           (system) 
 ROWKEY  | VARCHAR(STRING)  (system) 
 LAT     | BIGINT                    
 LON     | BIGINT                    
 ID 	 | VARCHAR(STRING)           
 STATUS  | ARRAY<VARCHAR(STRING)>    
-----------------------------------------

ksql> select * from gps_stream limit 1;
1554409412918 | payload | 34403609 | -69093300 | 11 | null

ksql> select id, cast(lat as DOUBLE) from gps_stream;
```
(this returns nothing if I run from beginning, where there are null values for lat column)

**Comment by rmoff** [comment]
Thanks @jiriklein. Can you check the KSQL Server log for when you run this query with no results - are there errors in it?

**Comment by jiriklein** [comment]
Hi @rmoff - I'm running this in Docker - no errors relating to my stream when running `docker logs ksql-server`. I then had a look in ksql-server container in `\usr\logs` and found the following:
`[2019-05-10 14:29:42,154] WARN Query terminated due to exception:org.eclipse.jetty.io.EofException (io.confluent.ksql.rest.server.resources.streaming.QueryStreamWriter:88)` - Hope this helps.

**Comment by big-andy-coates** [comment]
I can confirm this is an issue. Working on a fix.
