### ISSUE TITLE
Improve error message when not running queries in headless mode

### ISSUE THREAD

**Issue by spena** [confluentinc/ksql#2646]
The following error message is displayed when running statements in headless mode without having any persistent query: `The SQL file did not contain any queries`

That message is misunderstood as there are single queries in a file, even if they do not make sense to have in headless mode, the message confuses users (especially new users).

An improvement could be: `The SQL file does not contain any INSERT or CREATE statements with persistent queries`

**Comment by ouertani** [comment]
Pull request: https://github.com/confluentinc/ksql/pull/2684

**Comment by big-andy-coates** [comment]
Fixed by #Fixes #2646
