### ISSUE TITLE
io.confluent.ksql.parser.SqlBaseParser does not exist

### ISSUE THREAD

**Issue by liuxunorg** [confluentinc/ksql#265]
io.confluent.ksql.parser.SqlBaseParser does not exist.

**Comment by hjafarpour** [comment]
@liuxunorg It's a class that is generated by ANTLR. You can find it in the target folder in ksql-core.

**Comment by miguno** [comment]
@liuxunorg :  I suppose you created this ticket because you tried to find the sources for `SqlBaseParser`, right?  If so, see @hjafarpour's answer.  If instead you ran into an error or warning message relating to `SqlBaseParser`, please clarify your question.

**Comment by liuxunorg** [comment]
thank you.

Compile SqlBase.g4 with ANTLR, generate a io.confluent.ksql.parser.SqlBaseParser.
but, found and less SqlBaseBaseVisitor.I still lack what？
