### ISSUE TITLE
Docker tutorial docker-compose.yml references old image versions

### ISSUE THREAD

**Issue by TheoAndersen** [confluentinc/ksql#2685]
Following the [basic-docker tutorial ](https://docs.confluent.io/current/ksql/docs/tutorials/basics-docker.html#ksql-quickstart-docker), i got ```bad request```on pretty much all KSQL CLI requests.

It seems that ```docs/tutorials/docker-compose.yml``` for branch 5.2.1-post (which you need to use, per description in the tutorial) - uses the 5.0.0 version of the docker-images, which dosen't work with the docker-snippets for KSQL-CLI in the tutorial, asking to bring up ```confluentinc/cp-ksql-cli:5.2.1```.

Upping the versions in the docker-compose.yml to 5.2.1, seems to do the trick.

**Comment by apurvam** [comment]
@vcrfxia can you take care of this (as on call).

**Comment by vcrfxia** [comment]
Thanks for reporting this, @TheoAndersen ! I've applied your suggested fix: https://github.com/confluentinc/ksql/pull/2691 I haven't managed to uncover why the 5.2 CLI receives bad responses from the 5.0 server, but I'll track that issue separately and mark this one as resolved for now. Thanks again!
