### ISSUE TITLE
DROP STREAM can be used to drop a TABLE

### ISSUE THREAD

**Issue by uwegeercken** [confluentinc/ksql#269]
create a table:
command: CREATE table users_count as select user, count(*) from users group by user;
response: Table created and running

drop:
command: drop stream users_count;
response: Source USERS_COUNT was dropped

result: users_count table is dropped

**Comment by hjafarpour** [comment]
@uwegeercken Thanks for the feedback. We will fix it asap!

**Comment by apurvam** [comment]
Fixed by #444
