### ISSUE TITLE
"Query terminated" not appropriate

### ISSUE THREAD

**Issue by uwegeercken** [confluentinc/ksql#270]
when running a query in ksql such as:

```
SELECT * FROM users
```

and then when you press Ctrl-C the message "Query terminated" appears. The wording is inappropriate because the query continues to run as documented and as can be seen using "show queries".

A better wording would be: "Query output interrupted" or maybe "Query output stopped".

**Comment by hjafarpour** [comment]
@uwegeercken Actually the query is terminated. SELECT queries are transient queries where the results are just streamed to the console. When you use Ctrl+C to stop it, the corresponding Streams app will be closed and won't run anymore.
On the other hand persistent queries are CREATE STREAM AS SELECT and CREATE TABLE AS SELECT queries where the results are persisted in a stream or table with a kafka topic. These queries will keep running until you terminate them with TERMINATE statement.
