### ISSUE TITLE
How to deployment Client-server mode

### ISSUE THREAD

**Issue by zhuxt2015** [confluentinc/ksql#272]
I had read ksql's document but not found the illustrate

**Comment by hjafarpour** [comment]
@zhuxt2015 Yes, we will docs for client-server mode soon. In the meantime you can follow these steps to try it:
1. Start one or more servers using the following command:
$ ./bin/ksql-server-start /path/to/ksql_server1.properties

A sample properties file is as follows:

ksql.cluster.id=ksql_app_tests
application.id=ksql_app_tests
bootstrap.servers=localhost:9092
listeners=http://localhost:8080

Note that for each server you need a properties file and the listeners value should be unique.

2. In a new terminal window start a cli and connect to one of the servers by passing it's listener address:

$ ./bin/ksql-cli remote http://localhost:8080

**Comment by hzxhan** [comment]
to start ksql server:
./bin/ksql-server-start  ./config/ksqlserver.properties
