### ISSUE TITLE
start ksql throw FileNotFoundException 

### ISSUE THREAD

**Issue by xxh2000** [confluentinc/ksql#274]
when I used command `bin/ksql-cli` local to start ksql, it throws a `FileNotException`. which told me that it can't find `xxx/ksql-cli-0.1-SNAPSHOT-package/config/log4j-file.properties`. I checked the project and found that there was no config directory in `ksql-cli-0.1-SNAPSHOT-package` while a etc directory after I package the project . So what can I do to solve this problem?

**Comment by hjafarpour** [comment]
@xxh2000 Which OS are you using to run KSQL?

**Comment by xxh2000** [comment]
I used Win7 to package KSQL Project and used CentOS to run it .  Is there any  question?

**Comment by miguno** [comment]
Closed because of inactivity.  A lot of changes and improvements have been made since, so it is very likely that this problem doesn't exist any more.
