### ISSUE TITLE
KSQL risk estimation

### ISSUE THREAD

**Issue by KirillMoizik** [confluentinc/ksql#276]
I read a warning about not using  KSQL in a production environment. I would like to know what are the risks involved in this. I would love to use KSQL on production environment on my isolated topic with debug data not related to operational status of production, I am completely fine with KSQL not behaving as expected, would love to reassure that using KSQL is not a threat to the kafka cluster itself and other streams.

**Comment by hjafarpour** [comment]
@KirillMoizik You definitely can use KSQL at your own risk :)
KSQL makes it really easy to create kafka streams apps  and run them continuously so you need to pay especial attention to the amount of resources your queries use. Note that once you start a continuous query  it will keep running until you explicitly terminate it.
Although KSQL runs outside of your Kafka cluster, it will read from topics in your kafka cluster and write the results in new topics that you create using CREATE STREAM AS SELECT and CREATE TABLE AS SELECT statements. KSQL queries such as aggregate queries that need repartitioning also need to create intermediate topics. If you are ok with creating extra topics in your kafka cluster you can try running some queries there and let us know about your experience!

**Comment by KirillMoizik** [comment]
thanks. will report back :)

**Comment by miguno** [comment]
Closed because of inactivity.  Feel free to re-open if needed.

**Comment by Krishan410** [comment]
So Are you using KSQL on production?
If yes can you give some insigts on this?
If No can you explain the reason for not using?

**Comment by samek** [comment]
@hjafarpour should  those intermediate topics be cleaned up (when production ready) ? It seams to me they are just pilling up.
Also are they  save to clean (eg. lowest timestamp)  ?

eg. my topics generated by ksql 
````
ksql_transient_5984517653698547209_1510748414556-VIDEOS_VIDEOVIEW_30MINtransient_-repartition
ksql_transient_3375138881574277727_1510734178541-ARTICLE_PAGEVIEW_15MINtransient_-repartition
ksql_query_2-KSQL_Agg_Query_1510689026893-changelog
ksql_query_5-KSQL_Agg_Query_1510734371568-repartition
ksql_transient_7422392799694436694_1510748259000-VIDEOS_VIDEOVIEW_30MINtransient_-changelog
ksql_query_5-KSQL_Agg_Query_1510734371568-changelog
ksql_transient_178878190806239214_1510748567653-VIDEOS_VIDEOVIEW_30MINtransient_-changelog
ksql_transient_6167467090727308471_1510689084506-VIDEOS_VIDEOVIEW_30MINtransient_-repartition
ksql_transient_7998437462579943658_1510748166485-VIDEOS_VIDEOVIEW_30MINtransient_-repartition
ksql_transient_7283144265770510439_1510734379560-ARTICLE_PAGEVIEW_15MINtransient_-changelog
ksql_transient_7422392799694436694_1510748259000-VIDEOS_VIDEOVIEW_30MINtransient_-repartition
ksql_transient_5146719362084000005_1510748054753-VIDEOS_VIDEOVIEW_30MINtransient_-changelog
ksql_transient_8895847005349146277_1510734124335-ARTICLE_PAGEVIEW_15MINtransient_-repartition
ksql_transient_5984517653698547209_1510748414556-VIDEOS_VIDEOVIEW_30MINtransient_-changelog
ksql_transient_8895847005349146277_1510734124335-ARTICLE_PAGEVIEW_15MINtransient_-changelog
ksql_transient_178878190806239214_1510748567653-VIDEOS_VIDEOVIEW_30MINtransient_-repartition
ksql_transient_6243309775998157119_1510689034742-ARTICLE_PAGEVIEW_15MINtransient_-changelog
ksql_transient_6167467090727308471_1510689084506-VIDEOS_VIDEOVIEW_30MINtransient_-changelog
ksql_query_6-KSQL_Agg_Query_1510734402025-repartition
ksql_query_2-KSQL_Agg_Query_1510689026893-repartition
ksql_query_5-KSQL_Agg_Query_1510734371569-repartition
ksql_query_6-KSQL_Agg_Query_1510734402025-changelog
ksql__commands
ksql_transient_7998437462579943658_1510748166485-VIDEOS_VIDEOVIEW_30MINtransient_-changelog
ksql_transient_5146719362084000005_1510748054753-VIDEOS_VIDEOVIEW_30MINtransient_-repartition
ksql_transient_3375138881574277727_1510734178541-ARTICLE_PAGEVIEW_15MINtransient_-changelog
ksql_transient_6243309775998157119_1510689034742-ARTICLE_PAGEVIEW_15MINtransient_-repartition
ksql_query_4-KSQL_Agg_Query_1510689075562-repartition
ksql_query_2-KSQL_Agg_Query_1510689169078-repartition
ksql_query_4-KSQL_Agg_Query_1510689169826-repartition
ksql_transient_7283144265770510439_1510734379560-ARTICLE_PAGEVIEW_15MINtransient_-repartition
ksql_query_6-KSQL_Agg_Query_1510734402029-repartition
ksql_query_4-KSQL_Agg_Query_1510689075562-changelog
````
