### ISSUE TITLE
`ksql-functional-test` module depends on test-jars

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#2804]
The new `ksql-functional-tests` module, which I understand will be what customers will use to test KSQL statements, currently depends on test-jars from other modules, e.g.

```
<dependency>
      <groupId>io.confluent.ksql</groupId>
      <artifactId>ksql-engine</artifactId>
      <version>${project.version}</version>
      <type>test-jar</type>
</dependency>
```

We don't really want to be shipping jars to customers that rely on test jars, so we should break all these dependencies.

**Comment by apurvam** [comment]
Ping @hjafarpour do we plan to take care of this?

**Comment by hjafarpour** [comment]
Removing those dependencies will require code duplication since we would need to have the classes from the tests in the new `ksql-functional-test` module.
In this case, I think it's better to have code duplication instead of depending on the test-jars. Since we passed code freeze for 5.3, I'll keep it as it in 5.3 and make the refactoring for 5.4.

**Comment by apurvam** [comment]
I didn't dig into the details, but there probably are more options than full code duplication or depending on test jars. 

Either way, given the other problems this has caused (like test UDFS showing up in the list), it is probably better to figure out a fix and do it on 5.3. The next bug fix is in a few weeks. we should aim to get this done by then.

**Comment by big-andy-coates** [comment]
One of the tickets associated with #3252

**Comment by big-andy-coates** [comment]
@purplefox, we were hoping you may be able to help with this...

**Comment by purplefox** [comment]
Another possibility would be to separate out the shared test util classes into a new module, and have ksql-functional-tests and any tests from other modules that require them to depend on that.

**Comment by purplefox** [comment]
Or move them to ksql-test-utils

**Comment by vpapavas** [comment]
I think separating them to a different module is a good idea. But I would like someone with more engineering experience to chip in as well.
