### ISSUE TITLE
PARTITION BY does not work with GROUP BY output topic

### ISSUE THREAD

**Issue by peoplemerge** [confluentinc/ksql#2811]
#2356 suggests a strategy to change key of a table.  This doesn't seem to work in my use case, which further includes a GROUP BY expression.

```
CREATE TABLE t0 WITH ( KAFKA_TOPIC='tt') AS SELECT w, x, y, COLLECT_SET(z) FROM s0 GROUP BY w,x,y
```

ROWKEY for tbl at this point has a composite `w|+|x|+|y` as expected.  I don’t know how to translate a KTable to a KStream but I need to because my subsequent joins need to be KStream joins against other KTables, so I’m creating a new stream s2:

 ```
CREATE STREAM s1 WITH (KAFKA_TOPIC='tt' VALUE_FORMAT='avro');
CREATE STREAM s2 AS SELECT * FROM s1 PARTITION BY w;
```

Expected results: `SELECT * FROM s2` have only `w` in ROWKEY.
Actual results: ROWKEY still contains `w|+|x|+|y`.

**Comment by peoplemerge** [comment]
```ksql> version
Version: 5.1.2
```

**Comment by peoplemerge** [comment]
Oddly, by after the order of the columns, I had some trouble reproducing this.  Would still be nice to understand how to use the test harness to test this (see 202c023)

**Comment by mjsax** [comment]
This should work in latest versions of ksqlDB; note that `ROWKEY` was replaced to support multi-column keys now (cf https://www.confluent.io/blog/ksqldb-0-15-features-updates/).

Closing this ticket. Feel free to re-open of follow up with comments/questions.
