### ISSUE TITLE
Create Streams fails on master with new topic creation syntax

### ISSUE THREAD

**Issue by MichaelDrogalis** [confluentinc/ksql#2813]
Running against master on `23a5047d62d5f1f767db3c22a134424d3c9011e4`, the new topic creation functionality (https://github.com/confluentinc/ksql/pull/2776) seems to be broken. I know that I have an up-to-date build because `spool` is working, which was added to master after this functionality came in:

```
ksql> CREATE STREAM fubar (FOO VARCHAR, BAR INT) WITH(kafka_topic='fubar', partitions=1, value_format='json');
Invalid config variable in the WITH clause: PARTITIONS
ksql> spool 'test.log';
ksql> version
Version: 5.2.1
ksql> spool off;
ksql> 
Exiting KSQL.
Michael-Drogaliss-MBP15:harness michael.drogalis$ cat test.log 

ksql> version
Version: 5.2.1

ksql> spool off;
```

**Comment by agavra** [comment]
Cannot reproduce on HEAD (`c0784fb4f2627108be0c3a4f76c6a81a667412c1` one commit after the one you are referencing):
```
ksql> CREATE STREAM fubar (FOO VARCHAR, BAR INT) WITH(kafka_topic='fubar', partitions=1, value_format='json');

 Message
----------------
 Stream created
----------------
ksql> version
Version: 5.3.0-SNAPSHOT
```

Can you double check your build?

**Comment by MichaelDrogalis** [comment]
This one's my fault. I had a Docker build of Confluent Platform running that was blotting out my build from source. Sorry for the noise >_<
