### ISSUE TITLE
Create stream uses number of partitions for replicas

### ISSUE THREAD

**Issue by MichaelDrogalis** [confluentinc/ksql#2815]
Running a clean build of `c0784fb4f2627108be0c3a4f76c6a81a667412c1`, it appears that creating a stream uses the partition count on behalf of the replica count:

```
CLI v5.3.0-SNAPSHOT, Server v5.3.0-SNAPSHOT located at http://localhost:8088

Having trouble? Type 'help' (case-insensitive) for a rundown of how things work!

ksql> version
Version: 5.3.0-SNAPSHOT
ksql> create stream test_stream (author varchar) with (kafka_topic='test_topic', key='author', value_format='avro', partitions=5);
Failed to guarantee existence of topic test_topic
Caused by: Replication factor: 5 larger than available brokers: 1.
ksql> create stream test_stream (author varchar) with (kafka_topic='test_topic', key='author', value_format='avro', partitions=1);

 Message        
----------------
 Stream created 
----------------
```

I did a little digging to make sure I wasn't running against the wrong build again, and I bisected it down to `b7003623586d34f62e470f0871bfaabb7502d40e` (PR https://github.com/confluentinc/ksql/pull/2785). Took a quick scan of the diff, and I think I see the culprit: https://github.com/confluentinc/ksql/blob/c0784fb4f2627108be0c3a4f76c6a81a667412c1/ksql-parser/src/main/java/io/confluent/ksql/parser/tree/CreateSourceProperties.java#L143

**Comment by agavra** [comment]
Oops! I'm surprised testing didn't catch that. I'll fix forward ASAP and
add coverage.
