### ISSUE TITLE
Could not find or load main class io.confluent.ksql.Ksql

### ISSUE THREAD

**Issue by williamokano** [confluentinc/ksql#2820]
Hi, I'm new to KSQL and I download the source and tried to execute the `ksql-server-start` and I got the following error: `Could not find or load main class io.confluent.ksql.Ksql`

Any ideas on how can I fix this? Thanks in advance.

**Comment by mzur-at-crd** [comment]
Do you remember what fixed this issue for you? I am getting it ...
