### ISSUE TITLE
Possible to avoid running tests?

### ISSUE THREAD

**Issue by kirktrue** [confluentinc/ksql#292]
When compiling/packaging using `mvn`, it is not possible to skip compiling and running the unit tests (via `mvn package -Dmaven.test.skip=true`) as attempts to do so yield the following:

```
[ERROR] Failed to execute goal on project ksql-cli: Could not resolve dependencies for project io.confluent.ksql:ksql-cli:jar:0.1-SNAPSHOT: Could not find artifact io.confluent.ksql:ksql-core:jar:tests:0.1-SNAPSHOT in confluent (http://packages.confluent.io/maven/) -> [Help 1]
```

It's a bit tedious to have to run the unit tests each time as they take a few minutes for each run.

Let me know if there's a way to get around having to sit through the test execution each time.

Thanks.

**Comment by hjafarpour** [comment]
@kirktrue This works for me:

$ mvn clean install -DskipTests

Wanna try it and let me know if it works for you too.

**Comment by kirktrue** [comment]
Yes, `mvn clean install -DskipTests` (and `mvn clean package -DskipTests`) works for me. Subtle difference in the two commands :\
