### ISSUE TITLE
Kafka avro schema data not reflecting from topic

### ISSUE THREAD

**Issue by promothkumarprabakaran** [confluentinc/ksql#293]
When creating a stream from kafka topic having records using avro schema values are not getting mapped to column names properly. Some field does not read values and others have first character truncated.

**Comment by hjafarpour** [comment]
@promothkumarprabakaran how do you write avro values? Are you using schema registry?
Also can you give a bit more details on the avro schema and column names?

**Comment by promothkumarprabakaran** [comment]
@hjafarpour  Yes we use scheme registry for pushing values into kafka topic. For now i am copying the scheme file to local folder and refer the path in ksqlServerproperties. We have almost 30+ columns and i am creating stream from the kafka topic with only two of those columns. Values are some timing missing and it get truncated some times.

**Comment by hjafarpour** [comment]
@promothkumarprabakaran When you use Schema Registry the avro values will have extra magic bytes that need to be dealt with. We do not have support for schema registry yet but it is one of high priority items for us. Please stay tune for this.
