### ISSUE TITLE
Make command topic retention configurable

### ISSUE THREAD

**Issue by port8080** [confluentinc/ksql#2934]
KSQL command topics [set retention to be](https://github.com/confluentinc/ksql/blob/master/ksql-rest-app/src/main/java/io/confluent/ksql/rest/util/KsqlInternalTopicUtils.java#L79) `Long.MAX_VALUE`

This does not work for [heroku](
https://devcenter.heroku.com/articles/kafka-on-heroku) and esp. [multi-tenant heroku environments](https://devcenter.heroku.com/articles/multi-tenant-kafka-on-heroku#differences-to-dedicated-kafka-plans) because the retention is 1 day.

Please make the retention period configurable

**Comment by agavra** [comment]
Hello @port8080. I'm not sure this is a viable fix to the issue you are encountering. KSQL uses the command topic to recover from crashes, and having any retention other than infinite would make it impossible to recover after a crash.

As a workaround, you can start your KSQL server on headless mode by suppling a `.sql` file with the statements you want it to execute (see [non-interactive ksql usage guide](https://docs.confluent.io/current/ksql/docs/installation/server-config/index.html#non-interactive-headless-ksql-usage)) which shouldn't create the command topic to begin with.

**Comment by port8080** [comment]
I got in touch with Heroku, and supporting KSQL on multi-tenant cluster is not on their roadmap

<img width="888" alt="Screen Shot 2019-06-18 at 9 31 13 AM" src="https://user-images.githubusercontent.com/326830/59702162-f78a9380-91ab-11e9-838d-1bf0c339b223.png">
