### ISSUE TITLE
ksql-cli: slow to ctrl-c out of select statement when stream idle

### ISSUE THREAD

**Issue by henridf** [confluentinc/ksql#295]
I have a simple `select * from xyz` running (where `xyz` is obtained from a simple `create stream` from a topic) and if there is no data being produced into the topic, it takes 10s of seconds to get back to the CLI prompt after doing ctrl-c.

**Comment by miguno** [comment]
Are you running KSQL in Docker?

**Comment by henridf** [comment]
Yep. My starting point was the docker-compose file that comes with the quickstart. 

(I think you can repro this issue by using that docker-compose, then `docker stop`ing the generators.)

**Comment by miguno** [comment]
Closing this older ticket.  Feel free to reopen if needed.
