### ISSUE TITLE
ROWKEY format

### ISSUE THREAD

**Issue by allenansari174** [confluentinc/ksql#2988]
I created a stream but rowkey format is like this:
{"schema":{"type":"struct","fields":[{"type":"int64","optional":true,"field":"Id"}],"optional":false,"name":"com.github.jcustenborder.kafka.connect.twitter.StatusKey","doc":"Key for a twitter status."},"payload":{"Id":1140239850848882688}}

and the rest of the fields are null

any idea how to solve this issue.

ksql> SELECT * FROM twitter_raw LIMIT 1;
1560689344973 | {"schema":{"type":"struct","fields":[{"type":"int64","optional":true,"field":"Id"}],"optional":false,"name":"com.github.jcustenborder.kafka.connect.twitter.StatusKey","doc":"Key for a twitter status."},"payload":{"Id":1140239850848882688}} | null | null | null

**Comment by big-andy-coates** [comment]
Hi @allenansari174 

I'm sorry, but I'm not sure I have enough information about your problem to help.

Can you provide more details please? e.g.

- what version of KSQL?
- what statements did you run to create your source stream(s) / table(s)?
- what is the schema of the value?
- some sample data?

In the interest of keeping our issue backlog tidy I'm going to close this issue. Please feel free to reopen with more details if the answer does not fully answer your question of if you have a follow up question. Thanks for using KSQL!
