### ISSUE TITLE
Can't parse JSON with UTF8

### ISSUE THREAD

**Issue by sablastik** [confluentinc/ksql#3032]
We have a trouble with topic having JSON like `"CollAddressText":"Жилой комплекс \"Некрасовский\""`.

When I try to make KSQL print topic, this value starts to look like:
`"CollAddressText":"\xD0\x96\xD0\xB8\xD0\xBB\xD0\xBE\xD0\xB9 \xD0\xBA\xD0\xBE\xD0\xBC\xD0\xBF\xD0\xBB\xD0\xB5\xD0\xBA\xD1\x81 \x5C"\xD0\x9D\xD0\xB5\xD0\xBA\xD1\x80\xD0\xB0\xD1\x81\xD0\xBE\xD0\xB2\xD1\x81\xD0\xBA\xD0\xB8\xD0\xB9\x5C""` and topic `Format:String` while printing other topics without values like `"CollAddressText":"Жилой комплекс \"Некрасовский\""` looks like `Format:JSON`.

Please help us to make KSQL parsing such strings correctly.

**Comment by spena** [comment]
This is fixed or not reproducible in the latest master branch (0.11.0).

This is the Kafka topic content:
```
$ bin/kafka-console-consumer --bootstrap-server localhost:9092  --topic utf8 --from-beginning
{ "CollAddressText":"Жилой комплекс \"Некрасовский\"" }
```

This is the KSQL stream:
```
ksql> create stream utf8(CollAddressText string) with (kafka_topic='utf8', value_format='json');
 Message        
----------------
 Stream created 
----------------

ksql> print 'utf8' from BEGINNING;
Key format: ¯\_(ツ)_/¯ - no data processed
Value format: JSON or KAFKA_STRING
rowtime: 2020/06/22 18:05:55.403 Z, key: <null>, value: { "CollAddressText":"Жилой комплекс \"Некрасовский\"" }

ksql> select * from utf8 emit changes;
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|COLLADDRESSTEXT                                                                                                                                                                               |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|Жилой комплекс "Некрасовский"
```
