### ISSUE TITLE
Support for REST APIs

### ISSUE THREAD

**Issue by alexhafner** [confluentinc/ksql#304]
Once you start a ksql-server, you can do cool REST API calls such as 

Running a simple request
```
## Simple KSQL
curl -X "POST" "http://server:port/ksql";; \
     -H "Content-Type: application/json; charset=utf-8" \
     -d $'{
  "ksql": "LIST STREAMS;",
  "streamsProperties": {}
}'
```

or retrieving streaming data

```
## Stream Query
curl -X "POST" "http://server:port/query";; \
     -H "Content-Type: application/json; charset=utf-8" \
     -d $'{
  "ksql": "SELECT * FROM TEST_A;",
  "streamsProperties": {}
}'
```
This is a neat way to query KSQL from elsewhere, particularly for ad-hoc information. Even better when it runs under https. Some authorization/authentication capabilities in future would also be valuable.

In the documentation, the REST component is only getting a short mention, and it's used internally within the CLI and on quickstart.html. Is it planned to support it in the production release? #

**Comment by jadbox** [comment]
Currently I'm not sure how I'd connect to or use KSQL from any language outside the JVM.

**Comment by hjafarpour** [comment]
@alexhafner Thanks for your feedback. Yes, we will improve the documentation and will include more details on the REST API.  Although as you mentioned the REST API is only used by CLI but you can definitely use it with any REST client. 

@jadbox You can send requests from any language that can send http requests. For instance,  @alexhafner showed how to do it from console using curl.

**Comment by alexhafner** [comment]
@hjafarpour that's great news! Thanks for the clarification.

**Comment by pavel-agarkov** [comment]
Hello, how do you execute queries with rest api? When I send `ksql` like `SELECT * FROM SOME_TABLE;` it returns `Cannot handle statement of type 'Query'`. I don't actually need continuous query - I just need a current compacted table state.

**Comment by miguno** [comment]
The KSQL REST API is officially available and support nowadays.

Documentation is available at https://docs.confluent.io/current/ksql/docs/api.html.

**Comment by ankitraijr** [comment]
@alexhafner  when I am running below command it is working fine but when I put WHERE clause in this command it gives me an error.

curl -X "POST" "http://server:port/query";; \
     -H "Content-Type: application/json; charset=utf-8" \
     -d $'{
  "ksql": "SELECT * FROM TEST_A;",
  "streamsProperties": {}
}'

Below command not working

curl -X "POST" "http://localhost:8088/query" -H "Content-Type: application/json; charset=utf-8" -d $'{"ksql": " select * from LOCATION_EVENT WHERE room='Room4283' ;", "streamsProperties": {}}'

Error:- 

{"message":"Column ROOM4283 cannot be resolved.","stackTrace":["io.confluent.ksql.analyzer.ExpressionAnalyzer$Visitor.visitDereferenceExpression(ExpressionAnalyzer.java:115)"
