### ISSUE TITLE
Collect_LIST not working ok KTABLE ?

### ISSUE THREAD

**Issue by Maatary** [confluentinc/ksql#3078]
The documentation says that The aggregation function collect_list works for both Table and stream: https://docs.confluent.io/current/ksql/docs/developer-guide/syntax-reference.html#aggregate-functions

However although i succeeded to use it on a stream. I have not been successful in using it on a Table.

I wonder if anyone has manage to do so, or if there is a bug.

```
select addressid, collect_list(name) from users group by addressid;
    The aggregation function(s) (collect_list) cannot be applied to a table.
    Statement: select addressid, collect_list(name) from users group by addressid;
    Caused by: The aggregation function(s) (collect_list) cannot be applied to a
        table.
```

**Comment by vcrfxia** [comment]
This is a bug -- thanks for finding it @Maatary ! Here is the fix: https://github.com/confluentinc/ksql/pull/3104 The fix will be included in the next bugfix release of each KSQL version (and also 5.4, the next KSQL release).
