### ISSUE TITLE
Calculate window start ignore timezone

### ISSUE THREAD

**Issue by jeffreywk** [confluentinc/ksql#3088]
public Map<Long, TimeWindow> windowsFor(final long timestamp) {
        long windowStart = (Math.max(0, timestamp - sizeMs + advanceMs) / advanceMs) * advanceMs;
        final Map<Long, TimeWindow> windows = new LinkedHashMap<>();
        while (windowStart <= timestamp) {
            final TimeWindow window = new TimeWindow(windowStart, windowStart + sizeMs);
            windows.put(windowStart, window);
            windowStart += advanceMs;
        }
        return windows;
    }

This function ignore the timezone when calculate window start.

**Comment by jeffreywk** [comment]
long windowStart = (Math.max(0, timestamp - sizeMs + advanceMs) / advanceMs) * advanceMs;
should be 
    long windowStart = (Math.max(0, timestamp - sizeMs- Calendar.getInstance().get(Calendar.ZONE_OFFSET) *3600 *1000 + advanceMs) / advanceMs) * advanceMs;

**Comment by big-andy-coates** [comment]
Hi @jeffreywk 

Sorry, but I'm a little confused... what is this code you've posted?

In the interest of keeping our issue backlog tidy I'm going to close this issue. Please feel free to reopen with more details if the answer does not fully answer your question of if you have a follow up question. Thanks for using KSQL!
