### ISSUE TITLE
Unify code between the query validation tests and the KSQL testing tool

### ISSUE THREAD

**Issue by apurvam** [confluentinc/ksql#3119]
Currently, the new KSQL testing tool is separate from the query validation tests. This means that none of the 500+ test cases running through the query validation tests also exercise the testing tool. We should unify both code paths to get better coverage. 

See below for reference: https://github.com/confluentinc/ksql/pull/2968#pullrequestreview-249028151

**Comment by hjafarpour** [comment]
PR #3180 unifies the QTT with the testing tool.
