### ISSUE TITLE
subscribe to KTable

### ISSUE THREAD

**Issue by Fisherijus** [confluentinc/ksql#3146]
Now, to get data from Ktable i use KSQL REST API. is it possible to subscribe to it via consumer?

**Comment by big-andy-coates** [comment]
Yes. If you build a persistent query to build a new table from some other source it will be output to a sink topic and you can subscribe to that.

e.g.

```sql
CREATE STREAM S (somem schema) WITH (some props);
CREATE TABLE T AS SELECT id, count(1) FROM S GROUP BY id;
```

The second statement above will create a persistent query that outputs its results to a topic named 'T'.

In the interest of keeping our issue backlog tidy I'm going to close this issue. Please feel free to reopen with more details if the answer does not fully answer your question of if you have a follow up question. Thanks for using KSQL!
