### ISSUE TITLE
>Lowercase character in column name makes the column null

### ISSUE THREAD

**Issue by mayankiiitm** [confluentinc/ksql#3152]
> 
> 
> I'm not sure in which version this changed, but as of 5.1 you can quote fields (and objects) to retain their casing.
> 
> ```
> CREATE STREAM "MixedCaseStream" AS \
>             SELECT COL1, \
>                    COL1 AS "lowercase_col1", \
>                    COL1 AS "MixedCase_COL1", \
>                    COL1 AS "UPPERCASE_COL1", \
>                    COL1 AS NOTQUOTED_MixedCase_COL1 \
>           FROM SOURCE;
> ```
> 
> More: https://rmoff.net/post/how-ksql-handles-case/

When I rename and column name contains any lower case character, column becomes null. Source topic is getting the data. As long column name does not contains any lower case character everything works fine.

_Originally posted by @mayankiiitm in https://github.com/confluentinc/ksql/issues/1039#issuecomment-516771601_

**Comment by agavra** [comment]
This should be fixed in the most recent release of ksqlDB (0.6.0) - feel free to re-open if it persists!

**Comment by samjpv** [comment]
This appears to still be broken? I've had all of these fail, trying backticks and quotes interchangeably:

`CREATE STREAM "LowerCase" AS \
            SELECT "col1" 
          FROM SOURCE;`
(where col1 is lowercased in the source stream)

``CREATE STREAM "LowerCase" AS \
            SELECT col1 as "col1"
          FROM SOURCE;``
(where col1 is uppercased in the source stream)

In both cases col1 is not null in SOURCE,
with the resulting message being:
`{
    "col1": null
}`

Am I missing something? This seems like the same issue unresolved.
