### ISSUE TITLE
KSQL streams default.timestamp.extractor override is not working

### ISSUE THREAD

**Issue by spena** [confluentinc/ksql#3164]
Sometimes, for a weird reason, a topic might contain invalid timestamps that cannot be read by a KStream in KSQL. For example, when extracting data from Oracle using Attunity to Kafka occasionally sends over a timestamp of -1. This data is later streamed by KSQL, but causes KSQL to fail because an invalid timestamp found. The default timestamp extractor for KSQL is `FailOnInvalidTimestamp`.

To fix it, KStreams offers a timestamp extractor `UsePreviousTimeOnInvalidTimestamp`  that skips invalid timestamps. We could fix it by overriding the default with `ksql.streams.default.timestamp.extractor=UsePreviousTimeOnInvalidTimestamp`, but KSQL does not use the new timestamp extractor. It always defaults to `FailOnInvalidTimestamp`.

KSQL should be able to honor the override so it continues streaming data without problems.

**Comment by apurvam** [comment]
Isn't this fixed by https://github.com/confluentinc/ksql/pull/3176 ?
