### ISSUE TITLE
Consumer groups for queries are not cleaned up after terminating the queries

### ISSUE THREAD

**Issue by spena** [confluentinc/ksql#3193]
I noticed that the consumer groups created by KSQL when running transient and persistent queries are not destroyed or cleaned up after terminating the queries.

```
./kafka-consumer-groups --bootstrap-server localhost:9092 --list
_confluent-ksql-default_transient_2883290224913769496_1565385111554
_confluent-ksql-default_query_CSAS_S1_1
_confluent-ksql-default_transient_4408587371619061316_1565385359940
_confluent-ksql-default_transient_8612478566717420677_1565385376161
_confluent-ksql-default_transient_8747453382801417324_1565385749551
_confluent-ksql-default_transient_8530210690823170123_1565385739908
_confluent-ksql-default_transient_5687663212571748139_1565385160903
_confluent-ksql-default_transient_1308726277222381978_1565385130274
```
The above is the list of all consumers groups. At this point, there are not transient queries running, not even KSQL running (restarting KSQL does not clean them up either).

**Comment by spena** [comment]
We should be safe to delete the transient consumer groups after the query has been terminated.
 
For persistent queries, we should think if KSQL will support queries resume, so the resume process reuses the consumer group to continue from the commit offset, otherwise the resume will not work.

**Comment by apurvam** [comment]
it's worth noting that these are going to be garbage collected in Kafka anyway.

**Comment by big-andy-coates** [comment]
I don't think there's much ROI on 'fixing' this issue, given they are garbage collected...
