### ISSUE TITLE
"ksql-cli local" worked very well when first used  and after that it started hanging

### ISSUE THREAD

**Issue by kuncao** [confluentinc/ksql#320]
"ksql-cli local" worked very well when first used and after that it started hanging.
even after reboot the machine and can not fix the bug
and there is no error message and can not find the related logs
how to resolve the issue?
thanks a lot.

**Comment by kuncao** [comment]
OS :suse 12 sp2

**Comment by r13ssh** [comment]
possibly the same issue as Issue #303 ?

**Comment by kuncao** [comment]
@r13ssh 
thanks a lot
not same as issue #303 
in my case ,ksql-cli local does not return any message

**Comment by bluemonk3y** [comment]
Would you please attach a thread-dump of the hanging process?  Using jps and jstack.

**Comment by SoyeeDst** [comment]
@kuncao Can you check whether `localhost:9092` can be accessed from the machine of running the KSQL, since normally local mode would use this address by default.

**Comment by kuncao** [comment]
@SoyeeDst 
after kill the process which use 9092
./ksql-cli  local
io.confluent.ksql.exception.KafkaResponseGetFailedException: Failed to retrieve kafka topic names

**Comment by miguno** [comment]
Closed because of inactivity. Feel free to re-open if needed.
