### ISSUE TITLE
one join will create several topic, and kafka has a limit on the number of topic, so how many join ksql support at the same time?

### ISSUE THREAD

**Issue by wjphero** [confluentinc/ksql#3200]
one join will create several topic, and kafka has a limit on the number of topic, so how many join ksql support at the same time? 
I found that the ksql will create so many topic, and at the cluster environment, add new physical will not solve the problem

**Comment by big-andy-coates** [comment]
While there is a practical limit to the number of partitions a Kafka cluster can handle this number is high enough that it's generally not an issue.  I'm not up to date with the current guidelines on the maximum number, but I seem to remember it being in the 10s of thousands on replicas.

KSQL gets it source data from Kafka and outputs results to Kafka. In addition to this, KSQL uses KSQL to back the stores it needs for stateful operations, (topics ending in -statestore), and to handle any repartitioning of data that is needed, (topics ending in -repartition).

I hope this information is of some help. 

In the interest of keeping a clean set of Github issues I'm going to close this issue, but if you would like more information, or have follow up questions, then please reopen with more details.

Thanks for raising your issue!
