### ISSUE TITLE
PARTITION BY clause does not support lowercase field names

### ISSUE THREAD

**Issue by rajbhino** [confluentinc/ksql#3203]
When creating a stream with mixed case fields and using one of them for PARTITION BY clause using double quotes to preserve case-sensitiveness it does not work and throws error. It recognizes only upper case fields,. 

CREATE STREAM TEST_TIMESTAMP_X3 AS
select after->location_number AS "locationID", after->sku AS "itemID", after->qty AS "quantity"
from STREAM_tv_test;
CREATE STREAM TEST_TIMESTAMP_X3_PARTITIONED WITH
   (KAFKA_TOPIC='TEST_TIMESTAMP_X3',
    VALUE_FORMAT='JSON') AS
SELECT * FROM TEST_TIMESTAMP_X3
PARTITION BY "locationID"; --> Column LOCATIONID does not exist in the result schema. Error in Partition By clause.

**Comment by apurvam** [comment]
related to #2589

**Comment by big-andy-coates** [comment]
Hi @rajbhino - quoted identifiers don't yet work correctly in KSQL. Sorry for the confusion. Note: they are actively being worked on, so we should be able to support this very soon.

**Comment by pavelpe** [comment]
> so we should be able to support this very soon.
Hi, any update on this issue?

**Comment by agavra** [comment]
This should work on master @pavelpe - I believe it also works on ksqlDB 0.6.0 and KSQL 5.4.
