### ISSUE TITLE
KSQL table : results Duplication of record , same record appear two times after LEFT JOIN of two ktable

### ISSUE THREAD

**Issue by Jishnuprasad1** [confluentinc/ksql#3211]
KSQL table : results Duplication of record , same record appear two times after LEFT JOIN of two k table.

1)This is my customer data topic "producer" in the following format.

{"customerId":"GGGG1616","customerName":"user_1616","policyId":"P6","emailId":"user_1616@gmail.com","phoneNumber":9933001616,"targetTopic":"producer"}

Then i created a ktable based on the kafkatopic "producer".

ksql>CREATE TABLE customertable(customerId VARCHAR,customerName VARCHAR,policyId VARCHAR,emailId VARCHAR,phoneNumber BIGINT) WIth (key = 'policyId', kafka_topic ='producer', value_format='JSON');

ksql> select * from customertable;
1565677566724 | P0 | GGGG1627 | user_1627 | P0 | user_1627@gmail.com | 9933001627
1565677567231 | P9 | GGGG1632 | user_1632 | P9 | user_1632@gmail.com | 9933001632
1565677567638 | P2 | GGGG1636 | user_1636 | P2 | user_1636@gmail.com | 9933001636
1565677568146 | P8 | GGGG1641 | user_1641 | P8 | user_1641@gmail.com | 9933001641
1565677568350 | P3 | GGGG1643 | user_1643 | P3 | user_1643@gmail.com | 9933001643
1565677568451 | P1 | GGGG1644 | user_1644 | P1 | user_1644@gmail.com | 9933001644
1565677568654 | P6 | GGGG1646 | user_1646 | P6 | user_1646@gmail.com | 9933001646
1565677568756 | P7 | GGGG1647 | user_1647 | P7 | user_1647@gmail.com | 9933001647
1565677568857 | P10 | GGGG1648 | user_1648 | P10 | user_1648@gmail.com | 9933001648
1565677568959 | P5 | GGGG1649 | user_1649 | P5 | user_1649@gmail.com | 9933001649
1565677569060 | P4 | GGGG1650 | user_1650 | P4 | user_1650@gmail.com | 9933001650

ksql> describe extended customertable;

Name                 : CUSTOMERTABLE
Type                 : TABLE
Key field            : POLICYID
Key format           : STRING
Timestamp field      : Not set - using <ROWTIME>
Value format         : JSON
Kafka topic          : producer (partitions: 1, replication: 1)

 Field        | Type                      
------------------------------------------
 ROWTIME      | BIGINT           (system) 
 ROWKEY       | VARCHAR(STRING)  (system) 
 CUSTOMERID   | VARCHAR(STRING)           
 CUSTOMERNAME | VARCHAR(STRING)           
 POLICYID     | VARCHAR(STRING)           
 EMAILID      | VARCHAR(STRING)           
 PHONENUMBER  | BIGINT                    
------------------------------------------

2) This is Policy details topic "policy" in following format.

{"policyId":"P9","policyType":"Daily","updateBy":"JP","smsLimit":5,"emailLimit":8,"updateDate":1565686811223}

Then i created a Ktable based on this kafka-topic "policy".

ksql> CREATE TABLE policytable(policyId VARCHAR,policyType VARCHAR,channel STRUCT<smsLimit BIGINT,emailLimit BIGINT>,updateBy VARCHAR,updateDate BIGINT) WIth (key = 'policyId', kafka_topic ='policy2', value_format='JSON'); 

ksql> select * from policytable;
1565680272180 | P6 | P6 | yyyy | qwerty | 2 | 3 | 1565680271916
1565680288060 | P1 | P1 | yyyy | qwerty | 4 | 3 | 1565680288055
1565680298943 | P2 | P2 | yyyy | qwerty | 5 | 7 | 1565680298942
1565680307464 | P4 | P4 | yyyy | qwerty | 5 | 7 | 1565680307462
1565680316315 | P3 | P3 | yyyy | qwerty | 5 | 1 | 1565680316314
1565680326488 | P5 | P5 | yyyy | qwerty | 5 | 8 | 1565680326486
1565686811226 | P9 | P9 | Daily | JP | 5 | 8 | 1565686811223

ksql> describe extended policytable;

Name                 : POLICYTABLE
Type                 : TABLE
Key field            : POLICYID
Key format           : STRING
Timestamp field      : Not set - using <ROWTIME>
Value format         : JSON
Kafka topic          : policy (partitions: 1, replication: 1)

 Field      | Type                      
----------------------------------------
 ROWTIME    | BIGINT           (system) 
 ROWKEY     | VARCHAR(STRING)  (system) 
 POLICYID   | VARCHAR(STRING)           
 POLICYTYPE | VARCHAR(STRING)           
 UPDATEBY   | VARCHAR(STRING)           
 SMSLIMIT   | BIGINT                    
 EMAILLIMIT | BIGINT                    
 UPDATEDATE | BIGINT                    
----------------------------------------

ksql> select *  from policytable p left join customertable c  on p.policyId = c.policyId ;

1565680272180 | P6 | P6 | yyyy | qwerty | 2 | 3 | 1565680271916 | 1565677568654 | P6 | GGGG1646 | user_1646 | P6 | user_1646@gmail.com | 9933001646
1565680288060 | P1 | P1 | yyyy | qwerty | 4 | 3 | 1565680288055 | 1565677568451 | P1 | GGGG1644 | user_1644 | P1 | user_1644@gmail.com | 9933001644
1565680298943 | P2 | P2 | yyyy | qwerty | 5 | 7 | 1565680298942 | 1565677567638 | P2 | GGGG1636 | user_1636 | P2 | user_1636@gmail.com | 9933001636
1565680307464 | P4 | P4 | yyyy | qwerty | 5 | 7 | 1565680307462 | 1565677569060 | P4 | GGGG1650 | user_1650 | P4 | user_1650@gmail.com | 9933001650
1565680316315 | P3 | P3 | yyyy | qwerty | 5 | 1 | 1565680316314 | 1565677568350 | P3 | GGGG1643 | user_1643 | P3 | user_1643@gmail.com | 9933001643
1565680326488 | P5 | P5 | yyyy | qwerty | 5 | 8 | 1565680326486 | 1565677568959 | P5 | GGGG1649 | user_1649 | P5 | user_1649@gmail.com | 9933001649
1565686811226 | P9 | P9 | Daily | JP | 5 | 8 | 1565686811223 | 1565677567231 | P9 | GGGG1632 | user_1632 | P9 | user_1632@gmail.com | 9933001632
1565686811226 | P9 | P9 | Daily | JP | 5 | 8 | 1565686811223 | 1565677567231 | P9 | GGGG1632 | user_1632 | P9 | user_1632@gmail.com | 9933001632
1565680298943 | P2 | P2 | yyyy | qwerty | 5 | 7 | 1565680298942 | 1565677567638 | P2 | GGGG1636 | user_1636 | P2 | user_1636@gmail.com | 9933001636
1565680316315 | P3 | P3 | yyyy | qwerty | 5 | 1 | 1565680316314 | 1565677568350 | P3 | GGGG1643 | user_1643 | P3 | user_1643@gmail.com | 9933001643
1565680288060 | P1 | P1 | yyyy | qwerty | 4 | 3 | 1565680288055 | 1565677568451 | P1 | GGGG1644 | user_1644 | P1 | user_1644@gmail.com | 9933001644
1565680272180 | P6 | P6 | yyyy | qwerty | 2 | 3 | 1565680271916 | 1565677568654 | P6 | GGGG1646 | user_1646 | P6 | user_1646@gmail.com | 9933001646
1565680326488 | P5 | P5 | yyyy | qwerty | 5 | 8 | 1565680326486 | 1565677568959 | P5 | GGGG1649 | user_1649 | P5 | user_1649@gmail.com | 9933001649
1565680307464 | P4 | P4 | yyyy | qwerty | 5 | 7 | 1565680307462 | 1565677569060 | P4 | GGGG1650 | user_1650 | P4 | user_1650@gmail.com | 9933001650

Resulting table having the same record twise..
(My source topics doesnot hold any duplicate records having same CustomerId )

 When i try to retrieve SMSLIMIT and EMAILLIMIT using CUSTOMERID reults in showing same output 2 times.

ksql> select p.smsLimit,p.emailLimit  from policytable  p left join customertable c  on p.policyId =c.policyId where  c.customerId = 'GGGG1632' ;
5 | 8
5 | 8

Why is this happening ,should someone help me please.

**Comment by big-andy-coates** [comment]
Hi @Jishnuprasad1 

When you say duplicate records, are you meaning the rows like:

```
1565686811226 | P9 | P9 | Daily | JP | 5 | 8 | 1565686811223 | 1565677567231 | P9 | GGGG1632 | user_1632 | P9 | user_1632@gmail.com | 9933001632
1565686811226 | P9 | P9 | Daily | JP | 5 | 8 | 1565686811223 | 1565677567231 | P9 | GGGG1632 | user_1632 | P9 | user_1632@gmail.com | 9933001632
```

???

This may just be a misunderstanding on what is happening when you issue the statement: `select * from policytable p left join customertable c on p.policyId = c.policyId ;`

This will create a long running query that will output a row each time a new record is received on either of the source tables.  Records on the source tables may be adding new rows to the table or updating existing ones.  Therefore, it is fairly common to see rows output with a key (policyId) that you've already seen before.  This is not a duplicate row in the table: the table will only have one row. What you're seeing is the stream of _changes_ to the table.

This stream of changes is different to how a query against a standard db, which would just return a snapshot of the current table state.  The next release of KSQL (5.4) comes with 'pull queries' which work a little more like a query against a traditional db, i.e. they return you a snapshot.  

I hope this answers your question?

In the interest of keeping our issues backlog clean I'm going to close this issue, but feel free to reopen if you feel your question has not been answered.
