### ISSUE TITLE
Connect and KSQL both terminate

### ISSUE THREAD

**Issue by stariq2** [confluentinc/ksql#3220]
WARN Query terminated due to exception:org.eclipse.jetty.io.EofException (io.confluent.ksql.rest.server.resources.streaming.QueryStreamWriter:88)

**Comment by big-andy-coates** [comment]
Hi @stariq2 

Unfortunately, this issue does not contain enough information for us to investigate, e.g.

What operation where you performing?
What are the steps to recreate?
What version are you running?
What was in the logs?

So I'm going to close this issue. However, please raise a new issue with more info if your problem persists.
