### ISSUE TITLE
Increment persistent query ID during recovery even if query fails validation

### ISSUE THREAD

**Issue by vcrfxia** [confluentinc/ksql#3269]
Suppose the following statements are issued.
```
CREATE STREAM foo (...) WITH (KAFKA_TOPIC='foo');
CREATE STREAM foo_copy AS SELECT * from foo;  # starts a query with ID "CSAS_FOO_COPY_0"
TERMINATE CSAS_FOO_COPY_0;

CREATE STREAM bar (...) WITH (KAFKA_TOPIC='bar');
CREATE STREAM bar_copy AS SELECT * from bar;  # starts a query with ID "CSAS_BAR_COPY_1"
TERMINATE CSAS_BAR_COPY_1;
```
At the end of this, there are no running queries.

Now suppose the KSQL server is restarted, but in the meantime the topic `foo` has been deleted (externally). When the KSQL server replays the command topic, the first three statements will fail, and the next two will succeed. Because KSQL does not currently increment persistent query IDs for failed statements (during recovery), the query that is started as a result of `CREATE STREAM bar_copy AS SELECT * from bar;` will now have ID `CSAS_BAR_COPY_0`. This means the final statement (`TERMINATE CSAS_BAR_COPY_1;`) will fail, and after recovery the query that reads from `bar` and writes to `bar_copy` will still be running, even though it shouldn't be.

Related discussions: https://github.com/confluentinc/ksql/issues/2329, https://github.com/confluentinc/ksql/issues/2435

**Comment by stevenpyzhang** [comment]
https://github.com/confluentinc/ksql/pull/3354 addresses this issue. QueryID's should now be consistent after recovery since they're a function of the offset the query command is at in the command topic.
