### ISSUE TITLE
KSQL can't parse custom timestamp

### ISSUE THREAD

**Issue by apigban** [confluentinc/ksql#3277]
The stream went on for minutes then stopped because of this reason:

```Caused by: Text '2019-08-27T13:31:09.2+0000' could not be parsed at index 20```
```Query terminated```
```ksql>``` 

the relevant ksql statement:

```
...
    timestamp VARCHAR,
    type VARCHAR
) \
WITH (KAFKA_TOPIC='wazuh-archives-3.x',
        TIMESTAMP='timestamp',
        TIMESTAMP_FORMAT='yyyy-MM-dd''T''HH:mm:ss.SSSxxxx',
        VALUE_FORMAT='JSON');
```

Any guide on how to parse this? I've tried multiple combinations, `.SSSZZZZ` / `.Sxxxx/ etc.`.

I've referred to this https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html

**Comment by big-andy-coates** [comment]
Hi @apigban 

I think the issue here is the single digit milliseconds. I think you'd need the pattern `'yyyy-MM-dd''T''HH:mm:ss.SX'`

I've added a test in the following PR to cover just this case: https://github.com/confluentinc/ksql/pull/3549
