### ISSUE TITLE
Default server endpoint is incompatible with IPv6

### ISSUE THREAD

**Issue by vcrfxia** [confluentinc/ksql#3309]
The server properties file currently has a default of `listeners=http://0.0.0.0:8088` which is incompatible with IPv6. We should update this default to also include `http://[::1]:8088`, or perhaps `http://:::8088` (to avoid issues with localhost described in https://github.com/confluentinc/ksql/pull/2631), or at least add a docs note to warn users about the incompatibility.

**Comment by agavra** [comment]
Re-opening because of https://github.com/confluentinc/ksql/pull/3314

**Comment by big-andy-coates** [comment]
As per the comments on #3314, this is not something we can fix in a generic way.  Notes/help have been added to the ksql-server.properties file we ship. There's not much else we can do. So... closing...
