### ISSUE TITLE
kafka-streams : to modify message structure before sending it to kafka topics

### ISSUE THREAD

**Issue by avanchasr** [confluentinc/ksql#3311]
I have a scenario where I need to change the message structure:
{"id":"123","firstName":"pqr","lastName":"xyz","age":"23","dob":"20-09-1995"} 
I want to store this as below:
{"id":"123","name":{"firstName":"pqr","lastName":"xyz"}, "bio"{"age":"23","dob":"20-09-1995"}}

Is this possible in ksql? I do know how to break a nested JSON using STRUCT.. but I want the other way around.

**Comment by big-andy-coates** [comment]
Hi @avanchasr 

This is not _yet_ possible in KSQL, but hopefully will be soon.  Keep an eye on https://github.com/confluentinc/ksql/issues/3415, as that's the bit of functionality you want.  Also, feel free to vote on that issue, (just add a +1 comment), as that may bring forward when it will be worked on.
