### ISSUE TITLE
Failed to start KSQL with docker-compose up

### ISSUE THREAD

**Issue by asasvari** [confluentinc/ksql#3319]
Yesterday, https://github.com/confluentinc/ksql/commit/92b03ec1841e27b2359c7cece1f0a463d7d51367 introduced a change in `docker-compose.yaml`. I pulled the change and wanted to start KSQL, it failed with:

```
ksql-server_1      | [2019-09-10 09:39:38,273] ERROR Failed to start KSQL (io.confluent.ksql.rest.server.KsqlServerMain:62)
ksql-server_1      | java.net.SocketException: Protocol family unavailable
ksql-server_1      |    at sun.nio.ch.Net.bind0(Native Method)
ksql-server_1      |    at sun.nio.ch.Net.bind(Net.java:433)
ksql-server_1      |    at sun.nio.ch.Net.bind(Net.java:425)
ksql-server_1      |    at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
ksql-server_1      |    at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
ksql-server_1      |    at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:342)
ksql-server_1      |    at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:308)
ksql-server_1      |    at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
ksql-server_1      |    at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
ksql-server_1      |    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
ksql-server_1      |    at org.eclipse.jetty.server.Server.doStart(Server.java:396)
ksql-server_1      |    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
ksql-server_1      |    at io.confluent.rest.Application.start(Application.java:736)
ksql-server_1      |    at io.confluent.ksql.rest.server.KsqlRestApplication.start(KsqlRestApplication.java:201)
ksql-server_1      |    at io.confluent.ksql.rest.server.KsqlServerMain.tryStartApp(KsqlServerMain.java:74)
ksql-server_1      |    at io.confluent.ksql.rest.server.KsqlServerMain.main(KsqlServerMain.java:60)
```

https://github.com/confluentinc/ksql/blob/3e36dc0748169a79198802904faf97cfcc02a047/docs/tutorials/docker-compose.yml#L48 includes  `KSQL_LISTENERS: http://0.0.0.0:8088,http://[::]:8088`

The problem is that "By default, the Docker daemon configures the container network for IPv4 only." (see https://github.com/confluentinc/ksql/commit/92b03ec1841e27b2359c7cece1f0a463d7d51367).

https://github.com/confluentinc/ksql/commit/92b03ec1841e27b2359c7cece1f0a463d7d51367 basically breaks environments where Docker is not configured with IPv6. 

As a workaround, I changed `KSQL_LISTENERS: http://0.0.0.0:8088,http://[::]:8088` to `KSQL_LISTENERS: http://0.0.0.0:8088`. 

This behaviour is not documented in https://github.com/confluentinc/ksql/blob/master/docs/tutorials/basics-docker.rst

**Comment by stevenpyzhang** [comment]
https://github.com/confluentinc/ksql/commit/92b03ec1841e27b2359c7cece1f0a463d7d51367 was reverted just now
