### ISSUE TITLE
NullPointerException with CASE statement

### ISSUE THREAD

**Issue by myonlinecode1988** [confluentinc/ksql#3344]
The field `test_data` is of type `VARCHAR`. I was attempting to convert "null" strings to `null`.

This query fails !
```
select case when test_data = 'null' then null
else test_data
end as test_field
from test_stream limit 10;
Caused by: java.lang.NullPointerException
```

This query works !
```
select case when test_data = 'null' then 'HAHA'
else test_data
end as test_field
from test_stream limit 10;
```

Has anyone else faced such an issue and is there a fix for it ?

**Comment by apurvam** [comment]
This seems to be a bug to me. I think it should be legal for the `CASE` statement to evaluate to `null`. Which version of KSQL is this?

**Comment by ehaberman** [comment]
New to the project and tech, but it seems like a simple DB question would work here. Is the field "nullable" as defined or do we assume all fields are "nullable" and this is a bug or KSQL issue?

**Comment by big-andy-coates** [comment]
Fixed by https://github.com/confluentinc/ksql/pull/3531
