### ISSUE TITLE
INSERT VALUES inserts null ROWKEY into stream

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#3349]
```sql
-- Given:
CREATE STREAM ratings (id INT, rating DOUBLE) WITH (kafka_topic='ratings', partitions=1, value_format='json');

-- intuitively I can do this to insert values:
INSERT INTO ratings (id, rating) VALUES (294, 8.1);
```

However, the above inserts a row with a `null` `ROWKEY`.  This is not wrong: a stream can have a null key. But it might not be what the user expects.

A better user experience may be to either:

1. Output the data inserted in the response:

```
-- running:
INSERT INTO ratings (id, rating) VALUES (294, 8.1);

-- responds with:
Inserted:
key: null
value: 294, 8.1
```

2. Require ROWKEY for streams where no key field is supplied. (Don't link this! Why should rowkey be handled differently from other colums).  If the user wants a null rowkey, then they supply `null`.

3. Response with a warning

```
-- running:
INSERT INTO ratings (id, rating) VALUES (294, 8.1);

-- responds with:
value inserted. WARNING: rowkey was null. Was this intentional?
```

**Comment by purplefox** [comment]
I am leaning towards solution 3.

**Comment by blueedgenick** [comment]
seems a bit heavy-handed ? consider, for the same example stream, if i only
run `INSERT INTO ratings(id) VALUES (294);`. Now of course both the
`rowkey` and the `rating` attribute are NULL - but i suggest that this is
not surprising to anyone who used an rdbms. In the absence of nullability
constraints, which one day we may eventually get to, this makes sense:
every attribute, including rowkey (for a stream), is unavoidably
NULL-able.  If we really want to be hand-holding about telling the
user exactly what is happening , then some flavor of Option 1 (printing
exactly what was done) may be appropriate but nothing stronger than that.

**Comment by big-andy-coates** [comment]
After much thought and soul searching we've decided we can trust our users to work this one out without needing to be barraged with feedback ;)
