### ISSUE TITLE
Re-enable disabled JOIN tests.

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#3364]
We have tests disabled in `joins.json` waiting on [KIP-479](https://cwiki.apache.org/confluence/display/KAFKA/KIP-479%3A+Add+StreamJoined+config+object+to+Join).

This is a blocker for the next release.

**Comment by big-andy-coates** [comment]
These tests still fail if re-enabled.  They are expecting an internal topic name of `_confluent-ksql-some.ksql.service.idquery_CSAS_LEFT_OUTER_JOIN_0-KSTREAM-JOINTHIS-0000000008-store-changelog` but actual is  `_confluent-ksql-some.ksql.service.idquery_CSAS_LEFT_OUTER_JOIN_0-Join-this-join-store-changelog`.

This would be a breaking change for our existing users.

**Comment by big-andy-coates** [comment]
Looks like @agavra 'fixed' the expected topologies in commit 9f4dd9cc4dbab2a0656d98a34df2435c2107212f. We'll need to revert this and get all tests passing again if we're to avoid releasing a breaking change.

**Comment by bbejeck** [comment]
But we don't want to revert all the changes as with KIP-307 `Grouped` now names the aggregate processor and the new `StreamJoined` names the join processors.  These are non-breaking changes for the user and should remain in the topology files.  I'll have a PR soon that will re-enable the join tests and disable the naming of join state stores.
