### ISSUE TITLE
ksql-test-runner fails loading hamcrest and other testing jars

### ISSUE THREAD

**Issue by spena** [confluentinc/ksql#3387]
When executing the `ksql-test-runner` from a packaged confluent installation, the following error is thrown:

$ ./ksql-test-runner -s /tmp/statements.sql -i /tmp/input.json -o /tmp/output.json
```
...
Caused by: java.lang.ClassNotFoundException: org.hamcrest.Matcher
    at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

The reason is because the following jars are not packaged in KSQL:
```
ksql-functional-tests/hamcrest-all-1.3.jar
ksql-functional-tests/junit-4.12.jar
```

In 5.3.1, the `kafka-clients-5.3.1-css` is not found either:
```
ksql-functional-tests/kafka-clients-5.3.2-ccs-20190919.011153-4-test.jar
```
**Workaround**
The workaround is to copy the required jars into the confluent/ksql classpath. For instance, being `/opt/confluent/confluent-5.3.1/share/java/ksql` the classpath:

```
$ cd /opt/confluent/confluent-5.3.1/share/java/ksql
$ wget https://repo1.maven.org/maven2/junit/junit/4.12/junit-4.12.jar
$ wget https://repo1.maven.org/maven2/org/hamcrest/hamcrest-all/1.3/hamcrest-all-1.3.jar
```

This bug is found since the `5.3.x` branch.

**Comment by big-andy-coates** [comment]
I've marked this as a blocker for 5.4, which strictly speaking it isn't as its already broken in 5.3.  But we should really get the testing tool into a usable state for this release.

**Comment by holgerbrandl** [comment]
Is there any workaround until the fix? E.g using some pre-release automatically built containerized version of the ksql-test-runner?

**Comment by holgerbrandl** [comment]
Since 0.7 seems still quite far away, I still wonder about a workaround? E.g. by patching the class-path or similar.
