### ISSUE TITLE
Select query takes longer time to fetch results

### ISSUE THREAD

**Issue by MuthiahPrabhakaran** [confluentinc/ksql#3394]
Hi,

I have created a simple stream and table out of that stream without specifying any tumbling time.

CREATE STREAM TEST_STREAM
  (userid BIGINT,
   location VARCHAR)
  WITH (KAFKA_TOPIC='test',
        VALUE_FORMAT='JSON');

CREATE TABLE TEST_TABLE AS
  SELECT userid, location, COUNT(*) AS TOTAL
  FROM TEST_STREAM
  GROUP BY userid, location;

SELECT * FROM MY_TABLE
LIMIT 1;

I tried to query from Stream as well as from the table. Its a simple select query. I hit the KSQL rest enpoint from Postman. It always takes 7 to 10 seconds to return the data. Its just a localhost.

Even, if I hit the same in terminal, it takes the same obvious time which is around 9 seconds.

I couldn't understand why it takes this much time for a simple select query. Is it expected or Am I doing something wrong?

**Comment by cricket007** [comment]
Sorry, what is the definition of `MY_TABLE` look like?

**Comment by MuthiahPrabhakaran** [comment]
Hi @cricket007 ,
Sorry. I have messed up with that table. See the below definition. Original table is also the same as this one.
![thumbnail_image001](https://user-images.githubusercontent.com/33599547/65590713-de626180-dfa8-11e9-92a3-bb71accb9829.png)

**Comment by cricket007** [comment]
I guess my question is - is data actively produced to the topic backing your table?

**Comment by MuthiahPrabhakaran** [comment]
@cricket007 Currently no. Its in development mode. So, I am sending data now and then. Not very actively. 
When I execute this select query, it will take 8 to 9 seconds to fetch the first set of records. Post that, it won't take more than 2 seconds to pull the data from the particular topic. Support if I terminate the query and execute it again, same will happen... First set of records - record 8 to 9 seconds..

**Comment by big-andy-coates** [comment]
Hi @MuthiahPrabhakaran 

How often are you publishing data to the source topic?  KSQL is only going to return rows to you as they change. So if you're only publishing to the source topic every couple of seconds there's going to be a noticeable delay before you see results in the CLI.

On top of that KSQL has to do some work when you initially submit the query. This could be part of the initial delay you're seeing, though when I run locally I don't see delays at the magnitude you're talking about.

At the moment, no real effort has been spent streamlining this initial work as it's not seen as being on the critical path for most use cases. (Conversely, we have done work to optimise the processing of records in persistent queries).  We will get to optimising this too, in time, just not yet.

**Comment by MuthiahPrabhakaran** [comment]
Hi @big-andy-coates ,
Thanks for your valuable input. I look forward to the optimization that you are talking about.

**Comment by big-andy-coates** [comment]
Thanks @MuthiahPrabhakaran - I'm going to close this issue then.  Thanks for posting!
