### ISSUE TITLE
Not receiving proper JSON

### ISSUE THREAD

**Issue by MuthiahPrabhakaran** [confluentinc/ksql#3408]
See the below image.
When I post a KSQL query through postman with limit condition, its returning an improper JSON. I couldn't parse it since its not a proper JSON.
See the highlighted (so called) circle. I had to replace it in a dirty way. Is there any way to receive proper JSON?
![thumbnail_image002](https://user-images.githubusercontent.com/33599547/65593282-c3462080-dfad-11e9-9d8d-53654b7e38b2.png)

**Comment by big-andy-coates** [comment]
Hi @MuthiahPrabhakaran,

I'm assuming what you're after is a `,` in between the `}' and the `{`, right?  Which seems like a valid request, except...

The response is coming from a websocket, where each 'message' stands alone, i.e. each message is a standalone JSON document. It would therefore be incorrect to add the `,` as doing so would make each message contain an invalid JSON document as all but the last message would have an invalid trailing comma.

Hope that makes sense?

**Comment by MuthiahPrabhakaran** [comment]
Yes I understood your point. What's your recommendation to parse this so called JSON in Node.js?

**Comment by big-andy-coates** [comment]
Hey @MuthiahPrabhakaran,

Can I just confirm you are using the websocket end point and not the HTTP one?

**Comment by big-andy-coates** [comment]
I actually think @MuthiahPrabhakaran may have been running into this issue with our non-ws endpoint. If that's the case then it is a bug.
