### ISSUE TITLE
Avro schema validation fails for map types when replaying commands.

### ISSUE THREAD

**Issue by rodesai** [confluentinc/ksql#3460]
When KSQL creates a stream/table sink with an avro schema, it verifies that the schema is compatible with the current schema in the schema-registry, if such a schema exists. When validating map schemas, KSQL uses the avro map type. However when creating map schemas, it uses the format used by connect - a list of key-value pairs. So it's possible for the following series of events to happen:

1. Create a stream/table sink. Validation passes because no schema is currently registered.
2. Start the query, and create the sink schema in the schema registry.
3. Restart ksql. When replaying the command topic, schema validation fails and the query is not started.

To fix this, we should use the correct schema when validating compatibility.

**Comment by vcrfxia** [comment]
This is fixed by https://github.com/confluentinc/ksql/pull/3499.
