### ISSUE TITLE
Implement an expression evaluator without relying on Janino CodeGen

### ISSUE THREAD

**Issue by purplefox** [confluentinc/ksql#3497]
Currently, for every row that's selected at runtime, we use an expression evaluator to compute the value of the list of selects (generated classes). We do this even if the value being selected is a simple field. This results in a Method.invoke() for every column of every row that we select... Might be slow. An optimisation would be only use generated expression evaluators if there's a non trivial expression (e.g. some arithmetic). In other cases we could build more efficient direct evaluators that don't require reflection.

For pull queries, this is even more dramatic because compiling the code generation is expensive and and of itself - in fact it dramatically (anywhere between 2-10x) slows down our pull queries and gets worse linearly with each additional expression.

**Comment by agavra** [comment]
fixed by #7006
