### ISSUE TITLE
KSQL 5.4 syntax changes message improvements

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#3521]
Running Docker images CLI v5.4.0-beta1, Server v5.4.0-beta190925193823, I got this message when running a query from existing docs/demos with a `LIMIT` clause: 

```
ksql> SELECT * FROM POOR_RATINGS LIMIT 5;
Static queries don't support LIMIT clauses. Did you mean to execute a continuous query? Add an 'EMIT CHANGES' clause to do so.

Query syntax in KSQL has changed. There are now two broad categories of queries:
- Static queries: query the current state of the system, return a result, and terminate the query.
- Streaming queries: query the state of the system in motion and continue to output results until they meet a LIMIT clause condition or the user terminates the query.

Use 'EMIT CHANGES' to indicate that a query is continuous and outputs all changes. To convert a static query into a streaming query, which was the default behavior in older versions of KSQL, add `EMIT CHANGES` to the end of the statement before any LIMIT clause.

For example, the following are static queries:
        'SELECT * FROM X WHERE ROWKEY=Y;' (non-windowed table)
        'SELECT * FROM X WHERE ROWKEY=Y AND WINDOWSTART>=Z;' (windowed table)

The following is a streaming query:
        'SELECT * FROM X EMIT CHANGES;'

Note: Persistent queries, like `CREATE TABLE AS ...`, have an implicit `EMIT CHANGES`, but we recommend adding `EMIT CHANGES` to these statements.
Statement: SELECT * FROM POOR_RATINGS LIMIT 5;
```

👏 This is a helpful message, I would make a couple of comments: 

1. If we're going for the pull/push terminology should we use the same here? ATM it talks about `continuous`, `static, `streaming` queries. Perhaps we retain these but include `pull`/`push` in the appropriate place so as to start getting people familiar with the terms? 

2. I did as the message told me but still got an error: 

```
ksql> SELECT * FROM POOR_RATINGS EMIT CHANGES;
line 1:33: extraneous input 'CHANGES' expecting ';'
Statement: SELECT * FROM POOR_RATINGS EMIT CHANGES;
Caused by: line 1:33: extraneous input 'CHANGES' expecting ';'
```

I figured that this was because I was running a previous CLI against the latest Server. Should we : 

a) include in the above Server message a note to the user to make sure they're running the latest CLI? 
b) Make server/CLI exchange some kind of compatability info at the beginning of a session and warn the user?

**Comment by big-andy-coates** [comment]
> If we're going for the pull/push terminology should we use the same here? ATM it talks about continuous, static, streamingqueries. Perhaps we retain these but includepull/push` in the appropriate place so as to start getting people familiar with the terms?

This has already been done in another PR. 

> 2\. I did as the message told me but still got an error:
> 
> ```
> ksql> SELECT * FROM POOR_RATINGS EMIT CHANGES;
> line 1:33: extraneous input 'CHANGES' expecting ';'
> Statement: SELECT * FROM POOR_RATINGS EMIT CHANGES;
> Caused by: line 1:33: extraneous input 'CHANGES' expecting ';'
> ```
> 
> I figured that this was because I was running a previous CLI against the latest Server. Should we :
> a) include in the above Server message a note to the user to make sure they're running the latest CLI?

This can't be done as that error is being generated by the old CLI. The statement never makes it to the server.

> b) Make server/CLI exchange some kind of compatability info at the beginning of a session and warn the user?

That's a solid idea. https://github.com/confluentinc/ksql/issues/4020




> I'd suggest changing
> 
> ```
> Note: Persistent queries, like `CREATE TABLE AS ...`, have an implicit `EMIT CHANGES`, but we recommend adding `EMIT CHANGES` to these statements.
> ```
> 
> to
> 
> ```
> Note: Persistent queries, like `CREATE TABLE AS ...`, have an implicit `EMIT CHANGES`, but we recommend adding `EMIT CHANGES` to these statements for clarity.
> ```
> 
> (i.e. append ` for clarity` to the sentence)

done.
