### ISSUE TITLE
KSQL 5.4 - erroneous message in PRINT

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#3522]
`CLI v5.4.0-beta190925193823, Server v5.4.0-beta190925193823`

Print a topic that doesn't exist: 

```
ksql> print poor_ratings;
Could not find topic 'poor_ratings', or the KSQL user does not have permissions to list the topic.
Did you mean 'POOR_RATINGS'?
KSQL will treat unquoted topic names as uppercase.
To print a case-sensitive topic use quotes, for example: print 'Topic';
```

> KSQL will treat unquoted topic names as uppercase.

My understanding is that as of 5.4 this is no longer the case, so we should remove the message. 

---- 
BTW this is 🥇 👏 :) 

> Did you mean 'POOR_RATINGS'?

**Comment by big-andy-coates** [comment]
Already fixed by https://github.com/confluentinc/ksql/pull/3464
