### ISSUE TITLE
allowing geolocation queries 

### ISSUE THREAD

**Issue by pgibert** [confluentinc/ksql#353]
is it planned to integrate and allow geolocation queries  when you have columns with lat lon ... in the  stream  with some  new  keyword in the ksql dml langage

**Comment by blueedgenick** [comment]
@pgibert can you elaborate a little more on what specifically you were looking for ? e.g. you need some relatively simple "distance between 2 points" kind of functions, or something a little more complex like bounding polygons support, or ....?

**Comment by pgibert** [comment]
hello, i mean the same way elasticsearch does ...  classical  query example
- find all restaurants around this position in 3 km radius

**Comment by rmoff** [comment]
@blueedgenick's `GEO_DISTANCE` UDF addresses this requirement. Closing.
