### ISSUE TITLE
Pull Queries: templated pre-compiled expected WHERE clauses

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#3544]
With pull queries we know we require bounds on ROWKEY and, optionally, WINDOWSTART.

Currently we compile such WHERE clauses on each qull query request. It would be nice if we could avoid this cost.  

We can precompile these, but we'd need to a way to inject the value, i.e. the 'x' in `WHERE ROWKEY='x'`, which is not currently possible. Alternatively, given we know these are simple expressions, we could just something other than compiled code.

**Comment by vinothchandar** [comment]
@big-andy-coates is this planned in the timeframe for november release? We did a small (unscientific) benchmark which seems to suggest a constant 5ms overhead on these queries. 
Would be good to get this done before first release? Came up in a discussion with @derekjn @MichaelDrogalis

**Comment by agavra** [comment]
I'm going to close this in favor of the work being done to remove codegen altogether for pull queries see #3497
