### ISSUE TITLE
Add docker env variable support for embedded connect

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#3551]
With the addition of Connect in KSQL, the `cp-ksql-server` should support environment variables for configuring the Connect worker, just as the `kafka-connect-base` image does. 

[This is the config script](https://github.com/confluentinc/kafka-connect-images/blob/5.4.x-beta/kafka-connect-base/include/etc/confluent/docker/configure) that does it that I guess should be merged into [this](https://github.com/confluentinc/ksql-images/blob/master/cp-ksql-server/include/etc/confluent/docker/configure)? Or added and run in addition to the ksql one at docker container run time.

I guess `KSQL_CONNECT_<foo>` would be the obvious prefix to use

This should be added to the respective documentation too. 

It would be a good idea if some of the `CONNECT_` required vars can be pre-filled by default in KSQL using its own, for example `KSQL_BOOTSTRAP_SERVERS` would also be used for `CONNECT_BOOTSTRAP_SERVERS` etc

I'd suggest these vars aren't mandated and take defaults/inherit the provided KSQL vars: 

```
CONNECT_BOOTSTRAP_SERVERS -> KSQL_BOOTSTRAP_SERVERS
CONNECT_GROUP_ID -> ksql-embedded-connect
CONNECT_CONFIG_STORAGE_TOPIC -> _ksql-embedded-connect_config
CONNECT_OFFSET_STORAGE_TOPIC -> _ksql-embedded-connect_offset
CONNECT_STATUS_STORAGE_TOPIC -> _ksql-embedded-connect_status
CONNECT_VALUE_CONVERTER -> io.confluent.connect.avro.AvroConverter
CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: KSQL_KSQL_SCHEMA_REGISTRY_URL
CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
CONNECT_REST_ADVERTISED_HOST_NAME -> localhost
```

People can then override these if they want but we provide sensible defaults if not. These defaults hopefully line up with what's in the default connect worker properties that we're shipping with ksql-server

**Comment by MichaelDrogalis** [comment]
Whoops, this one went in a long time ago. Closing. :) cc @agavra
