### ISSUE TITLE
Avoid output `null` values when HAVING clauses not met

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#3558]
e.g. given this test case:

```json
{
      "name": "with having expression (stream->table)",
      "statements": [
        "CREATE STREAM TEST (f1 INT) WITH (kafka_topic='test_topic', KEY='f1', value_format='DELIMITED');",
        "CREATE TABLE OUTPUT AS SELECT f1, COUNT(*) FROM TEST GROUP BY f1 HAVING SUM(f1) > 1;"
      ],
      "inputs": [
        {"topic": "test_topic", "key": "1", "value": "1"},
        {"topic": "test_topic", "key": "2", "value": "2"},
        {"topic": "test_topic", "key": "1", "value": "1"},
        {"topic": "test_topic", "key": "2", "value": "2"},
        {"topic": "test_topic", "key": "3", "value": "3"}
      ],
      "outputs": [
        {"topic": "OUTPUT", "key": "1", "value": null},
        {"topic": "OUTPUT", "key": "2", "value": "2,1"},
        {"topic": "OUTPUT", "key": "1", "value": "1,2"},
        {"topic": "OUTPUT", "key": "2", "value": "2,2"},
        {"topic": "OUTPUT", "key": "3", "value": "3,1"}
      ]
    }
```

Notice the `null` value output for the first input row.  This is because the sum of the aggregate after the first row isn't high enough to pass the HAVING criteria.

The issue here is that the HAVING criteria is implemented using a `KTable::filter` call, which is stateless, and hence does not _know_ there hasn't been a previous value that did pass the filter, and so it must emit a tombstone to clear any previous output row.

The fix is actually a fix in KS, which is to turn on `KTableImpl:: enableSendingOldValues` for any filter that is downstream of a statestore.  This will mean the filter receives a CDC event, (old, new), rather than just (new).  Meaning it can be more intelligent and only send the tombstone if the change transitions from passing the filter for the old value to not passing for the new.

**Comment by vector1983** [comment]
@big-andy-coates Any work around for this? I keep see the ERROR log in KSQL:
ERROR Invalid format: 10.121.8.11 : null (io.confluent.ksql.structured.SqlPredicate)

**Comment by big-andy-coates** [comment]
> @big-andy-coates Any work around for this? I keep see the ERROR log in KSQL:
> ERROR Invalid format: 10.121.8.11 : null (io.confluent.ksql.structured.SqlPredicate)

Hi @vector1983, I'm not sure that's the same issue!  

There's no work around at the moment that I'm aware of.

**Comment by Deninc** [comment]
+1 to fix this
It's very confusing, because when we test print in KSQL-CLI it shows only non-null results. But in the actual topics it includes all the nulls. It should be at least explicit and consistent.

**Comment by vvcephei** [comment]
Hey @big-andy-coates , do you mind creating an AK Jira ticket to track this:

> The fix is actually a fix in KS, which is to turn on KTableImpl:: enableSendingOldValues for any filter that is downstream of a statestore.

Thanks!

**Comment by big-andy-coates** [comment]
Added https://issues.apache.org/jira/browse/KAFKA-10077 to track KS work.

**Comment by vvcephei** [comment]
Thanks!

**Comment by big-andy-coates** [comment]
This will also affect users with `WHERE` clauses, (not just `HAVING` clauses), e.g. 

```
CREATE TABLE KT_THERAPISTS AS SELECT
    ID AS THERAPIST_ID
FROM KT_USERS
WHERE ID = 100073;
```

**Comment by stevenpyzhang** [comment]
Adding needs-triage label to discuss if we should include in either 0.12.0/0.13.0

**Comment by big-andy-coates** [comment]
Upstream Kafka Streams work for this is now complete: https://github.com/apache/kafka/pull/9156
