### ISSUE TITLE
Add support for KS suppress functionality

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#3560]
This should likely fit in to the new syntax we have for controlling result materialization, i.e. the `EMIT CHANGES`.  We've discussed `EMIT FINAL` for a final value for push queries and `YIELD FINAL` for pull queries.  However, we need to look at what the suppress functionality has to offer and how is best exposed in KSQL.

**Comment by big-andy-coates** [comment]
see https://github.com/confluentinc/ksql/issues/3560

**Comment by big-andy-coates** [comment]
see https://stackoverflow.com/questions/58358784/ksql-query-returning-unexpected-values-in-simple-aggregation

**Comment by agavra** [comment]
opened #3754 to address this

**Comment by agavra** [comment]
close as duplicate of #1030
