### ISSUE TITLE
Unintuitive interaction between msgRate and maxInterval in KSQL datagen

### ISSUE THREAD

**Issue by vcrfxia** [confluentinc/ksql#3565]
KSQL datagen has two parameters for controlling frequency at which messages are produced and their interaction is confusing:

- `msgRate` ([link](https://github.com/confluentinc/ksql/blob/7260a937b2f602e1d8a84374de91c9d9370da844/ksql-examples/src/main/java/io/confluent/ksql/datagen/DataGen.java#L157)) controls a rate limiter ([link](https://github.com/confluentinc/ksql/blob/7260a937b2f602e1d8a84374de91c9d9370da844/ksql-examples/src/main/java/io/confluent/ksql/datagen/DataGenProducer.java#L118)), so each datagen thread will produce at most `msgRate` messages per second.
- `maxInterval` ([link](https://github.com/confluentinc/ksql/blob/7260a937b2f602e1d8a84374de91c9d9370da844/ksql-examples/src/main/java/io/confluent/ksql/datagen/DataGen.java#L154)) specifies a number of milliseconds such that each datagen thread will wait a (uniformly) random amount of time between 0 and `maxInterval` milliseconds after producing each message, before producing the next one ([link](https://github.com/confluentinc/ksql/blob/7260a937b2f602e1d8a84374de91c9d9370da844/ksql-examples/src/main/java/io/confluent/ksql/datagen/DataGenProducer.java#L135-L137)). This means that, in expectation, up to `1000 / (maxInterval / 2) = 2000 / maxInterval` messages will be produced each second (per thread).

As a result, if `msgRate > 2000 / maxInterval`, then `msgRate` is effectively ignored. Similarly, if `msgRate < 2000 / maxInterval`, then `maxInterval` is effectively ignored. To avoid confusion, we should just have one rate-limiting mechanism for KSQL datagen. My vote is for `msgRate`, though `maxInterval` has been around longer so we might not want to directly remove it if we're concerned about backwards compatibility.

Also, the usage doc for `maxInterval` ("Max time in ms between rows> (defaults to 500)") is confusing.

**Comment by apurvam** [comment]
Thanks for raising this Victoria. I’m +1 for deprecating message interval and standardizing on msgRate.
