### ISSUE TITLE
Pull Queries: Make timeouts configurable

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#3573]
The `DEFAULT_TIMEOUT` timeout used in `KsStateStore` when waiting for a store to become available should be configurable and the exception thrown if the store did not become available within the timeout should include details of the new config and its value.

Likewise, the `OWNERSHIP_TIMEOUT` timeout in `StaticQueryExecutor` should be configurable.

**Comment by vinothchandar** [comment]
@big-andy-coates Do you mind if I assign this as a newbie task to alan (who just joined).

**Comment by apurvam** [comment]
@vinothchandar that sounds like a good plan to me.
