### ISSUE TITLE
Pull Queries: pseudo support for structured keys

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#3584]
Request from @derekjn 

```sql
-- Given:
CREATE TABLE t AS SELECT x, y, count(*) FROM s GROUP BY x, y;

-- it would be nice to be able to do:
SELECT * FROM t WHERE (x, y) = (0, 1);
```

**Comment by big-andy-coates** [comment]
We discussed that this would make sense to add this to KSQL now _if_ it meant we can change how its handled under the hood once we have structured keys, and _if_ it wasn't too much throw away work.

**Comment by agavra** [comment]
This should be complete with the recent work on structured keys.
