### ISSUE TITLE
Support Array constructor

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#3591]
We do not currently have support for creating instances of ARRAYs. Our SQL grammar does have rules for this: `ARRAY[1,2,3]` should create an array.

We should support arrays being created with literals, e.g. `ARRAY[1,2,3]` and with expressions, e.g. `ARRAY[col1, 1 + 2, col3 / col4, max(col5, col6)]`.

We should support constructed arrays being used in:

- INSERT VALUES statements - it's currently not possible to insert an array into an existing source.
- SELECT expressions, e.g. `SELECT ARRAY[col0, col1] FROM ...`
- WHERE/HAVING expressions, e.g. `WHERE col0 = ARRAY[0,2]`
- GROUP BY, e.g. `GROUP BY ARRAY[col0, col1]`
 - etc

**Comment by agavra** [comment]
As a workaround (does not work in `INSERT VALUES`) I introduced the `AS_ARRAY` UDF. I think a valuable improvement would be to also allow `INSERT VALUES` to use UDFs.
