### ISSUE TITLE
Support DECIMAL literals

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#3593]
Similar to https://github.com/confluentinc/ksql/issues/3591 but for DECIMALs.

We need a way for users to construct decimals.  Currently, our SQL parsing rules handle DECIMAL creation:

```
DECIMAL_VALUE
    : DIGIT+ '.' DIGIT*
    | '.' DIGIT+
    | DIGIT+ ('.' DIGIT*)? EXPONENT
    | '.' DIGIT+ EXPONENT
    ;
```

However, this is converted to a `DoubleLiteral` in `ParserUtil`:

```java
public static DoubleLiteral parseDecimalLiteral(final DecimalLiteralContext context) {
   ...
}
```

Given we don't support implicit conversion of `DOUBLE` -> `DECIMAL`, and any such conversion would be potentially lossy anyway, it means we don't have any way for users to create `DECIMAL` literals to use in `INSERT VALUES` or indeed to create `DECIMAL`s to use in any other part of our SQL dialect.

We should look to change our current decimal parsing to return a `DECIMAL` literal, though doing so would be a breaking change without careful management.  We can maybe look to add a compatibility breaking config to decide how decimals should be parsed, and then look to remove this option in the next major release.

**Comment by agavra** [comment]
Perhaps this isn't desired behavior, but you can currently use `INSERT INTO` with a decimal if you represent it as a string (e.g. `INSERT INTO topic (decimalCol) VALUES ("1.12345")`)

**Comment by big-andy-coates** [comment]
We should consider make a breaking change in the next major version so that `12.4555` is a decimal literal, which can implicitly be converted to a double, and not a double, which a) might not be able to represent the number exactly and b) doesn't support implicit casting to decimal.

Marking for 6.0 release.

**Comment by big-andy-coates** [comment]
When we switch to proper decimal support we should remove the magic around string -> decimal coercion.  e.g. in INSERT VALUES functionality, and in ExpectedRecordComparator.java
