### ISSUE TITLE
CLI should not start up if server is down

### ISSUE THREAD

**Issue by mjsax** [confluentinc/ksql#360]
I was playing with the Docker Demo. I forgot the start the KSQL Server and did log into CLI directly. After doing the first command, I got

    java.net.ConnectException: Connection refused

This error is not optimal -- even if I immediately realized that the server was not running. (1) the error message can be improved (2) maybe the CLI should not even start up if the server is down in the first place.

The same happens, if Confluent Platform is not started up yet. (3) There should be different error messages for different services that are not available.

**Comment by miguno** [comment]
FYI: Also tracked internally under ticket 358.

**Comment by apurvam** [comment]
Fixed by #514
