### ISSUE TITLE
INSERT VALUES fails on negative numbers

### ISSUE THREAD

**Issue by agavra** [confluentinc/ksql#3610]
**Describe the bug**
`INSERT INTO ... VALUES` expects `INTEGER_VALUE` or `DECIMAL_VALUE`, neither of which expect a negative sign:
```g4
INTEGER_VALUE
    : DIGIT+
    ;

DECIMAL_VALUE
    : DIGIT+ '.' DIGIT*
    | '.' DIGIT+
    | DIGIT+ ('.' DIGIT*)? EXPONENT
    | '.' DIGIT+ EXPONENT
    ;
```
This results in a parser error (see steps to reproduce)

**To Reproduce**
Master as of 
```sql
ksql> CREATE STREAM LONGS (L BIGINT) WITH (kakfa_topic='longs', value_format='JSON', partitions=1);
ksql> INSERT INTO LONGS (L) VALUES (-1);
line 1:36: extraneous input '-' expecting {')', 'NULL', 'TRUE', 'FALSE', STRING, INTEGER_VALUE, DECIMAL_VALUE}
Statement: INSERT INTO LONGS (L) VALUES (-1);
Caused by: line 1:36: extraneous input '-' expecting {')', 'NULL', 'TRUE',
	'FALSE', STRING, INTEGER_VALUE, DECIMAL_VALUE}
```

**Expected behavior**
Insert into succeeds.

**Actual behaviour**
Errpr

**Additional context**
Reported on Community Slack.

**Comment by agavra** [comment]
This happens because our `SELECT` clauses use the `valueExpression` rule, which allows for a prefixed `operator` (which is a `MINUS | PLUS`). I think the proper fix here is probably to allow `INSERT VALUES` to sue any `valueExpression`.

**Comment by big-andy-coates** [comment]
Is not the correct fix to update the definition for `INTEGER_VALUE` and `DECIMAL_VALUE ` to allow for the minus sign?  

I'm guessing a potential issue is that this would make some things ambiguous, but it might be worth at least trying....

**Comment by agavra** [comment]
@big-andy-coates I was thinking about that, but I think there are some good aspects of having them require positive numbers. `number` (which contains `INTEGER_VALUE` and `DECIMAL_VALUE`) is used to help define `joinWindowSize`, the window unit and interval on `PRINT TOPIC` - all of the things require positive numbers. I think the fix in #3612 is powerful enough to address this ticket, but also many more.

**Comment by big-andy-coates** [comment]
We can add `POSITIVE_INTEGER_VALUE` and `POSITIVE_DECIMAL_VALUE` to handle those, right?

**Comment by agavra** [comment]
Perhaps - though I think that's a whole different subject :)
