### ISSUE TITLE
Consider optimizing "Table is not materialized" error for missing EMIT CHANGES

### ISSUE THREAD

**Issue by derekjn** [confluentinc/ksql#3615]
If this query is run against the stream `stream1`:

```sql
SELECT * FROM stream1;
```
The following error will be thrown:
```
Table 'STREAM1' is not materialized. KSQL currently only supports static queries on materialized aggregate tables. i.e. those created by a 'CREATE TABLE AS SELECT <fields>, <aggregate_functions> FROM <sources> GROUP BY <key>' style statement.
```
Thus the error is currently optimized for assuming the user meant to run a pull query against an unmaterialized relation. However, it is very likely that the reason a user will see this error is because they forgot to include the newly required `EMIT CHANGES` clause.

I think it would probably be more helpful to users if the error in this case suggests that they may have forgotten to include `EMIT CHANGES`.

**Comment by ShahOdin** [comment]
is this: https://github.com/confluentinc/ksql/issues/4493 somehow related to this issue?

**Comment by ShahOdin** [comment]
@derekjn wouldn't adding `emit changes` make it a push query?

**Comment by mjsax** [comment]
I think it would be more useful to just execute the query without the requirement to add `EMIT CHANGE`. Cf. [KLIP-11](https://github.com/confluentinc/ksql/pull/3799)

Also: I thought that KLIP-8 suggested to execute the query and that `EMIT CHANGE` if optional for this case for backward compatibility?

**Comment by big-andy-coates** [comment]
@derekjn 

Current output if you forget to add the EMIT CHANGES is:

```
ksql> create stream foo (ID INT) with (kafka_topic='foo', value_format='json', partitions=1);
create stream foo (ID INT) with (kafka_topic='foo', value_format='json', partitions=1)
 Message        

 Stream created 

ksql> select * from foo;
'FOO' is not materialized. Refer to https://cnfl.io/queries for info on query types. If you intended to issue a push query, resubmit with the EMIT CHANGES clause
 KSQL currently only supports pull queries on materialized aggregate tables. i.e. those created by a 'CREATE TABLE AS SELECT <fields>, <aggregate_functions> FROM <sources> GROUP BY <key>' style statement.
Query syntax in KSQL has changed. There are now two broad categories of queries:
- Pull queries: query the current state of the system, return a result, and terminate. 
- Push queries: query the state of the system in motion and continue to output results until they meet a LIMIT condition or are terminated by the user.

'EMIT CHANGES' is used to to indicate a query is a push query. To convert a pull query into a push query, which was the default behavior in older versions of KSQL, add `EMIT CHANGES` to the end of the statement before any LIMIT clause.

For example, the following are pull queries:
	'SELECT * FROM X WHERE ROWKEY=Y;' (non-windowed table)
	'SELECT * FROM X WHERE ROWKEY=Y AND WINDOWSTART>=Z;' (windowed table)

The following is a push query:
	'SELECT * FROM X EMIT CHANGES;'

Note: Persistent queries, e.g. `CREATE TABLE AS ...`, have an implicit `EMIT CHANGES`, but we recommend adding `EMIT CHANGES` to these statements for clarify.
```

Some thoughts on this:

1. The first line is:

```
'FOO' is not materialized. Refer to https://cnfl.io/queries for info on query types. If you intended to issue a push query, resubmit with the EMIT CHANGES clause
```

which talks about adding EMIT CHANGES, but far to the right on the users screen.  

We need to be careful, as the websocket endpoint truncates error messages to 123 characters, hence having the link early in the error message to give that the best chance of getting through.

2. This is overly verbose.  I think it made sense to have all this info in the error message when we first switch, but we can probably remove this now.

Hence I'm proposing change the error to simple:

```
Can't pull from 'FOO' as it's not a materialized table. See https://cnfl.io/queries for more info.
Add EMIT CHANGES if you intended to issue a push query.
```

On the websocket this will come back as:

```
Can't pull from 'FOO' as it's not a materialized table. See https://cnfl.io/queries for more info.
Add EMIT CHANGES if...
```

Names longer than 'FOO' will mean more of the error message is lost.  We could switch things around:

```
Can't pull as not a materialized table. See https://cnfl.io/queries for more info.
Add EMIT CHANGES if you intended to issue a push query.
Source: Foo
```

Which would _always_ give us this on the websocket error:

```
Can't pull as not a materialized table. See https://cnfl.io/queries for more info. Add EMIT CHANGES if you intended to...
```

NB: the truncated websocket error message is what users of the UI see, or those directly using the ws endpoints.

**Comment by derekjn** [comment]
I think this version is pretty good:

> Can't pull from 'FOO' as it's not a materialized table. See https://cnfl.io/queries for more info.
Add EMIT CHANGES if you intended to issue a push query.

The first sentence of the error is pretty descriptive and should usually be included over websockets. The link will also make it over any websocket responses that have a table name of 39 bytes or less, which is a fair amount of room.

**Comment by rishiCS** [comment]
Hi All, can someone please assign me this issue to work on?
I'm using ksql and want to use select queries on stream which I'm not able to do.
Can anyone please help me here?

**Comment by agavra** [comment]
@rishiCS - you can issue a select query if you use `EMIT CHANGES` (as the error message indicates). Is there something else that you expect that isn't working for you? If so, I recommend you open a new issue since this one is specifically about the error message

**Comment by rishiCS** [comment]
@agavra I'm trying pull queries, and If I'm not wrong I shouldn't use EMIT CHANGES for it right?
Why normal select query doesn't work in ksql on normal stream?
