### ISSUE TITLE
Pretty print: Show queries prints FETCH_FIELD_FROM_STRUCT instead of "->" for structs

### ISSUE THREAD

**Issue by vpapavas** [confluentinc/ksql#3618]
**Is your feature request related to a problem? Please describe.**

Assume a stream created as follows:
``CREATE STREAM metrics_stream (metrics_name STRING, metrics_value DOUBLE, dimensions STRUCT<cluster STRING, topic_name STRING, env STRING>, ts BIGINT) WITH (KAFKA_TOPIC = 'metrics', VALUE_FORMAT = 'JSON', timestamp='ts');``

Issue the following CTAS query:
``CREATE TABLE metrics_table AS 
SELECT metrics_name, dimensions->cluster as cluster, dimensions->topic_name as topic_name, dimensions->env as env, avg(metrics_value) as avg_value 
FROM metrics_stream 
WINDOW TUMBLING (size 60 seconds) 
GROUP BY metrics_name, dimensions->cluster as cluster, dimensions->topic_name as topic_name, dimensions->env;``

Issue `SHOW QUERIES` and the output is:
``CREATE TABLE METRICS_TABLE WITH (KAFKA_TOPIC='METRICS_TABLE', PARTITIONS=1, REPLICAS=1) AS SELECT
  METRICS_STREAM_2.METRICS_NAME "METRICS_NAME",
  FETCH_FIELD_FROM_STRUCT(METRICS_STREAM_2.DIMENSIONS, 'CLUSTER') "CLUSTER",
  FETCH_FIELD_FROM_STRUCT(METRICS_STREAM_2.DIMENSIONS, 'TOPIC_NAME') "TOPIC_NAME",
  FETCH_FIELD_FROM_STRUCT(METRICS_STREAM_2.DIMENSIONS, 'ENV') "ENV",
  AVG(METRICS_STREAM_2.METRICS_VALUE) "AVG_VALUE"
FROM METRICS_STREAM_2 METRICS_STREAM_2
WINDOW TUMBLING ( SIZE 60 SECONDS )
GROUP BY METRICS_STREAM_2.METRICS_NAME, FETCH_FIELD_FROM_STRUCT(METRICS_STREAM_2.DIMENSIONS, 'CLUSTER'), FETCH_FIELD_FROM_STRUCT(METRICS_STREAM_2.DIMENSIONS, 'TOPIC_NAME'), FETCH_FIELD_FROM_STRUCT(METRICS_STREAM_2.DIMENSIONS, 'ENV')
EMIT CHANGES;``

**Describe the solution you'd like**
The output should use "->" instead of the udf name `FETCH_FIELD_FROM_STRUCT`

**Describe alternatives you've considered**

**Additional context**

**Comment by big-andy-coates** [comment]
This should now be fixed with #3639 merged. Can you retest please @vpapavas ?

**Comment by vpapavas** [comment]
Yes it is fixed! Thanks @big-andy-coates !
