### ISSUE TITLE
Support ROWTIME and WINDOSTART in projection list of SELECT queries

### ISSUE THREAD

**Issue by vpapavas** [confluentinc/ksql#3619]
**Is your feature request related to a problem? Please describe.**

Assume a table with schema:
`ROWTIME|ROWKEY|METRICS_NAME |CLUSTER|TOPIC_NAME|ENV|AVG_VALUE`

Assume the following query:
`SELECT avg_value, rowtime FROM metrics_table WHERE rowkey='cluster_lmn|+|topic_2|+|dev';`

The error msg is: 
`Static queries don't support ROWTIME in select columns. Did you mean to execute a continuous query? Add an 'EMIT CHANGES' clause to do so. ... `

Assume the following query:
`SELECT avg_value, windowstart FROM metrics_table WHERE rowkey='cluster_lmn|+|topic_2|+|dev';`

The error msg is: 
`Field 'METRICS_TABLE.WINDOWSTART' cannot be resolved.`

**Describe the solution you'd like**
Support selecting the `ROWTIME` and `windowstart` columns from a windowed table.

**Describe alternatives you've considered**
Use `SELECT * ...`

**Additional context**

**Comment by big-andy-coates** [comment]
I think this is all working for pull queries now.

The 'non-windowed projection with ROWTIME' in 'pull-queries-against-materialized-aggregates.json' proves `ROWTIME` can be used in the projection of pull queries:

https://github.com/confluentinc/ksql/blob/00688fd3194fa276d5727f8a753405384a06c372/ksql-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-materialized-aggregates.json#L573-L592

PR https://github.com/confluentinc/ksql/pull/4404 adds support for `WINDOWSTART` and `WINDOWEND` in the projection of pull queries.
