### ISSUE TITLE
Support ROWTIME in pull queries

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#3623]
This is likely a breaking change as it will require the state store to track the ROWTIME as this information is not available from KS directly.

So at the moment, the data returned from a pull queries does not include any ROWTIME. Which may confuse users. 

What ROWTIME should be returned?  Good question... ideally the ROWTIME of the record in the changelog topic backing the statestore?

**Comment by big-andy-coates** [comment]
Good to keep https://github.com/confluentinc/ksql/wiki/faq%3Apull-queries#why-do-my-pull-queries-not-include-a-rowtime-column in mind...

**Comment by big-andy-coates** [comment]
At the moment, pull queries are only accessing materialized _aggregate_ state.  While the source data may have ROWTIME, which ROWTIME should be stored for the aggregated row?  Many source rows can contribute to the aggregate data in the table's row. So which source row's ROWTIME should used?  This is covered in more detail in the knowledge base article I've linked above.

This brings into question if an aggregate table _should_ have a ROWTIME.

The changelog that backs the table does have an event time, i.e. the timestamp the row was last changed.  Basically a `LAST_MODIFIED` column.  Tailing the changelog via something like `SELECT * FROM X EMIT CHANGES` will return rows with a `ROWTIME` and said `ROWTIME` will, by default, match the timestamp of the record stored in the changelog topic, (I believe).

This suggests that a table could have a `ROWTIME`, (which would semantically be the last modified timestamp).

Interestingly, I think @mjsax has commented elsewhere that he thinks rows in a table don't have a `ROWTIME`.  (cc @mjsax: care to elaborate?).

**Comment by big-andy-coates** [comment]
Looking at KS it now has `TimestampedKeyValueStoreType` which is a state store type that returns not just the value but also the timestamp.  WE can use this to expose ROWTIME. Yay.

My bad - @mjsax comment was not about tables not having ROWTIME, but about not having an OFFSET.

**Comment by mjsax** [comment]
Btw: the question what timestamp is stored is addressed by KS already. This question was part of the https://cwiki.apache.org/confluence/display/KAFKA/KIP-258%3A+Allow+to+Store+Record+Timestamps+in+RocksDB work (in particular https://issues.apache.org/jira/browse/KAFKA-6455)

For aggregations, the stored timestamp is `max(r1.ts,....,rn.ts)` with `r1` to `rn` being all records that contribute to the aggregation result. Hence, the timestamp does never go backwards, even if out-of-order input data arrives.

For `builder.table()` we only log a warning atm if we detect an out-of-order update but apply the update (time might to backwards here) for backward compatibility reasons (also log compaction works on offsets only a thus, if we drop the update the topic an table state might diverge; with https://cwiki.apache.org/confluence/display/KAFKA/KIP-280%3A+Enhanced+log+compaction we might be able to do better...)
