### ISSUE TITLE
A Kafka topic with the name <my topic name> already exists, with different partition/replica configuration than required. KSQL expects 4 partitions (topic has 10), and 5 replication factor (topic has 1)

### ISSUE THREAD

**Issue by NitikaGoel** [confluentinc/ksql#3629]
**Describe the bug**
Not able to create Kafka streams on existing topics using kSQL.

**To Reproduce**
Steps to reproduce the behavior, include:
Run a simple query:
CREATE STREAM <STREAM_NAME> WITH (KAFKA_TOPIC='TOPIC_NAME',VALUE_FORMAT='AVRO');

**Expected behavior**
I should get stream created.

**Actual behaviour**
I Get this error:
A Kafka topic with the name <my topic name> already exists, with different partition/replica configuration than required. KSQL expects 4 partitions (topic has 10), and 5 replication factor (topic has 1)

Error Logs:
"stackTrace": [
        "io.confluent.ksql.services.TopicValidationUtil.validateTopicProperties(TopicValidationUtil.java:55)",
        "io.confluent.ksql.services.TopicValidationUtil.validateTopicProperties(TopicValidationUtil.java:37)",
        "io.confluent.ksql.services.SandboxedKafkaTopicClient.validateTopicProperties(SandboxedKafkaTopicClient.java:151)",
        "io.confluent.ksql.services.SandboxedKafkaTopicClient.createTopic(SandboxedKafkaTopicClient.java:86)",
        "sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)",
        "sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)",
        "sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
        "java.lang.reflect.Method.invoke(Method.java:498)",
        "io.confluent.ksql.util.LimitedProxyBuilder.lambda$buildForwader$8(LimitedProxyBuilder.java:234)",
        "io.confluent.ksql.util.LimitedProxyBuilder$SandboxProxy.invoke(LimitedProxyBuilder.java:312)",
        "com.sun.proxy.$Proxy58.createTopic(Unknown Source)",
        "io.confluent.ksql.topic.TopicCreateInjector.createTopic(TopicCreateInjector.java:183)",
        "io.confluent.ksql.topic.TopicCreateInjector.injectForCreateSource(TopicCreateInjector.java:126)",
        "io.confluent.ksql.topic.TopicCreateInjector.inject(TopicCreateInjector.java:93)",
        "io.confluent.ksql.topic.TopicCreateInjector.inject(TopicCreateInjector.java:77)",
        "io.confluent.ksql.statement.InjectorChain.inject(InjectorChain.java:42)",
        "io.confluent.ksql.statement.InjectorChain.inject(InjectorChain.java:42)",
        "io.confluent.ksql.rest.server.validation.RequestValidator.validate(RequestValidator.java:145)",
        "io.confluent.ksql.rest.server.validation.RequestValidator.validate(RequestValidator.java:115)",
        "io.confluent.ksql.rest.server.resources.KsqlResource.handleKsqlStatements(KsqlResource.java:163)",
        "sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)",
        "sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)",
        "sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
        "java.lang.reflect.Method.invoke(Method.java:498)",
        "org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76)",
        "org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148)",
        "org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191)",
        "org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:200)",
        "org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)",
        "org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)",
        "org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)",
        "org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)",
        "org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)",
        "org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)",
        "org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)",
        "org.glassfish.jersey.internal.Errors.process(Errors.java:316)",
        "org.glassfish.jersey.internal.Errors.process(Errors.java:298)",
        "org.glassfish.jersey.internal.Errors.process(Errors.java:268)",
        "org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)",
        "org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)",
        "org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)",
        "org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416)",
        "org.glassfish.jersey.servlet.ServletContainer.serviceImpl(ServletContainer.java:409)",
        "org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:584)",
        "org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:525)",
        "org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:462)",
        "org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)",
        "org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)",
        "org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)",
        "org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1700)",
        "org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)",
        "org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)",
        "org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)",
        "org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)",
        "org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1667)",
        "org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)",
        "org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)",
        "org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)",
        "org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:152)",
        "org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:174)",
        "org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)",
        "org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:753)",
        "org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)",
        "org.eclipse.jetty.server.Server.handle(Server.java:505)",
        "org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)",
        "org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)",
        "org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)",
        "org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)",
        "org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)",
        "org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)",
        "org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)",
        "org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)",
        "org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)",
        "org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)",
        "org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)",
        "org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)",
        "java.lang.Thread.run(Thread.java:748)"

**Comment by NitikaGoel** [comment]
This issue is coming for all the topics on which i am trying to create new streams

**Comment by agavra** [comment]
Hello @NitikaGoel - which version of KSQL are you using?

**Comment by NitikaGoel** [comment]
Hello, 
I am using CLI v5.3.0, Server v5.3.0 of KSQL

**Comment by agavra** [comment]
Can you also share the `ksql-server.properties` that you are using?

**Comment by NitikaGoel** [comment]
listeners=http://0.0.0.0:8088
ksql.logging.processing.topic.auto.create=true
ksql.logging.processing.stream.auto.create=true
bootstrap.servers=<bootstrap server url for kafka brokers>
ksql.schema.registry.url=<schema registry url>
KSQL_KSQL_SERVICE_ID=ksqlserver

Most of the ksql properties have been set using environment variables in our helm charts

**Comment by NitikaGoel** [comment]
ENVIRONMENT VARIABLES :
KSQL_KSQL_STREAMS_AUTO_OFFSET_RESET=earliest
KSQL_KSQL_STREAMS_NUM_STREAM_THREADS=1

**Comment by agavra** [comment]
@NitikaGoel - thanks for sharing your environment variables. The ones that are probably causing the issue are:
```
KSQL_KSQL_SINK_REPLICAS=5
KSQL_KSQL_SINK_PARTITIONS=4
```
Those were deprecated in 5.3 and aren't necessary. It basically means that if you dont explicitly set the partitions and replicas in a WITH clause, it will use those. If you remove those configs, then it will use the partitions/replicas from the source topic (or if it's a join, from the left source topic).

**Comment by NitikaGoel** [comment]
Thanks @agavra . It resolved our issue.

**Comment by agavra** [comment]
Great! Thanks for circling back - feel free to re-open if you have any other questions.
