### ISSUE TITLE
ksql-cli: Scroll up in terminal does not display previous content

### ISSUE THREAD

**Issue by vpapavas** [confluentinc/ksql#3646]
**Is your feature request related to a problem? Please describe.**
Scrolling up using ksql-cli does not show the full previous content like commands and their output.

**Comment by agavra** [comment]
This is an issue with iTerm specifically - you can resolve it by enabling "Save lines to scrollback when an app status bar is present" in the settings. Feel free to re-open if this doesn't describe your problem or if it doesn't work for you.
