### ISSUE TITLE
Error message exposes internal column name

### ISSUE THREAD

**Issue by vpapavas** [confluentinc/ksql#3650]
**Describe the bug**
Error message displayed is: 
`Invalid key field, not found in schema: KSQL_INTERNAL_COL_1`

**To Reproduce**
Steps to reproduce the behavior, include:
1. The version of KSQL.
Master
2. Sample source data.

Assume stream with schema
`CREATE STREAM metrics_stream (metrics_name STRING, metrics_value DOUBLE, dimensions STRUCT<cluster STRING, topic_name STRING, env STRING>, ts BIGINT) WITH (KAFKA_TOPIC = 'metrics', VALUE_FORMAT = 'JSON', timestamp='ts');`

3. Any SQL statements you ran
`create table test as select dimensions->cluster as cluster , collect_set(dimensions->cluster) as collected from metrics_stream_2 group by dimensions->cluster;`

**Expected behavior**
The query should not fail, but even if it were supposed to fail, the error message does not help identifying what is wrong. Moreover, it should not expose the internal column name `KSQL_INTERNAL_COL_1`.

**Actual behaviour**
A clear and concise description of what actually happens, including:
1. CLI output
2. Error messages
`Invalid key field, not found in schema: KSQL_INTERNAL_COL_1`
3. KSQL logs

**Additional context**
This query does not fail:
`create table test as select metrics_name as cluster , collect_set(metrics_name) from metrics_stream_2 group by metrics_name;`
The problem seems to be in the `STRUCT` column.

**Comment by big-andy-coates** [comment]
This shouldn't be an issue once #https://github.com/confluentinc/ksql/issues/3537 and then #3669 is done

**Comment by big-andy-coates** [comment]
No longer reproducible in master
