### ISSUE TITLE
Avoid logging every pull query in INFO level

### ISSUE THREAD

**Issue by vinothchandar** [confluentinc/ksql#3672]
The log statement in KsqlResource

```
 public Response handleKsqlStatements(
      @Context final ServiceContext serviceContext,
      final KsqlRequest request
  ) {
     LOG.info("Received: " + request);
```

may be ok for non-pull queries. but for pull queries, it will keep flooding the logs since they will be issued at much higher rate

**Comment by big-andy-coates** [comment]
This can be fixed by moving pull queries onto the `/query` endpoint

**Comment by vinothchandar** [comment]
@big-andy-coates do you expect that to happen in the next week?
