### ISSUE TITLE
Breaking change: Rename `ARRAYCONTAINS`

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#3729]
The `ARRAYCONTAINS` method has the description: 

> Given JSON or AVRO array checks if a search  value contains in it 

Looking at the code it seems to have two different code paths:

1. `ARRAYCONTAINS(STRING, STRING)`: If the first parameter passed is a `STRING` it expects it to be a JSON array, e.g. a string such as `"[1,2,3]"`. It will return true if that array contains an element that matches the second parameter, which must also be a string.
1. `ARRAYCONTAINS(ARRAY<T>, T)`, where `T` can be `STRING`, `INT`, `BIGINT` or `DOUBLE` only. If the first parameter passed is an `ARRAY` it looks for the second parameter in the supplied array.

Note: the second code path was added later. The initial version only handled JSON arrays.

Note: there is no support for any 'Avro Array' as the description states and the description does not cover the second code path.

In short, this is two methods rolled into one: a method for checking if an `ARRAY` contains a certain element, and an a method for checking if a Json array contains a certain element.  

We should split this into two methods:

1. `ARRAYCONTAINS` should check for the presence of an element in an `ARRAY` instance. It should be extended to work with _any_ element type, i.e. extended to support `BOOLEAN`, `DECIMAL`, `MAP`, `ARRAY` and `STRUCT` element types.
1. `JSONARRAYCONTAINS` which should accept a `STRING` containing a JSON array. It should be extended to work with element types other than `STRING`. (It looks like the code in `ArrayContainsKudf` can already handle other types, but the only combination registered in `InternalFunctionRegistry` is `ARRAYCONTAINS(STRING, STRING)`.  e.g. we should support `JSONARRAYCONTAINS(STRING, INT)`, and variants with second parameter of type `BIGINT`, `BOOLEAN`, `DOUBLE`, `MAP`, `ARRAY` `DECIMAL` and `STRUCT`.

**Comment by big-andy-coates** [comment]
Fixing this should fix: 
https://github.com/confluentinc/ksql/issues/2644
https://github.com/confluentinc/ksql/issues/3135

These issues highlight how this combination of functionality is confusing users:
https://github.com/confluentinc/ksql/issues/1960
https://github.com/confluentinc/ksql/issues/2210
https://github.com/confluentinc/ksql/issues/2211

**Comment by PeterLindner** [comment]
I think providing a function to turn a json-array-string into an actual `ARRAY` would be even more useful. Then you could keep just the generic version of `ARRAYCONTAINS` and compose the functions for json arrays.

**Comment by agavra** [comment]
@PeterLindner - I looked into this because I totally agree with you. I think the problem is that we don't know what type of array to turn it into at query compilation. For example, what would be the output schema of `SELECT JSON_TO_ARRAY(col1) FROM FOO`? We could always force it to be `ARRAY<VARCHAR>` but that seems a little harsh.

**Comment by PeterLindner** [comment]
@agavra I've thought about that too and I think an explicit cast would be the solution.

So `JSON_TO_ARRAY(col1)` should always return `ARRAY<VARCHAR>` (btw. that function is already requested in #4082 as far as I understand) and one would cast with `CAST(JSON_TO_ARRAY(col1) AS ARRAY<ElementType>)` (I guess that is not supported as of now, haven't tried it). An example query would be:
```sql
SELECT ARRAYCONTAINS( CAST( JSON_TO_ARRAY( col1 ) AS ARRAY<INTEGER> ), 42 ) FROM FOO; 
```
is that too clumsy?
