### ISSUE TITLE
Demo - Grafana 502 error in Data Source

### ISSUE THREAD

**Issue by tvedtorama** [confluentinc/ksql#373]
I followed the docker-based tutorial and got the expected output all the way until I tried the Grafana GUI step.  The GUI shows blank "sections".  Trying to "save and test" the data source just gives a "502" error, no further description.

I run the Grafana web app on Firefox on the Ubuntu linux (VM) that is hosting the Docker container.

![image](https://user-images.githubusercontent.com/18142837/31582772-f81b02ea-b18c-11e7-9d11-2b019c94ea92.png)

**Comment by tvedtorama** [comment]
Might be related to:

https://github.com/confluentinc/ksql/issues/300

However, I get `Failed to connect to localhost port 9200: Connection refused` 

Tried to run `confluent start` but it just says all services are running.

**Comment by bluemonk3y** [comment]
Hi @tvedtorama  - below are some troubleshooting steps. I suspect ES is not running. If 'curl' fails to connect to ES - then the first step should fail. 

1. Check that Elasticsearch is running: http://localhost:9200/.
2. List connectors that have been configured: curl -X "GET" "http://localhost:8083/connectors" 
3. List datasources in grafana: curl -s "http://localhost:3000/api/datasources"  -u admin:admin|jq -c -M '.[]'

**Comment by tvedtorama** [comment]
Hi @bluemonk3y,

you were right.  I tried to start the Elastic Search again in my docker container and it responded with "Failed" in red.

I then deleted the container and tried everything again, curl-polling ES for each step - this time it worked all the way down to and including the browser nirvana-moment.

I guess that ES must have crashed from low memory (only 6MB allocated to the VM running the Docker container).  I also started Firefox in the VM, putting pressure on the memory.  Are there any logs easily available for ES?

Anyways, thanks for this quick and helpful answer - and most of all thanks for launching this very promising KSQL technology, and such a ultra-cool demo!

**Comment by bluemonk3y** [comment]
@tvedtorama  - good news.  Glad you like the tech, yes the demo was fun to put together.

When running OOM Unix will kill various (random) processes to prevent complete OS failure, it happened to choose ES. If you are running with COS if would be worthwhile reducing mem to 256M for all processes (zk, kafka, etc).

**Comment by tvedtorama** [comment]
Ok, 
I see.

If you have time, can you verify that understand the demo correctly?:

* Services are started and then data generators, where some continuously put new data into the topics
* KSQL is used to compose, join and do cool stuff with the tables and streams
    * Outputting to new plain Kafka tables and streams
* We use a "connector" to flow data into ES
* We mount the Grafana dashboard to the "tables" in ES
* Grafana polls ES for updates (or does it feed on RT data?)

Thank you again and good luck with this project!

**Comment by bluemonk3y** [comment]
Hi @tvedtorama  - yes, you have it correct. Remember all ksql.table.streams and ksql.streams have a kafka-topic underneath. Those topics are piped into ES using "Connnect". We then setup Grafana to use an ES datasource (polling)

Thanks

**Comment by datumgeek** [comment]
very helpful thread !! :sparkles: :boom:

**Comment by ramramra** [comment]
Hi guys 
i am using grafana -5.2.1 latest version .Here i have a issues for connect connect to data source elasticsearch 6.2.1 version .it popup with error 502 .I set up everything properly as per documents and guide line .can you guys help me for this error

**Comment by CaptainVincent** [comment]
@ramramra Did you use grafana in docker and the db is outside docker? If that's the case, you can try run docker with **--net=host** option. Because inside docker the default network namespace setting will cause your localhost ip convert to **not** 172.0.0.1.
