### ISSUE TITLE
Breaking Change: Don't include ROWKEY in join schema when selecting all columns

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#3731]
When we perform a join with all columns included, e.g.

```sql
SELECT * FROM A JOIN B ON...
```

Then the output schema contains columns `A_ROWKEY` and `B_ROWKEY`.  However, these columns are not really `KEY` columns anymore, they are now `VALUE` columns, i.e. part of the value stored to Kafka.

In the case where ksql is not doing any implicit repartitioning the two rowkeys will always match, as the join is done on rowkey, and these two columns will also be the string representation of the actual key.

In the case where ksql is doing an implicit repartitioning I *think* it is still the case that `A_ROWKEY` and `B_ROWKEY` are still the same as they come from the repartitioned stream, not the source stream.  (Though this needs confirming).  If this is the case this is actually a poor UX as `A_ROWKEY`, in the case where A was repartitioned, is not actually the key of `A`, but of the repartitioned `A`.

We should think carefully about NOT including `A_ROWKEY` and `B_ROWKEY` in the result schema of the join.

Instead, we could say that any `SELECT *` is including the `ROWKEY` of the output.  For joins this would be the same as both `A_ROWKEY` and `B_ROWKEY` and for non-joins it's basically what we already have.  This implicit `ROWKEY` would remain a `KEY` column, not a `VALUE` column.  

Transient queries, which currently only return the VALUE columns, will need to be changed to include any KEY columns.

Persistent queries, which currently remove any columns called `ROWKEY` or `ROWTIME` from the value schema, can remain as they are.

**Comment by big-andy-coates** [comment]
Thinking on this more, it's less about excluding ROWKEY, and more about excluding the join key.

e.g. consider two source schemas:

```
Table Source USER: [ID INT KEY, NAME STRING]
Stream Source ORDER: [ID INT KEY, USER_ID INT, ITEM_ID INT]
```

And a join:

```sql
SELECT * FROM ORDER JOIN USER ON ORDER.USER_ID = USER.ID;
```

The complete joined schema should included all columns, without duplication of the join field, e.g.

```
[
   USER_ID INT KEY, -- name from left side of join. No need for USER.ID col as it would be a duplicate
  ORDER_ID INT, -- this is ORDER.ID KEY moved into value schema
  ORDER_ITEM_ID INT,
  USER_NAME STRING
]
```

i.e. 

1. The new KEY column comes from ORDER.USER_ID, i.e. the left join field.
1. The USER.ID column is dropped as it is the same as ORDER.USER_ID by definition.
1. The old key columns from both sides become value columns. 

Putting this back into old `ROWKEY` terms, this means we should not be having `LEFT.ROWKEY` and `RIGHT.ROWKEY` from the value schema _if_ the join is on ROWKEY. For joins on fields other than ROWKEY we should be including both ROWKEYs in the value.

**Comment by agavra** [comment]
I'm not sure I understand why "the old key columns from both sides become value columns" by default just in joins. If I understand correctly, we concluded that a `SELECT * FROM FOO` does _not_ include the key columns in the value - is that different when we do `SELECT * FROM FOO PARTITION BY FOO.non_key`? I think we should have one "rule" that makes it easy to understand when a key will be copied into the value schema or not.

**Comment by big-andy-coates** [comment]
Think of it this way, (maybe it helps),

Give a source column set of a [cola, colb, colc], where one of those columns is a key column and then we have a repartition `partition by` call.  At the end, we we may have changed which column is the key column, but the set of columns should not have changed.

Does that make sense / answer your question?

**Comment by agavra** [comment]
I think that makes sense - if the key was `colA` and I did a `SELECT * PARTITION BY colB`, would `colB` remain in the value (duplicated) or would it be "moved to a key"?

**Comment by rodesai** [comment]
> Give a source column set of a [cola, colb, colc], where one of those columns is a key column and then we have a repartition partition by call. At the end, we should have the same set of columns.

One practical limitation with this model is that you now cannot write a query that has a column repeated in both the key and the value (with the same name). Do we want the key and value to be separate namespaces? If we do, then I don't think this works.

**Comment by rodesai** [comment]
Never mind, @agavra convinced me otherwise (that the namespace thing is orthogonal).

**Comment by agavra** [comment]
Summarizing some offline talks with @rodesai - here's how I think about it now. Let's imagine we have a source `FOO (K VARCHAR KEY, A VARCHAR)`

- a `SELECT *` maintains the _exact_ schema of the source, namely `key: K | value: A`
- a `PARTITION BY expression` will _move_ the key to the value schema, and add a new key field, namely: `key: expression | value: A, K`

Therefore, `SELECT * PARTITION BY A` is a special case where `expression` happens to be a column ref to something in the value. It will follow the same steps: (1) copy over the exact schema and (2) move `K` into the value and set `A` as the key. This results in "copying" `A` into the key and leaving it in the value: `key: A | value: A, K`

**Comment by agavra** [comment]
So this is actually different than what you suggest... 🤔 In your suggestion at the end of a partition by we should have the same columns. This is impossible if we `PARTITION BY expression`

**Comment by big-andy-coates** [comment]
moved to the key

**Comment by big-andy-coates** [comment]
It is different to what I'm proposing, but only for the situation where the partition by is by a column. If its an expression then you're essentially creating a new column, which becomes the key and all remaining columns become value columns.  Where the expression is a column, then we can avoid the duplicate column in the value and hence avoid the duplicate data.

I guess it's possible to argue either case: always copy to the value vs don't duplicate a column. Personally, I'm in the 'don't duplicate' camp.

I think another example that may help is one where given a source `FOO (A INT KEY, B INT)` and a `SELECT * FROM FOO PARTITION BY A`, (note: `A` is already the key).

In the 'do not duplicate' camp, the `PARTITION BY A` is a no-op as its already partitioned by `A`.

In the 'always copy to value' camp, would this still copy `A` into the value?

While we internally namespace columns to either the key or value I don't think we should necessarily expose this.  SQL does not normally allow you to have a PK with the same name as another column, so neither should we.  Internally, while executing a query, we may duplicate the key columns into the row passed around the topology, but that is just an implementation detail. Conceptually, we should not support duplicates IMHO.

**Comment by big-andy-coates** [comment]
More correctly for set theory would be to include the full set of columns from all sources, e.g.

```sql
-- I1 schema: ID INT KEY, V0 INT
-- I2 schema: ID INT KEY, V0 INT

SELECT * FROM I1 JOIN I2 ON I1.ID = I2.ID;
```

Should result in a schema containing the six columns.  As `I1.ID` is the new key column, it could be argued that `I2.ID` should remain as a value column.

Note: this is _not_ the same as today, which would see `I1.ID` as the new key column _and_ as a value column.

However, I would argue that as we _know_ I2.ID must be the same as `I1.ID`, we should not include it in the output.  Of course, others may feel otherwise - this is up for debate. Hopefully, what is not up for debate is that `I1.ID` should not be in two columns of the result!

**Comment by big-andy-coates** [comment]
Superseded by [klip-24](https://github.com/confluentinc/ksql/pull/5115).
