### ISSUE TITLE
Pull queries: Create new REST endpoint for pull queries

### ISSUE THREAD

**Issue by vpapavas** [confluentinc/ksql#3742]
**Is your feature request related to a problem? Please describe.**
Currently, pull queries are served through the `/ksql` endpoint. We argue that it makes more sense (both developer and user-facing wise) to have them separated into their own endpoint. 

Reasons: 

1. Pull queries necessitate special handling. Through our benchmarking we realized that the behavior of creating new admin, http, sr clients per request is not feasible nor necessary for pull queries. These happen for ACL validation or RBAC check per request even when RBAC is not enabled. See open PRs https://github.com/confluentinc/ksql/pull/3711 and https://github.com/confluentinc/ksql/pull/3696.  

2. The current two endpoint names are confusing for the user. The `/query` endpoint serves streaming/push queries whereas the `/ksql` endpoint serves DDL, metadata, and static/push queries.  

**Describe the solution you'd like**
Solutions:

1. Introduce a new `/push` endpoint. Problems: Are we decided on the `push` name for static/lookup queries? 

2.  Add `/query/push` and `/query/pull`.  For backwards compatibility we will maintain the current functionality of the `/query` endpoint and have it serve push queries. But as we move forward, we will deprecate it and have only the two new endpoints. The problems with this solution are the same problem as above: Have we decided what we will call the different queries?

**Describe alternatives you've considered**
Solution: Serve both streaming/push and  static/push from the `/query` endpoint. 
Problem: They have different response types. Push queries return a json http response whereas the `/query` endpoint returns a chunked http response for streaming queries. Moreover, they have completely different semantics and it makes it less confusing to the user to have different endpoints. 

**Additional context**
We need to make a decision before the Nov 20 release as that is when we introduce pull queries and we want users to find it easy to use them. It is not in our advantage to make such a public facing change after the release.

**Comment by purplefox** [comment]
I think it's a good idea to separate the admin commands (DDL) from runtime stuff (currently pull queries).

My suggestion would be to separate into:

/admin/xxx - for admin stuff - this is stuff done to setup topologies and interactive stuff from the CLI - i.e. pretty much everything we support apart from pull queries.
/query/xxx - for pull queries.

I don't like the idea of /query/push - for setting up push queries - this is just setting up the query not actually returning the results of the query, hence a completely different kind of thing to /query/pull.

I think the important thing here is whether the operation is admin or non admin as they have completely different performance and scaling requirements and should be separated. 

Taking this further. It might make sense to completely separate admin and non admin into different physical services at some point in the future. Also at some point we probably want to apply different access control depending on whether it's admin or not. E..g. a deployed app might have permission to executed pull queries but not to update ddl.

**Comment by vpapavas** [comment]
>I don't like the idea of /query/push - for setting up push queries - this is just setting up the query not actually returning the results of the query, hence a completely different kind of thing to /query/pull.

That's not true. The `/query` endpoint returns the results of a streaming query in a chunked response. It keeps the connection open until timeout.

**Comment by agavra** [comment]
I think there's still a good chunk of confusion around what types of queries we support and around the push/pull terminology. Here's how I like to think about it (not saying that I'm right about it, but at least it seems internally consistent):
```
                 QUERIES
                /        \
       Persistent         Transient
                         /         \         
                      Push        Pull
```
- **Persistent** queries are basically everything KSQL today is centered around. This is creating new data and putting it into new topics. _All_ queries that are persistent are "push" in the sense that they do not end unless they are terminated, but "push" is not the right word here. Instead I like to use "materializing" or "persistent" - "push" is a client-side concept.
- **Transient** queries are _client_ queries that don't use (at least on the surface) the kafka consumer to read the results of KSQL data
    - **Push** queries open up something like a web socket and keep pushing results as they come in a chunked manner. They will not end unless they are killed in one way or another
    - **Pull** queries issue a one-and-done query to get a set of data, and will terminate when that data is retrieved

I think if we agree on this query model, then we should model our rest endpoints similarly. There should be a `/persistent` endpoint (with a better name, I think `/ksql` makes sense here) and there should be a `/transient` endpoint (with a better name, I think `/query` makes sense here) with two sub-resources `/pull` and `/push` - which is @vpapavas' second solution.

cc @MichaelDrogalis @derekjn @big-andy-coates to comment on what they think of my description :)

**Comment by purplefox** [comment]
> > I don't like the idea of /query/push - for setting up push queries - this is just setting up the query not actually returning the results of the query, hence a completely different kind of thing to /query/pull.
> 
> That's not true. The `/query` endpoint returns the results of a streaming query in a chunked response. It keeps the connection open until timeout.

Thanks for the clarification :) I had no idea we streamed push queries over REST, I thought that they were consumed via Kafka topic consumers! But as long as the admin stuff is kept separate, I think that's the most important thing.

**Comment by MichaelDrogalis** [comment]
@agavra That is pretty close, but there are a couple of tweaks. I think an easy way to break it down is along these 3 core concepts:

1. First, how your data is stored. We do this with streams and tables which support immutability and mutability, respectively. If we want to wrap it up into a single category, we can generically call these "collections". Simple start.

2. Second, how we process your data. Today what we have called "persistent queries" are really processing, and this has led to a lot of confusion about what it supports. A better name for this, as you suggest, are "materialized views." Although we don't yet have syntax in the language to denote them, this is a more accurate description of the function that they serve. So this is any CSAS/CTAS.

3. Finally, there needs to be a way for clients and apps to get at the values of a materialized view. These are "queries", and KSQL now has them in two flavors: push and pull. They are exactly as you described. This is any `select` that isn't instructed to materialize.

It's useful to reserve the term "query" to avoid confusing (2) and (3), which understandably trips up a lot of people.

**Comment by apurvam** [comment]
I agree that separating naming the DDL and DML statements should go to a separate endpoint (we can keep the name `/ksql`). I think `INSERT INTO` statements which write into kafka topics also go to this endpoint today right?

I think separating out the the different types of queries under a `/query` end point makes sense.

However, I'm not sure that `/query/push` is terribly suggestive of the server pushing data to your app in a streaming fashion. From the callers point of view, `/query/push` seems instead to suggest an insert operation of some sort, ie. sending data to the server. On the contrary, I think `/query/pull` is a bit more suggestive of its actual function.

**Comment by big-andy-coates** [comment]
I don't think we need a new endpoint for pull queries. I think we need to move pull queries from the `/ksql` to the `/query` endpoint.  When I implemented pull queries I didn't realize we supported a REST endpoint at `/query`. I had it in my head it was websocket only. 

> 1.  Pull queries necessitate special handling. Through our benchmarking we realized that the behavior of creating new admin, http, sr clients per request is not feasible nor necessary for pull queries. These happen for ACL validation or RBAC check per request even when RBAC is not enabled. See open PRs #3711 and #3696.

Keep in mind that soon pull queries will also support arbitrary queries that may hit Kafka for data. Also, allow users access to materialized state stores without any security checks is a security hole. We'll need to fix this at some point.  Likely by checking the user has access to either all the source topics, (and so could build the result themselves), or maybe the output topic of the aggregate query.

We need to ensure the 'fix' for the performance issues allows for these up coming fixes and enhancements. This is why I'm suggesting we change the ServiceContext to lazily initialize the Kafka|SR|Connect clients on first use.  When we fix the security hole we'll also need to come up with some way to cache clients or the auth result per-user so that we don't reintroduce the perf hit.

> 2. The current two endpoint names are confusing for the user. The /query endpoint serves streaming/push queries whereas the /ksql endpoint serves DDL, metadata, and static/push queries.

As I've said above, we should move the pull queries onto the `/query` endpoint.

> Solution: Serve both streaming/push and static/push from the /query endpoint.
> Problem: They have different response types. Push queries return a json http response whereas the /query endpoint returns a chunked http response for streaming queries. Moreover, they have completely different semantics and it makes it less confusing to the user to have different endpoints.

Both push queries return chunked JSON messages. This is what we'll want pull queries to do too. In the near future pull queries will be returning bigger data sets, which we won't want to load fully into memory first, so a chunked response is what we want.

> We need to make a decision before the Nov 20 release as that is when we introduce pull queries and we want users to find it easy to use them. It is not in our advantage to make such a public facing change after the release.

I don't think this is critical for Nov 20.  This could easily be done after.  This would be a change to the rest api, which we don't officially support as a stable API yet.

**Comment by apurvam** [comment]
> This would be a change to the rest api, which we don't officially support as a stable API yet.

What do you mean? The existing REST API (KSQL 5.3/5.4) is very much officially supported.

**Comment by apurvam** [comment]
> Keep in mind that soon pull queries will also support arbitrary queries that may hit Kafka for data

I think we should make such changes cautiously. Let’s see the usage modes that emerge in the next months, and then expand the surface area more conscientiously.

**Comment by vinothchandar** [comment]
>From the callers point of view, /query/push seems instead to suggest an insert operation of some sort, ie. sending data to the server.
+1 

But won't overloading `/query` with different purposes (returning chunked responses for push vs regular responses for pull) be confusing? We could consider http/2 and multiplex these?

**Comment by vinothchandar** [comment]
@derekjn @MichaelDrogalis The point of having separate endpoints for push/pull was brought up by @big-andy-coates  today. 

Where do we stand on this? Are we planning to make pull queries also send chunked responses? As we saw with Grafana, not all tools may be able to consume this properly. 

Also as a side note, we should move away from http 1.1 to something like http/2 which supports bi-directional streams & request multiplexing. There is almost universal support for http/2 in things like envoy proxy/gRPC and other things people use to build web applications today.

**Comment by MichaelDrogalis** [comment]
We can always evolve the API over different versions, so this doesn't feel like do or die to me. But that said...

I think the real issue is that we haven't figured out what makes a good base API for the system. So for example, Kafka has a strongly defined protocol for all network operations to and between the brokers. Everything goes over this API with no exceptions. But we have rather the opposite. We're trying to cram everything into REST, which wasn't really designed to work well with streaming. We accommodated a bit by having an undocumented websocket API that works arguably better for this piece, but maybe not for everything and so having had the confidence to make this a public API. I agree @vinothchandar that switching over to HTTP 2 will help a lot, but I also think need figure out what makes the best API on top of which we build all other things.

Sorry for the non-answer :)

**Comment by vinothchandar** [comment]
Limiting the scope to immediate concerns.. @big-andy-coates is planning to move pull queries to `/query` shortly, i.e before the imminent release. Should we start with normal responses and then evolve to chunked down the line as we figure out more & add new features? 

What I can tell you as an internal user is that, we can't get grafana working if this is chunked. Not without a side car translator and doing a follow on change anyway to introduce a way to get non-chunked responses.

Now you can pick :)

**Comment by MichaelDrogalis** [comment]
Hah, fair enough @vinothchandar. My vote would be to run pull queries through `/ksql` because very few systems play nice with chunked responses since it's an old HTTP 1.1 thing.

I think that @big-andy-coates is absolutely right that long term we want to be on one endpoint, particularly because we don't want to be in the business of having clients introspecting queries to decide if they are pull or push and choosing the right endpoint. But in the absence of having an API that works equally well for both, we're better off using `/ksql`, otherwise it won't be terribly useable.

**Comment by big-andy-coates** [comment]
I'm planning on raising a PR to switch pull queries over to `/query`. However, the responses won't be chunked.  We only need chunked responses where we don't have all the data in memory.  For this initial release of pull queries we always have the data in memory, so won't chunk responses. in the future, (think scatter/gather style operations to scan the entire table), we will need chunking (or Http2)

**Comment by big-andy-coates** [comment]
out of interest, what's Grafana's issue with chunked responses?  And will switching to Http 2 allow us to stream an unknown sized stream of data to Grafana?

**Comment by vpapavas** [comment]
Grafana currently supports only json responses (non-chunked). But when I asked about it, they said they support RxJS Observables. https://github.com/grafana/grafana/issues/863

**Comment by big-andy-coates** [comment]
It turns out that Grafana has no issue with chunked or non-chunked responses. The issue for Grafana was that our rest API was returning invalid JSON from the `/query` rest endpoint., (#3408).

This issue has now been fixed.
