### ISSUE TITLE
Can not create Stream for the topic of which message contains "load" key in JSON

### ISSUE THREAD

**Issue by joychester** [confluentinc/ksql#3746]
**Confluent and KSQL version**:  5.2.1

**Problem**: Can not create Stream for the topic of which message contains "load" key with JSON format

**Source data**
Send some sample data

POST http://localhost:8082/topics/ksql_test_0/partitions/0

POST data:
{"records":[{"value":{"ts": "2019-11-04T22:36:29-0800", "**load**": 184}}]}

**Create [register] the stream**
🔴 Create a stream with confluent control center, exception occurred:
`line 1:40: extraneous input 'load' expecting {'INTEGER', 'DATE', 'TIME', 'TIMESTAMP', 'INTERVAL', 'YEAR', 'MONTH', 'DAY', 'HOUR', 'MINUTE', 'SECOND', 'ZONE', 'PARTITION', 'STRUCT', 'EXPLAIN', 'ANALYZE', 'TYPE', 'SHOW', 'TABLES', 'COLUMNS', 'COLUMN', 'PARTITIONS', 'FUNCTIONS', 'FUNCTION', 'ARRAY', 'MAP', 'SET', 'RESET', 'SESSION', 'IF', IDENTIFIER, DIGIT_IDENTIFIER, QUOTED_IDENTIFIER, BACKQUOTED_IDENTIFIER}`

Question: Does "load" is a keyword or has special meaning for the KSQL Stream?

Thanks!

**Comment by joychester** [comment]
<img width="640" alt="Screen Shot 2019-11-04 at 23 03 11" src="https://user-images.githubusercontent.com/235618/68185824-5c763880-ff57-11e9-87df-aee673acd182.png">
<img width="643" alt="Screen Shot 2019-11-04 at 23 03 19" src="https://user-images.githubusercontent.com/235618/68185833-65ffa080-ff57-11e9-88fa-4a3ef56edfae.png">

**Comment by agavra** [comment]
It looks like you caught a fringe bug! It seems like "LOAD" is for some reason a reserved word. There is no reason for it to be though, I suppose its an artifact of some time in the past. I will create a PR to remove this from the grammar. In the meantime, you may be able to work around it by quoting it and making it all uppercase (e.g. \`LOAD\`).

**Comment by joychester** [comment]
Thanks @agavra .. suggestion: for the reserved keywords if they are still used , can you use special char to differentiate it, e.g. `_LOAD` ?

**Comment by agavra** [comment]
@joychester - you can use quotes (" or \`) around the reserved word to use them. The quotations are not super reliable prior to 5.4 (which will be released soon)

**Comment by joychester** [comment]
Hi, @agavra , just tried "LOAD" in my JSON payload: 
POST data:
{"records":[{"value":{"ts": "2019-11-04T22:36:29-0800", "LOAD": 184}}]}

still has the same following issue when creating a Stream:
` line 1:40: extraneous input 'LOAD' expecting {'INTEGER', 'DATE', 'TIME', 'TIMESTAMP', 'INTERVAL', 'YEAR', 'MONTH', 'DAY', 'HOUR', 'MINUTE', 'SECOND', 'ZONE', 'PARTITION', 'STRUCT', 'EXPLAIN', 'ANALYZE', 'TYPE', 'SHOW', 'TABLES', 'COLUMNS', 'COLUMN', 'PARTITIONS', 'FUNCTIONS', 'FUNCTION', 'ARRAY', 'MAP', 'SET', 'RESET', 'SESSION', 'IF', IDENTIFIER, DIGIT_IDENTIFIER, QUOTED_IDENTIFIER, BACKQUOTED_IDENTIFIER}`

**Comment by joychester** [comment]
👍works now! Thanks @agavra

**Comment by agavra** [comment]
We decided not to remove the reserved words as we may have future need for them. Closing this ticket out with the solution being to use quoted identifiers!

**Comment by joychester** [comment]
HI, @agavra , 
2 quick questions:
- Is there any doc/wiki to show those reserved words to give people the transparency?
- Can we update the error message more meaningful to highlight the keywords being used:
`extraneous input 'LOAD' (a RESERVED words) expecting..... `

**Comment by agavra** [comment]
@joychester - you can take a look at https://github.com/confluentinc/ksql/blob/558d7302adf24df0dc41e3f19d011a2602ab3ca1/ksql-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4#L337-L456 to see all reserved words (as long as they don't show up in `nonReserved` which is right above.

As far as a better error message, it's a little hard because it's coming directly from ANTLR. We're trying a few things to make the parser error messages better, I'll let you know if I figure anything out.

**Comment by joychester** [comment]
Cool, good to know, thanks @agavra !
