### ISSUE TITLE
How to count amount of elements in array

### ISSUE THREAD

**Issue by mente** [confluentinc/ksql#3793]
Running **ksql-server 5.3.1**. 
I'm trying to get a total amount of unique strings within particular group and window. 

Straight to example:

```
CREATE TABLE orders_with_payments AS SELECT
  o.id "ID",
  o.amount "AMOUNT",
  o.currency "CURRENCY",
  COLLECT_SET(p.paymenthash) "UNIQUE_PAYMENT_HASHES",
  COLLECT_LIST(p.serialized_payment) "SERIALIZED_PAYMENTS",
  COUNT(p.paymenthash) "PAYMENTS_COUNT"
FROM orders_by_reservation o
INNER JOIN payments p WITHIN 1 HOURS ON o.RESERVATION_ID = p.RESERVATIONID
WHERE p.status = 'paid'  AND o.status = 'paid'
GROUP BY o.id, o.amount, o.currency;

CREATE TABLE orders_with_more_than_one_payment
AS SELECT * FROM orders_with_payments
WHERE PAYMENTS_COUNT > 1 AND UNIQUE_PAYMENT_HASHES[1] IS NOT NULL;
```

So `orders_with_payments` table contains grouped order with all payments for it. Now I would like to get only orders with more than 1 real payment (because payments and orders have at-least-once delivery guarantee). Thus I have a second table `orders_with_more_than_one_payment`. 
It is working and there are real results in table but I've noticed some errors in server logs:

```
[2019-11-07 15:52:41,188] ERROR {"type":1,"deserializationError":null,"recordProcessingError":{"errorMessage":"Error evaluating predicate ((ORDERS_WITH_PAYMENTS.PAYMENTS_COUNT > 1) AND (ORDERS_WITH_PAYMENTS.UNIQUE_PAYMENT_HASHES[1] IS NOT NULL)): null","record":null,"cause":["Index: 1, Size: 1"]},"productionError":null} (processing.CTAS_MULTIPLE_PAYMENTS_PER_ORDER_STRATEGY_5.Filter.FILTER:44)
```

My guess is due that error about overflowing of array (because in most cases we don't have >1 payment per order).

Coming back to question - what will be the legit way to get count of array in predicates or output stream/table?

**Comment by mente** [comment]
Anything I can help to move it forward? Give example topics with data and schema ?

**Comment by big-andy-coates** [comment]
Take a look at `ARRAY_LENGTH` and `COUNT_DISTINCT`. Not sure what version they were added in, but these should help you in your quest!
