### ISSUE TITLE
ksql-cli should be able to accept input from STDIN and a filename via an argument

### ISSUE THREAD

**Issue by tunderhill** [confluentinc/ksql#380]

**Comment by hjafarpour** [comment]
@tunderhill KSQL already is able to do this.
1. If you have a query file and you wanna run KSQL by passing the query file you can run the following command for each instance of your application:

$./bin/ksql-node /Users/hojjat/quickstart.sql

This will start the KSQL engine and run the statements in the given file
2. If you wanna just run a single statement you can run the following command:

$./bin/ksql-cli local --exec "SELECT * FROM PAGEVIEWS_ORIGINAL LIMIT 5;"

This will run the given statement and show the results in the terminal.

**Comment by miguno** [comment]
@hjafarpour We should add those examples to the Examples doc.

**Comment by tunderhill** [comment]
Thanks @hjafarpour ksql-node works as you described.
