### ISSUE TITLE
Breaking change. Redesign REST/WS API

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#3816]
We should consider _designing_ our rest/ws API in the next major version bump.

e.g. 

* do we want to move to HTTP/2?  
* Chunking vs non-chunking vs better streaming support
* Standardize on returning Schemas for all /query responses.
* split admin from non-admin, e.g. should INSERT VALUES be on the /ksql endpoint?
* Do we want binary protocol? 

One conn of a binary protocol is that its less accessible than the current HTTP one. Anyone, from pretty much any language, can access our HTTP endpoints. It would be a shame to give this flexibility up.

**Comment by big-andy-coates** [comment]
At the moment, with https://github.com/confluentinc/ksql/pull/3819 merged, our rest API for queries on '/query' does return a valid JSON payload for all requests, except those returning an infinite set of data.   For infinite result sets the client never receives a final row and the array termination character `]`.  

This suggests REST is not a good fit for such responses.

**Comment by big-andy-coates** [comment]
Assigning to Tim as he's looking into this

**Comment by apurvam** [comment]
I think #3649 is only loosely coupled with this. The server side implementation and API design are distinct activities. I think Tim only mentioned actively looking at the latter.

**Comment by purplefox** [comment]
I think this is covered by https://github.com/confluentinc/ksql/pull/4069 and once we have agreement on that, we will create a new set of issues to cover the work that needs to be done, so I'm going to close this one.
