### ISSUE TITLE
Throw a better error message when nonexistent column given to INSERT INTO statement

### ISSUE THREAD

**Issue by derekjn** [confluentinc/ksql#3838]
For the following stream:
```sql
CREATE STREAM test_stream (x VARCHAR, y INTEGER)
  WITH (kafka_topic='test_topic', key='x', value_format='json', partitions=1);
```
And this `INSERT`:
```sql
INSERT INTO test_stream (x, nonexistent) VALUES ('x', 0);
```
This error will be thrown:
```
Failed to insert values into 'TEST_STREAM'. null
```
We should throw a more descriptive error in this case since we know exactly what the problem is.

**Comment by sakshiganeriwal** [comment]
@derekjn @apurvam I was looking into this issue, it looks like the exception message is being passed but the exception object itself is null:
https://github.com/confluentinc/ksql/blob/master/ksql-engine/src/main/java/io/confluent/ksql/engine/InsertValuesExecutor.java#L216
am i looking at the wrong place?

**Comment by apurvam** [comment]
It seems like the right place, but the the exception object seems not to have a message set. If the exception object was null, this should have been an NPE. did you try to inspect the exception thrown?
