### ISSUE TITLE
Throw an error if CLI attempts to connect to an incompatible server version

### ISSUE THREAD

**Issue by vcrfxia** [confluentinc/ksql#3860]
**Is your feature request related to a problem? Please describe.**

As mentioned in https://github.com/confluentinc/ksql/issues/3813, 5.4+ KSQL CLI verisons are incompatible with pre-5.4 server versions (i.e., 5.3 and below). Currently, a user can use a 5.4+ CLI and connect to a pre-5.4 server successfully, but any push queries issued will fail with bizarre error messages (related to the introduction of pull queries in 5.4).

**Describe the solution you'd like**

Rather than allowing the connection followed by poor UX, the 5.4+ CLI should simply throw an error when attempting to connect to a pre-5.4 server.

**Describe alternatives you've considered**

n/a

**Additional context**

**Comment by vcrfxia** [comment]
Another report of user confusion resulting from this:

> The 0.12.0 ksqlDB CLI is incompatible with the 0.14.0 ksqlDB server. The CLI successfully connects but `SHOW STREAMS;` and `SHOW TABLES;` commands fail with an unhelpful message unless there happen to be no streams/tables.

**Comment by nward** [comment]
> Another report of user confusion resulting from this:
> 
> > The 0.12.0 ksqlDB CLI is incompatible with the 0.14.0 ksqlDB server. The CLI successfully connects but `SHOW STREAMS;` and `SHOW TABLES;` commands fail with an unhelpful message unless there happen to be no streams/tables.

I am seeing exactly this.
```
CLI v6.0.1, Server v0.14.0 located at http://10.0.10.15:8088

Having trouble? Type 'help' (case-insensitive) for a rundown of how things work!

ksql> show streams;

at index 2
ksql> show topics;

 Kafka Topic                 | Partitions | Partition Replicas
---------------------------------------------------------------
 default_ksql_processing_log | 1          | 1
---------------------------------------------------------------
ksql> show tables;

 Table Name | Kafka Topic | Format | Windowed
----------------------------------------------
----------------------------------------------
```

0.14.0 client works fine:
```
CLI v0.14.0, Server v0.14.0 located at http://10.0.10.15:8088
Server Status: RUNNING

Having trouble? Type 'help' (case-insensitive) for a rundown of how things work!

ksql> show tables;

 Table Name | Kafka Topic | Key Format | Value Format | Windowed
-----------------------------------------------------------------
-----------------------------------------------------------------
ksql> show streams;

 Stream Name         | Kafka Topic                 | Key Format | Value Format | Windowed
------------------------------------------------------------------------------------------
 KSQL_PROCESSING_LOG | default_ksql_processing_log | KAFKA      | JSON         | false
------------------------------------------------------------------------------------------
```

**Comment by vcrfxia** [comment]
A user on the Slack google group has reported that the 0.14 ksqlDB CLI is incompatible with the 6.0.1 ksqlDB server (approximately ksqlDB 0.10), which is noteworthy since it means we don't have backwards compatibility (between newer CLI versions and older server versions) in all cases either. 

Specifically, describing a stream from the CLI resulted in
```
ksql> describe ITCS_EVENT_JSON_PRODUCTION;
Failed to deserialise object
Caused by: Cannot construct instance of
	`io.confluent.ksql.rest.entity.SourceDescription`, problem:
	queryOffsetSummaries
 at [Source:
	(byte[])"[{"@type":"sourceDescription","statementText":"describe
	ITCS_EVENT_JSON_PRODUCTION;","sourceDescription":{"name":"ITCS_EVENT_JSON_PRODUC
	TION","windowType":null,"readQueries":[],"writeQueries":[],"fields":[{"name":"EV
	ENTTIME","schema":{"type":"STRING","fields":null,"memberSchema":null}},{"name":"
	RECEIVEDTIME","schema":{"type":"STRING","fields":null,"memberSchema":null}},{"na
	me":"OPERATIONALDATE","schema":{"type":"STRING","fields":null,"memberSchema":nul
	l}},{"name":"OPERATORREF","schema":{"type":""[truncated 3209 bytes]; line: 1,
	column: 3693] (through reference chain:
	io.confluent.ksql.rest.entity.KsqlEntityList[0]->io.confluent.ksql.rest.entity.S
	ourceDescriptionEntity["sourceDescription"])
Caused by: queryOffsetSummaries
```
Link to Slack post (this is ephemeral so this link will no longer work after some time): [link](https://confluentcommunity.slack.com/archives/C6UJNMY67/p1610106529135900)
