### ISSUE TITLE
Docker images do not include testing-tool JARs

### ISSUE THREAD

**Issue by agavra** [confluentinc/ksql#3989]
**Describe the bug**

When trying to run the testing tool from the docker image of the server or cli (v0.6.0) with:
```
./ksql-test-runner -s ./test.sql -i ./input.json -o ./output.json
```
The response is an error `Could not find or load main class io.confluent.ksql.test.tools.KsqlTestingTool`. This is caused because we do not package the testing tool jars inside the docker image.

**To Reproduce**
Download the 0.6.0 ksqldb-server docker image and try to run the testing tool.

**Expected behavior**
The testing tool should work

**Actual behaviour**
`Could not find or load main class io.confluent.ksql.test.tools.KsqlTestingTool`

**Comment by vpapavas** [comment]
ETA for fixing this is mid January
