### ISSUE TITLE
Stream-Table join return null table value even after rekey table and table RowTime is earlier than stream

### ISSUE THREAD

**Issue by wengkham** [confluentinc/ksql#3997]
**Describe the bug**
Stream-Table join return null table value even after rekey table and table RowTime is earlier than stream

Attempt to join _EMAIL_HISTORY_ stream with _CONTACT_T_ table on _EMAIL_HISTORY.ContactId_ = _CONTACT_T.Id_ to get _Country_

_EMAIL_HISTORY_
{"Id": 471, "ContactId" : 111170, "Subject": "Hello 1"},
{"Id": 494, "ContactId" : 111170, "Subject": "Hello 2 "},
{"Id": 520, "ContactId" : 111170, "Subject": "Hello 3"},

_CONTACT_T_
{"Id": 111170, "Country": "SG"}

**To Reproduce**
Steps to reproduce the behavior, include:
1. The version of KSQL.
v5.3.1

**Create statement**

`CREATE STREAM CONTACT WITH (KAFKA_TOPIC='Contact', VALUE_FORMAT='AVRO');`
`CREATE STREAM CONTACT_REKEY AS SELECT * FROM CONTACT PARTITION BY Id;`
`CREATE TABLE CONTACT_T WITH (KAFKA_TOPIC='CONTACT_REKEY', VALUE_FORMAT='AVRO', KEY='Id');`
`CREATE STREAM EMAIL_HISTORY WITH (KAFKA_TOPIC='EmailHistory', VALUE_FORMAT='AVRO');`

**Select statement**
`ksql> select rowkey,TIMESTAMPTOSTRING(rowtime,'yyyy-MM-dd HH:mm:ss'), country from CONTACT_T where Id = 111170;`
Result: `111170 | 2019-11-28 10:10:24 | SG`

`ksql> select rowkey,TIMESTAMPTOSTRING(rowtime,'yyyy-MM-dd HH:mm:ss') from EMAIL_HISTORY where CONTACTID = 111170;`
Result:
`Struct{Id=471} | 2019-11-28 10:16:45`
`Struct{Id=494} | 2019-11-28 10:16:45`
`Struct{Id=520} | 2019-11-28 10:16:45`

`ksql> select e.contactid, c.country from EMAIL_HISTORY e left join CONTACT_T c on e.contactid = c.id where e.contactid = 111170;`
Result: 
`111170 | null`
`111170 | null`
`111170 | null`

**Expected behavior**
Joint result should show value of _Country_ instead of null

**Actual behaviour**
_Country_ is null

**Additional context**
kafka topics were populated from MySQL with debezium

**Comment by mjsax** [comment]
With the latest improvements in Kafka Streams, this issue should be resolved:
- https://cwiki.apache.org/confluence/display/KAFKA/KIP-353%3A+Improve+Kafka+Streams+Timestamp+Synchronization
- https://cwiki.apache.org/confluence/display/KAFKA/KIP-695%3A+Further+Improve+Kafka+Streams+Timestamp+Synchronization

Closing this ticket for now.
