### ISSUE TITLE
Restarting KSQL with active transient queries can leave orphaned internal topics

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#4009]
**Describe the bug**
It may be the case that restarting KSQL, while there are running push/transient query that uses internal changelog or repartition topics, results in the internal topics not being deleted

This has been removed on the community slack: 

https://confluentcommunity.slack.com/archives/C6UJNMY67/p1574980967041200

If this is the case, it's probably because we're not `close()`ing transient queries on shutdown, which would clean up these internal topics.  This would fix half the problem.

Of course, we may still have transient topics left around if a node _crashes_ or is killed while there are transient queries.  At the moment, a specific node would not be able to clean these up on restart as they could belong to another node.  We'd need to encode a node identify into the topic name to allow a restarted node to clean up orphaned topics.

**Comment by progocz** [comment]
We could also add support for transient topics to kafka in order to properly solve the issue.

**Comment by big-andy-coates** [comment]
Did some testing. Internal topics are generally cleaned up, but occasionally not. Looks to be some kind of race condition.

Regardless, on hard-kill / crash they will not be, so need some way of cleaning up. e.g. store set
of transient queries in topic/table. Use this to clean up on restart?

**Comment by apurvam** [comment]
I'm dropping this off the milestone, as I don't think we are going to work on it: it's just been carried over blindly.

**Comment by rodesai** [comment]
I think we should consider prioritizing this in 0.14 or 0.15 as we've seen numerous leaks on our soak cluster (see https://github.com/confluentinc/ksql/issues/6360). I'll mark as needs-triage again so we can discuss.

**Comment by apurvam** [comment]
I think we should do this for 0.15.
