### ISSUE TITLE
Documentation on push-pull queries needs clarification.

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#4011]
I've found some time to review the new docs around push and pull queries.  Below are some thoughts...

### Index
link : https://github.com/confluentinc/ksql/blob/master/docs-md/concepts/queries/index.md) 

1. Text is:
> Sometimes, you need to process your events by aggregating them together into a materialized view. In this case, you need a way for your applications or microservices to leverage this view. That's where queries come in.

However, push queries also allow you access to things other than materialized views, i.e. streams!  I can do `SELECT * FROM MYSTREAM;`.

### Push queries doc
link : https://github.com/confluentinc/ksql/blob/master/docs-md/concepts/queries/push.md

1. The text talks about a 'user credit score' example, but the example image is to do with tracking location.

2. Has text:

> They can be used to query either streams or tables for a particular key.

Push are not limited to key look-ups. They support our full set of SQL, including filters, selects, group bys, partition bys, joins, etc.

3. Has text:

> The result of a push query isn't persisted to a backing {{ site.ak }} topic.

What the `{{ site.ak }}` intended?

4. Has text:

> Push queries enable you to query a materialized view with a subscription to the results. Push queries emit refinements to materialized views, which enable reacting to new information in real-time. They’re a good fit for asynchronous application flows. For request/response flows, see Pull Query.

It says above this that push queries can be used to "query either streams or tables", which is correct, so I'm assuming this paragraph is adding more information to the `subscribe to table` side of things. However, it's talking about materialized views: which we want to add, but don't have yet.  So maybe this paragraph would benefit from clarification? Or maybe I'm being overly critical. Not sure. 

### Push queries:
link: https://github.com/confluentinc/ksql/blob/master/docs-md/concepts/queries/pull.md

1. As per pull queries, picture doesn't align with text.
2. Consider changing:

> Pull queries are a form of query issued by a client that retrieve a result as of "now"

To

> Pull queries are a form of query issued by a client that retrieve a result as of "now", like a query against a traditional RDBS.

??

3.  Has text:

> They can only be used to query tables that have been processed into materialized views.

This is misleading / incorrect.  

First, the source might not be a table. It may be a stream, and we're thinking of adding materialized views, so it may be a view!
Second, it's not that pull queries can only be issued against materialized views.  As I've said, we're looking to change most `CREATE TABLE` statements into `CREATE MATERIALIZED VIEW`. Pull queries are currently only available against _materialized aggregate tables/views_, i.e. on something that was built by a persistent query with a `GROUP BY` in it.

4. Do we want to include details of _what_ is currently supported for pull queries?  

Currently, it only states:

> Currently, pull queries only support looking up events by key

Which is true for non-windowed aggregations, but not windowed ones. We could add more detail, e.g.

a. WHERE clause can only have `ROWKEY=x` style bounds for non-windowed tables. Windowed tables also support bounds on `WINDOWSTART` using operators `<=`, `<`, `=`, `>`, `>=`.
b. `JOIN`, `PARTITION BY`, `GROUP BY` and `WINDOW` clauses not supported.
c. SELECTs can contain column arithmetic and function calls.

### Other...

In general, the docs seem to use materialized view and table interchangeable. This could confuse users. Especially as we have no `materialized view` type in KSQL yet.  

Also, how about adding some example SQL to the two push/pull pages?

**Comment by big-andy-coates** [comment]
cc @derekjn @MichaelDrogalis for their views too.

**Comment by derekjn** [comment]
Thanks for sharing your thoughts @big-andy-coates, this is great feedback.
