### ISSUE TITLE
Get the KSQL CLI to work in Windows and Cygwin

### ISSUE THREAD

**Issue by mikeTWC1984** [confluentinc/ksql#402]
No luck getting it to work under CygWin. Would be nice to compile it for Windows.

**Comment by hjafarpour** [comment]
@blueedgenick I remember you were running KSQL on your windows machine. Any suggestions?

**Comment by blueedgenick** [comment]
never tried with cygwin specifically, but i can report that the current .sh scripts have a couple issues which prevent them working in either the git bash shell or the ubuntu-based "bash on windows" thing (some incompatible 'set' options and platform-specific line-endings, iirc).

**Comment by miguno** [comment]
Has this helped you @mikeTWC1984?

**Comment by RxSaml** [comment]
> What i did instead was just run the jar file directly, which is really most of what the shell script does anyway. You can try something like this, which works for me:
> `$ java -jar ksql-cli/target/ksql-cli-0.1-SNAPSHOT-standalone.jar local   

Running ksql-cli this way gave me the following error on Windows : 
`io.confluent.ksql.exception.KafkaResponseGetFailedException:` Failed to retrieve kafka topic names

**Comment by mikeTWC1984** [comment]
I tried this code get same error as Rxsaml, I guess thats probably because kafka is not started. At this point I just use Docker on Ubuntu. I tried Docker tools on my Win 7 machine, got some errors, probably because of java version, I noticed ksql doesn't like recent 1.8 and 1.9 versions.

**Comment by miguno** [comment]
Closing this older ticket because of inactivity.  Feel free to reopen.

**Comment by vikassubramaniam** [comment]
I faced a similar issue in installing Confluent CLI on my windows machine. Finally I got to know from [here](http://www.surfacetablethelp.com/2017/01/windows-10-ubuntu-bash-home-directory-location-and-access-drive-in-bash.html) that the directories of windows are exposed in "Bash on Ubuntu on Windows" through "\mnt\". Then I was able to run the bash commands by appending "\mnt\c\"(for C drive. for D drive it will be "\mnt\d\") at the beginning of paths that are specified in the Bash command.  I didn't get any "Permission denied" errors. Hope this helps someone.

**Comment by bossReact** [comment]
I ran command through ksql-server-start command through cgywin in windows I faced
 ksql-server-start: line 32: E:/confluent-5.5.1-2.12/confluent-5.5.1/bin/ksql-run-class io.confluent.ksql.rest.server.KsqlServerMain: No such file or directory. Need help

**Comment by shdhumale** [comment]
Any update on this error for windows ksql-run-class io.confluent.ksql.rest.server.KsqlServerMain: No such file or directory

**Comment by rmoff** [comment]
In general, I would suggest this approach if you are on Windows and want to run Confluent Platform: https://www.confluent.io/blog/set-up-and-run-kafka-on-windows-linux-wsl-2
