### ISSUE TITLE
Docs Not found cli-config link

### ISSUE THREAD

**Issue by albertosantini** [confluentinc/ksql#4027]
At the page [Develop ksqlDB Applications](https://docs.ksqldb.io/en/latest/developer-guide/) the link (the first one) [Configure ksqlDB CLI](https://docs.ksqldb.io/en/latest/installation/cli-config) is not found.

I think all the folder `installation` has not been deployed.

**Comment by albertosantini** [comment]
The page said `Page last revised on: 2019-12-17` but it contains the same error.

**Comment by JimGalasyn** [comment]
Verified fixed.
