### ISSUE TITLE
Enable configuring Window retention for Kafka Streams from within KSQL

### ISSUE THREAD

**Issue by Tapppi** [confluentinc/ksql#408]
Hey, I've read in one of the blog posts that ksql handles late arriving data by replaying the window it belongs to. This makes sense, but you will have to control the retention period, i.e. how long late-arriving data can be handled. Otherwise you would have to keep all processed windows in memory, no? IIRC kafka streams let's one configure a retention period for this purpose.

If KSQL uses streams' retention to handle late arriving data, what is the retention period configured to, or are all processed windows kept in memory?

**Comment by hjafarpour** [comment]
@Tapppi Thanks for your question. Currently KSQL uses the default retention value the same as Kafka Streams which is 1 day. You can set this to different value in Kafka Streams app but you cannot configure it in KSQL yet. We will be adding this feature in future.

**Comment by apurvam** [comment]
@hjafarpour why can't we configure this through the streams properties using the`SET` statement inside KSQL?

**Comment by rmoff** [comment]
@apurvam I think this came up internally the other day too. I tried this: 

```
ksql> SET 'ksql.streams.retention.ms' = '424242';
ksql> CREATE STREAM RETENTION_TEST AS SELECT * FROM fakedata22;

 Message
----------------------------
 Stream created and running
----------------------------
```

But in the broker log: 

    INFO Created log for partition RETENTION_TEST-1 in /var/lib/kafka/data with properties {compression.type -> producer, message.format.version -> 1.1-IV0, file.delete.delay.ms -> 60000, max.message.bytes -> 1000012, min.compaction.lag.ms -> 0, message.timestamp.type -> CreateTime, min.insync.replicas -> 1, segment.jitter.ms -> 0, preallocate -> false, min.cleanable.dirty.ratio -> 0.5, index.interval.bytes -> 4096, unclean.leader.election.enable -> false, retention.bytes -> -1, delete.retention.ms -> 86400000, cleanup.policy -> [delete], flush.ms -> 9223372036854775807, segment.ms -> 604800000, segment.bytes -> 1073741824, retention.ms -> 604800000, message.timestamp.difference.max.ms -> 9223372036854775807, segment.index.bytes -> 10485760, flush.messages -> 9223372036854775807}. (kafka.log.LogManager)

Note the `retention.ms -> 604800000`. 

Is this the wrong place to look for the retention info, or am I running the command wrong? Thanks

**Comment by apurvam** [comment]
Hey @rmoff , that setting controls the _topic_ retention. This ticket is about controlling the window retention for streams app. I think the window retention config is `ksql.streams.windowstore.changelog.additional.retention.ms`, and it should show up in the ksql logs, not the kafka logs. 

Overriding that property using `set` should work, but I haven't tried it.

**Comment by apurvam** [comment]
As a followup, I ran 

```
ksql> SET 'windowstore.changelog.additional.retention.ms'='200';
```
On the console, and this shows up in the `StreamsConfig` for streams generated in the future.:

```
        windowstore.changelog.additional.retention.ms = 200
```

I am going to close this out.

**Comment by apurvam** [comment]
I turns out that the above config only adding to the retention for the changelgo topic (which is one day). 

Currently there is no way to configure KSQL to pass a different window retention time to the underlying streams apps. So this is a feature request.

**Comment by blueedgenick** [comment]
I believe the enhancement we're looking for is the one tracked in #899 ("Add SQL syntax for window retention time")

**Comment by apurvam** [comment]
Yes. I will close this. Thanks for following up @rmoff !
