### ISSUE TITLE
Ensure joins check key wrapping & format to ensure binary compatibility.

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#4129]
Joins are performed on the binary key.  It is not sufficient for the join columns to have the same Sql type.  They must also have:

* the same format:  serialized as JSON vs KAFKA vs AVRO will result in different binary keys
* the same wrapping: `UNWRAP_SINGLE_KEYS` can change how a single key column is stored, i.e. as a top-level value or wrapped in an object: again resulting in different binary keys.

This will be necessary as we support `KEY_FORMAT` and `UNWRAP_SINGLE_KEYS`.

**Comment by agavra** [comment]
This is completed as part of #6762
