### ISSUE TITLE
Primitive Keys: Support CAST in join criteria

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#4130]
Previously, as all keys were of type `STRING` you could join on two columns of different types, e.g. a `STRING` column that you know to contain a number with an `INTEGER` column, or an `INTEGER` column with a `BIGINT` column.

With primitive key support this is no longer the case.  The `STRING` containing a number won't necessarily be the same as a `INTEGER`.  Hence the join is not allowed. 

This can break users existing joins, with no easy way for them to fix because we don't support arbitrary expressions in the join criteria, i,.e. they can't do:

```
SELECT * FROM A JOIN B ON A.ID = CAST(B.ID AS INTEGER);
```

We could consider supporting casts, or just any expression, in the join criteria.

**Comment by agavra** [comment]
Dropping a note here, but I need to explore more in depth - I'm wondering if this was properly implemented in first place. The partitioning strategy for Strings may not be the same as for Integers (for example) so the co-partitioning requirement may have been broken to begin with.

**Comment by big-andy-coates** [comment]
As discussed, I still think its worthwhile
