### ISSUE TITLE
Primitive Keys: Update demos and examples for primitive key changes in 5.5

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#4144]
- main ksql-examples repo (https://github.com/confluentinc/examples)
- anything robin uses on regular basis.

**Comment by big-andy-coates** [comment]
cc @rmoff can you provide details of any other projects you use that need updating please?

**Comment by big-andy-coates** [comment]
Am I right in thinking these can't be updated until a new CP release goes out with the primitive keys?, i.e. once we have 5.5. builds?

**Comment by big-andy-coates** [comment]
Removing P0 label for 0.7.0 release after talking with MD

**Comment by rmoff** [comment]
* `demo-scene` we don't update for new releases - it's on the user of the material to update it if they want to do so (i.e. versions are left untouched and known-to-work, unless someone opts to bump the version and verify again)
* `examples` and `cp-demo` is owned by @ybyzek and I would assume will need updating for this if it's a breaking hange

**Comment by big-andy-coates** [comment]
done
