### ISSUE TITLE
Introduce TIMESTAMP or DATETIME types

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#4148]
Potentially breaking change...

We should look to switch ROWTIME to be a `TIMESTAMP` or `DATETIME` type, rather than a `BIGINT`.

**Comment by agavra** [comment]
related to #5299

**Comment by agavra** [comment]
Adding this as a p0 to help enable improved connect integration

**Comment by big-andy-coates** [comment]
@agavra may help to add details of _why_ this would help improve connect integration :D

**Comment by agavra** [comment]
Fair enough! Many DBs have columns that use `TIMESTAMP`/`DATETIME` and we convert it usually to just long, which causes issues when we then sink back into a database. It doesn't necessarily mean we need to change `ROWTIME` to those formats, but I was piggy-backing on this ticket as a "let's introduce these new formats".

**Comment by jzaralim** [comment]
Closed with:

https://github.com/confluentinc/ksql/pull/6649
https://github.com/confluentinc/ksql/pull/6806
https://github.com/confluentinc/ksql/pull/6852
https://github.com/confluentinc/ksql/pull/6853
https://github.com/confluentinc/ksql/pull/6901
https://github.com/confluentinc/ksql/pull/6927
https://github.com/confluentinc/ksql/pull/6948
