### ISSUE TITLE
KSQL 5.4.0-beta1 - Arithmetic alters precision of decimal types

### ISSUE THREAD

**Issue by robinroos** [confluentinc/ksql#4162]
Multiplication and division of decimal types, in KSQL, causes the resulting field to have an extended scale beyond those of the decimal types involved.

Perhaps this is deliberate, but is it pretty difficult to work with.  In the example below I value positions differently depending on whether they are long, short or flat.  In the flat case there is no multiplications.  I am then unable to join the flat valuation result to the prior valuation results as the implied schemas differ between result and sink.
 
1 - Value long positions

`CREATE STREAM fx_position_intraday_pl AS SELECT *, (QuotedAmount + (BaseAmount * Bid)) AS SpotVal FROM fx_position_with_market_long;`

Multiplication of decimal(14,4) by decimal (14,4) results in decimal 

2 - Value short positions

`INSERT INTO fx_position_intraday_pl SELECT *, (QuotedAmount + (BaseAmount * Ask)) AS SpotVal FROM fx_position_with_market_short;`

3 - Value flat positions (no multiplication)

```
ksql> INSERT INTO fx_position_intraday_pl SELECT *, QuotedAmount AS SpotVal FROM fx_position_with_market_flat;

Incompatible schema between results and sink. Result schema is [`ROWKEY` STRING KEY, `LONGSHORT` STRING, `BOOK` STRING, `PAIR` STRING, `SETTLEDATE` INTEGER, `BASEAMOUNT` DECIMAL(14, 4), `QUOTEDAMOUNT` DECIMAL(14, 4), `AVGPRICE` DECIMAL(33, 19), `BID` DECIMAL(14, 9), `ASK` DECIMAL(14, 9), `SPOTVAL` DECIMAL(14, 4)], but the sink schema is [`ROWKEY` STRING KEY, `LONGSHORT` STRING, `BOOK` STRING, `PAIR` STRING, `SETTLEDATE` INTEGER, `BASEAMOUNT` DECIMAL(14, 4), `QUOTEDAMOUNT` DECIMAL(14, 4), `AVGPRICE` DECIMAL(33, 19), `BID` DECIMAL(14, 9), `ASK` DECIMAL(14, 9), `SPOTVAL` DECIMAL(30, 13)].
ksql> 
```

4 - Describe the source streams

```
ksql> describe fx_position_with_market_long;

Name                 : FX_POSITION_WITH_MARKET_LONG
 Field        | Type                      
------------------------------------------
 ROWTIME      | BIGINT           (system) 
 ROWKEY       | VARCHAR(STRING)  (system) 
 LONGSHORT    | VARCHAR(STRING)           
 BOOK         | VARCHAR(STRING)           
 PAIR         | VARCHAR(STRING)           
 SETTLEDATE   | INTEGER                   
 BASEAMOUNT   | DECIMAL                   
 QUOTEDAMOUNT | DECIMAL                   
 AVGPRICE     | DECIMAL                   
 BID          | DECIMAL                   
 ASK          | DECIMAL                   
------------------------------------------
```

The _short and _flat streams are equivalent.

5 - Workaround

In this instance I can rewrite the _flat valuation to include multiplication by a decimal which I know will be zero.  But I think there are generally issues with arithmetic altering precision.  For example, my average price column is, as DECIMAL(33,19), is far more "precise" than I could ever desire.  And yet, to render that in a client, I must define an equivalent Avro IDL record with "AvgPrice decimal(33,19)".   

Perhaps we could have a precision clause in KSQL which allows us to dictate the precision which is assigned to an expression result?

I've marked this as a bug, but I understand if you don't see it the same way.

**Comment by agavra** [comment]
Hello @robinroos - the scale/precision calculations that we implemented are inspired directly from other databases (again, linking to transact-SQL because the documentation is very clear, see the table here: https://docs.microsoft.com/en-us/sql/t-sql/data-types/precision-scale-and-length-transact-sql?view=sql-server-ver15 you can also take a look at Oracle SQL documentation: https://docs.oracle.com/javadb/10.6.2.1/ref/rrefsqlj36146.html#rrefsqlj36146). I think that nearly all math concerning decimals necessarily changes the precision (a `DECIMAL(2,1) x DECIMAL(2,1)` will only in exceptional cases fit in `DECIMAL(2,1)`).

> Perhaps we could have a precision clause in KSQL which allows us to dictate the precision which is assigned to an expression result?

I think this is a valid feature request and should resolve your issue. I will retag this issue as a feature request and change the title.

**Comment by agavra** [comment]
By the way, you can cast the result of a math operation to whatever decimal format you want as long as it is valid:

```
ksql> SELECT CAST(val AS DECIMAL(3,1)) FROM DECIMALS EMIT CHANGES;
+----------------------------------------------------------------------------------------------+
|KSQL_COL_0                                                                                    |
+----------------------------------------------------------------------------------------------+
|2.0                                                                                           |
^CQuery terminated
ksql> SELECT CAST(val AS DECIMAL(2,2)) FROM DECIMALS EMIT CHANGES;
+----------------------------------------------------------------------------------------------+
|KSQL_COL_0                                                                                    |
+----------------------------------------------------------------------------------------------+
|null                                                                                          |
^CQuery terminated
ksql> SELECT CAST(val AS DECIMAL(3,2)) FROM DECIMALS EMIT CHANGES;
+----------------------------------------------------------------------------------------------+
|KSQL_COL_0                                                                                    |
+----------------------------------------------------------------------------------------------+
|2.00                                                                                          |
```

There is also a built in `ROUND` UDF that will round decimals to the desired decimal places if the casting is invalid.

```
ksql> DESCRIBE FUNCTION ROUND;

Name        : ROUND
Overview    : Round a value to the number of decimal places as specified by scale to the right
              of the decimal point. If scale is negative then value is rounded to the right of
              the decimal point. Numbers equidistant to the nearest value are rounded up (in the
               positive direction). If the number of decimal places is not provided it defaults
              to zero.
Type        : SCALAR
Jar         : internal
Variations  :

	Variation   : ROUND(val DECIMAL)
	Returns     : DECIMAL

	Variation   : ROUND(val DOUBLE, decimalPlaces INT)
	Returns     : DOUBLE

	Variation   : ROUND(val DOUBLE)
	Returns     : BIGINT

	Variation   : ROUND(val DECIMAL, decimalPlaces INT)
	Returns     : DECIMAL

	Variation   : ROUND(val INT)
	Returns     : BIGINT

	Variation   : ROUND(val BIGINT)
	Returns     : BIGINT
```

Let me know if this addresses your problem.

**Comment by robinroos** [comment]
Attaching the schema of fx_position_with_market_long.

[schema-FX_POSITION_WITH_MARKET_LONG-value-v1.json.txt](https://github.com/confluentinc/ksql/files/3975659/schema-FX_POSITION_WITH_MARKET_LONG-value-v1.json.txt)

**Comment by robinroos** [comment]
Thanks @agavra, I do think that CAST and ROUND will allow me to better control these things.  I will do some testing around that and revert.

**Comment by robinroos** [comment]
The problem reported here can be solved by CAST(... AS DECIMAL(precision, scale)).
