### ISSUE TITLE
KSQLDB - Upper case in all the JSON key

### ISSUE THREAD

**Issue by searceinc** [confluentinc/ksql#4195]
we are using KsqlDB. We created a stream on top of other streams. Then we can see the same stream name as a Topic in Kafka. 

Two things:

1. The topic name is fully upper case. How can I make it lower case (can I use KAFKA_TOPIC='my-lower-case-name' inside the WITH) 
2. The JSON keys in the stream(the topic) are showing UPPER CASE. How fix this? 

My Stream's source SQL:
```
 CREATE STREAM rawstream_mysql_db01_bhuvi_rohi
      (before STRUCT<
            id int, 
            fn VARCHAR, 
            ln VARCHAR, 
       phone int>,
       after STRUCT<
            id int, 
            fn VARCHAR, 
            ln VARCHAR, 
       phone int>, 
       source STRUCT< 
       ts_ms int>,
       op varchar) 
WITH (KAFKA_TOPIC='mysql-db01.bhuvi.rohi', VALUE_FORMAT='JSON');



CREATE stream ksql_mysql_db01_bhuvi_rohi AS
SELECT before->id    AS before_id, 
       before->fn    AS before_fn, 
       before->ln    AS before_ln , 
       before->phone AS before_phone, 
       after->id     AS id, 
       after->fn     AS fn, 
       after->ln     AS ln, 
       after->phone  AS phone , 
       source->ts_ms AS ts_ms , 
       op            AS op 
FROM   rawstream_mysql_db01_bhuvi_rohi ;
```

Read from Kafka (consumer) :
```
{
	"BEFORE_ID": null,
	"BEFORE_FN": null,
	"BEFORE_LN": null,
	"BEFORE_PHONE": null,
	"ID": 5,
	"FN": "rohit",
	"LN": "ayare",
	"PHONE": 87611,
	"TS_MS": 1188887368,
	"OP": "c"
}
```

**Comment by 0x003e** [comment]
Hello,
 \+ Same Upper case on topic table name after: ```CREATE TABLE <name> WITH ....```

**Comment by agavra** [comment]
Hello @searceinc - you can add `CREATE STREAM ... WITH (kafka_topic='foo') AS SELECT ...` to specify the output topic name. To make sure that the fields are case sensitive, escape them using backticks or double quotes:
```
CREATE stream ksql_mysql_db01_bhuvi_rohi 
WITH (kafka_topic='ksql_mysql_db01_bhuvi_rohi')
AS SELECT before->id  AS `before_id`, 
   ...
```
Please let me know if that fixes your issues!

**Comment by mattsurge** [comment]
@agavra what do you suggest if you're using `JSON_SR`?
