### ISSUE TITLE
HA Pull queries: Report both offset and head position

### ISSUE THREAD

**Issue by vpapavas** [confluentinc/ksql#4227]
**Is your feature request related to a problem? Please describe.**
For determining which server is more caught up, have KSQL servers report both their offset and their view of the topic's head position .

**Describe the solution you'd like**
Future proof the current design that supports only offset reporting. This change depends on the outcome of discussion in KIP-535.

**Comment by vinothchandar** [comment]
@vpapavas this is probably an implementation detail in  #4088 ? can we consolidate and close this? wdyt?

**Comment by vpapavas** [comment]
Consolidated with issue #4088
