### ISSUE TITLE
Pull Queries: Heartbeat: Investigate whether to use event loop for scheduling threads

### ISSUE THREAD

**Issue by vpapavas** [confluentinc/ksql#4233]
**Is your feature request related to a problem? Please describe.**
The current design uses `AbstractScheduledService` with a common thread pool. We can instead use a https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/DelayQueue.html to implement the scheduling of the three independent tasks.

**Comment by agavra** [comment]
I'm going to close this as won't do - if someone is working on a project that requires making this change we can revisit at that time.
