### ISSUE TITLE
[feat] Implement basic auth for new API

### ISSUE THREAD

**Issue by purplefox** [confluentinc/ksql#4264]
Parent task https://github.com/confluentinc/ksql/issues/4254

We need to implement basic auth on the new server API.

Take a look at using the Vert.x Web auth functionality to handle basic auth for the new API.

Please see
https://vertx.io/docs/vertx-web/java/#_authentication_authorisation
https://vertx.io/docs/#authentication_and_authorisation
https://vertx.io/docs/vertx-auth-common/java/

Most probably we will have to write our own AuthProvider and integrate it with the existing auth functionality in ksqlDB

**Comment by vcrfxia** [comment]
Implemented in https://github.com/confluentinc/ksql/pull/4685
