### ISSUE TITLE
[feat] Implement Java client

### ISSUE THREAD

**Issue by purplefox** [confluentinc/ksql#4265]
Parent task https://github.com/confluentinc/ksql/issues/4254

Implement a Java client that implements streaming of queries (push and pull), streaming of inserts from client to server, and termination of push queries and admin operations.

The client should expose a reactive streams (publisher/subscriber) API.

**Comment by vcrfxia** [comment]
Marking this as complete as the first version of the Java client with support for push and pull queries, and single row inserts, has been completed for 0.10.0.

The remaining tasks for 0.11.0 are tracked separately:
https://github.com/confluentinc/ksql/issues/5583
https://github.com/confluentinc/ksql/issues/5584
https://github.com/confluentinc/ksql/issues/4286
