### ISSUE TITLE
Pull Queries: Heartbeat: Replace TreeMap with List

### ISSUE THREAD

**Issue by vpapavas** [confluentinc/ksql#4277]
**Is your feature request related to a problem? Please describe.**
Currently heartbeats are stored in a concurrent hash map of tree maps. The alternative solution is to keep them in a list. We append to the list the new heartbeats. For processing them, we remove the heartbeats into a different data structure and then order them for processing. 

**Describe the solution you'd like**
We should investigate which approach is more performant.

**Comment by agavra** [comment]
I'm going to close this out as won't do - if we ever need to focus on performance improvements we should have that as an independent project, and the owner can be responsible of triaging and figuring out what is best.
