### ISSUE TITLE
Docker: Update docker-compose in quickstart guide

### ISSUE THREAD

**Issue by vpapavas** [confluentinc/ksql#4303]
After we create the new docker images, we need to update the docker-compose.yml file on our quickstart guide to include 
```
KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
```

**Comment by JimGalasyn** [comment]
Fixed by @colinhicks in https://github.com/confluentinc/ksql/commit/641c7dd740a3b3793b9d5a8b10bfbd6f162f4874.
