### ISSUE TITLE
Pull Queries: SslFactory.configure consumes a large fraction of handling time.

### ISSUE THREAD

**Issue by AlanConfluent** [confluentinc/ksql#4305]
**Describe the bug**
When profiling pull query benchmarks, I noticed a large slice of time was spend handling SslFactory.configure.  This seems to be something that doesn't need to be configured per request and could be made a singleton.

**Comment by vinothchandar** [comment]
Should we now do a different annotation on the PR to close the issue? @AlanConfluent i saw you had `Fixes` .. but did not seem to close this one.
