### ISSUE TITLE
`SHOW QUERIES` should include transient queries

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#4308]
With issues such as https://github.com/confluentinc/ksql/issues/4296, it would probably be useful for people to be able to see what transient queries are running.   Such queries could be causing issues.

Hence, I think `SHOW QUERIES` should include transient queries.

**Comment by big-andy-coates** [comment]
We should make sure its clear what is a transient query and what is a persistent query.

**Comment by stevenpyzhang** [comment]
Some questions I could use some clarification on for this.

There's currently no QueryId stored in TransientQueryMetadata so would that column in `Show Queries` response be blank? Or should QueryId's be added to TransientQueryMetadata ? 

You only mentioned the regular show queries, so we don't want transient queries to also show up in `Show Queries Extended`?

Is the query string not enough of a distinction between a transient and a persistent query? CTAS/CSAS indicates Persistent and `Select ...` Transient (do we need an extra column indicating whether it's transient/persistent?)

**Comment by stevenpyzhang** [comment]
What it's looking like currently
``` 
Query ID                                                            | Kafka Topic    | Query String                                                                                           
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CSAS_DOUBLE_6                                                       | DOUBLE         | CREATE STREAM DOUBLE WITH (KAFKA_TOPIC='DOUBLE', PARTITIONS=1, REPLICAS=1) AS SELECT *
FROM PAGEVIEWS_COPY PAGEVIEWS_COPY
EMIT CHANGES; 
 CSAS_PAGEVIEWS_COPY_0                                               | PAGEVIEWS_COPY | CREATE STREAM PAGEVIEWS_COPY WITH (KAFKA_TOPIC='PAGEVIEWS_COPY', PARTITIONS=1, REPLICAS=1) AS SELECT *
FROM PAGEVIEWS PAGEVIEWS
EMIT CHANGES; 
 _confluent-ksql-default_transient_4236186162078317116_1579133444796 | PAGEVIEWS      | select userid from pageviews emit changes;                                                             
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
For detailed information on a Query run: EXPLAIN <Query ID>;
ksql> 
```

An extended output
```
ID                   : 
SQL                  : select userid from pageviews emit changes;

 Field  | Type            
--------------------------
 USERID | VARCHAR(STRING) 
--------------------------

Sources that this query reads from: 
-----------------------------------
PAGEVIEWS

For source description please run: DESCRIBE [EXTENDED] <SourceId>

Execution plan      
--------------      
 > [ PROJECT ] | Schema: ROWKEY STRING KEY, USERID STRING | Logger: 4236186162078317116.Project
                 > [ SOURCE ] | Schema: PAGEVIEWS.ROWKEY STRING KEY, PAGEVIEWS.ROWTIME BIGINT, PAGEVIEWS.ROWKEY STRING, PAGEVIEWS.VIEWTIME BIGINT, PAGEVIEWS.USERID STRING, PAGEVIEWS.PAGEID STRING | Logger: 4236186162078317116.KsqlTopic.Source


Processing topology 
------------------- 
Topologies:
   Sub-topology: 0
    Source: KSTREAM-SOURCE-0000000000 (topics: [pageviews])
      --> KSTREAM-TRANSFORMVALUES-0000000001
    Processor: KSTREAM-TRANSFORMVALUES-0000000001 (stores: [])
      --> Project
      <-- KSTREAM-SOURCE-0000000000
    Processor: Project (stores: [])
      --> KSTREAM-FOREACH-0000000003
      <-- KSTREAM-TRANSFORMVALUES-0000000001
    Processor: KSTREAM-FOREACH-0000000003 (stores: [])
      --> none
      <-- Project
```

**Comment by big-andy-coates** [comment]
> There's currently no QueryId and there are no sinks associated with a transient query in TransientQueryMetadata so the `Query ID` and `Kafka Topic` columns in `Show Queries` response are blank. Should QueryId's be added to TransientQueryMetadata? I could potentially use the query application id as the "query id" for a transient query and the sourceNames for the Kafka Topic column, is that acceptable?

Yeah, I'd add a `QueryId` to `TransientQueryMetadata`. I see in your example output you've got `_confluent-ksql-default_transient_4236186162078317116_1579133444796`. Maybe the queryId should be just the `4236186162078317116_1579133444796` part?

Transient queries don't have a sink topic, so that column should be blank, i.e. the `getSinks` method should return an empty set.

I'd also add a new `type` field to `RunningQuery` differentiate between query types. Have a new enum e.g. `enum QueryType{ PUSH, PERSISTENT}`, and output that in a column in the table, and also in any description of the query, i.e. the extended view.

> 
> You only mentioned the regular show queries, so we don't want transient queries to also show up in `Show Queries Extended`?

They should show up in extended too.

> 
> Is the query string not enough of a distinction between a transient and a persistent query? CTAS/CSAS indicates Persistent and `Select ...` Transient (do we need an extra column indicating whether it's transient/persistent?)

I'd add the type as a column. It's less ambiguous for users and makes it clearer there are two types here, not just different names.

> 
> On a tangent to the above, instead of combining both transient/persistent queries into a single command, would it make sense to split it out into `Show Queries Transient` and `Show Queries Push`?

Terminology wise, push and pull queries are both transient. For now, pull queries won't be returned in the list as they're not long running (in general). We may add them once they become long running.

I was thinking about adding an `ALL` option, as exists for other commands, e.g. show topics. However, that only allows either _just persistent_ or _all_.  What if they just want push?   Your idea fits better here.

We could change the syntax rule to:

> | (LIST | SHOW) (PUSH | PERSISTENT)? QUERIES EXTENDED?                                       #listQueries

This would mean:

* `show queries` would list all queries.
* `show push queries` would list only push queries.
* `show persistent queries` would list only persistent queries.

Note, you can likely add `PUSH` and `PERSISTENT` to the `nonReserved` list so that they can be used as identifiers.

**Comment by rodesai** [comment]
We need to think through the behavior for multi-node clusters. Currently the different KSQL nodes are not aware of transient queries running on the other nodes. Without some mechanism in place for sharing this information between nodes the user can't really reason about what queries exist based on the response they get back.

We have some options here:
- The ongoing heartbeat work has a way of discovering the nodes in the cluster. We could use the list of discovered nodes to do a scatter-gather when listing queries.
- Instead of a scatter-gather we could report new queries. However if we go this route we should probably either go through Kafka, or include this info as part of some periodic report so that the reporting mechanism is reliable.

Unfortunately none of these things is a small amount of work, and I think they allude to something that merits broader discussion - having a way of sharing metadata across the cluster. However without this I'm not sure that including transient queries in the listing is an improvement since it might cause confusion.

**Comment by stevenpyzhang** [comment]
@big-andy-coates any thoughts on @rodesai comment for multi-node cluster behavior? I think the inspiration you had for creating this issue was when debugging a cluster with a single node. However, there may be multiple nodes eventually and which server gets a particular request is determined by a load balancer (random) which might not always hit the particular node with the transient query running i.e. running `Show Query` twice in a row with this transient query functionality added might return different results depending on which node served the request.

**Comment by big-andy-coates** [comment]
Makes sense that we need info from other nodes.
