### ISSUE TITLE
SHOW QUERIES has incorrect field heading

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#4344]
`Kafka Topic` should be `KSQL object` (or similar) - it's definitely _not_ Kafka topic though. In this example here the topic is `BAR` but `SHOW QUERIES` says it's `FOO2` (which is the name of the stream)

```
ksql> CREATE STREAM FOO2 WITH (KAFKA_TOPIC='BAR') AS SELECT * FROM KSQL_PROCESSING_LOG;

 Message
------------------------------------------------------------------------------
 Stream FOO2 created and running. Created by query with query ID: CSAS_FOO2_2
------------------------------------------------------------------------------
ksql> SHOW QUERIES;

 Query ID    | Kafka Topic | Query String
---------------------------------------------------------------------------------------------------------------
 CSAS_FOO2_2 | FOO2        | CREATE STREAM FOO2 WITH (KAFKA_TOPIC='BAR', PARTITIONS=1, REPLICAS=1) AS SELECT *
FROM KSQL_PROCESSING_LOG KSQL_PROCESSING_LOG
EMIT CHANGES;
---------------------------------------------------------------------------------------------------------------
For detailed information on a Query run: EXPLAIN <Query ID>;
ksql>
```

This may seem like a nit, but if you're using `SHOW QUERIES` and want to match a query with a stream, this mislabeling makes things more difficult.

**Comment by stevenpyzhang** [comment]
I still need to look a bit closer into this, but it seems like we always just assume the name of the Stream/Table created by a CTAS/CSAS will be the name of the sink topic which is why `FOO2` is returned instead of the true sink topic `BAR`. This happens during the parsing stage of the statement.
