### ISSUE TITLE
Bad error message inserting when no Schema Registry connectivity

### ISSUE THREAD

**Issue by MichaelDrogalis** [confluentinc/ksql#4347]
**Describe the bug**

When inserting a record into a stream that's serialized with Avro, a poor error message is raised if ksqlDB can't connect to Schema Registry.

**To Reproduce**

With ksqlDB 0.6.0, where Schema Registry is not configured on the server:

```sql
CREATE STREAM s1 (c1 varchar) WITH (kafka_topic='t1', partitions=1, key='c1', value_format = 'avro');

insert into s1 (c1) values ('a');
```

**Expected behavior**

An error message indicating that ksqlDB couldn't connect to Schema Registry.

**Actual behaviour**

```
Failed to insert values into 'S1'. Could not serialize row: [ 'a' ]
```

This error message is tough because in a more complex setting, it leads the user to believe that it's a problem with their data.

**Comment by stevenpyzhang** [comment]
@MichaelDrogalis this should be fixed with https://github.com/confluentinc/ksql/pull/4325
The error message should now say something like:
```
Caused by: KSQL is not configured to use a schema registry. To enable it, please
        set ksql.schema.registry.url
```

**Comment by MichaelDrogalis** [comment]
@stevenpyzhang Nice one. Closing, staged for 0.7.
