### ISSUE TITLE
Pull Queries: HA routing: Skip loop when routing to standby

### ISSUE THREAD

**Issue by vpapavas** [confluentinc/ksql#4413]
**Is your feature request related to a problem? Please describe.**
When the router tries the active and fails, it then tries the standby. However, since the query is forwarded to the standby like a normal http request, it goes through the same code path in `PullQueryExecutor` where it first tries the active and then itself. We can improve upon this, if we can annotate the request that it is not the original but an internal forwarded one and skip the routing loop.

**Comment by vinothchandar** [comment]
@vpapavas IIUC you have already done this?
