### ISSUE TITLE
SELECT statements hang in ksql-cli and server mode

### ISSUE THREAD

**Issue by alexhafner** [confluentinc/ksql#442]
We have upgraded to the latest relase of ksql today.

Now we've got a new hanging situation. DDL such as creating tables and streams work, but SELECTing does not, both for cli and server mode. There's no entry in the log, I attach a java stackdump for a stuck CLI scenario.

[ksql_hang_on_select.txt](https://github.com/confluentinc/ksql/files/1451806/ksql_hang_on_select.txt)

**Comment by bluemonk3y** [comment]
thanks @alexhafner  - could you provide some basic steps to reproduce? (everything working for me)

**Comment by alexhafner** [comment]
Hi @bluemonk3y - I retested this today and can no longer reproduce this. I'll make a note for our testing procedures that we'll also verify that the kafka topic actually streams data with a second method when we run into situations like this - maybe the topic did not produce new records during our test period yesterday and we've interpreted this as a hang when we were purely waiting for data.
