### ISSUE TITLE
Support non-key joins.

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#4424]
With https://cwiki.apache.org/confluence/display/KAFKA/KIP-213+Support+non-key+joining+in+KTable complete, we should be able to enhance ksqlDB to support non-key joins!

**Comment by entechlog** [comment]
@big-andy-coates , @vpapavas Is support for non key table join coming to ksqlDB in 0.8.0 release ? We have a project going into production in second quarter of this year and its heavily dependent on table joins which always dont share same primary key. Without this feature GlobalKTable and custom kafka streams may be our only option (which we were trying to avoid with ksql platform)

**Comment by vpapavas** [comment]
Hi @entechlog, unfortunately foreign key joins are not coming in 0.8.0. How about creating additional tables that have as primary key the join key you are interested in? Simulate the behavior of secondary indeces basically by creating extra tables by hand that have the schema you need for each join you are interested in,

**Comment by entechlog** [comment]
@vpapavas ,
I don't think creating an additional table will always help, Unless I am missing something. Please see below example.

Here I need to join the orders table every time when an order comes in with user table and both has different PK's. I can't make USER_ID as PK in orders table, then it will retain only one order record, Unless the PK's are same ksqlDB is not letting to join the tables.

**TBL_ORDERS**
_ORDER_ID - Primary Key_
ITEM_ID
ITEM_DESC
QUANTITY
PRICE
USER_ID

**TBL_USER**
_USER_ID - Primary Key_
USER_NAME
USER_EMAIL
USER_PHONE

**Comment by PeterLindner** [comment]
@entechlog you have to convert your orders table to a stream partitioned by user ID, then you can perform a stream - table join on user ID, repartition back to order ID and convert back to a table
Note however that changes to the user table would not apply to older orders, if you need that I believe the only way to do this is to use the collect_set udaf to collect all order ids grouped by user ID (yields a table), perform a stream-table join with a user stream to get a message for each user modification and then explode an repetition on the collected order ids to propagate the modifications to the orders, then join that stream with the original orders table and insert into the orders stream and again create a table from it.
I hope you could follow :wink: note that I haven't tried that myself yet, but I will have to do something similar for my use case once I get my data into Kafka, so please tell me if it worked.

**Comment by entechlog** [comment]
@PeterLindner, Thanks for the input. We are trying several things and will keep you posted on what we  end up doing. The example was just to share the idea but we are dealing with much complex with multiple self joins and self joins based on result from aggregation of all historical data.

**Comment by bellemare** [comment]
@big-andy-coates I was actually just about to email you about this, as I see you've done a lot of work on the joins to date. I contributed the PR (with some help from many fine people) for KIP-213 mentioned above, and I've been looking at how to get this into KSQL. I've been looking under the hood of KSQL and I admit that I don't have a firm handle on it yet, and was wondering where this sort of work sits in terms of priority for the Confluent folks working on this product. I'm interested in helping if I can, but I admit that I know next to nothing about KSQL's engine.

Thanks Andy!

**Comment by bellemare** [comment]
Bumping the question @big-andy-coates

**Comment by bhamur** [comment]
@PeterLindner collect_set has a limitation of just 1000 elements in the array. Did you implement non-key joins with any other work-around?

**Comment by PeterLindner** [comment]
@bhamur unfortunately not, for my use case I knew, that I'd have at most 3 records in the set

**Comment by nvaksmann1992** [comment]
@entechlog did you find a solution for the join with foreign-key ?

I have the same problem and I was wondering if you found a solution yet ? :)

**Comment by big-andy-coates** [comment]
> @big-andy-coates I was actually just about to email you about this, as I see you've done a lot of work on the joins to date. I contributed the PR (with some help from many fine people) for KIP-213 mentioned above, and I've been looking at how to get this into KSQL. I've been looking under the hood of KSQL and I admit that I don't have a firm handle on it yet, and was wondering where this sort of work sits in terms of priority for the Confluent folks working on this product. I'm interested in helping if I can, but I admit that I know next to nothing about KSQL's engine.
> 
> Thanks Andy!

Hi @bellemare, sorry for the delay in answering your question!

To be honest, I'm not 100% sure where this comes in terms of priority. I know its not part of the next quarter's roadmap. Beyond that, I'm not sure.  @MichaelDrogalis or @derekjn may be able to comment more.

It would be great to have you contribute, if you feel able!  First steps would be to write up the design proposal: https://github.com/confluentinc/ksql/blob/master/design-proposals/README.md.

Andy

**Comment by MichaelDrogalis** [comment]
A KIP/patch for this would be 😍

**Comment by bellemare** [comment]
Unfortunately, I don't have the time to devote to this in the next 3 months due to personal obligations. We also aren't using KSql where I work at the moment, so I can't reasonably get cycles there to address it.

**Comment by big-andy-coates** [comment]
Understandable. We appreciate your contribution to Streams, and we will leverage your work by exposing it in ksqlDB within the foreseeable future, just no firm date as yet.  What this space!

**Comment by bellemare** [comment]
I'll keep my eyes and ears open! That being said, if something changes, this would probably be one of the first things I would work on :)

**Comment by rtrive** [comment]
is there some updates for this feature?

**Comment by MichaelDrogalis** [comment]
Hey @rtrive, nothing yet. But patches welcome from anyone that wants to work on this. ❤️

**Comment by yuranos** [comment]
I really think this usecase is becoming more and more common and hope that Confluent folks will be able to prioritize it somewhere soon.
I am [struggling](https://github.com/confluentinc/ksql/issues/7169) with rekeying a table as it stands and if I don't find a way to resolve, we will have to look into different options to query Kafka, which is a shame.

**Comment by MichaelDrogalis** [comment]
@yuranos We're working on this right now. :)

**Comment by pragmaticivan** [comment]
Howdy! Is there a place we could track code progress for that issue?

**Comment by mjsax** [comment]
There is no PR yet... Stay tuned. Happy to link PRs to this ticket when available.

**Comment by mkoziel2000** [comment]
Glad the one-to-many is getting worked on.  this specific issue is keeping us from actually treating ksql as anything other than a toy to play around with.  Hoping this gets over the finish line soon...it could offset a whole lot of consumer code we currently are having to develop.

**Comment by mjsax** [comment]
First PR: https://github.com/confluentinc/ksql/pull/7452

**Comment by mjsax** [comment]
Second PR: #7491

**Comment by mjsax** [comment]
Third PR: #7511
Fourth PR: #7517

**Comment by mjsax** [comment]
Adding more tests: #7526

**Comment by mjsax** [comment]
Required refactoring: #7499

**Comment by bellemare** [comment]
@mjsax I am very pleased to see your work on this!

**Comment by mjsax** [comment]
It's about time to add it to kslqDB... But it's not just me, but a team effort together with @vcrfxia and @spena :)

**Comment by mjsax** [comment]
Adding more tests: #7528
Extend logical planner: #7522

**Comment by mjsax** [comment]
Logical to Physical plan translation (and trying to get the tests green): https://github.com/confluentinc/ksql/pull/7543

**Comment by mjsax** [comment]
More tests: #7537

**Comment by mjsax** [comment]
Some more bug fixes: https://github.com/confluentinc/ksql/pull/7576

**Comment by mjsax** [comment]
Bug fix: https://github.com/confluentinc/ksql/pull/7547
Test framework fix: https://github.com/confluentinc/ksql/pull/7579
Fixing long standing but expose by FK-join work: https://github.com/confluentinc/ksql/pull/7585

**Comment by mjsax** [comment]
Add missing test: https://github.com/confluentinc/ksql/pull/7588

**Comment by mjsax** [comment]
Another bug fix: https://github.com/confluentinc/ksql/pull/7592

**Comment by mjsax** [comment]
Updating docs: https://github.com/confluentinc/ksql/pull/7628

**Comment by shrugal** [comment]
Hey @mjsax thanks for posting these updates! Do I read it right that it's actually a N:1 join, so a row from the left table is joined with just one from the right, but one and the same row from the right table can be joined to multiple different rows from the left? For example with the tables users and orders  `FROM orders JOIN users ON orders.user_id = users.id` is possible, but `FROM users JOIN orders on user.id = orders.user_id` is not?

**Comment by mjsax** [comment]
That is correct. If you think in DW terms, the left table would be your "fact table" and you can do FK-lookups into the right "dimension table".

It would be possible of course, to enhance ksqlDB to also allow the second query (and I am sure we will do this at some point). It's similar to the missing "RIGHT JOIN" support -- we don't support `t1 RIGHT JOIN t2` but you can still do the join as `t2 LEFT JOIN t1`... We need to enhance ksqlDB to internal "flip" left/right input to support this. It's in our backlog :)
