### ISSUE TITLE
Rename Artifacts/Modules from "KSQL" to "ksqlDB"

### ISSUE THREAD

**Issue by agavra** [confluentinc/ksql#4426]
After the rebrand we've started publishing the docker images under the new name `ksqlDB` but this requires a pipeline that uses maven to rename the artifacts only during the docker build. This causes some inconsistencies (e.g. with publishing UDF jars). We should rename all of the modules and artifacts to reflect the rebrand.

Most of the work related to this issue is likely to be internal to Confluent's build pipeline.

**Comment by vcrfxia** [comment]
This was completed in https://github.com/confluentinc/ksql/pull/4428 -- closing this out 🎉
