### ISSUE TITLE
Left join doesn't work as advertised

### ISSUE THREAD

**Issue by burnayev-co** [confluentinc/ksql#443]
Trying to wrap my mind around KSQL joins with KSQL 0.1... Always getting null on the right side.

Here's an example:

1. Create a stream, a table, and a continuous query:

```
CREATE STREAM pageviews (userid varchar, pageid varchar) WITH (kafka_topic='pageviews', value_format='DELIMITED');
CREATE TABLE users (regionid varchar, userid varchar) WITH (kafka_topic='users', value_format='DELIMITED');
CREATE STREAM pageviews_with_users AS SELECT pageviews.userid AS userid, pageid, regionid FROM pageviews LEFT JOIN users ON pageviews.userid = users.userid;
```

2. Setup the observation:

```
SELECT * FROM pageviews;
SELECT * FROM users;
SELECT * FROM pageviews_with_users;
```

3. Post a few messages:
u_abc123,p_xyz890 - to pageviews
US,u_abc123 - to users
u_abc123,p_xyz890 - to pageviews

4. Watch the queries:

```
ksql> select * from pageviews;
1510088750070 | abc123 | u_abc123 | p_xyz890
1510088873623 | abc123 | u_abc123 | p_xyz890

ksql> select * from users;
1510088814659 | abc123 | US | u_abc123

ksql> select * from pageviews_with_users;
1510088750070 | u_abc123 | u_abc123 | p_xyz890 | null
_1510088873623 | u_abc123 | u_abc123 | p_xyz890 | **null**_
```

According to https://docs.confluent.io/current/streams/developer-guide.html#streams-developer-guide-dsl-joins I'd expect to see a non-null value in the highlighted row above.

Am I doing something wrong?

**Comment by bluemonk3y** [comment]
Hi @burnayev-co  - Can you confirm that your table data is published with a key? (how are you publishing it?)

**Comment by burnayev-co** [comment]
val producer = KafkaProducer<String, ByteArray>(getKafkaProperties())
    File("users.txt").forEachLine { line ->
        val serialized = line.toByteArray()
        val record = ProducerRecord<String, ByteArray>("users", "abc123", serialized)
        producer.send(record)
    }
    producer.close()

All the messages are published with the same key **abc123**

It's Kotlin if you wonder

**Comment by bluemonk3y** [comment]
hi @burnayev-co - I believe we have a fix. Either pick up the latest 4.0.x branch or wait for the new release tomorrow.

**Comment by apurvam** [comment]
This is fixed by #450 . Closing this ticket out. Please repoen if you can reproduce with the latest commits on 4.0.x

**Comment by chengang2** [comment]
@burnayev-co I have the same problem, how to solve。left join tableb but  the column of tableb  value is null

**Comment by burnayev-co** [comment]
@chengang2 In my testing everything worked as advertised with the 0.4 release
