### ISSUE TITLE
ksql-test-runner does not support non-string keys

### ISSUE THREAD

**Issue by holgerbrandl** [confluentinc/ksql#4434]
When using the ksql-test-runner with the example from the documentation from https://docs.confluent.io/current/ksql/docs/developer-guide/ksql-testing-tool.html an error is being thrown:

```
ksql-test-runner  -i demo_test.inputs.json -o demo_test.outputs.json -s demo_test.stmts.ksql
        >>>>> Test failed: Invalid key value for topic test_topic.
Expected KeyType: STRING
Actual KeyType: INTEGER, key: 0.
This is likely caused by the key type in the test-case not matching the schema.
````

A workaround is to quote the keys in the input and output. 

Either the docs should be adjusted or the ksql-test-runner should be fixed to support non-string keys.

Tested against recent master branch of KSQL (d521b16461a7558fbe2d43f1a98dbc6043002ac6)

**Comment by apurvam** [comment]
@big-andy-coates I think this should be a blocker for 0.7.0, since primitive keys seem to be broken with the test runner out of the box.

**Comment by big-andy-coates** [comment]
No surprise there, given https://github.com/confluentinc/ksql/issues/4067 hasn't been done yet.

**Comment by apurvam** [comment]
I am not sure we want to hold up the 0.7.0 release for this. WDYT @MichaelDrogalis ? 

IMO, we should add the limitation to the release notes and aim to release a 0.7.1 with this patch (and maybe others). @agavra @vpapavas to comment on our readiness for a 0.7.1 release.

**Comment by MichaelDrogalis** [comment]
That sounds okay to me. As long as we prioritize fixing this immediately after 0.7.0
