### ISSUE TITLE
Allow system columns in query projections without the need to alias. 

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#4458]
At the moment, in master, the following fails with an error:

```sql
SELECT ROWKEY, ROWTIME, WINDOWSTART, WINDOWEND FROM FOO;
```

Because those are reserved system column names.  The error makes sense for C*AS statements, where the data will be persisted into Kafka, as such fields would be invalid when read back in.  But for straight up push and pull queries these should be allowed: it's a bit weird requiring them to be aliased, and is a regression compared to previous releases.

**Comment by apurvam** [comment]
Is the linked PR sufficient to close this, or downgrade from a release blocker @big-andy-coates ?
