### ISSUE TITLE
Json primitive keys

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#4461]
KSQL currently only supports KAFKA  serialized keys i.e. those serialized using Kafka's own `StringSerializer`, `IntegerSerializer`, `DoubleSerializer` or `LongSerializer`.

We need to support other key formats!

**Comment by apurvam** [comment]
Moving this to the 0.13.0 milestone, since we know this isn't going to make 0.12.0

**Comment by big-andy-coates** [comment]
Removing from milestone as only things being worked on should be in a milestone.

**Comment by apurvam** [comment]
@big-andy-coates are we saying that we don't plan to have this in the 0.13.0 milestone? Or it is more a matter of bookkeeping, and it will be in the 0.13.0 milestone once work on it starts?

**Comment by big-andy-coates** [comment]
We'll hopefully have this in 0.13, but nothing should be marked as being in the milestone until being worked on.

**Comment by big-andy-coates** [comment]
Repurposing this task as an epic for JSON format support for keys.
