### ISSUE TITLE
Incorrect functionality claimed in stream-processing.md

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#4464]
In `stream-processing.md` it states:

> Given the following table:
> ```sql
> CREATE TABLE products (product_name VARCHAR, cost DOUBLE)
>     WITH (kafka_topic='products', partitions=2, value_format='json');
> ```
> You can create a stream that captures all writes made to the table:
> ```sql
> CREATE STREAM products_changelog AS
>     SELECT * FROM products EMIT CHANGES;
> ```

This is not the case.  The second statement would fail with an error talking about the fact the query is returning a table, not a stream.

The following would work, but would just create a copy of the table

```sql 
CREATE TABLE products_copy AS
    SELECT * FROM products EMIT CHANGES;
```

**Comment by JimGalasyn** [comment]
Fixed in https://github.com/confluentinc/ksql/pull/5352.
