### ISSUE TITLE
Limits on push queries

### ISSUE THREAD

**Issue by purplefox** [confluentinc/ksql#4475]
Parent issue https://github.com/confluentinc/ksql/issues/4266

Implement limits on total number of push queries at any one time, as each push query currently has it's own Kafka Streams topology which owns threads.

**Comment by blueedgenick** [comment]
Thinking out loud here: I wonder if it's better to put the limit on the
number of running stream threads? That feels like a better proxy for the
system load being created, given that most of the allocated buffers are
per-streamthread and it's possible for a user already to set the number of
steam threads each query will use. WDYT?
