### ISSUE TITLE
Docs incorrectly claim source names can be quoted.

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#4479]
In `syntax-reference.md` it claims:

> Also, you can use backtick characters for the names of sources, like streams
and tables. For example, you can create a stream name that has an embedded
hyphen:
> ```sql
> CREATE STREAM `foo-bar` (id VARCHAR) WITH (kafka_topic='foo', value_format='JSON', partitions=1);
> ```

I'm 99.9% sure source names can not be quoted. Only column names.

**Comment by blueedgenick** [comment]
Just did this successfully (in 5.4):
```
ksql> create stream `t1` as select * from aml_status;

 Message
---------------------------------------------------------------------------
 Stream T1 created and running. Created by query with query ID: CSAS_T1_12
---------------------------------------------------------------------------
```

**Comment by JimGalasyn** [comment]
@blueedgenick @big-andy-coates Should I go ahead and close this?
