### ISSUE TITLE
Todos in the docs

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#4534]
The following pages in the new markdown docs still have TODOs  in them!

* create-stream-as-select.md
* create-table-as-select.md
* describe-function.md
* drop-stream.md
* drop-table.md
* insert-into.md
* show-functions.md
* show-properties.md
* show-queries.md
* show-streams.md
* show-tables.md
* spool.md
* terminate.md

Our docs published docs should not have TODOs

**Comment by JimGalasyn** [comment]
We removed these somewhere along the way.
