### ISSUE TITLE
Numeric/Decimal Values Fail to Convert to KSQL Model.

### ISSUE THREAD

**Issue by SteadBytes** [confluentinc/ksql#4602]
**Describe the bug**

Creating a stream from topics containing numeric/decimal values produced by PostgreSQL + Kafka Connect (`io.confluent.connect.jdbc.JdbcSourceConnector`) fails with `Failed to convert schema to KSQL model: Invalid Decimal schema: precision parameter not found.`

**To Reproduce**

Please see https://github.com/SteadBytes/ksql-numeric-types-issue for minimal reproduction, demonstration and CLI commands/log output. The README contains step-by-step instructions :+1: 
- All containers are pinned to exact tags
- KSQL version 0.7.0 (from `confluentinc/ksqldb-server:0.7.0`)

Note: The same behaviour was reproduced using a local build of `ksql` from `master` branch at rev `041ce5bb5fb9a4bf2678df4d1a8b9cb31694a51e`.

**Expected behavior**
A KSQL stream is created without error. (see step 6 of reproduction README)

**Actual behaviour**
See step 6 of reproduction README
- `Failed to convert schema to KSQL model: Invalid Decimal schema: precision parameter not found.`

My team and I at Unipart Digital are willing to collaborate on and upstream fixes :smile:

**Comment by agavra** [comment]
Hello @SteadBytes - thanks for reporting this! I've run into this same issue before (I don't think I can find a public-facing ticket describing it), but this is caused because the JDBC connector doesn't output the "proper" connect schema definition. If you curl schema registry, you'll probably get something like:
```json
{
  "name":"amount",
  "type":{
    "type":"bytes",
    "scale":3,
    "precision":38,
    "connect.version":1,
    "connect.parameters":{
      "scale":"3",
    },
    "connect.name":"org.apache.kafka.connect.data.Decimal"
  }
}
```

The correct schema would include `"connect.decimal.precision":38` in the `connect.parameters` object.

A possible manual workaround (thanks to amazing @mikebin) would be to manually register a schema version wit the missing `connect.decimal.precision` attribute after the JDBC connector creates the original schema. ksqlDB would use the most recent schema, so unless the JDBC connector overrides the manually created one you should be able to work around it.

If you are interested in fixing the issue, I believe https://github.com/confluentinc/kafka-connect-jdbc accepts community contributions!

**Comment by SteadBytes** [comment]
Aha ok thank you, I see the incorrect `precision` field:
```json
{
  "type": "record",
  "name": "numeric_val",
  "fields": [
    {
      "name": "id",
      "type": "int"
    },
    {
      "name": "a_value",
      "type": {
        "type": "bytes",
        "scale": 20,
        "precision": 64,
        "connect.version": 1,
        "connect.parameters": {
          "scale": "20"
        },
        "connect.name": "org.apache.kafka.connect.data.Decimal",
        "logicalType": "decimal"
      }
    },
    {
      "name": "write_date",
      "type": {
        "type": "long",
        "connect.version": 1,
        "connect.name": "org.apache.kafka.connect.data.Timestamp",
        "logicalType": "timestamp-millis"
      }
    }
  ],
  "connect.name": "numeric_val"
}
```

Creating a new version as follows allows the stream to be successfully created:
```json
{
  "type": "record",
  "name": "numeric_val",
  "fields": [
    {
      "name": "id",
      "type": "int"
    },
    {
      "name": "a_value",
      "type": {
        "type": "bytes",
        "scale": 20,
        "precision": 64,
        "connect.version": 1,
        "connect.parameters": {
          "scale": "20",
          "connect.decimal.precision": "64"
        },
        "connect.name": "org.apache.kafka.connect.data.Decimal",
        "logicalType": "decimal"
      }
    },
    {
      "name": "write_date",
      "type": {
        "type": "long",
        "connect.version": 1,
        "connect.name": "org.apache.kafka.connect.data.Timestamp",
        "logicalType": "timestamp-millis"
      }
    }
  ],
  "connect.name": "numeric_val"
}
```

Thanks for the pointers, I'll open up an issue at https://github.com/confluentinc/kafka-connect-jdbc and hopefully get a fix in there!

**Comment by agavra** [comment]
Great - I'm glad the workaround helped. I'll close out this ticket in favor of the one in the other repo to keep our backlog clean - but feel free to reopen if there's a related issue!

**Comment by SteadBytes** [comment]
Sorry to re-open but I'm confused as to where the issue actually lies here. I can see that KSQL is expecting the precision parameter https://github.com/confluentinc/ksql/blob/d15026fe7c8993673152d740d46b16253896d8e8/ksql-common/src/main/java/io/confluent/ksql/util/DecimalUtil.java#L33 . However I can find no reference to that parameter being required by the core connect Decimal type https://github.com/apache/kafka/blob/3cdc78e6bb1f83973a14ce1550fe3874f7348b05/connect/api/src/main/java/org/apache/kafka/connect/data/Decimal.java#L41 . kafka-connect-jdbc is producing valid schema according to that class as far as I can tell. Is this a special case required by KSQL?

**Comment by agavra** [comment]
I took a deeper look into why this is being expected and it looks like its the schema registry AvroData that requires it (and we rely on it to understand Avro schemas):

https://github.com/confluentinc/schema-registry/blob/c19da74f7c4326438dd96d022a7e3d38dd3c68af/avro-data/src/main/java/io/confluent/connect/avro/AvroData.java#L251

**Comment by SteadBytes** [comment]
Yes, it also seems that other connectors e.g. [Debuzium](https://github.com/debezium/debezium/blob/ef0d018c79e5aa25077eadf4ebe35f2dc4bb37cc/debezium-core/src/main/java/io/debezium/data/SpecialValueDecimal.java#L36) provide this parameter. I'm still unclear on the reasoning for it in the first place over the avro `precision` parameter but thank you for the pointers - I'll address the issue on the `kakfa-connect-jdbc` for now :+1:
