### ISSUE TITLE
Make ksqlDB available as an rpm package

### ISSUE THREAD

**Issue by MichaelDrogalis** [confluentinc/ksql#4615]
**Is your feature request related to a problem? Please describe.**

Right now, ksqlDB's standalone releases are only available through Docker. It would be great to get them as rpm's as well.

**Comment by OneCricketeer** [comment]
The docs seem to suggest [`yum install confluent-ksqldb`](https://docs.confluent.io/platform/current/installation/available_packages.html#confluent-ksqldb) should work

**Comment by MichaelDrogalis** [comment]
@OneCricketeer It should be the case that if you add the right repo, you'd get [the Confluent Platform distribution of ksqlDB](https://ksqldb.io/distributions.html) through RHEL. Can you confirm that you have the right one configured?

**Comment by OneCricketeer** [comment]
Ah, I see, it's not the latest version that you'd get with the standalone Docker image

**Comment by MichaelDrogalis** [comment]
Yeah, that's correct. This is the Confluent Platform distribution.

**Comment by nward** [comment]
I'm very keen to see this as well - we're looking for features in more modern versions than what confluent platform ships with, and the environment is not a docker shop right now. Happy to help if I can do so - plenty of RPM experience here, but almost zero modern Java experience..

**Comment by agavra** [comment]
@derekjn - this is complete as of 0.17, right?

**Comment by OneCricketeer** [comment]
If it is, then the docs are missing - https://docs.ksqldb.io/en/latest/operate-and-deploy/installation/

**Comment by derekjn** [comment]
> @derekjn - this is complete as of 0.17, right?
We haven't posted links and instructions for the packages yet, so let's leave this issue open until that work is done and they're fully available to our users. cc @colinhicks

**Comment by MichaelDrogalis** [comment]
We're very pleased to close this issue:

- [RPM quickstart](https://ksqldb.io/quickstart-standalone-rpm.html#quickstart-content)
- [tar quickstart](https://ksqldb.io/quickstart-standalone-tarball.html#quickstart-content)
