### ISSUE TITLE
Add syntax to show available connector plugins

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#4623]
ksqlDB should offer an interface to the Connect `connector-plugins` API, something like `SHOW CONNECTOR PLUGINS` so that the user can see which ones are installed. 

Example use of API: 

    curl -s localhost:8083/connector-plugins|jq '.[].class'

**Comment by rmoff** [comment]
Came up against this again today. The alternative is either exposing 8083 external to the ksqlDB container and relying on the user having `curl` and `jq` on their host machine, or installing on them the ksqlDB container - neither of which are great. 

Could we get this one on this list maybe @MichaelDrogalis @derekjn, please? :)

**Comment by MichaelDrogalis** [comment]
Im not sure how hard this would be—it seems simple. Marked as needs-triage to see whether this could be a fix-it-week thing.

**Comment by spena** [comment]
The PR is merged and `show connector plugins` will be available in the next 0.18 release.

**Comment by rmoff** [comment]
sweeeet!

**Comment by RobertMcCarter** [comment]
Fantastic!  Thanks team!
