### ISSUE TITLE
Rename `VALUE_AVRO_SCHEMA_FULL_NAME` to `VALUE_SCHEMA_FULL_NAME`

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#4656]
Similar to https://github.com/confluentinc/ksql/issues/4556, this schema name should not be specific to AVRO, but also supported by PB.

At the moment generated PB schemas are pretty horrid with message names like `ConnectDefault0` and `ConnectDefault1` etc.

We ran into the same issue with Avro, which prompted the introduction of `VALUE_AVRO_SCHEMA_FULL_NAME`.  Now we should make this more generic.

**Comment by big-andy-coates** [comment]
Also see https://github.com/confluentinc/ksql/issues/4657

**Comment by mjsax** [comment]
Reassigning this ticket @lihaosky -- we need this for the schema-id work.
