### ISSUE TITLE
Need a better error when accidentally using double quotes in INSERT INTO

### ISSUE THREAD

**Issue by cjmatta** [confluentinc/ksql#4663]
**Is your feature request related to a problem? Please describe.**
Trying to insert records into a stream:
`create stream testregexp (id bigint, desc varchar) with (kafka_topic='testregexp', value_format='avro');`

```
ksql> insert into testregexp (ROWKEY, ID, DESC) values ("1", 1, "Cut Cat Cot");
Failed to prepare statement: null
```

**Describe the solution you'd like**
Either accept the above input, or provide a helpful error like "Please use single quotes for strings when using INSERT INTO"

**Comment by agavra** [comment]
@cjmatta what version are you using? I can no longer reproduce this on the latest ksqlDB (0.8.1):
```
ksql> INSERT INTO TEST (rowkey, val) values (1, "foo");
Failed to insert values into 'TEST'. Code generation failed for insert value: Cannot find the select field in the available fields. field: `foo`, schema: [`VAL` STRING]. expression:foo, schema:`ROWKEY` INTEGER KEY, `VAL` STRING
```
I believe this may have already been fixed by #4926. Feel free to reopen this ticket if it was not fixed.
