### ISSUE TITLE
Breaking change to APIs that use KsqlRequest

### ISSUE THREAD

**Issue by rodesai** [confluentinc/ksql#4674]
We recently merged a breaking change to APIs that use KsqlRequest (https://github.com/confluentinc/ksql/pull/4597). The patch renames the `streamsProperties` to `configOverrides`.

We should either revert the change, or fix all our stuff that depends on the property:
   - CLI
   - Documentation (including API docs)
   - UI
   - Demos

IMO we should do the latter, since the new name makes more sense and we're at a stage where its OK to make breaking changes.

**Comment by apurvam** [comment]
fixed by #4597 (which reverted the breaking change)
