### ISSUE TITLE
new api returns 200 for invalid pull query

### ISSUE THREAD

**Issue by jrea** [confluentinc/ksql#4698]
**Describe the bug**
the new http2 API does return invalid status codes/errors for pull queries

**To Reproduce**
Steps to reproduce the behavior, include:

`create table cars (id VARCHAR, lat DOUBLE, long DOUBLE) with (KAFKA_TOPIC='cars', VALUE_FORMAT='JSON', key='id', partitions=1, replicas=1);`

`select LAT, LONG, from CARS where ROWKEY='Car1';`

**Expected behavior**
This is not a materalized view, so I would expect an error from http

**Actual behaviour**
REST endpoint gives `200 OK`
CLI output complains about materialized view, as expected

update: 
Looking at this a bit more, I don't think any response comes back at all. Even when I have a correct query (works in the CLI), the endpoint still give back data: []

**Comment by apurvam** [comment]
cc @vcrfxia @purplefox

**Comment by jrea** [comment]
Looking at this a bit more, I don't think any response comes back at all. Even when I have a correct query (works in the CLI), the endpoint still give back `data: []`

**Comment by jrea** [comment]
I got this sorted. gotta use the new protocol :D
