### ISSUE TITLE
Extend the DESCRIBE statement to more useful information

### ISSUE THREAD

**Issue by sriramsub** [confluentinc/ksql#470]
DESCRIBE (extended) statement to report on originating SQL and other useful information (created-timestamp, sql create statement, stream topology, basic metrics <number of events, last event timestamp, number of errors/exceptions>, underlying kafka-topic) (future: permissions, group, creator etc) (should this be part of show query instead?)

**Comment by hjafarpour** [comment]
Yes, we can have `DESCRIBE  queryId` to show the above information for the stream job associated with the query.
We should also extend the current `DESCRIBE`  for streams/tables to include more information.

**Comment by bluemonk3y** [comment]
done
