### ISSUE TITLE
ksqlDB 0.7.1 - Can't find any functions with the name 'AS_ARRAY'

### ISSUE THREAD

**Issue by Deninc** [confluentinc/ksql#4738]
Error from a very simple query:
```
ksql> SELECT as_array(before->status, after->status) "status" FROM STREAM_INVOICES emit changes;
Can't find any functions with the name 'AS_ARRAY'
```

This worked in ksql 5.4.0. But not in ksqlDB 0.7.1.

**Comment by agavra** [comment]
Hello @Deninc - `AS_ARRAY` was replaced with the SQL standard `ARRAY[]` syntax. Let me know if that works for you (`ARRAY[before->status, after->status]`).

**Comment by Deninc** [comment]
Thank @agavra, it worked. 
The document here is not updated:
https://docs.ksqldb.io/en/latest/developer-guide/ksqldb-reference/scalar-functions/#asarray

**Comment by agavra** [comment]
Thanks for pointing that out @Deninc - I'll make sure to update that now.
