### ISSUE TITLE
KSQL should not filter out stream rows with null key

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#4747]
It makes sense that tables ignore any records in their changelog logs (or sources) would null keys. A table requires a primary key, and hence a `null` is invalid.

However, streams have no such restriction. Yet, ksql will filter out rows where the key is null, e.g. the following fails:

```json
{
      "name": "partition by with null value",
      "statements": [
        "CREATE STREAM TEST (ROWKEY BIGINT KEY, ID bigint) with (kafka_topic='test_topic', value_format = 'json');",
        "CREATE STREAM REPARTITIONED AS select * from TEST partition by ID;"
      ],
      "inputs": [
        {"topic": "test_topic", "key": 0, "value": null},
        {"topic": "test_topic", "key": 0, "value": {}},
        {"topic": "test_topic", "key": 0, "value": {"ID": 10}}
      ],

      "outputs": [
        {"topic": "REPARTITIONED", "key":  null, "value": {}},
        {"topic": "REPARTITIONED", "key":  null, "value": {}}
        {"topic": "REPARTITIONED", "key": 10, "value": {"ID": 10}}
      ]
    },
    
```

To get it to pass one must remove the output rows with null keys:

```json
{
      "name": "partition by with null value",
      "statements": [
        "CREATE STREAM TEST (ROWKEY BIGINT KEY, ID bigint) with (kafka_topic='test_topic', value_format = 'json');",
        "CREATE STREAM REPARTITIONED AS select * from TEST partition by ID;"
      ],
      "inputs": [
        {"topic": "test_topic", "key": 0, "value": null},
        {"topic": "test_topic", "key": 0, "value": {}},
        {"topic": "test_topic", "key": 0, "value": {"ID": 10}}
      ],

      "outputs": [
        {"topic": "REPARTITIONED", "key": 10, "value": {"ID": 10}}
      ]
    },
    
```

**Comment by blueedgenick** [comment]
Yikes! This seems like a pretty serious bug - can you tell if this had
always been the case  or it was a regression somewhere along the line?

**Comment by mjsax** [comment]
That is an interesting case. Note that a query like this would be "non-deterministic" with regard the output topic partitioning, because for the `null`-key record a random partition would be selected.

Hence, I am wondering if this might be an issue or not?

**Comment by big-andy-coates** [comment]
> Yikes! This seems like a pretty serious bug - can you tell if this had always been the case or it was a regression somewhere along the line?

I think this has always been the case.

**Comment by big-andy-coates** [comment]
> That is an interesting case. Note that a query like this would be "non-deterministic" with regard the output topic partitioning, because for the `null`-key record a random partition would be selected.
> 
> Hence, I am wondering if this might be an issue or not?

The non-determinism may well be an issue.  If it is, then I'm guessing we'll need to introduce a SQL `NULL` object of some kind, which will serialize to something other than null bytes.  This would ensure consistent partitioning.

However, I feel the introduction of a `NULL` object is potentially best left to a different ticket.  Initially, we can just ensure we're not filtering out these rows.
