### ISSUE TITLE
Unable to SELECT data using query() command with KSQLAPI in Python

### ISSUE THREAD

**Issue by yongki7297** [confluentinc/ksql#4756]
This is the query I used to read the data in Python. I'm able to select data in CLI but there was error in Python. The queries other than `SELECT` or `PRINT` were working fine.
`query = client.query("SELECT * FROM table1")`
`for item in query:  print(item)`
 However, there is no data returned and I get a time out error at the end.
`ConnectionError: HTTPConnectionPool(host='10.0.150.12', port=8088): Read timed out.`

In this case, I had changed the ksql properties as follows, and increase the time out to become 10 minutes in api.py, but the same issue was still happening.
`'ksql.streams.auto.offset.reset': 'earliest'`
`self.timeout = kwargs.get("timeout", 600)`

Does anyone facing the same issue, or is there any method to solve this?

**Comment by surajranatechahead** [comment]
Yes, I am facing the same.
