### ISSUE TITLE
Doesn't start with Kafka 0.9.0

### ISSUE THREAD

**Issue by vbash** [confluentinc/ksql#476]
When starting with Kafka 0.9.0 version fails with the following exception.
io.confluent.ksql.exception.KafkaResponseGetFailedException: Failed to retrieve kafka topic names

I can reproduce it on MacOs, Windows(CigWin) and Linux. The problem occurs when run with Kafka version 0.9.0
Works fine with Kafka version 0.11.0

Quick research shown that KafkaFuture returned by method names() (org.apache.kafka.clients.admin.ListTopicsResult : 36) is getting timed out.

Reproduced on confluent/kafka in docker and on CDH Kafka (Cloudera) both 0.9.0 versions.

**Comment by vbash** [comment]
Built from 0.1.x branch

**Comment by hjafarpour** [comment]
KSQL  uses kafka streams and requires Kafka 0.10.x and above.

**Comment by vbash** [comment]
Thank you for the confirmation.
That would be nice to write about the supported Kafka versions in README file.
That would save people a lot of time.

**Comment by ijuma** [comment]
That's reasonable. It's 0.10.1 and above to be more specific.

**Comment by hjafarpour** [comment]
@vbash good point. We will add compatibility information to the docs.
