### ISSUE TITLE
Add Kafka/COS version compatibility to the docs.

### ISSUE THREAD

**Issue by hjafarpour** [confluentinc/ksql#478]
Some users and contributors raised the issue of not having a compatibility information for KSQL and Kafka/COS versions. We need to add this to the docs to help users to detect if their env is good for running KSQL.

**Comment by miguno** [comment]
Example issue: https://github.com/confluentinc/ksql/issues/476

**Comment by miguno** [comment]
In our docs now: https://docs.confluent.io/current/ksql/docs/installation/installing.html#supported-versions-and-interoperability
