### ISSUE TITLE
Topic retention policies mean that query ids will diverge on different ksql engines over time

### ISSUE THREAD

**Issue by apurvam** [confluentinc/ksql#479]
At a logical level, the scheme to use a kafka topic keep the different ksql engine instances in perfect sync makes sense. This perfect syncing assumption is what enables a decoupling the assignment of query ids in each engine: since each engine's view is identical, the generated query ids will be identical. And then using these query ids to set the streams application id means that we get automatic scaling for free.

But Kafka's topic retention policies mean that the view of each ksql engine will diverge over time. So it is impossible to guarantee that engines will stay in perfect sync over time. 

Today, with the default 7 day retention, spinning up a new ksql engine on the 8th day will mean that it will start generating different query ids. This means that for a given query there will be multiple streams applications processing the same sources and sinks. This will result in duplicate output at best and data corruption at worst.

**Comment by hjafarpour** [comment]
@apurvam The current command topic is not a compacted topic and as you mentioned application of retention policy for the topic will remove older commands which results in possible inconsistent state.
We can have two solutions with relatively low LOE:

1. Set the retention policy for the command topic to infinity when we create the command topic. This will make sure that we won't loos any command.

2. Make the command topic a compacted topic and set unique keys for the command messages that are sent to the command topic. The key can be combination of server uuid/ip/port and timestamp. As long as this key is unique we won't loose any message.

Any of the above options will guarantee correctness.

**Comment by apurvam** [comment]
It seems to me that your solution 2 above is the same as setting retention to infinite unless the topic is setup for compact+delete, in which case we will run into the same issue.

Infinite retention seems like more of a workaround for the short term. In the longer term, we need to be able to clean up the garbage. Otherwise it would be prohibitively expensive to bring up new ksql engines: they would have to create and then drop all the streams since the beginning of time until they catch up to the current state. 

A proper solution probably means that we need a more sophisticated state propagation protocol in ksql.

**Comment by hjafarpour** [comment]
Yes, we indeed tried this earlier in summer but did not finish it because of other priorities in the launch. Currently when a KSQL server starts reads the command topic from the beginning and fetches all of the existing commands and executes them sequentially. 
We should be able to process the list of previous command deterministically and only execute the statements that are valid and not execute invalid statements such as the queries that have been terminated or stream/tables that have been dropped. This process should be deterministic and should not result in incorrect query id assignment too.

**Comment by dguy** [comment]
This needs much more thought and i think it comes back to the architecture of the system. Setting the command topic retention to infinite is really a non-starter in my opinion. Also having the query ids allocated as incrementing longs isn't going to work for reasons above, i.e., when the log is cleaned and commands are dropped, new and restarting engines will be out of sync. So we can't have the queryId specified as we do now. Something i'm looking at in https://github.com/confluentinc/ksql/pull/456, but haven't merged yet, is to derive the query id from the statement. So it would become a string, for example, "CTAS_MY-TABLE" or "CSAS_MY-STREAM" etc. this can always be reconstructed and doesn't matter about having a counter that has to have processed every command to be correct across all engines.
Also, i think there are probably 2 separate topics needed. First is the command topic, lets just treat this as an event stream. Then we could have another compacted topic that is basically the backing topic for the metastore, i.e, it is the snapshot of the current state of the metastore. So it would have all create table, etc statements in it. This way when engines start the previous command stuff moves to restoring the metastore and creating the tables/streams etc. And then we accept events from the command topic. Mind you i haven't completely thought this through, but it is worth having the discussion around what the architecture should look like and how we can get there from where we currently are.

**Comment by bluemonk3y** [comment]
It all folds under the consolidation of the command-topic work @dguy is working on. If that is fixed properly then using natural keys derived from the underlying statement provides universally consistent entity ids regardless of source etc (i.e. built from the AST etc).

**Comment by apurvam** [comment]
@dguy where are we on this ? Is there more work to do? If so, I think we should do it before GA.

**Comment by dguy** [comment]
@apurvam this is still an issue due to the way the command topic works. We either need to set the retention of the command topic much higher or rethink how we keep the state of the metastore, i.e., maybe by tracking it in a compacted topic

**Comment by dguy** [comment]
closing this ticket and created #742
