### ISSUE TITLE
ksqldb docker image prints all logs to console when running test-runner

### ISSUE THREAD

**Issue by rodesai** [confluentinc/ksql#4810]
**Describe the bug**
In ksqldb 0.7.1, running the ksqldb test runner would just print out the test output:

```
$ docker exec ksqldb-cli ksql-test-runner -i /opt/app/test/input.json -s opt/app/src/statements.sql -o /opt/app/test/output.json
	 >>> Test passed!
```

And for a failure:
```
Rohan-Desai-MBP16:transform-stream rohan$ docker exec ksqldb-cli ksql-test-runner -i /opt/app/test/input.json -s opt/app/src/statements.sql -o /opt/app/test/output.json
	>>>>> Test failed: Topic 'FLATTENED_ORDERS', message 0: Expected <1, {"ORDER_ID":"12","ORDER_TS":"2020-01-18 01:12:05","ORDER_AMOUNT":84.02,"CUST_FIRST_NAME":"Ricardo","CUST_LAST_NAME":"Ferreira","CUST_PHONE_NUMBER":"1234567899","CUST_ADDR_STREET":"Street SDF","CUST_ADDR_NUMBER":"8602","CUST_ADDR_ZIPCODE":"27640","CUST_ADDR_CITY":"Raleigh","CUST_ADDR_STATE":"NC","PROD_SKU":"P12345","PROD_NAME":"Highly Durable Glue","PROD_VENDOR_NAME":"Acme Corp","PROD_VENDOR_COUNTRY":"US"}> with timestamp=1579309925000 but was <1, {ORDER_ID=1, ORDER_TS=2020-01-18 01:12:05, ORDER_AMOUNT=84.02, CUST_FIRST_NAME=Ricardo, CUST_LAST_NAME=Ferreira, CUST_PHONE_NUMBER=1234567899, CUST_ADDR_STREET=Street SDF, CUST_ADDR_NUMBER=8602, CUST_ADDR_ZIPCODE=27640, CUST_ADDR_CITY=Raleigh, CUST_ADDR_STATE=NC, PROD_SKU=P12345, PROD_NAME=Highly Durable Glue, PROD_VENDOR_NAME=Acme Corp, PROD_VENDOR_COUNTRY=US}> with timestamp=1579309925000
```

The 0.8.0 image prints all the logs to the console, and the test result is hard to see:
[results.txt](https://github.com/confluentinc/ksql/files/4346498/results.txt)

**To Reproduce**
Set up a ksql test and run:

```
docker exec ksqldb-cli ksql-test-runner -i /opt/app/test/input.json -s opt/app/src/statements.sql -o /opt/app/test/output.json
```

**Expected behavior**
At least on success, we should just print out the test result.

**Actual behaviour**
Lots of noisy logs obscuring the test result

**Comment by colinhicks** [comment]
In Docker, the config directory winds up defaulting to `/usr`. This means an invalid path to `log4j-silent.properties` is used: https://github.com/confluentinc/ksql/blob/5a332a0a87f77a73aa29f3cd9efdd84a64857ced/bin/ksql-test-runner#L9-L10

For 0.8.0 a workaround is to configure the container with `KSQL_CONFIG_DIR=/etc/ksqldb`.

This affects 0.7.x as well, which can use `KSQL_CONFIG_DIR=/etc/ksql`.

**Comment by vcrfxia** [comment]
@rodesai were you following a Kafka Tutorials example when you encountered this bug? If so I think it's because Kafka Tutorials docker-compose files have
```
  ksqldb-cli:
    image: confluentinc/ksqldb-cli:0.7.1
    container_name: ksqldb-cli
    depends_on:
      - broker
      - ksqldb-server
    entrypoint: /bin/sh
    environment:
      KSQL_CONFIG_DIR: "/etc/ksql"
    tty: true
    volumes:
      - ./src:/opt/app/src
      - ./test:/opt/app/test
```
and the line `KSQL_CONFIG_DIR: "/etc/ksql"` needs to be updated to `KSQL_CONFIG_DIR: "/etc/ksqldb"` when the image version is upgraded from 0.7.1 to 0.8.0 (or later). If you do this, the ksql-test-runner does not print logs as expected. Without this update, the `log4j-silent.properties` file fails to be found as @colinhicks identified as the cause.

**Comment by vcrfxia** [comment]
@colinhicks is there a code change you'd like to see from this issue? I can't tell from your comment above if you're saying you think the default log4j config directory for the ksql-test-runner should be changed, or if it's fine as is (and users should supply the override as needed).

**Comment by colinhicks** [comment]
Thanks for taking a look, @vcrfxia. I think it's fine to explicitly supply `KSQL_CONFIG_DIR`, so long as it has always been necessary to provide it.

For example, if CP 5.4 images use log4j-silent _without_ any explicit configuration, but recent community images do require the config dir to be explicitly set, then it seems there's a UX regression to address.

**Comment by vcrfxia** [comment]
> For example, if CP 5.4 images use log4j-silent without any explicit configuration, but recent community images do require the config dir to be explicitly set, then it seems there's a UX regression to address.

Got'cha. I've just confirmed that the CP 5.4 images are structured the same way as the ksqlDB images: executables including `ksql-test-runner` are in `/usr/bin` while config files are in `/etc/ksql` (or `/etc/ksqldb` for newer images). The `ksql-test-runner` script has not changed either which means it's the same UX for both CP images and ksqlDB images.
