### ISSUE TITLE
ksql with AVRO format

### ISSUE THREAD

**Issue by dreamcatchernick** [confluentinc/ksql#4811]
hi all
i have a topic with avro data format . i would like to filter some of the column in that topic.  What i did is registering a stream and output a new topic. 
script below 
````
CREATE STREAM sample_stream(ACCOUNT_NO VARCHAR, SYSTEM_CODE VARCHAR, BIZ_LOG_ID VARCHAR) with (KAFKA_TOPIC=‘sample’, VALUE_FORMAT='Avro', KEY='ACCOUNT_NO');

CREATE STREAM myoutput AS SELECT  ACCOUNT_NO , SYSTEM_CODE FROM sample_stream
````
The new topic myoutput is also avro format. However when i looked at  the schema registry i can only find myoutput-value. i  expect it would have both myoutput-key and myoutput-value

i saw the doc mentioned "Avro message values are supported. Avro keys are not yet supported. "

i am using confluent 5.4 right now

thanks

**Comment by rmoff** [comment]
You answered your own question :) 
 Avro keys are not supported yet, so you only see a schema for the value part of the message.
