### ISSUE TITLE
PRINT output for messages with NULL keys unhelpfully verbose

### ISSUE THREAD

**Issue by blueedgenick** [confluentinc/ksql#4852]
**Is your feature request related to a problem? Please describe.**
As pointed out by @rmoff , the output of `print` on a topic whose messages have null keys - which is pretty common for a stream of JSONs for example, is overly verbose and obscures the actual message detail on the screen.

![image](https://user-images.githubusercontent.com/4551840/77197813-0b4c8880-6aa3-11ea-8eb2-505988c2a9c5.png)

**Describe the solution you'd like**
Suppress this message for null keys. Maybe shorten the list of possible formats to 'Unknown' or similar if the list is too long - more than 2 or 3 possibilities.

**Comment by big-andy-coates** [comment]
Humm... yes, null keys, or values, will result in a somewhat verbose output.

We can probably have it return `UNKNOWN`, or `¯\_(ツ)_/¯` if its not seen any data.

However, I'm a bit loathed to just change this to return `UNKNOWN` if there a more than 2 or 3 possibilities.   Sometimes just knowning what format it's definitely NOT can be useful.

**Comment by rmoff** [comment]
If it's `null`, can't we just write `<null>` or `n/a` or something like that? 

I'm not too opinionated _what_ we put, so long as it's not five lines of text which is just messy and confusing :)

**Comment by big-andy-coates** [comment]
@rmoff with linked PR output is now:

```
ksql> print Topic_with_null_keys from beginning;
Key format: ¯\_(ツ)_/¯ - no data processed
Value format: JSON or KAFKA_STRING
rowtime: 23/03/20 12:45:33 GMT, key: <null>, value: {"NAME": "bob"}
```
