### ISSUE TITLE
Add LEAST and GREATEST functions

### ISSUE THREAD

**Issue by PeterLindner** [confluentinc/ksql#4861]
**Is your feature request related to a problem? Please describe.**
Finding the least and/or greatest of more than two values becomes quite cumbersome quickly when using `CASE`.
For example: Our machines are equipped with at least 10 temperature sensors, sometimes more than 20. Each sensor has it's own (nullable) column and I want to find the minimum and maximum temperature for each row. Performing such an operation with `CASE` (+ NULL checking) is quite infeasible.

**Describe the solution you'd like**
add the stateless functions `LEAST(col1, col2, ..., colN)` and `GREATEST(col1, col2, ..., colN)` which find the least and greatest value of the given ones, respectively.
maybe also consider adding `LEAST(array)` and `GREATEST(array)`

**Describe alternatives you've considered**
1. using `CASE` which is a pain
2. use an intermediate stream with one sensor per row and aggregate using `MIN()` and `MAX()`. But this would involve more than 20 `INSERT INTO`s, the aggregation table would grow unbounded and I'd have to join back with the original stream.

**Additional context**
- mysql docs:
  - [LEAST()](https://dev.mysql.com/doc/refman/8.0/en/comparison-operators.html#function_least)
  - [GREATEST()](https://dev.mysql.com/doc/refman/8.0/en/comparison-operators.html#function_greatest)
- [postgres docs](https://www.postgresql.org/docs/current/functions-conditional.html#FUNCTIONS-GREATEST-LEAST)

**Comment by sd1998** [comment]
@PeterLindner Can this issue be assigned to me?

**Comment by PeterLindner** [comment]
@sd1998 I'm just a random guy having some ideas, so I can't decide on that and unfortunately I also don't know who can, but it seems like @big-andy-coates manages a lot of issues (sorry for pinging you Andy if you are the wrong guy)

**Comment by agavra** [comment]
@sd1998 we'd be happy to have your contribution! assigning this to you, and feel free to reach out if you need any help

**Comment by sd1998** [comment]
@agavra Thanks. I am new to the codebase. What could be a good starting point?

**Comment by agavra** [comment]
@sd1998 - you can take a look at recent PRs introducing UDFs such as https://github.com/confluentinc/ksql/pull/5534 and follow their examples. Note that there are a ton of generated JSON files, to generate those - simply run `PlannedTestGeneratorTest` (which is ignored by default). This will generate the specs for the JSON integration tests (such as this file: https://github.com/confluentinc/ksql/pull/5534/files#diff-fbe011e0738164208d4392cec3e70ec6)

Let me know if that is helpful!

**Comment by sd1998** [comment]
@agavra This is really helpful. Thanks. Will get started right away.

**Comment by vcrfxia** [comment]
Hi @sd1998 , any update of this? I'm happy to take this off your hands if you don't think you'll get time to work on it anytime soon. Thanks.

**Comment by vcrfxia** [comment]
Hey @sd1998 I'm going to reassign this ticket for now but let me know if you're still interested in contributing and I can help suggest other tickets for you. Thanks.

**Comment by Sullivan-Patrick** [comment]
@vcrfxia Attempting a quick comment to see if that allows you to add me to the ticket.
