### ISSUE TITLE
Issue with creating a KTABLE with a composite key

### ISSUE THREAD

**Issue by sivaknakka** [confluentinc/ksql#4863]
Trying to create a KTABLE with composite key, but it is not taking multiple columns part of the KEY syntax. Do not want to go with GROUP BY approach, that way I have to provide aggregation function and I have many columns, can not apply group by on all those columns.
Getting this error.
ksql> CREATE TABLE DHCP_TBL WITH (KAFKA_TOPIC='dhcp_topic', KEY='IP,PORT',VALUE_FORMAT='AVRO');
No column with the provided key column name in the WITH clause, IP,PORT, exists in the defined schema.
ksql>

**Comment by big-andy-coates** [comment]
Hey @sivaknakka - support for multiple key columns is coming...

https://github.com/confluentinc/ksql/issues/824
