### ISSUE TITLE
Cannot use CLI to connect to HTTPS server

### ISSUE THREAD

**Issue by vcrfxia** [confluentinc/ksql#4885]
**Describe the bug**

In ksqlDB 0.8.0 and later (including `master`, not including CP 5.5) it's not possible to use the ksqlDB CLI to connect to a ksqlDB server with HTTPS enabled, as a result of the refactor in https://github.com/confluentinc/ksql/pull/4609.

Trying to connect to an HTTPS server address results in the message `Cannot make request with scheme https as client is configured without tls` since the new CLI expects the user to set a new property, `ksql.client.enable.tls`: https://github.com/confluentinc/ksql/blob/258d0b06d81954af2c4e2c17fd7f26c74f315368/ksqldb-rest-client/src/main/java/io/confluent/ksql/rest/client/KsqlClient.java#L137-L139

However, attempting to set this property on the CLI doesn't work either since the custom property (i.e., not part of KsqlConfig) is rejected by property validation:
```
invalid property found: Not recognizable as ksql, streams, consumer, or producer property: 'ksql.client.enable.tls'
Caused by: Not recognizable as ksql, streams, consumer, or producer property:
	'ksql.client.enable.tls'
```

Thus, it's not possible to connect to an HTTPS server with a ksqlDB CLI version that contains this bug. However, an earlier version of the ksqlDB CLI can still be used to successfully connect.

I've verified that forcing the property to be set (by modifying the if-statement in https://github.com/confluentinc/ksql/blob/258d0b06d81954af2c4e2c17fd7f26c74f315368/ksqldb-rest-client/src/main/java/io/confluent/ksql/rest/client/KsqlClient.java#L137-L139) resolves the connection issue, so this is the definitely the source of the problem.

**To Reproduce**

1. Build ksqlDB CLI from `0.8.x-ksqldb` or `master`.
1. Start ksqlDB server with HTTPS listener.
1. Attempt to connect ksqlDB CLI to the ksqlDB server, e.g., `./bin/ksql https://localhost:8088`
1. You'll see the error `Cannot make request with scheme https as client is configured without tls`.
1. Try to work around this by creating a config file with `ksql.client.enable.tls=true` and passing it to the CLI: `./bin/ksql https://localhost:8088 --config-file /path/to/config/file`
1. You'll see the error
    ```
    invalid property found: Not recognizable as ksql, streams, consumer, or producer property: 
    'ksql.client.enable.tls'
    Caused by: Not recognizable as ksql, streams, consumer, or producer property:
    	'ksql.client.enable.tls'
    ```

**Expected behavior**

ksqlDB CLI should be able to connect to HTTPS server.

**Actual behaviour**

See above for error messages.

**Additional context**

As noted above, versions of the ksqlDB CLI before the refactor can still be used to successfully connect to HTTPS-enabled servers (even of later versions), so there is a workaround.

**Comment by vcrfxia** [comment]
In terms of how to fix this, we could update the property validation to allow users to pass the `ksql.client.enable.tls` config to the ksqlDB CLI, but I don't think users should be required to pass this config at all. Rather, the ksqlDB CLI should infer from the fact that the server address starts with `https` that the client should have TLS enabled. What do you think @purplefox ?

**Comment by purplefox** [comment]
I haven't been able to build and run ksql from master today :( However I have a feeling this is configurable via a system property, see https://github.com/confluentinc/ksql/blob/master/ksqldb-cli/src/main/java/io/confluent/ksql/Ksql.java#L124

**Comment by vcrfxia** [comment]
> I have a feeling this is configurable via a system property, see https://github.com/confluentinc/ksql/blob/master/ksqldb-cli/src/main/java/io/confluent/ksql/Ksql.java#L124

Yep, good catch. @rodesai pointed this out as well. Another workaround for the time being is to include `KSQL_OPTS=-Dksql.client.enable.tls=true` in the CLI command:
```
KSQL_OPTS=-Dksql.client.enable.tls=true ./bin/ksql https://localhost:8088
```
