### ISSUE TITLE
Make the Properties file optional?

### ISSUE THREAD

**Issue by joewood** [confluentinc/ksql#489]
Could the ksql-server properties file be optional and instead allow the process to be entirely configured using environment variables? For example, the `STREAMS_BOOTSTRAP_SERVERS` is already used in the docker quickstart compose file. Unless I'm misunderstanding, right now I have to generate a properties file for **ksql-server-start** to use.

**Comment by miguno** [comment]
The properties file is optional.  If you omit it, the KSQL server starts with default settings.  See https://github.com/confluentinc/ksql/blob/4.0.x/docs/concepts.md#client-server-mode.

**Comment by miguno** [comment]
To clarify: I think your actual issue is that you want to deploy KSQL via Docker, and to make this more seamless you'd like the various KSQL server settings to be configurable through env variables?

**Comment by joewood** [comment]
Hi @miguno - yes, the aim is to make running with containers easier. Incidentally, if I try to run `ksql-server-start` without arguments I see:

```
root@ksql-cli:/# ksql-server-start
Required arguments are missing: 'properties-file'
See the -h or --help flags for usage information
```

**Comment by miguno** [comment]
Understood now, @joewood.  We will look into this.  We definitely want to provide a smooth experience for Docker. ;-)

**Comment by miguno** [comment]
FYI: We are currently working on better Docker images.

**Comment by miguno** [comment]
I'll close this because this will work with our upcoming Docker images.
