### ISSUE TITLE
LEFT Join statement always return null

### ISSUE THREAD

**Issue by NetGH** [confluentinc/ksql#491]
we have a query 

`select * from table as a join table as b on a.name = b.name;`
ksql-cli always display "null" and and query exit. May I know to troubleshoot that?

`select * from table` works .

Actually, we would like to implement a dwelltime calculation for a visit, there are two streams, one is entering stream, the other is leaving stream, we would like to calculate how many time it already taken for a specific visit.

Does KSQL support that?

**Comment by Satyajitv** [comment]
It could be because of the table alias name, that you have used in the query,
"as a" and "as b" and KSQL doesn't support inner join.
Please try below query,
select * from tablea left join tableb on tablea.name = tableb.name;

**Comment by chengang2** [comment]
@Satyajitv  select * from tablea left join tableb on tablea.name = tableb.name; but  the column of tableb isnull. how to resolve?

**Comment by fengzheng1024** [comment]
I meet the same problem .

**Comment by fengzheng1024** [comment]
now,when I try single field table,
select * from tablea left join tableb on tablea.name = tableb.name;,
it is OK.
