### ISSUE TITLE
Generated column names for field access can require quoting

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#4911]
ksqlDB generates the column names for STRUCT field access by dropping the source and replacing `->` with `__`, e.g. 

```sql
CREATE TABLE T (ID INT KEY, A STRUCT<B INT>) WITH (...);
CREATE TABLE AS SELECT A-> B FROM T;
-- output schema: ID -> A__B
```

This works for the simple case and even for the case where there are multiple levels of field access, e.g. `A->B->C` becomes a column names `A__B__C`. 

However, this breaks down when you throw array and map access into the mix, e.g. 

```sql
CREATE TABLE T (ID INT KEY, A STRUCT<B MAP<STRING, STRUCT<C ARRAY<INT>>>>) WITH (...);
CREATE TABLE AS SELECT A-> B['mapKey']->C[10] FROM T;
-- output schema: ID -> A__B['mapKey']__C[10]
```

The generated column name should work with @Almog's awesome work on quoted identifiers. However, the column name is a bit of a mouthful and requires quoting to be used in downstream queries.

Also, bare in mind that the name the key in a map can any string at the moment, .e.g `'I/'m.A$[Map]//Key'`.  In the future, we'll likely support MAPs with key types other name STRING, which may complicate things even more.

So... question is...  can we come up with a better naming? One that doesn't require quoting? Or do we stick with what we have?

Options that I see are:
1. Stick with what we have an just require users to quote their column names.

2. Use a generated column name like `KSQL_COL_0`.
   We can chose when to use column names like `KSQL_COL_0`. We could use them:  
      * always, i.e. we stop trying to generate the column name from the expression.  This matches what we do with other expressions that aren't a simple column name.
      * if the expression includes a map lookup. i.e.  `A-> B['mapKey']` becomes `KSQL_COL_0`, but array access or pure field access still get converted, e.g. `A->B[10]` becomes `A__B10` and `A->B` becomes `A__B`. (As its the string map keys that cause issues at the moment.
      * if the expression includes anything other than struct field access, i.e. map and array access causes the name to be in the form `KSQL_COL_0`. 
   
  (If going this route I'd also like to propose we replace the double underscores with singles, i.e. `A->B->C` should become `A_B_C` not `A__B__C`.  Only because I find the double underscores ugly. ;) )

3. Use only the most nested field name.
    e.g. `A->B->C` becomes `C`.
    We'd still need to work out what to do with map/array access, e.g. what do `A->B->C['some$Key']` and `A->B->C[10]` become?  I'd propose `KSQL_COL_0` and `C10`, respectively.

This is becoming more important as we'll be naming the key column from struct field to with: https://github.com/confluentinc/ksql/issues/4895

**Comment by big-andy-coates** [comment]
cc @derekjn @MichaelDrogalis: any thoughts on this chaps?

**Comment by MichaelDrogalis** [comment]
@big-andy-coates Maybe I'm missing something, but why does `SELECT A-> B['mapKey']->C[10]` require quoting to begin with?

**Comment by big-andy-coates** [comment]
It's not the original select that needs quoting, it's the generated column name.

Given:

```sql
CREATE TABLE T2 AS SELECT A-> B['mapKey']->C[10] FROM T;
```

The table `T2` has a column named `A__B['mapKey']__C[10]`, which is a pretty funky column name!  If the user wants to reference this column in another query they'll need to quote it and work out how to escape the quotes already embedded in the name.  I _think_ it would need to be something like:

```sql
SELECT 'A__B['''mapKey''']__C[10]' from T2';
```

**Comment by MichaelDrogalis** [comment]
Ahh, I understand now. Thanks for clarifying @big-andy-coates. I agree that referencing that expression every time is just gross. (3) seems problematic since you could easily have a name collision if more than two columns reference the same inner name. (2) seems about right, with the pragmatic thing always being generating a name for it. I think using `AS` is an easy convention to catch onto when using this pattern.

**Comment by big-andy-coates** [comment]
Personally, I think (3) is the cleanest.  If there's a name clash, then they can add an alias.

But if we're going for (2), then which version of (2)?

a) always, i.e. we stop trying to generate the column name from the expression. This matches what we do with other expressions that aren't a simple column name.
b) if the expression includes a map lookup. i.e. A-> B['mapKey'] becomes KSQL_COL_0, but array access or pure field access still get converted, e.g. A->B[10] becomes A__B10 and A->B becomes A__B. (As its the string map keys that cause issues at the moment.
c) if the expression includes anything other than struct field access, i.e. map and array access causes the name to be in the form KSQL_COL_0.

I think (b) works OK, but that the same time we could just bin the whole special handling for struct field column naming and people can just add aliases.

**Comment by MichaelDrogalis** [comment]
(3) is okay to me too as long as there's a good error message about aliasing when there is a collision.

**Comment by agavra** [comment]
FWIW (since @big-andy-coates asked for my opinion 😉) I'm happy with any of the options; I think if users really care they'll use aliasing to specify the name that they want to begin with.

**Comment by big-andy-coates** [comment]
Yep, I agree people will/should generally alias.  I know this is not a big thing. But is most likely that people will run into this issue early in their ksql journey, and didn't want to just make a change without checking with Product first.
