### ISSUE TITLE
Can not use NULLs in INSERT VALUES

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#4912]
Running:

```sql
INSERT INTO FOO (colA, colB) VALUES (NULL, NULL);
```

Should work, but fails with NPE.

**Comment by archy-bold** [comment]
I've found you can use the `CAST()` function as follows to achieve similar, but not sure if it can be used in all statements.

```
CAST(null AS VARCHAR)
```

**Comment by deuscapturus** [comment]
> I've found you can use the `CAST()` function to achieve this with primitives, but not sure if it can be used in all statements. It certainly doesn't work for non-primitive types eg `STRUCT`
> 
> ```
> CAST(null AS VARCHAR)
> ```

I was able to INSERT INTO SELECT and set null values for STRUCTS and other non-primitive types with CAST() as of at least v0.27.2
