### ISSUE TITLE
Add CLI parameter to execute commands without KSQL interative

### ISSUE THREAD

**Issue by spena** [confluentinc/ksql#4981]
**Is your feature request related to a problem? Please describe.**

I sometimes want to execute a single statement in KSQL, i.e list current streams, without going into the KSQL command line,  but can't find how. The only option is to open the CLI, and wait until it initializes, then run the command.

**Describe the solution you'd like**

I'd like to use a CLI parameter, like Mysql and other databases do, to execute a command without going into the KSQL command line. This will allow me to write scripts to get info from KSQL.

Example:
```
$ ksql -e "show streams;" | grep -v KSQL_PROCESSING_LOG | awk '{print $1}' | sed '/^\s*$/d' | tail +2
PS1
s1
```

**Describe alternatives you've considered**

There are no alternatives.

**Additional context**

**Comment by blueedgenick** [comment]
big +1 from me. In fact, this used to work, not sure where along the line it got regressed.
