### ISSUE TITLE
Array functions Docs error 

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#5020]
https://docs.ksqldb.io/en/latest/developer-guide/ksqldb-reference/scalar-functions lists function `ARRAY_CONTAINS` as `ARRAYCONTAINS`, and doesn't include reference for `ARRAY_LENGTH`

/cc @JimGalasyn

**Comment by JimGalasyn** [comment]
Fixed in https://github.com/confluentinc/ksql/pull/5124.
