### ISSUE TITLE
No variations for GEO_DISTANCE on latest master

### ISSUE THREAD

**Issue by vcrfxia** [confluentinc/ksql#5024]
**Describe the bug**

Submitting a query with the built-in `GEO_DISTANCE` function results in
```
Code generation failed for Predicate: Function 'geo_distance' does not accept parameters (DOUBLE, DOUBLE, DECIMAL(6, 4), DECIMAL(7, 4)).
Valid alternatives are:

For detailed information on a function run: DESCRIBE FUNCTION <Function-Name>;. expression:(GEO_DISTANCE(LATITUDE, LONGITUDE, 37.4133, -122.1162) <= 5), schema:`ROWKEY` STRING KEY, `PROFILEID` STRING, `LATITUDE` DOUBLE, `LONGITUDE` DOUBLE, `ROWTIME` BIGINT, `ROWKEY` STRING
```

**To Reproduce**

1. Build ksqlDB from `master`.
2. Follow the [quickstart](https://ksqldb.io/quickstart.html) including the command `SELECT * FROM riderLocations WHERE GEO_DISTANCE(latitude, longitude, 37.4133, -122.1162) <= 5 EMIT CHANGES;`

**Expected behavior**

Query is submitted successfully.

**Actual behaviour**

The error message
```
Code generation failed for Predicate: Function 'geo_distance' does not accept parameters (DOUBLE, DOUBLE, DECIMAL(6, 4), DECIMAL(7, 4)).
Valid alternatives are:

For detailed information on a function run: DESCRIBE FUNCTION <Function-Name>;. expression:(GEO_DISTANCE(LATITUDE, LONGITUDE, 37.4133, -122.1162) <= 5), schema:`ROWKEY` STRING KEY, `PROFILEID` STRING, `LATITUDE` DOUBLE, `LONGITUDE` DOUBLE, `ROWTIME` BIGINT, `ROWKEY` STRING
```

**Additional context**

This is not an issue on 0.8.1 or earlier.

**Comment by agavra** [comment]
@vcrfxia did you compile with the `-parameters` flag? (do any UDFs work?)

**Comment by vcrfxia** [comment]
I built a docker image from master using the command in https://github.com/confluentinc/ksql/blob/master/ksqldb-docker/README.md. 

I just tried the latest RC from Jenkins and it's not an issue there so it must be something about the docker build command, but the two look more or less the same to me. Can you spot the difference?

**Comment by vcrfxia** [comment]
The only difference that jumps out at me is that the two commands use different maven profiles, but comparing the two profiles I don't see anything overrides that affect the `-parameters` compiler arg specified in the ksqldb-parent pom.

**Comment by vcrfxia** [comment]
Tried reproducing this just now on the latest master and was unsuccessful with either the UBI base image or the old Debian base image, so I'm going to close this issue as fluke ¯\_(ツ)_/¯
