### ISSUE TITLE
Add support for joining array contents into a string

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#5028]
I'd like to see a function that will take an array and just flatten it.

e.g. `['a','b','c']` becomes `a,b,c`

My use case is simplifying JDBC sink which doesn't support writing arrays to target DBs (even if they support it e.g. postgres)

**Comment by hpgrahsl** [comment]
@rmoff based on your simple, single example above I would assume you expect the following for such a UDF - let's call it `ARRAY_JOINER` for now:

1) provide several overloaded variants for all different primitive data types i.e. `BOOLEAN,INTEGER,BIGINT,DOUBLE,VARCHAR`
2) always returns a single value of type `VARCHAR` composed of the string representation of each value contained in the array
3) offers a function parameter which allows to specify a custom separator character e.g. `,` or `|`...

If so, I assume this to be rather straigt-forward. Now the fun part:

- What output would you expect for array elements of non-primitive types i.e. maps and structs?
- Should this function be applicable for nested data structures e.g. arrays of arrays of... likewise what about deeply nested structs? 

Your input as reporter is highly appreciated here @rmoff ;-)

**Comment by rmoff** [comment]
TBH my motivation for this was just to get "something" that worked based on the original use case. 

It'd probably be a good idea to look at existing solutions for this elsewhere (e.g. postgres) to understand common patterns. 

On your three assumptions, I would agree with those. On the two fun questions, I have no opinion/answer :) 

/cc @blueedgenick @derekjn who maybe have some good references / pointers on the direction for this to take

**Comment by derekjn** [comment]
@hpgrahsl these are excellent questions. I see two approaches to such an array join builtin:

1. We make it **strict**, requiring all input expressions to be strings. Users would be required to explicitly cast/stringify each array element.
2. We make it **non-strict**, in which case the equivalent of `CAST(element AS STRING)` would be implicitly applied to each array element.

I believe both of these approaches should work on both primitive and structured types.

**Comment by hpgrahsl** [comment]
@derekjn thx for sharing your thoughts.

for what you call "strict": if I understood you correctly it would mean that users have to find a way to cast each of the elements first which is probably not so nice since you can have any number of elements inside the array. what would work is to provide an array helper function that does the CAST/STRINGIFY on all elements so that its output can be passed into the JOINER function. but then again it is an additional step for users so the "non-strict" approach where this happens implicitly is a much better choice IMHO. WDYT?

**Comment by derekjn** [comment]
> for what you call "strict": if I understood you correctly it would mean that users have to find a way to cast each of the elements first which is probably not so nice since you can have any number of elements inside the array

That understanding is correct. There are also array literals to consider:

```sql
SELECT ARRAY_JOIN('<delimiter>', ARRAY['one', 'two', 'three']) ...
```
But I agree that the non-strict approach would be a preferable UX here.

**Comment by vcrfxia** [comment]
This functionality is now supported by the `ARRAY_JOIN` method, added by @hpgrahsl . Closing this ticket as done. Thanks!
