### ISSUE TITLE
create stream: quotes around partition are ignored

### ISSUE THREAD

**Issue by datumgeek** [confluentinc/ksql#503]
Quotes around `partition by` expression doesn't work to specify lower case, get error saying no column CMTSNODE.

```
create stream node_analysis_run with (value_format='json', partitions=5) as select r.cmtsnode as "cmtsnode", r.cmts as "cmtz", r.cmts as "cmts", r.node as "node", 'run' as "state" from node_analysis_request r left join node_analysis_state s on r.rowkey = s.rowkey where ((s.state is null) or (s.state = 'at rest')) partition by "cmtsnode";
```

**Comment by rmoff** [comment]
@datumgeek Does it work if you `PARTITION BY cmtsnode`?

**Comment by rmoff** [comment]
@datumgeek I've just tested this locally and I think it's all good in the latest version (5.0.0-SNAPSHOT). Please re-open if not. Also see #1475.
