### ISSUE TITLE
Missing docs for new LATEST_BY_OFFSET UDAF

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#5033]
There doesn't seem to be any documentation for the new `LATEST_BY_OFFSET` UDAF.  This is especially important given it has some pretty strict valid use-cases / known limitations.

**Comment by JimGalasyn** [comment]
Thanks for the feedback, @big-andy-coates! We have a little blurb at https://docs.ksqldb.io/en/latest/developer-guide/ksqldb-reference/aggregate-functions/#latest_by_offset -- please feel free to add a comment with use-cases/limitations, and I'll get them in there.

**Comment by purplefox** [comment]
Docs were added when I wrote it in the aggregate functions reference, after discussing with Jim. Is this the wrong place?

**Comment by JimGalasyn** [comment]
@purplefox @big-andy-coates It's in the 0.8.1 docs: https://docs.ksqldb.io/en/latest/developer-guide/ksqldb-reference/aggregate-functions/#latest_by_offset. Does it also need to be in the 0.7.1 docs?

**Comment by purplefox** [comment]
Hey Jim, the feature was released in 0.8.1 so I don't think it needs to go in the 0.7.1 docs.

**Comment by JimGalasyn** [comment]
kk cool, so we can close this puppy?

**Comment by purplefox** [comment]
I think so :)

**Comment by JimGalasyn** [comment]
Fixed in https://github.com/confluentinc/ksql/pull/4782.
