### ISSUE TITLE
Support COUNT DISTINCT

### ISSUE THREAD

**Issue by jinleileiking** [confluentinc/ksql#506]
Edited by @miguno on Nov 23, 2018:

> From @apurvam at https://github.com/confluentinc/ksql/issues/506#issuecomment-367848878
>
> I take this feature to mean that we should implement the `DISTINCT` keyword such that the following query would count the number of distinct values for `field` in the window:
>
> ```
> SELECT COUNT(DISTINCT field) FROM stream WINDOW TUMBLING (size 1 hour);
> ```

Original ticket was empty.

**Comment by sun7059** [comment]
hello, how does the ksql support `distinct` syntax

**Comment by apurvam** [comment]
I take this feature to mean that we should implement the `DISTINCT` keyword such that the following query would count the number of distinct values for `field` in the window:

```
SELECT COUNT(DISTINCT field) FROM stream window tumbling (size 3600 seconds);
```

**Comment by tomlinsonr** [comment]
+1 for this

**Comment by fengzheng1024** [comment]
+1 for this

**Comment by dantaya** [comment]
+1 for this would solve my issue

**Comment by Jianyi-Ren** [comment]
maybe we can just use [TOPKDISTINCT](https://docs.confluent.io/current/ksql/docs/syntax-reference.html#aggregate-functions) and assign k as maxint.

**Comment by sangli00** [comment]
@Jianyi-Ren  
cannot use this SQL.
```select col1,count(TOPKDISTINCT(field,10)) from stream window_tumbing(size 100 seconds);```
error:
Caused by:Can't find any function with the name 'TOPKDISTINCT'

**Comment by sangli00** [comment]
I try ``` select count(sum(cols)) from stream;```
This statement is cannot use KSQL.
error:can't find any function with the name  'COUNT'

**Comment by dspathak** [comment]
> @Jianyi-Ren
> cannot use this SQL.
> `select col1,count(TOPKDISTINCT(field,10)) from stream window_tumbing(size 100 seconds);`
> error:
> Caused by:Can't find any function with the name 'TOPKDISTINCT'

The issue here is piping the output of one function (TOPKDISTINCT) into another function (COUNT). If you simply had TOPKDISTINCT by itself, you would not see that error.

Assuming that the above piping worked, the above query would give correct results only if we are assured that the number of distinct elements in the stream is less than K.

**Comment by sangli00** [comment]
so,How to use count distinct in KSQL?

**Comment by gpinu1** [comment]
Hi , I wanted to check , if we can create  UDFs, I mean a scalar function to give only the distinct values of the stream like the TOPKDISTINCT function but it works only with group by function. Can we just create a Distinct function in sql eg. select distinct EMPLOYEE_ID from EMPLOYEE in ksql. if yes? guide. I will build the UDFs.

Thanks for your help

**Comment by apurvam** [comment]
Adding to the UDF epic: #3556

**Comment by MichaelDrogalis** [comment]
Staged for next release: https://github.com/confluentinc/ksql/pull/4150

**Comment by vitalikaz** [comment]
Do we have any ETA when we can expect #4150 to appear in main builds and ksql docker images?

**Comment by MichaelDrogalis** [comment]
@vitalikaz This already shipped in [0.7.0](https://hub.docker.com/layers/confluentinc/ksqldb-server/0.7.0/images/sha256-ab51193592dc413cbe4c69bd826ea2c44ed5e9eeccd8bed738c5fe05602bcaf0?context=explore).

**Comment by vitalikaz** [comment]
Nice! One small thing, which might be out of topic though. Can't find any docs on how `confluentinc/ksqldb-server` docker images relate to `confluentinc/cp-ksql-server` images and how often do they sync with each other in terms of new features?

**Comment by MichaelDrogalis** [comment]
@vitalikaz Good question. This is something we're working on documenting precisely right now. To keep this issue on topic, swing by #ksqldb in the Confluent Community Slack room and I can give the quick rundown.
