### ISSUE TITLE
No documentation on ksqldb version numbers vs confluent version numbers

### ISSUE THREAD

**Issue by Keristero** [confluentinc/ksql#5111]
I see confluent version numbers here https://hub.docker.com/r/confluentinc/cp-ksql-server/tags
and ksqldb version numbers here https://github.com/confluentinc/ksql/blob/master/CHANGELOG.md#080-2020-03-18
What is the difference? I see both forms of version numbers thrown around in the commits
Can I find a table somewhere relating these?

**Comment by JimGalasyn** [comment]
Hi @Keristero. You’ve caught us during the middle of some changes! Sorry about that, we’re still tidying up.

There are two distributions of ksqlDB: standalone and enterprise (part of Confluent Platform). We’re about to post some documentation that describes how the two link together, but the short story is that the distribution in Confluent  Platform essentially wraps around an existing standalone distribution.

The current version of ksqlDB standalone is 0.8.1. The upcoming version of Confluent Platform ksqlDB is 5.5.0, which will contain 0.7.1 standalone, plus a few patches.
Hopefully this is helpful for now - we’ll be posting docs shortly to make it easier to track this in the future.

**Comment by Keristero** [comment]
Awesome, thanks
