### ISSUE TITLE
GROUP BY not recognizing SELECT Elements?

### ISSUE THREAD

**Issue by kdrakon** [confluentinc/ksql#512]
Maybe I've been looking at my screen too long, but doesn't my `group by` contain the necessary elements to perform a grouping?
```
ksql> create stream rejected_orders with (kafka_topic='output.rejected_orders', value_format='json') as select * from orders where current_status = 'Rejected';

 Message
----------------------------
 Stream created and running
ksql> describe rejected_orders;

 Field          | Type
----------------------------------
 ROWTIME        | BIGINT
 ROWKEY         | VARCHAR(STRING)
 REQUEST_ID     | BIGINT
 ORDER_ID       | VARCHAR(STRING)
 PLATFORM       | VARCHAR(STRING)
 ORDER_TYPE     | VARCHAR(STRING)
ksql> select request_id, current_status from rejected_orders group by request_id;
Group by elements should match the SELECT expressions.
ksql>
```
This is running on the Docker image of ksql-cli, version 0.2 (080bbe2bfdbf).

**Comment by kdrakon** [comment]
I was actually trying to initially perform the following:
```
create table rejected_orders_table with (kafka_topic='output.rejected_orders_table', 
value_format='json') as select request_id, current_status from rejected_orders 
group by request_id;
```

**Comment by hjafarpour** [comment]
@kdrakon currently KSQL only supports `GROUP BY` clause with aggregate functions so you need to use at least one aggregate function such as `count` to use `GROUP BY`.

**Comment by kdrakon** [comment]
Thanks for clarifying @hjafarpour

**Comment by kdrakon** [comment]
Would 
`select request_id, count(request_id), current_status from rejected_orders group by request_id;`
be expected to work then, because I'm getting the same error message?

**Comment by kdrakon** [comment]
Ah, I see, the above looks to be working if I remove the `current_status` field.
