### ISSUE TITLE
ConnectIntegration.shouldDescribeConnector is unstable.

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#5127]
Fails often with the error:

```
java.lang.AssertionError: 
Expected: an instance of io.confluent.ksql.rest.entity.ConnectorDescription
     but: <ErrorEntity{errorMessage='{"error_code":404,"message":"No status found for connector mock-connector"}'}> is a io.confluent.ksql.rest.entity.ErrorEntity
```

This looks to be caused by a race condition:  When the create connector command returns there is a delay before the status of the connector is set in the connect server.  Any attempt to describe the connector before it it set will result in the above error.

There is a retry loop in DefaultConnectClient. However, this does not seem to be being invoked for this failure scenario.  Not sure if its meant to.

Fix seems to be either:
 - fix in prod code: i.e. retry on this error
 - fix in test code: i.e. change the test to `assertThatEventually`...

**Comment by agavra** [comment]
fixed by #5204
