### ISSUE TITLE
Improve docs on grace period and window retention

### ISSUE THREAD

**Issue by vinothchandar** [confluentinc/ksql#5140]
@big-andy-coates had a good suggestion. Opening an issue to track this. 

Docs: I see an update to the `time-and-windows-in-ksqldb-queries.md`, which is good, but it feels like this feature would benefit from being included in other reference style docs, e.g. `create-stream-as-select.md` and `create-table-as-select.md`, and `insert-into.md` and some join docs, i.e. anywhere the windowing stuff is currently documented.

@JimGalasyn wdyt?

**Comment by rmoff** [comment]
+1 this would be good to have, I went looking for the syntax today and struggled.

**Comment by JimGalasyn** [comment]
@vinothchandar @rmoff I can sprinkle around links to the [Late-arriving events](https://docs.ksqldb.io/en/latest/concepts/time-and-windows-in-ksqldb-queries/#late-arriving-events) and [Window retention](https://docs.ksqldb.io/en/latest/concepts/time-and-windows-in-ksqldb-queries/#window-retention) sections, how does that sound?

**Comment by rmoff** [comment]
I personally prefer to see the actual full syntax listed in the syntax pages, not just links.

**Comment by JimGalasyn** [comment]
@rmoff k cool, just so I'm clear you'd like to see the code snippets from those two sections sprinkled around, correct?

**Comment by rmoff** [comment]
👍  @JimGalasyn

**Comment by JimGalasyn** [comment]
I added some snippets in appropriate places: https://github.com/confluentinc/ksql/pull/6362. Please let me know if you'd like to submit others!
