### ISSUE TITLE
Make the command-runner thread restartable when the consumer throws an exception

### ISSUE THREAD

**Issue by rodesai** [confluentinc/ksql#5141]
**Is your feature request related to a problem? Please describe.**
When the command runner thread exits, we terminate the JVM because it can no longer respond to incoming requests (if the uncaught exception handler is enabled). This works because we'll eventually recover, but it's not very graceful.

**Describe the solution you'd like**
Ideally we don't restart the whole server. Instead, we should just retry the poll from the command-runner thread (maybe after recreating the consumer). However we need to be careful that we resume consuming the command topic from the command following the command that we last applied, otherwise we'll corrupt our state.

**Comment by apurvam** [comment]
This would depend on the type of exception right? Are we saying that we only want to restart on things like `TimeoutException` ?

**Comment by purplefox** [comment]
@rodesai Can you provide some more specific pointers on this? E.g. the classes and methods that you're referring to.

**Comment by rodesai** [comment]
When ksql is configured with an uncaught exception handler, and the command runner hits an uncaught exception, we exit the JVM. The thinking was that in settings where there is a process or cluster manager (e.g. upstart or kubernetes), this is preferable to doing nothing, because the node will be automatically restarted and recover. If we did nothing, the command topic would just remain unconsumed and the `/ksql` endpoint would be unusable. Problems with this approach:
    - it disrupts query processing
    - the error that caused the command topic to fail (e.g. consumer.poll erroring out) might prevent the server from starting up

Couple of ways I think this might be improved:

1. The main unhandled error scenario is exceptions thrown from `KafkaConsumer.poll`. The current implementation is really conservative about these - nothing handles exceptions from `poll` and we restart. We should figure out whether there are any exceptions here that we could handle by just retrying the poll.

2. Have the command runner try to recover without a full process restart for errors that aren't retry-able. For exceptions that aren't retry-able, we need to re-init the kafka consumer, and then reset it's position to the next expected offset (the offset after the last successfully applied command).

Whenever I've seen this come up, it's been a `TimeoutException`. I think we should figure out if getting a `TimeoutException` from the `poll` is something that makes sense to retry on (I'm not sure - based on the docs it's not supposed to throw this), and then do one of the above based on that.

**Comment by purplefox** [comment]
Imho, throwing a TimeoutException by the Kafka client seems a reasonable thing to do. The call to poll() needs to return after timeout anyway. If Kafka  is unreachable then, if it didn't throw an exception it would need to return an empty iterator, and there would be no way to distinguish that from there simply being no records available.

**Comment by purplefox** [comment]
Retrying on TimeoutException seems a reasonable thing to do - transient network errors are to be expected I guess. In which case is the fix for this kind of trivial? Just catch TimeoutException and continue the poll loop?

**Comment by purplefox** [comment]
Not sure, why we would need to reset the offset on the consumer? If the server hasn't delivered any records, then the client wouldn't have updated the offset anyway, but perhaps I am missing something here?

**Comment by purplefox** [comment]
Hey @rodesai any thoughts on the above?

**Comment by stevenpyzhang** [comment]
@rodesai @purplefox are there any updates for this?

**Comment by rodesai** [comment]
Ah we discussed off-line. I think my analysis is not correct. I don't think the TimeoutException is being thrown from poll. It's probably from our call to position. We could add error handling there but it would be simpler to just tune the command consumer timeouts to allow for a longer loss of connectivity (I think the default is a minute).

**Comment by purplefox** [comment]
So can I close this issue now?

**Comment by rodesai** [comment]
Closed.
