### ISSUE TITLE
View Tables Properties for a Stream

### ISSUE THREAD

**Issue by tomlinsonr** [confluentinc/ksql#516]
For Arcadia Data:

Need a way to look at the properties set for a table or stream:
```
DESCRIBE PROPERTIES (stream_name | table_name)
```

**Comment by hjafarpour** [comment]
@tomlinsonr is this what you need?
https://github.com/confluentinc/ksql/pull/511
If yes, it will include in our December release.

**Comment by tomlinsonr** [comment]
Great! The proposed enhancement in December looks like it will cover it
