### ISSUE TITLE
KSQL avro schemas need to support non-nullable fields

### ISSUE THREAD

**Issue by terryf82** [confluentinc/ksql#5160]
Avro schemas generated by KSQL (either automatically or explicitly) by default allow each field to be null. This can conflict with the intent of an existing schema, and in the case of using a CDC connector like Debezium prevent natural schema evolution.

For example, a v1 schema created by Debezium reflects the structure of the source table (not allowing nulls where the table didn't):

```
...
"fields": [
    {
      "name": "before",
      "type": [
        "null",
        {
          "type": "record",
          "name": "Value",
          "fields": [
            {
              "name": "id",
              "type": "int"
            },
            {
              "name": "name",
              "type": "string"
            },
```

Registering a KSQL stream / table over this topic creates v2 of the schema, allowing for nulls by default:

```
...
"fields": [
    {
      "name": "BEFORE",
      "type": [
        "null",
        {
          "type": "record",
          "name": "KsqlDataSourceSchema_BEFORE",
          "fields": [
            {
              "name": "ID",
              "type": [
                "null",
                "int"
              ],
              "default": null
            },
            {
              "name": "NAME",
              "type": [
                "null",
                "string"
              ],
              "default": null
            },
```

Now, if a change is made to the source table such as adding a new field, Debezium cannot push a v3 schema and maintain full compatibility, because it will try to indicate `id` and `name` can only hold `int` and `string` respectively, breaking compatibility with v2.

Ideally KSQL should look to the first schema (v1) and mirror its structure for non-nullable fields when creating a stream / table. If this isn't possible, being able to specify `not null` when manually configuring the schema in CS/CT statements would be the next best thing.

cc @MichaelDrogalis

**Comment by MichaelDrogalis** [comment]
Set for 0.10, but might punt it out once we scope the effort.

**Comment by spena** [comment]
This feature is being tracked in this issue: https://github.com/confluentinc/ksql/issues/4436

I'll close this issue as a duplicate.
