### ISSUE TITLE
Enhance AS_VALUE to support structured type

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#5170]
AS_VALUE UDF is used to copy a key column into the value.  For primitive keys it only needed to support primitive keys. However, for structured keys the key column type can also be other more complex types, i.e. DECIMAL, LIST, STRUCT, MAP.

AS_VALUE will need enhancing to support these types. Ideally, this would be done by enhancing the UDF framework to support a more simple impl of AS_VALUE:

```java
@UdfDescription(name = "AS_VALUE", description = AsValue.DESCRIPTION)
public class AsValue {

  ...

  @Udf(schemaProvider = "schemaProvider")
  public Object asValue(@UdfParameter final Object val) {
    return val;
  }

  @UdfSchemaProvider
  public SqlType schemaProvider(final List<SqlType> params) {
    return params.get(0);
  }
}
```

**Comment by vcrfxia** [comment]
This is done, and QTTs were added as well: https://github.com/confluentinc/ksql/blob/07bd62906c0758f9c2febc767a8335a1b1572f96/ksqldb-functional-tests/src/test/resources/query-validation-tests/as_value.json#L153-L194
