### ISSUE TITLE
Problems with column name and escaping

### ISSUE THREAD

**Issue by otobrglez** [confluentinc/ksql#5196]
**Describe the bug**
Trying to use a column with reserved keyword results in an error. Escaping; doesn't work.

**To Reproduce**
I'm having a stream with a struct that has a name "group"; so this query fails

```SQL
select 
	venue->venue_name as group_name,  -- <-- this works nicely.
        group->group_name as group_name   -- <-- fails
from hello_ksql 
EMIT CHANGES; -- Experimenting from control-center
```

With following parsing error:

```
Error parsing query: line 3:5: mismatched input 'group' expecting {'(', 'EMIT', 'CHANGES', 'NOT', 'NULL', 'TRUE', 'FALSE...
```

If I try to using escaping (standard in [SQL 1999](https://en.wikipedia.org/wiki/SQL:1999) for example [here](https://github.com/ronsavage/SQL/blob/master/sql-99.bnf) with double quote (") [(QUOTATION MARK)](https://unicode-table.com/en/0022/))

```sql
select 
  venue->venue_name as group_name,
  "group->group_name" as group_name -- <- like so
from hello_ksql 
EMIT CHANGES;
```

If fails with:

```
Column 'HELLO_KSQL.group->group_name' cannot be resolved.
```

**Expected behaviour**
The query should work; if not with standard query language; then with usage of escaping - or not? :)

**Additional context**
- confluent-5.4.1 (ksql server)

This is my first bug report here; so please be gentle. 

Thank you guys for making this amazing piece of software!

Cheers!

**Comment by agavra** [comment]
Hello @otobrglez - can you try quoting it like `"group"->group_name` instead? otherwise it looks for the entire name `"group->group_name"` in the `hello_ksql` schema.

**Comment by otobrglez** [comment]
Hey @agavra! I later found out that this works,...

```
SELECT 
  venue->venue_name as group_name,
  `GROUP`->group_name as group_name -- <- this
from hello_ksql 
EMIT CHANGES;
```

Notice the backticks around the group part. Cheers.

**Comment by agavra** [comment]
Glad it worked! Closing out this ticket
