### ISSUE TITLE
Data in Kafka topic for Ksql query disapears

### ISSUE THREAD

**Issue by dujijun007** [confluentinc/ksql#520]
I create a table and a stream, then join them to a stream with a Kafka topic.
I write sql like these:

Table:
```
create table patient_flat_table (_user_id varchar, _name varchar, _race varchar, _birthdate varchar, _timestamp bigint, _gender varchar) with (kafka_topic='patient-json', value_format='json', timestamp='_timestamp');
```

Stream:
```create stream heart_rate_flat_stream (_user_id varchar, _timestamp bigint, _measures_heart_rate_unit varchar, _measures_heart_rate_value double) with (kafka_topic='heart-rate-json', value_format='json', timestamp='_timestamp');
```

Join to a Stream:
```
create stream heart_rate_patient_join_stream with (kafka_topic='heart-rate-patient-join', value_format='json', timestamp='timestamp') \
as \
select h._user_id user_id, h._timestamp timestamp,h._measures_heart_rate_value, p._gender gender, p._race race \
from \
HEART_RATE_FLAT_STREAM h \
left join \
PATIENT_FLAT_TABLE p \
on h._user_id = p._user_id \
where p._gender is not null and p._race is not null and h._timestamp is not null;
```

I set 'auto.offset.reset' = 'true' in ksql cli, and in the beginning I can consume message from the topic `heart-rate-patient-join`, but a few minutes later, I can't get data from this topic any more.

**Comment by hjafarpour** [comment]
@dujijun007 You need to set the `key` in `WITH` clause when you create a table. Make sure the key value in `patient-json` topic is set to the same value as `_user_id`.
`auto.offset.reset` can be either `earliest` or `latest`.
Try these and let me know if you still see the problem.
Also make sure that `heart-rate-json` has continuous data.

**Comment by dujijun007** [comment]
@hjafarpour Thanks for your help! You are right, our topic `heart-rate-json` doesn't have continuous data, we just wanna join the historical data and output to a topic for a simple test of integration with Kylin and Kafka, that's why I set `auto.offset.reset` to `earliest`. It's the reason for the failure? I don't know exactly why the data can be seem at the first but disappears soon even though I check the `delete.retention.ms` property is set to 7days.

**Comment by big-andy-coates** [comment]
Hi @dujijun007 , you'd previously mentioned that you set `auto.offset.reset` to `true`, not `earliest`. So you may want to check!  Assuming you have set to `earliest` and you are using the `WITH (Key=something)` clause in your `CREATE TABLE` statement, and you're sure the key of each Kafka record matches the contents of the `_user_id` field, then it should all work ;)

This issue has been open a while without any activity. If you're still encountering errors after ensuring all of the above, then please get back to us with more details and we'll do all we can to help.

If we don't hear back from you soon we'll assume you're all sorted and close the issue, (though feel free to reopen / recreate if you're still having issues!).
