### ISSUE TITLE
Docs incorrectly reference planned KEY_FORMAT option.

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#5218]
https://docs.ksqldb.io/en/0.7.1-ksqldb/developer-guide/serialization/
 references `KEY_FORMAT`, but that hasn't been released yet!  

The key format is _always_ `KAFKA` until https://github.com/confluentinc/ksql/issues/4461 is done.

**Comment by JimGalasyn** [comment]
Fixed in https://github.com/confluentinc/ksql/pull/5280 and cherry picked to various branches.
