### ISSUE TITLE
Protobuf section in wrong place

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#5219]
In https://docs.ksqldb.io/en/0.7.1-ksqldb/developer-guide/serialization/ the protobuf section is within the 'Single field (un)wrapping' section, where as it should be above that section under `serialization formats`.

**Comment by MichaelDrogalis** [comment]
Fix in https://github.com/confluentinc/ksql/pull/5267

**Comment by JimGalasyn** [comment]
Cherry-picked to various branches.
