### ISSUE TITLE
Better docs around schema inference

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#5220]
There doesn't seem to be much documentation about schema inference that I could find, i.e. ksql getting the schema from SR.  Maybe I'm just not looking in the right place?

I did find https://docs.ksqldb.io/en/0.7.1-ksqldb/concepts/schemas/ - but that's just a todo page :(

I found https://docs.ksqldb.io/en/0.7.1-ksqldb/operate-and-deploy/installation/server-config/avro-schema/#configure-avro-and-schema-registry-for-ksql, but that doesn't really cover much. It mainly talks about Avro, mentions Protobuf a little bit, and Json not at all.

Avro, PB and Json schemas are all supported, (@agavra can you confirm they were all supported in 0.7?)

0.7 also so the introduction of partial schemas for CT and CS statements, (https://github.com/confluentinc/ksql/pull/4625), where the user can just supply the key schema and the value schema is loaded from SR.

It would be good to better explain how loading schemas from SR can be used.  Seems that `create-a-table.md`, `create-a-stream.md`, `create-table.md` and `create-stream.md` would be good places to either explain some of this stuff or link to somewhere that does.

We should be explain that users need don't need to supply the value columns in CT/CS statements if they are using SR. They only need to provide the key columns.  

We should explain that JSON and PB are also supported, not just Avro.

**Comment by big-andy-coates** [comment]
Added a little bit of detail to https://github.com/confluentinc/ksql/pull/5222, but more is needed.

**Comment by apurvam** [comment]
I'm dropping this to P1, since it has been open for nearly 4 months and doesn't seem to be causing much confusion.
