### ISSUE TITLE
Allow -1 as a valid replication factor

### ISSUE THREAD

**Issue by MichaelDrogalis** [confluentinc/ksql#5233]
As of [KIP-464](https://cwiki.apache.org/confluence/display/KAFKA/KIP-464%3A+Defaults+for+AdminClient%23createTopic), the AdminClient can use `-1` as the replication factor for partitions and the broker defaults. This is useful so that ksqlDB can honor the defaults of the broker. We also need to do this so that ksqlDB behaves as other components in Confluent Platform do.

Today, ksqlDB will not accept anything less than 1 as a valid replication factor.  We should allow `-1` as a valid value.

**Comment by agavra** [comment]
@MichaelDrogalis - FWIW, when implementing this in ksql I intentional kept this constraint because ksql gives you the ability _not_ to specify a replication factor at all (and that is the same semantically as setting it to -1). Personally, I feel like this is easier to understand but I'm happy to defer to product on this one about whether or not we should support -1.

**Comment by MichaelDrogalis** [comment]
@agavra That makes sense is probably a better choice in a vaccuum. In this case, we want to support `-1` since it should work uniformly across Confluent Platform.

**Comment by PeterLindner** [comment]
@agavra if I remember correctly it is required to specify the replication factor to create an empty stream/table, this means it's impossible to create them with defaults now

**Comment by agavra** [comment]
@MichaelDrogalis makes sense, I'll do that.

@PeterLindner I'm not sure what you mean, if you're referring to creating a topic alongside a DDL this works:
```sq
ksql> CREATE STREAM foo (id VARCHAR) with (value_format='json', partitions=1, kafka_topic='foo');

 Message
----------------
 Stream created
----------------
ksql> show topics;

 Kafka Topic                 | Partitions | Partition Replicas
---------------------------------------------------------------
 default_ksql_processing_log | 1          | 1
 foo                         | 1          | 1
---------------------------------------------------------------
```

**Comment by PeterLindner** [comment]
@agavra wasn't aware of that, sorry
Thanks for clarification
