### ISSUE TITLE
Basic auth docs example fails with "unable to find LoginModule class"

### ISSUE THREAD

**Issue by vcrfxia** [confluentinc/ksql#5254]
**Describe the bug**

The removal of Jetty from the ksqlDB server (https://github.com/confluentinc/ksql/pull/5134) means the basic auth examples in our docs (https://docs.ksqldb.io/en/latest/operate-and-deploy/installation/server-config/security/#configure-ksqldb-for-basic-http-authentication) no longer work since the docs use `org.eclipse.jetty.jaas.spi.PropertyFileLoginModule` which is no longer packaged with the ksqlDB server.

This is the error message that results when a user tries to authenticate according to the example in the docs:
```
[2020-05-03 13:06:19,336] ERROR Failed to log in. unable to find LoginModule class: org.eclipse.jetty.jaas.spi.PropertyFileLoginModule (io.confluent.ksql.api.auth.JaasAuthProvider:117)
```

**To Reproduce**

Follow the docs linked above on the latest `master`.

**Expected behavior**

The docs example works.

**Actual behaviour**

Authentication fails with the error message above.

**Additional context**

Unless we want to add back the dependency, we should update the documentation with how to get the jar and add it to `KSQL_CLASSPATH`, including how to do this when running the ksqlDB server via docker image. It'd be nice to do this before the 0.9.0 release.

**Comment by apurvam** [comment]
Victoria can you fix the docs?

**Comment by purplefox** [comment]
I agree, this looks like a docs issue.
