### ISSUE TITLE
Support for earliest_by_offset

### ISSUE THREAD

**Issue by MichaelDrogalis** [confluentinc/ksql#5268]
**Is your feature request related to a problem? Please describe.**

We recently introduced `latest_by_offset`. There's been a lot of demand for its twin, `earliest_by_offset`. This is particularly useful for windowing when you want to see what the opening and closing values are. This comes up in a lot of financial services use cases.

**Comment by mjsax** [comment]
@MichaelDrogalis @spena For windowing, I have some doubts if `earliest_by_offset` is useful (also actually, `latest_by_offset()` does not seems to be useful for windowing, either).

Do we really want to add it? To me it sound like as if the users want to get the earliest/latest event per timestamp within a window?

**Comment by MichaelDrogalis** [comment]
@mjsax We've had a few people who just want to grab the first and last events that constitute a window. It's worth adding since we already have `latest_by_offset`, and I know of at least a few people who have already done the grunt work of implementing it themselves.

To your point, having a variant by time would be undoubtedly useful (as described before), but by offset is already proving valuable, too.
