### ISSUE TITLE
Support User Defined Table Functions (UDTFs)

### ISSUE THREAD

**Issue by hpgrahsl** [confluentinc/ksql#527]
as very briefly discussed with @hjafarpour in the slack community:

I've seen the array column support as well as the `extractjsonfield` UDF explained in the docs which are for different use cases than the feature/enhancement I'm suggestion here: it would be great to have support for an _explode_ UDTF so that it's e.g. possible to GROUP BY the values contained in an array-like structure of a column. illustrating example below:

```
col1     col2 
1       ["a","a","b"]
2       ["b","c","c"]
3       ["a","d"]
```
when applying `SELECT col1, explode(col2) FROM ...` the expected result would be 

```
col1    col2
1       "a"
1       "a"
1       "b"
2       "b"
2       "c"
2       "c"
3       "a"
3       "d"

```

based on this you could e.g. GROUP BY col2

**Comment by k1th** [comment]
We would benefit from this as well.
Our case is a JSON structure that contains an array of n events, each having another array of m sub-events.
We would need explode this into n*m messages…

**Comment by miguno** [comment]
Thanks for the +1 @k1th.

**Comment by hpgrahsl** [comment]
@k1th thx for the comment and upvote. while your suggestion sounds interesting I guess a first version shoud probably stick to 1 level of unnesting per UDTF call. recursively 'exploding' across multiple levels might result in a very large number of rows pretty quickly based on an originally single record, which is something that needs to be carefully done - if at all.

**Comment by k1th** [comment]
If this were JSON-specific, a syntax that actually defines the flatten (or flatMap) would be handy. Then the user would have control over how many levels this would go and also be aware or the potentially massive expansion of data.
For this one would need a JSON processing library like jq, though…

**Comment by hpgrahsl** [comment]
@miguno I'm afraid EXPLODE needs to be 'compiled down' to something like flatMapValues. IMHO should be doable when UDTFs are available :)

**Comment by nalinaly** [comment]
waiting for EXLODE too,
need extract the data to multiple records

**Comment by lamerexter** [comment]
Can someone explain the status of the explode() or unnest() (POSTGRES equivalent) functionality for dealing with ARRAY types?

Has anyone found a workaround to navigate through ARRAY types (for...each) without having to use indices?

**Comment by miguno** [comment]
+1 from a KSQL user in an offline conversation

**Comment by pmacaubas** [comment]
Hello. I need to explode array in many lines, however, there is no function for this. When will the **UDFT**  be available? What prevision?

**Comment by dtheodor** [comment]
Postgres and BigQuery call this function `unnest` https://www.postgresql.org/docs/10/functions-array.html https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#unnest

Clickhouse calls it `arrayJoin` https://clickhouse.yandex/docs/en/query_language/functions/array_join/

You should stick with the majority and call it unnest. Explode is a bad term (arrayJoin is even worse).

**Comment by jaszka** [comment]
+1 is there any timeframe for this?

**Comment by osalvador** [comment]
+1 for unnest function

**Comment by bparlapalliAscend** [comment]
+1 for this

**Comment by rahulgul** [comment]
+1 for unnest function.

**Comment by rahulgul** [comment]
> +1 for this
> 
> also - would be helpful if we can explode/unnest an array of struct:
> 
> ```
> col1     col2 
> 1       [{key1:val11,key2:val12},{key1:val21,key2:val22}]
> ```
> select col1,Unnest col2 from..
> 
> expected result:
> 
> ```
> col1 col2
> 1       "{Key1:val11,key2:val12}"
> 2      "{key1:val21,key2:val22}"
> ```

+1 for this as well.

**Comment by baroni2019** [comment]
+1 for explode or unnest function.

**Comment by muirandy** [comment]
+1

We have the following structure, where we need to read each code out:
```
"items":{
          "item":[{
            "code":"someCode"
          },{
            "code":"someOtherCode"
          }]
}
```

We need to access "someCode" and "someOtherCode" (plus any others - the array size is unbounded).

**Comment by rohitshrivastava04** [comment]
Is there any progress on this issue, can we expect it anytime soon.

**Comment by anindo-bandyopadhyay** [comment]
+1 for this feature

**Comment by dunaroliver** [comment]
+1

**Comment by peoplemerge** [comment]
+1

**Comment by pavel-agarkov** [comment]
Is there any workaround for now? Any way to use EXTRACTJSONFIELD and CONCAT for later LIKE filterring?
So is there a way to convert OP example from
```
col1     col2 
1       ["a","a","b"]
2       ["b","c","c"]
3       ["a","d"]
```
to
```
col1     col2 
1       "|a|a|b|"
2       "|b|c|c|"
3       "|a|d|"
```
so it will be possible to use `where col2 like '%|a|%'`

**Comment by dhanasgit** [comment]
+1

**Comment by rmoff** [comment]
Here is a hacky workaround, using `INSERT INTO`: 

Test data: 

    kafkacat -b localhost:9092 -t test -P << EOF
    {"col1":1, "col2":      ["a","a","b"]}
    {"col1":2, "col2":      ["b","c","c"]}
    {"col1":3, "col2":      ["a","d"]}
    EOF

KSQL: 

    CREATE STREAM SOURCE (COL1 INT, COL2 ARRAY<VARCHAR>) WITH (KAFKA_TOPIC='test',VALUE_FORMAT='JSON');

    SET 'auto.offset.reset' = 'earliest';

    SELECT COL1, COL2 FROM SOURCE;

    CREATE STREAM OUTPUT AS SELECT COL1, COL2[0] AS COL2 FROM SOURCE WHERE COL2[0] IS NOT NULL;
    INSERT INTO OUTPUT      SELECT COL1, COL2[1] AS COL2 FROM SOURCE WHERE COL2[1] IS NOT NULL;
    INSERT INTO OUTPUT      SELECT COL1, COL2[2] AS COL2 FROM SOURCE WHERE COL2[2] IS NOT NULL;

Results: 

    ksql> SELECT COL1, COL2 FROM OUTPUT;
    2 | c
    3 | a
    1 | a
    2 | c
    2 | b
    1 | b
    1 | a
    3 | d

    ksql> SELECT COL1,
    >       SUM(CASE WHEN COL2='a' THEN 1 ELSE 0 END) AS A_VALUES,
    >       SUM(CASE WHEN COL2='b' THEN 1 ELSE 0 END) AS B_VALUES,
    >       SUM(CASE WHEN COL2='c' THEN 1 ELSE 0 END) AS C_VALUES,
    >       SUM(CASE WHEN COL2='d' THEN 1 ELSE 0 END) AS D_VALUES
    >  FROM OUTPUT
    >  GROUP BY COL1;
    3 | 1 | 0 | 0 | 1
    1 | 2 | 1 | 0 | 0
    2 | 0 | 1 | 2 | 0

Also written up with another example here: https://rmoff.net/post/a-poor-mans-ksql-explode-unnest-technique/

**Comment by anindo-bandyopadhyay** [comment]
@rmoff this case is valid when we know the maximum possible number of elements in array. In the example above the max allowed elements in array is 3 and this solution will work fine. But in many business cases the max elements wont be fixed. 
How we are solving this problem is listening to topic using Kafka-console-consumer and de-nesting the json using **jq** and pushing back to Kafka using kafka-console-producer to another topic for KSQL to take over. Its an additional step but currently working for us.

**Comment by rmoff** [comment]
@anindo-bandyopadhyay that sounds interesting. Any chance you could share an example of it here?

**Comment by anindo-bandyopadhyay** [comment]
Lets say following json data is produced to kafka-topic-a

```
{
    "1" : ["a","a","b"],
    "2" : ["b","c","c"],
    "3" : ["a","d"]
}
```

Below shell script will listen to kafka-topic-a, and transform the json data using jq and produce it back to kafka-topic-b

```
#!/bin/bash

kafka-console-consumer --bootstrap-server localhost:9092 --topic kafka-topic-a --group kafkta-topic-a-cruncher --from-beginning | while read -r line; do 
    echo $line | jq -c 'keys[] as $k | .[$k][] as $v | {key: $k, value: $v}' | kafka-console-producer --broker-list localhost:9092 --topic kafka-topic-b
done
```

The above script will give output like:
```
{"key":"1","value":"a"}
{"key":"1","value":"a"}
{"key":"1","value":"b"}
{"key":"2","value":"b"}
{"key":"2","value":"c"}
{"key":"2","value":"c"}
{"key":"3","value":"a"}
{"key":"3","value":"d"}
```
Now this json can be processed through KSQL easily.

**Comment by peoplemerge** [comment]
+1 +1 +1
My team is still keeping a shim in kafka-streams that just does flatmap()
Now that I'm the KSQL guru, I've spoken to two teams at my company who were considering KSQL but ultimately rejected it because this feature is missing.

**Comment by hasmizal** [comment]
+1 for this feature

**Comment by terryf82** [comment]
+1
would be very helpful in a number of situations I'm facing.

**Comment by RikJansen81** [comment]
+1

**Comment by iamyojimbo** [comment]
+3 from my team! Is this being worked on or anyone can point me in the right direction to work on a PR?

**Comment by rahulbats** [comment]
+1

**Comment by MichaelDrogalis** [comment]
Hey @iamyojimbo! We're going to try to get this one onto the queue in the next month or two -- no promises though. We realize it's a super important expression to have and want to knock it out, even though it's a bit involved.

**Comment by peoplemerge** [comment]
@MichaelDrogalis we're *thrilled* to hear it could be coming sooner than expected.  Outstanding!

**Comment by purplefox** [comment]
AIUI, the unnest() function that you will find in sql is usually used in the FROM class, not in the SELECT.

The explode() function that is being suggested here looks like it would be used in the SELECT clause.

Are we favouring an explode() that works on the SELECT rather than an unnest()?

**Comment by purplefox** [comment]
The unnest() way of doing things would be something like the following:

Let's say we have the following data (id, arr) in stream1

```
'A', [1, 4, 7, 8]
'B', [3, 2, 7]
'C', [10, 2]
```
We want to transform that into a stream with the following data:
```
'A',1
'A',4
'A',7
'A',8
'B',3
'B',2
'B',7
'C',10
'C',2
```
The unnest way of doing that would something like the following (e.g. see https://cloud.google.com/bigquery/docs/reference/standard-sql/arrays )

```
SELECT id, arr_flattened
FROM stream1
CROSS JOIN UNNEST(stream1.arr) AS arr_flattened;
```
So you basically flatten the array column into another stream/table and join that back to the original stream to fill in the other values.

Another way of getting the same result is by having an EXPLODE() function which can live in the SELECT, e.g.

```
SELECT id, EXPLODE(arr)
FROM stream1
```

This looks simple, but is kind of weird in that the EXPLODE is a vector type (a list) but the id is scalar type. In SQL, a SELECT is supposed to return a single row so this doesn't really make sense from a traditional SQL viewpoint (Which I guess is why sql implements table functions on the FROM clause).

In the latter case we would also need a heuristic to decide how we fill in the non exploded values - do we just duplicate them? What if we have more than one UDTF in the select?

**Comment by dtheodor** [comment]
You can look at how an existing system deals with functions returning more than 1 row when they are used in the SELECT list

https://www.postgresql.org/docs/11/xfunc-sql.html#XFUNC-SQL-FUNCTIONS-RETURNING-SET

> Functions returning sets can also be called in the select list of a query. For each row that the query generates by itself, the set-returning function is invoked, and an output row is generated for each element of the function's result set.

> If there is more than one set-returning function in the query's select list, [...] there is an output row using the first result from each function, then an output row using the second result, and so on. If some of the set-returning functions produce fewer outputs than others, null values are substituted for the missing data, [...].

I think that's a sensible way to model this. Both how to fill non exploded values, and how to deal with multiple such functions in the SELECT. Also there's no such limitation of having to name the same thing with two different names based on whether it's used in SELECT or FROM. A set returning function can be used either in FROM or in SELECT.

**Comment by purplefox** [comment]
It seems that allowing the UDTF function in the SELECT is Postgres specific (?) I think the SQL standard only refers to having the UDTF in the FROM clause.
In an ideal world I think it would make sense to implement this as per the SQL standard (FROM clause) and also implement it in the SELECT (as Postgres does).
From an implementation point of view, supporting this in the FROM looks it would be more difficult as it would require us to implement correlated CROSS joins.
It seems like most people on this thread seem to want the UDTF on the SELECT so in the interests of pragmatism I'm going to propose that we:
1. Initially allow a UDTF on the SELECT clause only.
2. Only allow a single UDTF per SELECT (If anyone can come up with a concrete use case showing how more than UDTF on a select would be useful, then we can consider supporting more, but this would be more work too).
We can consider UDTFs on FROM clauses at a later date if there is demand.

**Comment by purplefox** [comment]
Hi All, I have created a new GH issue to track the implementation of this feature: https://github.com/confluentinc/ksql/issues/3504

I'm going to close this issue now.

Can we please continue any discussion on the linked issue.
