### ISSUE TITLE
INSERT INTO VALUES does not allow full range of decimal values equal to zero

### ISSUE THREAD

**Issue by MichaelDrogalis** [confluentinc/ksql#5282]
**Describe the bug**

The statement `INSERT INTO VALUES` doesn't seem to work with valid decimal input.

**To Reproduce**

ksqlDB 0.8.1:

Create a stream:

```sql
CREATE STREAM s1 (
    x DECIMAL(12, 2)
) WITH (
    kafka_topic = 's1',
    partitions = 1,
    value_format='avro'
);
```

This works:

```sql
INSERT INTO s1 (x) VALUES (0);
```

But none of these do:

```sql
ksql> INSERT INTO s1 (x) VALUES (0.00);
Failed to insert values into 'S1'. Code generation failed for insert value: DECIMAL precision must be >= scale: DECIMAL(1,2). expression:0.00, schema:`ROWKEY` STRING KEY, `X` DECIMAL(12, 2)
```

```sql
ksql> INSERT INTO s1 (x) VALUES (0.0);
Failed to insert values into 'S1'. Could not serialize row: [ 0.0 ]
```

**Expected behavior**

All of the inserts should work.

**Comment by nae701** [comment]
Almog found this answer on stackoverflow that explains that BigDecimal in java "the special case that the number is equal to zero (i.e. 0.000), the precision is always 1." and was the source of this bug

**Comment by apurvam** [comment]
It looks like this has been fixed by the linked PRs. Closing this out.
