### ISSUE TITLE
INSERT INTO does not allow full range of decimal values

### ISSUE THREAD

**Issue by MichaelDrogalis** [confluentinc/ksql#5285]
**Describe the bug**

Likely related to https://github.com/confluentinc/ksql/issues/5282. The statement `INSERT INTO` doesn't seem to work with valid decimal input.

**To Reproduce**

ksqlDB 0.8.1:

Create two streams:

```sql
CREATE STREAM s1 (
    x DECIMAL(12, 2)
) WITH (
    kafka_topic = 's1',
    partitions = 1,
    value_format='avro'
);

CREATE STREAM s2 (
    x DECIMAL(12, 2)
) WITH (
    kafka_topic = 's1',
    partitions = 1,
    value_format='avro'
);
```

And run these inserts. All of them fail:

```sql
ksql> insert into s1 select 0 as x from s2 emit changes;
Incompatible schema between results and sink. Result schema is `ROWKEY` STRING KEY, `X` INTEGER, but the sink schema is `ROWKEY` STRING KEY, `X` DECIMAL(12, 2).

ksql> insert into s1 select 0.0 as x from s2 emit changes;
Incompatible schema between results and sink. Result schema is `ROWKEY` STRING KEY, `X` DECIMAL(1, 1), but the sink schema is `ROWKEY` STRING KEY, `X` DECIMAL(12, 2).

ksql> insert into s1 select 0.00 as x from s2 emit changes;
DECIMAL precision must be >= scale: DECIMAL(1,2)

ksql> insert into s1 select 1.25 as x from s2 emit changes;
Incompatible schema between results and sink. Result schema is `ROWKEY` STRING KEY, `X` DECIMAL(3, 2), but the sink schema is `ROWKEY` STRING KEY, `X` DECIMAL(12, 2).
```

**Expected behavior**

It seems like these inserts ought to work.

**Comment by MichaelDrogalis** [comment]
As another data point, this also fails in a `CASE` statement:

```sql
ksql> INSERT INTO auction_events
>    SELECT 'new_auction' AS event_kind,
>           item_name,                                                                                             
>           initial_price,
>           CASE WHEN FALSE THEN 0.00 END AS current_bid,
>           '-' AS bidder_name,
>           0 AS n_bids
>    FROM auction_items
>    EMIT CHANGES;
>
>
DECIMAL precision must be >= scale: DECIMAL(1,2)
```

**Comment by apurvam** [comment]
@spena I assume that this wasn't fixed in 0.11.0?

**Comment by agavra** [comment]
I believe @nae701 fixed this with https://github.com/confluentinc/ksql/issues/5282 though it's worthwhile to confirm the exact examples here

**Comment by nae701** [comment]
I just checked the 4 insert examples above and they are still failing even after fixing #5282

**Comment by apurvam** [comment]
Ok. This should be moved out of the milestone then cc @vcrfxia

**Comment by vcrfxia** [comment]
Ack. I haven't gone through and cleaned up the 0.11.0 milestone yet. Will do that now.

**Comment by spena** [comment]
@MichaelDrogalis The issue should be fixed for literal expressions as you mentioned in the example:
```
insert into s1 select 0 as x from s2 emit changes;
```

But how about the the schema coming from the source? say `s2.x` is an `integer`, and `s1.x` is a `decimal`. Should that be converted? It sounds like a schema evolution change, and it might confuse users. I say we shouldn't fix the below case, but what do you think?
```
insert into s1 select x from s2 emit changes;
```

**Comment by MichaelDrogalis** [comment]
An explicit cast would fix that, right? Im cool leaving that alone.

**Comment by spena** [comment]
Yes, the cast should fix  that case.
