### ISSUE TITLE
Support n-1 relationship for topics to stream/table

### ISSUE THREAD

**Issue by joewood** [confluentinc/ksql#533]
Related to #529 
It would be great to support multiple inbound topics to a single stream, or the ability to aggregate mutliple input streams into a single output stream. Right now the relationship between source topic, to stream and table is all 1:1 - meaning multiple sources of events need to be modeled as separate stovepipes of data.

**Comment by miguno** [comment]
As already said via Slack: Thanks for reporting @joewood. :)

**Comment by rmoff** [comment]
`INSERT INTO` provides the ability to do multiple streams to one output stream. 

Tracking in #708 which was raised around multiple input topics (with a wildcard) to one stream
