### ISSUE TITLE
Can't connect KSQL to CCloud - Failed to guarantee existence of topic ksql__commands

### ISSUE THREAD

**Issue by danphanley** [confluentinc/ksql#536]
I have a CCloud cluster which I can read and write to. 

I'm trying to boot a local KSQL and connect to the cluster.
```
➜  ksql git:(4.0.x) ✗ ./bin/ksql-cli local --bootstrap-server r0.kafka-mt-1.us-west-2.aws.stag.cpdev.cloud:9092 --properties-file ./ksql-cli.properties
Initializing KSQL...
io.confluent.ksql.exception.KafkaResponseGetFailedException: Failed to guarantee existence of topic ksql__commands
```
My ksql-cli.properties contains:
```
ssl.endpoint.identification.algorithm=https
sasl.mechanism=PLAIN
request.timeout.ms=20000
bootstrap.servers=SASL_SSL://r0.kafka-mt-1.us-west-2.aws.stag.cpdev.cloud:9092,r0.kafka-mt-1.us-west-2.aws.stag.cpdev.cloud:9093,r0.kafka-mt-1.us-west-2.aws.stag.cpdev.cloud:9094
retry.backoff.ms=500
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="<REMOVED>" password="<REMOVED>";
security.protocol=SASL_SSL
```
Manually creating the ksql__commands topic shifts the error to:
```
Initializing KSQL...
java.lang.IllegalStateException: No current assignment for partition ksql__commands-11
```
I suspect there is some initialisation of the cluster to create the topics KSQL requires which I can't see in the docs.

Any help gratefully recieved.

**Comment by miguno** [comment]
@danphanley : I removed the password you had included in your `ksql-cli.properties` file.

**Comment by apurvam** [comment]
Native support for ksql on cloud is coming.  But in the meantime you are on the right track. You just need to create the command topic with exactly one partition.

**Comment by danphanley** [comment]
Thanks guys

➜  ccloud topic delete ksql__commands
Topic "ksql__commands" marked for deletion.
➜  ccloud topic create --partitions 1 ksql__commands
Topic "ksql__commands" created.

And it's all good.
