### ISSUE TITLE
Something is missing on ETL Tutorial

### ISSUE THREAD

**Issue by llimacruz** [confluentinc/ksql#5383]
Hi!
I've tried the ETL Tutorial and at the final step, when you call Elastic Search API to retrieve data, the data was not returned like the tutorial shows.
When I insert new order and shipment and call Elastic API, this new order is retrieved.
So what is happenning is that the data that were inserted before the sink creation (or the shipped_orders streams) are not being captured by the sink.

Am I missing something or is there any step not mentioned in the tutorial?
What is necessary to make the sink capture those data?
Thank you!

**Comment by MichaelDrogalis** [comment]
Hey @llimacruz. Could it be that you omitted running `SET 'auto.offset.reset' = 'earliest';` at the beginning of the ksqlDB CLI session? There's a line in the tutorial for that, but it can be easy to miss.

I ran through the tutorial and it worked for me.

**Comment by llimacruz** [comment]
You nail it!
Doing all the steps again it worked as expected.
My mistake, sorry about that.
Thank you for you time.

**Comment by MichaelDrogalis** [comment]
No worries, thanks for asking!

**Comment by marceloco** [comment]
Hi Michael! I'm Leonardo's friend and coworker. I've had the same issue and I'm pretty sure I did run `SET 'auto.offset.reset' = 'earliest';`
I will run through the tutorial again and see what happens. I will try with and without cleaning-up all the installations and configurations. I will update the results here.

**Comment by marceloco** [comment]
Stranger things! 🤔 
Everything has worked perfectly now! 👏 

But I'm pretty sure that I've configured `SET 'auto.offset.reset' = 'earliest';` the first time I've gone through this very good tutorial. I do remember it because of the message it shows:

> `Successfully changed local property 'auto.offset.reset' to 'earliest'. Use the UNSET command to revert your change.`

ksqlDB rocks! 🚀

**Comment by MichaelDrogalis** [comment]
That's pretty odd. Well I'm glad you enjoyed the tutorial, keep us posted if you see any other strange behavior that we can reproduce!
