### ISSUE TITLE
Quote string keys in PRINT output

### ISSUE THREAD

**Issue by mikebin** [confluentinc/ksql#5410]
Very minor feedback - it would be helpful to quote string keys in the output to `PRINT`, to make it more obvious that it's a string field. For example, if a key is the string `"1"`, it will currently show up in the output to `PRINT` as:

`key: 1`

Someone looking at the output might mistake that as a numeric value. The following would reduce ambiguity:

`key: "1"`

**Comment by big-andy-coates** [comment]
After thinking through the implications of this change, I'm in two minds about it.

On the one hand, wrapping strings in quotes makes it really clear the key, (or value), is a string. But on the other hand, this then brings in ambiguity for users about whether the data itself contains the quotes or not. For example, if the user sees:

```
key: "1"
```

They could easily think the data itself is `"1"` and not `1`.

The CLI doesn't wrap strings in quotes either....

And the key, or value, format is also output from the PRINT command:

```
Key format: KAFKA_STRING or JSON
```

I'm going to see what others think...

**Comment by mikebin** [comment]
Good point, and I'm fine with whatever you decide. Thanks for taking a look!

**Comment by big-andy-coates** [comment]
I'm going to err on the side of not changing things I think.  Thanks for reporting.
