### ISSUE TITLE
`select-push-query.md` has docs for weird subset of SQL functionality

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#5428]
`select-push-query.md` has docs for `CAST`, `CASE`, `LIKE` and `BETWEEN`, yet these are not unique to push queries. They are just part of our SQL syntax, can be used in persistent queries too, and IMHO should just be part of our syntax reference.  Yet I'm struggling to find any other documentation for them outside of this page.

I suggest we move these sections into our syntax reference.

To a lesser extent the docs around `WINDOW` clause also shouldn't just be here. `create-table-as-select.md` also supports the `WINDOW` clause, so maybe the details of windowing clauses should be in a common place and each of these places should link to this shared doc?   We could even have the link in the synopsis at the top...

**Comment by JimGalasyn** [comment]
This is also the case for JOIN and PARTITION BY, which should also have mentions in the syntax reference.

**Comment by big-andy-coates** [comment]
Yup!

**Comment by JimGalasyn** [comment]
These have been moved to https://docs.ksqldb.io/en/latest/developer-guide/ksqldb-reference/quick-reference/.
