### ISSUE TITLE
partition by can't reference aliased columns

### ISSUE THREAD

**Issue by MichaelDrogalis** [confluentinc/ksql#5487]
**Describe the bug**

In the past, ksqlDB allowed you to partition by computed column value aliases, as seen in our [Cook Book.](https://www.confluent.io/stream-processing-cookbook/ksql-recipes/creating-composite-key/) But this doesn't seem to be allowed now.

**To Reproduce**

With ksqlDB 0.9.0.

Set to earliest:

```sql
SET 'auto.offset.reset' = 'earliest';
```

Create a stream:

```sql
CREATE STREAM s1 (
    k VARCHAR,
    v1 INT,
    v2 VARCHAR,
    v3 BOOLEAN
) WITH (
    kafka_topic = 's1',
    partitions = 1,
    value_format = 'avro',
    key = 'k'
);
```

Add some records:

```sql
INSERT INTO s1 (
    k, v1, v2, v3
) VALUES (
    'k1', 0, 'a', true
);

INSERT INTO s1 (
    k, v1, v2, v3
) VALUES (
    'k2', 1, 'b', false
);

INSERT INTO s1 (
    k, v1, v2, v3
) VALUES (
    'k1', 2, 'c', false
);

INSERT INTO s1 (
    k, v1, v2, v3
) VALUES (
    'k3', 3, 'd', true
);

INSERT INTO s1 (
    k, v1, v2, v3
) VALUES (
    'k2', 4, 'e', true
);
```

And select:

```sql
SELECT *, CAST(v1 AS VARCHAR) AS x1
FROM s1
PARTITION BY x1
EMIT CHANGES;
```

This statement fails with:

```
Line: 1, Col: 58: PARTITION BY column 'S1.X1' cannot be resolved.
```

But seems that it should be permissible.

**Comment by MichaelDrogalis** [comment]
Closing since this was intentional. See https://github.com/confluentinc/ksql/issues/2701

Will update the docs to reflect the behavior.

**Comment by entechlog** [comment]
@MichaelDrogalis , Did we update the documentation already ? If yes can you share the link ? I do not see the update yet .

**Comment by MichaelDrogalis** [comment]
I haven't gotten around to it yet. The short answer is that `partition by` intentionally only works on the schema of the incoming row, not the outgoing one (which is what an `AS` would pick up). You can just create a second stream and partition by whatever was computed and stored under `AS`. Does that make sense?

**Comment by wlaforest** [comment]
I find this to be non-intuitive as partition by is defining how to partition the new stream.  We should allow someone to use the fields in the newly created stream even if its not the same behavior as group by (which correctly matches standard SQL behavior and only allows for incoming fields.  See newly created related ticket of https://github.com/confluentinc/ksql/issues/7998

**Comment by MichaelDrogalis** [comment]
Thanks @wlaforest. Indeed, we've gone back and forth over the last year about whether this was the right decision. I'll look at the other ticket.
