### ISSUE TITLE
Add array_sort function

### ISSUE THREAD

**Issue by derekjn** [confluentinc/ksql#5490]
`array_sort(arr)` - Returns a sorted copy of the input array

**Comment by apurvam** [comment]
Thanks for self assigning @blueedgenick . We hope to cut the 0.10.0 release by 3 June, so ideally these patches land by then to make it into that release.

**Comment by blueedgenick** [comment]
Thanks for the reminder - hopefully shouldn't be a problem, was already
discussing a couple of these with Derek before the ticket was filed so a
chunk of work already done.
