### ISSUE TITLE
Add string_encode function

### ISSUE THREAD

**Issue by derekjn** [confluentinc/ksql#5493]
`string_encode(s, input_encoding, output_encoding)` - Takes an input string `s`, which is encoded as `input_encoding`, and encodes it as `output_encoding`. For example,
- `string_encode(s, 'hex', 'utf-8')` - Converts a hex string to UTF-8.
- `string_encode(s, 'utf-8', 'hex')` - Converts a UTF-8 string to hex.

**Comment by apurvam** [comment]
what encodings would we want to support here?

**Comment by derekjn** [comment]
I think these probably make the most sense to start:
- `hex`
- `utf-8`
- `base64`
- `ascii`
