### ISSUE TITLE
ROWKEY=null, while should be a value

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [confluentinc/ksql#5539]
**Describe the bug**
I'm creating a stream with 
```
CREATE STREAM S_USERS32
(id VARCHAR,
   name VARCHAR,
   country VARCHAR)
WITH (KAFKA_TOPIC='users3',VALUE_FORMAT='JSON', KEY='id');
```
it gets created. but when i query it with 
```
select * from S_USERS32 EMIT CHANGES;
```
i get ROWKEY=null while actual `id` field is correct. 
screenshot: http://joxi.ru/L21lbV3TgQwdNm

**To Reproduce**
Steps to reproduce the behavior, include:
1. ksql-server: docker image `confluentinc/cp-ksql-server:5.4.0`
2. Sample source data
{
            "id": "1",
            'name': "Bob" ,
            "country": "Thailand"
        }

**Expected behavior**
ROWKEY to be the same as `id`

**Comment by PeterLindner** [comment]
`WITH(KEY='id')` does not set the key, it's just an optimization hint for ksqldb that the key of the topic is the same as the given field in the value so that ksqldb does not need to repartition the topic...
As far as I know this was removed recently, see #3537

**Comment by big-andy-coates** [comment]
Yes, it was removed recently.

Getting `KEY='id'` will not change the data in the topic.  So if the data in the topic has a null key, then so will the data returned by your select statement.

This functionality has now been removed, (as it was causing confusion!), so closing the ticket.
