### ISSUE TITLE
Question - Kafka stream and joins 

### ISSUE THREAD

**Issue by anupkumarsharma** [confluentinc/ksql#555]
I have a legacy SQL Server query which curates, enrich, formats the data. I am trying to push data to Kafka and implement the SQL query in Kafka streams. In this stored procedure we join with several different dimension(SCD) tables.
I guess we need to create Stream for the fact and some kind of table cache for all the SCDs and some kind of periodic refresh for the SCDs.Thoughts?

**Comment by miguno** [comment]
- In KSQL/Kafka you'd create a stream and several tables, which you'd then join against the stream; i.e., a sequence of stream-table joins.
- Regarding your existing data: Kafka Connect would be used to continuously ingest (aka streaming-ingest) the tables' data from wherever it is today into Kafka, from which it would then be read into KSQL tables.
