### ISSUE TITLE
Schema inference for tables

### ISSUE THREAD

**Issue by rodesai** [confluentinc/ksql#557]
When using an avro schema with a table, I cannot use schema inference because ksql cannot recognize the key field:

```
ksql> CREATE TABLE users_original WITH (kafka_topic='users', value_format='AVRO', key = 'userid');
No column with the provided key column name in the WITH clause, USERID, exists in the defined schema.
ksql>
```

The server should be able to reference the key field against the registered schema for avro formatted topics.

**Comment by apurvam** [comment]
Fixed by #562
