### ISSUE TITLE
Table WINDOW RETENTION not enforced

### ISSUE THREAD

**Issue by harlev** [confluentinc/ksql#5605]
On a table with `WINDOW` and `RETENTION` settings, windows are kept long after expiration (possibly never deleted)

**To Reproduce**
1. ksqlDB 0.9.0
2. Create a table with (for example) `WINDOW TUMBLING ( SIZE 1 MINUTES , RETENTION 3 MINUTES , GRACE PERIOD 10 SECONDS )`
3. Insert some data with current `ROWTIME`
4. Wait for the retention period to pass (or even hours or a day later)
5. Query to see window with data is still showing in the table.

**Expected behavior**
Expired windows should be deleted after a reasonable time period

**Actual behaviour**
Querying shows a day old window still exists in table

**Comment by big-andy-coates** [comment]
Hi @harlev, 

Just to be clear... can you provide the exact statements you're running, especially for step 5.

Thanks,

Andy

**Comment by harlev** [comment]
@big-andy-coates 

1. `CREATE STREAM my_stream (a INT, b INT) WITH (KAFKA_TOPIC='s1', VALUE_FORMAT='JSON', PARTITIONS=1);`
2. `CREATE TABLE MY_W_TABLE AS SELECT a,count(*) FROM MY_STREAM WINDOW TUMBLING ( SIZE 5 SECONDS , RETENTION 30 SECONDS, GRACE PERIOD 1 SECOND) group by a  EMIT CHANGES;`
3. `INSERT INTO my_stream (rowkey,a, b) VALUES ('abc', 3 , 2); `
4. `SELECT * FROM MY_W_TABLE EMIT CHANGES;`
How long after, should I expect step 4 to return results?

**Comment by agavra** [comment]
might be related to #5554

**Comment by agavra** [comment]
also cc @vinothchandar who worked on the initial retention feature

**Comment by vcrfxia** [comment]
Hey @harlev , thanks for reporting this! I've just merged a patch to master, which means the issue will be fixed in ksqlDB 0.11.0.
