### ISSUE TITLE
Update Avro docs for tables because of issue 557

### ISSUE THREAD

**Issue by miguno** [confluentinc/ksql#561]
The current docs for upcoming 0.3 do not yet describe correctly how to use TABLEs with Avro because of https://github.com/confluentinc/ksql/issues/557.  The current docs do not inform the user that, for TABLEs, you must right now still explicitly define columns and types because of #557.

Docs that seem to be affected by this include but might not be limited to:

- Examples, e.g. CREATE TABLE statements under https://github.com/confluentinc/ksql/blob/master/docs/examples.md#avro
- Syntax Ref guide (https://github.com/confluentinc/ksql/blob/master/docs/syntax-reference.md#ksql-statements), where the CT and CTAS statements.

Also, we should update the Syntax Ref guide anyways w.r.t. Avro support for CS, CT, CSAS, CTAS statements to highlight that, for Avro data, you don't even need to specify the columns (this is clear in the Examples document which has its own Avro section, but it is NOT clear in the Syntax Guide).  Of course, https://github.com/confluentinc/ksql/issues/557 currently does prevent you from omitting columns when creating tables, so we need to account for this in the first iteration of fixing the docs until the root issue is resolved.  (This could be a separate GH ticket but this and the above are so much related that I think we should fix this in one swing.)

**Comment by miguno** [comment]
It is possible that the PR https://github.com/confluentinc/ksql/pull/562 fixes the root cause, and that the issue raised here *might* not be applicable any longer.

**Comment by apurvam** [comment]
Addressed by #562
