### ISSUE TITLE
Accessing ROWTIME in join query returns unexpected results

### ISSUE THREAD

**Issue by mikebin** [confluentinc/ksql#5610]
**Describe the bug**
When executing a stream-table join in ksqlDB which returns the individual `ROWTIME` values for the stream and table in the output, the same timestamp is returned for both, even if they're actually different. Querying the stream and table separately return the correct (different) individual timestamps.

**To Reproduce**
Versions tested: ksqlDB 5.5.0, 0.9.0 (statements below from 0.9.0)

```sql
create stream s (id varchar) with (kafka_topic='s', value_format='json', partitions=1);

create table t (rowkey varchar primary key, id varchar) with (kafka_topic='t', value_format='json', partitions=1);

--Note the different timestamps being inserted for the stream and table
insert into t (rowtime, rowkey, id) values (1591910797965, 'key1', 'tableid1');
insert into s (rowtime, id) values (1591910814678, 'key1');

--Returns the same value for table_time and stream_time (the timestamp from the stream)
select TIMESTAMPTOSTRING(T.ROWTIME, 'yyyy-MM-dd HH:mm:ss') as table_time, TIMESTAMPTOSTRING(S.ROWTIME, 'yyyy-MM-dd HH:mm:ss') as stream_time, s.id, t.id from s left join t on (s.id = t.rowkey) emit changes;
```

**Expected behavior**
`table_time` and `stream_time` have separate values (`2020-06-11 21:26:37` and `2020-06-11 21:26:54`, respectively.

**Actual behaviour**
Same value returned for both timestamps:
```
+--------------------------------+--------------------------------+--------------------------------+--------------------------------+
|TABLE_TIME                      |STREAM_TIME                     |S_ID                            |T_ID                            |
+--------------------------------+--------------------------------+--------------------------------+--------------------------------+
|2020-06-11 21:26:54             |2020-06-11 21:26:54             |key1                            |tableid1                        |
```

**Additional context**
Separate timestamps are returned as expected in KSQL 5.4.1

Could this be related to making `ROWTIME` a pseudo-column? https://github.com/confluentinc/ksql/pull/5150

**Comment by apurvam** [comment]
@big-andy-coates  can you help take a look?

**Comment by big-andy-coates** [comment]
This is a known issue: https://github.com/confluentinc/ksql/issues/4131

Thanks for reporting @mikebin. Closing as a duplicate.
