### ISSUE TITLE
ksql client cannot render the Postgres Decimal Data from Kafka which was serialized by debezium in AVO format

### ISSUE THREAD

**Issue by amit-wakade** [confluentinc/ksql#5612]
ksql client cannot render the PostgreSQL Decimal Data from Kafka which was serialized by debezium in AVO format

**To Reproduce**
Steps to reproduce the behavior, include:
1. The version of KSQL from Confluenct 5.5.0
2. Decimal Data from Postgress with Debezium Source Connector 
3. SQL statements - select after->"GROSS_UNITS"->"SCALE", after->"GROSS_UNITS"->"VALUE" from REQUESTS_STREAM EMIT CHANGES;

**Expected behavior**
Ideally the value of the decimal field should be shown 

**Actual behaviour**
A clear and concise description of what actually happens, including:
1. CLI output
line 2:1: extraneous input ';' expecting {<EOF>, 'SELECT', 'CREATE', 'INSERT', 'DESCRIBE', 'PRINT', 'EXPLAIN', 'SHOW', 'LIST', 'TERMINATE', 'DROP', 'SET', 'UNSET', 'RUN'}
Statement: select after->"GROSS_UNITS"->"SCALE", after->"GROSS_UNITS"->"VALUE" from REQUESTS_STREAM EMIT CHANGES;
;
Caused by: line 2:1: extraneous input ';' expecting {<EOF>, 'SELECT', 'CREATE',
	'INSERT', 'DESCRIBE', 'PRINT', 'EXPLAIN', 'SHOW', 'LIST', 'TERMINATE', 'DROP',
	'SET', 'UNSET', 'RUN'}
2. Error messages
line 2:1: **extraneous input '**;' expecting {<EOF>, 'SELECT', 'CREATE', 'INSERT', 'DESCRIBE', 'PRINT', 'EXPLAIN', 'SHOW', 'LIST', 'TERMINATE', 'DROP', 'SET', 'UNSET', 'RUN'}
Statement: select after->"GROSS_UNITS"->"SCALE", after->"GROSS_UNITS"->"VALUE" from REQUESTS_STREAM EMIT CHANGES;
;
Caused by: line 2:1: extraneous input ';' expecting {<EOF>, 'SELECT', 'CREATE',
	'INSERT', 'DESCRIBE', 'PRINT', 'EXPLAIN', 'SHOW', 'LIST', 'TERMINATE', 'DROP',
	'SET', 'UNSET', 'RUN'}

3. KSQL logs

**Additional context**

Basically, issue is we are using Debezium Postgres Source connector from confluent hub and we are using AVRO schema for the Postgres table source data and one of the decimal value from postgress is coming in kafka avro as "gross_units": {"scale": 4, "value": "\u0001"}
when I looked up into schema registry it is like below
{
              "name": "gross_units",
              "type": [
                "null",
                {
                  "type": "record",
                  "name": "VariableScaleDecimal",
                  "namespace": "io.debezium.data",
                  "fields": [
                    {
                      "name": "scale",
                      "type": "int"
                    },
                    {
                      "name": "value",
                      "type": "bytes"
                    }
                  ],
                  "connect.doc": "Variable scaled decimal",
                  "connect.version": 1,
                  "connect.name": "io.debezium.data.VariableScaleDecimal"
                }
              ],
              "doc": "Variable scaled decimal",
              "default": null
            }, 

After conversion the data lands up in AWS MSK Apache kafka node as below
the excrept of PRINT topic is as below
 {"before": null, "after": {"id": 27, "status": 12, "type": 1, "user_id": 372, "gross_units": {"scale": 2, "value": "\u0002"}, .......
Issue is when we are trying to read the decimal values from stream it returns only one part of the structure, that is  {"scale": 2} .
I tried to explicitly address the value using structure->value operator I got an error is value is not found

**Comment by big-andy-coates** [comment]
As ksqlDB does not yet have a BYTES sql type it can't import the `value` field of the `gross_units` column.  

It should happily import the `scale` field for you - though its not much use on its own!

The reason you're getting an error with this selecT:

```sql
select after->"GROSS_UNITS"->"SCALE", after->"GROSS_UNITS"->"VALUE" from REQUESTS_STREAM EMIT CHANGES;
```

Is because you're using double quotes around the column names. One of these should work:

```sql
select after->GROSS_UNITS->SCALE from REQUESTS_STREAM EMIT CHANGES;

-- or -- 

select after->`gross_units`->`scale` from REQUESTS_STREAM EMIT CHANGES;
```


Looking at the docs for the connector: https://debezium.io/documentation/reference/1.1/connectors/postgresql.html

I can see there is a `decimal.handling.mode` setting.  At its default value of `precise` it looks like it will output an Avro decimal in a format that ksqlDB would recognise _unless_ the the source `NUMERIC` or `DECIMAL` types are used without any scale. At which point you end up with the `STRUCT` data structure you're encountering.

> There is an exception to this rule. When the NUMERIC or DECIMAL types are used without any scale constraints then it means that the values coming from the database have a different (variable) scale for each value. In this case a type io.debezium.data.VariableScaleDecimal is used and it contains both value and scale of the transferred value.
