### ISSUE TITLE
Embedded Connect group.id is `connect-<query name>` instead of defined parameter

### ISSUE THREAD

**Issue by deuscapturus** [confluentinc/ksql#5635]
**Describe the bug**

For a ksql cluster I have set:

`KSQL_CONNECT_GROUP_ID="_exp_learner_search-kafka-connect-stackexchangeposts_v1"`

However, the group.id used by the embedded kafka-connect for a connector is instead `connect-STACK_EXCHANGE_POSTS_TO_S3_V1`

"STACK_EXCHANGE_POSTS_TO_S3_V1" is the name of my SINK CONNECTOR

```
CREATE SINK CONNECTOR STACK_EXCHANGE_POSTS_TO_S3_V1 WITH()
```

This is dangerous as it is easy to have namespace collisions on group ids if they are based on the query name.

**To Reproduce**

ksql Versions:

confluentinc/cp-ksql-server:5.4.2 and confluentinc/ksqldb-server:0.9.0

**Expected behavior**

kafka-connect should respect the group.id configuration set by the environment variable.

**Comment by agavra** [comment]
These are two different group IDs; one of them (`_exp_learner_search...`) is the group ID for the connect cluster. All clusters that share this ID will create the same source/sink connectors and share tasks across them and read from the same .

On the other hand, `connect-STACK_EXCHANGE_POSTS_TO_S3_V1` is the ID for the sink connector specifically, which indicates where in the underlying topic it has read from.

See the documentation for connect about `group.id`: https://docs.confluent.io/current/connect/references/allconfigs.html#distributed-worker-configuration

**Comment by deuscapturus** [comment]
Thank you.  This does clear things up.  But I still worry about name collisions on consumer groups.  I wish there was a sink consumer group id prefix parameter.  We have separate teams creating connectors with names like "s3-sink".  It is not obvious to anyone that those names need to be unique and identifiable.

**Comment by agavra** [comment]
@deuscapturus that's definitely an interesting point, connect was probably designed to have one large cluster instead of many smaller ones (which is they usage ksqlDB encourages). It might be worth opening an apache kafka ticket suggesting a configuration that allows changing the sink connector prefix.

Since this is mostly a connect related change, I'm going to close out this ticket - but feel free to ask any questions that you may still have.
