### ISSUE TITLE
GEO_DISTANCE Function does not support predicate less than 0.1

### ISSUE THREAD

**Issue by wmcred** [confluentinc/ksql#5636]
**Describe the bug**
The GEO_DISTANCE functions returns a large decimal precision but when in a predicate clause you do a comparison on the return with more than one decimal it will not work when the value is (0.0x), for example 0.02.

**To Reproduce**
Steps to reproduce the behavior, include:
1. The version of KSQL. 5.5.0
2. Sample source data. GEO_DISTANCE(39.18660374, -76.73262144, 39.18660374, -76.73222145 ) 
3. Any SQL statements you ran
ksql> select GEO_DISTANCE(39.18660374, -76.73262144, 39.18660374, -76.73222145 ) from circle 
>  where GEO_DISTANCE(39.18660374, -76.73262144, 39.18660374, -76.73222145 ) < 0.04 emit changes;

**Expected behavior**
I would expect the comparison to be supported and work just like it does for  < 1.04

**Actual behaviour**
A clear and concise description of what actually happens, including:
1. CLI output
Code generation failed for Predicate: DECIMAL precision must be >= scale: DECIMAL(1,2). expression:(GEO_DISTANCE(39.18660374, -76.73262144, 39.18660374, -76.73222145) < 0.04), schema:`ROWKEY` STRING KEY, `TYPE` STRING, `PROP` STRUCT<`NAME` STRING, `DESCRIPTION` STRING>, `GEOMETRY` STRUCT<`TYPE` STRING, `COORDINATES` ARRAY<ARRAY<ARRAY<DOUBLE>>>, `RADIUS` DOUBLE>, `ID` STRING, `ROWTIME` BIGINT, `ROWKEY` STRING
ksql> \
2. Error messages
Code generation failed for Predicate: DECIMAL precision must be >= scale: DECIMAL(1,2). expression:(GEO_DISTANCE(39.18660374, -76.73262144, 39.18660374, -76.73222145) < 0.04), schema:`ROWKEY` STRING KEY, `TYPE` STRING, `PROP` STRUCT<`NAME` STRING, `DESCRIPTION` STRING>, `GEOMETRY` STRUCT<`TYPE` STRING, `COORDINATES` ARRAY<ARRAY<ARRAY<DOUBLE>>>, `RADIUS` DOUBLE>, `ID` STRING, `ROWTIME` BIGINT, `ROWKEY` STRING
ksql> \
3. KSQL logs
I could not find any log info

**Additional context**

**Comment by fractal** [comment]
I can confirm this is an issue. Locations in UK are particularly affected :)

**Comment by big-andy-coates** [comment]
This looks to be a bug relating to the conversion / coercion between decimals and doubles.

This is already fixed in the master branch, and in the soon to be released v0.10 ksqlDB release. v0.10 of ksqlDB will also be included in CP v6.0.0
