### ISSUE TITLE
LATEST_BY_OFFSET and EARLIEST_BY_OFFSET do not support Decimal

### ISSUE THREAD

**Issue by vcrfxia** [confluentinc/ksql#5657]
The current implementations of the `LATEST_BY_OFFSET` and `EARLIEST_BY_OFFSET` built-in aggregation functions do not support Decimal data types. It'd be useful for them to do so.

**Comment by big-andy-coates** [comment]
Closing as a duplicate of https://github.com/confluentinc/ksql/issues/5437

**Comment by aabrams** [comment]
Perhaps support for DECIMAL could be added quickly, with the other more complicated data structures delayed for UDAF improvements?
