### ISSUE TITLE
Support hard-deletes against Schema Registry

### ISSUE THREAD

**Issue by MichaelDrogalis** [confluentinc/ksql#5714]
**Is your feature request related to a problem? Please describe.**

When you run a push query using Schema Registry, a schema is created each time and deleted at the end of execution. But right now, Schema Registry defaults to soft-deletes. This is a problem when you want to be careful about the number of schemas you're keeping around.

Schema Registry also supports hard-deletes as a request parameter. It seems like we should use these for push queries to prevent people from retaining too many schemas.

**Comment by stevenpyzhang** [comment]
@MichaelDrogalis I don't think this is currently possible for us to do easily as there's no SR client support for this. Hard deletes are triggered by adding a URL parameter to the request being sent https://docs.confluent.io/current/schema-registry/schema-deletion-guidelines.html#hard-delete-a-schema

I've filed a JIRA to track this (DG-616)

**Comment by apurvam** [comment]
I believe the schema registry client now enables hard deletes, so we should be unblocked here.
