### ISSUE TITLE
mismatched input 'JOIN' expecting '

### ISSUE THREAD

**Issue by xhx1304** [confluentinc/ksql#5716]
CREATE TABLE archive_info AS 
 SELECT arc.id,arc.business_id,arc.cover_image,arc.title,arc.org_id,arc.status,arc.year,arc.business_type,arc.create_date,arc.operate_date,arc.order,arc.file,array_remove(array_agg(al.name), NULL) as label,array_remove(array_agg(ac.name),NULL) as category
 FROM archive arc JOIN archive_category_relation acr ON arc.id = acr.archive_id 
 JOIN archive_category ac ON acr.archive_id = ac.id 
 JOIN archive_label_relation alr ON arc.id = alr.archive_id 
 JOIN archive_label al ON alr.lable_id = al.id
 GROUP BY arc.id,arc.business_id,arc.cover_image,arc.title,arc.org_id,arc.status,arc.year,arc.business_type,arc.create_date,arc.operate_date,
arc.order,arc.file
WITH (KAFKA_TOPIC = 'arc.archive.archive_info',VALUE_FORMAT = 'JSON',KEY = 'id');

Caused by: line 3:81: mismatched input 'JOIN' expecting ';'
Caused by: org.antlr.v4.runtime.InputMismatchException

**Comment by xhx1304** [comment]
ksql server v5.4.1

**Comment by agavra** [comment]
Hello @xhx1304 - ksql v5.4.1 does not include n-way joins (you could only specify a maximum of one join). I believe 5.5.x has this feature, and if not then 6.0.x will definitely have it. If you're using open source versions I believe it was available in 0.9. Feel free to re-open if this doesn't answer your question.
