### ISSUE TITLE
mismatched input 'WITH' expecting ';'

### ISSUE THREAD

**Issue by xhx1304** [confluentinc/ksql#5717]
CREATE TABLE archive_info AS 
 SELECT arc.id,
 arc.business_id,
 arc.cover_image,
 arc.title,
 arc.org_id,
 arc.status,
 arc.year,
 arc.business_type,
 arc.create_date,
 arc.operate_date,
 arc.order,
 arc.file,
 array_remove(array_agg(al.name), NULL) as label,
 array_remove(array_agg(ac.name),NULL) as category
 FROM archive arc LEFT JOIN archive_category_relation acr ON arc.id = acr.archive_id
 LEFT JOIN archive_category ac ON acr.category_id = ac.id
 LEFT JOIN archive_label_relation alr ON arc.id = alr.archive_id
 LEFT JOIN archive_label al ON alr.lable_id = al.id
 GROUP BY arc.id,
 arc.business_id,
 arc.cover_image,
 arc.title,
 arc.org_id,
 arc.status,
 arc.year,
 arc.business_type,
 arc.create_date,
 arc.operate_date,
 arc.order,arc.file
WITH (KAFKA_TOPIC = 'arc.archive.archive_info',VALUE_FORMAT = 'JSON');

**Comment by agavra** [comment]
Please see the documentation for `CREATE TABLE AS SELECT` (https://docs.ksqldb.io/en/latest/developer-guide/ksqldb-reference/create-table-as-select/), the `WITH` clause should come before the `AS SELECT`. Feel free to re-open this ticket if that did not answer your question.
