### ISSUE TITLE
Can't find any functions with the name 'ARRAY_AGG'

### ISSUE THREAD

**Issue by xhx1304** [confluentinc/ksql#5718]
does ksql support 'ARRAY_AGG' or 'STRING_AGG' like postgresql

**Comment by vcrfxia** [comment]
Hi @xhx1304 , the equivalent of ARRAY_AGG in postgresql in ksqlDB is `COLLECT_LIST`: https://docs.ksqldb.io/en/latest/developer-guide/ksqldb-reference/aggregate-functions/#collect_list

ksqlDB does not have a built-in STRING_AGG equivalent but you can achieve the behavior by combining `COLLECT_LIST` and `ARRAY_JOIN`: https://docs.ksqldb.io/en/latest/developer-guide/ksqldb-reference/scalar-functions/#array_join
