### ISSUE TITLE
Missing aggregated columns when using a GROUP BY 

### ISSUE THREAD

**Issue by marghidanu** [confluentinc/ksql#5719]
**Describe the bug**
Missing aggregated columns when using a GROUP BY clause on a CREATE TABLE SELECT

**To Reproduce**
Using ksqlDb version is 0.10.0

I have a stream containing columns: a, b, c, d

```
CREATE TABLE myTable WITH (VALUE_FORMAT='JSON') AS
SELECT
    a AS GROUP, 
    b AS NAME
    SUM(c) AS Total,
    MAX(d) AS LastDate
    WindowStart as WS
FROM myStream
WINDOW TUMBLING(SIZE 10 MINUTES)
GROUP BY a, b
EMIT CHANGES;
```

The **GROUP** and **NAME** columns do not appear in the corresponding topic for the table.

**Expected behavior**

The column names should be present

**Comment by apurvam** [comment]
they do exist in the key as a concatened string though? I guess the expectation is that they should occur in the key _and_ value?

**Comment by apurvam** [comment]
We will update our docs and changelog. But you need to use the `AS_VALUE` UDF to copy the key into the value. See here for an example: https://github.com/confluentinc/ksql/blob/master/ksqldb-functional-tests/src/test/resources/query-validation-tests/group-by.json#L931

**Comment by big-andy-coates** [comment]
Yep, this is expected behaviour.  The aggregate columns `a` and `b` do exist in the Kafka topic. However, they are now in the record key, not the value.
