### ISSUE TITLE
CREATE STREAM should support column names starting with @ when reading from JSON

### ISSUE THREAD

**Issue by my2ndhead** [confluentinc/ksql#572]
Some json documents may contain elements starting with a @-character. 

Example query:

`CREATE STREAM filebeat_original (@timestamp VARCHAR, message VARCHAR) with (kafka_topic='filebeat', value_format='JSON');`

Example json:

`{
	"@timestamp": "2017-12-19T15:37:55.184Z",
	"@metadata": {
		"beat": "filebeat",
		"type": "doc",
		"version": "6.1.0",
		"topic": "filebeat"
	},
	"offset": 14619691,
	"message": "Dec 19 16:37:54 www kernel:  ...snip...",
	"source": "/var/log/messages",
	"prospector": {
		"type": "log"
	},
	"beat": {
		"name": "www",
		"hostname": "www",
		"version": "6.1.0"
	}
}`

ksql should support the @ character in column names, allow substitution characters or renaming columns on-the-fly.

**Comment by hjafarpour** [comment]
@my2ndhead I pushed a fix for handling fields with `@` prefix. Please try the latest version from master branch and let us know if you find any issues.
