### ISSUE TITLE
when is the KSQL stable release planned?

### ISSUE THREAD

**Issue by selvakumarEsra** [confluentinc/ksql#573]

**Comment by hjafarpour** [comment]
Very soon hopefully! We have planned it for Q1 of 2018.

**Comment by selvakumarEsra** [comment]
thanks looking forward to it

**Comment by ror6ax** [comment]
+1

**Comment by apurvam** [comment]
We plan to release the GA version of KSQL at the end of March 2018. Closing this for now.
