### ISSUE TITLE
UDAFs do not respect the Configurable interface

### ISSUE THREAD

**Issue by MichaelDrogalis** [confluentinc/ksql#5738]
**Describe the bug**

Version: 0.10.0, related to #5737 

[The docs](https://docs.ksqldb.io/en/latest/concepts/functions/#configurable-udf) describe that a UDF can be made configurable with external parameters by implementing the `Configurable` interface. This works as described for scalar functions. But it doesn't work for UDAFs. The `configure()` method is silently ignored. This might be a bit worse than #5737 because UDAF factories expect to return a `Udaf` or `TableUdaf`. Because Java doesn't support type unions, we might need to jump through some hoops to get ksqlDB to realize which UDAFs are configurable and which are not.

Either way, this behavior should also function for UDAFs.

**Comment by purplefox** [comment]
Please see comment on https://github.com/confluentinc/ksql/issues/5737
