### ISSUE TITLE
docker-compose get ksqldb fail

### ISSUE THREAD

**Issue by wangbf** [confluentinc/ksql#5759]
I use docker-compose get ksqldb, follow the doc. 
Here is my  docker-compose.yml :

---
version: '2'

services:
  ksqldb-server:
    image: confluentinc/ksqldb-server:0.10.0
    hostname: ksqldb-server
    container_name: ksqldb-server
    ports:
      - "8088:8088"
    environment:
      KSQL_LISTENERS: http://0.0.0.0:8088
      KSQL_BOOTSTRAP_SERVERS: <broker endpoint>
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"

  ksqldb-cli:
    image: confluentinc/ksqldb-cli:0.10.0
    container_name: ksqldb-cli
    depends_on:
      - ksqldb-server
    entrypoint: /bin/sh
    tty: true

then, run  docker-compose up，I get this error blow:

ksqldb-server    | [2020-07-02 08:58:36,110] ERROR Error during restore (io.confluent.ksql.rest.server.computation.CommandRunner:202)
ksqldb-server    | java.lang.NullPointerException
ksqldb-server    | 	at org.apache.kafka.clients.consumer.internals.Fetcher.prepareFetchRequests(Fetcher.java:1113)
ksqldb-server    | 	at org.apache.kafka.clients.consumer.internals.Fetcher.sendFetches(Fetcher.java:246)
ksqldb-server    | 	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1284)
ksqldb-server    | 	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1236)
ksqldb-server    | 	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1204)
ksqldb-server    | 	at io.confluent.ksql.rest.server.CommandTopic.getRestoreCommands(CommandTopic.java:88)
ksqldb-server    | 	at io.confluent.ksql.rest.server.computation.CommandStore.getRestoreCommands(CommandStore.java:211)
ksqldb-server    | 	at io.confluent.ksql.rest.server.computation.CommandRunner.processPriorCommands(CommandRunner.java:164)
ksqldb-server    | 	at io.confluent.ksql.rest.server.KsqlRestApplication.initialize(KsqlRestApplication.java:419)
ksqldb-server    | 	at io.confluent.ksql.rest.server.KsqlRestApplication.startKsql(KsqlRestApplication.java:349)
ksqldb-server    | 	at io.confluent.ksql.rest.server.KsqlRestApplication.startAsync(KsqlRestApplication.java:332)
ksqldb-server    | 	at io.confluent.ksql.rest.server.KsqlServerMain.tryStartApp(KsqlServerMain.java:72)
ksqldb-server    | 	at io.confluent.ksql.rest.server.KsqlServerMain.main(KsqlServerMain.java:58)
ksqldb-server    | [2020-07-02 08:58:36,112] ERROR Unhandled exception in server startup (io.confluent.ksql.rest.server.KsqlServerMain:76)
ksqldb-server    | java.lang.NullPointerException
ksqldb-server    | 	at org.apache.kafka.clients.consumer.internals.Fetcher.prepareFetchRequests(Fetcher.java:1113)
ksqldb-server    | 	at org.apache.kafka.clients.consumer.internals.Fetcher.sendFetches(Fetcher.java:246)
ksqldb-server    | 	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1284)
ksqldb-server    | 	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1236)
ksqldb-server    | 	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1204)
ksqldb-server    | 	at io.confluent.ksql.rest.server.CommandTopic.getRestoreCommands(CommandTopic.java:88)
ksqldb-server    | 	at io.confluent.ksql.rest.server.computation.CommandStore.getRestoreCommands(CommandStore.java:211)
ksqldb-server    | 	at io.confluent.ksql.rest.server.computation.CommandRunner.processPriorCommands(CommandRunner.java:164)
ksqldb-server    | 	at io.confluent.ksql.rest.server.KsqlRestApplication.initialize(KsqlRestApplication.java:419)
ksqldb-server    | 	at io.confluent.ksql.rest.server.KsqlRestApplication.startKsql(KsqlRestApplication.java:349)
ksqldb-server    | 	at io.confluent.ksql.rest.server.KsqlRestApplication.startAsync(KsqlRestApplication.java:332)
ksqldb-server    | 	at io.confluent.ksql.rest.server.KsqlServerMain.tryStartApp(KsqlServerMain.java:72)
ksqldb-server    | 	at io.confluent.ksql.rest.server.KsqlServerMain.main(KsqlServerMain.java:58)
ksqldb-server    | [2020-07-02 08:58:36,112] INFO Server shutting down (io.confluent.ksql.rest.server.KsqlServerMain:79)
ksqldb-server    | [2020-07-02 08:58:51,143] INFO API server stopped (io.confluent.ksql.api.server.Server:183)
ksqldb-server    | [2020-07-02 08:58:51,145] ERROR Failed to start KSQL (io.confluent.ksql.rest.server.KsqlServerMain:60)
ksqldb-server    | java.lang.NullPointerException
ksqldb-server    | 	at org.apache.kafka.clients.consumer.internals.Fetcher.prepareFetchRequests(Fetcher.java:1113)
ksqldb-server    | 	at org.apache.kafka.clients.consumer.internals.Fetcher.sendFetches(Fetcher.java:246)
ksqldb-server    | 	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1284)
ksqldb-server    | 	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1236)
ksqldb-server    | 	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1204)
ksqldb-server    | 	at io.confluent.ksql.rest.server.CommandTopic.getRestoreCommands(CommandTopic.java:88)
ksqldb-server    | 	at io.confluent.ksql.rest.server.computation.CommandStore.getRestoreCommands(CommandStore.java:211)
ksqldb-server    | 	at io.confluent.ksql.rest.server.computation.CommandRunner.processPriorCommands(CommandRunner.java:164)
ksqldb-server    | 	at io.confluent.ksql.rest.server.KsqlRestApplication.initialize(KsqlRestApplication.java:419)
ksqldb-server    | 	at io.confluent.ksql.rest.server.KsqlRestApplication.startKsql(KsqlRestApplication.java:349)
ksqldb-server    | 	at io.confluent.ksql.rest.server.KsqlRestApplication.startAsync(KsqlRestApplication.java:332)
ksqldb-server    | 	at io.confluent.ksql.rest.server.KsqlServerMain.tryStartApp(KsqlServerMain.java:72)
ksqldb-server    | 	at io.confluent.ksql.rest.server.KsqlServerMain.main(KsqlServerMain.java:58)

**Comment by spena** [comment]
@wangbf It looks like a problem with the command topic. Were you running an older version of KSQL? Perhaps is this image is reading an incompatible or corrupted command_topic.

**Comment by wcmolin** [comment]
I have the same problem

**Comment by spena** [comment]
@wcmolin Seems there's some incompatibility between the Kafka client and server versions. ksqlDB dockers are built and tested using Confluent 5.5 dependencies which use Kafka 2.5. Could you upgrade to the latest Kafka?

**Comment by wcmolin** [comment]
@spena When I upgraded Kafka to version 2.5, it became available. Thanks!

**Comment by spena** [comment]
@wangbf Check your Kafka version. That might be the problem.

I'll close this question.
