### ISSUE TITLE
Protobuf serde doesn't support DECIMAL sql type.

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#5762]
**Describe the bug**

Looks like the new(ish) PROTOBUF format in ksqlDB doesn't support DECIMALs.

**To Reproduce**

Add this test to `decimals.json` to add a QTT test:

```json
{
      "name": "PROTOBUF should not trim trailing zeros",
      "statements": [
        "CREATE STREAM INPUT (ID STRING KEY, dec DECIMAL(6,4)) WITH (kafka_topic='test', value_format='PROTOBUF');",
        "CREATE STREAM OUTPUT AS SELECT * FROM INPUT;"
      ],
      "inputs": [
        {"topic": "test", "value": {"DEC": 10.0000}},
        {"topic": "test", "value": {"DEC": 1.0000}}
      ],
      "outputs": [
        {"topic": "OUTPUT", "value": {"DEC": 10.0000}},
        {"topic": "OUTPUT", "value": {"DEC": 1.0000}}
      ],
      "post": {
        "sources": [
          {"name": "INPUT", "type": "stream", "schema": "ID STRING KEY, DEC DECIMAL(6,4)"},
          {"name": "OUTPUT", "type": "stream", "schema": "ID STRING KEY, DEC DECIMAL(6,4)"}
        ]
      }
    }
```

**Expected behavior**

The test should pass

**Actual behaviour**

The test fails with the error

```
Caused by: java.lang.RuntimeException: Unexpected BYTES type null
```

Doing the same in ksql for real results in a similar error:

```
ksql> CREATE STREAM INPUT (ID STRING KEY, dec DECIMAL(6,4)) WITH (kafka_topic='test', value_format='PROTOBUF', PARTITIONS=1);

 Message        
----------------
 Stream created 
----------------

ksql> INSERT INTO INPUT VALUES(null, 10.0);
Failed to insert values into 'INPUT'. Could not serialize row: [ 10.0 ]. Error serializing message to topic: test. Invalid type for BYTES: class java.math.BigDecimal
```

### Update

#5784 was created to handle the short term fix, which is a better error message.  This issue is left for the long term fix, which is for the Protobuf format to support the DECIMAL type. 

Protobuf ticket for Decimal support: protocolbuffers/protobuf#4406
Schema Registry ticker for Decimal support: https://confluentinc.atlassian.net/browse/DG-615

**Comment by big-andy-coates** [comment]
Please enable the disabled test in `decimals.json` once this is fixed.

**Comment by big-andy-coates** [comment]
So we can see that INSERT VALUES doesn't work for decimals.  Not 100% sure if processing source data for Kafka is broken or not. It looks likely, but the error seen from the QTT test above is in the test framework itself, so its _possible_ the actual processing works and we just can't test it.

**Comment by big-andy-coates** [comment]
Protobuf, and more specifically the protobuf in the schema registry, doesn't support a decimal type:

Protobuf ticket for Decimal support: https://github.com/protocolbuffers/protobuf/issues/4406
Schema Registry ticker for Decimal support: https://confluentinc.atlassian.net/browse/DG-615

Without these, ksqlDB can't support DECIMAL for protobuf.  However, it _should_ report a better error.

**Comment by rmoff** [comment]
👏 good job on the error message - I hit this and it brought me straight here.
