### ISSUE TITLE
A problem in "Event-driven microservice" tutorial

### ISSUE THREAD

**Issue by ChenShuai1981** [confluentinc/ksql#5764]
https://docs.ksqldb.io/en/latest/tutorials/event-driven-microservice/

After fire `CREATE TABLE possible_anomalies WITH (...)` command, **since the `card_number` is the group key which is occurred in message key instead of message value**, thus after fire the command 'PRINT 'possible_anomalies' FROM BEGINNING;' it will NOT be occurred in message values, so the `card_number` will NOT be in schema registry `possible_anomalies-value` subject. After `mvn generate-sources`, I can't find the `card_number` field in generated PossibleAnomaly.java source, this is a problem. I tried to modify EmailSender.java to get `card_number` from record.key() but found there is garbled code like '373913272311617q�ө`'. 

How to duplicate `card_number` field both in message key and in message value?

**Comment by MichaelDrogalis** [comment]
Hey @ChenShuai1981, thanks for reporting. This indeed looks broken. I've opened https://github.com/confluentinc/ksql/pull/5776 to provide a fix. In the meantime, you can use the `as_value` function to control where the data is placed. That function will place it in the value side of the Kafka record.

**Comment by MichaelDrogalis** [comment]
Merged the PR.
