### ISSUE TITLE
Issue creating stream "Caused by: key" in 0.10.0

### ISSUE THREAD

**Issue by szicari-farmobile** [confluentinc/ksql#5791]
We've got ksqlDB 0.10.0 deployed as ECS tasks in AWS. We're trying to set up a stream but running into an error. Here is my stream definition:

```
CREATE STREAM my_topic_stream
  WITH (KAFKA_TOPIC='my-topic', VALUE_FORMAT='AVRO');
```

The stream appears to be set up properly:

```
ksql> SHOW STREAMS;

 Stream Name      | Kafka Topic    | Format
--------------------------------------------
 MY_TOPIC         | my-topic       | AVRO
--------------------------------------------
```

...but trying to DESCRIBE it results in the following error:

```
ksql> DESCRIBE MY_TOPIC_STREAM;
Error issuing POST to KSQL server. path:/ksql
Caused by: Error reading entity from input stream.
Caused by: Cannot construct instance of
	`io.confluent.ksql.rest.entity.SourceDescription`, problem: key
 at [Source:
	(org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 2636] (through reference chain:
	io.confluent.ksql.rest.entity.KsqlEntityList[0]->io.confluent.ksql.rest.entity.SourceDescriptionEntity["sourceDescription"])
Caused by: key
```

The topic key data type is int, if that matters. The topic value schema is below:

```json
{
    "type": "record",
    "name": "myTopic",
    "namespace": "data",
    "fields": [
        {
            "name": "id",
            "type": "int"
        },
        {
            "name": "ts",
            "type": [
                "long",
                "null"
            ],
            "logicalType": "timestamp-millis"
        },
        {
            "name": "date",
            "type": [
                "string",
                "null"
            ]
        },
        {
            "name": "epoch",
            "type": [
                "long",
                "null"
            ]
        },
        {
            "name": "gps_speed",
            "type": [
                "double",
                "null"
            ],
            "default": "0.0"
        },
        {
            "name": "gps_speed_metric",
            "type": [
                "double",
                "null"
            ],
            "default": "0.0"
        },
        {
            "name": "altitude",
            "type": [
                "double",
                "null"
            ]
        },
        {
            "name": "latitude",
            "type": [
                "double",
                "null"
            ]
        },
        {
            "name": "longitude",
            "type": [
                "double",
                "null"
            ]
        },
        {
            "name": "true_course",
            "type": [
                "double",
                "null"
            ]
        },
        {
            "name": "stage_1_ts",
            "type": "string"
        },
        {
            "name": "stage_2_ts",
            "type": "string"
        },
        {
            "name": "msg_count",
            "type": [
                "int",
                "null"
            ]
        },
        {
            "name": "bin_count",
            "type": [
                "string",
                "null"
            ]
        },
        {
            "name": "src_num",
            "type": [
                "long",
                "null"
            ]
        },
        {
            "name": "sequence",
            "type": [
                "long",
                "null"
            ]
        },
        {
            "name": "status_bits",
            "type": [
                "long",
                "null"
            ]
        },
        {
            "name": "util",
            "type": [
                "long",
                "null"
            ]
        },
        {
            "name": "valid_message",
            "type": "boolean"
        }
    ]
}
```

**Comment by vcrfxia** [comment]
Hey @szicari-farmobile , what's the serialization format for your Kafka topic key? Are the keys serialized as Avro integers, with the Kafka integer serializer, or something else?

**Comment by szicari-farmobile** [comment]
@vcrfxia The key is an integer, but no AVRO schema is defined for the key.

**Comment by vcrfxia** [comment]
Hey @szicari-farmobile , if I understand correctly, it sounds like your keys are Avro-serialized integers? If so, they are unfortunately not supported by ksqlDB at this time, but will be in an upcoming release. Here's the GitHub issue to track: https://github.com/confluentinc/ksql/issues/4461

I'm closing this one for now as a duplicate, but please do reopen it if I've misunderstood.

**Comment by vcrfxia** [comment]
This error message is really awful, though. Let me see if I can figure out where that's coming from...

**Comment by vcrfxia** [comment]
Hey @szicari-farmobile I was unable to reproduce your issue. Can you spot where I've gone wrong?

Running ksqlDB 0.10.0 with Kafka and Schema Registry on Confluent Platform 5.5:

- Created topic `my-topic`: `./kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic my-topic`
- Registered the above schema as `my-topic-value`: `curl -X POST http://localhost:8081/subjects/my-topic-value/versions -H "Content-Type: application/vnd.schemaregistry.v1+json;charset=utf-8" -d '{"schema":"{\"type\": \"record\", \"name\": \"myTopic\", \"namespace\": \"data\", \"fields\": [{\"name\": \"id\", \"type\": \"int\"}, {\"name\": \"ts\", \"type\": [\"long\", \"null\"], \"logicalType\": \"timestamp-millis\"}, {\"name\": \"date\", \"type\": [\"string\", \"null\"] }, {\"name\": \"epoch\", \"type\": [\"long\", \"null\"] }, {\"name\": \"gps_speed\", \"type\": [\"double\", \"null\"], \"default\": \"0.0\"}, {\"name\": \"gps_speed_metric\", \"type\": [\"double\", \"null\"], \"default\": \"0.0\"}, {\"name\": \"altitude\", \"type\": [\"double\", \"null\"] }, {\"name\": \"latitude\", \"type\": [\"double\", \"null\"] }, {\"name\": \"longitude\", \"type\": [\"double\", \"null\"] }, {\"name\": \"true_course\", \"type\": [\"double\", \"null\"] }, {\"name\": \"stage_1_ts\", \"type\": \"string\"}, {\"name\": \"stage_2_ts\", \"type\": \"string\"}, {\"name\": \"msg_count\", \"type\": [\"int\", \"null\"] }, {\"name\": \"bin_count\", \"type\": [\"string\", \"null\"] }, {\"name\": \"src_num\", \"type\": [\"long\", \"null\"] }, {\"name\": \"sequence\", \"type\": [\"long\", \"null\"] }, {\"name\": \"status_bits\", \"type\": [\"long\", \"null\"] }, {\"name\": \"util\", \"type\": [\"long\", \"null\"] }, {\"name\": \"valid_message\", \"type\": \"boolean\"} ] }"}'`
- Created ksqlDB stream: `CREATE STREAM my_topic_stream WITH (KAFKA_TOPIC='my-topic', VALUE_FORMAT='AVRO');`
- Described newly created stream: 
```
ksql> DESCRIBE MY_TOPIC_STREAM;

Name                 : MY_TOPIC_STREAM
 Field            | Type
------------------------------------
 ID               | INTEGER
 TS               | BIGINT
 DATE             | VARCHAR(STRING)
 EPOCH            | BIGINT
 GPS_SPEED        | DOUBLE
 GPS_SPEED_METRIC | DOUBLE
 ALTITUDE         | DOUBLE
 LATITUDE         | DOUBLE
 LONGITUDE        | DOUBLE
 TRUE_COURSE      | DOUBLE
 STAGE_1_TS       | VARCHAR(STRING)
 STAGE_2_TS       | VARCHAR(STRING)
 MSG_COUNT        | INTEGER
 BIN_COUNT        | VARCHAR(STRING)
 SRC_NUM          | BIGINT
 SEQUENCE         | BIGINT
 STATUS_BITS      | BIGINT
 UTIL             | BIGINT
 VALID_MESSAGE    | BOOLEAN
------------------------------------
For runtime statistics and query details run: DESCRIBE EXTENDED <Stream,Table>;
```

Reopening this issue as the key serialization format shouldn't affect the output of describing a stream, though the fact that ksqlDB does not support Avro-serialized keys at this time is still a problem for your use case.

**Comment by szicari-farmobile** [comment]
@vcrfxia Here are some tests we've run:

### First Test
I deleted my kafka topic and the associated schema in the schema registry. 
I recreated the kafak topic and ran an app to register the schema and publish data to the topic. 
The data in the topic has an integer serialized key and an avro serialized value. 

```python
from confluent_kafka.serialization import IntegerSerializer 
…
self._avro_producer = SerializingProducer({
    'bootstrap.servers': environ['BOOTSTRAP_SERVERS'], 
    'key.serializer': IntegerSerializer(), 
    'value.serializer': self._puc_value_schema
})
```

I then created a stream in ksqlDB that pointed to the kafka topic.  

```bash
ksql> show streams;

 Stream Name | Kafka Topic | Format 
------------------------------------
------------------------------------
```

Show streams fails. 

```bash
ksql> CREATE STREAM unpacked_pulse_stream_noschema
>  WITH (KAFKA_TOPIC='unpacked-pulse', VALUE_FORMAT='AVRO');

 Message        
----------------
 Stream created 
----------------
ksql> describe UNPACKED_PULSE_STREAM_NOSCHEMA;
Error issuing POST to KSQL server. path:/ksql
Caused by: Error reading entity from input stream.
Caused by: Cannot construct instance of
	`io.confluent.ksql.rest.entity.SourceDescription`, problem: key
 at [Source:
	(org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInpu
	tStream); line: 1, column: 2479] (through reference chain:
	io.confluent.ksql.rest.entity.KsqlEntityList[0]->io.confluent.ksql.rest.entity.S
	ourceDescriptionEntity["sourceDescription"])
Caused by: key
```

### Second Test
Same scenario as above however, this time I created a topic with a string serialized key. The results were the same.

**Comment by vcrfxia** [comment]
Hey @szicari-farmobile , thanks for the additional context. A couple more questions to help my understanding:
- An error is thrown when you try to describe the newly created stream. Do you encounter other issues when using the stream, for example, when reading from the stream (`SELECT * FROM unpacked_pulse_stream_noschema EMIT CHANGES;`), or using the stream as a source for a persistent query (`CREATE STREAM AS SELECT ... FROM unpacked_pulse_stream_noschema EMIT CHANGES;`)?
- Could you share the rest of your Avro producer code, including how you created the topic, and how you produced a record or two to the topic? (I assume you produced a record or two to the topic, as I'm not sure how the Avro value schema would have been registered otherwise.) I wonder if this issue might be specific to the Python client. I'd be surprised but I'm not sure how else to explain the fact that I wasn't able to reproduce the issue with my experiment above.

**Comment by szicari-farmobile** [comment]
Hi, @vcrfxia. Sorry I missed this message! Let me see what I can find. We upgraded to 0.11.0 and now get an error when we try to describe a stream:

```Error issuing POST to KSQL server. path:/ksql
Caused by: Error reading entity from input stream.
Caused by: Cannot construct instance of
        `io.confluent.ksql.rest.entity.SourceDescription`, problem: key
 at [Source:
        (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInpu
        tStream); line: 1, column: 2008] (through reference chain:
        io.confluent.ksql.rest.entity.KsqlEntityList[0]->io.confluent.ksql.rest.entity.S
        ourceDescriptionEntity["sourceDescription"])
Caused by: key```

**Comment by szicari-farmobile** [comment]
I'm closing this because we've had a number of other issues with our ksqlDB deployment. I need to ensure we've deployed it properly in the first place. Thanks again, and sorry for making you parse through something that might not be an issue.

**Comment by szicari-farmobile** [comment]
@vcrfxia What version of the ksqlDB CLI were you using when you attempted to reproduce this bug? Do you recall? I suspect maybe I was using an older version that wasn't compatible in some way.

**Comment by vcrfxia** [comment]
Hi @szicari-farmobile when I previously attempted to reproduce the issue I used 0.10.0 for both the ksqlDB server and the CLI.

Your theory of the bug being caused by using an older, incompatible CLI version seems very plausible, especially since the error message references Jersey which was used by older ksqlDB CLI versions but not by the more recent ones. Good find! I'd missed that earlier.
