### ISSUE TITLE
JSON_SR Schemas Incorrectly Considered Incompatible in CREATE STREAM

### ISSUE THREAD

**Issue by dlfaraujo** [confluentinc/ksql#5798]
When ksqlDB uses a topic that has a schema already registered in schema registry, it ensures that the schema is compatible with the one that ksqlDB generates given the generated sql code. To test compatibility, it uses the schema registry's `testCompatibility` method. For `JSON_SR` (`AVRO` as well, but there are other factors in play that make it not an issue) case changes cause compatibility issues (see this comment: https://github.com/confluentinc/ksql/issues/5801#issuecomment-656267848) especially with regards to case sensitivity.

Additionally, there are many properties that are not convertible to SQL schemas:

- `additionalProperties`
- `$id`

Changing our schema to include additional properties for the serde might be possible, but it seems that `testCompatibility` should not fail if missing the above properties.

-----

Original Ticket:

When using a JSON Schema with `"additionalProperties": true` and trying to CREATE STREAM from a topic with that schema it returns the error `Could not register schema for topic.`. The exact same schema but with `"additionalProperties": false` works fine.

[flight.json.zip](https://github.com/confluentinc/ksql/files/4894627/flight.json.zip)

**Comment by agavra** [comment]
Thanks for reporting this @dlfaraujo - I'm going to change the name of this ticket and clarify the bug a little bit to cover this general class of bugs. I think it will require changes in schema registry to resolve these bugs.

**Comment by rayokota** [comment]
FYI, it's best to generate schemas with `"additionalProperties": false`.   Otherwise, if set to`true` or omitted (default is `true`, most schema changes will be incompatible.

**Comment by agavra** [comment]
@rayokota - thanks for the tip. I'm not sure I understand though, wouldn't `"additionalProperties": true` be strictly more lenient than having it set to `false`? Or are we concerned about the case where a field that wasn't in the first schema but was in the data is then declared as having a different type?

**Comment by rayokota** [comment]
Yes, the latter case.  See https://github.com/confluentinc/schema-registry/issues/1529
