### ISSUE TITLE
stream - stream foreign key joins

### ISSUE THREAD

**Issue by ram1sankar** [confluentinc/ksql#5800]
Inner joins gives blank data in cli and left join give null record for the right stream
SET 'auto.offset.reset'='earliest';
Successfully changed local property 'auto.offset.reset' to 'earliest'. Use the UNSET command to revert your change.
ksql> select * from OC_PURPLTREE_VENDOR_PRODUCTS_STM emit changes limit 1;
+-----+-----+-----+-----+-----+-----+-----+-----+
|ROWKE|ID   |SELLE|PRODU|IS_AP|CREAT|DATE_|__OP |
|Y    |     |R_ID |CT_ID|PROVE|ED_AT|MODIF|     |
|     |     |     |     |D    |     |IED  |     |
+-----+-----+-----+-----+-----+-----+-----+-----+
|{"id"|2    |3    |47   |1    |18442|null |u    |
|:2}  |     |     |     |     |     |     |     |
Limit Reached
Query terminated
ksql> select * from MBC_VEN_ID_STM emit changes limit 2;
+-----+-----+-----+-----+
|MBC_I|VENDO|VEN_S|__OP |
|D    |R_ID |YM_ID|     |
+-----+-----+-----+-----+
|4    |2    |001  |c    |
|5    |3    |002  |c    |
Limit Reached
Query terminated
ksql> select a.seller_id,b.vendor_id,b.ven_sym_id from OC_PURPLTREE_VENDOR_PRODUCTS_STM a left join MBC_VEN_ID_STM b within 1 minute on a.seller_id=b.vendor_id emit changes limit 1;
+-----+-----+-----+
|SELLE|VENDO|VEN_S|
|R_ID |R_ID |YM_ID|
+-----+-----+-----+
|3    |null |null |
Limit Reached
Query terminated
*********************************
Inner Join
 select * from OC_PURPLTREE_VENDOR_PRODUCTS_STM emit changes limit 1;
+-----+-----+-----+-----+-----+-----+-----+-----+
|ROWKE|ID   |SELLE|PRODU|IS_AP|CREAT|DATE_|__OP |
|Y    |     |R_ID |CT_ID|PROVE|ED_AT|MODIF|     |
|     |     |     |     |D    |     |IED  |     |
+-----+-----+-----+-----+-----+-----+-----+-----+
|{"id"|2    |3    |47   |1    |18442|null |u    |
|:2}  |     |     |     |     |     |     |     |
Limit Reached
Query terminated
ksql> select * from MBC_VEN_ID_STM emit changes limit 2;
+-----+-----+-----+-----+
|MBC_I|VENDO|VEN_S|__OP |
|D    |R_ID |YM_ID|     |
+-----+-----+-----+-----+
|4    |2    |001  |c    |
|5    |3    |002  |c    |
Limit Reached
Query terminated
ksql> select a.seller_id,b.vendor_id,b.ven_sym_id from OC_PURPLTREE_VENDOR_PRODUCTS_STM a inner join MBC_VEN_ID_STM b within 1 minute on a.seller_id=b.vendor_id emit changes limit 1;
+-----+-----+-----+
|SELLE|VENDO|VEN_S|
|R_ID |R_ID |YM_ID|
+-----+-----+-----+

**Comment by vcrfxia** [comment]
Hey @ram1sankar , I assume your question is why you're seeing this behavior? If you haven't already, please have a look at these docs regarding the semantics of stream-stream joins: https://docs.ksqldb.io/en/latest/developer-guide/joins/join-streams-and-tables/#semantics-of-stream-stream-joins For example, you can see in the "left join" expected output column that nulls are expected if a record arrives in the left stream when there are no corresponding records in the right stream. Regarding the inner join result, did you check that the timestamps for the two records are really within 1 minute of each other?

If you still have questions, it'd be helpful to get:
- the SQL statements you used to create your two source streams
- the full pieces of example data from both sides of the stream, including timestamps
- the ksqlDB version you're running

Also, you can use GitHub code blocks to format console output in a more readable way: https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

**Comment by ram1sankar** [comment]
Thanks for the reply. will print the output along with the timestamp of the underlying topic.

**Comment by ram1sankar** [comment]
```
Yes you are right. the timestamp for rowtime of when both the queries were created are different as you can see below.
ksql> print 'dbz.opencart.oc_order' from beginning limit 2;

Key format: JSON or HOPPING(KAFKA_STRING) or TUMBLING(KAFKA_STRING) or KAFKA_STRING
Value format: JSON or KAFKA_STRING
rowtime: 2020/07/10 12:15:31.871 Z, key: {"order_id":59}, value: {"order_id":59,"invoice_no":0,"invoice_prefix":"INV-2020-00","store_id":0,"store_name":"Your Store","date_added":1594402982000,"date_modified":1594402982000,"__op":"c"}
rowtime: 2020/07/10 12:15:33.464 Z, key: {"order_id":59}, value: {"order_id":59,"invoice_no":0,"invoice_prefix":"INV-2020-00","store_id":0,"store_name":"Your Store","date_added":1594402982000,"date_modified":1594402985000,"__op":"u"}

ksql> select TIMESTAMPTOSTRING(ROWTIME, 'yyyy-MM-dd HH:mm:ss.SSS') as rowtime_formatted,TIMESTAMPTOSTRING(date_added, 'yyyy-MM-dd HH:mm:ss.SSS') as date_added,TIMESTAMPTOSTRING(date_modified, 'yyyy-MM-dd HH:mm:ss.SSS') as date_modified,order_id,order_status_id,__op from OC_ORDERS_REPART emit changes limit 1;

|ROWTI|DATE_|DATE_|ORDER|ORDER|__OP |
|ME_FO|ADDED|MODIF|_ID  |_STAT|     |
|RMATT|     |IED  |     |US_ID|     |
|ED   |     |     |     |     |     |
+-----+-----+-----+-----+-----+-----+
|2020-|2020-|2020-|59   |1    |u    |
|07-10|07-10|07-10|     |     |     |
| 17:4| 17:4| 17:4|     |     |     |
|3:02.|3:02.|3:05.|     |     |     |
|000  |000  |000  |     |     |     |
Limit Reached
Query terminated

ksql> select TIMESTAMPTOSTRING(ROWTIME, 'yyyy-MM-dd HH:mm:ss.SSS') as rowtime_formatted,* from OC_ORDER_PROD_REPART emit changes limit 1;

|ROWTI|ORDER|ORDER|VEN_S|PRODU|NAME |MODEL|QUANT|PRICE|TOTAL|TAX  |REWAR|__OP |
|ME_FO|_ID  |_PROD|YM_ID|CT_ID|     |     |ITY  |     |     |     |D    |     |
|RMATT|     |UCT_I|     |     |     |     |     |     |     |     |     |     |
|ED   |     |D    |     |     |     |     |     |     |     |     |     |     |
+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+
|2020-|59   |72   |null |40   |iPhon|produ|1    |100.0|100.0|0.0  |0    |c    |
|07-10|     |     |     |     |e    |ct 11|     |     |     |     |     |     |
| 12:1|     |     |     |     |     |     |     |     |     |     |     |     |
|5:32.|     |     |     |     |     |     |     |     |     |     |     |     |
|131  |     |     |     |     |     |     |     |     |     |     |     |     |
Limit Reached
Query terminated
```

**Comment by ram1sankar** [comment]
```
created a new test case where inner join works.
ksql> select TIMESTAMPTOSTRING(ROWTIME, 'yyyy-MM-dd HH:mm:ss.SSS') as rowtime_formatted,* from OC_ORDERS_TEST_REP  emit changes limit 1

|ROWTI|ORDER|STORE|
|ME_FO|_ID  |_ID  |
|RMATT|     |     |
|ED   |     |     |
+-----+-----+-----+
|2020-|59   |0    |
|07-10|     |     |
| 12:1|     |     |
|5:31.|     |     |
|871  |     |     |
Limit Reached
Query terminated

ksql> select TIMESTAMPTOSTRING(ROWTIME, 'yyyy-MM-dd HH:mm:ss.SSS') as rowtime_formatted,* from OC_ORDERS_PROD_TEST_REP  emit changes limit 1;

|ROWTI|ORDER|NAME |
|ME_FO|_ID  |     |
|RMATT|     |     |
|ED   |     |     |
+-----+-----+-----+
|2020-|59   |iPhon|
|07-10|     |e    |
| 12:1|     |     |
|5:32.|     |     |
|131  |     |     |
Limit Reached
Query terminated

ksql> select a.order_id,b.order_id,b.name from oc_orders_test_rep a inner join oc_order_prod_repart b within 1 minute on a.order_id=b.order_id emit changes limit 1;
+-----+-----+-----+
|A_ORD|B_ORD|NAME |
|ER_ID|ER_ID|     |
+-----+-----+-----+
|59   |59   |iPhon|
|     |     |e    |
Limit Reached
Query terminated
```

**Comment by ram1sankar** [comment]
Will try and insert new record in the topic and will simulate the same scenario again and will paste the output here so that others can reference it

**Comment by vcrfxia** [comment]
Hey @ram1sankar , glad you were able to get the join working once the timestamp issue was resolved! I'm going to close this ticket for now, but feel free to continue adding / updating posts for future reference as you like. Thanks.
