### ISSUE TITLE
ksqldb version in confluent platform

### ISSUE THREAD

**Issue by rtrg** [confluentinc/ksql#5817]
ksqldb server version which comes with confluent [platform](https://docs.confluent.io/current/quickstart/ce-quickstart.html#ce-quickstart) says it's version is `5.5.1`

```
                 
                  ===========================================
                  =       _              _ ____  ____       =
                  =      | | _____  __ _| |  _ \| __ )      =
                  =      | |/ / __|/ _` | | | | |  _ \      =
                  =      |   <\__ \ (_| | | |_| | |_) |     =
                  =      |_|\_\___/\__, |_|____/|____/      =
                  =                   |_|                   =
                  =  Event Streaming Database purpose-built =
                  =        for stream processing apps       =
                  ===========================================

Copyright 2017-2020 Confluent Inc.

CLI v5.5.1, Server v5.5.1 located at http://localhost:8088

Having trouble? Type 'help' (case-insensitive) for a rundown of how things work!

```
whereas in the blog [here](https://www.confluent.io/blog/ksqldb-0-10-0-latest-features-updates/), it is mentioned that `0.10.0` version is released recently and java client is introduced since this.

In both above mentioned places it is being referred as `ksqldb`, **what is the difference between these two different version ranges?**

With confluent platform `5.5.1` version, when I try to connect to `ksqldb` using java client I ran into below error
```
Exception in thread "main" java.util.concurrent.ExecutionException: io.confluent.ksql.api.client.exception.KsqlClientException: Received 404 response from server: HTTP 404 Not Found. Error code: 40400 at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) at
```

From [this](https://github.com/confluentinc/ksql/issues/5765#issuecomment-656211787) comment, it looks like this issue gets resolved if we use `ksqldb 0.10.0` version instead of ksqldb which comes by default with confluent platform `5.5.1`.

**Is it expected that to use java client, we need to install ksqldb 0.10.0 as a [standalone](https://ksqldb.io/quickstart.html) using docker or use [confluent cloud](https://www.confluent.io/blog/ksqldb-0-10-0-latest-features-updates/)?**

**Is there any future plan to include java client support for ksqldb which comes as part of confluent platform too?**

**Comment by MichaelDrogalis** [comment]
Hey @rtrg,

> what is the difference between these two different version ranges?

[Our product page](https://ksqldb.io/product.html) has a concise explanation of how we use parallel version tracks.

> Is it expected that to use java client, we need to install ksqldb 0.10.0 as a standalone using docker or use confluent cloud?

Yes. Our standalone distribution gets released faster than our enterprise distribution (the one included with Confluent Platform). Our most recent standalone release, 0.10.0, shipped after the most recent Confluent Platform release.

In general, we aim to update our cloud offering concurrently with new standalone releases.

> Is there any future plan to include java client support for ksqldb which comes as part of confluent platform too?

Yes. ksqlDB 0.10 will be bundled into the next release of Confluent Platform.

Let me know if you have any other questions!

**Comment by rtrg** [comment]
> Yes. ksqlDB 0.10 will be bundled into the next release of Confluent Platform.

@MichaelDrogalis can you please let me know when is the next release of Confluent Platform scheduled?

**Comment by MichaelDrogalis** [comment]
Because Confluent Platform is our enterprise offering, I can't comment on target release dates in this forum. What I can say is that we traditionally do 3-4 major release of Confluent Platform each year, and [the last one](https://www.confluent.io/blog/introducing-confluent-platform-5-5/) was on April 24th of this year. Should give you an idea. You can always contact Confluent through an official channel for more information.

**Comment by rtrg** [comment]
>You can always contact Confluent through an official channel for more information.

Sure, thanks!
