### ISSUE TITLE
Cannot create stream/table specifying only partitions and not replicas

### ISSUE THREAD

**Issue by vcrfxia** [confluentinc/ksql#5847]
**Describe the bug**

On ksqlDB master (not 0.10.1), ksqlDB is unable to create streams/tables with only the number of partitions specified, and not the number of replicas. For example, the first statement in the quickstart is broken:
```
ksql> CREATE STREAM riderLocations (profileId VARCHAR, latitude DOUBLE, longitude DOUBLE)
>  WITH (kafka_topic='locations', value_format='json', partitions=1);
Could not get default replication from Kafka cluster!
Caused by: java.lang.NullPointerException
```

A workaround is to specify the number of replicas explicitly, e.g.:
```
ksql> CREATE STREAM riderLocations (profileId VARCHAR, latitude DOUBLE, longitude DOUBLE)
>  WITH (kafka_topic='locations', value_format='json', partitions=1, replicas=1);

 Message
----------------
 Stream created
----------------
```

**To Reproduce**

1. Build ksqlDB master
1. Launch ksqlDB server
1. Issue `CREATE STREAM` statement from the quickstart.

**Expected behavior**

The stream is successfully created.

**Actual behaviour**

The error shown above is thrown. ksqlDB logs don't contain much additional information. From initial debugging, the NPE is coming from the fact that `getConfig()` returns an empty Config, so `.get()` returns null, and `.value()` throws:
https://github.com/confluentinc/ksql/blob/029bcd7c4e17c5f80f2a5340f60170fbe916a42b/ksqldb-engine/src/main/java/io/confluent/ksql/services/KafkaTopicClientImpl.java#L150-L152

**Additional context**

**Comment by agavra** [comment]
I'm hitting the same thing, I assumed it had something to do with my Kafka setup so I mentally muted it and just worked around. Since you're also hitting this, we probably need to address this soon - thanks for reporting!

**Comment by apurvam** [comment]
This should be a blocker for 0.11.0 right?

**Comment by vcrfxia** [comment]
Yeah, I'd say it's a blocker as it's a nasty surprise.

**Comment by colinhicks** [comment]
for reference:

v0.10.1-ksqldb
`<kafka.version>6.0.0-ccs-beta200608020919-hf-1</kafka.version>`

v0.11.0-ksqldb
`<kafka.version>6.1.0-ccs-beta200715032424-hf-1</kafka.version>`

**Comment by stevenpyzhang** [comment]
It's interesting how there was no test coverage for this bug. I took a look at our integration tests which should have caught this and it looks like we never test this behavior there. We use `TEST_HARNESS.ensureTopics()` which creates the topics outside of a Create statement (RestApiTest for example). We should definitely add some coverage here after we pinpoint the issue.

**Comment by stevenpyzhang** [comment]
What the regression is https://github.com/apache/kafka/pull/8312#issuecomment-660478715

This one is a bit tricky, the only way we would've caught this ourselves through automated testing is testing client/server compatibility between newer and older versions of Kafka. These tests should already be present in Kafka so it seems redundant to have our own though.

**Comment by apurvam** [comment]
What's the status here? Was the bugfix merged upstream? Can this be closed?

**Comment by vcrfxia** [comment]
Yes, this was fixed by https://github.com/apache/kafka/pull/9046.
