### ISSUE TITLE
Stranded transient queries when push queries are issued via /query and HTTP/2

### ISSUE THREAD

**Issue by vcrfxia** [confluentinc/ksql#5881]
**Describe the bug**

Attempting to start a push query by issuing an HTTP/2 POST request to the /query endpoint results in a 405 since the HTTP streaming response used by the /query endpoint for push queries does not support HTTP/2. However, a Kafka Streams app is still started for the push query request, and this app is not being closed as it should be. This results in a transient query that cannot be terminated (see https://github.com/confluentinc/ksql/issues/5868), which is poor user experience.

**To Reproduce**

1. Start a recent version of ksqlDB. I think the problem goes back to 0.9.0, definitely happens with 0.10.x and 0.11.0.
1. Issue a push query request to the /query endpoint with HTTP/2, e.g.,: `curl -X "POST" "http://localhost:8088/query" -H "Content-Type: application/vnd.ksql.v1+json; charset=utf-8" -d '{"ksql":"select * from ksql_processing_log emit changes;"}' --http2 --verbose`.
1. Observe the 405 response code -- this is expected.
1. Run `show queries;` from the CLI and observe a stranded push query -- this is not expected.

**Expected behavior**

There is no transient query leftover from the failed push query attempt.

**Actual behaviour**

A Kafka Streams app is started for the query, and the stranded query lingers after the connection is closed.

**Additional context**

Work around this bug by either using HTTP/1.1, or by using the `/query-stream` endpoint which supports HTTP/2.

This issue is especially problematic when using curl to connect to an HTTPS server, as curl defaults to using HTTP/2 in this case.

Similar to how Kafka Streams apps are stranded when push queries requests are sent to the `/query` endpoint with HTTP/2, the Kafka consumer for `print topic` requests are also stranded when print topic requests are sent to the `/query` endpoint with HTTP/2.

**Comment by apurvam** [comment]
I think this should go out in 0.11.0 and also be backported to 0.10.x (for CP 6.0)
