### ISSUE TITLE
Add service to restart failed persistent queries

### ISSUE THREAD

**Issue by spena** [confluentinc/ksql#5897]
**Is your feature request related to a problem? Please describe.**

Sometimes a persistent query hits a condition that prevents it from making progress, and the query enters an ERROR state and terminates execution. Recovering from the error requires to terminate the query, drop the stream/table, and re-create the stream/table again.

**Describe the solution you'd like**

To recover from most errors KSQL just has to restart the query, sometimes after another entity (user, on-call, psc operator) resolves the underlying error condition. Instead of relying on a human to force this (as we do today), we should just have KSQL retry failed queries internally. 

**Describe alternatives you've considered**

Manual Retries
Instead of infinitely retrying queries, we could implement an API for users to manually restart failed queries. The advantage here would be that we avoid unnecessary failed attempts to retry, and that the recovery time would be faster (since once the user has resolved the condition, they don’t have to wait for the backoff). I went with automatic retries since this avoids the operational burden of manually restarting failed queries.

**Comment by rmoff** [comment]
This is a great feature to add!
Will ksqlDB retry the failed query more than once? and if so will it do so with any kind of incremental backoff?

**Comment by spena** [comment]
Yes, queries will keep restarting until succeed or the user terminates them manually. Restarts happen on incremental backoff, and it can be customized on these configs:
```
ksql.query.retry.backoff.initial.ms
ksql.query.retry.backoff.max.ms
```

**Comment by rmoff** [comment]
Perfect, thanks!
