### ISSUE TITLE
Update the ksql metric names to not contain ksql.service.id and instead add them as tags to the metrics.

### ISSUE THREAD

**Issue by harinirajendran** [confluentinc/ksql#5948]
**Is your feature request related to a problem? Please describe.**
We noticed that some of the metrics that are published by ksql have the following naming format `io.confluent.ksql/_confluent_ksql_<ksql.service.id>ksql_engine_query/<metric_name>` . And this would make it difficult to perform any cross ksql cluster metrics analysis as the metrics' names would vary from cluster to cluster. 

**Describe the solution you'd like**
It would be better if we remove the service id from the metric name and add it as a tag for the metrics instead.

**Comment by stevenpyzhang** [comment]
@rodesai @apurvam Do you two have context on why we decided to include the ksql service id into the metrics name and then the service id in the metrics group name later on instead of using the tags?

https://github.com/confluentinc/ksql/pull/1703
https://github.com/confluentinc/ksql/pull/2831

It seems like KSQL follows a different convention compared to other CP components

**Comment by rodesai** [comment]
Probably just a misunderstanding. We should fix this and have the metric names be the same for all clusters, and just include cluster-specific info in tags.

**Comment by rodesai** [comment]
Marking as needs-triage so we can decide a version to include this in.

**Comment by stevenpyzhang** [comment]
I'm thinking of doing this in two stages, In 0.15.0, we'll add the metric tag in the 0.15.0 image and update all metrics reporting regex to recognize the new naming format. In 0.16.0 we can remove the legacy metrics.

**Comment by stevenpyzhang** [comment]
Created a follow up ticket here https://github.com/confluentinc/ksql/issues/6740 to track fully removing metrics that contain the ksql service id in the metric name
