### ISSUE TITLE
When processing error occurs on nested field in a STRUCT, only set that field to null instead of entire STRUCT

### ISSUE THREAD

**Issue by mikebin** [confluentinc/ksql#5980]
**Is your feature request related to a problem? Please describe.**
Currently, when a processing error occurs on a nested field in a `STRUCT`, the entire encapsulating `STRUCT` is set to `null` in the output stream. Using an example where a date conversion fails for one of the fields in a struct type:

```sql
create stream s (val string) with (kafka_topic='s', value_format='json', partitions=1);
insert into s (val) values ('2020-08-11');
insert into s (val) values ('bad-date');

select struct(field1:=val, field2:=DATETOSTRING(STRINGTODATE(val, 'yyyy-MM-dd'), 'yyyyMMdd')) as body from s emit changes;
+--------------------------------------------------+
|BODY                                              |
+--------------------------------------------------+
|{FIELD1=2020-08-11, FIELD2=20200811}              |
|null                                              |
```

**Describe the solution you'd like**
Only set the failing field(s) in the struct to `null`, and preserve other valid field(s). Using the example, above, instead of `null` for the entire `BODY` struct, return `null` for `field2`, and preserve `field1`:

```
{FIELD1=2020-08-11, FIELD2=null} 
```

**Comment by colinhicks** [comment]
Let's re-evaluate the priority of this item as it came up recently as a production-blocking issue.
