### ISSUE TITLE
[JSON_SR Support]: Check partial schema inference works with none-Kafka key formats.

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#5990]
ksqlDB currently supports partial schema inference, where the user supplies only the key schema and the value schema is loaded from the schema registry.

Once we support non-KAFKA key formats we may have users have a key format that supports schema inference and a value schema that does not.  So we need to ensure partial schema inference works the other way around. e.g. 

```sql
-- only value schema supplied, key schema loaded from SR:
CREATE STREAM FOO (
  VAL STRING
 ) WITH (
  kafka_topic='foo',
  key_format='avro',
  value_format='delimited'
 );
```

**Comment by vcrfxia** [comment]
Tests were added in https://github.com/confluentinc/ksql/pull/6432, so this is done.
