### ISSUE TITLE
Support IF NOT EXISTS on CREATE CONNECTOR

### ISSUE THREAD

**Issue by spena** [confluentinc/ksql#5992]
**Is your feature request related to a problem? Please describe.**
Support the IF NOT EXISTS keyword on CREATE SOURCE|SINK CONNECTOR. For example:
```
CREATE SOURCE CONNECTOR IF NOT EXISTS <connector> ...;
CREATE SINK CONNECTOR IF NOT EXISTS <connector> ...;
```

**Describe the solution you'd like**
Create the source/sink connector only if it does not exist.

**Describe alternatives you've considered**
No alternatives.

**Comment by hemantgs** [comment]
Hi , can I have a go at this ?

**Comment by spena** [comment]
@hemantgs Go head, take it. :).
