### ISSUE TITLE
function support is still too weak

### ISSUE THREAD

**Issue by junhui** [confluentinc/ksql#600]
hope can add more standard function support, thanks

**Comment by miguno** [comment]
Which functions are you looking for?  Otherwise it is difficult to address your request.

There are already a couple of tickets that cover such functions.

**Comment by rmoff** [comment]
@junhui I'm closing this ticket for more, please feel free to re-open it with specific functions that you're looking for. You'll also see issues open for other functions, which you can +1 to help us gauge the level of demand for them.
