### ISSUE TITLE
CSAS: WITH is incompatible with WHERE? 

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#604]
I can CSAS with a `WHERE`: 
```SQL
ksql> CREATE STREAM FOO AS SELECT EXTRACT_TS, ORDER_DATE_EPOCH, ORDER_ID, ORDER_DATE, ORDER_STATUS, ORDER_TOTAL FROM ORDERS_INT_01 WHERE ORDER_STATUS IS NOT NULL;

 Message
----------------------------
 Stream created and running
----------------------------
```

And I can CSAS with a `WITH`: 
```SQL
ksql> CREATE STREAM FOO3 AS SELECT EXTRACT_TS, ORDER_DATE_EPOCH, ORDER_ID, ORDER_DATE, ORDER_STATUS, ORDER_TOTAL FROM ORDERS_INT_01 WITH (TIMESTAMP ='ORDER_DATE_EPOCH');

 Message
----------------------------
 Stream created and running
----------------------------
ksql>
```

but I can't CSAS with a `WITH` *and* a `WHERE`: 

```SQL
ksql> CREATE STREAM FOO2 AS SELECT EXTRACT_TS, ORDER_DATE_EPOCH, ORDER_ID, ORDER_DATE, ORDER_STATUS, ORDER_TOTAL FROM ORDERS_INT_01 WHERE ORDER_STATUS IS NOT NULL WITH (TIMESTAMP ='ORDER_DATE_EPOCH');
line 1:158: missing ';' at 'WITH'
Caused by: line 1:158: missing ';' at 'WITH'

ksql> CREATE STREAM FOO2 AS SELECT EXTRACT_TS, ORDER_DATE_EPOCH, ORDER_ID, ORDER_DATE, ORDER_STATUS, ORDER_TOTAL FROM ORDERS_INT_01 WHERE ORDER_STATUS='FOO' WITH (TIMESTAMP ='ORDER_DATE_EPOCH');
line 1:152: missing ';' at 'WITH'
Caused by: line 1:152: missing ';' at 'WITH'
```

**Comment by apurvam** [comment]
Hi @rmoff your usage of `WITH` is currently unsupported anyway. I think it is silently ignored in your first statement, but the second one fails correctly. We should not silently ignore the `WITH` but fail the statement with a proper error.

**Comment by rmoff** [comment]
Good point - my syntax for [CSAS](https://github.com/confluentinc/ksql/blob/master/docs/syntax-reference.md#create-stream-as-select) was wrong. This now works: 

    CREATE STREAM FOO2  WITH (TIMESTAMP ='ORDER_DATE_EPOCH') AS SELECT EXTRACT_TS, ORDER_DATE_EPOCH, ORDER_ID, ORDER_DATE, ORDER_STATUS, ORDER_TOTAL FROM ORDERS_INT_01 WHERE ORDER_STATUS IS NOT NULL;
