### ISSUE TITLE
Could not create topic _confluent-ksql-dswes-ccpclstransient_4787618039516871800_1597734035766-Aggregate-groupby-repartition.

### ISSUE THREAD

**Issue by bjlvfei** [confluentinc/ksql#6044]
Hi Team,

we meet an issue when run the sql in ksql server as below. It's can not create this topic _confluent-ksql-dswes-ccpclstransient_4787618039516871800_1597734035766-Aggregate-groupby-repartition due to it's so long. Could someone please help to check it?

ksql> SET 'auto.offset.reset' = 'earliest';
Successfully changed local property 'auto.offset.reset' to 'earliest'. Use the UNSET command to revert your change.

ksql> select A_ENTTYP, count(*) NUM from STREAM_SODS1_SALES_ORD_PRTNR_ADR_INFO group by A_ENTTYP emit changes;
+----------------------------------------------------------------+----------------------------------------------------------------+
|A_ENTTYP                                                        |NUM                                                             |
+----------------------------------------------------------------+----------------------------------------------------------------+
Could not create topic _confluent-ksql-dswes-ccpclstransient_4787618039516871800_1597734035766-Aggregate-groupby-repartition.
Caused by: Topic name exceeds the 100 character limit
Query terminated

Levi
Thanks!

**Comment by spena** [comment]
@bjlvfei which version of ksql and kafka are you running? From what I know, Kafka has a 255 character limit. 

A quick test, could you create the `_confluent-ksql-dswes-ccpclstransient_4787618039516871800_1597734035766-Aggregate-groupby-repartition` directly in Kafka to see if it works?

**Comment by spena** [comment]
Hey @bjlvfei @yfaykya, it's hard to support less than 100 characters in the topic name for the queries. That name is a mix of constants, service-id and other streams constants we cannot change. Only way is to reduce the # of characters of the service id `dswes-ccpcls`.

Currently we fully-support Kafka systems with 255 characters limitation, but not IBM Eventstream.

**Comment by spena** [comment]
I will close this issue as not fix.
