### ISSUE TITLE
ksql logs topic data if serializing records from print topic fails

### ISSUE THREAD

**Issue by rodesai** [confluentinc/ksql#6069]
**Describe the bug**

When ksql is executing `print topic`, if it hits an error serializing the topic data it will print out topic data in its log. This is a security vulnerability as the access control on the log may be quite different from the topic.

```
[2020-08-20 13:27:37,002] WARN Exception formatting record (io.confluent.ksql.rest.server.resources.streaming.TopicStream$RecordFormatter:80)
com.fasterxml.jackson.core.JsonParseException: <error message>
 at [Source: (String)"<data>"; line: 1, column: 123]
```

**To Reproduce**
Steps to reproduce the behavior, include:
1. Reproduced on KSQL 5.4
2. Create topic foo
2. Produce a record to foo with valid json.
2. Produce a record to foo with invalid json like: {"foo": "foo\x22bar"}
3. Run `print foo;`

**Expected behavior**
Log an error message without the recoord contents

**Comment by agavra** [comment]
This is no longer reproducable on master after https://github.com/confluentinc/ksql/pull/4551 - we now swallow all serialization errors and just default to more general types.
