### ISSUE TITLE
Bad error message on CREATE with keywords as field names (i.e. SIZE)

### ISSUE THREAD

**Issue by jonathanskrz** [confluentinc/ksql#6083]
Running : CLI v0.11.0, Server v0.11.0
(pulled from confluentinc/ksqldb-server:0.11.0)

Creating a stream with a field named "size" results in the following error : 
extraneous input 'size' expecting {'EMIT'

It seems like size is considered a reserved keyword.
Creating the stream with CREATE STREAM trades ( "size" DOUBLE ) works.

Looks similar to https://github.com/confluentinc/ksql/issues/3746

**Comment by jonathanskrz** [comment]
Just realized that's because SIZE is being used by the window tumbling operator... don't know if a more suitable error message would help here

**Comment by spena** [comment]
Right, the SIZE is a keyword it can't be used as a field name.
