### ISSUE TITLE
Java Client: Unable to list topics on 0.11.0

### ISSUE THREAD

**Issue by jhg023** [confluentinc/ksql#6088]
**Describe the bug**
 - Using the Java client, I am unable to list Kafka topics.
 - The HTTP request that's sent simply times out when sent from the Java client.
 - However, when sent using cURL, it succeeds with a 200 response code, and the response body contains the correct JSON (list of topics).

**To Reproduce**

    ClientOptions clientOptions = ClientOptions.create().setHost("localhost").setPort(8088);
    Client ksqlClient = Client.create(clientOptions);

    String topics = ksqlClient.listTopics()
                              .get(50L, TimeUnit.SECONDS)
                              .stream()
                              .map(topic -> topic.getName())
                              .collect(Collectors.joining(","));
    
The version of KSQL being used (Java Client) is `0.11.0`:

    implementation("io.confluent.ksql:ksqldb-api-client:0.11.0")

**Expected behavior**
 - I expect the request to not time out, and for the correct response to be returned.

**Actual behaviour**
 - The request times out and throws a `TimeoutException` after `50` seconds have passed.

**Additional context**
 - ksqldb-server is running within a docker container using branch `5.5.1-post` of https://github.com/confluentinc/cp-all-in-one
 - Sending the following cURL request works just fine
   - `curl -X POST -H "Content-Type: application/vnd.ksql.v1+json" -d '{"ksql": "show topics;"}' http://localhost:8088/ksql`

**Comment by spena** [comment]
Hi @jhg023,

The Java client will not work with ksqlDB 5.5.1 because it is not supported there. The Java client support was added since ksqlDB 0.10, but 5.5.1 is running an older version.

**Comment by jhg023** [comment]
@spena So, is the solution to upgrade the version of ksqlDB that I'm running?

**Comment by spena** [comment]
Yes, you need to upgrade. ksqlDB 0.11 should work fine with CP 5.5.1 as we used that version in our quickstart guide (https://ksqldb.io/quickstart.html).

**Comment by jhg023** [comment]
Thanks, I was able to get it to work by specifying the following in my `docker-compose.yml`:

    ksqldb-server:
        image: confluentinc/ksqldb-server:0.11.0

I wish that the CP repository would update this on their end; maybe I'll open a PR ¯\\_(ツ)_/¯

**Comment by eshil-patel** [comment]
Hi @spena , I'm facing a very similar issue as Jacob is facing. However, I can verify that my ksqldb-server version is indeed 0.11.0, and it is deployed on AWS.  
I can send a curl request and get a response to the server directly :  ```curl -X POST -H "Content-Type: application/vnd.ksql.v1+json" -d '{"ksql": "show topics;"}' {url-to-server}:80/ksql```.
Would you happen to know what could be the issue here ?
