### ISSUE TITLE
Connect default config incorrectly use AvroConverter for the key

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#6132]
The [default connect config](https://github.com/confluentinc/ksql/blob/0.12.x-ksqldb/config/connect.properties#L15) use the `AvroConverter` for the key convertor in the connect config.  Given ksqlDB doesn't support AVRO as a key format yet, this won't work!  

We should fix the related https://github.com/confluentinc/ksql/issues/4524 to, and the related docs issue https://github.com/confluentinc/ksql/issues/6131.

**Comment by big-andy-coates** [comment]
cc @agavra

**Comment by agavra** [comment]
@big-andy-coates the latter:
```java
    // at the moment, KSQL only supports String keys - when we
    // support non-string keys we should remove this line
    // (see: https://github.com/confluentinc/ksql/issues/3534)
    resolvedConfigs.putIfAbsent("key.converter", StringConverter.class.getName());
```
Though it seems that we should remove that line and fix this now that we support non-string keys!
