### ISSUE TITLE
Integrate code paths for schema compatibility checks for AVRO and other formats

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#6133]
ksqlDB supports two new formats that integrate with the schema register: `JSON_SR` and `PROTOBUF`, yet it only checks that a new schema abides by the schema compatibility rules for `AVRO` formats.

Given QTT test cases added to `serdes.json`:

```json
[
  {
      "name": "serialization should fail if primitive schema not compatible with existing value schema - JSON_SR",
      "statements": [
        "CREATE STREAM INPUT (K STRING KEY, foo STRING) WITH (kafka_topic='input_topic', value_format='JSON_SR');",
        "CREATE STREAM OUTPUT WITH (wrap_single_value=false) AS SELECT * FROM INPUT;"
      ],
      "topics": [
        {"name": "OUTPUT", "schema": {"name": "KsqlRecord", "type": "record", "fields": [{"name": "FOO", "type": "string"}]}}
      ],
      "expectedException": {
        "type": "io.confluent.ksql.util.KsqlStatementException",
        "message": "Cannot register JSON schema for OUTPUT as the schema is incompatible with the current schema version registered for the topic."
      }
    },
    {
      "name": "serialization should fail if primitive schema not compatible with existing value schema - PROTOBUF",
      "statements": [
        "CREATE STREAM INPUT (K STRING KEY, foo STRING) WITH (kafka_topic='input_topic', value_format='PROTOBUF');",
        "CREATE STREAM OUTPUT WITH (wrap_single_value=false) AS SELECT * FROM INPUT;"
      ],
      "topics": [
        {"name": "OUTPUT", "schema": {"name": "KsqlRecord", "type": "record", "fields": [{"name": "FOO", "type": "string"}]}}
      ],
      "expectedException": {
        "type": "io.confluent.ksql.util.KsqlStatementException",
        "message": "Cannot register protobuf schema for OUTPUT as the schema is incompatible with the current schema version registered for the topic."
      }
    }
]
```

### Expected result:

Tests pass, i.e. invalid schema evolution is detected.,

### Actual result:

Tests fail, as no exception is thrown.

The implications of this would be that we could start producing data to a topic with a different schema to other producers, breaking downstream processes.

**Comment by big-andy-coates** [comment]
This feels like a P0 to me, but leaving as `needs-triage` so it can be discussed.

**Comment by agavra** [comment]
Discussed offline so I'm going to add more information: the check still does happen, it happens in `SchemaRegistryInjector` because now we're eagerly registering schemas. At that point, if the schema is incompatible, it will fail.

The QTT tests don't have a real schema registry instance running, so it doesn't go through the injector. The additional check that is being done for AVRO is probably unnecessary and can be removed.

We do need to improve the error message, as the experience is currently sub-par:
```
ksql> CREATE STREAM out WITH (KAFKA_TOPIC='out') AS SELECT * FROM a;
Could not register schema for topic.
```

**Comment by big-andy-coates** [comment]
Agreed - we should remove the code in `AvroUtil` that calls `testCompatibility` as this is not needed. The main `register` call will also test compatibility.  We should, as @agavra says, improve the error message when the `register` call fails to include more information - inline with what the `AvroUtil` code currently does.
