### ISSUE TITLE
No error shown when using --exec option

### ISSUE THREAD

**Issue by chwong1** [confluentinc/ksql#616]
I tried to run ksql-cli remote http://localhost:8080 --exec “run script ‘/tmp/counts-schema.sql’;”

And there is an error in the script which can be shown when I use ksql shell.
"Cannot define a TABLE without providing the KEY column name in the WITH clause."

However, it did not show error when using "--exec" option.

Expected: it should show the error

**Comment by miguno** [comment]
This *should* be fixed in our latest KSQL versions. Closing this ticket for now.
