### ISSUE TITLE
How to alter connector of debezium?

### ISSUE THREAD

**Issue by koolay** [confluentinc/ksql#6195]
**Provide details of the setup you're running**
Let us know what version of KSQL you're running, what OS, etc, 

**Outline your question**
I have created a connector with `whitelist='table_01'` and I want to alter the connector with `whitelist='table_01,table_02'` over `rest api` of ksqldb server.
However, I cant found any doc about it.

**Comment by MichaelDrogalis** [comment]
Hey @koolay. You just run `DROP CONNECTOR <connector>;` and create a new one with the properties you want.

**Comment by koolay** [comment]
@MichaelDrogalis 
Thanks, I will try it.
