### ISSUE TITLE
Feat: DROP CONNECTOR foo DELETE OFFSET

### ISSUE THREAD

**Issue by benissimo** [confluentinc/ksql#6207]
**Is your feature request related to a problem? Please describe.**
Use case:
I'm working on deployment scripts for a KSQL application that involves a source connector, and streams attached to that connector's topic.
I drop the topic with "DROP STREAM foo DELETE TOPIC". This removes the topic and the corresponding schema. Great!
I then drop the connector using "DROP CONNECTOR".
I then regenerate the connector with "CREATE CONNECTOR ..." and regenerate the stream.
Problem: no new data flows in because the "DROP CONNECTOR" step didn't flush the connector's offsets.

**Describe the solution you'd like**
I'd love it if there were an option such as:
DROP CONNECTOR foo DELETE OFFSET
which would write a tombstone entry into the offsets topic if using distributed mode or whatever the equivalent is in standalone.

**Describe alternatives you've considered**
I considered renaming the connector when regenerating it (that's an easy workaround in development, but in other environments it's cumbersome, and would violate my company's naming policies in production).
I considered manually posting a tombstone as detailed by https://rmoff.net/2019/08/15/reset-kafka-connect-source-connector-offsets/
That's still cumbersome as it involves first looking up which topic is used to store offsets (my local uses Docker, our other environments don't; so it's "docker-connect-offsets" in some places, "connect-offsets" in others, and that could vary if configuration changes) and requires having write access to invoke the producer (more involved with the use of ssl certs, as opposed to the ease of posting via REST APIs).

**Additional context**
The current lack of a "DELETE OFFSET" option means that dropping a connector does not reset my application to the state it was in prior to creating the connector. My company requires that deployment tasks always have a rollback step that can effectively restore the previous state. Adding "DELETE OFFSET" option would make it easier to automate the corresponding rollback for the "CREATE CONNECTOR" deployment step.

**Comment by agavra** [comment]
Thanks for reporting this @benissimo - I think it would be breaking an abstraction to implement this in ksqlDB without having support for it in Kafka Connect. The connect offsets are explicitly stored (like you mentioned) in a `connect-offsets` topic. Having ksqlDB deal with that topic directly gets into some weird territory (it would be like someone outside of ksql messing with the ksql's command topic). If you're interested in this feature, I think it makes sense to issue a ticket against Apache Kafka and then we can pull it into ksqlDB when it's supported there.

**Comment by benissimo** [comment]
I see your point. KSQL's "CREATE CONNECTOR" builds on the Connect API. If currently there is no Connect API to reset connector config, you'd have to cheat by writing to the offsets topic directly, breaking abstraction, with no guarantee that such an approach would continue to work in the future.

I found that there already is an open issue about this in Kafka:
https://issues.apache.org/jira/browse/KAFKA-4107
and a related request:
https://cwiki.apache.org/confluence/display/KAFKA/KIP-199%3A+Add+Kafka+Connect+offset+tool

Finally, there's also an open issue about revising kafka-console-producer to allow it to post null values:
https://issues.apache.org/jira/browse/KAFKA-10238

Listing these here in case other users have similar needs.
