### ISSUE TITLE
[JSON Support]:  UI updates for `KEY_FORMAT` and `FORMAT`

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#6210]
Update UIs and examples to take advantage of new `KEY_FORMAT` and `FORMAT` with clause properties.

**Comment by vcrfxia** [comment]
This is done: the UI has been updated to display key format on all stream/table listings. The create stream/table modals have been removed (this change is currently behind a feature flag and will be flipped for the 0.14 release).
