### ISSUE TITLE
[JSON Support]: Support `DECIMAL` and `BOOLEAN` key types

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#6214]
JSON supports `DECIMAL` and `BOOLEAN` types. 
1. Add support for these types are key columns.
1. Add suitable QTT tests, (`json.json` or `elements.json`)
1. Ensure `AS_VALUE` works for these new types.

**Comment by apurvam** [comment]
I'm thinking that maybe we can leave this out of the initial releases. I am not sure if we know that people have DECIMAL / BOOLEAN in keys. if they do, we can add it as a followup feature.

**Comment by apurvam** [comment]
cc @MichaelDrogalis
