### ISSUE TITLE
[SR Support]: Add support for reading & writing key schemas from & to SR

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#6222]
1. Add support for reading and writing schemas to and from the schema registry.
 * Pick up https://github.com/confluentinc/ksql/issues/6133 as part of this work.
  * Register key schema on CREATE and CREATE AS statements in the same way as is done for value schemas.
  * Delete key subject on delete (and value subject for non-Avro, which may not currently be happening)
  * Delete key subject on internal topics too when query terminated (and value subject for non-Avro, which may not currently be happening)
2. Doc updates
 - Document the subject name for key schemas (and value if not already done) and when schemas are created / deleted

**Comment by agavra** [comment]
The above two PRs should get the bulk of this functionality done. We'll track follow-ups separately.
