### ISSUE TITLE
ksql server / client for release 5.5.1

### ISSUE THREAD

**Issue by cstmgl** [confluentinc/ksql#6224]
hi All, This is not a bug but a question I could not find the information for.

I'm trying to have a using ksql and a registry using protobuf and I've seen this is already merged
https://github.com/confluentinc/ksql/pull/4469

but I did not find any image for the 5.5.1 release.
I noticed all the other components of confluent I wanted to use are in release 5.5.1 but I could not find this one, and honestly I also would not know where to check.

This is the image I'm looking for https://hub.docker.com/r/confluentinc/cp-ksql-server/tags but it seems there is nothing there.
I'm wondering if maybe now it goes by a different name?
I could also not find it for the ksql-cli https://hub.docker.com/r/confluentinc/cp-ksql-cli/tags both seem just be in release 5.4.2

Did I miss understood which release is supporting protobuf in ksql?

**Comment by agavra** [comment]
Hello @cstmgl - ksql was renamed to ksqlDB in CP 5.5. The docker repo you are interested in is: https://hub.docker.com/r/confluentinc/cp-ksqldb-server/tags

Feel free to re-open if that doesn't answer your question!
