### ISSUE TITLE
[AVRO Support]:  add support for `AVRO` as a key format.

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#6226]
**Avro support** Adds support for the `AVRO` key format, inc. schema registry integration.
1. Allow it as key format
1. Support `KEY_AVRO_SCHEMA_FULL_NAME` and `AVRO_SCHEMA_FULL_NAME` WITH property name
   - Can we generalise these so they are generated from the `Format`'s supported properties? e.g. Given a Format `supportedProperty` of `AVRO_SCHEMA_FULL_NAME`, can we automagically convert this to `WITH` clause properties `KEY_AVRO_SCHEMA_FULL_NAME` and `VALUE_AVRO_SCHEMA_FULL_NAME` for setting separately, and `AVRO_SCHEMA_FULL_NAME` for setting both together.
1. inc. fixing https://github.com/confluentinc/ksql/issues/6132
1. Add a few test cases.
    - `elements.json`
    - negative tests to prove setting both `AVRO_SCHEMA_FULL_NAME` and either key or value specific ones fails.
1. Doc updates
     - inc. fixing https://github.com/confluentinc/ksql/issues/6131
1. Add tests to ensure inheritable key format properties, e.g. AVRO schema name, as correctly inherited, both when key format is explicitly provided, and when it is loaded from config / inherited from left-most source.

**Comment by agavra** [comment]
This is done! #6694
