### ISSUE TITLE
Is there plan to allow to connect remotely to this functionality

### ISSUE THREAD

**Issue by AssafKatz3** [confluentinc/ksql#623]
Hi,
We want to use the option to filter the topics by configuration for blue/green (This is similar to what you can see that another company did and showed at [re:Invent 2014 | (APP307) Leverage the Cloud with a Blue/Green Deployment Architecture](https://www.youtube.com/watch?v=abK2Q_aecxY)).
Is there a plan to allow to use this code to create stream/table that remote application will be able to connect to? I know that we can do similar by using Kafka Connect but this software seems to be much closer to what we want - declarative definition of filtering topics so we will be able to change the definition of topics in two commands.
Thanks

**Comment by hjafarpour** [comment]
@AssafKatz3 In KSQL you write the results into a topic. So as long as your remote apps can read from kafka topics they should be able to read KSQL streams/tables.
