### ISSUE TITLE
Docs: note that GROUP BY clause is necessary for windowing

### ISSUE THREAD

**Issue by colinhicks** [confluentinc/ksql#6299]
The [windowing documentation](https://docs.ksqldb.io/en/latest/concepts/time-and-windows-in-ksqldb-queries/#windows-in-sql-queries) does not explicitly state that windowing queries must group by the keys selected by the query.

This can cause unexpected behavior when the queries are consumed.

**Comment by JimGalasyn** [comment]
Fixed in https://github.com/confluentinc/ksql/pull/6364.
