### ISSUE TITLE
Connecting to server URL without port results in CLI error

### ISSUE THREAD

**Issue by mikebin** [confluentinc/ksql#6319]
**Describe the bug**
Connecting to a server URL without a port number (defaulting to 80 or 443) results in an error: `Server URL must begin with protocol (e.g., http:// or https://)` in ksqlDB 6.0.0.

**To Reproduce**
Steps to reproduce the behavior, include:
Version: 6.0.0 (CLI and Server)

`ksql http://localhost`

```
                  ===========================================
                  =       _              _ ____  ____       =
                  =      | | _____  __ _| |  _ \| __ )      =
                  =      | |/ / __|/ _` | | | | |  _ \      =
                  =      |   <\__ \ (_| | | |_| | |_) |     =
                  =      |_|\_\___/\__, |_|____/|____/      =
                  =                   |_|                   =
                  =  Event Streaming Database purpose-built =
                  =        for stream processing apps       =
                  ===========================================

Copyright 2017-2020 Confluent Inc.

CLI v6.0.0, Server v<unknown> located at http://localhost

Having trouble? Type 'help' (case-insensitive) for a rundown of how things work!

Server URL must begin with protocol (e.g., http:// or https://)
ksql> show topics;
port p must be in range 0 <= p <= 65535
```

**Expected behavior**
Successful connection using standard implicit port (80 or 443).

**Actual behaviour**
See above.

**Additional context**
Workaround is to add the implicit port number to the URL:

```
ksql http://localhost:80
```

This issue does not occur in earlier CLI versions.

**Comment by AlanConfluent** [comment]
Is this a regression?

**Comment by mikebin** [comment]
Seems to be, port number is not required in CLI 5.5.1
