### ISSUE TITLE
[DELIMITED]: support user defined delimiter for keys

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#6342]
ksqlDB already supports `value_delimiter` for supplying a delimiter to the value format. WIth structured keys it should support `key_delimiter` and maybe just `delimiter`.

Joins should fail if the delimiter is different and there is more than one key column.

Rather than just hacking these with clause properties in, we should probably take the time to _design_ how a `Format` can declare properties that can be set in the WITH clause.  (This will be necessary for user-defined-formats).

My view would be that the `Format` defines the set of properties, (as it does today), e.g. `DelimitedFormat`'s `DELIMITER`, or `AvroFormat`'s  full schema name.  Then when we validate the WITH properties we use some rules to wire up the property to the format.  For example, `value_delimiter` is valid if the value format is `delimited`, `key_delimiter` if the key format is `delimited` and just `delimiter` if both are `delimited`.  

To put this another way, we define the valid properties as `key_<key-format-property-name>`, `value_<value-format-property-name>, and if both key and value match then allow `<format-property-name>`.

This will likely mean some existing WITH property names change - we should support both old and new names, but update all the docs and examples to use new names.  Looking to age out the old names in time.

**Comment by agavra** [comment]
There's probably still validity in this ticket (taking time to design a better way to define the format information), but the use case is now accounted for in #6745. Closing this out as the issue itself is addressed.
