### ISSUE TITLE
EXTRACTJSONFIELD into multiple columns

### ISSUE THREAD

**Issue by ashish-padakannaya** [confluentinc/ksql#6387]
**Provide details of the setup you're running**
KsqlDB version:  confluentinc/ksqldb-server:0.12.0

**Outline your question**
In the [EXTRACTJSONFIELD](https://docs.ksqldb.io/en/latest/developer-guide/ksqldb-reference/scalar-functions/#extractjsonfield) is it possible to split extractions into different columns?

I have a UDF `getClasses` that returns the following JSON.
```
{
      "spam": "1",
      "fourclass": "2",
      "sentiment": "3"
}
```
I need spam, four-class, and sentiment in separate columns, so I end up creating an intermediate stream with column `classes`, store the entire message JSON in it and use another stream with `EXTRACTJSONFIELD` to split fields into their specific columns. 

Is there any way I can use `EXTRACTJSONFIELD` and split it into columns directly and avoid using an intermediate stream/topic?

**Comment by spena** [comment]
Hi @ashish-padakannaya,

There are no functions in ksqlDB that allows you to do that. The `EXTRACTJSONFIELD` is just a UDF that accepts and returns one row and one column. I looked into the different functions we support, and there's nothing that allows you to do it in one function. You'll have to create the separate stream unfortunately.

**Comment by ashish-padakannaya** [comment]
Bummer. Thanks for confirming @spena !
