### ISSUE TITLE
Fix pull query performance regression

### ISSUE THREAD

**Issue by agavra** [confluentinc/ksql#6407]
https://github.com/confluentinc/ksql/pull/6261 introduced a (~50%) regression in pull query performance. We should make sure not to release 0.14 until we've resolved this (and put in corresponding automated guards to make sure this doesn't happen again).

We have a PR to revert the change https://github.com/confluentinc/ksql/pull/6401 that we will backport to 0.13 but we still need to figure out why and either fix forward or revert it in master before cutting 0.14. Master is currently broken, so we can't merge it in cleanly.

Creating this issue to make sure this task isn't forgotten before cutting 0.14

**Comment by vpapavas** [comment]
This is the flamegraph of the reverted code where pull queries have 3K qps
[reverted-pksqlc-21871-ksql-0-1602288077-60s-cpu.pdf](https://github.com/confluentinc/ksql/files/5374932/reverted-pksqlc-21871-ksql-0-1602288077-60s-cpu.pdf)

This is the flamegraph of master where pull queries have 1.5K qps
[master-pksqlc-pj50o-ksql-0-1602214140-60s-cpu.pdf](https://github.com/confluentinc/ksql/files/5374933/master-pksqlc-pj50o-ksql-0-1602214140-60s-cpu.pdf)

I have the files in svg locally but cannot upload them to GH.
