### ISSUE TITLE
Adopt scala client deprecation & migration to kafka java client

### ISSUE THREAD

**Issue by bluemonk3y** [confluentinc/ksql#642]
WRT KafkaConsumerGroupClientImpl

This functionality will very shortly be added to the java admin client, maybe even in the upcoming 1.1. release: https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=74686265

Also, the Scala admin client is on the path to deprecation.

**Comment by apurvam** [comment]
KIP-222 is now available. We should follow up and drop the dependency on the scala admin client for listing consumer groups.

This can be done concurrently with implementing #1268 .

**Comment by ijuma** [comment]
Take a look at https://github.com/apache/kafka/pull/5032 for an example of how to implement the relevant functionality using the Java AdminClient.
