### ISSUE TITLE
QTT should support partial schema inference

### ISSUE THREAD

**Issue by agavra** [confluentinc/ksql#6441]
We generate the topic information from the CT/CS statement if there is no topic node in the QTT. The problem is, in the case when both key and value are AVRO, that if we have either the key or the value schema we need both in the topic node because otherwise it won't generate the topic from the CT statement and use the one supplied (and we get a 404 when looking up the schema in SR). 

The test below fails with 404 from SR unless we add in the valueSchema into the topic node.
```json
    {
      "name": "BOOLEAN - key - inference",
      "properties": {
        "ksql.key.format.enabled": true
      },
      "statements": [
        "CREATE STREAM INPUT (foo INT) WITH (kafka_topic='input_topic', format='AVRO');",
        "CREATE STREAM OUTPUT AS SELECT * FROM INPUT;"
      ],
      "topics": [
        {
          "name": "input_topic",
          "keySchema": {"type": "boolean"},
          "keyFormat": "AVRO"
        }
      ],
      "inputs": [
        {"topic": "input_topic", "key": true, "value": {"FOO": 10}},
        {"topic": "input_topic", "value": null}
      ],
      "outputs": [
        {"topic": "OUTPUT", "key": true, "value": {"FOO": 10}},
        {"topic": "OUTPUT", "value": null}
      ]
    },
```

_Originally posted by @agavra in https://github.com/confluentinc/ksql/pull/6432#discussion_r505647275_

**Comment by fjbecerra** [comment]
Hi @agavra , I just raised a PR on this issue, Im happy to be assigned. thanks

**Comment by agavra** [comment]
Thanks @fjbecerra - appreciate it! I'll take a look at your PR today
