### ISSUE TITLE
[AVRO SUPPORT] Avoid record name clashes

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#6465]
The value schema generated for Avro values has a constant default record name of `io.confluent.ksql.avro_schemas.KsqlDataSourceSchema`.

This is lame. 

The record name becomes the Java class name if anyone downstream generated Java types from the schema. (The same is similar for other programming languages which can generate types from Avro schemas too).

So if a downstream consumer of ksqlDB created topics wants to generate java types and consume multiple topics they run into issues because all the schemas generate a class called `KsqlDataSourceSchema`.

To get around this issue, way back when, support for overriding the default name was added via the `WITH(VALUE_AVRO_SCHEMA_FULL_NAME='some.full.name')`.

This is slightly less lame.

With the support for AVRO keys, the default behaviour will be for both the key and value schemas to generate types called `KsqlDataSourceSchema`, meaning a downstream app can't even generate types so it can deserialize both the key and the value from a single topic without running into a name clash!  

We could introduce `KEY_AVRO_SCHEMA_FULL_NAME`.  Quickest solution... and lame.

I propose we default the name of the record in the key schema to `<sourceNameInCamelCase>Key`, e.g. for a source named `BOB`, the record in the key schema would be called `BobKey`.

Note: we want camel casing here!

**Be use to add test cases with nests STRUCT and MAP types as these generate nested records - which also need decent and unique names.**

Given value schema properties are part of the query plan, we can also change the value schemas so they too benefit from this lame-removing change!!!!

**Comment by agavra** [comment]
This should have been closed with #6609
