### ISSUE TITLE
Confirm change in output due to KS change is intentional

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#6496]
Outstanding question around whether the upstream change identified in PR https://github.com/confluentinc/ksql/pull/6486 is intentional or not.

Note, https://github.com/confluentinc/ksql/pull/6486 was merged to get the build green, but we should be happy the change is intentional before releasing. (It likely is).

**Comment by mjsax** [comment]
As discussed on the PR, the _new_ behavior seems actually to be correct, while the _old_ behavior seems incorrect. Thus, the question is, what is the next step? Do we need to dig into it?

**Comment by agavra** [comment]
Talked offline with @vvcephei and @colinhicks, given that the default deployment involves buffering this change is likely to affect very few production use cases as there was already some nondeterminism. Definitely something that would be good to dig into, so I'll bump this down to a P1, but I suspect the ROI of blocking 0.14 on investigating why it changed is low.

**Comment by big-andy-coates** [comment]
I've looked into my crystal ball and checked with the tea leaves.... and I predict this issue will still be open whence next the nights draw long.  Happy halloweeeeeeen.

**Comment by big-andy-coates** [comment]
If we're not looking into the issue before releasing 0.14, then I actually don't see any point in looking into it at all.

The reason the ticket was raised was because we don't understand why the output has changed.  So either we're worried that something may have changed that going to cause users issues or we're not.  If we're worried, then we shouldn't release without getting to the bottom of this. If we're not, and we release, then there's little value in later going back to check if our call was correct - it's already too late to do anything about it.

**Comment by agavra** [comment]
I think what @big-andy-coates is saying is reasonable, I'm closing out this ticket.
