### ISSUE TITLE
Confirm removal of state store after upstream change is safe

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#6497]
PR https://github.com/confluentinc/ksql/pull/6487 updates our historic test plans to get the build passing again. The change removes some statestores used to materialize tables.  As documented in the PR, I *think* this change is safe, i.e. won't cause compatibility issues or results in missed/dropped messages when users upgrade.

The above PR is being merged to fix the build. The outstanding questions from the PR are tracked by this issue and should be answered before release.

**Comment by mjsax** [comment]
As commented on the PR, if there are two state stores with the same data, and the first one is dropped as redundant, it seems to be a safe change to me.

**Comment by big-andy-coates** [comment]
Cool. Glad we're in agreement!  Closing...
