### ISSUE TITLE
Container name to be removed for the scaling to work

### ISSUE THREAD

**Issue by vinay-thakkar** [confluentinc/ksql#6519]
https://github.com/confluentinc/ksql/blob/6a0c29014a0d521d21a85456eb42f751d4ee21e3/docker-compose.yml#L77
https://docs.docker.com/compose/compose-file/#container_name

Error:
Cannot create container for service
The container name is already in use by container. 
You have to remove (or rename) that container to be able to reuse that name.

**Comment by vcrfxia** [comment]
Hi @vinay-thakkar , thanks for raising this! I've opened a PR to fix the issue: https://github.com/confluentinc/ksql/pull/6526
