### ISSUE TITLE
Support for allOf JSON schema references is very limited

### ISSUE THREAD

**Issue by haf** [confluentinc/ksql#6521]
**Describe the bug**
ksqlDB doesn't support allOf JSON schema references.

Having allOf refs would be useful in order to compose schemas. E.g. if I have a base message type, I want to do allOf: base.schema.json in all my submessages.

**To Reproduce**
Steps to reproduce the behavior, include:
1. The version of KSQL. 0.12
2. Sample source data: https://app.logary.tech/schemas/identify-user-message.schema.json
3. Any SQL statements you ran. None

**Expected behavior**
I would expect it to do a recursive merge of all properties into the "reference scope"; if then those properties combine in an invalid way, that would be up the programmer to fix.

**Actual behaviour**
A clear and concise description of what actually happens, including:
1. ksqlDB log output (and also returned in response) " Unable to verify if the schema for topic messages-raw is compatible with KSQL. Reason: Unsupported criterion allOf for ..."
2. Statement: `create stream firehose with (kafka_topic='messages-raw', value_format='json_sr');`

**Comment by vcrfxia** [comment]
Hi @haf , thanks for raising this. I've filed a corresponding GitHub issue in the Schema Registry project, as ksqlDB uses the Schema Registry JSON schema converter out of the box: https://github.com/confluentinc/schema-registry/issues/1671

**Comment by rayokota** [comment]
A fix for the JSON schema converter has been merged https://github.com/confluentinc/schema-registry/pull/2107

**Comment by spena** [comment]
I run a quick test with the schema used here (https://github.com/confluentinc/schema-registry/issues/1671#issuecomment-990592348).

I created a stream, but the STRUCT columns (`CONTEXT`, `GAUGES`, `FIELDS`) do not contain any of the fields mentioned in in https://app.causiq.com/schemas/logary-message-base.schema.json
```
ksql> create stream test2 with (kafka_topic='test2', value_format='json_sr');

 Message        
----------------
 Stream created 
----------------
ksql> describe test2;

Name                 : TEST2
 Field        | Type            
--------------------------------
 LEVEL        | VARCHAR(STRING) 
 NAME         | VARCHAR(STRING) 
 CONTEXT      | STRUCT<>        
 RECEIVED     | DOUBLE          
 GAUGES       | STRUCT<>        
 ID           | VARCHAR(STRING) 
 TYPE         | VARCHAR(STRING) 
 FIELDS       | STRUCT<>        
 PARENTSPANID | VARCHAR(STRING) 
 TIMESTAMP    | DOUBLE          
 NEWUSERID    | VARCHAR(STRING) 
 PREVUSERID   | VARCHAR(STRING) 
--------------------------------
```

Unsure whether this is a SR or KSQL issue yet. Just pointing out `allOf` with references is not fully supported yet.

**Comment by haf** [comment]
Timed out
