### ISSUE TITLE
REPLACE STATEMENT

### ISSUE THREAD

**Issue by becerriljc** [confluentinc/ksql#6534]
**Describe the bug**
Replace statement not working....

**To Reproduce**
Steps to reproduce the behavior, include:
1. Install KSQLDB following this steps: **__https://docs.confluent.io/current/quickstart/ce-docker-quickstart.html#step-1-download-and-start-cp-using-docker__**

**Expected behavior**
I try to execute a **replace statement** on a stream created and return **Unknown error** by Rest API **https://docs.ksqldb.io/en/latest/developer-guide/ksqldb-rest-api/ksql-endpoint/**

CREATE [OR **REPLACE**] STREAM stream_name ( { column_name data_type [KEY] } [, ...] )
  WITH ( property_name = expression [, ...] );

Can you help me?

**Comment by agavra** [comment]
Hello @becerriljc - can you help me by letting me know which version of the server you are running? You seem to be pointing to confluent edition of ksqlDB (version 6.0) which does not have this functionality. If you want to use `CREATE OR REPLACE` you will need to either wait for 6.1 or use the community ksqlDB 0.12+ version.

**Comment by becerriljc** [comment]
Hi @agavra !!!

Thank u very much, I'm using confluent edition of ksqlDB version 6.0  for production. I tried to use the community ksqlDB 0.12.0 version and it works fine for develop environment. I will wait for the confluent edition 6.1 version to implement REPLACE statement!

Best regards!
