### ISSUE TITLE
fails to build 0.12.0-ksqldb

### ISSUE THREAD

**Issue by VisionaryAries** [confluentinc/ksql#6536]
**Describe the bug**
failes to build 0.12.0 ksqldb

**To Reproduce**
Steps to reproduce the behavior, include:
1. wget https://github.com/confluentinc/ksql/archive/0.12.0-ksqldb.zip
2. mvn clean package -DskipTests

**Expected behavior**
it builds

**Actual behaviour**
build fails with the following errors:
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for ksqldb-parent 6.1.0-SNAPSHOT:
[INFO] 
[INFO] ksqldb-parent ...................................... SUCCESS [ 24.813 s]
[INFO] ksqldb-test-util ................................... FAILURE [ 16.552 s]
[INFO] ksqldb-udf ......................................... SKIPPED
[INFO] ksqldb-common ...................................... SKIPPED
[INFO] ksqlDB UDF / UDAF :: Quickstart .................... SKIPPED
[INFO] ksqldb-serde ....................................... SKIPPED
[INFO] ksqldb-rest-model .................................. SKIPPED
[INFO] ksqldb-execution ................................... SKIPPED
[INFO] ksqldb-metastore ................................... SKIPPED
[INFO] ksqldb-parser ...................................... SKIPPED
[INFO] ksqldb-streams ..................................... SKIPPED
[INFO] ksqldb-engine ...................................... SKIPPED
[INFO] ksqldb-tools ....................................... SKIPPED
[INFO] ksqldb-rest-client ................................. SKIPPED
[INFO] ksqldb-version-metrics-client ...................... SKIPPED
[INFO] ksqldb-rest-app .................................... SKIPPED
[INFO] ksqldb-cli ......................................... SKIPPED
[INFO] ksqldb-examples .................................... SKIPPED
[INFO] ksqldb-console-scripts ............................. SKIPPED
[INFO] ksqldb-etc ......................................... SKIPPED
[INFO] ksqldb-functional-tests ............................ SKIPPED
[INFO] ksqldb-package ..................................... SKIPPED
[INFO] ksqldb-benchmark ................................... SKIPPED
[INFO] ksqlDB RocksDB Config Setter ....................... SKIPPED
[INFO] ksqldb-docker ...................................... SKIPPED
[INFO] ksqldb-api-reactive-streams-tck .................... SKIPPED
[INFO] ksqldb-api-client .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  42.458 s
[INFO] Finished at: 2020-10-28T21:33:03+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project ksqldb-test-util: Could not resolve dependencies for project io.confluent.ksql:ksqldb-test-util:jar:6.1.0-SNAPSHOT: The following artifacts could not be resolved: org.apache.kafka:kafka_2.13:jar:6.1.0-ccs-beta200825192044-hf-1, org.apache.kafka:kafka_2.13:jar:test:6.1.0-ccs-beta200825192044-hf-1, org.apache.kafka:kafka-clients:jar:6.1.0-ccs-beta200825192044-hf-1, org.apache.kafka:kafka-clients:jar:test:6.1.0-ccs-beta200825192044-hf-1: Could not find artifact org.apache.kafka:kafka_2.13:jar:6.1.0-ccs-beta200825192044-hf-1 in confluent (https://packages.confluent.io/maven/) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :ksqldb-test-util

**Additional context**
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/share/maven
Java version: 1.8.0_261, vendor: Oracle Corporation, runtime: /usr/share/jdk1.8.0_261/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "3.10.0-957.el7.x86_64", arch: "amd64", family: "unix"

**Comment by agavra** [comment]
Hello @VisionaryAries - we depend on beta artifacts of kafka for our community releases. If you want to build from source, you need to use the tag (https://github.com/confluentinc/ksql/tree/v0.12.0-ksqldb) and you need to build it with `-s maven-settings.xml` (which is supplied in the root of the project, e.g. https://github.com/confluentinc/ksql/blob/v0.12.0-ksqldb/maven-settings.xml)

**Comment by VisionaryAries** [comment]
Thanks @agavra - I , I successfully build from the source code as your instructions.

The all steps are as following:

1. wget https://codeload.github.com/confluentinc/ksql/tar.gz/v0.12.0-ksqldb
2. vi pom.xml, add  `<skip>true</skip>`  in the following configuration, or will fail to build with error 'Maven cannot find .git (dotGitDirectory)'
```
<plugin>
                <groupId>pl.project13.maven</groupId>
                <artifactId>git-commit-id-plugin</artifactId>
                <version>${git-commit-id-plugin.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>revision</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <dotGitDirectory>${project.basedir}/.git</dotGitDirectory>
                    <skip>true</skip>
                    <generateGitPropertiesFile>true</generateGitPropertiesFile>
                    <generateGitPropertiesFilename>${project.build.outputDirectory}/git.properties</generateGitPropertiesFilename>
                </configuration>
            </plugin>
        </plugins>
```
3. mvn clean package -DskipTests -s maven-settings.xml

**Comment by agavra** [comment]
Great! Thanks for posting that information. I'll close the ticket, but feel free to open a new one if any other problems come up.
