### ISSUE TITLE
KSQL select * or insert alters the avro fields into optional

### ISSUE THREAD

**Issue by rahulbats** [confluentinc/ksql#6554]
**Describe the bug**
if i create stream from another AVRO stream using select * , its making the required fields optional? 
If i do insert into AVRO stream KSQL adds another version making fields optional

**To Reproduce**
Steps to reproduce the behavior, include:
1. The version of KSQL. 0.12.0
2. Sample source data.
  i created a source topic with this schema 
```
{
  "doc": "Sample schema to help you get started.",
  "fields": [
    {
      "doc": "The int type is a 32-bit signed integer.",
      "name": "myField1",
      "type": "int"
    },
    {
      "doc": "The double type is a double precision (64-bit) IEEE 754 floating-point number.",
      "name": "myField2",
      "type": "double"
    }
  ],
  "name": "value_test_required",
  "namespace": "com.mycorp.mynamespace",
  "type": "record"
}
```
3. Any SQL statements you ran
CREATE STREAM test_required_stream with(KAFKA_TOPIC='test_required', VALUE_FORMAT='AVRO');
create STREAM TEST_REQUIRED_BECOMES_OPTIONAL as select * from test_required_stream;

**Expected behavior**
the schema of TEST_REQUIRED_BECOMES_OPTIONAL should maintain the same schema

**Actual behaviour**
A clear and concise description of what actually happens, including:
the schema of TEST_REQUIRED_BECOMES_OPTIONAL is 
```
{
  "connect.name": "io.confluent.ksql.avro_schemas.KsqlDataSourceSchema",
  "fields": [
    {
      "default": null,
      "name": "MYFIELD1",
      "type": [
        "null",
        "int"
      ]
    },
    {
      "default": null,
      "name": "MYFIELD2",
      "type": [
        "null",
        "double"
      ]
    }
  ],
  "name": "KsqlDataSourceSchema",
  "namespace": "io.confluent.ksql.avro_schemas",
  "type": "record"
}
```

**Additional context**
Same thing happens if i run KSQL `insert into`. This time new version is added into source topic making the fields optional

**Comment by agavra** [comment]
Hello @rahulbats, thanks for the feedback! This is because ksql does not yet support `NOT NULL` fields (see #4436). I'm going to close this issue as a duplicate, feel free to track the other one.
