### ISSUE TITLE
Broken links in clients section

### ISSUE THREAD

**Issue by MichaelDrogalis** [confluentinc/ksql#6562]
We have a couple broken links in our [contributing clients docs](https://docs.ksqldb.io/en/latest/developer-guide/ksqldb-clients/contributing/).

- KsqlObject: dead link to https://docs.ksqldb.io/en/latest/developer-guide/ksqldb-clients/contributing/api/io/confluent/ksql/api/client/KsqlObject.html
- ClientOptions: dead link to https://docs.ksqldb.io/en/latest/developer-guide/ksqldb-clients/contributing/api/io/confluent/ksql/api/client/ClientOptions.html
- Creating a client instance: dead link to https://docs.ksqldb.io/en/latest/developer-guide/ksqldb-clients/contributing/api/io/confluent/ksql/api/client/Client.html#create(io.confluent.ksql.api.client.ClientOptions)
- KILIP: dead link to https://docs.ksqldb.io/en/latest/design-proposals/README.md

**Comment by vcrfxia** [comment]
Hey @MichaelDrogalis , thanks for calling this out! I've opened a PR with a fix, hoping to have it live soon.

**Comment by vcrfxia** [comment]
PR has been merged and cherry-picked to relevant branches.
