### ISSUE TITLE
Add NULLIF function

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#6567]
It would be useful if ksqlDB had a `NULLIF` function, as common across SQL in other platforms.

[Example from postgres](https://www.postgresql.org/docs/7.1/functions-conditional.html):

> `NULLIF(value1, value2)`
> _The NULLIF function returns NULL if and only if value1 and value2 are equal. Otherwise it returns value1._

**Comment by fjbecerra** [comment]
Hi, just raised a [PR](https://github.com/confluentinc/ksql/pull/6685) on this one, happy to be assigned. Thanks!

**Comment by vcrfxia** [comment]
PR has been merged. Marking this issue as done. Thanks @fjbecerra !
