### ISSUE TITLE
LATEST_BY_OFFSET should support all datatypes

### ISSUE THREAD

**Issue by axaluss** [confluentinc/ksql#6610]
**Is your feature request related to a problem? Please describe.**
LATEST_BY_OFFSET should support all datatypes. Atm it only supports primitive datatypes. 

**Describe the solution you'd like**
LATEST_BY_OFFSET should support all datatypes.
Primitive types
Decimal type
Array type
Map type
Struct type
Custom types

**Comment by big-andy-coates** [comment]
duplicate of https://github.com/confluentinc/ksql/issues/5437
