### ISSUE TITLE
External Connect integration over HTTPS doesn't work

### ISSUE THREAD

**Issue by mikebin** [confluentinc/ksql#6631]
**Describe the bug**
Integrating ksqlDB with an external Kafka Connect cluster doesn't seem to work with HTTPS, at least when a custom truststore is needed. There are no configuration properties available to specify SSL settings for the HTTPS connection, such as truststore location. Even configuring the truststore location through JVM system properties (`KSQL_OPTS`) does not appear to work.

**To Reproduce**
Configure `ksql.connect.url` to point to an external Connect cluster that uses HTTPS with a self-signed certificate (requiring a custom truststore on the ksqlDB side).

Run `SHOW CONNECTORS;`

**Expected behavior**
Successful connection and response.

**Actual behaviour**
```
io.confluent.ksql.util.KsqlServerException: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

**Comment by abraham-leal** [comment]
+1, Hitting this issue as described when setting up https on the external connect cluster and enabling Confluent RBAC on both components with Confluent Platform 6.2. We tried passing through the TLS config through `ksql.connect.*` prefixes but they don't seem to hold.

**Comment by agavra** [comment]
re-labeling this needs-triage given demand we've recently seen

**Comment by reneveyj** [comment]
Recently upgraded to 6.2.0 with mTLS using Ansible files. Same behavior.
