### ISSUE TITLE
Add schemaProvider functionality to UDAFs

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#6638]
Both UDFs and UDTFs support calling a method to obtain the return type of a function by setting a `schemaProvider`.  This can be very useful when working with generic or Struct parameters.  However, UDAFs have no such capability and this is stopping people writing UDAFs that work with more generic / structured typed.

UDAFs support input, aggregate and output schemas. Likely, we'd need a schema provider method for the last two. Maybe the first?

This work should probably be done at the same time as [extending UDAFs to support multiple parameters](https://github.com/confluentinc/ksql/issues/5747)

**Comment by big-andy-coates** [comment]
Needed to fixc https://github.com/confluentinc/ksql/issues/5437

**Comment by jnh5y** [comment]
https://github.com/confluentinc/ksql/pull/8871 and https://github.com/confluentinc/ksql/pull/8896 should cover this issue.
