### ISSUE TITLE
include ksqldb-rocksdb-config-setter in ksqldb-server docker image

### ISSUE THREAD

**Issue by rodesai** [confluentinc/ksql#6644]
Currently we don't include ksqldb-rocksdb-config-setter in the ksqldb-server docker image. This makes it hard for users to use it to configure ksql with a memory bound. We should fix this and include the config setter by default.

As a workaround, users could copy the jar directly from the s3 maven repo at:
`https://ksqldb-maven.s3-us-west-2.amazonaws.com/maven/io/confluent/ksql/ksqldb-rocksdb-config-setter/<ksqldb version>/ksqldb-rocksdb-config-setter-<ksqldb version>.jar`

**Comment by vcrfxia** [comment]
Closing as a dup of https://github.com/confluentinc/ksql/issues/6838
