### ISSUE TITLE
create stream syntax did not create the same partition number as the number of partitions of the input stream/table used.

### ISSUE THREAD

**Issue by hchiuzhuo** [confluentinc/ksql#672]
According to [ksql-doc](https://github.com/confluentinc/ksql/blob/master/docs/syntax-reference.md), if the "partition" property is not specified in the create stream syntax, the number of partitions of the input stream/table will be used. However, when we run the test, we found the result did not go well as we expected. 
```
CREATE STREAM pageviews_valid \
  WITH (timestamp='logtime', \
        kafka_topic='pageviews_valid',
        value_format='DELIMITED') AS \
  SELECT rowtime as logtime, *  
  FROM pageviews_original \
  [WHERE userid like 'User_%' AND pageid like 'Page_%' \]
```

The _pageviews_original_ stream maps to kafka topic _pageviews_, which in default has 2 partitions. When we create a _pageviews_valid_ stream by selecting from _pageviews_original_, ksql creates 4 partitions instead of 2 partitions. 

```
//Partition result of stream pageviews_valid
# docker-compose exec kafka kafka-topics --zookeeper zookeeper:32181 --describe
Topic:pageviews    PartitionCount:2    ReplicationFactor:1    Configs:
    Topic: pageviews    Partition: 0    Leader: 1    Replicas: 1    Isr: 1
    Topic: pageviews    Partition: 1    Leader: 1    Replicas: 1    Isr: 1
Topic:pageviews_valid    PartitionCount:4    ReplicationFactor:1    Configs:
    Topic: pageviews_valid    Partition: 0    Leader: 1    Replicas: 1    Isr: 1
    Topic: pageviews_valid    Partition: 1    Leader: 1    Replicas: 1    Isr: 1
    Topic: pageviews_valid    Partition: 2    Leader: 1    Replicas: 1    Isr: 1
    Topic: pageviews_valid    Partition: 3    Leader: 1    Replicas: 1    Isr: 1
```
Currently, we need to specify the partition number in the create stream syntax to achieve our expectation.  Please let us know if there is any config that we did not set up correctly.

**Comment by big-andy-coates** [comment]
Yep, we need to update the docs.

**Comment by big-andy-coates** [comment]
Doc change made.
