### ISSUE TITLE
Issue with ksqldb Java client and remote requests

### ISSUE THREAD

**Issue by tmbull** [confluentinc/ksql#6728]
I searched for existing questions, but I could not find an answer. 

**Provide details of the setup you're running**
I am running ksqldb 0.13.0 via docker-compose. You can find my docker-compose file here:

https://gist.github.com/tmbull/8c5f9eaa1ee1707cd0f96f4634479cf6

I have experienced the behavior against the docker-compose file running on my local MacBook as well as on a Ubuntu 20.04 AWS EC2 instance.

**Outline your question**
I am just trying to get a basic demo working using the ksqldb java client. Code is as follows:

```java
public class KsqldbAccountAgent {

    public static String KSQLDB_SERVER_HOST = "w.x.y.z";
    public static int KSQLDB_SERVER_HOST_PORT = 8088;

    public static String KSQLDB_QUERY = "SELECT * FROM CUSTOMERSUPPLIER_BY_ACCOUNTID EMIT CHANGES;";

    public static void main(String[] args) throws ExecutionException, InterruptedException, TimeoutException {
        Logger.getRootLogger().setLevel(Level.ALL);
        Layout layout = new PatternLayout("%d [%t] %-5p %c %x - %m%n");
        Logger.getRootLogger().addAppender(new ConsoleAppender(layout));

        ClientOptions options = ClientOptions.create()
                .setHost(KSQLDB_SERVER_HOST)
                .setPort(KSQLDB_SERVER_HOST_PORT);
        Client client = Client.create(options);

        // Send requests with the client by following the other examples
        client.streamQuery(KSQLDB_QUERY)
            .thenAccept(streamedQueryResult -> {
                System.out.println("Query has started. Query ID: " + streamedQueryResult.queryID());

                RowSubscriber subscriber = new RowSubscriber();
                streamedQueryResult.subscribe(subscriber);
            }).exceptionally(e -> {
                System.out.println("Request failed: " + e);
                return null;
            });

        // Terminate any open connections and close the client
        client.close();
    }
}
```

This works as expected when running against `localhost:8088`, but fails with the following error log whenever I try to run against a remote host:

```
...
2020-12-05 10:53:48,987 [vert.x-eventloop-thread-2] DEBUG io.netty.util.Recycler  - -Dio.netty.recycler.ratio: 8
Request failed: java.util.concurrent.CompletionException: java.lang.UnsupportedOperationException: Not yet implemented
563  [vert.x-eventloop-thread-2] DEBUG io.netty.handler.codec.http2.Http2ConnectionHandler  - [id: 0xa925938e, L:/10.10.9.237:61753 - R:/54.245.197.65:8088] Sent GOAWAY: lastStreamId '0', errorCode '2', debugData 'Not yet implemented'. Forcing shutdown of the connection.
2020-12-05 10:53:49,052 [vert.x-eventloop-thread-2] DEBUG io.netty.handler.codec.http2.Http2ConnectionHandler  - [id: 0xa925938e, L:/10.10.9.237:61753 - R:/54.245.197.65:8088] Sent GOAWAY: lastStreamId '0', errorCode '2', debugData 'Not yet implemented'. Forcing shutdown of the connection.
Dec 05, 2020 10:53:49 AM io.vertx.core.net.impl.ConnectionBase
SEVERE: Not yet implemented
```

I have tracked the error down to [this line](https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/net/impl/clientconnection/Pool.java#L411) in the `vert.x` codebase, but have no idea why it is failing. I'm not very familiar with HTTP/2. I have confirmed that I can query the HTTP 1.1 APIs directly without issue (either remote or local), so it does not seem to be a networking issue. Any help is appreciated.

**Comment by vcrfxia** [comment]
Hey @tmbull , have you tried commenting out the `client.close();` call at the end of your script? The `client.streamQuery(...)` is asynchronous, so it seems plausible that your script is closing the client before the response from your remote server can be processed, and a race condition is producing the error you've observed.

**Comment by tmbull** [comment]
Hi @vcrfxia, thank you for the reply. I just tried commenting out the `client.close();` and unfortunately that did not change the behavior. The same exception is still being thrown.

**Comment by jzaralim** [comment]
Hi @tmbull I tried running the docker compose file on a Ubuntu laptop and the Java client on a MacBook with IntelliJ and  was not able to reproduce the error. I had the Ubuntu laptop set up with no auth and was running the client with Java 8.

**Comment by tmbull** [comment]
@jzaralim Thank you for taking the time to try it out yourself. I will go ahead and close this. It sounds like this is some issue with my environment. I've switched over to using Kafka streams due to #2415 being a hard blocker for my use case.
