### ISSUE TITLE
Set and list against ksql.streams.topic.* prefixed properties is not working

### ISSUE THREAD

**Issue by spena** [confluentinc/ksql#6734]
**Describe the bug**
The properties prefixed with `ksql.streams.topic.*` are not listed with `LIST PROPERTIES` and cannot be set from CLI sessions either.

There is a confusion whether these properties should be listed or not. There is a fix to allow the streams topic prefix configs can be configured https://github.com/confluentinc/ksql/pull/3691 from the properties file. However, the `KsqlConfigResolver.java` has code with a difference on the topics to resolve and not.

These configs are resolved, which do not contain the topic prefix:
```
private static final List<PrefixedConfig> STREAM_CONFIG_DEFS = ImmutableList.of(
      new PrefixedConfig(StreamsConfig.CONSUMER_PREFIX, CONSUMER_CONFIG_DEF),
      new PrefixedConfig(StreamsConfig.PRODUCER_PREFIX, PRODUCER_CONFIG_DEF),
      new PrefixedConfig("", CONSUMER_CONFIG_DEF),
      new PrefixedConfig("", PRODUCER_CONFIG_DEF),
      new PrefixedConfig("", STREAMS_CONFIG_DEF)
  );
```
But in the `resolveStreamsConfig`, the topic prefix is added:
```
if (propertyName.startsWith(KSQL_STREAMS_PREFIX)
        && !propertyName.startsWith(KSQL_STREAMS_PREFIX + StreamsConfig.PRODUCER_PREFIX)
        && !propertyName.startsWith(KSQL_STREAMS_PREFIX + StreamsConfig.CONSUMER_PREFIX)
        && !propertyName.startsWith(KSQL_STREAMS_PREFIX + StreamsConfig.TOPIC_PREFIX)) {
      return Optional.empty();  // Unknown streams config
    }
```

Perhaps this is a bug, and we should add the topic prefix to the `STREAM_CONFIG_DEFS` as well.

**To Reproduce**
Use the latest master (6.2.0). Add the `ksql.streams.topic.min.insync.replicas` to the `ksql-server.properties`, and then run `list properties` from the CLI. The `ksql.streams.topic.min.insync.replicas` is not displayed.

**Expected behavior**
I'm not sure if these properties should be displayed or not, but looking at the code difference above, seems they should be displayed too.

**Comment by agavra** [comment]
Looking at the `TopicConfig` class, I think it makes sense to list these properties. At least it seems valuable to me!
