### ISSUE TITLE
NullPointerException for null records from SqlPredicate.getStringKeyPredicate

### ISSUE THREAD

**Issue by rodesai** [confluentinc/ksql#680]
When we process null rows in a stream/table, SqlPredicate.getStringKeyPredicate logs a null-pointer exception. null rows are not unexpected. They can be emitted by streams for example when a filter fails. We should handle them more gracefully.

**Comment by bluemonk3y** [comment]
Fixed in https://github.com/confluentinc/ksql/pull/739

**Comment by bluemonk3y** [comment]
@rodesai - can you confirm pls.

**Comment by rodesai** [comment]
ack - looking now

**Comment by rmoff** [comment]
@rodesai @blueedgenick is this still an issue, or can it be closed?
