### ISSUE TITLE
Cast to bigint for stream returning null

### ISSUE THREAD

**Issue by jbdoster** [confluentinc/ksql#6805]
**Distributor ID: Ubuntu**
**Description:    Ubuntu 20.04.1 LTS**
**Release:        20.04**
**Codename:       focal**

**Ksql-server Docker Image: confluentinc/cp-ksqldb-server:6.0.0**

Hello!

This is a fantastic product. 
My end goal is to follow this doc:
https://docs.ksqldb.io/en/latest/developer-guide/syntax-reference/#tables

And properly cast a string value (from a message payload that is not the message key) to a BIGINT and create a new stream from that. (This is the part I am currently having an issue with)
**Ultimately** I would like to have a materialized cache updating by each indexed row

By chance, does any one know what I am doing wrong?

**Queries and output**
`    CREATE STREAM users_with_wrong_key2 (
      alias_account_id STRING,
      user_id VARCHAR
   ) WITH (
      KAFKA_TOPIC='x', 
      VALUE_FORMAT='JSON'
   );`

![first-stream](https://user-images.githubusercontent.com/31192968/102674334-e6309780-4152-11eb-8b4f-7dfe2074fe3a.png)

`CREATE STREAM users_with_proper_key2
   WITH (KAFKA_TOPIC='users-with-proper-key') AS
   SELECT 
      CAST(alias_account_id AS BIGINT) AS alias_account_id,
      user_id
   FROM users_with_wrong_key2
   PARTITION BY CAST(alias_account_id AS BIGINT)
   EMIT CHANGES;`

![second-stream](https://user-images.githubusercontent.com/31192968/102674339-eb8de200-4152-11eb-9647-522ea887ef90.png)

Thank you

**Comment by jbdoster** [comment]
Another note

Ultimately I wanted to produce a materialized cache from the topic

Would it be better to use a query like this
`CREATE TABLE TABLE3 AS
  SELECT
    alias_account_id + ‘§’ + user_id AS composite_key,
    count(user_id) as length
  FROM users_with_wrong_key3
  GROUP BY CAST(alias_account_id AS STRING) + ‘§’ + CAST(user_id AS STRING);`
and derive from the stream "users_with_wrong_key2" this way? I tried it with the composition and just grouping by 1 column to test it but it looks like the table it populating with multiple rows of the same key:
![mv](https://user-images.githubusercontent.com/31192968/102675960-a7054500-4158-11eb-9895-db113fba1e60.png)

**Comment by vcrfxia** [comment]
Hi @jbdoster , it looks like you've figured out how to cast the `STRING` field to a `BIGINT` field, how to populate message keys from a value column using `PARTITION BY`, and how to create a materialized cache using `CREATE TABLE ... AS SELECT ... GROUP BY ...`. Which part are you still unclear on?

> it looks like the table it populating with multiple rows of the same key

This is expected as your screenshot shows you are inspecting the changelog topic underlying the ksqlDB table. The changelog topic records all updates, of which there may be multiple per key. If you're only interested in fetching the latest value for a particular key, you can use a pull query: https://docs.ksqldb.io/en/latest/concepts/queries/pull/
