### ISSUE TITLE
Wrong prefix for transient query changelog subject names in Schema Registry

### ISSUE THREAD

**Issue by mikebin** [confluentinc/ksql#6817]
**Describe the bug**
In some cases, ksqlDB may generate an invalid subject name for transient query schemas in Schema Registry. For example:

```
_confluent-ksql-default_query_1681835265420415213-KsqlTopic-Reduce-changelog-value
```

Note the missing the `transient` keyword in the subject name prefix.

In these cases, when the query terminates, the schemas are not automatically cleaned up and deleted as expected with https://github.com/confluentinc/ksql/issues/5714.

**To Reproduce**

**Expected behavior**
All schemas created as part of the transient query are hard-deleted when the query terminates.

**Actual behavior**
Misnamed schemas are not cleaned up, resulting in potential unbounded growth of registered schemas in Schema Registry

**Comment by mikebin** [comment]
cc @rodesai for additional detail

**Comment by rodesai** [comment]
Thanks for filing this @mikebin. When we create the source topology node, the deserializer we instantiate will (if the source is a windowed table, or the query is from an older version which didn't force materialization) try and create the schema if it's not already registered. This was done to paper over KAFKA-10179. When we do this the query id we generate is not correct for transient queries. We can fix this by constructing the application id before generating the final topology and add it as a property in `KsqlQueryBuilder`. Along the way, we should also refactor `KsqlQueryBuilder` and split it into separate contexts for building the physical plan and final topology.
