### ISSUE TITLE
How can i recorey stream query after i  terminate this query to avoid miss message. 

### ISSUE THREAD

**Issue by jiakai908** [confluentinc/ksql#6822]
ksql-verison: cp-5.4.1
I use terminate command to kill  this query:
`create stream xxx as select xxx from ...`.
I want recovery this query and avoid miss kafka message. how can i handle it .

**Comment by agavra** [comment]
Hello @jilakai908 - if you terminate a query, then the [consumer groups ](https://docs.confluent.io/platform/current/clients/consumer.html#consumer-groups) are removed, meaning you cannot recover it at the same point that you were previously processing.

Your only option is to restart the query from the beginning of the source topic. Note that in later versions of ksqlDB we have introduced the `CREATE OR REPLACE` functionality in a limited fashion that will let you achieve this type of behavior for some transformations.
