### ISSUE TITLE
datagen tool crashes on a class not found error using the Docker image 

### ISSUE THREAD

**Issue by sofianinho** [confluentinc/ksql#685]
Hello everyone,

I tried to use the docker image on the hub . I tried two versions: latest (which points to 0.3, I think) and 0.4-rc1. 
```
docker run -it  confluentinc/ksql-cli:0.4-rc1
```
I went through the examples on the documentation, and got and error when generating the data as explained:
```
/usr/bin/ksql-datagen quickstart=pageviews format=delimited topic=pageviews maxInterval=10000
/usr/bin/ksql-run-class: line 19: KSQL_LOG4J_OPTS: unbound variable
```
When I commented the 19th line in the script, I got this error:
```
ksql-datagen quickstart=pageviews format=delimited topic=pageviews maxInterval=10000
Error: Could not find or load main class io.confluent.ksql.datagen.DataGen
```

Any ideas ?

Thanks in advance

**Comment by apurvam** [comment]
Which documentation did you follow?

**Comment by rcillo** [comment]
@sofianinho I also had problems with "confluentinc/ksql-examples:5.0.0-beta1". Try using "confluentinc/ksql-examples:5.0.0-beta30". This did the trick for me.

**Comment by spencerdcarlson** [comment]
I am running into issues on branch `5.3.1-post` using the **examples/cp-all-in-one** docker-compose.yaml

specifically, I am attempting to run:
```bash
docker exec ksql-datagen ksql-datagen \
    bootstrap-server=broker:9092 \
    schemaRegistryUrl=schema-registry:8081 \
    format=avro \
    topic=custom.users.v1.json \
    iterations=1000000000 \
    maxInterval=100 \
    schema=/custom/schemas/user.avro \
    key=uid
```

Which results in:
```bash
Error serializing row to topic custom.users.v1.json using Converter API
```
@apurvam, @rcillo -- Any thoughts?
