### ISSUE TITLE
changelog generation is not able to handle squashed merged

### ISSUE THREAD

**Issue by rodesai** [confluentinc/ksql#6882]
Hit this when trying to generate the changelog for 0.15. When we released 0.14 we merged a bunch of changes from master into the 6.1.x and the 0.14 release branch. These changes all got squashed into one commit. Our changelog generation was subsequently not able to generate the correct changelog for 0.15 - it included all those 0.14 changes in 0.15's changelog.

I think I understand why. IIUC, the changelog generation works like this:
- use `conventional-changelog` to generate a changelog for the previous release
- use `conventional-changelog` to generate a changelog for the current release
- run `process_commit_files.py`. This script finds all the commits in the current release that aren't in the previous release. However since in this case those commits were squashed, they don't show up in the previous release's changelog and get added to the current release's

I'm not sure exactly how to fix this. It might be enough to just be careful not to squash the commits away. Another alternative might be to check the current changelog (generated by `conventional-changelog`) against the CHANGELOG.md on the release branch and remove any commits that are already in that changelog (assuming the RM for the release with squashed commits did the right thing and added those commits to the changelog manually)

**Comment by vcrfxia** [comment]
> It might be enough to just be careful not to squash the commits away.

This is my vote. We didn't discover that squashing cherrypick commits as we did when cherry-picking from master to 6.1.x ahead of the 0.14 would impact changelog generation in this way until after we'd already done it. If we'd known in advance, we could've simply not squashed the commits and then changelog generation would've been fine. As a result. auto-changelog generation is impacted for the 0.14 and 0.15 releases but that's it.

**Comment by agavra** [comment]
I'll add this to our contributing guide, but I think we need to do some work to make sure that during releases this doesn't happen. FYI @vvcephei who's running the next release.
