### ISSUE TITLE
KSQL convert rows to comma separated list with GROUP BY

### ISSUE THREAD

**Issue by vishwajeets7** [confluentinc/ksql#6957]
Have a stream column ID and Account numbers, would like to concatenate the Account# as comma separated list in one row.

Below is the query in SQL which creates the comma separated list with group by clause. (copy pasted from https://www.peteonsoftware.com/index.php/2009/12/11/creating-a-comma-separated-list-from-a-sql-grouping/)

    SELECT e.EmployeeId, e.FirstName, e.LastName,
    STUFF((SELECT ',' + COALESCE(LTRIM(RTRIM(t.TerritoryDescription)), '') 
    FROM EmployeeTerritories et
    INNER JOIN Territories t on et.TerritoryID = t.TerritoryID
    WHERE et.EmployeeID = e.EmployeeId
    FOR XML PATH('') ), 1, 1, '') as TerritoryList
    FROM Employees e

Is it possible to achieve in KSQL?

Expected output:
ID                 AccountList
1                  1001,1002,1003

**Comment by PeterLindner** [comment]
You could try [```COLLECT_LIST```](https://docs.ksqldb.io/en/latest/developer-guide/ksqldb-reference/aggregate-functions/#collect_list) or [```COLLECT_SET```](https://docs.ksqldb.io/en/latest/developer-guide/ksqldb-reference/aggregate-functions/#collect_set) together with [```ARRAY_JOIN```](https://docs.ksqldb.io/en/latest/developer-guide/ksqldb-reference/scalar-functions/#array_join). Not sure if this produces the same results in all edge cases though

**Comment by vishwajeets7** [comment]
Thank you @PeterLindner, I could get the array as a column.

I have created a table out of a stream join, to group the rows to columns. However the stream is updating the table as it runs, so ended up getting single record as a result of the group by clause.

Example:
ID AccountList
1  [1001]
1  [1002]
1  [1003]

Expecting the results as
ID  AccountList
1    [1001,1002,1003]

Understand the stream is event processing model, is there any possibility of delaying the results to the table. So I can get array of Accounts?

**Comment by PeterLindner** [comment]
@vishwajeets7 using the [current docker setup](https://ksqldb.io/quickstart.html) the following worked for me:

```sql
-- create example stream
CREATE STERAM ACCOUNTS (ID INT KEY, ACCOUNT VARCHAR) 
  WITH (KAFKA_TOPIC='accounts', VALUE_FORMAT='JSON', PARTITIONS=1, REPLICAS=1);
-- create some example records
INSERT INTO ACCOUNTS VALUES (1, '1001');
INSERT INTO ACCOUNTS VALUES (1, '1002');
INSERT INTO ACCOUNTS VALUES (1, '1003');
-- query
SELECT 
  ID, 
  ARRAY_JOIN(COLLECT_SET(ACCOUNT), ',') AS ACCOUNTLIST 
FROM ACCOUNTS 
GROUP BY ID 
EMIT CHANGES;
```
the result is:
```
+------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+ 
|ID                                                                                              |ACCOUNTLIST                                                                                     | 
+------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+ 
|1                                                                                               |1001,1002,1003                                                                                  |
```

Note that this is a [push query](https://docs.ksqldb.io/en/latest/concepts/queries/push/) and potentially streams back intermediate results.
If that's not what you want, you could also materialize this result in a new Table with:
```sql
CREATE TABLE ACCOUNTSTABLE AS 
SELECT 
  ID, 
  ARRAY_JOIN(COLLECT_SET(ACCOUNT), ',') AS ACCOUNTLIST 
FROM ACCOUNTS 
GROUP BY ID 
EMIT CHANGES;
```
and use a [pull query](https://docs.ksqldb.io/en/latest/concepts/queries/pull/) to access the data like from a conventional database table (with the same result as above):
```sql
SELECT * FROM ACCOUNTSTABLE WHERE ID = 1;
```
Note however, that table scans are not yet supported as of version 0.14, which means you have to specify a particular rowkey in the `WHERE` clause (or multiple with the `IN` operator). Table scans will be supported in the near future though.

Note also that `COLLECT_SET` does not handle deletes as far as I'm aware and there may be some other edge cases I'm not aware of. Hope this helped you, though.

**Comment by abbccdda** [comment]
Hey @vishwajeets7, I think @PeterLindner has made some good explanations here, do you think we could close this ticket?

**Comment by vishwajeets7** [comment]
Sorry for late reply, can be closed.

Thank you.
