### ISSUE TITLE
Support LIMIT Clauses in Pull Queries

### ISSUE THREAD

**Issue by agavra** [confluentinc/ksql#6962]
Now that we support table scans for pull queries (see #6726 as well as #6813) users may want to return only a few rows from the tables that they scan. We should support standard `LIMIT` syntax on pull queries.

**Comment by aonamrata** [comment]
If you are like be and come across this issue then LIMIT option is available in KSQL `"version": "0.24.0",`

**Comment by agavra** [comment]
thanks @aonamrata, this is correct! I'll close out this ticket.
