### ISSUE TITLE
CREATE OR REPLACE on 6.0.1

### ISSUE THREAD

**Issue by zeyaddeeb** [confluentinc/ksql#6968]
I was looking through the documentation for updating queries; https://docs.ksqldb.io/en/latest/concepts/upgrades/

Seems like `CREATE OR REPLACE` is not avaliable yet on `cp-ksql-server:6.0.1`.  I'm assuming it is on `6.1.0`, is there a specific timeline this would be released?

Same goes for `... EMIT FINAL;`

Thanks in advance!

**Comment by MichaelDrogalis** [comment]
Hey @zeyaddeeb. We don't pre-announce dates for Confluent Platform releases, but stay tuned. It's not too far away.

Regarding `EMIT FINAL`, that feature will continue to be hidden behind a feature flag and turned off by default. We want to do a little more work to harden it before it officially goes out the door.

**Comment by zeyaddeeb** [comment]
Sounds good. Thank you @MichaelDrogalis
