### ISSUE TITLE
LIMIT is not documented in Syntax Guide

### ISSUE THREAD

**Issue by miguno** [confluentinc/ksql#697]
We should document `LIMIT` notably because its current behavior is per-partition, so a `LIMIT 5` on topic with 2 partitions might actually show you 10 output results.

**Comment by miguno** [comment]
cc @joel-hamill 

While we are revamping the KSQL docs, we might want to cover LIMIT in the new Syntax Guide.

**Comment by joel-hamill** [comment]
@miguno please provide some more details on this command, and a JIRA issue. please do not use GH issues for docs.
