### ISSUE TITLE
KSQL tries to load dropped tables art startup

### ISSUE THREAD

**Issue by rodesai** [confluentinc/ksql#699]
User reports that KSQL is loading dropped tables at startup, which causes server (or cli in local mode) startup to take an unnecessarily long time (>15 minutes).

**Comment by apurvam** [comment]
This shouldn't be an issue any more. @dguy implemented an optimization where terminated queries and dropped streams/tables should not be loaded at startup.

I am closing this out. @dguy please reopen if I am wrong.
