### ISSUE TITLE
Function "CUSTOM_UDF" does not accept parameters (ARRAY<STRING>).

### ISSUE THREAD

**Issue by jfromaniello** [confluentinc/ksql#6991]
I am trying to build a UDF that accepts an array of strings, I tried copying [ArrayJoin.java](https://github.com/confluentinc/ksql/blob/ef32ae23f6de2ba6ebe28e16eebacb880a77434c/ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/array/ArrayJoin.java) but I still get the same error.

The versions of ksqldb-server and client are listed here:
```
CLI v0.14.0-rc732, Server v0.14.0-rc732 located at http://ksqldb-server:8088
Server Status: RUNNING
```

My class UDF looks like this:

```java
package com.testproject;

import io.confluent.ksql.function.udf.Udf;
import io.confluent.ksql.function.udf.UdfDescription;
import io.confluent.ksql.function.udf.UdfParameter;

import java.util.List;


@UdfDescription(
  name = "ARRAY_TEST",
  description = "ARRAY TEST DEMO"
)
public class ArrayTest {

  @Udf
  public <T> String test(
      @UdfParameter final List<T> input
  )  {
    return "test";
  }
}

```
I am currently linking to this dependency:
```xml
    <dependency>
      <groupId>io.confluent.ksql</groupId>
      <artifactId>ksqldb-udf</artifactId>
      <version>6.0.1</version>
    </dependency>
```

The same cases where I get the error work with `ARRAY_JOIN`.

Thank you very much in advance

**Comment by jfromaniello** [comment]
mm I figured that `@UdfParameter` must be called with the name of parameter `@UdfParameter("input")`.

This is different to what I see in native functions, but it works.

**Comment by agavra** [comment]
@jfromaniello - just so that you know, `@UdfParameter` is not required if you compile with the `-parameters` java flag (see http://openjdk.java.net/jeps/118). I'm glad you found a solution!

**Comment by jfromaniello** [comment]
Oh thank you very much!
