### ISSUE TITLE
strange characters key

### ISSUE THREAD

**Issue by alihossein** [confluentinc/ksql#7034]
I using this query to generate a table 

```
CREATE TABLE LimiteOneMinute_TB2
   WITH (kafka_topic='limitoneminute2', value_format='JSON') as
select (lr.rowkey) majmoo , AS_VALUE(cast(lr.rowkey as varchar)) inet_config, max(lr.inet) ip, (max(lr.rowtime) + 60000) expire_time, true as captcha
from LIMITER_REQUEST lr join CONFIG_TB lc on lr.configid = lc.id
WINDOW HOPPING (SIZE 59 SECONDS, ADVANCE BY 5 SECONDS)
group by (lr.rowkey)
having count(*) > max(lc.oneminute)
emit changes;
```
After running it, I saw output (limitoneminute2 topic) and I have a problem with Key. 

What are these extra characters?
How can I destroy them?

![Screenshot from 2021-02-19 17-55-58](https://user-images.githubusercontent.com/11248545/108518422-c9911700-72dd-11eb-88ba-9f23e59e17b1.png)

**Comment by mjsax** [comment]
You are doing a windowed-aggregation and thus the `ROWKEY` is a complex key containing the `GROUP BY` attributes plus the window-start timestamp (encoded as long). Thus, the data type is some internal `BYTE` format, thus what you see is expected.

What is the exact problem you face with it? It's an internal format and there is no need to worry about it.

**Comment by alihossein** [comment]
thanks @mjsax 

> What is the exact problem you face with it? It's an internal format and there is no need to worry about it.


actually, I want to update the value of the events later (by producing the new event with the same key), so I need to know the exact key of each event.

**Comment by mjsax** [comment]
Not sure if I understand... how do you intent to update the value? And where do you want to produce those new events into (same of different topic?).

You could get the window start time via `WINDOWSTART` function (cf https://docs.ksqldb.io/en/latest/developer-guide/ksqldb-reference/quick-reference/#windowstart-windowend), but it might be difficult to actually use it. ksqDB does make it tricky to work with windowed aggregation result atm -- we hope to improve this in the future.

**Comment by mjsax** [comment]
Closing this question as there was not further response. Feel free to reopen.
