### ISSUE TITLE
KSQL throws UnsupportedVersionException, broker does not support DESCRIBE_CONFIGS

### ISSUE THREAD

**Issue by vodovozovge** [confluentinc/ksql#704]
KSQL – v0.4.0
Confluent platform – 3.2.2

Following the guide here https://github.com/confluentinc/ksql/blob/0.4.x/docs/quickstart/quickstart-non-docker.md#start-ksql I received an error when trying to run `./bin/ksql-cli local`

```
[2017-12-15 17:19:20,508] ERROR Failed to initialize TopicClient: org.apache.kafka.common.errors.UnsupportedVersionException: The broker does not support
DESCRIBE_CONFIGS
```

Updating Confluent platform from 3.2.2 to 4.0.0 solved the issue

**Comment by miguno** [comment]
@vodovozovge thanks for creating the ticket!

**Comment by apurvam** [comment]
KSQL depends on CP 3.3+ and AK 0.11.0+ The compatibility matrix has been updated to reflect this.
