### ISSUE TITLE
return an error message from the http2 `/query-stream` endpoint

### ISSUE THREAD

**Issue by rodesai** [confluentinc/ksql#7054]
The `/query` and ws query endpoints for streaming back transient query results both have a mechanism for returning query-killing errors - they return the error as a final message in the stream. There is no such mechanism for the `/query-stream` endpoint, and therefore users of the endpoint have no way to figure out if their query exited on error. I think we can use the same mechanism here - return a final message that contains details about the error.

**Comment by AlanConfluent** [comment]
We have the callback to write an error, but it's not being called.  I was able to reproduce it.  Here is `/query`:

```
> curl http://localhost:8088/query -X "POST" -H "Content-Type: application/json; charset=utf-8" -d $'{ "ksql": "select * from RATINGS_TABLE where key = 10 emit changes;", "streamsProperties": {}}'
[{"header":{"queryId":"_confluent-ksql-default_transient_5993160049405637205_1624482448220","schema":"`KEY` INTEGER, `AVG_RATING` DOUBLE, `AVG_STARS` DOUBLE, `LATEST_MSG` STRING"}},
{"errorMessage":{"@type":"generic_error","error_code":50000,"message":"stream-thread [_confluent-ksql-default_transient_5993160049405637205_1624482448220-7338ea81-510d-4f42-93f1-505fb20dd278-StreamThread-2] task [0_1] Failed to flush cache of store KsqlTopic-Reduce\nCaused by: ERROR!"}},
```

On the other endpoint `/query-stream`, the error occurs and is in the logs, but doesn't trigger the error callback:
```
> curl http://localhost:8088/query-stream -X "POST" -H "Content-Type: application/json; charset=utf-8" -d $'{ "sql": "select * from RATINGS_TABLE where key = 10 emit changes;", "streamsProperties": {}}' --http2
{"queryId":"4677cd6c-664e-49ba-89d0-90ae51a0953d","columnNames":["KEY","AVG_RATING","AVG_STARS","LATEST_MSG"],"columnTypes":["INTEGER","DOUBLE","DOUBLE","STRING"]}

```
