### ISSUE TITLE
KSQL should include expected Schema name in Schema Registry error

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#707]
Per [Community Slack discussion](https://confluentcommunity.slack.com/archives/C6UJNMY67/p1518035685000101?thread_ts=1517844132.000663&cid=C6UJNMY67), currently KSQL throws an error if the Avro schema cannot be found in the Schema Registry: 

     Could not fetch the AVRO schema from schema registry. Subject not found.; error code: 40401 

A more user-friendly error would be to include the name of the schema that's expected. For example: 

     Could not fetch the Avro schema "PerFrameStats-value" from schema registry. Subject not found.; error code: 40401

**Comment by cricket007** [comment]
I would suggest

`Could not fetch the Avro schema for subject "PerFrameStats-value" from schema registry`

**Comment by rmoff** [comment]
This error message, thrown if a schema does not exist in the Schema Registry, has changed since this ticket was raised and is now even more ambiguous: 

```
ksql> create stream test14 with (kafka_topic='test14', value_format='avro');
 Unable to verify the AVRO schema is compatible with KSQL. Subject not found.; error code: 40401
ksql>
```

I would re-iterate my suggestion as given above for the message to throw if the schema cannot be found.

**Comment by cricket007** [comment]
This may be resolvable by merging https://github.com/confluentinc/schema-registry/pull/821
