### ISSUE TITLE
java.lang.IllegalArgumentException: Unsupported type specification while creating UDAF

### ISSUE THREAD

**Issue by anupsdtiwari** [confluentinc/ksql#7077]
Team

I am working on a UDAF where input is string and intermediate dataType is STRUCT and output will be Double. 
I am successfully able to build JAR but when i am restarting ksqlDB then i am getting error "java.lang.IllegalArgumentException: Unsupported type specification".

Below is the Sample code :-

public class SumContext {
	
    public static final Schema AGGREGATE_SCHEMA = SchemaBuilder.struct().optional()
            .field("SPECIALSTATUS", Schema.OPTIONAL_STRING_SCHEMA)
            .field("TOTAL", Schema.OPTIONAL_FLOAT64_SCHEMA)
            .build();

    public static final String AGGREGATE_SCHEMA_DESCRIPTOR = "STRUCT<" +
            "SPECIALSTATUS STRING," +
            "TOTAL DOUBLE," +
            ">";

    private SumContext() {
    }

    @UdafFactory(description = "Sums Integer values of stream based on a context.",
                paramSchema = "STRING",
                aggregateSchema = AGGREGATE_SCHEMA_DESCRIPTOR,
                returnSchema = "DOUBLE")
    public static Udaf<String, Struct , Double> createUdaf(String inputSeperator){
        return SumContextUdafImpl(inputSeperator);
    }

    static <T>Udaf<String, Struct , Double> SumContextUdafImpl(String inputSeperator) {
    	
    	return new Udaf<String, Struct, Double>() {
            @Override
            public Struct initialize() {
                return new Struct(AGGREGATE_SCHEMA);
            }

            @Override
            public Struct aggregate(String newValue, Struct aggregateValue) {
               // <UDAF SPECIFIC LOGIC Will be Here>
            	return aggregateValue;
            }
            @Override
            public Double map(Struct intermediate) {
                return intermediate.getFloat64("TOTAL");
            }

            @Override
            public Struct merge(Struct aggOne, Struct aggTwo) {
                return aggTwo;
            }
    	} ;
    }
}

**Comment by anupsdtiwari** [comment]
Note :- I am using ksqlDB from confluent-6.0.1 community package.

**Comment by agavra** [comment]
Whoever is taking a look at this issue should also make sure that we make the error message more actionable. Which type is causing the error? In which UDF? etc...
