### ISSUE TITLE
Feature request: support for wildcarding topic names when creating streams/tables

### ISSUE THREAD

**Issue by labedzkim** [confluentinc/ksql#708]
I personally have a need for creating a stream of multiple topics through a single DDL statement. For example: `CREATE STREAM MyStream (NAME VARCHAR) WITH (kafka_topic='*_FINISHED', value_format='JSON');`. The assumption is of course that all those topics share the same schema or at least have the _name_ attribute.

**Comment by rmoff** [comment]
@labedzkim do you have an example of the kind of use-case or data this would be useful for? 
Does the new `INSERT INTO` syntax help here? It doesn't support wildcards but it does enable you to merge multiple streams.

**Comment by labedzkim** [comment]
My intention was to use streams to debug microservices ecosystem. The idea was to simplify as much as possible the way how multiple topics can be merged into a single stream of 'something'. Those 'something' would be then used to debug the cause-and-effect sequence between microservices. I have an impression that the new INSERT INTO supports my use case but still it's not as simple as 'one command'. Personally, I'm fine if I can specify topics to be included in a stream (support for regex would be great here) and then observe a stream of JSON messages. I'm not sure if my wish fits well to the architectural and business boundaries of KSQL. Anyway, this is what I meant. Regards!

**Comment by mjsax** [comment]
Closing as duplicate.
