### ISSUE TITLE
Joining on a Struct

### ISSUE THREAD

**Issue by nomemory** [confluentinc/ksql#7114]
Hello, given I am having two streams:

```
CREATE STREAM carLocations (profileId VARCHAR, color VARCHAR, hasPapers BOOLEAN, location STRUCT<x INT, y INT>)
  WITH (kafka_topic='carLocations', value_format='json', partitions=1);

CREATE STREAM policeLocations(profileId VARCHAR, location STRUCT<x INT, y INT>)
 WITH (kafka_topic='policeCarLocations', value_format='json', partitions=1);
```

How do I create a third stream to "detect" the moment when a car has the location as the police.
Something like:

```
CREATE STREAM policeStops AS
    SELECT *
    FROM carLocations c
    INNER JOIN policeLocations p WITHIN 5 SECONDS
    ON c.location = p.location
    EMIT CHANGES;
```

But if I do the above, the following error is received:

```
Unsupported key schema: [`C_LOCATION` STRUCT<`X` INTEGER, `Y` INTEGER> KEY]
```

Is there a solution to join the two streams based on both the `.x` and the `.y` coordinates?

**Comment by mjsax** [comment]
Joins on complex types are not supported yet. -- We recently added support for complex aggregations (ie, multi-column `GROUP BY`), and we will keep extending this functionality (so we can hopefully support complex join types soon!). Cf https://www.confluent.io/blog/ksqldb-0-15-reads-more-message-keys-supports-more-data-types/

A current workaround could be, to transform the `STRUCT` into a string with some delimiter, like `location(5,6)` would become `"5_6"`.

**Comment by nomemory** [comment]
Thank you for the answer. I did as suggested. It's a valid workaround. 
Waiting to see this feature added in the future.
