### ISSUE TITLE
Add Lambda support to interpreter

### ISSUE THREAD

**Issue by AlanConfluent** [confluentinc/ksql#7124]
**Is your feature request related to a problem? Please describe.**
The interpreter currently has feature parity with the code compiler up through lambdas.  We need to eventually add support, and in the near term, ensure that users can switch back to the code compiler if they really want the feature.

**Describe the solution you'd like**
Per request enabling/disabling of the interpreter

**Describe alternatives you've considered**
- Implementing the lambda functionality
- Decide dynamically which evaluator to use based on existence of lambdas

**Additional context**

**Comment by agavra** [comment]
Adding to the 0.17 milestone so that we make sure the error message around this is actionable if we don't end up implementing full lambda support for pull query interpreter during the 0.17 timeline.

**Comment by AlanConfluent** [comment]
#7152
