### ISSUE TITLE
How to avoid dividing by zero?

### ISSUE THREAD

**Issue by shota-hizawa-reazon** [confluentinc/ksql#7131]
**Provide details of the setup you're running**
ksqldb client: io.confluent.ksql:ksqldb-api-client:0.15.0
ksqldb server: confluentinc/ksqldb-server:0.15.0

**Outline your question**
The IFNULL function doesn't seem to work with the expression that could be divided by zero, but how can I avoid?

My create table statements is: 
```
CREATE TABLE delivery_block_stats AS
                SELECT
                    delivery_block_id,
                    SUM(order_count) AS order_count,
                    SUM(crew_count) AS crew_count,
                    SUM(crew_accepted_count) AS crew_accepted_count,
                    ROUND(IFNULL(CAST((SUM(crew_count) - SUM(crew_accepted_count)) AS DOUBLE) / SUM(order_count), CAST(0 AS DOUBLE)), 2)
                    AS block_crew_order_ratio,
                FROM delivery_area_stats das
                GROUP BY delivery_block_id
                EMIT CHANGES;
```

SUM(order_count) AS order_count, SUM(crew_count) AS crew_count, and SUM(crew_accepted_count) AS crew_accepted_count could be zero.
When I run this create statement, I got the error:

```
[2021-03-02 13:02:19,063] ERROR {"type":1,"deserializationError":null,"recordProcessingError":{"errorMessage":"Error computing expression ROUND(IFNULL((CAST((KSQL_AGG_VARIABLE_10 - KSQL_AGG_VARIABLE_11) AS DOUBLE) / KSQL_AGG_VARIABLE_12), CAST(0 AS DOUBLE)), 2) for column BLOCK_CREW_ORDER_RATIO with index 10","record":null,"cause":["Failed to invoke function public java.lang.Double io.confluent.ksql.function.udf.math.Round.round(java.lang.Double,java.lang.Integer)","java.lang.reflect.InvocationTargetException","Character N is neither a decimal digit number, decimal point, nor \"e\" notation exponential mark."]},"productionError":null,"serializationError":null,"kafkaStreamsThreadError":null} (processing.CTAS_DELIVERY_BLOCK_STATS_57.Aggregate.Project:44)
```

What I expected is the value of `block_crew_order_ratio` should be zero when `SUM(order_count)` is zero.

**Comment by agavra** [comment]
Hello @shota-hizawa-reazon - you may be interested in the `CASE` statement. You can see the documentation here: https://docs.ksqldb.io/en/latest/developer-guide/ksqldb-reference/quick-reference/#case

Let us know if that helps!

**Comment by shota-hizawa-reazon** [comment]
Hi @agavra,

I saw the page you linked, and I changed the create statement like below, then it works perfectly.
Thank you for your quick reply!

```
CREATE TABLE delivery_block_stats AS
                SELECT
                    delivery_block_id,
                    SUM(order_count) AS order_count,
                    SUM(crew_count) AS crew_count,
                    SUM(crew_accepted_count) AS crew_accepted_count,
                    CASE
                        WHEN SUM(order_count) = 0 THEN CAST(0 AS DOUBLE)
                        ELSE ROUND(CAST((SUM(crew_count) - SUM(crew_accepted_count)) AS DOUBLE) / SUM(order_count), 2)
                    END AS block_crew_order_ratio,
                FROM delivery_area_stats das
                GROUP BY delivery_block_id
                EMIT CHANGES;
```

In my opinion, this kind of information should be written in doc([this](https://github.com/confluentinc/ksql/blob/master/docs/developer-guide/ksqldb-reference/operators.md) page may be suitable for this?), so can I make a PR to improve this page?

**Comment by agavra** [comment]
cc @JimGalasyn - any ideas where would be the right place for additional documentation here, if more is needed at all?

**Comment by agavra** [comment]
OK, in that case less keep the docs as is. @shota-hizawa-reazon, if more people complain about this we can loop you in to help contribute to the docs but for now I think the CASE docs are useful as is.

**Comment by shota-hizawa-reazon** [comment]
@agavra,
I've got it. Thanks for your considerations!
