### ISSUE TITLE
`SET` should fail for config that cannot be changed in a session

### ISSUE THREAD

**Issue by mjsax** [confluentinc/ksql#7156]
**Is your feature request related to a problem? Please describe.**
Using `set` command, it is possible to change config that cannot be changed dynamically, for example `ksql.schema.registry.url`. Issuing a corresponding set command just report success and `show properties` shows the new value, even if the new value is not effective.

**Describe the solution you'd like**
The `set` command should fail with a descriptive error message if the config cannot be changes, and `show properties` should still show the old value.

**Comment by rodesai** [comment]
related: https://github.com/confluentinc/ksql/issues/6869
