### ISSUE TITLE
avro serdes don't correctly handle precision/scale mismatch between ksql and registered schema

### ISSUE THREAD

**Issue by rodesai** [confluentinc/ksql#7170]
Our avro deserializer doesn't try to handle the case where the incoming precision/scale don't match the schema precision/scale - it just takes the deserialized BigDecimal and hands it off to the engine (the json deserializer does do this). Then, when we try to serialize the BigDecimal to write it (e.g. to a change-log), the converter throws because the scale is off.

The correct behavior would be to either:
- treat the schema change as a query-killing error and fail the query from the deserializer so the error is more clear
- don't treat the schema change as a query-killing error and try to coerce the values into the new schema. rows with values that can't be coerced can be discarded and we'd log a processing log msg

Not sure which would be better. We should also look at enabling users to evolve their ksql schemas to the correct version (in the event this happens due to a schema change) - I don't think we support that now in a way that would also update the running query

**Comment by jzaralim** [comment]
The json deserializer follows the second option when it receives a BigDecimal with mismatched precision/scale. Is there a reason avro values should be handled differently?
