### ISSUE TITLE
Is there something similar to an SQL Union supported ?

### ISSUE THREAD

**Issue by nomemory** [confluentinc/ksql#7171]
I have two streams that share a similar structure: `policeLocations` and `carLocations`.

The definition for both is as following:

```
CREATE STREAM carLocations (profileId VARCHAR, color VARCHAR, hasPapers BOOLEAN, location VARCHAR)
  WITH (kafka_topic='carLocations', value_format='json', partitions=1);

CREATE STREAM policeLocations(profileId VARCHAR, location VARCHAR)
 WITH (kafka_topic='policeCarLocations', value_format='json', partitions=1);
```

I want to create a table that represents a "snapshot" of all the cars (both "normal" cars and "police cars") locations.

How can I achieve this? 
Does **ksqldb** supports something akin to an `SQL UNION`?

**Comment by PeterLindner** [comment]
Currently this should be possible with `INSERT INTO` (with some fiddling around to get a table in the end), however `UNION ALL` is proposed in KLIP-17: #4125
The KLIP also mentions their benefits and shortcomings, respectively

**Comment by nomemory** [comment]
@PeterLindner thank you for you answer. I will take a look at KLIP-17.
