### ISSUE TITLE
'ksql-migrations create' does not fail if attempting to create a duplicate file

### ISSUE THREAD

**Issue by spena** [confluentinc/ksql#7197]
**Describe the bug**
When a migration file already exists and I try to create the same file again, the `ksql-migrations create` command generates a new file with a new version instead of failing. In the below example I am attempting to create the version 1, but it creates version 2 or 3 (depending of the latest version available).

I'm not sure this should be the case. IMHO this operation should fail because the version already exists (even if the description is different).

**To Reproduce**

```
$ ksql-migrations -c migrations/ksql-migrations.properties create 1 Setup
Creating migration file: migrations/migrations/V000001__Setup.sql
Migration file successfully created
Execution time: 0.0080 seconds

$ ksql-migrations -c migrations/ksql-migrations.properties create 1 Setup
Creating migration file: migrations/migrations/V000002__Setup.sql
Migration file successfully created
Execution time: 0.0080 seconds

$ ksql-migrations -c migrations/ksql-migrations.properties create 1 Setup
Creating migration file: migrations/migrations/V000003__Setup.sql
Migration file successfully created
Execution time: 0.0080 seconds
```

**Expected behavior**

```
$ ksql-migrations -c migrations/ksql-migrations.properties create 1 Setup
Creating migration file: migrations/migrations/V000001__Setup.sql
Migration file successfully created
Execution time: 0.0080 seconds

$ ksql-migrations -c migrations/ksql-migrations.properties create 1 SetupAgain
A migration file with version 1 already exists.

$ echo $? 
1
```

The command should fail with the right error code (1: Operation not permitted).

**Comment by spena** [comment]
Seems the `version` is ignored.

```
./ksql-migrations -c migrations/ksql-migrations.properties create 3 Setup
Creating migration file: migrations/migrations/V000002__Setup.sql
Migration file successfully created
Execution time: 0.0080 seconds
```

**Comment by vcrfxia** [comment]
Version must be passed as a flag. The proper syntax is `./ksql-migrations -c migrations/ksql-migrations.properties create -v 3 Setup`

**Comment by vcrfxia** [comment]
Here's a fix to throw an error message if too many arguments are specified: https://github.com/confluentinc/ksql/pull/7201
