### ISSUE TITLE
KSQL compile error

### ISSUE THREAD

**Issue by mts57017** [confluentinc/ksql#720]
/ksql/ksql-common/src/main/java/io/confluent/ksql/metrics/MetricCollectors.java:[93,37] **lambda expressions are not supported in -source 1.7 (use -source 8 or higher to enable lambda expressions)**

i have version 9 installed now

do i need to change the flag?

**Comment by apurvam** [comment]
can you share the output of `javac -version` from your environment?

**Comment by mts57017** [comment]
9.0.4

**Comment by miguno** [comment]
Closed because of inactivity. Feel free to re-open if needed.
