### ISSUE TITLE
Getting error when try to delete stream

### ISSUE THREAD

**Issue by hinguabhishek** [confluentinc/ksql#721]
I am getting below error when I am trying to delete stream

Could not write the statement 'DROP STREAM ORDER_DATA_STREAM;' into the command topic.
Caused by: org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.
Caused by: Failed to update metadata after 60000 ms.

**Comment by apurvam** [comment]
Was your cluster available at the time? does this continue to be a problem?

**Comment by miguno** [comment]
Closed because of inactivity.  Feel free to reopen if needed.
