### ISSUE TITLE
kSQLdb API hangs and does nothing

### ISSUE THREAD

**Issue by mike-thompson-h** [confluentinc/ksql#7213]
I am trying to query streams and tables using the kSQLDB api, but they keep running and do nothing. 

Steps I have taken to reproduce the behavior, include:
1. Version - 0.12.0
2. Sample source data.
3. I am running the following curl statement below to the API:

curl --location --request POST 'http://{ipaddress}:{port}/query?Accept=application/vnd.ksql.v1+json' \
--header 'Accept: application/vnd.ksql.v1+json' \
--header 'Content-Type: text/plain' \
--data-raw '  {
      "ksql": "SELECT * FROM ORDERS EMIT CHANGES LIMIT 5;"
  }'

I expected for this query to run, but it does not even complete hours after kicking this off.  I get results when I run the same command within the Confluent CLI. Also, other queries that list the existing streams and tables are working. I do not know what could be causing this. Please could someone help me with this.

**Comment by maksymilian-gasztych** [comment]
I've noticed that too recently, if you don't have to don't use query endpoint, use query-stream instead. Query endpoint hangs for more than one concurrent client. https://github.com/confluentinc/ksql/issues/7172

**Comment by mike-thompson-h** [comment]
Thanks for the advice. The server was restarted and this seemed to fix the issue.
