### ISSUE TITLE
Query related metrics not showing after ksqldb 0.15 upgrade 

### ISSUE THREAD

**Issue by rajbhino** [confluentinc/ksql#7254]
**Describe the bug**
Till ksqldb 0.14 version, metrics for queries running in the cluster where visible. However once we upgraded to 0.15.0 docker version, and re-deployed the queries we are not seeing the metrics related to the running queries. 

**To Reproduce**
Steps to reproduce the behavior, include:

- Used Confluent provided helm chart, changed image name and image tag to pull docker image of 0.15.0 (from https://hub.docker.com/r/confluentinc/ksqldb-server/tags?page=1&ordering=last_updated)
- Deploy the helm chart to bring up the ksqldb cluster with 3 pod counts.
- Use REST Curl to post queries for installing the persistent queries.
- Queries got deployed successfully and streams running successfully.
- Only the following JMX metrics are showing when checked with Prometheus targets and the query related metrics are not shown. 
    
    But if we roll it back to 0.14.0 and follow the same steps query related metrics are also showing. We did multiple times to double confirm

**Expected behaviour**
Query related metrics should be visible. 

Example metrices that we are expecting to see : # HELP _confluent_ksql_stg_eks_retail_kafka_entinv_ksql_ksql_engine_query_stats_running_queries Count of queries in RUNNING state. (io.confluent.ksql.metrics<type=ksql-engine-query-stats><>_confluent-ksql-stg-eks-retail-kafka-entinv-ksql-ksql-engine-query-stats-RUNNING-queries)
# TYPE _confluent_ksql_stg_eks_retail_kafka_entinv_ksql_ksql_engine_query_stats_running_queries untyped
_confluent_ksql_stg_eks_retail_kafka_entinv_ksql_ksql_engine_query_stats_running_queries 5.0
# HELP _confluent_ksql_stg_eks_retail_kafka_entinv_ksql_bytes_consumed_total The total number of bytes consumed across all queries (io.confluent.ksql.metrics<type=ksql-engine-query-stats><>_confluent-ksql-stg-eks-retail-kafka-entinv-ksql-bytes-consumed-total)
# TYPE _confluent_ksql_stg_eks_retail_kafka_entinv_ksql_bytes_consumed_total untyped
_confluent_ksql_stg_eks_retail_kafka_entinv_ksql_bytes_consumed_total 2.19132542E9

**Actual behaviour**
Only the below JMX Metrics are shown. Query related metrics are not visible at all
# HELP jmx_scrape_duration_seconds Time this JMX scrape took, in seconds.
# TYPE jmx_scrape_duration_seconds gauge
jmx_scrape_duration_seconds 0.00179449
# HELP jmx_scrape_error Non-zero if this scrape failed.
# TYPE jmx_scrape_error gauge
jmx_scrape_error 0.0
# HELP jmx_config_reload_success_total Number of times configuration have successfully been reloaded.
# TYPE jmx_config_reload_success_total counter
jmx_config_reload_success_total 0.0
# HELP jmx_config_reload_failure_total Number of times configuration have failed to be reloaded.
# TYPE jmx_config_reload_failure_total counter
jmx_config_reload_failure_total 0.0

**Additional context**
In our helm chart below is what we have.
## ref: https://hub.docker.com/r/confluentinc/ksqldb-server
image: confluentinc/ksqldb-server
imageTag: 0.15.0 -> if we change this to 0.14.0 and install the metrics are visible.

**Comment by stevenpyzhang** [comment]
@rajbhino we removed some legacy metrics naming conventions in this PR https://github.com/confluentinc/ksql/pull/6643 you'll need to update the metrics you're monitoring to match the metrics naming available after 0.15.0

**Comment by rajbhino** [comment]
metrics naming pattern updated in jmx-configmap.yaml and we are able to view the metrics.

**Comment by stevenpyzhang** [comment]
The 0.15.0 metrics docs has a working set of metrics name patterns https://docs.ksqldb.io/en/0.15.0-ksqldb/reference/metrics/

Will close this issue out now
