### ISSUE TITLE
The server has detected corruption in the command topic

### ISSUE THREAD

**Issue by ivoras** [confluentinc/ksql#7267]
I had a stream created as:

```
create stream database_daemon_messages(datetime varchar, client varchar, building varchar, host varchar, service varchar, object string) with (kafka_topic='saturn-database-daemon', value_format='json', partitions=1);
```

But the 'object' field of the topic's JSON format is a nested structure, so I tried a new `create stream` statement instead of first dropping the old one:

```
create stream database_daemon_messages(datetime varchar, client varchar, building varchar, host varchar, service varchar, object struct) with (kafka_topic='saturn-database-daemon', value_format='json', partitions=1);
```

and got this error:

```
Failed to prepare statement: Cannot resolve unknown type: STRUCT
```

The reason I've just tried "struct" as the data type is because the nested structure isn't strictly defined, and can miss some fields. I suppose I should have tried a "struct" with some defined fields?

Anyway, after the last error message, I keep getting this:

```
ksql> drop stream database_daemon_messages;
Failed to handle Ksql Statement.
The server has detected corruption in the command topic due to modifications performed on it.
DDL statements will not be processed any further.
If a backup of the command topic is available, restore the command topic using the backup file.
A server restart is required to restore full functionality.
```

How did it come to this corruption? Where do I look for a backup of the command topic?

**Comment by stevenpyzhang** [comment]
@ivoras do you have `ksql.metastore.backup.location` config set? If set, backups for the KSQL command topic are enabled. It should be disabled by default.

**Comment by stevenpyzhang** [comment]
If you restart the server, does it still say it's corrupted? If you still encounter the corrupted error message, would you mind sharing the contents of your command topic? Did you perhaps delete the command topic for the KSQL server while it was still running?

**Comment by ivoras** [comment]
I did this to resolve it (some steps might be superfluous):

- Shut down ksql
- Restart kafka
- Delete the command topic
- Start ksql

It continued to perform as expected.

**Comment by melizalde95** [comment]
In my case using docker compose, I just restart using:
 
```bash
$ docker-compose restart ksqldb-server broker ksqldb-cli
```

IDK which works.

**Comment by daehokimm** [comment]
Why is this happened? Is there any docs or reference about this issue?

**Comment by stevenpyzhang** [comment]
If you haven't set a value for `ksql.metastore.backup.location` and you're running into this issue, the most likely cause is that the command topic was deleted while the ksqlDB server was still running. Restarting the server resumes functionality because the ksqlDB server creates a new command topic (since if it doesn't exist during server startup, the topic is created)

**Comment by stevenpyzhang** [comment]
If there's another scenario that leads to an unexplained command topic corruption, please list the steps taken so we can investigate.
