### ISSUE TITLE
Upgrade compatability error between cp-ksql 5.X and ksqldb 0.15

### ISSUE THREAD

**Issue by deuscapturus** [confluentinc/ksql#7277]
I tried to upgrade my cp-ksql 5.4.2 to ksqldb 0.15 and got error when running list tables or list streams:

```
WARNING: The server has encountered an incompatible entry in its log and cannot process further DDL statements.
This is most likely due to the service being rolled back to an earlier version.
```

I guess this upgrade path is not supported.  I'm posting here because this error otherwise doesn't exist on the internet.

**Comment by JimGalasyn** [comment]
@deuscapturus, thank you for the feedback!

**Comment by sameer2800** [comment]
I am facing the exact issue when I upgraded the cluster. Is this expected?  can't we upgrade the cluster to a higher version? If not, whats migration strategy to move out my running streams and queries.

**Comment by JimGalasyn** [comment]
@deuscapturus @sameer2800 You can’t upgrade from 5.4.x to 5.5.x and higher without creating a new command topic and recreating the queries. For more information, see [Upgrading to ksqlDB 5.5 from KSQL 5.4](https://docs.confluent.io/platform/current/ksqldb/upgrading.html#upgrading-to-ksqldb-5-5-from-ksql-5-4).
