### ISSUE TITLE
Can't run aggregations on integer columns

### ISSUE THREAD

**Issue by apurvam** [confluentinc/ksql#730]
Aggregations on integer columns fail with:

```
No SUM aggregate function with Schema{INT32}  argument type exists!
```

**Comment by blueedgenick** [comment]
Example to reproduce as follows:

Stream 'ratings' defined against an avro topic:

ksql> describe ratings;

 Field       | Type
-----------------------------------------
 ROWTIME     | BIGINT           (system)
 ROWKEY      | VARCHAR(STRING)  (system)
 RATING_ID   | BIGINT
 USER_ID     | INTEGER
 STARS       | INTEGER
 ROUTE_ID    | INTEGER
 RATING_TIME | BIGINT
 CHANNEL     | VARCHAR(STRING)
 MESSAGE     | VARCHAR(STRING)
-----------------------------------------

Query: 
ksql> select channel, sum(stars) from ratings group by channel;

Error:
No SUM aggregate function with Schema{INT32}  argument type exists!
