### ISSUE TITLE
Support stream-stream joins

### ISSUE THREAD

**Issue by apurvam** [confluentinc/ksql#731]
Currently, you can only perform stream-table joins (stream: left, table: right).  We should support stream-stream joins, too, similar to what Kafka's Streams API already supports.

Related tickets:
* [GH-760: Support table-table joins](https://github.com/confluentinc/ksql/issues/760)

**Comment by IDispose** [comment]
table-table joins also should be supported.

**Comment by miguno** [comment]
@IDispose and @pouledodue : Please cast your +1 vote to the separate table-table join ticket that I just created: https://github.com/confluentinc/ksql/issues/760

**Comment by apurvam** [comment]
Fixed by #1417
