### ISSUE TITLE
Document streams configs that are relevant to KSQL

### ISSUE THREAD

**Issue by rodesai** [confluentinc/ksql#732]
We should document and explain streams configs that are relevant to tuning ksql. Some examples:
auto.offset.reset: needs to be set to 'earliest' to consume a topic from the beginning.
cache.max.bytes.buffering: impacts the results of some queries, also can be used to turn off aggregate caching for workloads where it hurts performance.

**Comment by miguno** [comment]
Is this already covered by our latest docs, @rodesai ?

**Comment by joel-hamill** [comment]
@rodesai @miguno @rmoff https://docs.confluent.io/current/ksql/docs/installation/server-config/config-reference.html

**Comment by rmoff** [comment]
Looks like this is covered in the docs now, thanks @joel-hamill . Closing.
