### ISSUE TITLE
!= operator not working with Integer Comparison

### ISSUE THREAD

**Issue by mateen-dar** [confluentinc/ksql#733]
Hello
I have a simple stream query as follows

```sql
SELECT after_hash, before_hash, CAST(after_hash AS varchar) != CAST(before_hash AS varchar) FROM tirsdms_stream_test_2
```

Without casting the two columns (after_hash and before_hash) to String the `!=` operator returns true in all cases. Comparing two integer columns with `!=` does not work as expected.

**Comment by rodesai** [comment]
I was not able to reproduce this. Can you include the output of the following queries:

`DESCRIBE EXTENDED tirsdms_stream_test_2;`
`SELECT after_hash, before_hash, after_hash != before_hash FROM tirsdms_stream_test_2;`

For the `SELECT` can you try and include some rows that return incorrect results for the `!=` expression?
