### ISSUE TITLE
About logging configuration

### ISSUE THREAD

**Issue by maksymilian-gasztych** [confluentinc/ksql#7352]
**Provide details of the setup you're running**
any version

**Outline your question**
Is there a way to disable warnings like that ? I haven't observed any negative effects related to those logs, so I would like to change the log level for the logs like that but I couldn't find any information on how to do that and my own attempts failed.

I think it would be useful to include more information on logs configuration into the documentation.

![image](https://user-images.githubusercontent.com/72374203/113803903-6fb6b480-9798-11eb-861b-e2cdb2bcd2c5.png)

Just in case attaching ksqldb log4j.properties I'm using.

```
log4j.rootLogger=INFO, stdout

# appenders
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=jp.menu.jinrai.GoogleCloudLoggingLayout

log4j.appender.streams=org.apache.log4j.ConsoleAppender
log4j.appender.streams.layout=jp.menu.jinrai.GoogleCloudLoggingLayout

log4j.appender.main=org.apache.log4j.ConsoleAppender
log4j.appender.main.layout=jp.menu.jinrai.GoogleCloudLoggingLayout

log4j.appender.kafka=org.apache.log4j.ConsoleAppender
log4j.appender.kafka.layout=jp.menu.jinrai.GoogleCloudLoggingLayout

# loggers

log4j.logger.org.reflections=ERROR, stdout

# Uncomment the following line to stop KSQL from logging out each request it receives:
log4j.logger.io.confluent.ksql.rest.server.resources.KsqlResource=WARN

# And this one to avoid the logs being spammed with KsqlConfig values.
# Though these can be useful for debugging / investigations.
log4j.logger.io.confluent.ksql.util.KsqlConfig=ERROR

## Kafka Streams logs:
log4j.logger.org.apache.kafka.streams=INFO, streams
log4j.additivity.org.apache.kafka.streams=false

## Kafka Client logs:
log4j.logger.kafka=WARN, stdout
log4j.logger.org.apache.zookeeper=WARN, stdout
log4j.logger.org.apache.kafka=WARN, stdout
log4j.logger.org.I0Itec.zkclient=WARN, stdout
```

**Comment by rodesai** [comment]
@maksymilian-gasztych you can disable the logs by setting the logger's level to OFF in your log4j properties:
```
log4j.logger.<logger id>=OFF
```

**Comment by maksymilian-gasztych** [comment]
Thanks, that worked. I'm pretty sure I had tried it before though, but it somehow didn't work. Must have done something wrong.
