### ISSUE TITLE
Are windowed tables a dead end for further processing? (KSQL does not support persistent queries on windowed tables)

### ISSUE THREAD

**Issue by ivoras** [confluentinc/ksql#7353]
I'm trying to send summary data about error logs to an external database (MongoDB in this case), and to do that, I have a windowed table which counts how many errors  a particular service had in the last 5 minutes.

Doing a SELECT... EMIT CHANGES on this table does *exactly* what I wanted.

However, creating a stream on that fails with `KSQL does not support persistent queries on windowed tables` (the intent was to export exactly what I see with the above query through a connector to MongoDB).

Googling around, it looks like the concept of tables, and especially windowed tables in KSQL is very limited, almost toy-like:

* It's impossible to query all rows from this type of virtual table (in this case it would be with the goal of getting an overview of services and their error counts), even though this data is collected and exists somewhere.
* It's impossible to create a stream on a windowed table, even though I can do a SELECT .. EMIT CHANGES on it just fine.

So it looks like once we create a windowed table, that's it - no additional processing can be done on this data, and it can only be queried row by row if we know individual table keys in advance.

Is there a way to work around any of the above issues? This is ksqldb 0.15.

**Comment by mjsax** [comment]
> Doing a SELECT... EMIT CHANGES on this table does exactly what I wanted.

If you have already a table created (ie, `CREATE TABLE myWindowedResultTable AS SELECT...`), and you want to export the data to MongoDB, you can use the table's topic (by default `myWindowedResultTable`) to export the data to MongoDB via Kafka Connect.

The is no need to create an additional STREAM. You can still create an additional stream via `CREATE STREAM myResultStream WITH (topic='myWindowedResultTable',...)` but I don't think that would be necessary?

> it looks like the concept of tables, and especially windowed tables in KSQL is very limited

We are aware of the limitation and there a lot of work in progress to lift those :)

**Comment by ivoras** [comment]
Hi,

Thanks for the quick answer!

The reason why I tried to create a stream on top of a windowed table is to do some additional data processing, including renaming fields.

Since in this particular case we have a unique pair (host, service), and MongoDB uses `_id` as a unique primary key, I can simulate having a table of `((host,service), count(...) windowed)` in MongoDb, which I can query in bulk, but I needed to prepare the data in KSQL first.

Anyway, this is my workaround so far:

My table definition:
```
create table saturn_errors_summary 
 with (key_format='json') 
 as select concat(host, '_', service) as _id, count(*) as error_count 
  from saturn_messages 
  window tumbling (size 24 hours) 
  where level != 'info' 
  group by concat(host, '_', service);
```

So the concat(host,service) is the key and the windowed count is the aggregate.

Then I sink it like this:

```
create sink connector mongodb_errors_summary with 
("connector.class"='com.mongodb.kafka.connect.MongoSinkConnector',
 "connection_url"='mongodb://server.example.com:27017',
 "mode"='bulk',
 "key.converter"='org.apache.kafka.connect.storage.StringConverter',
 "key.converter.schemas.enable"='false',
 "value.converter"='org.apache.kafka.connect.json.JsonConverter',
 "value.converter.schemas.enable"='false',
 "database"='saturn_kafka',

 "transforms"='RenameField',
 "transforms.RenameField.type"='org.apache.kafka.connect.transforms.ReplaceField$Value',
 "transforms.RenameField.renames"='_ID:_id',

 "topics"='SATURN_ERRORS_SUMMARY');
```

BUT, for some reason, the records in the SATURN_ERRORS_SUMMARY topic only contains the `error_count` field, not the _id, and not the windowstart and windowend (verified with kafkacat) fields. I can see those fields, and they behave as expected, by doing:

```
select * from SATURN_ERRORS_SUMMARY emit changes;
```

So I'm kind of back at the starting point: how to get the output of the above query into a connector?

**Comment by maksymilian-gasztych** [comment]
You can definitely do some additional processing on a windowed table, but you need to create additional stream without key on top of the topic, however cumbersome it may be. Hope that helps you.
  ```
CREATE TABLE windowed AS
                SELECT
                    key_id,
                    AS_VALUE(id) AS id,
                    COUNT(*) AS c
                FROM some_Stream
                WINDOW TUMBLING (SIZE 30 SECONDS,RETENTION 30 SECONDS,GRACE PERIOD 0 SECONDS)
                GROUP BY key_id
                EMIT FINAL;
  CREATE STREAM windowed_stream (id BIGINT,c BIGINT) WITH(kafka_topic='WINDOWED',value_format='avro');
  CREATE TABLE crew_location AS
        SELECT
            id AS renamed_id,
            c AS renamed_c
        FROM windowed_stream
        GROUP BY id
        EMIT CHANGES;
```
