### ISSUE TITLE
Join on a nested field value?

### ISSUE THREAD

**Issue by dave-pollock** [confluentinc/ksql#7381]
**Provide details of the setup you're running**
KSQL 5.4.3

**Outline your question**
I see this issue was closed, with a note that joining on a nested value should now work: https://github.com/confluentinc/ksql/issues/4051

Is that true? I'm getting the same issue as the original poster, with the same setup.

**Comment by agavra** [comment]
Hello @dave-pollock - ksqlDB 5.4.3 is quite old, this was fixed in more recent versions. I don't know exactly which version this was merged to, but I believe 6.0 is the first CP version to include the fix.
