### ISSUE TITLE
Investigate outer-join materialized store's pull query result 

### ISSUE THREAD

**Issue by guozhangwang** [confluentinc/ksql#7391]
**Describe the bug**
When looking at https://github.com/confluentinc/ksql/pull/7246, we found the full-scan pull query results are not sorted by keys as expected (note that the tests are with a single partition, so there's no non-detereminism due to gather-scatter). I think we need to figure out why it is the case compared with others. More observations:

* Keys are only not sorted for outer join; inner / left join results are sorted.
* Data formats make no difference: AVRO, JSON and PROTOBUF all have displayed this scenario for outer joins.

**Comment by cprasad1** [comment]
If we don’t explicitly specify the number of partitions, then the default is 4. This results in a scatter gather and the rows are unordered. If we specify the the num of partitions to be 1 then we see ordered results for pull queries. This is a quirk of our testing framework (pull queries ordering is as expected). The default is set here: https://github.com/confluentinc/ksql/blob/ab84fd8bf14c810b956330c891586c8c76285842/ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/Topic.java#L26

Do we know why the default is 4? Do we want to update the default?

**Comment by agavra** [comment]
I think 4 is a reasonable default - that makes sure that we by default test the more complicated scenarios. Let's keep it at that, thanks for digging into this!

**Comment by guozhangwang** [comment]
Thanks for looking into it @cprasad1 !

**Comment by cprasad1** [comment]
We decided to keep the default number of partitions to 4
