### ISSUE TITLE
Using KSQL to drill down on Kafka messages

### ISSUE THREAD

**Issue by ivoras** [confluentinc/ksql#7393]
I have a log processing pipeline which sends log messages to Kafka where they are retained in a topic for a 24 hour period, and there are a couple of KSQL streams and tables which filter or summarise the data.

However, one of the things I need to do is enable data drill down.

When a certain condition is met, e.g. a log message with a "CRITICAL" type is received, filtered through a KSQL stream, we need to query for a number of raw log messages from the original Kafka topic which surround this message.

To me, a natural way to do that would be to query the Kafka topic or KSQL stream by the message timestamp or rowtime. However, this doesn't exactly work:

```
ksql> SET 'auto.offset.reset' = 'earliest';

ksql> select * from saturn_messages where rowtime > 1618822191475 AND rowtime < 1618822266080 limit 1000000;
Pull queries don't support LIMIT clauses. See https://cnfl.io/queries for more info.
Add EMIT CHANGES if you intended to issue a push query.

ksql> select * from saturn_messages where rowtime > 1618822191475 AND rowtime < 1618822266080;
Can't pull from `SATURN_MESSAGES` as it's not a materialized table. See https://cnfl.io/queries for more info.
Add EMIT CHANGES if you intended to issue a push query.
```

What works is `EMIT CHANGES`:

```
ksql> select * from saturn_messages where rowtime > 1618822191475 AND rowtime < 1618822266080 emit changes;
```

But, since the processing time is long (which is allright because these types of operations are rare), we can't really use a timeout to distinguish between "no messages" and "ksql is still processing data".

Is there a workaround which we can use to just process all the messages in the Kafka topic as if they are just there, not continually streaming?

I'm using a timestamp (rowtime) here, but it would be very useful if this isn't just timestamp-based (which admiteddly we can do directly in Kafka) but also include querying other fields.

**Comment by agavra** [comment]
Hi @ivoras - I believe there are two limitations for what you're asking for:
- first is https://github.com/confluentinc/ksql/issues/7209 (if you're trying to query over a stream)
- and if you're query a table, then #6962 is the ticket you're interested in. The first is in our near term roadmap, the second I will bring up with the team again.

**Comment by agavra** [comment]
I'll close this question out for now - feel free to re-open if my answer wasn't sufficient.
