### ISSUE TITLE
ksqldb-api-client http2MultiplexingLimit unrecoverable exception

### ISSUE THREAD

**Issue by k1th** [confluentinc/ksql#7426]
**Describe the bug**
In `ClientImpl.java`  `HttpClientOptions` does not set the `http2MultiplexingLimit` resulting in it being -1.
This in turn, is used here in Vertx

```
public static VertxHttp2ConnectionHandler<Http2ClientConnection> createHttp2ConnectionHandler(
  HttpClientImpl client,
  Object queueMetric,
  ConnectionListener<HttpClientConnection> listener,
  ContextInternal context,
  Object socketMetric,
  BiConsumer<Http2ClientConnection, Long> c) {
  long http2MaxConcurrency = client.getOptions().getHttp2MultiplexingLimit() <= 0 ? Long.MAX_VALUE : client.getOptions().getHttp2MultiplexingLimit();
```
`http2MaxConcurrency`is then Long.MAX_VALUE.

Later, in `Pool.java` in Vertx, in our case concurrency is set to 100 on connection upgrade and holder.concurrency at `Long.MAX_VALUE`.
```
  private synchronized void setConcurrency(Holder holder, long concurrency) {
    if (concurrency < 0L) {
      throw new IllegalArgumentException("Cannot set a negative concurrency value");
    }
    if (holder.removed) {
      assert false : "Cannot recycle removed holder";
      return;
    }
    if (holder.concurrency < concurrency) {
      long diff = concurrency - holder.concurrency;
      if (holder.capacity == 0) {
        available.add(holder);
      }
      capacity += diff;
      holder.capacity += diff;
      holder.concurrency = concurrency;
      checkProgress();
    } else if (holder.concurrency > concurrency) {
      throw new UnsupportedOperationException("Not yet implemented");
    }
  }
```

This results in the error also seen in #6728
In our case, we can reproduce this only on remote connections, not on local ones (both with Docker).

**To Reproduce**
- Build an example client with https://docs.ksqldb.io/en/latest/developer-guide/ksqldb-clients/java-client/
- Set up for a remote connection with KSQL Server 0.15
- Create a `CompletableFuture<StreamedQueryResult> streamedQuery`and `get()`it

**Expected behavior**
No exception.

**Actual behaviour**
```
Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException: Not yet implemented
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at my.ksqldb.app.ExampleApp.main(ExampleApp.java:30)
Caused by: java.lang.UnsupportedOperationException: Not yet implemented
```

**Additional context**
I guess this is rather a Vertx issue than a KSQL client issue, but it's a blocker when using tools that rely on the HTTP/2 streaming API client.

**Comment by colinhicks** [comment]
@agavra Do you recall the plan to address this? It seems like we might want to allow setting Vert.x HttpClientOptions directly. This would provide a workaround for what does appear to be a Vert.x issue. Elsewhere, it was raised that it would be useful to be able to access or provide the HttpClientOptions instance in order to set arbitrary request headers.

Also, should we move this to `streaming-engine`?

Separately, since this issue was reported only for remote connections, it seems reasonable to presume that some other networking layer, such as a proxy is setting this limit. cf. spec for `SETTINGS_MAX_CONCURRENT_STREAMS`: https://datatracker.ietf.org/doc/html/rfc7540#section-6.5.2

**Comment by k1th** [comment]
Any plans for this yet?
