### ISSUE TITLE
HTTP 415 Unsupported Media Type error on older versions of ksqlDB when API request uses Accept header

### ISSUE THREAD

**Issue by jzaralim** [confluentinc/ksql#7454]
**Describe the bug**
On older versions of ksqlDB (5.5.1, not sure what other versions are affected), passing the Accept header in a Rest API request results in a HTTP 415 Unsupported Media Type error despite the [docs](https://github.com/confluentinc/ksql/blob/5.5.x/docs/developer-guide/api.rst) saying to use the Accept header:

```
curl -X "POST" "http://localhost:8088/ksql" \
          -H "Accept: application/vnd.ksql.v1+json" \
          -d $'{"ksql": "LIST STREAMS;","streamsProperties": {}}'
{"@type":"generic_error","error_code":41500,"message":"HTTP 415 Unsupported Media Type","stackTrace":[...]}
```

Newer versions of ksqlDB accept the Accept header though.

**Actual behaviour**
The documentation should instruct the user to the the Content-Type header instead of the Accept header for versions that don't accept Accept.

**Comment by agavra** [comment]
it seems like this is true for everything before 5.5

**Comment by agavra** [comment]
I'm especially confused, looking at the code it looks like this should work: https://github.com/confluentinc/ksql/blob/868977bf1b277024b1815a8bc3cc4391f55ce583/ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlResource.java#L76-L79

**Comment by agavra** [comment]
OK I figured it out - for some reason the older versions of ksqlDB don't default `-H "Content-Type: application/json"` which you also need. It has nothing to do with the `Accept` header 🤕. I'll work on updating the docs to reflect that

**Comment by agavra** [comment]
It doesn't happen in the newer versions because the Vertx server doesn't require json as the content type: https://github.com/confluentinc/ksql/blob/5df5532bb99883cb5f8af740a10755f188b57ced/ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/ServerVerticle.java#L146-L150

**Comment by agavra** [comment]
After looking at the docs, I realized that this ticket isn't right. The docs always had this as the example:
```
curl -X "POST" "http://localhost:8088/ksql" \
     -H "Content-Type: application/vnd.ksql.v1+json; charset=utf-8" \
     -d $'{
  "ksql": "LIST STREAMS;",
  "streamsProperties": {}
}'
```
Notice the `-H "Content-Type...` not `-H "Accept...`. If you pass in both (the content-type and accept) then it works as expected:
```
(16:46:08) almog.gavra % curl -X "POST" "http://localhost:8088/ksql" -H "Content-Type: application/vnd.ksql.v1+json; charset=utf-8" -d $'{
  "ksql": "LIST STREAMS;",
  "streamsProperties": {}
}'
[{"@type":"streams","statementText":"LIST STREAMS;","streams":[{"type":"STREAM","name":"KSQL_PROCESSING_LOG","topic":"default_ksql_processing_log","format":"JSON"}],"warnings":[]}]
```
