### ISSUE TITLE
Topics not being removed in KSQL although removed in zookeeper

### ISSUE THREAD

**Issue by kccheung** [confluentinc/ksql#753]
I connected to my zookeeper via `zookeeper-shell` and delete topics via `rmr /brokers/topics/test`, but the topics still exists in KSQL when I apply `list topics;`. I already verify the topics are being deleted using `ls /brokers/topics`.

**Comment by rodesai** [comment]
You should use the kafka-topics tool to delete your topic: `kafka-topics --zookeeper <zookeeper addr> --delete --topic <topic name>`

**Comment by apurvam** [comment]
@kccheung. I hope @rodesai answered your question. If you delete kafka topics properly, they will disappear from ksql. Please reopen if you find this not to be the case.
