### ISSUE TITLE
Generate JSON Data From Select Statement

### ISSUE THREAD

**Issue by karno123** [confluentinc/ksql#7531]
I have a case that I need to input to specific topic from select statement with below structure:

`{
"ingestion_id": "004a83cd-fb38-4408-9242-cc9c77fc0a93",
"data": [
{
"entity_type": "string"
"signup_timestamp": int64,
"status": "string",
}
]
}`

From existing scalar function, I use Array and AS_MAP, AS_ARRAY function. with below command and I get error:
`SELECT
  UUID() AS ingestion_id,
  ARRAY[
    AS_MAP(
      AS_ARRAY[
       'entity_type',
       'signup_timestamp',
       'status'
      ],
      AS_ARRAY[
        customer.entity_type,
        customer.signup_timestamp,
        customer.status
    )
  ] AS data
FROM CUSTOMER emit changes`

With error  `Cannot construct an array with mismatching types `, I realize that map function currently do not support for different value types. 

Is there any other way how to construct  STRUCT<entity_type varchar, signup_timestamp BIGINT> from select command?

**Comment by PeterLindner** [comment]
@karno123 according to the [docs about data types](https://docs.ksqldb.io/en/latest/reference/sql/data-types/#struct):
>Also, you can output a struct from a query by using a SELECT statement. The following example creates a struct from a stream named s1
`SELECT STRUCT(f1 := v1, f2 := v2) FROM s1 EMIT CHANGES;`

It's missing from the [function reference](https://docs.ksqldb.io/en/latest/developer-guide/ksqldb-reference/scalar-functions/) though (`ARRAY` and `MAP` are documented there)
@JimGalasyn it seems like you are the lord of the docs :wink:, may be worth adding it there too. Took some time to find it although I knew it existed somewhere.

**Comment by JimGalasyn** [comment]
Thank you for the feedback, @karno123! I'm thinking this would be a good addition to the SELECT docs, _e.g._, [here](https://docs.ksqldb.io/en/latest/developer-guide/ksqldb-reference/select-push-query/).

**Comment by karno123** [comment]
Hi @PeterLindner, @JimGalasyn  Thanks for the answer. This is exactly what I want.

**Comment by JimGalasyn** [comment]
I'm tracking this issue with internal ticket DOCS-8265. We'll let you know when it's been resolved. Thanks again for the feedback!
