### ISSUE TITLE
Using double quotes in VARCHAR literals doesn't work

### ISSUE THREAD

**Issue by PetarLotrean** [confluentinc/ksql#754]
Some examples (that work in SQL):
`select '"TestValue"' as TestColumn from TestTable`
`select * from TestTable where TestColumn like '%Value"'`
`select 
	EXTRACTJSONFIELD(requestHeaders, '$["user-id"]') as user_id 
from test_stream;`

With errors:
`ksql> select ts, '"test"' as tst from article_view_raw;
Code generation failed for SelectValueMapper
Caused by: Line 1, Column 7: Unexpected token "test"`

Escaping with \ doesn't work either, nor using double double quotes.

**Comment by apurvam** [comment]
thanks for reporting this @PetarLotrean . this indeed seems like a bug.

**Comment by rmoff** [comment]
ref #1238 for workaround

**Comment by apurvam** [comment]
cc @agavra is this covered by the work on quoted identifiers? If not, should it be?

**Comment by agavra** [comment]
@apurvam - yes, this should be covered by that work. I will take a look and make sure that it is addressed!

**Comment by agavra** [comment]
This will be fixed in the next release of KSQL! Closing out, but feel free to re-open if you can reproduce on master:
```
ksql> SELECT '"col"', col FROM TEST EMIT CHANGES;
+----------------------------------------------+----------------------------------------------+
|KSQL_COL_0                                    |COL                                           |
+----------------------------------------------+----------------------------------------------+
|"col"                                         |"col"                                         |
```
