### ISSUE TITLE
How to query how long does a field value last

### ISSUE THREAD

**Issue by ChenZhaobin** [confluentinc/ksql#7589]
In my stream,I have 4 fields as below:
Id  long ,MachineCode varchar, MachineState int, CreateTime  timestamp

How to write a query to get  how long does the latest MachineState last based on CreateTime?

**Comment by MichaelDrogalis** [comment]
Can you explain more about what those columns represent? I don't understand what you're trying to achieve.

**Comment by ChenZhaobin** [comment]
@MichaelDrogalis 
For example ， 
Id      MachineCode       MachineState   DataGeneratedTime          Result
1             X001                  **RUNNING**          2021-05-21              1 DAY IN RUNNING  STATUS  
2             X001                  **RUNNING**          2021-05-22              2 DAY IN RUNNING  STATUS 
3             X001                  **RUNNING**          2021-05-23              3 DAY IN RUNNING  STATUS 
4             X001                  **RUNNING**          2021-05-24              4 DAY IN RUNNING  STATUS 
5             X001                  **POWEROFF**        2021-05-25              **1** DAY IN POWEROFF  STATUS 
6             X001                  **POWEROFF**        2021-05-25              **2** DAY IN POWEROFF  STATUS 
7             X001                  **POWEROFF**        2021-05-25              **3** DAY IN POWEROFF  STATUS 
8             X001                  **POWEROFF**        2021-05-25              **4** DAY IN POWEROFF  STATUS 
9             X001                  **RUNNING**          2021-05-25              1 DAY IN RUNNING  STATUS

**Comment by ChenZhaobin** [comment]
I find this:
https://stackoverflow.com/questions/54713760/kafka-time-difference-last-two-records-ksql-or-other

**Comment by MichaelDrogalis** [comment]
I think a [user-defined aggregation function](https://docs.ksqldb.io/en/latest/how-to-guides/create-a-user-defined-function/) would fit the bill here. Group by machine ID, and maintain intermediate state for the going high and low day, emitting the difference as the result.
