### ISSUE TITLE
Java client  0.18.0 dependencies issue

### ISSUE THREAD

**Issue by maksymilian-gasztych** [confluentinc/ksql#7619]
Dependencies for java client as described in the [following](https://docs.ksqldb.io/en/latest/developer-guide/ksqldb-clients/java-client/#getting-started) tutorial are incorrect since the 0.18.0 release.

The following dependency doesn't resolve so could you replace it with the correct one ?
https://jenkins-confluent-packages-beta-maven.s3.amazonaws.com/7.0.0-beta210423230724/1/maven/

I remember that there was an issue like that with 0.14 release too.

**Comment by jzaralim** [comment]
Hi @maksymilian-gasztych there is a typo in the docs. It should be https://jenkins-confluent-packages-beta-maven.s3.amazonaws.com/7.0.0-beta210423230724/2/maven/ instead. We will update the docs.

**Comment by jzaralim** [comment]
Docs are updated
