### ISSUE TITLE
Rest API from curl

### ISSUE THREAD

**Issue by mostetskyi** [confluentinc/ksql#762]
Hi, I want to post ksql query from CL by curl, but whem I tried to create stream I get strange exception. When I start this query from UI all Ok.
![exc](https://user-images.githubusercontent.com/26233738/36483821-e4d609a2-171f-11e8-959e-fb745505f4a8.jpg)

**Comment by voodoonv** [comment]
The same problem, please help, its very important

**Comment by rodesai** [comment]
Looks like a problem with your command. You have single-quotes (`'`) inside a single-quoted string (e.g. `'...kafka_topic='json'...'`) which actually terminates the single-quoted portion of the string, so your final string is actually: `...kafka_topic=json...` . KSQL then tries to interpret json as a reference. Try something line `'...kafka_topic='\'json\''...'`
