### ISSUE TITLE
404 : https://docs.ksqldb.io/en/latest/concepts/queries/select-pull-query.md

### ISSUE THREAD

**Issue by survivant** [confluentinc/ksql#7634]
![image](https://user-images.githubusercontent.com/191879/120698295-dac0f680-c47c-11eb-89ed-c1214288c696.png)

from this page : https://docs.ksqldb.io/en/latest/concepts/queries/
at the bottom : If you want to learn more about Pull Queries, see Pull Queries.   

If you click on Pull Queries.. you will get a 404

**Comment by agavra** [comment]
@survivant thanks for reporting! The hyperlink is indeed broken and we'll fix it ASAP. In the meantime here is the full link: https://docs.ksqldb.io/en/0.18.0-ksqldb/developer-guide/ksqldb-reference/select-pull-query/
