### ISSUE TITLE
How to  custom insert into query names when I execute it ?

### ISSUE THREAD

**Issue by ChenZhaobin** [confluentinc/ksql#7685]
I want to give 'insert into query' a name  when I execute the insert into command, is it possible ?
It should be like this  `insert into streamName select ....    Named as  myCustomQueryName`

If so ,I can run "terminate myCustomQueryName" when I don't need this query.[In my scenario ，it has  thousands of queries to a  stream]

**Comment by agavra** [comment]
@spena was thinking exactly about this - can you comment?

**Comment by spena** [comment]
@ChenZhaobin There's a syntax to specify a query ID to the insert statement, like:
```
INSERT INTO WITH (QUERY_ID='myID') SELECT ...
```
You can terminate that query using the same name:
```
TERMINATE myID;
```

Is that what you're looking for?

**Comment by ChenZhaobin** [comment]
@spena  thx very much , this is exactly what I'm looking for!
