### ISSUE TITLE
Create stream fails if hyphen is used

### ISSUE THREAD

**Issue by kapoora** [confluentinc/ksql#769]
CREATE STREAM agg_log (api-key varchar, api-request-method varchar, _message varchar) WITH (kafka_topic='ksql-test', value_format='json');

Caused by: line 1:27: extraneous input '-' expecting

**Comment by cricket007** [comment]
Try backticks? ``` `api-key` ```?

**Comment by rmoff** [comment]
Closing to track in #1466
