### ISSUE TITLE
Add support for compound types to COLLECT_SET and COLLECT_LIST

### ISSUE THREAD

**Issue by derekjn** [confluentinc/ksql#7697]
`COLLECT_SET` and `COLLECT_LIST` currently only support scalar types. We should expand the supported types to allow users to pass compound types (`Array`, `Map` and `Struct`) to these aggregates. Given that compound types may now be used as row keys, we should have the associated equality operators to make this possible.

**Comment by agavra** [comment]
depends on #6638

**Comment by jnh5y** [comment]
https://github.com/confluentinc/ksql/pull/8877 should handle this.
