### ISSUE TITLE
Kafka JS

### ISSUE THREAD

**Issue by pouledodue** [confluentinc/ksql#770]
### What

Capability to manipulate streams without compiling/scheduling/managing microservices.

### How

Using Javascript.

Capability to inject simple javascript into the Kafka engine like it is possible to do in the Event Store engine: https://eventstore.org/docs/projections/user-defined-projections/

In Event Store you can add/modify those scripts using an API or GUI textarea.

It makes easy to create new events when interesting combinations occur, create temporal correlation queries, and business logic using simple Javascript;

You can easily read streams, maintain a state and emit to other streams, all with simple javascript

### Implementation 
Maybe a Kafka dev can tell if Kafka Streams already has all what is needed to support this, maybe transparently binding javascript `state` variable to a state store or KTable?

### Benefits
- Easy to add business logic to Kafka
- Easy to manipulate streams without having to code/compile/schedule/manage microservices for each small piece of business logic or temporal correlation query
- Lower barrier of entry
- Everyone on the team know Javascript
- Fast transitioning of traditional three-tier developers to the streaming architecture mental schema. They get results fast, a new world opens to them and they want to Kafkaify all the world.

related:
https://github.com/fhussonnois/kafkastreams-cep

**Comment by cricket007** [comment]
Related to #304 with AJAX. 

Also see the [KSQL UI](https://github.com/confluentinc/ksql-experimental-ui) project for JavaScript implementations

**Comment by miguno** [comment]
Thanks for your write-up @pouledodue!

This is related to https://github.com/confluentinc/ksql/issues/678 - Support user-defined functions (UDF).

Note: The feature requests we are managing in this project (KSQL) are for functionality that goes into KSQL.  I am not sure whether your feature request is about (1) support JavaScript "in some form" in KSQL vs. (2) creating a Kafka Streams like JavaScript library.  (1) is in scope for the KSQL project whereas (2) is not. Perhaps you could clarify, @pouledodue?

**Comment by pouledodue** [comment]
so:
* javascript
* injectable via REST ([like KSQL](https://github.com/confluentinc/ksql/issues/304)) and GUI
* no need to deploy a microservice

is it a standalone library like [winton's python lib](https://github.com/wintoncode/winton-kafka-streams) ? **no**
is it in scope for KSQL? **no**

where can I post this enhancement request? There seem to be interest 👍. In the [JIRA](https://issues.apache.org/jira/browse/KAFKA) as `improvement`?

@cricket007 [ksql-experimental-ui](https://github.com/confluentinc/ksql-experimental-ui) has been removed, do you know where I can find it now?

**Comment by miguno** [comment]
> where can I post this enhancement request? There seem to be interest 👍. In the [JIRA](https://issues.apache.org/jira/browse/KAFKA) as improvement?

You can do that, yes.  I also took a note myself for this feature request.

> ksql-experimental-ui has been removed, do you know where I can find it now?

This project was actually meant to be closed source. You'll see the experimental UI for KSQL as part of upcoming Confluent Platform 4.1 (ETA: early April).

**Comment by miguno** [comment]
@pouledodue : Since this is not in scope for KSQL (you said so yourself), I will close this issue.
