### ISSUE TITLE
Ksqldb's metastore turns into unhealthy state after some period of time

### ISSUE THREAD

**Issue by maksymilian-gasztych** [confluentinc/ksql#7704]
**Describe the bug**
Recently I tried to execute show queries extended and I noticed that one of our three ksqldb servers shows as unresponsive for all queries, which got me concerned. Can it be a bug in the ksqldb-cli or our ksqldb settings are just wrong ? 
(By the way show queries throws null.pointer.exception from time to time which is definitely another bug)

Part of the output from ksqldb-cli
`Host Query Status    : {10.92.5.31:8088=RUNNING, 10.92.2.98:8088=RUNNING, 10.92.4.96:8088=UNRESPONSIVE}`
Excerpt from logs from respective ksqldb-server instances:

```
Using 'ksql.advertised.listener' config for intra-node communication: http://10.92.2.98:8088
Using 'ksql.advertised.listener' config for intra-node communication: http://10.92.5.31:8088
Using 'ksql.advertised.listener' config for intra-node communication: http://10.92.4.96:8088
```

part of our ksqldb-server configuration (everything set up according to the docs):

```
KSQL_LISTENERS: http://0.0.0.0:8088
KSQL_BOOTSTRAP_SERVERS: PLAINTEXT://kafka-cluster-kafka-bootstrap:9092
KSQL_KSQL_STERAMS_CACHE_MAX_BYTES_BUFFERING: "40000000"
KSQL_KSQL_STREAMS_NUM_STREAM_THREADS: "8"
KSQL_CONNECT_REST_ADVERTISED_HOST_NAME: << here goes the ip address of the kubernetes pod in which the ksqldb server is deployed
KSQL_KSQL_ADVERTISED_LISTENER: "http://$KSQL_CONNECT_REST_ADVERTISED_HOST_NAME:8088"
```

**To Reproduce**

Run cluster of 3 nodes of ksqldb-server 0.18.0

**Expected behavior**
execution of show queries extended shows that all ksqldb servers are in running state

**Actual behaviour**
one of the servers shows up as unresponsive

**Additional context**

**Comment by maksymilian-gasztych** [comment]
I tried to recreate pods and now everything is fine, which leads me to believe that there's some bug either in the show queries command, or in the ksqldb itself, if it was really unresponsive, which I have no idea how to actually verify since it did respond to commands.
`Host Query Status    : {10.92.4.28:8088=RUNNING, 10.92.5.137:8088=RUNNING, 10.92.3.18:8088=RUNNING}`

**Comment by maksymilian-gasztych** [comment]
After sometime, one of the servers started to have problems with metastore whatever it is, and the show queries again shows status unresponsive. Any ideas?
`{"isHealthy":false,"details":{"metastore":{"isHealthy":false},"kafka":{"isHealthy":true},"commandRunner":{"isHealthy":true}}}`

**Comment by vcrfxia** [comment]
Hi @maksymilian-gasztych , do you have a way to reproduce this issue to aid in investigation?

**Comment by maksymilian-gasztych** [comment]
Hi, it happend 3 times so far ( in course of 2 weeks - we disabled auto restart of unhealthy servers so maybe it was happening before, but I have no way of knowing) I'll let you know if I find somehting out.

**Comment by maksymilian-gasztych** [comment]
After the weekend, all the servers have that metastore unhealthy status, and I don't see any corresponding logs, maybe it's normal that metastore is unhealthy ? I wonder if effect will be the same if I don't run any queries at all, and just 2 servers in cluster mode the. Is there any documentation on metastore ? There doesn't seem to be any issues with persistent queries we're running, it's just that status.

**Comment by maksymilian-gasztych** [comment]
It seems that the issue doesn't occur anymore after we upgraded to ksqldb 0.19.0, so I'm closing the issue.
