### ISSUE TITLE
Rename ksql-cli to ksql and remove standalone and local mode

### ISSUE THREAD

**Issue by dguy** [confluentinc/ksql#773]
We want to rename `bin/ksql-cli` to `ksql` and remove the ability to run it in `local` and `standalone` mode. The only arguments it should accept are the address of a ksql rest server, username, and password. i.e.,
`ksql http://my-ksql-server:8080 --user user --password pass`

If no server is provided it should be set to the ksql default, i.e., localhost:9080

Ensure docker images work with this change

**Comment by miguno** [comment]
> If no server is provided it should be set to the ksql default, i.e., localhost:9080

I suppose that's a typo.  The default KSQL server endpoint should be `http://localhost:8080`, right?

**Comment by miguno** [comment]
> Ensure docker images work with this change

We must also ensure that the upcoming Confluent CLI integration works with these changes.
