### ISSUE TITLE
Enhance ksql server startup

### ISSUE THREAD

**Issue by dguy** [confluentinc/ksql#774]
We currently do this by running `ksql-cli standalone /path/to/queries.sql`. As we will be removing this option from the cli we need to add it to the `ksql-server-start` script.

We need to enhance the script and the main method to accept two parameters:
1. `/path/to/ksql-server.properties` (required)
2. `--queries-file=/path/to/queries.sql` (optional)

When `--queries-file` is present we should not start the REST service, the experimental UI, or connect to the command topic, i.e., it will run "standalone" as it does today via `ksql-cli standalone`.

We should also print out a suitable message when the server starts, i..e., something like:
"KSQL Server started with query file /path/to/queries.sql. Interactive mode is disabled"

We can also add another property to the server config, i.e, `queries.file`, if this is present then it would have the same effect as passing in the cmd-line argument (this is to support init scripts for example). If the cmd-line argument is present it should take precedence.

Ensure that docker images work with these changes.

**Comment by miguno** [comment]
I'd suggest the following startup message when `--queries-file` is present:

> KSQL server is executing a pre-defined set of queries from /path/to/foo.sql. Interactive functionality (REST API, UI, access via CLI) has been disabled automatically.

**Comment by miguno** [comment]
To add to the above:  As part of this ticket we should also remove the current `ksql-node` script and fold its functionality (running the KSQL server standalone, given a .sql file) into `ksql-server-start`.

**Comment by miguno** [comment]
Two further comments:

> `--config-file=/path/to/ksql-server.properties`

This setting should be optional (as you wrote above), and it should have a default value for the location of the KSQL server config file.  My suggestion would be `/etc/ksql/ksql-server.properties`.

> `--queries-file=/path/to/queries.sql`

This setting should be optional (as you wrote above), but it should not have a default value for the location of the .sql file.

**Comment by miguno** [comment]
> Ensure that docker images work with these changes.

We must also ensure that the upcoming Confluent CLI integration works with these changes.

**Comment by dguy** [comment]
I've changed the `--config-file` param to be required as (so no --config-file):
1. it is presently required.
2. I don't believe there is a sensible default.
3. Other confluent projects don't default this, i.e, schema-registry

**Comment by blueedgenick** [comment]
i think that magically disabling the http listener is too extreme if there's no way to turn it back on again. Feedback suggests that the ability to keep the http listener alive, even if only on one server node out of a group which is processing the same sql application, is a useful and desirable capability for sysadmins. The folks I've talked to all suggested some variant of using e.g. nginx reverse proxy to limit access to that one node but they do want the ability to log in via a cli and "poke around" to check status etc.
Therefore I suggest that we move to more explicit requesting of behavior with these parameters - perhaps introduce an extra flag for `--ui-enabled` or similar to give people the option of rolling their own permutations.

**Comment by bluemonk3y** [comment]
I agree - magic is bad and all changes must be obvious. BTW - many banks will deny any form of interactive access and want it locked down, they would also want to enforce the loading of a config file (probably from source control or as part of the devops infra). Any messing around will be done against a prod backup. We need the ability to support all permutations of client requirements (i.e. those that will want to support interactive behaviour in prod)

**Comment by miguno** [comment]
What's the status here?  IIRC @dguy said offline that we'll be going with the auto-disabling of the REST API in case the user defines `--queries-file`?

**Comment by dguy** [comment]
Correct - for 4.1, at least, we will go with what we had already discussed.

**Comment by big-andy-coates** [comment]
@blueedgenick I thought similar.  Some orgs might want it fully locked down, like banks, as @bluemonk3y  says, but many others will want the ability to poke around for support reasons. 

What's needed IMHO is the ability to bring up one or more nodes with the same metadata as the production pool, but which won't actively partake in processing any of the data. These nodes can then support the UI / rest end point and allow interactive users. Any new statements would run only on the interactive nodes.

So, for example, say the production pool is hard coded to to process a could of streams, then the interactive nodes would a) know about these streams/tables and their format / metadata, b) allow `SELECT foo, bar FROM x` style ops against these streams, and c) allow other persistent CSAS ops to be created.  All processing for this adhoc work should only be done on interactive nodes.

Affectively, this is just supporting _SLA_ and _interactive_ nodes within a pool, or sharing the same metadata between an _SLA_ pool and an _interactive_ pool. 

Could this not be achieved by running two pools:
1. A _SLA_ pool, with a supplied _queries_ file and no REST or UI.
2. An _interactive_ pool, with the same _queries_ file, plus the REST and UI, but with a flag to say 'Do no start queries' when processing the queries file.

**Comment by miguno** [comment]
@big-andy-coates: Thanks for chiming in, Andy!

What you describe is quite different IMHO to what this PR is about, and I would prefer us to not increase the scope of this PR.

> Some orgs might want it fully locked down, like banks, as @bluemonk3y says, but many others will want the ability to poke around for support reasons.

I'd throw in that "poking around" for support reasons may not necessarily imply running SQL queries in the same (locked-down) cluster.  There are other ways (like the JMX metrics we are currently exposing, or log files) for such purposes.  I agree that we could do more, but I'd suggest to create a separate GH ticket for that.

> Affectively, this is just supporting SLA and interactive nodes within a pool, or sharing the same metadata between an SLA pool and an interactive pool.

I remember this from an offline conversation.  Let's keep this separate from @dguy's PR.

**Comment by big-andy-coates** [comment]
Sure. Np :) I just thought I'd add to @blueedgenick's comments, which were along the same lines.
