### ISSUE TITLE
as_map function not possible for Array<T> as propagated by ksqldb-server

### ISSUE THREAD

**Issue by lkaupp** [confluentinc/ksql#7741]
**Describe the bug**
The as_map function is not working as expected. From Documentation:
`AS_MAP(keys, vals)`
`which should be (as returned by KSQLDB-Server): keys: Array<VARCHAR>, values: Array<T>`

but in current version 0.17.0:

CREATE STREAM env5_map WITH (KAFKA_TOPIC='env5_map') AS SELECT rowkey, as_map(array['datetime', 'source', 'SGRP'], array[datetime, source, SGRP]) as val_map FROM env5_stream;

datetime is BIGINT
source is VARCHAR
SGRP is DOUBLE

an error is thrown:
Could not determine output schema for query due to error: operator does not exist: BIGINT = STRING (SOURCE)

**To Reproduce**
Create a topic with AVRO-Schema and value fields with (datetime BIGINT, source VARCHAR, sgrp DOUBLE);
Create a stream ontop that mirror the topic;
Try to create a map_stream as shown above;
Error should appear.

**Expected behavior**
Map should be created with multiple different types.

**Actual behaviour**
Not possible without casting everything to string forth / back and loosing percision on the cast / recast.

**Additional context**
Workaround cast all values to String as described in the answer:
https://stackoverflow.com/questions/62674452/map-scalar-function-issue-in-ksqldb

**Comment by PeterLindner** [comment]
@lkaupp according to the [docs for the Map type](https://docs.ksqldb.io/en/latest/reference/sql/data-types/#map):
>All of the keys must be of the same type, and all of the values must also be of the same type.

You probably want to use a [Struct](https://docs.ksqldb.io/en/latest/reference/sql/data-types/#struct), which supports different types for its field, instead

**Comment by lkaupp** [comment]
idk why i do not found this doc in the first place. Thank you for your suggestion. i gonna use a struct for that instead. 👍
