### ISSUE TITLE
Unclear retention times - topic, stream, table - unexpected behaviour

### ISSUE THREAD

**Issue by lkaupp** [confluentinc/ksql#7747]
At the moment i think i have a problem with retention during my stream and table creation. Maybe it is also a bug, but i report this first as a documentation issue. First, here is my procedure:

`SET 'auto.offset.reset'='earliest';
events -> topic -> create mirror stream1 on topic -> create derived_stream1 on stream1 -> create table table1 on derived_stream1 with window where attr like 'test%' group by etc.`

At the moment i do not explicitly set the retention time. Now, the current behaviour bugs me around. If i do the whole procedure in one, one after another everything works fine. I also can create multiple tables with where conditions as the like operator, everything works as expected. The `select * from table1;` gives me all right results. After some time if i want to create another table (in the same session, maybe 1 hour later) the table is created but not filled. It get only be filled if i recreate a new mirror stream of the topic, another new derived_stream and than the table again. If i create only the table, the table is not filled (the query is identical to the first query). I think this is related to retention time, but the docs are very spare about that issue. I found out that the kafka topic could have a retention time and the window function has also a retention time. What is about the stream, did they have also a hidden retention time? What can lead to this behaviour? Can someone pin point me in the right direction - or is it simply a bug?

**Comment by agavra** [comment]
Hello @lkaupp - thanks for submitting the ticket. Can you give us the statements that you were using as well as some sample data to reproduce the issue? That will make it easier for us to dig into it.

**Comment by lkaupp** [comment]
This is still a problem, but at the time of writing, I have no example that I can share. The bug is correlated with a big number of tables and streams ~40k in parallel. Maybe there are also race conditions if you create tables/streams on top of each other filled by rules before they are fully initialized. For 40k tables this took quite a while until everything was up and running.
