### ISSUE TITLE
Enable ksql-server properties to be supplied on the command line via java system properties

### ISSUE THREAD

**Issue by dguy** [confluentinc/ksql#775]
We should have the ability to override/set ksql properties via the command line, i.e,
`ksql-server-start /path/to/config.properties -Dbootstrap.servers=overriden:8080 -Dnum.stream.threads=1`
etc.

The properties supplied on the command line should take precedence over those loaded from the config file.

This should, for example, help us provide a docker images where people can set arguments via ENV variables (need to look into this)

We need to ensure that the docker images work with these changes

**Comment by miguno** [comment]
@dguy: AFAIU this change is really required only for our follow-up work on Docker images (e.g. a dedicated KSQL-server-only Docker image)?

**Comment by apurvam** [comment]
This will also be useful for deployments in environments like Heroku.

**Comment by ewencp** [comment]
Do we actually want to expose jvm-specifics like this so directly, and if so why? I have no doubt we already do so, but why would we not expose it in a cleaner way for overriding configs? Java-isms are a really terrible UI for most users... I've been working in the ecosystem for quite awhile and still get confused over gradle properties, java system properties, and how they all interact.

Why wouldn't KSQL just have some set of properties, a set of command line args, and rules for how they apply? The Java mess is what makes the gradle rules absolutely confusing for me...

**Comment by dguy** [comment]
yeah - we have a set of properties, which is all the ksql, streams, producer, consumer configs etc that are read from a properties file as supplied on the command line. So for most people running KSQL is just:
`bin/ksql-server-start my.properties`

This is really so that people can override those properties if they were using a docker image, for example. So they don't need to have a different image for each configuration property.

Anyway, i'm open to suggestions on a better way to do it, but specifying command line arguments for every property is not it.

**Comment by miguno** [comment]
I'm with @dguy here.  Open to better suggestions, but I don't see why it would be cumbersome to follow the simple pattern of specifying any required KSQL settings (that would normally go into a properties file like `/etc/ksql/ksql-server.properties`) via `-D` on the command line.

As Damian mentioned the use case is primarily for someone configuring a Docker container for KSQL.

**Comment by big-andy-coates** [comment]
Such a feature can also be really useful to SRE / Sysadmins for plugging in secure credentials at runtime, rather than having them in the config file.

**Comment by ewencp** [comment]
So this neither matches the existing tooling we have for handling env vars in docker images (where you don't need any customization for the service, we just build out the properties file for you) nor the patterns we're using to do it in a non-Docker-ecosystem-standard way but much more simply, which is to use volumes to mount the config directly and not have to jump through these extra hoops.

Has there been a design pass done on how the docker image should work, and/or an attempt to ensure the way these work will be aligned with the rest of CP?

**Comment by dguy** [comment]
There is nothing here that stops from doing it the CP way. The default way of doing things is to load config from a properties file. All that is added is the ability to override those configs on the command line via system properties if for some reason you can't modify the properties file (or don't want to). 
We should create the Docker images in the standard CP way.
