### ISSUE TITLE
Can ksqldb-server log as JSON?

### ISSUE THREAD

**Issue by mathieux51** [confluentinc/ksql#7757]
Howdy folks, 

I'm using `confluentinc/ksqldb-server:0.18.0` and I was wondering if I can get the logs in JSON format? 
Ideally I'd like to had the following configuration into a configmap and `ksqldb-server` would pick it up.
```
  log4j.properties: |
    log4j.appender.CONSOLE=org.apache.log4j.ConsoleAppender
    log4j.appender.CONSOLE.layout=net.logstash.log4j.JSONEventLayoutV1
    log4j.rootLogger=INFO, CONSOLE
```

Possible?

**Comment by maksymilian-gasztych** [comment]
Yes it can, if you provide a json layout for log4j 1.2.X . I've implemented layout that supports google cloud logging because there was none that I could find. (Not sure if there's a simpler way) Just drop in your layout jar onto the classpath and your done.
Our log4j props:
```
log4j.rootLogger=INFO, stdout

# appenders
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=jp.menu.jinrai.GoogleCloudLoggingLayout

log4j.appender.streams=org.apache.log4j.ConsoleAppender
log4j.appender.streams.layout=jp.menu.jinrai.GoogleCloudLoggingLayout

log4j.appender.main=org.apache.log4j.ConsoleAppender
log4j.appender.main.layout=jp.menu.jinrai.GoogleCloudLoggingLayout

log4j.appender.kafka=org.apache.log4j.ConsoleAppender
log4j.appender.kafka.layout=jp.menu.jinrai.GoogleCloudLoggingLayout
```

**Comment by agavra** [comment]
Thanks @maksymilian-gasztych for the suggestion - we do use log4j for all of our logging, so I recommend you look at solutions out there for JSON logging (including Maksymilian's suggestion). I'll close out this ticket for now, but feel free to reopen if you need anything else.
