### ISSUE TITLE
can we specific Ksql table start time

### ISSUE THREAD

**Issue by nesmaalshazly** [confluentinc/ksql#7779]
Hello

 I have a requirement to create window that start at 5 am and last for 24 hours
 I can not find a way to specify window start time , only how to define window size
if i defined it as 24 it automatically start at 12 am
any help?

**Comment by vcrfxia** [comment]
Hi @nesmaalshazly , I believe your request is a duplicate of https://github.com/confluentinc/ksql/issues/4460. This feature cannot be implemented in ksqlDB today as Kafka Streams (ksqlDB's underlying implementation) does not support it. You may want to file an enhancement request for Kafka Streams: https://issues.apache.org/jira/browse/KAFKA. Thanks.
