### ISSUE TITLE
Migrations tool jars are missing from Confluent Platform Docker versions

### ISSUE THREAD

**Issue by colinhicks** [confluentinc/ksql#7786]
**Describe the bug**
Attempting to run `ksql-migrations` in platform Docker versions, including `confluentinc/cp-ksqldb-server:6.2.0` or `confluentinc/cp-ksqldb-cli:6.2.0`, fails.

**To Reproduce**
```
$ docker run -it confluentinc/cp-ksqldb-server:6.2.0 ksql-migrations
Error: Could not find or load main class io.confluent.ksql.tools.migrations.Migrations
Caused by: java.lang.ClassNotFoundException: io.confluent.ksql.tools.migrations.Migrations
```

**Additional context**
The `cp-ksqldb-` prefixed images use separate poms, which are missing the migration tool's module:
* https://github.com/confluentinc/ksql-images/blob/master/cp-ksqldb-cli/pom.xml
* https://github.com/confluentinc/ksql-images/blob/master/cp-ksqldb-server/pom.xml

This needs to be added:
```xml
    <dependency>
      <groupId>io.confluent.ksql</groupId>
      <artifactId>ksqldb-tools</artifactId>
      <version>${io.confluent.ksql.version}</version>
    </dependency>
```

The **workaround** is to use a standalone Docker image version for the migration tool. For example the `ksql-migrations` tool in `confluentinc/ksqldb-server:0.18.0` can be run against ksqlDB servers running Confluent Platform ksqlDB 6.2.0.

Originally filed as https://github.com/confluentinc/ksql-images/issues/60.

**Comment by jzaralim** [comment]
This is fixed: https://github.com/confluentinc/ksql-images/pull/62
