### ISSUE TITLE
Pull Query table scans do not support LIKE or BETWEEN operators

### ISSUE THREAD

**Issue by agavra** [confluentinc/ksql#7793]
**Describe the bug**

Table scans should support the full suite of operations in the `WHERE` clause, however `LIKE` is not supported:

**To Reproduce**

Issue any query with `WHERE key LIKE '%foo%';`

**Expected behavior**

Query works

**Actual behaviour**

```
ksql> set 'ksql.query.pull.table.scan.enabled'='true';
Successfully changed local property 'ksql.query.pull.table.scan.enabled' from 'true' to 'true'.
ksql> select * from prices where key LIKE '%aws:high:standard_v2:peered-vpc-internet%';
Unsupported expression in WHERE clause: (KEY LIKE '%aws:high:standard_v2:peered-vpc-internet%').  See https://cnfl.io/queries for more info.
Add EMIT CHANGES if you intended to issue a push query.
Pull queries require a WHERE clause that:
 - includes a key equality expression, e.g. `SELECT * FROM X WHERE <key-column>=Y;`.
 - in the case of a multi-column key, is a conjunction of equality expressions that cover all key columns.

If more flexible queries are needed, table scans can be enabled by setting ksql.query.pull.table.scan.enabled=true.
```

**Comment by Goodkat** [comment]
It seems that "LIKE" is not only the operation which is not supported.
Checking the code I found out that "IN" and "OR" are not allowed for Pull queries as well.

```java
  /**
   * Validate the WHERE clause for pull queries. Each of these validation steps are taken for each
   * disjunct of a DNF expression.
   * 1. There must be exactly one equality condition per key.
   * 2. An IN predicate has been transformed to equality conditions and therefore isn't handled.
   * 3. Only AND is allowed.
   * 4. If there is a multi-key, conditions on all keys must be specified.
   */
```

https://github.com/confluentinc/ksql/blob/master/ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/QueryFilterNode.java#L254

**Comment by agavra** [comment]
@Goodkat - what version are you using? if you enable table scans then it doesn't check for the validity of the pull query using the function you are referencing. the config is `set 'ksql.query.pull.table.scan.enabled'='true';`

**Comment by Goodkat** [comment]
@agavra - version of what? I just checked the master repo. And the exception you got only appeared in the function I referred to. Thus, even if you have enabled table scans, it is still checking for the validity of the pull query.

https://github.com/confluentinc/ksql/blob/master/ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/QueryFilterNode.java#L278

**Comment by agavra** [comment]
Got it, I had assumed you were hitting this in a deployment. Without digging into the code, I think the issue I've described here is that it should not go through that code path for `LIKE`, but for some reason it does.

The other query types you mentioned are supported even w/o table scans:
```
ksql> create table foo (id int primary key, col1 varchar) with (kafka_topic='foo', format='json', partitions=1);

 Message
---------------
 Table created
---------------
ksql> create table foo_mat as select * from foo;
inser
 Message
--------------------------------------
 Created query with ID CTAS_FOO_MAT_3
--------------------------------------
t ksql> insert into foo (id, col1) values (1, 'a');
ksql> insert into foo (id, col1) values (2, 'b');

ksql> select * from foo_mat where id in (1, 2);
+--------------------------------------+--------------------------------------+
|ID                                    |COL1                                  |
+--------------------------------------+--------------------------------------+
|1                                     |a                                     |
|2                                     |b                                     |
Query terminated

ksql> select * from foo_mat where id = 1 or id = 2;
+--------------------------------------+--------------------------------------+
|ID                                    |COL1                                  |
+--------------------------------------+--------------------------------------+
|1                                     |a                                     |
|2                                     |b                                     |
Query terminated
```

**Comment by Goodkat** [comment]
The same problem with `BETWEEN` expression. 
I assume we have to implement the `LikeExpression` and  `BetweenExpression` classes, as it is done for `InListExpression` and `LogicalBinaryExpression` which include `IN` and `OR` operators respectively.

**Comment by Goodkat** [comment]
@agavra I am trying to build the project locally, run `mvn clean package -DskipTests` on project root, but getting the error: 
`[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM io.confluent:common:[7.1.0-0, 7.1.1-0) for io.confluent.ksql:ksqldb-parent:7.1.0-0: No versions matched the requested parent version range '[7.1.0-0, 7.1.1-0)' and 'parent.relativePath' points at wrong local POM @ line 22, column 13`
I have checked the issue https://github.com/confluentinc/ksql/issues/5483 and added the additional entries in my `pom.xml` as described there, but the result is still the same.
Do you have any ideas how to build it locally for now?

**Comment by agavra** [comment]
@Goodkat can you open a new issue for this to make sure it gets triaged separately? I don't have bandwidth right now to dig into this (and I don't know off the top of my head what might be causing that)
