### ISSUE TITLE
ksql-server-start requires params but docs say not

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#780]
Per: https://github.com/confluentinc/ksql/blob/v0.5/docs/concepts.md#client-server-mode

> Start with default settings:
> 
> `$ ./bin/ksql-server-start`

But: 

```
Robin@asgard02 ~/g/ksql> ./bin/ksql-server-start
USAGE: ./bin/ksql-server-start [-daemon] ksqlserver.properties
```

**Comment by big-andy-coates** [comment]
I've fixed this in the 4.1.x branch, which will get merged across soon.

Happy to close this?

**Comment by rmoff** [comment]
Sure! So are the parms required, or not?

**Comment by big-andy-coates** [comment]
The property file is required.
