### ISSUE TITLE
Async stream method implementation is missed at KsqlRestClient

### ISSUE THREAD

**Issue by pkgonan** [confluentinc/ksql#7842]
**Is your feature request related to a problem? Please describe.**
The KsqlRestClient appears to be an easy tool to use the KsqlClient. But KsqlRestClient did not provide async streaming method using postQueryRequestStreamedAsync at KsqlClient.java.

**Describe the solution you'd like**
Support async streaming method using postQueryRequestStreamedAsync at KsqlClient.java.

**Describe alternatives you've considered**
Use KsqlClient directly, not KsqlRestClient.

**Comment by vcrfxia** [comment]
Hi @pkgonan , KsqlClient and KsqlRestClient are not meant for use outside the ksqlDB codebase. Their APIs are not guaranteed and may be changed without notice in the future. ksqlDB supports a separate Java client for which the API does come with guarantees, and which also supports async streaming. Here are the docs: https://docs.ksqldb.io/en/latest/developer-guide/ksqldb-clients/java-client/
