### ISSUE TITLE
Grafana 502 Bad Gateway

### ISSUE THREAD

**Issue by unruledboy** [confluentinc/ksql#789]
I think it is the same problem as [Issue 373](https://github.com/confluentinc/ksql/issues/373), now graph being shown

But after I recreate the whole container from scratch, it is the same thing.

And yes, I think somehow the port 9200 is not exposing to the host. Any idea?

My environment:
- Windows 10
- Docker Version 17.12.0-ce-win47 (15139)

**Comment by rmoff** [comment]
@unruledboy can you try with the latest quickstart, and report back with version numbers & exact URL followed  if you still have the same problem?

**Comment by miguno** [comment]
Closing this older ticket.  Please reopen if needed, @unruledboy.
