### ISSUE TITLE
Support specifying fully-qualified record name for PROTOBUF and JSON_SR

### ISSUE THREAD

**Issue by mikebin** [confluentinc/ksql#7925]
**Is your feature request related to a problem? Please describe.**
ksqlDB currently supports specifying a top-level fully-qualified record name for the `AVRO` format with `VALUE_AVRO_SCHEMA_FULL_NAME`, but this isn't currently supported for `PROTOBUF` and `JSON_SR`. So you end up with a default record name in the schema like `ConnectDefault1`, which might be undesirable for application(s) which need to consume the data downstream.

**Describe the solution you'd like**
Add equivalent support for specifying a top-level fully-qualified record name with `PROTOBUF` and `JSON_SR` - perhaps rename `VALUE_AVRO_SCHEMA_FULL_NAME` to `VALUE_SCHEMA_FULL_NAME`.

**Describe alternatives you've considered**

**Additional context**
Would we need similar support for specifying fully-qualified record names for for key schemas as well, now that ksqlDB supports keys in Avro, Protobuf, and JSON Schema format?

**Comment by colinhicks** [comment]
Older issue with the same property-renaming suggestion as above: https://github.com/confluentinc/ksql/issues/4656
