### ISSUE TITLE
Multiple Schema Registry in Single Cluster

### ISSUE THREAD

**Issue by ishaan-k03** [confluentinc/ksql#7934]
I am using multiple schema in case one server goes down it should use second.
But in ksql it seems we can only give one url in [ksql.schema.registry.url] property.

Also,
I created schema cluster but still in topic I need to manually provide the working schema url.

Please provide some enhancement on this.

**Comment by vcrfxia** [comment]
Hi @ishaan-k03 , you are correct that ksqlDB today only supports a single schema registry URL in its config. Supporting multiple such URLs is an enhancement that we would like to add at some point. 

> I created schema cluster but still in topic I need to manually provide the working schema url.

Can you please clarify what you mean by this? I'm not sure what it means to provide a schema url in a topic. The various [tutorials](https://docs.ksqldb.io/en/latest/tutorials/) on the microsite demonstrate ksqlDB deployments with Schema Registry. Hope they help if you haven't seen them already.

**Comment by PeterLindner** [comment]
@vcrfxia may be beneficial to also support multiple A records similar to the Kafka client config `client.dns.lookup=use_all_dns_ips`

**Comment by spena** [comment]
@PeterLindner I tested the multiple SR and it works. I set `ksql.schema.registry.url` like this:
```
ksql.schema.registry.url=localhost:8081,localhost:8082
```

The SR documentation says the above config supports that too - https://docs.confluent.io/platform/current/schema-registry/index.html#high-availability-for-single-primary-setup

What's the error you got when you tried it?

**Comment by PeterLindner** [comment]
@spena unfortunately I can't remember what went wrong. The version I tested with was 5.3.1 (probably not worth investigating)
However, I though it would be a nice addition to ksqlDB, if one could just specify a single schema registry url but have high availability without an actual loadbalancer (or when using multiple loadbalancers).
It was just an idea though, since kafka itself already supports this.

**Comment by spena** [comment]
Thanks @PeterLindner . I think I'm gonna close this issue then. 

However, could you create another issue with more details about the below comment? I didn't understand it, so it'd be nice to have what is expected and maybe linking the examples of Kafka.
```
However, I though it would be a nice addition to ksqlDB, if one could just specify a single schema registry url but have high availability without an actual loadbalancer (or when using multiple loadbalancers).
```
