### ISSUE TITLE
Clickstream Analysis screencast link broken

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#796]
On this page: https://github.com/confluentinc/ksql/tree/master/ksql-clickstream-demo, there is an image of a screen cast just below the text `Click here to watch a screencast of the KSQL demo on YouTube.`, but clicking on the image opens the image, not the youtube video.

**Comment by joel-hamill** [comment]
https://github.com/confluentinc/ksql/pull/798
