### ISSUE TITLE
Add cool ASCII art KSQL rocket to splash screen

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#797]
Can we get @derrickdoo  to do a cool little ASCII art KSQL rocket for the CLI/server splash screens ? e.g. like https://textart.io/art/J2Jz7aDnHHZ9_2Nr50l8VgeF/spaceship-rocket

**Comment by big-andy-coates** [comment]
Hey @rmoff, if you can get @derrickdoo to come up with the ASCII art, I can plug it in... :D

**Comment by uurl** [comment]
[ksql.txt](https://github.com/confluentinc/ksql/files/2218817/ksql.txt)
@rmoff @big-andy-coates KSQL rocket in ASCII art
