### ISSUE TITLE
Is there a way to fix a table with sum that turned negative ?

### ISSUE THREAD

**Issue by maksymilian-gasztych** [confluentinc/ksql#7986]
After a few days of running, SUM aggregate of one of our tables becomes negative. It happens always and the sum never goes back to normal. Is there a way to do something to fix that without removing the query with the backing topics and recreating it ? It always happens for only one particular query, similar to the **stats_by_block** below:

```
            CREATE TABLE stats_by_area AS
                SELECT
                    da.area_id,
                    da.block_id,
                    IFNULL(ossa.a,0) +
                    IFNULL(ossa.b,0) +
                    IFNULL(ossa.c,0) +
                    IFNULL(osua.d,0) +
                    IFNULL(osua.e,0)
                        AS abcde,
                    IFNULL(ossa.a0)+IFNULL(ossa.b,0) AS ab,
                    IFNULL(ossa.c,0) AS c,
                    IFNULL(ossa.d,0) AS d,
                    ....
                FROM da
                LEFT JOIN  ossa ON ossa.id = da.area_id
                LEFT JOIN  osua ON osua.id = da.area_id
                LEFT JOIN ocba ON ocba.id = da.area_id;
                
               CREATE TABLE stats_by_block AS
                SELECT
                    block_id,
                    SUM(a+b+c+d+e) AS abcde,
                    SUM(a+b) AS ab,
                    SUM(a) AS a,
                    SUM(b) AS b
                FROM stats_by_area
                GROUP BY block_id
                EMIT CHANGES;
```

Right now I drop the query and recreate it for it  to get back to normal but I wonder if there's any better way. It looks like a huge bug of Ksqldb or there's something wrong fit the table definition. Note that there's never invalid data in stats_by_area table, so the problem lies solely within that single stats_by_block table

**Provide details of the setup you're running**
any ksqldb version

**Comment by mjsax** [comment]
Why are you assuming that the SUM cannot be negative? If you have negative input data, the SUM would become negative, right?

> Note that there's never invalid data in stats_by_area table

What would you consider invalid data?

**Comment by maksymilian-gasztych** [comment]
I'm (obviously) summing positive numbers (which are created by queries similar to the one below), and the data in those tables is never negative (as it shouldn't because it's just sum of ones) but the result table stats_by_block after some times starts to show negative values, and my question is, is there a way to fix that ? 

```
CREATE TABLE ossa AS SELECT
    area_id,
    SUM(1) AS count
FROM xxx
WHERE state = 2
GROUP BY area_id
EMIT CHANGES;
```

**Comment by mjsax** [comment]
Thanks for the details.

> I'm (obviously) summing positive numbers

Well, the question did not say... Just starting from basic principles. Sometimes people just miss things like this.

Not sure what the root cause could be, but one issue with table aggregations is, that an upstream change of the aggregation input table, create two records that need to be processed downstream: the old row form the input table is "subtracted" from the downstream result and the new row of the input table is "added" to the result. If for whatever reason the "adding" record gets lost but only the "substraction" record get processed, if you could get a negative result.

Did you configure your topic and kslqDB cluster correctly to avoid data loss? Replication factor = 3, min.isr=2, acks=all are the recommended setting.

If you really get into a corrupted state, there is not much you can do about it unfortunately.

**Comment by maksymilian-gasztych** [comment]
Yeah I wonder how it's possible that some records, for this particular table only, get lost. We've been experiencing it for a few months, and we've been dropping and recreating that table when this was happening to somehow mitigate the issue. (Fortunately we can easily detect invalid values automatically)
I think the configuration is all fine, we have 3 ksqldbs with those settings:
```
  KSQL_HEAP_OPTS: "-Xms3G -Xmx5G"
  KSQL_LISTENERS: "http://0.0.0.0:8088"
  KSQL_KSQL_ADVERTISED_LISTENER=http://${KSQL_CONNECT_REST_ADVERTISED_HOST_NAME}:8088
  KSQL_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka-cluster-kafka-bootstrap:9092"
  KSQL_KSQL_SCHEMA_REGISTRY_URL: "http://cp-schema-registry-service:8081"
  KSQL_KSQL_SERVICE_ID: "ksqldb-cluster"
  KSQL_KSQL_INTERNAL_TOPIC_REPLICAS: "3"
  KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
  KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
  KSQL_KSQL_STREAMS_NUM_STREAM_THREADS: "4"
  KSQL_KSQL_STERAMS_CACHE_MAX_BYTES_BUFFERING: "20000000" # 20MB
 #---------------
 # https://docs.confluent.io/platform/current/streams/developer-guide/config-streams.html#recommended-configuration-parameters-for-resiliency
  KSQL_KSQL_STREAMS_PRODUCER_ACKS: "all"
  KSQL_KSQL_STREAMS_REPLICATION_FACTOR: "3"
  KSQL_KSQL_STREAMS_TOPIC_MIN_INSYNC_REPLICAS: "2"
  # This allows KSQL to pause processing if the underlying Kafka cluster is unavailable.
  KSQL_KSQL_STREAMS_PRODUCER_DELIVERY_TIMEOUT_MS: "2147483647"
  KSQL_KSQL_STREAMS_PRODUCER_MAX_BLOCK_MS: "9223372036854775807"
 #----------------
  # Configuration to embed Kafka Connect support.
  KSQL_CONNECT_GROUP_ID: "ksql-connect-cluster"
  KSQL_CONNECT_BOOTSTRAP_SERVERS: "kafka-cluster-kafka-bootstrap:9092"
  KSQL_CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
  KSQL_CONNECT_VALUE_CONVERTER: "io.confluent.connect.avro.AvroConverter"
  KSQL_CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: "http://cp-schema-registry-service:8081"
  KSQL_CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: "http://cp-schema-registry-service:8081"
  KSQL_CONNECT_CONFIG_STORAGE_TOPIC: "ksql-connect-configs"
  KSQL_CONNECT_OFFSET_STORAGE_TOPIC: "ksql-connect-offsets"
  KSQL_CONNECT_STATUS_STORAGE_TOPIC: "ksql-connect-statuses"
  KSQL_CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "3"
  KSQL_CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "3"
  KSQL_CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "3"
  KSQL_CONNECT_REST_ADVERTISED_HOST_NAME: ${status.podIP}
```

**Comment by maksymilian-gasztych** [comment]
We haven't had this issue since upgrade to 0.19.0 (no other changes to configuration). I guess I'll keep the ticket open for another 2 weeks and close it if the issue doesn't reoccur.

**Comment by maksymilian-gasztych** [comment]
Ok, seems it doesn't happen anymore.
