### ISSUE TITLE
CREATE STREAM fails when field name is "table"

### ISSUE THREAD

**Issue by chengang2** [confluentinc/ksql#801]
kafka topic content is a json, json field contain ‘’table‘’ field. Turn this topic into stream. Wrong. Tip table is the keyword, how to deal with this。
json like：{"userid":"14","table":"demo_kafka","name":"jack"}

**Comment by apurvam** [comment]
this should be fixed by #716 

Please follow that PR for the fix. Closing this out.

**Comment by chengang2** [comment]
but the result of select is null,not what I want
