### ISSUE TITLE
Migrations fails when using `create connector if not exists`

### ISSUE THREAD

**Issue by colebaileygit** [confluentinc/ksql#8014]
**Describe the bug**
KSQL Migration with `CREATE CONNECTOR IF NOT EXISTS` fails if the connector already exists.

**To Reproduce**
1. Apply migration file containing `CREATE CONNECTOR IF NOT EXISTS` statement
2. Reset migration metadata: `ksql-migrations destroy-metadata`
3. Apply migration file again

**Expected behavior**
Migration should apply with no error

**Actual behaviour**
Migration fails:
```
"errorMessage":"{\"error_code\":409,\"message\":\"Connector SQS_SOURCE_DELIVERY_ENQUEUED already exists\"}","warnings":[]}
```

**Comment by colebaileygit** [comment]
After attempting a workaround, I can confirm that unfortunately the same problem happens when running a `DROP CONNECTOR IF EXISTS` statement. This makes using ksql-migrations project untenable for managing connectors unfortunately.

**Comment by jzaralim** [comment]
Caused by the Java client not having an "if not exist" option in the `createConnector` function and the migration tool blindly sending the commands regardless. Added the needs-triage label back so the team can discuss.
