### ISSUE TITLE
Missing KEY_FORMAT parameter

### ISSUE THREAD

**Issue by maver1ck** [confluentinc/ksql#805]
Hi,
I'm using KSQL for querying data where both key and value are serialized with Avro.
How can I specify the format for KEY ?

**Comment by apurvam** [comment]
KSQL only accepts avro values. The keys themselves are always interpreted as strings. Do you have a use case for accessing fields within an avro encoded key?

**Comment by maver1ck** [comment]
No. I wanted to group by key. And don't know how. (whole key so it can by string)

**Comment by apurvam** [comment]
Have you seen our documentation on https://github.com/confluentinc/ksql? It has plenty of examples for grouping by key.

**Comment by rmoff** [comment]
@maver1ck whilst there's no support for Avro keys currently, you can use KSQL to re-key a topic (`PARTITION BY`). The resulting topic will have String keys and can then be correctly used for joining, grouping, etc. This blog posts demonstrates this feature in action: https://www.confluent.io/blog/ksql-in-action-real-time-streaming-etl-from-oracle-transactional-data
