### ISSUE TITLE
UDF EXTRACTJSONFIELD does not work in combination of TRANSFORM

### ISSUE THREAD

**Issue by stefanfrehse** [confluentinc/ksql#8122]
**Describe the bug**
Using the UDF `EXTRACTJSONFIELD` does not correctly parse JSON within a `TRANSFORM` lambda call while taking the path variable from the `TRANSFORM` argument. 

**To Reproduce**
Steps to reproduce the behavior, include:

* ksqlDb: 0.20.0 probably earlier as well
* Apply the following statements demonstrates the faulty behavior:
```sql
set 'auto.offset.reset'='earliest';
CREATE STREAM STREAM_A  (
    "key" VARCHAR KEY,
    "value" VARCHAR,
    "extractor" ARRAY<VARCHAR>
) WITH(KAFKA_TOPIC = 'test-topic-transform', VALUE_FORMAT = 'JSON', PARTITIONS = 1, REPLICAS = 3);

INSERT INTO STREAM_A ("key", "value", "extractor") VALUES( 'key_1', '{\"sensor_1\": 10, \"sensor_2\": 15}', ARRAY['.sensor_1', '.sensor_2']);
INSERT INTO STREAM_A ("key", "value", "extractor") VALUES( 'key_2', '{\"sensor_1\": 3, \"sensor_2\": 11}', ARRAY['.sensor_1', '.sensor_2']);

SELECT
    "key",
    "value",
    "extractor",
    TRANSFORM("extractor", (data) => EXTRACTJSONFIELD("value", ('$' + data))) AS "unpackedValue"
    FROM STREAM_A
EMIT CHANGES;
```
which results currently in `[10,10]`, and, `[3,3]`

**Expected behavior**
The result of the query should be: `[10,15]`, and, `[3,11]`.

**Comment by spena** [comment]
Issue fixed here - https://github.com/confluentinc/ksql/pull/8123
