### ISSUE TITLE
Unable to join two tables

### ISSUE THREAD

**Issue by priyanshuHasija** [confluentinc/ksql#8127]
I am trying to join 3 tables but getting an error:
table-table joins require to join on the primary key of the right input table. However, I am joining on the primary key.

Name                 : TOKENA
 Field    | Type
-------------------------------------------
 ADDRESS  | VARCHAR(STRING)  (primary key)
 DECIMALS | INTEGER
 SYMBOL   | VARCHAR(STRING)
-------------------------------------------

JOIN CONDITION:

FROM TOKENSWAPS_PANGOLIN S
LEFT OUTER JOIN BLOCKS B ON ((S.BLOCKHASH = B.HASH))
LEFT OUTER JOIN TOKENA TBASE ON ((S.TOKENORIGIN = LOWER(TBASE.ADDRESS)))

Right input table is TOKENA and ADDRESS is the primary key, still facing the issue

**Comment by mjsax** [comment]
Well, you are using `LOWER(TBASE.ADDRESS)` so you don't joins on the (plain) primary key, but you modify it by applying `LOWER` function. So the join is not on the primary key, but on some derived value. It does not matter that you derive the join-attribute from the primary key. To "join on the primary key" mean to join on the unmodified primary key.
