### ISSUE TITLE
Multiple Tables based on same stream property with different LIKE operatator in where-clause become non-queryable

### ISSUE THREAD

**Issue by lkaupp** [confluentinc/ksql#8139]
**Describe the bug**
I suspect the LIKE operator in the where condition for the bug. First of all, I have a sensor stream with multiple sensor readings in a Kafka topic. Next, I derive a second stream and create a hierarchy string based on the properties of the first stream. Now, the sensor readings have a hierarchy string as a property. Each String is in the format "hierarchy.level{n}.sublevels{n}.subsublevels{n}.[...]". So the hierarchy describes the path of the connection and is part of the reasoning. Now if I create a windowed table and use a where-clause with a like operator for a leaf of the hierarchy e.g. LIKE 'hierarchy.level0.sublevels0%' everything works like expected. But, if I create more tables e.g. on an upper level of the hierarchy (same stream property) 'hierarchy.level0%' either the first or the last table becomes non-queryable. But not always, sometimes, after a competing query is defined e.g. 'hiearchy.level0.sublevels1%' or other higher-level tables with filters e.g. 'hierarchy.level1%' are set or after the containers are restarted.

**To Reproduce**
Steps to reproduce the behavior, include:
1. Create an event stream on a kafka topic based on AVRO key / value schema with a hierarchy property string.
2. Sample source data (e.g.):

```
datetime, hierarchystr, value1, value2
2021-09-16 10:21:21.654, "hierarchy.level0.sublevel0",1,6
2021-09-16 10:21:22.654, "hierarchy.level1.sublevel0",2,5
2021-09-16 10:21:23.654, "hierarchy.level0.sublevel1",3,4
2021-09-16 10:21:23.654, "hierarchy.level0.sublevel0",4,3
2021-09-16 10:21:24.654, "hierarchy.level1.sublevel0",5,2
2021-09-16 10:21:25.654, "hierarchy.level0.sublevel1",6,1
```

3. Any SQL statements you ran:

```
1. CREATE STREAM IF NOT EXISTS sensors_stream WITH (KAFKA_TOPIC='sensors', KEY_FORMAT='AVRO', timestamp='datetime',  timestamp_format = 'yyyy-MM-dd HH:mm:ss.SSS', VALUE_FORMAT='AVRO')
2. CREATE STREAM IF NOT EXISTS sensors_hiearchy_stream AS SELECT *, source + cast(sensorgroup as string) AS hierarchystr FROM sensors_stream
3. CREATE TABLE IF NOT EXISTS sensors_leaf AS SELECT datetime, hierarchystr, collect_list(value0), collect_list(value1) FROM sensors_hiearchy_stream WINDOW TUMBLING (SIZE 1 SECONDS) WHERE hierarchystr LIKE '%hierarchy.level0.sublevels0%' GROUP BY datetime, hierarchystr
4. CREATE TABLE IF NOT EXISTS sensors_leaf2 AS SELECT datetime, hierarchystr, collect_list(value0), collect_list(value1) FROM sensors_hiearchy_stream WINDOW TUMBLING (SIZE 1 SECONDS) WHERE hierarchystr LIKE '%hierarchy.level0.sublevels1%' GROUP BY datetime, hierarchystr
5. CREATE TABLE IF NOT EXISTS sensors_higherlevel AS SELECT datetime, hierarchystr, collect_list(value0), collect_list(value1) FROM sensors_hiearchy_stream WINDOW TUMBLING (SIZE 1 SECONDS) WHERE hierarchystr LIKE '%hierarchy.level0%' GROUP BY datetime, hierarchystr
6. CREATE TABLE IF NOT EXISTS sensors_higherlevel2 AS SELECT datetime, hierarchystr, collect_list(value0), collect_list(value1) FROM sensors_hiearchy_stream WINDOW TUMBLING (SIZE 1 SECONDS) WHERE hierarchystr LIKE '%hierarchy.level1%' GROUP BY datetime, hierarchystr
```

**Expected behavior**
Each filter fetches the events of the downstream hierarchy. The tables based on the filter of the higher level will catch more events than the downstream separate tables. Each table has the events of the same hierarchy level as well as the events of its subsequent hierarchy levels.

**Actual behaviour**
One or more tables either sensors_higherlevel or sensors_leaf become non-queryable after a while or after restart of the containers.

**Comment by lihaosky** [comment]
Hi @lkaupp, thanks for reporting. Can you share how topic `sensors` is created in _schema registry_?

**Comment by spena** [comment]
@agavra I moved this to the query engine as it fits there.

**Comment by lkaupp** [comment]
So basically, I learned that ksqlDB is not meant to be used with big data and a lot of tables. Speaking of numbers, my hierarchy that is generated is about 40k tables with corresponding queues, that have all different triggers to proceed and do some ETL. In the end, the basic idea behind ksqlDB is wonderful, but in practices, it means that a 32 core / 64 GB RAM rack cannot handle a small amount of event data ~200 MB if it is fed to ksqlDB, because of all the event splits. Even the setup time takes hours to create all the queues and tables. We end up going back to a simple db and doing the processing on our own, which does the same but on a fraction of the hardware requirements, and it's even faster. So, idk what ksqlDB is made for, but not for high frequency mass of sensor data. Maybe for just small scale operations / business operations, but definitely not for production.
