### ISSUE TITLE
Properties file entries for maximum resiliency

### ISSUE THREAD

**Issue by blueedgenick** [confluentinc/ksql#817]
Recent enhancements to Kafka Streams API e.g [KIP-224](https://cwiki.apache.org/confluence/display/KAFKA/KIP-224%3A+Add+configuration+parameter+%60retries%60+to+Streams+API) have made it easier to configure a Streams application for maximum resiliency in the face of broker unavailability, such as that encountered during a rolling restart for example.

It seems desirable to collect all such best-practice settings and include them as defaults in the OOTB settings, or at the very least prominently document them.

For those users who prefer a 'fail-fast' approach, we can supply documentation of how to adjust the defaults to achieve this.

**Comment by rmoff** [comment]
@blueedgenick does https://docs.confluent.io/current/ksql/docs/installation/server-config/config-reference.html#recommended-ksql-production-settings satisfy this issue?

**Comment by blueedgenick** [comment]
Not really - the original request was to make it resilient OOTB, which it clearly isn't. I don't think hiding this away in the docs is necessarily the best solution we can provide....  
Even if we don't want to make it resilient OOTB, we could easily provide a second properties file example in the distribution which _did_ have those settings in it.

**Comment by rmoff** [comment]
Gotcha - I mis-read the initial issue. 
Do we have a list of these defaults that we'd want to set?
