### ISSUE TITLE
Streams configurations specified in the ksqlserver.properties files are not propagated to the streams application

### ISSUE THREAD

**Issue by apurvam** [confluentinc/ksql#818]
See #815 

It seems that the streams properties like `replication.factor`, etc. specified in the `ksql.properties` file do not get passed on to the streams config. Hence the streams application uses the default values (like `replication.factor = 1` for internal topics), causing errors when the environment requires a different minimum value for this setting.

When the underlying kafka cluster requires certain configuration values for streams properties, we would want to be able to specify it in the KSQL server config and not explicitly for each query. We need figure out why the configs are not passed from the ksql server properties to the streams app and then fix it.

**Comment by rodesai** [comment]
It works, you just have to prefix the settings with `ksql.core.streams`. That doesn't seem to be documented anywhere though.

**Comment by apurvam** [comment]
Interesting. I haven’t verified, but if what you say is true, this could be just a documentation change.

**Comment by miguno** [comment]
cc @joel-hamill

**Comment by miguno** [comment]
cc @ybyzek

**Comment by joel-hamill** [comment]
@apurvam @rodesai would [this behavior](https://github.com/confluentinc/ksql/issues/818#issuecomment-370103513) be assumed by a user, or would they assume the get passed on to the streams config automatically?

**Comment by rodesai** [comment]
Are you asking whether a user should use the prefix or not?

**Comment by joel-hamill** [comment]
@rodesai nope, i'm specifically asking whether users would expect to have to use a prefix for their configurations. i.e. is this normal programatic behavior? i.e. are we papering over something that could be fixed in the code?

**Comment by apurvam** [comment]
Not sure I understand your question @joel-hamill . All the configs work without a prefix now. The prefixes are good hygiene to make the config files more readable and also to avoid config name clashes between different sub components.

There is nothing here that needs to be fixed in the code.
