### ISSUE TITLE
Replacing a source with CREATE OR REPLACE TABLE yields unexpected results

### ISSUE THREAD

**Issue by Sullivan-Patrick** [confluentinc/ksql#8197]
**Describe the bug**
If you replace a source table generated with a `CREATE SOURCE TABLE` statement with a `CREATE OR REPLACE` statement, it leads to a table that you can use with both pull queries (as you might expect from a source table) and  `INSERT VALUES` (which should be disallowed from pull queries).

Title is intentionally vague as I don't have a lot of context regarding expected behavior of source tables with CREATE OR REPLACE, and I suspect there may be other bugs or inconsistencies surrounding this.

**To Reproduce**
On master (SHA eb398997cd25750208896ec47115a2356aeb27f7), issue the following queries:

```
CREATE SOURCE TABLE tbl (k INT PRIMARY KEY, v INT) WITH (kafka_topic='tbl', value_format='json', partitions=1);
CREATE OR REPLACE TABLE tbl (k INT (k INT PRIMARY KEY, v INT) WITH (kafka_topic='tbl', value_format='json', partitions=1);
INSERT INTO tbl (k, v) VALUES (1, 2);
SELECT * FROM tbl;
```

**Expected behavior**
The table is still a source table, with `INSERT VALUES` disallowed.

**Actual behaviour**
The table allows for contradicting behaviors as described above.

**Comment by spena** [comment]
Closing this ticket as it is resolved in https://github.com/confluentinc/ksql/pull/8199. Source tables should not be writable.

**Comment by Sullivan-Patrick** [comment]
@spena Thanks!
