### ISSUE TITLE
Support TIMESTAMP types in the WITH(..., TIMESTAMP='<tsColumn>`) property

### ISSUE THREAD

**Issue by spena** [confluentinc/ksql#8235]
**Is your feature request related to a problem? Please describe.**
The `WITH` clause has a property to specify the timestamp column of a stream which only supports `BIGINT` and `STRING`. When working with Debezium to export DBs to Kafka using Connect types, the new columns are parsed as `TIMESTAMP`, but it is impossible to specify the timestamp column from the `WITH` clause.

The following message appears when attempting to use a TIMESTAMP type as a WITH/TIMESTAMP property:
```
ksql> CREATE OR REPLACE TABLE cursus WITH (KAFKA_TOPIC = 'intra.public.cursus', FORMAT = 'AVRO', TIMESTAMP = 'updated_at');
Timestamp column, `UPDATED_AT`, should be LONG(INT64) or a String with a timestamp_format specified
```

**Describe the solution you'd like**
The `WITH/TIMESTAMP` property should work with `TIMESTAMP` column types because internally they are represented as long values.

**Comment by sajjadnazrulla** [comment]
Hi. I am looking to start contributing to ksql and I would like to work on this. Can this be assigned to me ?

**Comment by spena** [comment]
Hi @sajjadnazrulla, thanks for looking to help on ksql work. I appreciate that. However, there's another person already working on this that we forgot to assign. Do you have a preference on these types of issues with data types? are you willing to work on other good first issues?

There is one that was just recently opened that I think is important too - https://github.com/confluentinc/ksql/issues/8250. Or if you want specific areas, I can help find finding some.

**Comment by sajjadnazrulla** [comment]
Thanks for the update @spena . I can look into the issue mentioned.

**Comment by Gerrrr** [comment]
I am new to ksql, and it took me a bit to reproduce the described case, therefore, I am going to document it here. The following steps are not too consistent as I used a local IP and linked containers interchangeably, but they get the job done.

OS: OS X 11.6
Docker: Docker Desktop 4.1.1 (69879)
These steps are a combination of https://debezium.io/documentation/reference/tutorial.html and https://debezium.io/documentation/reference/1.7/configuration/avro.html with a corrected port mapping in the latter.

1. Start Zookeeper:

```bash
$ docker run -it --rm --name zookeeper -p 2181:2181 -p 2888:2888 -p 3888:3888 debezium/zookeeper:1.7
```

2. Start Kafka

```bash
$ docker run -it --rm --name kafka -p 9092:9092 --link zookeeper:zookeeper -e ADVERTISED_HOST_NAME=<IP> debezium/kafka:1.7
```

3. Start MySQL

```bash
$ docker run --cap-add=sys_nice -it --rm --name mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=debezium -e MYSQL_USER=mysqluser -e MYSQL_PASSWORD=mysqlpw debezium/example-mysql:1.7
```

4. Start Schema Registry

```bash
docker run -it --rm --name schema-registry \
    --link zookeeper \
    --link kafka \
    -e SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zookeeper:2181 \
    -e SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=kafka:9092 \
    -e SCHEMA_REGISTRY_HOST_NAME=<IP> \
    -p 8081:8081 confluentinc/cp-schema-registry
```

5. Start Connect

```bash
docker run -it --rm --name connect \
    --link zookeeper:zookeeper \
    --link kafka:kafka \
    --link mysql:mysql \
    --link schema-registry:schema-registry \
    -e GROUP_ID=1 \
    -e CONFIG_STORAGE_TOPIC=my_connect_configs \
    -e OFFSET_STORAGE_TOPIC=my_connect_offsets \
    -e KEY_CONVERTER=io.confluent.connect.avro.AvroConverter \
    -e VALUE_CONVERTER=io.confluent.connect.avro.AvroConverter \
    -e CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL=http://<IP>:8081 \
    -e CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL=http://<IP>:8081 \
    -p 8083:8083 debezium/connect:1.7
```

6. Create Debezium connector for MySQL

```bash
$ curl -i -X POST -H "Accept:application/json" -H "Content-Type:application/json" localhost:8083/connectors/ -d '{"config": {"database.port": "3306", "database.server.name": "dbserver1", "database.history.kafka.topic": "schema-changes.inventory", "key.converter.schema.registry.url": "http://<IP>:8081", "key.converter": "io.confluent.connect.avro.AvroConverter", "tasks.max": "1", "database.server.id": "184054", "value.converter": "io.confluent.connect.avro.AvroConverter", "connector.class": "io.debezium.connector.mysql.MySqlConnector", "value.converter.schema.registry.url": "http://<IP>:8081", "database.history.kafka.bootstrap.servers": "kafka:9092", "database.include.list": "inventory", "database.hostname": "mysql", "database.user": "debezium", "database.password": "dbz"}, "name": "inventory-connector"}'
```

7. Change config of the local clone of ksqlDB

__Note__: I am using the local clone rather than a dockerized version to iterate quicker during development.

`ksql/config/ksql-server.properties`:

```
bootstrap.servers=<IP>:9092
ksql.schema.registry.url=http://<IP>:8081
```

8. Start ksqlDB

In ksql folder:

```bash
$ bin/ksql-server-start ./config/ksql-server.properties
```

9. Start ksql client

```bash
$ bin/ksql
```

10. Run command that should work after this issue is merged

```sql
ksql> CREATE OR REPLACE TABLE inventory (version varchar primary key, name varchar, ts_ms timestamp) WITH (KAFKA_TOPIC = 'dbserver1', FORMAT = 'AVRO', TIMESTAMP ='ts_ms');
Timestamp column, `TS_MS`, should be LONG(INT64) or a String with a timestamp_format specified
```
