### ISSUE TITLE
Unable to verify if the value schema for topic TOPIC_NAME is compatible with ksqlDB.

### ISSUE THREAD

**Issue by darroyod** [confluentinc/ksql#8241]
**Describe the bug**
I have a topic with a JSON schema succesfully loaded. I've confirmed that events are arriving under normal conditions and that the kafka server is running smoothly.
When I launch a command for create a stream or a table via KSQL, I'm getting an error that says:

```
Unable to verify if the value schema for topic twin is compatible with ksqlDB.
Reason: Unsupported schema type org.everit.json.schema.FalseSchema

Please see https://github.com/confluentinc/ksql/issues/ to see if this particular reason is already known.
If not, please log a new issue, including this full error message.
Schema:{"$schema":"http://json-schema.org/draft-07/schema","additionalProperties":false,"name":"twin-value","properties":{"........ TEXT_INTENTIONALLY_CUT
```

**To Reproduce**
- Version of KSQL: CLI v6.2.1, Server v6.2.1
- SQL statements you ran: create stream streamTwin WITH (kafka_topic = 'twin', value_format = 'JSON_SR');

**Expected behavior**
A stream or table should be created with the structure populated from the JSON schema stored in the schema registry.

**Actual behaviour**
A clear and concise description of what actually happens, including:
```
ksql> create stream streamTwin WITH (kafka_topic = 'twin', value_format = 'JSON_SR');
Unable to verify if the value schema for topic twin is compatible with ksqlDB.
Reason: Unsupported schema type org.everit.json.schema.FalseSchema

Please see https://github.com/confluentinc/ksql/issues/ to see if this particular reason is already known.
If not, please log a new issue, including this full error message.
Schema:{"$schema":"http://json-schema.org/draft-07/schema","additionalProperties":false,"name":"twin-value","properties":{"........ TEXT_INTENTIONALLY_CUT
```

**Comment by vcrfxia** [comment]
Hi @darroyod , do you have an example schema that reproduces the bug? It's hard to tell from the error message alone what's happening. Thanks.

**Comment by darroyod** [comment]
The JSON data contained an errata and it was not a valid JSON document. This was the reason for the error.
