### ISSUE TITLE
ksqlDB not clearing state store data from disk

### ISSUE THREAD

**Issue by anupsdtiwari** [confluentinc/ksql#8288]
Hi Team ,

I have noted that even after executing "drop table <tableName> delete topic ;" command, ksqlDB(0.17 - Confluent 6.2.0 community version) is NOT clearing data from the local disk of all nodes which it uses for storing state data.
However, the table is dropped from meta store and the topic is deleted from kafka.

PS : Owner of directory is the user using which ksqlDB process is running.

**Comment by suhas-satish** [comment]
@anupsdtiwari , this issue has been fixed in https://github.com/confluentinc/ksql/pull/7729 released with ksqlDB(ksqlDB(0.21 version). Can you pls try again with this release version or higher?
