### ISSUE TITLE
how to create stream if the json field is not fixed

### ISSUE THREAD

**Issue by chengang2** [confluentinc/ksql#829]
json like：{"userid":"14","tablename":"demo_kafka","name":"jack"}
json like：{"userid":"14","age":"18","name":"jack"}

in the fact I do not know the specific fields in json

**Comment by big-andy-coates** [comment]
How would you write SQL against a table if you didn't know the columns? :D

You only need to know the set of fields that you want to act on.  So, using your example above, if you only wanted to count events by `userid`, it would be sufficient to create a stream as:

`CREATE STREAM user_events (userid bigint) WITH (kafka_topic='someTopic', value_format='JSON');`

If there are other fields you also need to use, just add them to the definition. They don't need to be in all message you receive. If a message is received that does not have a particular field, then its value will be null.

If you know the full set of possible fields then you can add them all. However, if you don't, you can just add the fields you know and care about. Of course, the other fields would not be accessible within your SQL statements or in the output messages.

**Comment by chengang2** [comment]
@big-andy-coates thanks, I hope automatically create stream fields based on json.

**Comment by apurvam** [comment]
great, please reopen if you have questions.
