### ISSUE TITLE
ksqlDB API Client does not handle return values of `"@type":"warning_entity"`

### ISSUE THREAD

**Issue by rspurgeon** [confluentinc/ksql#8318]
**Describe the bug**
Against cloud ksqlDB as of 11/2/2021 version `0.21.0`, 4 CSUs (lksqlc-r8vgk)

When executing a statement like the following in the ksqlDB Java SDK, `ksqlClient.executeStatement` function:
```
CREATE STREAM IF NOT EXISTS high_value_stock_trades
```

I get a response w/ a `@type=warning_entity` and the response code is `200` (full response here):
```
{"@type":"warning_entity","statementText":"CREATE STREAM IF NOT EXISTS high_value_stock_trades\n    WITH (KAFKA_TOPIC='high_value_stock_trades') AS\nSELECT U.ID USERID,\n    U.REGIONID REGION,\n    T.SIDE SIDE,\n    T.QUANTITY QUANTITY,\n    T.SYMBOL SYMBOL,\n    T.PRICE PRICE,\n    T.ACCOUNT ACCOUNT\nFROM STOCKTRADES T\nINNER JOIN USERS U ON (T.USERID = U.ID)\nWHERE ((T.PRICE > 500) AND (T.QUANTITY > 2500))\nEMIT CHANGES;","message":"Cannot add stream `HIGH_VALUE_STOCK_TRADES`: A stream with the same name already exists.","warnings":[]}
```

The code runs through a function called `handleUnexpectedEntity` where no case is covered to handle this type of response and an exception is thrown.

**To Reproduce**
Steps to reproduce the behavior, include:
*. The version of KSQL = 0.21.0
*. Any SQL execution statement that includes an IF NOT EXISTS, when the persistent query already exists

**Expected behavior**
The Java SDK should not throw an exception, but return an `ExecuteStatementResult` with the results (including the warning) of the statement

**Actual behaviour**
The Java SDK is throwing an `IllegalStateException` on this return value.

**Comment by wcarlson5** [comment]
I have a PR for just fixing the the `IF NOT EXISTS` case but we should consider how we should handle warning entity types to avoid this for any future breakage.
