### ISSUE TITLE
STDDEV_SAMP actually computes variance

### ISSUE THREAD

**Issue by colebaileygit** [confluentinc/ksql#8345]
**Describe the bug**
STDDEV_SAMP implementation is incorrect. Results are valid variances, but stddev should be the square root of that. Suggest to rename or add both functions to prevent confusion.

**To Reproduce**
Run test cases here: https://github.com/confluentinc/ksql/blob/dd36ca7728103f9fad6fd83d797f70b52ffc5bd0/ksqldb-functional-tests/src/test/resources/query-validation-tests/standarddeviation.json

And compare with any standard deviation calculator. For instance the set [0, 10] should result in variance of 50 and stddev of 7.07. Test case uses the value 50.

**Expected behavior**
Standard deviation should be the square root of variance.

**Actual behaviour**
Variance is returned by stddev_samp function.

**Comment by jnh5y** [comment]
I opened https://github.com/confluentinc/ksql/issues/8725 without realizing this ticket is here.
