### ISSUE TITLE
Implement LAST_N aggregate function

### ISSUE THREAD

**Issue by agavra** [confluentinc/ksql#8348]
Similar to `LATSET_BY_OFFSET` and `COLLECT_LIST` users may want to have a "bounded" `COLLECT_LIST` function that only collects the latest `N` elements instead of the (default) behavior of collecting the first `N` elements.

**Comment by suhas-satish** [comment]
@agavra , any reason you request this?

**Comment by agavra** [comment]
@suhas-satish this came from a conversation with the field, I don't remember the exact use case that triggered it. It's not high priority.

**Comment by jnh5y** [comment]
@agavra does the fact that latest_by_offset takes a size cover this?

**Comment by agavra** [comment]
yes I believe that would cover the use case
