### ISSUE TITLE
Remove the need for secondary '_TS' queries in the click stream demo.

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#835]
Doubling up all queries, just to expose a timestamp field to elastic search, isn't a good pattern to have out there, and it's already being replicated by other blogs.

Instead, it's possible to use a `InsertField` transformation on the Kafka Connect config to grab the `timestamp.field` from the Kafka record and expose it to Elasticsearch. 

Docs: https://kafka.apache.org/documentation/#connect_transforms, (search for `InsertField`).

**Comment by blueedgenick** [comment]
big +1 for this - it definitely complicates things for the learner who wants to dig in and figure out the patterns from this

**Comment by big-andy-coates** [comment]
I've a fix for this now. Just need to work out if we want this in 4.1.x or master.

**Comment by big-andy-coates** [comment]
Fixed on 4.1.x
