### ISSUE TITLE
More intuitive default timestamp info in DESCRIBE EXTENDED output

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#837]
Currently `DESCRIBE EXTENDED` on a CT or CS without any TIMESTAMP set shows `Timestamp field: Not set - using <ROWTIME>`.  

This is a bit confusing, time based operations alway use `ROWTIME`, and that the use of the `TIMESTAMP` option controls what `ROWTIME` is populated with, defaulting to the source message's timestamp. 

Would it not make more sense the to list this as `Not set - using metadata timestamp` or `using default message timestamp`??

**Comment by miguno** [comment]
Yeah, let's chat whether we can make this information more intuitive if we believe it is not.

But I have a counterpoint to:

> Would it not make more sense the to list this as Not set - using metadata timestamp or using default message timestamp?

`ROWTIME` is something that a KSQL user will see a lot when using KSQL interactively.  Whereas "metadata timestamp" or "message timestamp" is lower-level Kafka detail.  I am typically reluctant to give a "Kafka (or KStreams) answer" to a "KSQL question" if there is a better "KSQL answer".

**Comment by big-andy-coates** [comment]
Well, I think we can either code with:
1. "Not set" - which has no Kafka terminology, but doesn't explain what is being used.
1. "Not set - using record timestamp" - which explains what is being used, but has Kafka terminology.

Personally, I'd go with the second one. Other parts of the `describe` output include Kafka terminology e.g. the "topic" second talks about partitions and replication.

**Comment by miguno** [comment]
What about:

> "Not set - using record timestamp (ROWTIME column)"

**Comment by big-andy-coates** [comment]
As I understand it, 

For CTAS/CSAS the `WITH(TIMESTAMP=x)` clause controls which field within the schema downstream queries will use as ROWTIME, with the default being the ROWTIME from the source stream. (Note: The value of ROWTIME of the source stream may or may not be the record timestamp in Kafka, depending on whether the source stream was also constructed with a `WITH(TIMESTAMP=x)` clause or not). So, the existing "Not set - using <ROWTIME> column" would seem to be correct, though maybe "Not set - using source stream's <ROWTIME> column" might be more correct / informative?

For CT/CS the `WITH(TIMESTAMP=x)` clause again controls which field within the schema downstream queries will use as ROWTIME, but this time the default is the record timestamp in Kafka. There is no source stream to pick up a ROWTIME column from. So the current "Not set - using <ROWTIME> column" would seem to be misleading / confusing. Maybe something like "Not set - using record timestamp for ROWTIME column" would be more correct / informative?

@hjafarpour @rodesai @apurvam Both @miguno and I would appreciate your input on the terminology here and checking that my understanding is correct.

**Comment by hjafarpour** [comment]
I like `Not set - using record timestamp for ROWTIME column`. It's more accurate. I agree with @miguno 's concern about bringing lower level concepts to KSQL but in this case I think this is a minor issue and the above description provides enough info to not be confusing.
On the other hand, key field is different. `WITH ( key=x)` only indicates that the key in kafka message has the same value as the given column and it's user's responsibility to provide accurate information. We can use similar expression to describe key field if it's not set: `Not set - using record key for ROWKEY column`.

**Comment by rodesai** [comment]
Something like `Not set - using record timestamp for ROWTIME column` makes more sense to me. Though if I were picking nits I would call it a message timestamp instead since the value is coming from the kafka message. ROWTIME is the timestamp of the record, so using record timestamp there is kind of circular.

I don't think saying `Not set - using record key for ROWKEY column` makes sense. That implies that if it is set then we don't use the record key for the ROWKEY column, which is not true.

**Comment by rodesai** [comment]
Actually never mind on the message/record thing. That's just a notion I had in my own head for some reason. Kafka uses the term record in its api.

**Comment by apurvam** [comment]
+1 to `Not set - Using record timestamp for ROWTIME column` for `CT` and `CS` statements. 

For `CTAS`, `CSAS` statements, we can have `Not set - Using source streams' ROWTIME column`.

**Comment by miguno** [comment]
> Not set - using record timestamp for ROWTIME column

As said offline already yesterday, I'm +1.
