### ISSUE TITLE
incorrect data type descriptions for struct and map

### ISSUE THREAD

**Issue by blueedgenick** [confluentinc/ksql#8374]
In the table at https://docs.ksqldb.io/en/latest/reference/sql/data-types/#compound-types the descriptive text for the `struct` and `map` entries is incorrect, possibly transposed ? If transposed, suggest updating the `struct` one to be more clear - a struct isn't really "a kind of map", more of a sub-schema or collection of named and typed fields.

**Comment by agavra** [comment]
@blueedgenick - I just went ahead and removed the description in that table since below there's a more detailed description for those who aren't clear on it :)
