### ISSUE TITLE
Switch 'output topic' for 'input topic' for DESCRIBE EXTENDED output for CT and CS.

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#838]
`DESCRIBE EXTENDED` on CT or CS shows `Kafka output topic: blah”, but this is a source topic, right? Not a topic KSQL is outputting to. Would not “Kafka input topic” be more correct/intuitive?

**Comment by big-andy-coates** [comment]
Yes. 

Looking at the code, it looks like the context needed to differentiate between CT/CS and CTAS/CSAS has been lost. So I think the most simple code change would just be to change "Kafka output topic" to "Kafka topic", which suits both cases.

**Comment by miguno** [comment]
I'd vote for differentiating between input and output topics in DESCRIBE EXTENDED.  I'm sure users would be asking themselves whether "topic" would mean input or output. ;-)
