### ISSUE TITLE
stream to table join emit changes when table updates

### ISSUE THREAD

**Issue by msillence** [confluentinc/ksql#8386]
Currently stream to table joins only emit changes when the stream changes

We would like changes to be emitted when either the stream or table changes

Alternative aproaches
windowed joins
 - this is not really a possibility as our window would need to be forever we have both fast changing and data that almost never changes in the table, we also have a huge amount of data for some of the topics we need this for
 - writing the queries both ways - stream A join table B and stream B join table A - this gets tedious when we have multiple tables to join

we don't really care about reproducibility or order we only care about eventual consistency - that we eventually get the latest values from both A and B regardless of order of changes.

We have written an app that persists data to postgres and then using joins and where clauses emits new events - we find that we have to be mindful of race conditions to make sure we get the correct end value

**Comment by mjsax** [comment]
> We would like changes to be emitted when either the stream or table changes

Seems to be ill defined? Assume you have already joined 1M stream records with the table. If the table is updated, should _all_ previously emitted result record be updated (note the all 1M stream records _could_ have joined with the same table row)? Also, a STREAM contains immutable events and thus it's not really possible to _update_ previous result (it would only be possible to re-emit, but those would technically be duplicates).

Would be good if you could clarify what you want to achieve.

> we don't really care about reproducibility or order we only care about eventual consistency - that we eventually get the latest values from both A and B regardless of order of changes.

Sounds like a table-table join to me.

**Comment by msillence** [comment]
fundimentally I guess your right a table + table join sounds fine, re-emitting results is also fine

reason I thought we were using streams was joining a primary key to part of a composite key wasn't supported but testing this and it seems to work

one anomoly from changing to table + table joins - we can't modify the key

so the below no longer works when using a table join but does for streams:
```
select struct(newkey:= concat('prefix', s.ROWKEY->key)) as ROWKEY,
... partition by struct(newkey:= concat('prefix', s.ROWKEY->key))
```

I guess we could live with the modifying the key problem and create another topic using a stream transform after the table + table join

**Comment by msillence** [comment]
OK I think it's that there is a problem with table + table joins and one to many relationships or even many to one as the issue suggests we do https://github.com/confluentinc/ksql/issues/4424

in our tests we only get 40 results and expect over 1000

Our query is of the form:
`create table combined_table as SELECT m.*, s.* FROM many m INNER JOIN single s ON struct(id:= m.rowkey->id) = s.rowkey emit changes;`

**Comment by msillence** [comment]
Following up on the lack of results this is as we have a composite key table and to join to a table with a simpley key - just one of the composite pair.

We also use compacting for the topics as there can be a lot of churn and we don't need the history.

To join the tables we need to repartion the composite key table so the partitions align but in ksql the only way to do that is to rekey the topic. When that happens we then no longer have unique keys the other half of the composite key is missing. This means we lose data and the join no longer works.
If we don't repartition the composite key ends up on a different partiton to the simpley key table

I see no way to achieve what we want with ksql

as an example: 

```
create table header_table (rowkey struct<ID string> primary key, ID string, DESCRIPTION string)
  with (KAFKA_TOPIC='detail2', PARTITIONS=3, value_format='JSON', key_format='JSON', REPLICAS=1);

create table detail_table (rowkey struct<ID string, CODE string> primary key, ID string, CODE string) 
  with (KAFKA_TOPIC='header', PARTITIONS=3, value_format='JSON', key_format='JSON', REPLICAS=1);


insert into header (ROWKEY, ID, DESCRIPTION) values(struct(ID:='id1'), 'id1', 'd1');

insert into detail (ROWKEY, ID, CODE) values(struct(ID:='id1', CODE:='c1'), 'id1', 'c1');
insert into detail (ROWKEY, ID, CODE) values(struct(ID:='id1', CODE:='c2'), 'id1', 'c2');

select d.rowkey, d.id, d.code from detail_table d inner join header_table h on struct(id:=d.rowkey->id) = h.rowkey emit changes;
```

in the above the detail_table  is the composite key and when we use partitions the same ID can end up in different partitions to the  header table and the join fails. Rekeying on ID and we no longer have uniqueness and at some point compact will drop one of the CODEs

**Comment by mjsax** [comment]
Since v0.19.0 FK-joins are supported: https://www.confluent.io/blog/ksqldb-0-19-adds-data-modeling-foreign-key-joins/ (You actually linked to the ticket above).

For this case, you don't need to change your left input table containing the composite key: FK-joins don't require that input tables are co-partition, but the runtime will take care of it internally. If you are interested how FK-joins work at the runtime level, check out https://www.confluent.io/blog/data-enrichment-with-kafka-streams-foreign-key-joins/

However, for your case you will need to use v0.21.0 that adds support for expressions in the join condition: https://www.confluent.io/blog/announcing-ksqldb-0-21-new-features-major-upgrades/

Thus, you simple join query
```
select d.rowkey, d.id, d.code from detail_table d inner join header_table h on struct(id:=d.rowkey->id) = h.rowkey emit changes;
```
should actually just work using v0.21.0.

**Comment by mjsax** [comment]
@msillence -- Closing this ticket now. Feel free to re-open if necessary.
