### ISSUE TITLE
Add a key serde field to records in the Command Topic

### ISSUE THREAD

**Issue by rodesai** [confluentinc/ksql#846]
We may want to change the serde that KSQL uses to serialize/deserialize Kafka message keys. For example, to fix https://github.com/confluentinc/ksql/issues/724 we could use a binary key format instead of a String with delimiters. To make this possible in the future we should add metadata to the Command Topic about the serde used for keys by the query that executes the command. KSQL should then use that serde if it knows about it, or not run the command if it does not know about that serde.

**Comment by apurvam** [comment]
This seems to be a dup of #824 . If so can you close it @rodesai ?

**Comment by rodesai** [comment]
Yeah, it should get covered as part of the implementation of that feature.
