### ISSUE TITLE
Support verbose join syntax

### ISSUE THREAD

**Issue by mjsax** [confluentinc/ksql#8478]
**Is your feature request related to a problem? Please describe.**
SQL supports inner/left/right/outer joins including verbose and short syntax. We should consider to support the full verbose syntax, instead of just short syntax.

**Describe the solution you'd like**
We should support
- `a [INNER] JOIN b ON`
- `a LEFT [OUTER] JOIN b ON`
- `a RIGHT [OUTER] JOIN b ON` (we don't support `RIGHT` join at all atm)
- `a FULL [OUTER] JOIN b ON`

**Comment by jnh5y** [comment]
From a discussion with @mjsax, it sounds like the remaining work for this issue is to support RIGHT joins.

**Comment by Gerrrr** [comment]
I double-checked that and @jnh5y is correct - the remaining work from the original description is to support right joins.

@mjsax Can you please elaborate a bit on the scope of supporting right joins? As I can see, Kafka Streams currently supports [KTable-Ktable right join](https://github.com/apache/kafka/blob/trunk/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KTableKTableRightJoin.java). Is this issue only about making that one available via ksql or also extending right join semantics to KStream-KStream?

**Comment by jnh5y** [comment]
@Gerrrr From what I understand, I believe the work is syntactical sugar where right joins are internally switched to be left joins (and then executed).  I hope that helps before Matthias joins the conversation to answer better.:)

**Comment by Gerrrr** [comment]
Makes sense, @jnh5y. Thank you!
