### ISSUE TITLE
ksqlDB should use the JsonSchemaConverter when deserializing JSON_SR records

### ISSUE THREAD

**Issue by rayokota** [confluentinc/ksql#8526]
**Describe the bug**
ksqlDB should use the JsonSchemaConverter when deserializing JSON_SR records

**To Reproduce**

By not using the JsonSchemaConverter, constructs like an array of `anyOf` types are not deserialized properly.

Schema:
```
      {
        "properties": {
          "products": {
            "type": "array",
            "description": "A list of identifiers attached to the product.",
            "items": {
              "$ref": "#/$definitions/products"
            }
          }
        },
        "$definitions": {
          "products": {
            "title": "Product Identifier",
            "type": "object",
            "anyOf": [
              {
                "type": "object",
                "properties": {
                  "keycode": {
                    "type": "string"
                  }
                }
              },
              {
                "type": "object",
                "properties": {
                  "itemCode": {
                    "type": "string"
                  }
                }
              }
            ]
          }
        }
      }
```

Record:
```
{"products": [{"keycode": "secret"}]}
```

Output:
```
{
"PRODUCTS": [
{
"IO.CONFLUENT.CONNECT.JSON.ONEOF.FIELD.0": null
}
]
}
```

**Expected behavior**
Above the output should contain another object rather than `null`.  The JsonSchemaConverter will produce the proper output, but ksqlDB is not using it for JSON_SR records.

**Additional context**
I noticed a comment in `KsqlJsonDeserializer.java` that says

```
      // don't use the JsonSchemaConverter to read this data because
      // we require that the MAPPER enables USE_BIG_DECIMAL_FOR_FLOATS,
      // which is not currently available in the standard converters
```

However, JsonSchemaConverter currently enables `USE_BIG_DECIMAL_FOR_FLOATS`, so perhaps it can be used now.

**Comment by spena** [comment]
@rayokota I tried using the JsonSchemaConverter using the same schema and record you posted, but I get an error with this message: `org.apache.kafka.connect.errors.DataException: Invalid value: null used for required field: "keyCode", schema type: STRING`.

I was also looking at the code and I didn't see the `USE_BIG_DECIMAL_FOR_FLOATS` configured in the json mapper.
https://github.com/confluentinc/schema-registry-json-schema/blob/master/json-schema-serializer/src/main/java/io/confluent/kafka/serializers/json/AbstractKafkaJsonSchemaDeserializer.java#L55

Is the schema correct?

**Comment by rayokota** [comment]
@spena , the schema has `keycode` not `keyCode`. 

 The `USE_BIG_DECIMAL_FOR_FLOATS` is configured here: https://github.com/confluentinc/schema-registry/blob/master/json-schema-provider/src/main/java/io/confluent/kafka/schemaregistry/json/jackson/Jackson.java#L78

**Comment by spena** [comment]
I modified the code to use the `JsonSchemaConverter` and the result when given the `{"products": [{"keycode": "secret"}]}` record is this:
```
{
  "PRODUCTS":[
    { "IO.CONFLUENT.CONNECT.JSON.ONEOF.FIELD.0" : {"KEYCODE":"secret"}},
    { "IO.CONFLUENT.CONNECT.JSON.ONEOF.FIELD.1" : null}
  ]
}
```

I think a user would expect something like this:
```
{
  "PRODUCTS":[
    {"KEYCODE":"secret"}
  ]
}
```

@rayokota told me (offline) that he's working on an improvement to handle enums/unions for all converters, including the JsonSchemaConverter. This improvement will be enabled by a flag. We may want to use this new improvement to get the right result. The improvement will be available either 7.1 or 7.2. I'll put this ticket on hold when this flag is available.

**Comment by spena** [comment]
@rayokota is the improvement in SR to handle enums/unions ready?

**Comment by rayokota** [comment]
@spena , yes the improvement is now in `master`.  You can use the `JsonSchemaConverter` and then set the flag `generalized.sum.type.support=true`.  This will provide more consistent handling of enums and unions.

**Comment by spena** [comment]
This is fixed by the https://github.com/confluentinc/ksql/pull/9130 PR.
