### ISSUE TITLE
Several functions don't do null checks on inputs

### ISSUE THREAD

**Issue by jzaralim** [confluentinc/ksql#8545]
**Describe the bug**
There are a few functions (`AS_MAP`, `ARRAY_SORT` and `URL_ENCODE_PARAM` for example) that don't do null checks on inputs. We should do null checks because these errors are left uncaught and end up crashing queries. An example of one that has been fixed recently is https://github.com/confluentinc/ksql/pull/8400

**Comment by jzaralim** [comment]
#8364 is a general fix for this

**Comment by jnh5y** [comment]
@jzaralim `ARRAY_SORT` seems to have a null check.  (I'm looking for others and have confirmed the other two are problematic.). I just wanted to check that I'm not missing something with ARRAY_SORT.

**Comment by jzaralim** [comment]
@jnh5y https://github.com/confluentinc/ksql/blob/6b65cd4da78e38832b6a9ec232595c3a8b8d1443/ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/array/ArraySort.java#L51

The direction parameter doesn't have a null check. If it's null then `direction.toUpperCase()` will throw an NPE.

**Comment by jnh5y** [comment]
I believe https://github.com/confluentinc/ksql/pull/8726 closes this issue at the minute.  Feel free to reopen if I've missed anything!
