### ISSUE TITLE
SELECT Query not returning a valid JSON

### ISSUE THREAD

**Issue by LapoElisacci** [confluentinc/ksql#8554]
**Describe the bug**
Following the official quickstart tutorial [here](https://ksqldb.io/quickstart.html), after populating the stream with events if you run the following query:

```SQL
"SELECT * FROM riderLocations;"
```

It returns:

```JSON
[
	{
		"header": {
			"queryId": "transient_RIDERLOCATIONS_2722336623052488734",
			"schema": "`PROFILEID` STRING, `LATITUDE` DOUBLE, `LONGITUDE` DOUBLE"
		}
	},
	{
		"row": {
			"columns": [
				"c2309eec",
				37.7877,
				-122.4205
			]
		}
	},
	{
		"row": {
			"columns": [
				"18f4ea86",
				37.3903,
				-122.0643
			]
		}
	},
	{
		"row": {
			"columns": [
				"4ab5cbad",
				37.3952,
				-122.0813
			]
		}
	},
	{
		"row": {
			"columns": [
				"4ab5cbad",
				38.3952,
				-122.0813
			]
		}
	},
	{
		"row": {
			"columns": [
				"4ab5cbad",
				38.3952,
				-122.0813
			]
		}
	},
	{
		"row": {
			"columns": [
				"4ab5cbad",
				38.3952,
				-122.0813
			]
		}
	},
	{
		"row": {
			"columns": [
				"4ab5cbad",
				38.3952,
				-121.0813
			]
		}
	},
	{
		"row": {
			"columns": [
				"4ddad000",
				37.7857,
				-122.4011
			]
		}
	},
	{
		"row": {
			"columns": [
				"4ddad000",
				37.7857,
				-122.4011
			]
		}
	},
]
```

Which has an extra comma (",") at the end that brakes any JSON Parser.

**To Reproduce**
Steps to reproduce the behavior, include:
1. Follow the quickstart guide [here](https://ksqldb.io/quickstart.html)
2. Run the query `SELECT * FROM riderLocations;`

**Expected behavior**
The response to be a valid JSON.

**Actual behaviour**
A clear and concise description of what actually happens, including:
1. The response is not a valid JSON

**Comment by agavra** [comment]
Thanks for reporting this @LapoElisacci - can you share which version you are using? cc @AlanConfluent @cprasad1 as this seems to relate to the endpoint work.

**Comment by LapoElisacci** [comment]
Sure @agavra, I'm using the following Docker Image:

`confluentinc/ksqldb-server:0.23.1`

**Comment by AlanConfluent** [comment]
Looking into this today. I know this codepath has recently changed, so not sure if this will still be an issue on master, but will check.
