### ISSUE TITLE
Add DELETE/DROP Topic functionality

### ISSUE THREAD

**Issue by NCAndreea** [confluentinc/ksql#8577]
Hi,

In KSQL DB when deleting a stream or table we have the option to add also the DELETE TOPIC clause: DROP TABLE test DELETE TOPIC;
In case the DELETE TOPIC has not been added when the TABLE/STREAM was dropped then we are not able to delete the topic from KSQLDB.
Please add this feature to be able to do: DELETE topic;
Thank you.

Regards,

**Comment by spena** [comment]
Thanks @NCAndreea . It's a nice thing to have. But there are no plans to support a CLI for Kafka at this moment. I think we only have the PRINT and SHOW TOPICS. 
I'll close this issue as there are no plans to extend this.

**Comment by NCAndreea** [comment]
If we have this already working: DROP TABLE test **DELETE TOPIC**;
Why we cannot have DROP/DELETE TOPIC X; ?
Part of this functionality is already implemented here: DROP TABLE test **DELETE TOPIC**;
