### ISSUE TITLE
error: create table  as select  

### ISSUE THREAD

**Issue by chengang2** [confluentinc/ksql#859]
error: create table a with (value_format='json') as  select age,name from streamb limit 200;
point：Invalid result type. Your SELECT query produces a STREAM. Please use CREATE STREAM AS SELECT statement instead.
but i  want to create table. how to do

**Comment by big-andy-coates** [comment]
For tables, you need to aggregate the stream by some key. This key will define the key of the table.  You achieve this by doing a `GROUP BY`.

The example queries in the [quick start](https://github.com/confluentinc/ksql/tree/master/docs/quickstart#quick-start) show this.

**Comment by apurvam** [comment]
Please reopen if @big-andy-coates didn't answer your question, though that is the right answer(tm).
