### ISSUE TITLE
Cannot terminate/explain PUSH query

### ISSUE THREAD

**Issue by NCAndreea** [confluentinc/ksql#8615]
Hi, 

If I want to terminate or do an explain on a PUSH query I get following error:  
line 1:21: mismatched input '-' expecting ';'
Statement: terminate _confluent-ksql-user1transient_7056226157773336917_1642576953130;
Caused by: line 1:21: mismatched input '-' expecting ';'
Caused by: org.antlr.v4.runtime.InputMismatchException

![image](https://user-images.githubusercontent.com/96262788/150084875-772480d2-6187-49ad-99f6-1e9bae9efa3f.png)

I have tried to use different quotes to make it work but still not working. Is there a workaround for this? 
Would be useful to be able to do these operations.
Thank you very much for your help.

**Comment by agavra** [comment]
using single quotes should work - also what version of ksqlDB are you using? see #7947, which was merged in 0.22

**Comment by agavra** [comment]
@NCAndreea unfortunately the fix linked above is not in any CP release yet. You'll need to either use the community edition (which is interoperable with 6.2 brokers) or wait for 7.1 to come out.

I'll close this issue since it's been fixed, but feel free to follow up with any questions.
