### ISSUE TITLE
ksqldb aggregate window send only final message

### ISSUE THREAD

**Issue by devopg** [confluentinc/ksql#8643]
I have topic with collect _view_ for users.

How i can in ksqldb send only final message for windows aggregate on close 10 minute?

Example after first 10 minute we have only 2 messages then windows close (center column on screen). "myApp" receive only 2 messages per user.

p.s. beautiful range of time is more for clarity

![image](https://user-images.githubusercontent.com/61819835/150689874-151f739f-2d7d-4c2e-89c4-6df47a20f50b.png)

**Comment by mjsax** [comment]
ksqlDB supports `EMIT FINAL` (similar to `EMIT CHANGES`) that tells ksqlDB to only emit the final result of a windowed aggregation. It's an undocumented feature that should be used with care: `EMIT FINAL` uses an in-memory buffer that could grow unbounded and thus could lead to out-of-memory errors.

Furthermore, if you use `EMIT FINAL` the result is emitted when the window closes (window close time = window end plus grace period). Grace period defaults to 24h what is most likely too large. Thus you should also set an appropriate grace period in your window definition.

Closing this question. Feel free to reopen if you have follow up questions.
