### ISSUE TITLE
array_concat is not listed as a scalar function

### ISSUE THREAD

**Issue by jnh5y** [confluentinc/ksql#8666]
array_concat should be on https://docs.ksqldb.io/en/latest/developer-guide/ksqldb-reference/scalar-functions

**Comment by JimGalasyn** [comment]
Good find, @jnh5y! Tracking with internal ticket DOCS-11937.

**Comment by jnh5y** [comment]
Happy to help.  At some point maybe I'll know ksqldb well enough that I won't be reading the docs as much:).  Thanks for picking it up!

**Comment by JimGalasyn** [comment]
Background: this content was reverted in https://github.com/confluentinc/ksql/pull/8016 for 0.20.0, and I didn't remember to add it for 0.21.0.

**Comment by JimGalasyn** [comment]
Fixed in https://github.com/confluentinc/ksql/pull/8688.
