### ISSUE TITLE
KAFKA format does not support BYTES

### ISSUE THREAD

**Issue by jzaralim** [confluentinc/ksql#8693]
**Describe the bug**
If you try to create a KAFKA formatted source with a BYTES column, the command will return

```
CREATE STREAM TEST (ID BYTES KEY, b BYTES) WITH (kafka_topic='test', format='DELIMITED');
The 'KAFKA' format does not support type 'BYTES'
```

This is because the BYTES type is missing [here](https://github.com/confluentinc/ksql/blob/a27e5e7501891e644196f8d164d078672e0feecd/ksqldb-serde/src/main/java/io/confluent/ksql/serde/kafka/KafkaSerdeFactory.java#L40)

**Comment by RishiKumarRay** [comment]
will adding BYTES.class, Serdes.BYTES() solves this error?

**Comment by jzaralim** [comment]
@RishiKumarRay Internally, ksqlDB uses `java.nio.ByteBuffer` to represent the BYTES type, so it would actually be `ByteBuffer.class, Serdes.ByteBuffer()`

**Comment by RishiKumarRay** [comment]
is there anything else needed to add for solving this issue other than issue?

**Comment by jzaralim** [comment]
That's all! For testing, we will need to add a case for `BYTES` [here](https://github.com/confluentinc/ksql/blob/a27e5e7501891e644196f8d164d078672e0feecd/ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/serde/kafka/KafkaSerdeSupplier.java#L74) in order for our [integration tests](https://github.com/confluentinc/ksql/blob/master/ksqldb-functional-tests/src/test/resources/query-validation-tests/bytes.json) to work with the KAFKA format.

**Comment by RishiKumarRay** [comment]
case BYTESBuffer:
        return Serdes.serdeFrom(
            new TestNumberSerializer<>(Serdes.BYTESBuffer.serializer(), BYTESBuffer.class,
                Number::BYTESBuffer),
            new TestBYTESBufferDeserializer(Serdes.BYTESBuffer.deserializer())

@jzaralim is it correct ? just tried after looking at the code?

**Comment by jzaralim** [comment]
The case would be BYTES, since it refers to the name of the ksql type.

You would have to write a custom deserializer to convert base64 strings to bytebuffers. This is because our tests are written as JSON files, which can't inherently represent byte arrays. The number types do this as well to distinguish between int/bigint/double. You can see an example [here](https://github.com/confluentinc/ksql/blob/a27e5e7501891e644196f8d164d078672e0feecd/ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/serde/kafka/KafkaSerdeSupplier.java#L236).
