### ISSUE TITLE
ksqlDB returns invalid JSON as a response to /query requests

### ISSUE THREAD

**Issue by Gerrrr** [confluentinc/ksql#8746]
**Describe the bug**

ksqlDB returns invalid JSON as a response to `/query` requests. This bug occurs only on `master`. The latest released version, 0.23.1, responds to queries with valid JSON.

**To Reproduce**

Create an empty source table:

```
ksql> CREATE SOURCE TABLE t1
>                (K INT PRIMARY KEY, VS ARRAY<INT>)
>                WITH (KAFKA_TOPIC='t1', value_format='JSON', partitions=1);

 Message
--------------------------------
 Created query with ID CST_T1_7
--------------------------------
```

Query the table via an HTTP request:

```
$ curl --header "Accept: application/json" \
     --request POST \
     -d '{"ksql": "SELECT K, VS FROM t1 WHERE K=2 LIMIT 1;"}' \
      http://localhost:8088/query
```

**Expected behavior**

HTTP response contains valid JSON. For example, here is output of ksqlDB 0.23.1:

```
 curl --header "Accept: application/json" \
     --request POST \
     -d '{"ksql": "SELECT K, VS FROM t1 WHERE K=2;"}' \
      http://localhost:8088/query
[{"header":{"queryId":"query_1644571334010","schema":"`K` INTEGER KEY, `VS` ARRAY<INTEGER>"}}]%
```

**Actual behaviour**

HTTP response contains invalid JSON.  Output in `master`:

```
$ curl --header "Accept: application/json" \
     --request POST \
     -d '{"ksql": "SELECT K, VS FROM t1 WHERE K=2 LIMIT 1;"}' \
      http://localhost:8088/query
[{"header":{"queryId":"query_1644570958629","schema":"`K` INTEGER KEY, `VS` ARRAY<INTEGER>"}},
]%
```

**Comment by colinhicks** [comment]
@Gerrrr is the behavior the same if the `Accept: application/json` header passed to the request?

`Content-Type` is usually interpreted as the content type of the request payload. `Accept` should indicate the desired response data format.

**Comment by Gerrrr** [comment]
@colinhicks you are right! Setting `Accept: application/json` headers solved the issue:

```
curl --header "Accept: application/json" \
     --request POST \
     -d '{"ksql": "SELECT K, VS FROM s1 LIMIT 1;"}' \
      http://localhost:8088/query
[{"header":{"queryId":"transient_S1_3113559663616535365","schema":"`K` INTEGER, `VS` ARRAY<INTEGER>"}},
{"row":{"columns":[1,[1,2,3]]}},
{"finalMessage":"Limit Reached"}]
```

Thank you!

**Comment by agavra** [comment]
@Gerrrr is this a dupe of #8554?

**Comment by Gerrrr** [comment]
@agavra I think that this is the same issue. Although #8554 is closed, I can reliably reproduce the example from this issue description on the most recent master. 

We can either reopen #8554 or keep this issue.

**Comment by agavra** [comment]
cc @AlanConfluent can you take a look?

**Comment by AlanConfluent** [comment]
The bug occurs when there are no rows...  I discovered this as well.  I have a PR which fixes this and adds a test for it: https://github.com/confluentinc/ksql/pull/8705

**Comment by colinhicks** [comment]
Can we close this as https://github.com/confluentinc/ksql/pull/8705 was merged?

**Comment by Gerrrr** [comment]
I double-checked that the bug is fixed, closing this issue.
