### ISSUE TITLE
Support DATE and TIMESTAMP types with MIN/MAX aggregate functions

### ISSUE THREAD

**Issue by mikebin** [confluentinc/ksql#8757]
It would be useful to be able to use `MIN`/`MAX` aggregate functions directly with `DATE` and `TIMESTAMP` types. Currently have to convert to numeric values with `UNIX_DATE` and `UNIX_TIMESTAMP`.

**Comment by pgaref** [comment]
Addresses by https://github.com/confluentinc/ksql/pull/8924
