### ISSUE TITLE
Add REGEXP_EXTRACT built-in function

### ISSUE THREAD

**Issue by hjafarpour** [confluentinc/ksql#878]
This built-in function will help extracting a string using the pattern.

**Comment by big-andy-coates** [comment]
Hi @hjafarpour - given that these are internal functions, not user-defined, it might be clearer to give them another name...  KDFs!  (Well, that's one option anyway).

**Comment by apurvam** [comment]
How is this different from #881 ? cc @rmoff

**Comment by rmoff** [comment]
I'd +1 not calling it a *U*DF

From my point of view both `INSTR` and `REGEXP_EXTRACT` are useful. The former is simpler and more accessible (and more familiar to more SQL users). The latter is more powerful but requires knowledge of regex, and for simple stuff is thus overkill.

**Comment by hjafarpour** [comment]
We can call them build in functions :)

**Comment by bluemonk3y** [comment]
Built-in would be the presumed standard.  I.e Cassandra etc

**Comment by blueedgenick** [comment]
+1 for a regexp_extract function

**Comment by stevenpyzhang** [comment]
What exactly is the behavior we want for this function? I've been looking through other example of 
REGEXP_EXTRACT and there's slight variance in all their behaviors.

https://docs.data.world/documentation/sql/reference/functions/regexp_extract.html
https://www.ibm.com/support/knowledgecenter/SS5FPD_1.0.0/com.ibm.ips.doc/postgresql/sqltk/r_sqlext_regexp_extract.html

cc @confluentinc/ksql

**Comment by blueedgenick** [comment]
As usual, the Presto team has a well thought out approach to this (family
of) function: https://prestodb.io/docs/current/functions/regexp.html. I'd
look there for inspiration.

**Comment by vcrfxia** [comment]
This was implemented in https://github.com/confluentinc/ksql/pull/4728
