### ISSUE TITLE
KSqlTestRunner: Extra result per expected record with null key 

### ISSUE THREAD

**Issue by AndyCa** [confluentinc/ksql#8793]
KSqlTestRunner: Extra result per expected record with null key 

**Describe the bug**
KSqlTestRunner returns an unexpected doubling of the expected test-output. The KSQL included links the same table (table_a) to the a relationship table. The expectation is that each intermediary table b has a single record (which is the case) and therefore the final output table also has a single record (not 2). The extra record has unexpected null keys and values for the relationship table. See attached zip for test files to be run with `ksql-test-runner` with docker image `confluentinc/ksqldb-cli`.

KSQL:
```
create table table_a(ROWKEY STRUCT<id STRING> PRIMARY KEY, NAME STRING)
    with (kafka_topic='A', key_format='AVRO', value_format='AVRO', PARTITIONS=1);

create table relationship_table (
    ROWKEY STRUCT<id STRING> PRIMARY KEY,
    relationship_id STRING,
    relationship_type STRING
  ) 
  with (kafka_topic='relationship', VALUE_AVRO_SCHEMA_FULL_NAME='Relationship', key_format='AVRO', value_format='AVRO', PARTITIONS=1);

create stream stream_b
    (
        ROWKEY STRUCT<ID STRING> KEY,
        relationship_id STRING
    ) 
    with (
		kafka_topic='com.abc.sys.client_legal_owner_0_table_v1', 
		VALUE_AVRO_SCHEMA_FULL_NAME='B',
		key_format='AVRO',
		value_format='AVRO',
		PARTITIONS=1);

create table table_b
  with (
    kafka_topic='com.abc.sys.client_legal_owner_0_table_v1', 
    VALUE_AVRO_SCHEMA_FULL_NAME='B', 
    key_format='AVRO',
    value_format='AVRO',
    PARTITIONS=1) 
    as
      select 
        a.rowkey as rowkey,
        r.relationship_id as relationship_id
      from table_a a 
      left join relationship_table r 
        on r.rowkey = a.rowkey
      where r.relationship_type = 'B'
      emit changes;
	  
create table output_table
  with (
	kafka_topic='output', 
	VALUE_AVRO_SCHEMA_FULL_NAME='Output', 
	key_format='AVRO', 
	value_format='AVRO', 
	PARTITIONS=1) 
	as
	  select
		a.rowkey,
		b.rowkey,
		b.relationship_id as relationship_id 
	  from table_a a
	  left join table_b b
		on a.rowkey = b.rowkey
	  emit changes;
```

**To Reproduce**
Steps to reproduce the behavior, include:
1. The version of KSQL: Docker image `confluentinc/ksqldb-cli:sha256:eaf5b9a8cda8f87ba42767f8a9888827aa0837a82fae146ae1eb67bfa6d1e3aa`
2. Sample source data: Included as an attachment.
3. To reproduce via git bash: `winpty docker run -it --rm --mount type=bind,source="{path_to_unzipped_attachment}/ksql_bug_example",target=/app confluentinc/ksqldb-cli:latest bash` followed by `ksql-test-runner -s /app/test.ksql -i /app/test-input.json -o /app/test-output.json`

**Expected behavior**
Expect the attached test to pass with a result set of 1 record containing no null `relationship_id/relationship_type`. Instead the result has 2 records with the extra unexpected record having a null key and null `relationship_id/relationship_type`.

**Actual behaviour**

```
 ksql-test-runner -s /app/test.ksql -i /app/test-input.json -o /app/test-output.json > output.txt
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
        >>>>> Test failed: Topic output. Expected <1> records but it was <2>
Actual records:
<{ID=ID_1}, {RELATIONSHIP_ID=null, B_ROWKEY=null}> with timestamp=0    <-------- WHY?????
<{ID=ID_1}, {RELATIONSHIP_ID=B_ID, B_ROWKEY={ID=ID_1}}> with timestamp=0
```

KSQL logs are attached in ksql_bug_example.zip

**Additional context**
[ksql_bug_example.zip](https://github.com/confluentinc/ksql/files/8109336/ksql_bug_example.zip)

**Comment by mjsax** [comment]
Closing this for now. Feel free to follow up / re-open if necessary.
