### ISSUE TITLE
Create a "Count" function to get the length of an array in an event for KSQL queries.

### ISSUE THREAD

**Issue by JordanGardiner-enable** [confluentinc/ksql#8797]
Hi All,
Is it possible to create a KSQL Stream where the Length of an array is calculated and used in the Where condition?
I.e something like this:

CREATE STREAM DEPARTED_FULL_TRAINS AS SELECT * FROM TEST_TRAIN_DEPARTURES_STREAM WHERE PASSENGER_COUNT > (COUNT(TRAIN->CARRIAGES) * 40);

Below is the event
{
  "TRAIN": {
    "ID": "train123",
    "TYPE": "steam",
    "CARRIAGES": [
      {
        "CARRIAGE": {
          "ID": "1Z781BP99Y",
          "TYPE": "string"
        }
      },
      {
        "CARRIAGE": {
          "ID": "YTNJP4NCTD",
          "TYPE": "string"
        }
      },
      {
        "CARRIAGE": {
          "ID": "RB76E6XPWQ",
          "TYPE": "string"
        }
      },
      {
        "CARRIAGE": {
          "ID": "GQCN6UPIA3",
          "TYPE": "string"
        }
      },
      {
        "CARRIAGE": {
          "ID": "CU9HX8TGWW",
          "TYPE": "string"
        }
      }
    ]
  },
  "STATION": {
    "ID": "CHCH_4",
    "LOCATION": "Christchurch",
    "NAME": "christchurch_4"
  },
  "DEPARTURE_TIME": "2022-02-21 15:03:20.909436",
  "DESTINATION": {
    "ID": "AP_1",
    "LOCATION": "Christchurch",
    "NAME": "airport_1"
  },
  "PASSENGER_COUNT": 5
}

This is the error message that is returned:

Invalid Predicate: Can't find any functions with the name 'COUNT'. expression: (PASSENGER_COUNT > (COUNT(TRAIN->CARRIAGES) * 40)), schema:`DEPARTURE_ID` STRING, `TRAIN` STRUCT<`ID` STRING, `TYPE` STRING, `CARRIAGES` ARRAY<STRUCT<`CARRIAGE` STRUCT<`ID` STRING, `TYPE` STRING, `CAPACITY` INTEGER>>>>, `STATION` STRUCT<`ID` STRING, `LOCATION` STRING, `NAME` STRING>, `DEPARTURE_TIME` STRING, `DESTINATION` STRUCT<`ID` STRING, `LOCATION` STRING, `NAME` STRING>, `PASSENGER_COUNT` INTEGER, `ROWTIME` BIGINT, `ROWPARTITION` INTEGER, `ROWOFFSET` BIGINT Caused by: Can't find any functions with the name 'COUNT'

**Comment by agavra** [comment]
There's an `ARRAY_LENGTH` method. Is that what you're looking for?

**Comment by JordanGardiner-enable** [comment]
That is exactly what I am looking for! Thanks for that, can you please link me to the documentation?

**Comment by agavra** [comment]
here you go: https://docs.ksqldb.io/en/latest/developer-guide/ksqldb-reference/scalar-functions/#array_length
