### ISSUE TITLE
Add support for REPLACE function

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#882]
It would be useful to have a `REPLACE` function, similar in concept to [this](https://docs.oracle.com/database/121/SQLRF/functions167.htm#SQLRF00697)

Reason: data mungling & wrangling.

**Comment by mateuszmrozewski** [comment]
@rmoff, this seems to be already implemented: https://docs.ksqldb.io/en/latest/developer-guide/ksqldb-reference/scalar-functions/#replace
