### ISSUE TITLE
chore: Update references to ConnectorPluginInfo to PluginInfo

### ISSUE THREAD

**Issue by jnh5y** [confluentinc/ksql#8841]
This change in Kafka https://github.com/apache/kafka/commit/029a14b530dcaab980faee4fa18c925b95db3122 renamed ConnectorPluginInfo to PluginInfo.

**Comment by suhas-satish** [comment]
@jnh5y , whats the impact of this? Is it a breaking change?

**Comment by jnh5y** [comment]
@suhas-satish Since it is a change in the public Kafka API, ksqlDB will not compile against the latest Kafka nano-versions until we make a change in ksqlDB.  I don't think such a nano-version is available yet, so we'll have to wait for that...

As soon as that becomes available, the ksqlDB build will be broken until we merge a fix for this issue.

**Comment by jnh5y** [comment]
Sure, I'll take it in the background.

**Comment by jnh5y** [comment]
The PR has resolved this!
