### ISSUE TITLE
Support non-SchemaRegistry PROTOBUF serialization/deserialization

### ISSUE THREAD

**Issue by ddai23** [confluentinc/ksql#8853]
**Is your feature request related to a problem? Please describe.**
Schema Registry is required in ksqlDB for Protobuf deserialization.

**Describe the solution you'd like**
Supports map<topic, protobuf_definition> in parameters to ksqlDB cluster, and deserialize given Protobufs in corresponding topics without needing Schema Registry.

**Describe alternatives you've considered**

**Additional context**
We can't upgrade the input data to be schema-id encoded, and managing the additional SchemaRegistry cluster is an overhead for only a handful of static PROTOBUFs.

**Comment by suhas-satish** [comment]
prioritizing this for Q2. cc: @Gerrrr
