### ISSUE TITLE
Pull queries are not supported on streams??

### ISSUE THREAD

**Issue by MariaCobretti** [confluentinc/ksql#8879]
I am trying on of the most basic examples without it getting to work so iam curios for your input..

I created a stream for a topic in the ksql cli

`create stream streamSimple with (kafka_topic='weatherSimple',format='avro');`

and the issued a pull query

`select * from streamsimple where rowkey='munich';`

where i am getting the response: Pull queries are not supported on streams. See https://cnfl.io/queries for more info.
even though when you look at the docs it says: You can issue a pull query against any stream.

thanks

**Comment by agavra** [comment]
What version are you using? pull queries are supported on streams as of 0.23 (I believe)

**Comment by MariaCobretti** [comment]
well that would make some sense.. I'm using the cp version 7.0.1 which relates to 0.21 ksqlDB Standalone I just found out, so it lags 3 versions behind
