### ISSUE TITLE
ksql-cli will swallow silently that brokers do not meet offsets.topic.replication.factor

### ISSUE THREAD

**Issue by larsp** [confluentinc/ksql#888]
In case `offsets.topic.replication.factor` is not fulfilled by the brokers the kafka server log will complain a lot once `ksql-cli` is started:
```
...
[2018-03-08 09:32:22,024] ERROR [KafkaApi-0] Number of alive brokers '1' does not meet the required replication factor '3' for the offsets topic (configured via 'offsets.topic.replication.factor'). This error can be ignored if the cluster is starting up and not all brokers are up yet. (kafka.server.KafkaApis)
[2018-03-08 09:32:22,027] ERROR [KafkaApi-0] Number of alive brokers '1' does not meet the required replication factor '3' for the offsets topic (configured via 'offsets.topic.replication.factor'). This error can be ignored if the cluster is starting up and not all brokers are up yet. (kafka.server.KafkaApis)
[2018-03-08 09:32:22,037] ERROR [KafkaApi-0] Number of alive brokers '1' does not meet the required replication factor '3' for the offsets topic (configured via 'offsets.topic.replication.factor'). This error can be ignored if the cluster is starting up and not all brokers are up yet. (kafka.server.KafkaApis)
...
```
Even though critical internal topics can't be created/used, `KSQL` (e.g. through `ksql-cli local`) will start without any signs of issues. Furthermore it will accept all sorts of queries but will never return any results on `SELECT` statements.

_Expected_:
If internal topics can't be created/used with the result that KSQL won't function properly, I would expect it to notify the user/client.

**Comment by big-andy-coates** [comment]
Hi @larsp, thanks for reporting this issue. Could you provide a little more info please?

* What version are you running
* Are you seeing this issue while running one of the demos, or with your own Kafka / KSQL clusters?

**Comment by larsp** [comment]
Hi @big-andy-coates, thanks for the fast reply.

I am using the latest and greates `ksql` version from yesterday:

```
ksql> version
Version: 0.5
```
but I had the same issue with the previous version: `0.4`

I am running my own cluster using `confluent-platform-oss-2.11 4.0.0-1 ` on ubuntu 16.04 and it is doing what it suppose to do :)

**Comment by big-andy-coates** [comment]
How many brokers are there in your Kafka cluster?

**Comment by larsp** [comment]
Sorry, thought that was clear from first message.

This happens when there are less brokers than configured in `offsets.topic.replication.factor`. The default value is 3. The test setup only had one broker up, hence the errors in the broker server log.

ksql was started via: `ksql-cli local`

**Comment by big-andy-coates** [comment]
Hi @larsp. I believe that when a single node Kafka cluster is created it will still create the __consumer_offsets topic, (with a single replica), though it will log as you've listed above.  However, this should _not_ stop the Kafka cluster working, or KSQL.

I have a feeling your issue is unrelated to this log line.  Maybe you can explain what you're trying to achieve?  A common gotcha for people new to KSQL is to have existing data in a topic, starting up KSQL, and expect to be able to `select *` from this topic.  KSQL, (and KStreams), by default only shows new data coming into the topic.  You can `SET 'auto.offset.reset'='earliest';` to have it read from the start of topics.

**Comment by larsp** [comment]
_TL;DR_ `ksql-cli` won't work properly if it can't setup `__consumer_offsets`

As I have pointed out in my initial report, the broker is doing what it is suppose to do, KSQL is not. Let me guide you through everything step by step since you seem reluctant in trying to reproduce it :wink:. 

Apologies for verbosity.

Let's create a `users` topic on a pretty empty one node cluster:
```
> $ kafka-topics --zookeeper localhost:2181 --list

> $ kafka-topics --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic users
Created topic "users".
> $ kafka-topics --zookeeper localhost:2181 --describe 
Topic:users	PartitionCount:1	ReplicationFactor:1	Configs:
	Topic: users	Partition: 0	Leader: 0	Replicas: 0	Isr: 0
```

Let's generate some random data to that topic:
```
> $ ./ksql-datagen quickstart=users format=json topic=users key=userid maxInterval=1000
User_8 --> ([ 1501714450688 | 'User_8' | 'Region_7' | 'OTHER' ])
User_4 --> ([ 1518067771278 | 'User_4' | 'Region_8' | 'OTHER' ])
User_2 --> ([ 1499731457815 | 'User_2' | 'Region_3' | 'FEMALE' ])
...
```
Let's check if the messages actually made it to the broker/topic:
```
> $ kafka-simple-consumer-shell  --broker-list localhost:9092 --topic users
[2018-03-08 13:52:08,973] WARN WARNING: SimpleConsumerShell is deprecated and will be dropped in a future release following 0.11.0.0. (kafka.tools.SimpleConsumerShell$)
{"registertime":1501714450688,"gender":"OTHER","regionid":"Region_7","userid":"User_8"}
{"registertime":1518067771278,"gender":"OTHER","regionid":"Region_8","userid":"User_4"}
{"registertime":1499731457815,"gender":"FEMALE","regionid":"Region_3","userid":"User_2"}
...
```
looks like what we wanted.


Now, let us tail the broker log and start ksql:
```
> $ ./ksql-cli local
Initializing KSQL...
                       ======================================
                       =      _  __ _____  ____  _          =
                       =     | |/ // ____|/ __ \| |         =
                       =     | ' /| (___ | |  | | |         =
                       =     |  <  \___ \| |  | | |         =
                       =     | . \ ____) | |__| | |____     =
                       =     |_|\_\_____/ \___\_\______|    =
                       =                                    =
                       =   Streaming SQL Engine for Kafka   =
Copyright 2017 Confluent Inc.                         

CLI v0.5, Server v0.5 located at http://localhost:9098

Having trouble? Type 'help' (case-insensitive) for a rundown of how things work!

ksql> 
```

``` 
> $ tail -f /var/log/kafka/server.log 
2018-03-08 13:55:29,483] INFO Got user-level KeeperException when processing sessionid:0x16205d7bad30000 type:setData cxid:0x5f zxid:0x33 txntype:-1 reqpath:n/a Error Path:/config/topics/ksql__commands Error:KeeperErrorCode = NoNode for /config/topics/ksql__commands (org.apache.zookeeper.server.PrepRequestProcessor)
[2018-03-08 13:55:29,484] INFO Got user-level KeeperException when processing sessionid:0x16205d7bad30000 type:create cxid:0x60 zxid:0x34 txntype:-1 reqpath:n/a Error Path:/config/topics Error:KeeperErrorCode = NodeExists for /config/topics (org.apache.zookeeper.server.PrepRequestProcessor)
[2018-03-08 13:55:29,487] INFO Topic creation {"version":1,"partitions":{"0":[0]}} (kafka.admin.AdminUtils$)
[2018-03-08 13:55:29,493] INFO Got user-level KeeperException when processing sessionid:0x16205d7bad30000 type:create cxid:0x68 zxid:0x37 txntype:-1 reqpath:n/a Error Path:/brokers/topics/ksql__commands/partitions/0 Error:KeeperErrorCode = NoNode for /brokers/topics/ksql__commands/partitions/0 (org.apache.zookeeper.server.PrepRequestProcessor)
[2018-03-08 13:55:29,494] INFO Got user-level KeeperException when processing sessionid:0x16205d7bad30000 type:create cxid:0x69 zxid:0x38 txntype:-1 reqpath:n/a Error Path:/brokers/topics/ksql__commands/partitions Error:KeeperErrorCode = NoNode for /brokers/topics/ksql__commands/partitions (org.apache.zookeeper.server.PrepRequestProcessor)
[2018-03-08 13:55:29,508] INFO [ReplicaFetcherManager on broker 0] Removed fetcher for partitions ksql__commands-0 (kafka.server.ReplicaFetcherManager)
[2018-03-08 13:55:29,514] INFO Loading producer state from offset 0 for partition ksql__commands-0 with message format version 2 (kafka.log.Log)
[2018-03-08 13:55:29,515] INFO Completed load of log ksql__commands-0 with 1 log segments, log start offset 0 and log end offset 0 in 3 ms (kafka.log.Log)
[2018-03-08 13:55:29,517] INFO Created log for partition [ksql__commands,0] in /tmp/kafka-logs with properties {compression.type -> producer, message.format.version -> 1.0-IV0, file.delete.delay.ms -> 60000, max.message.bytes -> 1000012, min.compaction.lag.ms -> 0, message.timestamp.type -> CreateTime, min.insync.replicas -> 1, segment.jitter.ms -> 0, preallocate -> false, min.cleanable.dirty.ratio -> 0.5, index.interval.bytes -> 4096, unclean.leader.election.enable -> false, retention.bytes -> -1, delete.retention.ms -> 86400000, cleanup.policy -> [delete], flush.ms -> 9223372036854775807, segment.ms -> 604800000, segment.bytes -> 1073741824, retention.ms -> 9223372036854775807, message.timestamp.difference.max.ms -> 9223372036854775807, segment.index.bytes -> 10485760, flush.messages -> 9223372036854775807}. (kafka.log.LogManager)
[2018-03-08 13:55:29,518] INFO [Partition ksql__commands-0 broker=0] No checkpointed highwatermark is found for partition ksql__commands-0 (kafka.cluster.Partition)
[2018-03-08 13:55:29,518] INFO Replica loaded for partition ksql__commands-0 with initial high watermark 0 (kafka.cluster.Replica)
[2018-03-08 13:55:29,520] INFO [Partition ksql__commands-0 broker=0] ksql__commands-0 starts at Leader Epoch 0 from offset 0. Previous Leader Epoch was: -1 (kafka.cluster.Partition)
[2018-03-08 13:55:34,582] ERROR [KafkaApi-0] Number of alive brokers '1' does not meet the required replication factor '3' for the offsets topic (configured via 'offsets.topic.replication.factor'). This error can be ignored if the cluster is starting up and not all brokers are up yet. (kafka.server.KafkaApis)
[2018-03-08 13:55:35,474] ERROR [KafkaApi-0] Number of alive brokers '1' does not meet the required replication factor '3' for the offsets topic (configured via 'offsets.topic.replication.factor'). This error can be ignored if the cluster is starting up and not all brokers are up yet. (kafka.server.KafkaApis)
[2018-03-08 13:55:35,980] ERROR [KafkaApi-0] Number of alive brokers '1' does not meet the required replication factor '3' for the offsets topic (configured via 'offsets.topic.replication.factor'). This error can be ignored if the cluster is starting up and not all brokers are up yet. (kafka.server.KafkaApis)
...
```

Now let's try to use ksql to list topics, create a stream and read from it (yes, with `SET 'auto.offset.reset'='earliest';`
```
ksql> list topics;

 Kafka Topic    | Registered | Partitions | Partition Replicas | Consumers | Consumer Groups 
---------------------------------------------------------------------------------------------
 ksql__commands | true       | 1          | 1                  | 0         | 0               
 users          | true       | 1          | 1                  | 0         | 0               
---------------------------------------------------------------------------------------------

ksql> SET 'auto.offset.reset'='earliest';
Successfully changed local property 'auto.offset.reset' from 'null' to 'earliest'
ksql> CREATE STREAM users (registertime bigint, userid varchar, regionid varchar, gender varchar) \
> WITH (value_format = 'json', kafka_topic='users', key='userid');

 Message        
----------------
 Stream created 
----------------
ksql> SELECT * FROM users LIMIT 3;


```
The `SELECT` will never terminate.

Let's check what topics had been created via cmd line:

```
> $ kafka-topics --zookeeper localhost:2181 --describe 
Topic:ksql__commands	PartitionCount:1	ReplicationFactor:1	Configs:retention.ms=9223372036854775807
	Topic: ksql__commands	Partition: 0	Leader: 0	Replicas: 0	Isr: 0
Topic:users	PartitionCount:1	ReplicationFactor:1	Configs:
	Topic: users	Partition: 0	Leader: 0	Replicas: 0	Isr: 0
```

Hmm... looks like things are missing here?

Let's start KSQL again, tail the broker log and check again which topics are around:
```
> $ kafka-topics --zookeeper localhost:2181 --list
ksql__commands
users

> $ ./ksql-cli local
Initializing KSQL...
Could not fetch broker information. KSQL cannot initialize AdminCLient.

> $ tail -f /var/log/kafka/server.log


```

No errors in the server log, but `ksql-cli` seems unhappy.

Now let's set up a new single node cluster where `offsets.topic.replication.factor` is 1, and therefore all requirements should be fulfilled. Once this is done let's do the same things: create a topic, generate some data, check if the data made it to the broker:

```
> $  kafka-topics --zookeeper localhost:2181 --list

>   kafka-topics --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic users
Created topic "users".
vagrant@ksql-pipeline:~$ kafka-topics --zookeeper localhost:2181 --describe 
Topic:users	PartitionCount:1	ReplicationFactor:1	Configs:
	Topic: users	Partition: 0	Leader: 0	Replicas: 0	Isr: 0
```

Let's again generate some random data...
```
> $ ./ksql-datagen quickstart=users format=json topic=users key=userid maxInterval=1000
User_2 --> ([ 1507639050507 | 'User_2' | 'Region_1' | 'MALE' ])
User_5 --> ([ 1494235922396 | 'User_5' | 'Region_3' | 'OTHER' ])
User_8 --> ([ 1508777069753 | 'User_8' | 'Region_7' | 'OTHER' ])
...
```

Let's again check for it...
```
kafka-simple-consumer-shell  --broker-list localhost:9092 --topic users
[2018-03-08 14:28:41,520] WARN WARNING: SimpleConsumerShell is deprecated and will be dropped in a future release following 0.11.0.0. (kafka.tools.SimpleConsumerShell$)
{"registertime":1507639050507,"gender":"MALE","regionid":"Region_1","userid":"User_2"}
{"registertime":1494235922396,"gender":"OTHER","regionid":"Region_3","userid":"User_5"}
{"registertime":1508777069753,"gender":"OTHER","regionid":"Region_7","userid":"User_8"}
...
```

Let's now again start ksql:
```
> $ ./ksql-cli local
Initializing KSQL...
                       ======================================
                       =      _  __ _____  ____  _          =
                       =     | |/ // ____|/ __ \| |         =
                       =     | ' /| (___ | |  | | |         =
                       =     |  <  \___ \| |  | | |         =
                       =     | . \ ____) | |__| | |____     =
                       =     |_|\_\_____/ \___\_\______|    =
                       =                                    =
                       =   Streaming SQL Engine for Kafka   =
Copyright 2017 Confluent Inc.                         

CLI v0.5, Server v0.5 located at http://localhost:9098

Having trouble? Type 'help' (case-insensitive) for a rundown of how things work!

ksql> 
```

Let's check what internal topics have been created:
```
> $ kafka-topics --zookeeper localhost:2181 --list
__consumer_offsets
ksql__commands
users
```

__Looks like `__consumer_offsets` has now been created.__


Now everything works.
```
ksql> SET 'auto.offset.reset'='earliest';
Successfully changed local property 'auto.offset.reset' from 'null' to 'earliest'
ksql> CREATE STREAM users (registertime bigint, userid varchar, regionid varchar, gender varchar) \
> WITH (value_format = 'json', kafka_topic='users', key='userid');

 Message        
----------------
 Stream created 
----------------
ksql> SELECT * FROM users LIMIT 3;
1520519200208 | User_2 | 1507639050507 | User_2 | Region_1 | MALE
1520519200757 | User_5 | 1494235922396 | User_5 | Region_3 | OTHER
1520519201721 | User_8 | 1508777069753 | User_8 | Region_7 | OTHER
LIMIT reached for the partition.
Query terminated

```

Great, the same query works.

In my opinion two things are critical
1. Even though `__consumer_offsets` has not been created successfully, `ksql` initializes and starts without any warning
2. `ksql` is not able to recover from that state and quits with a `Could not fetch broker information. KSQL cannot initialize AdminCLient.`

**Comment by big-andy-coates** [comment]
Hi @larsp - appreciate the detailed information. I'll see if I can re-create.

What's a little confusing though is that your two points above seem to conflict:

> `ksql` initializes and starts without any warning
and
> `ksql`... quits with a (error)

I'll re-read when I have more time and I'm sure it'll make sense.

Thanks again @larsp

**Comment by larsp** [comment]
1. 
> `ksql` initializes and starts without any warning

When you start `ksql` the first time backed by an empty broker when it tries to create `__consumer_offsets`. The create of `__consumer_offsets` fails because of `offsets.topic.replication.factor`

2. > `ksql`... quits with a (error)

Every other time you want to start `ksql` following 1.

**Comment by big-andy-coates** [comment]
Hi @larsp, sorry for the delay getting back to you. I had some pressing tasks I needed to clear off.

I've taken some time to read through this again, and one thing that struck me was that the __consumer_offsets topic should, in normal operation, be created well before KSQL gets involved, if you're using `confluent start`. I can only assume you're you're just starting kafka with `confluent start kafka` - would that be right?

Assuming this is the case, I spent some time trying to recreate this. My testing was on Mac OS, with Confluent 4.0.0, and the current 0.5.x branch.

Before starting, I ran `confluent destroy` to ensure no prior state, and then:

1. `confluent start kafka`
1. `kafka-topics --zookeeper localhost:2181 --list` - returned no topics.
1. `kafka-topics --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic users`
1. `ksql-datagen quickstart=users format=json topic=users key=userid maxInterval=1000`, which published data.
1. `kafka-simple-consumer-shell  --broker-list localhost:9092 --topic users`, which returned records.
1. `kafka-topics --zookeeper localhost:2181 --list` returns only `users`
1. `mvn clean install -DskipTests` to ensure we've got a clean 0.5.x build
1. `./bin/ksql-cli local` to start the CLI.
1. Logs on Mac OS are using the confluent installation directory, `grep WARN ../logs/server.log` returned no warnings like those you see.
1. `kafka-topics --zookeeper localhost:2181 --list` returns expected list:
    __consumer_offsets
    ksql__commands
    users
1. `ksql> list topics;` list shows `ksql_commands` and `users` as you'd expect. Though I note that in your output the `users` topic is already registered, where it shouldn't be.
1. If I now run the select query it returns data.

So, I'm afraid I can't recreate this locally.  This _could_ be because I'm on Mac OS, not Ubuntu.

If there is an issue here, then in all honesty it is not with KSQL. KSQL is not doing anything special to create the `__consumer_offsets` topic, it does not explicitly create it, it is just using stock Kafka consumers, which, when used with consumer groups or offsets commits, will cause Kafka itself to create the `__consumer_offsets` topic. If there is an issue here, then it must be with Apache Kafka.  

If you have the time, you may want to investigate more, starting with a `confluent destroy` and a `mvn clean install -DskipTests` (*NOTE*: the `destroy` command will destroy your data!). If you don't, then I suggest just using `confluent start`, to bring up the entire stack. This will force the creation of the offset topic well before KSQL is used, which may help you get past this blip.

**Comment by larsp** [comment]
Hi @big-andy-coates 

what was `offsets.topic.replication.factor` set to when you started `ksql` the first time?

Thanks

Lars

**Comment by big-andy-coates** [comment]
My vanilla confluent platform installation (4.0.0) has the broker coming up with:

```server.properties:offsets.topic.replication.factor=1```

**Comment by larsp** [comment]
> Issue Title: ksql-cli will swallow silently that brokers do not meet offsets.topic.replication.factor

In order to reproduce it you would need to set it to something larger than the available brokers. The default value according to the kafka broker documentation is 3.

**Comment by big-andy-coates** [comment]
Hi @larsp. I think we may have got to the cusp of the problem!  If you configure _Kafka_ to require a larger replication factor on the offsets topic than the number of brokers running in the cluster, then yes, it will report errors when the offsets topic gets created.

KSQL is not doing anything special here - it's just using the stock Kafka java client.  KSQL is only causing the broker to log the errors in so much as its using Kafka consumers to consume the topic data.  Any Kafka consumer would cause the same errors, (assuming its using either consumer groups or storing offsets in Kafka).

Is your issue that KSQL does not detect that the Kafka cluster is in a bad state and inform the user, or that KSQL is somehow doing something wrong, which results in the errors in the broker log? Or both?

**Comment by big-andy-coates** [comment]
Hi @larsp 

Are you happy for this issue to be closed now?

Thanks,

Andy

**Comment by larsp** [comment]
It is your product. If you are happy with the described behavior, sure ¯\_(ツ)_/¯

**Comment by big-andy-coates** [comment]
Hi @larsp,

If you think there is still an issue with KSQL here, then let us get the details hammered out. I detailed what I saw as the possible issues I thought you may be alluding to above:

> If you configure Kafka to require a larger replication factor on the offsets topic than the number of brokers running in the cluster, then yes, it will report errors when the offsets topic gets created.

> KSQL is not doing anything special here - it's just using the stock Kafka java client. KSQL is only causing the broker to log the errors in so much as its using Kafka consumers to consume data. Any Kafka consumer would cause the same errors, (assuming its using either consumer groups or storing offsets in Kafka).

> I'm left wondering if your original issue was that KSQL does not detect that the Kafka cluster is in a bad state and inform the user, or that KSQL is somehow doing something wrong, which results in the errors in the broker log? Or both?

> If it's the former, then I think there is some grounds for seeing that as a bug. Though the issue would need to be address in KStreams, which KSQL is leveraging, not KSQL itself. Would you mind raising an appropriate Jira?

> If the latter, then you might want to try going through your example above again, but this time don't start KSQL. Instead use the kafka-console-consumer.sh with the --group option to consume from a topic via a consumer group. This too will result in the offsets topic being created, and the errors in the broker logs, hopefully proving that this is not a KSQL issue.

What do you think?
