### ISSUE TITLE
VALUE_SCHEMA_ID does not work with Protobuf schema containing float type

### ISSUE THREAD

**Issue by mikebin** [confluentinc/ksql#8885]
**Describe the bug**
New `VALUE_SCHEMA_ID` support in ksqlDB 0.24.0 (KLIP-56) does not work with a Protobuf schema that has field(s) of type `float`. _Without_ `VALUE_SCHEMA_ID`, schema inference works fine, and is able to coerce Protobuf `float` into ksqlDB `double`. 

**To Reproduce**
Version: 0.24.0

1. Register Protobuf schema for topic `mytopic` containing a field of type `float`:
```
syntax = "proto3";

package com.mycorp.mynamespace;
    
message SampleRecord {
    float  f1 = 1;
}
```
Assume that this schema has id 1.

2. Create stream for this topic using `VALUE_SCHEMA_ID`:
```sql
create stream mystream with (kafka_topic='mytopic', value_format='protobuf', value_schema_id=1);
```

**Expected behavior**
Stream is successfully created, coercing Protobuf `float` type to ksqlDB `double`.

**Actual behaviour**
```
Value format does not support schema.
format: PROTOBUF
schema: Persistence{columns=[`f1` DOUBLE], features=[]}
reason: Unexpected schema type: Schema{FLOAT32}
```

**Additional context**
Works fine with schema inference (coercing Protobuf `float` to ksqlDB `double`) when `VALUE_SCHEMA_ID` is _not_ specified:
```
ksql> create stream mystream with (kafka_topic='mytopic', value_format='protobuf');

 Message
----------------
 Stream created
----------------

ksql> describe mystream;

Name                 : MYSTREAM
 Field | Type
----------------
 F1    | DOUBLE
----------------
```

**Comment by lihaosky** [comment]
Hi @mikebin , thanks for the finding.

The different between `VALUE_SCHEMA_ID` and schema inference is that if you use `VALUE_SCHEMA_ID`, the schema used for serialization will be your physical schema defined in SR. If you use schema inference, we translate you SR schema to ksqlDB logical schema in which case the `float32` is translated to `double` and ksqlDB logical schema containing `double` is used for data serialization. It's checked here: https://github.com/confluentinc/ksql/blob/master/ksqldb-serde/src/main/java/io/confluent/ksql/serde/connect/KsqlConnectSerializer.java#L42

I think this exception probably make sense because if you serialize `double` to `float32`, it will lose precision.

**Comment by mikebin** [comment]
Makes sense on the potential loss of precision on the serialization side. In this case, the difference in behavior is on the deserialization (source) side.

**Comment by lihaosky** [comment]
@mikebin , let me know if you are OK to close this.

**Comment by mikebin** [comment]
@lihaosky - just two points to clarify:

- In earlier versions of ksqlDB (such as 7.0.1), specifying `VALUE_SCHEMA_ID` on the CS/CT statement would work with a Protobuf `float` type. For example, this works in 7.0.1 for a protobuf schema that contains a `float` type, but fails in 0.24.0:
```sql
create stream pb with (kafka_topic='pb', value_format='protobuf', value_schema_id=1);
```
So essentially the behavior in 0.24.0 is a breaking change, although it might be the preferred approach.

- These two statements might appear to a user as logically the same thing if `VALUE_SCHEMA_ID` references the latest schema version, but one works, with a Protobuf `float` type, and one doesn't:
```
-- Works
create stream pb with (kafka_topic='pb', value_format='protobuf');

-- Fails
create stream pb with (kafka_topic='pb', value_format='protobuf', value_schema_id=1);
```

If you don't consider either of these points significant enough to warrant a change, then the issue can be closed. Thanks for reviewing.

**Comment by lihaosky** [comment]
Hi @mikebin 

* `VALUE_SCHEMA_ID` is not officially documented and release before 0.24. So we made breaking changes here. Before 0.24, ksqlDB doesn't use *physical schema* to serialize data when `VALUE_SCHEMA_ID` is specified. 
* The below two statements are handled differently
    - For `create stream pb with (kafka_topic='pb', value_format='protobuf');`, latest physical schema is fetched from SR and translated to logical schema in ksqlDB and write back to SR. During the translation, `float` is translated to `double` and `double` is written back to SR. That's why it works.
    - For `create stream pb with (kafka_topic='pb', value_format='protobuf', value_schema_id=1);`, we don't register the translated logical schema in SR but register the original physical schema in SR again under correct subject name. So `float` is maintained and serialization won't work.

One of the purpose of `VALUE_SCHEMA_ID` is to let ksqlDB serialize and deserialize data using user specified physical schema. You can see the *Data Serialization* section in https://github.com/confluentinc/ksql/blob/master/docs/operate-and-deploy/schema-inference-with-id.md.

Hope this clarifies it.

**Comment by mikebin** [comment]
Thanks for the explanation, you can close out the issue.
