### ISSUE TITLE
Error insert value between -1 and 1

### ISSUE THREAD

**Issue by nacholore** [confluentinc/ksql#8890]
Hi, I have created a stream with double type field when I have inserted value near zero in this field, ksql throw error.

KSQL server -> v0.24.0

`sql
CREATE STREAM ais_locations (
            LON DOUBLE,
            DATETIME VARCHAR)
    WITH (kafka_topic='ais_locations',
          partitions=1,
          value_format='JSON',
          timestamp='datetime',
          timestamp_format='yyyy-MM-dd HH:mm:ss');
`

When insert data in stream
`
INSERT INTO ais_locations (LON, DATETIME) VALUES (0.013138,'2022-03-11 12:51:15');
`

Show error
Failed to insert values into 'AIS_LOCATIONS'. Unexpected error generating code for insert value. expression: 0.013138

**Comment by agavra** [comment]
Thanks for the report @nacholore - this has been fixed and will be available in 0.25 (https://github.com/confluentinc/ksql/pull/8720)

In the meantime you can use the workarounds specified in this ticket: #8413
