### ISSUE TITLE
KSQL FROM_BYTES(bytes, encoding) always returns null

### ISSUE THREAD

**Issue by samjpv** [confluentinc/ksql#8895]
I'm new to KSQL and have been experimenting with queries on a cluster via confluent cloud. I am trying to convert a BYTES type field pulled from a header to an ASCII string, precisely following the example provided here: https://docs.ksqldb.io/en/latest/reference/sql/data-definition/#:~:text=CREATE%20STREAM%20s5%20AS%20SELECT%20FROM_BYTES(h1%2C%20%27ascii%27)%20AS%20decoded%20FROM%20s4%3B.

I have an existing stream created from a Kafka topic that contains messages like so: 
`{
  "DATA":  "Zm9vYmFy"
}`
Where DATA comes from a query like this:
`CREATE STREAM newstream
( data BYTES HEADER('header.message')) 
WITH (KAFKA_TOPIC='topicname', VALUE_FORMAT='JSON');`

And am using the query below in an attempt to convert this value to an ASCII string:
`CREATE STREAM ASCIIENCODED WITH (KAFKA_TOPIC='<topic>', PARTITIONS=1, REPLICAS=3, VALUE_FORMAT='JSON') AS SELECT FROM_BYTES(DATA, 'ascii') KSQL_COL_0
FROM SOURCE SOURCE
EMIT CHANGES;`

It seems that no matter what I do, the resulting value in the ASCIIENCODED stream corresponding to the above message is this:
`{
  "KSQL_COL_0": null
}`

There are no errors on creation of the query, and no errors show up in the ksql processing log stream. I have verified that DATA is being pulled successfully from 'newstream' and that it is valid base64, and I have also tried just about every combination of encoding and byte data possible as parameters for FROM_BYTES. I've also noticed that there's no indication of the encoding parameter there being wrong or not during query creation even if a trash value is used, which might be an issue in itself.

I've spent quite a lot of time trying to make this work, to no avail, and I'm wondering if it might be a bug. I would appreciate it if someone could verify. If nothing else it seems like there should be a better way of giving error feedback in this case.

On a related note, is there a way to somehow nest scalar functions within a query that I haven't found? If so, I might be able to circumvent this issue.

**Comment by samjpv** [comment]
This started working after what seemed like no change

**Comment by samjpv** [comment]
After some trial and error, this seems to possibly be an issue with confluent cloud portal not displaying the right value in the ASCIIENCODED stream after it is processed from newstream, as it sometimes starts showing non-null ascii values for KSQL_COL_0 after I reload the page, and tends to start showing them as null after I leave the page open for a while.. This wouldn't surprised me, as a massive number of messages are being processed in my case. Maybe the UI can't keep up with the query? I'll have to do a bit more experimenting to verify.

**Comment by samjpv** [comment]
It appears that the FROM_BYTES function is in fact yielding null sometimes, and the correct, ascii value for KSQL_COL_0 other times. A 3rd variation where the query spits out KSQL_COL_0 as the base64 byte value also seems to happen inconsistently. To summarize, 3 different things happen here with no change to the query: 
`{ "DATA": "Zm9vYmFy" } => from bytes query => { "DATA": null }`
`{ "DATA": "Zm9vYmFy" } => from bytes query => { "DATA": "Zm9vYmFy" }`
`{ "DATA": "Zm9vYmFy" } => from bytes query => { "DATA": "foobar" }`

I've no idea under what conditions each of these individually happens, but they are all happening.

**Comment by Gerrrr** [comment]
Hey @samjpv ,

As I see from the issue description, you use the following schema

```sql
CREATE STREAM newstream ( data BYTES HEADER('header.message')) WITH (KAFKA_TOPIC='topicname', VALUE_FORMAT='JSON');
```

where `data` is extracted from the record headers.

According to the [Headers doc](https://docs.ksqldb.io/en/latest/reference/sql/data-definition/#headers)

> If the Kafka record does not contain a header with the specified key, then that column will be populated by NULL.

Can you please verify that this is not the case here? In other words, can you please ensure that `data` is not `null` for the records that hit the issue? One way to do it would be to modify `ASCIIENCODED` such that it also includes the original `data` value. 

```sql
CREATE STREAM ASCIIENCODED ...
AS SELECT DATA, FROM_BYTES(DATA, 'ascii') KSQL_COL_0 FROM SOURCE SOURCE EMIT CHANGES;
```

If such a stream contains `(Zm9vYmFy, null)` or `(Zm9vYmFy, Zm9vYmFy)` row, then there is indeed a bug.

**Comment by Gerrrr** [comment]
I am going to close this issue for now. @samjpv feel free to reopen it if you run into the issue again and have time to debug it.
