### ISSUE TITLE
Enable bytes and string data types for max/min udaf

### ISSUE THREAD

**Issue by jnh5y** [confluentinc/ksql#8913]
**Is your feature request related to a problem? Please describe.**
The mentioned functions only require that types by Comparable.  Presently, they do not support BYTES or the time types.

**Describe the solution you'd like**
Add support for BYTES and time types to MAX, MIN, TopKDistinct, GREATEST, and LEAST

**Additional context**
[Add any other context or screenshots about the feature request here.](https://github.com/confluentinc/ksql/issues/8912) is about handling TopK for these types and DECIMAL.

**Comment by suhas-satish** [comment]
@bvarghese1 , can this be closed?

**Comment by bvarghese1** [comment]
I fixed it only for min and max udafs. Need to check for TopKDistinct, GREATEST, and LEAST

**Comment by jnh5y** [comment]
As some housekeeping, I added a new issue: https://github.com/confluentinc/ksql/issues/9125 for the remaining work so that we can close this issue.
