### ISSUE TITLE
Null struct deferencing inside a function call does not work as expected

### ISSUE THREAD

**Issue by jnh5y** [confluentinc/ksql#8917]
**Describe the bug**
In the Confluent Community Slack, Miguel reported that a statement like 
`SELECT IFNULL(requirements->education->degree, 'n/a') as required_edu_degree FROM 'my-stream' emit changes;`
does not produce the expected results.
(https://confluentcommunity.slack.com/archives/C6UJNMY67/p1647949968220039)

**To Reproduce**
Deference a nested struct.

The issue is that the failed null dereferencing in a function call prevents the function evaluation.  This issue is similar to https://github.com/confluentinc/ksql/issues/8324 and the fix is similar to https://github.com/confluentinc/ksql/commit/2a60269cadddc8a11522d103d800ae2a6769d690

**Comment by jnh5y** [comment]
In light of the other issue, the interesting question is what other expressions should be guarded in a similar way.

**Comment by alexwoolford** [comment]
I'm excited to see that you created a PR for this, @jnh5y .

A friend of mine ran into this issue:

```
ksql> CREATE STREAM ORDER_LINE_DEBEZIUM WITH (KAFKA_TOPIC='order_line_debezium', VALUE_FORMAT='AVRO');

ksql> SELECT
 BEFORE -> ID AS BEFORE_ID,
 AFTER->ID AS AFTER_ID,
 COALESCE(BEFORE->ID, AFTER->ID) AS ID
FROM ORDER_LINE_DEBEZIUM EMIT CHANGES;
+-------------------+-------------------+-------------------+
|BEFORE_ID          |AFTER_ID           |ID                 |
+-------------------+-------------------+-------------------+
|null               |13363              |null               |
|null               |13364              |null               |
|null               |13365              |null               |
```

Note that the `COALESCE` didn't work.

Without your PR, they'd need to write an SMT or Kafka Streams job. That's not ideal. They want a nice, neat ksqlDB statement that's simple to maintain and understand.

Any idea when your PR will be merged and made available in Confluent Cloud?

**Comment by jnh5y** [comment]
https://github.com/confluentinc/ksql/pull/8918 should address this issue.
