### ISSUE TITLE
CLI - improve visual usability

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#892]
Many people like to use CLI, even if a GUI is available. We should make the KSQL CLI even nicer to use: 

* Render results with column headings (consider option to periodically repeat, c.f. pages of continuous streams of data)
* Render results with each column of fixed size (either dynamically, or user-configurable). sql*plus does this [to an extreme](https://docs.oracle.com/database/121/SQPUG/ch_six.htm#SQPUG462) which I wouldn't suggest we try to imitate, but the basic syntax of `format <col> width <x>` could be useful
* Support colour coding, for example, different colours for  (a) the `ksql>` prompt , (b) command text (c) result stream (d) errors

Related: #797

**Comment by MichaelDrogalis** [comment]
This is small but worthwhile in my opinion. For (1) and (2), today we have:

```
ksql> select * from all_publications;
1559328693686 | C.S. Lewis | C.S. Lewis | The Silver Chair
1559328694429 | George R. R. Martin | George R. R. Martin | A Song of Ice and Fire
1559328694555 | C.S. Lewis | C.S. Lewis | Perelandra
1559328694696 | George R. R. Martin | George R. R. Martin | Fire & Blood
1559328694768 | J. R. R. Tolkien | J. R. R. Tolkien | The Hobbit
1559328694840 | J. R. R. Tolkien | J. R. R. Tolkien | The Lord of the Rings
1559328694924 | George R. R. Martin | George R. R. Martin | A Dream of Spring
1559328695002 | J. R. R. Tolkien | J. R. R. Tolkien | The Fellowship of the Ring
1559328695095 | George R. R. Martin | George R. R. Martin | The Ice Dragon
```

Whereas we could instead have:
```
    rowtime   |        rowkey       | author              |         title
--------------+---------------------+---------------------+--------------------------
1559328693686 | C.S. Lewis          | C.S. Lewis          | The Silver Chair
1559328694429 | George R. R. Martin | George R. R. Martin | A Song of Ice and Fire
1559328694555 | C.S. Lewis          | C.S. Lewis          | Perelandra
1559328694696 | George R. R. Martin | George R. R. Martin | Fire & Blood
1559328694768 | J. R. R. Tolkien    | J. R. R. Tolkien    | The Hobbit
1559328694840 | J. R. R. Tolkien    | J. R. R. Tolkien    | The Lord of the Rings
1559328694924 | George R. R. Martin | George R. R. Martin | A Dream of Spring
1559328695002 | J. R. R. Tolkien    | J. R. R. Tolkien    | The Fellowship of the Ring
1559328695095 | George R. R. Martin | George R. R. Martin | The Ice Dragon
```

In general, I like copying [what Postgres has](https://www.postgresql.org/docs/9.3/tutorial-select.html) for usability.

**Comment by agavra** [comment]
Closing this out since we have everything other than color coding (which we can open a new feature request ticket if we'd like that)!

**Comment by rmoff** [comment]
Thanks @agavra - I've raised #3728

**Comment by rmoff** [comment]
Also https://github.com/confluentinc/ksql/issues/4457
