### ISSUE TITLE
Does ksqldb 's custom udaf function guarantee concurrency?

### ISSUE THREAD

**Issue by Kimakjun** [confluentinc/ksql#8941]
I'm running 5 ksqldb instance(k8s), and each instance thread(ksql server properties) num is 3

I implemented the udaf function to aggregate a simple map object using the udaf function. Data corruption did not occur when more than 10,000 pieces of data per minute were aggregated through the udaf function in a cluster environment.
My guess is that the udfa function seems to guarantee concurrency, am I right?

I have one more question for you.
I am currently running a ksqldb instance in the k8s environment. Will the table aggregate data of ksqldb work normally without loss even in the restart situation?

**Comment by agavra** [comment]
You should not store any information in fields of your UDAF implementation. The state management is done by ksqlDB and the only state that you should rely on is what is passed to you via the `aggregate` method.

> I am currently running a ksqldb instance in the k8s environment. Will the table aggregate data of ksqldb work normally without loss even in the restart situation?

Yes that is correct, the offset management is done via the kafka consumer group protocol and state restoration is done via reading changelog topics. If you need exactly once semantics, make sure to enable them https://docs.ksqldb.io/en/latest/operate-and-deploy/exactly-once-semantics/
