### ISSUE TITLE
Parameter for FORMAT_TIMESTAMP is different than TIMESTAMPTOSTRING

### ISSUE THREAD

**Issue by nicholasnet** [confluentinc/ksql#8957]
As per this [documentation](https://docs.ksqldb.io/en/latest/developer-guide/ksqldb-reference/scalar-functions/#timestamptostring) `TIMESTAMPTOSTRING` is deprecated and it says to use `FORMAT_TIMESTAMP` however parameter requirements for both functions are different I think documentation should mention that in some way. 

For instance 
This works
`TIMESTAMPTOSTRING(WINDOWEND, 'yyyy-MM-dd''T''HH:mm:ss.SSSX', 'UTC') AS window_end`
But this does **not**
`FORMAT_TIMESTAMP(WINDOWEND, 'yyyy-MM-dd''T''HH:mm:ss.SSSX', 'UTC') AS window_end`

**Comment by jnh5y** [comment]
@colinhicks one option may be to add a version of FORMAT_TIMESTAMP which takes a long.... 

Thoughts?

**Comment by suhas-satish** [comment]
Lets track this for the docs bug fix and create a separate issue for fix-it-week for the bug.

**Comment by JimGalasyn** [comment]
@suhas-satish, I can add a note to the docs -- what's the workaround?

**Comment by jnh5y** [comment]
@JimGalasyn yes, that does look like the correct workaround.

**Comment by JimGalasyn** [comment]
This fix is live now: https://docs.ksqldb.io/en/latest/developer-guide/ksqldb-reference/scalar-functions/#timestamptostring

**Comment by JimGalasyn** [comment]
> @JimGalasyn I was just chatting with @wlaforest and he suggested that the note may be useful to put on https://docs.ksqldb.io/en/latest/developer-guide/ksqldb-reference/scalar-functions/#format_timestamp.
> 
> Maybe having it both places would be useful?

@jnh5y @wlaforest Good idea! This change is live now.

**Comment by wlaforest** [comment]
whoa, that was lightening fast!  Thanks @JimGalasyn
