### ISSUE TITLE
Tumbling time window does not behave as expected

### ISSUE THREAD

**Issue by emrekuecuek** [confluentinc/ksql#8970]
We are trying to use aggregation functions within tumbling windows. We have a stream of values, and we would like to aggregate these values inside their time buckets. But ksqlDB applies aggregation functions in an accumulated manner instead of grouping data points into time buckets and applying aggregation functions for each time bucket individually.

ksqlDB version: 0.23.1-rc9
Example data:
```
+--------------------------------------------------+--------------------------------------------------+
|TIMESTAMP                                         |SENSOR_VALUE                                      |
+--------------------------------------------------+--------------------------------------------------+
|1648467665                                        |7.0                                               |
|1648467665                                        |26.0                                              |
|1648467725                                        |8.0                                               |
|1648467725                                        |26.0                                              |
|1648467785                                        |8.0                                               |
|1648467785                                        |26.0                                              |
|1648467845                                        |9.0                                               |
|1648467845                                        |26.0                                              |
|1648467905                                        |8.0                                               |
|1648467905                                        |26.0                                              |
|1648467965                                        |8.0                                               |
|1648467965                                        |26.0                                              |

.
.
.
```
While creating the stream, we also use the 'TIMESTAMP' column as ROWTIME as well.
SQL Query to create stream:
```SQL
CREATE STREAM example_stream (
    timestamp BIGINT,
    sensor_value DOUBLE,
    example_tag VARCHAR
) WITH (
    KAFKA_TOPIC = 'sensor_topic'
    TIMESTAMP = 'timestamp',
    VALUE_FORMAT = 'json'
);
````

Data and the structure of the stream are put as an example. The sensor sends data every minute, and sends two message. I would like to aggregate them within five minute windowed time buckets. We are trying to use tumbling window feature for this.
```SQL
SELECT COUNT(sensor_value) AS counts, AVG(sensor_value) as average_values
FROM example_stream
WINDOW TUMBLING (SIZE 5 MINUTES) GROUP BY example_tag
EMIT CHANGES;
```

As a result of the ```SELECT``` query, we expect every data point in the stream would be divided within 5 minute windows and aggregation functions would be applied. **Expected** example output is given below.
```
+--------------------------------------------------+--------------------------------------------------+
|COUNTS                                            |AVERAGE_VALUES                                    |
+--------------------------------------------------+--------------------------------------------------+
|10                                                |17.713051823416507                                |
|10                                                |18.5667                                           |
|10                                                |19.30379598072629                                 |
.
.
.
```
Since the sensor is sending 2 messages every minute, in 5 minute tumbling windows, we would expect 10 messages in each windows and those to be aggregated. But instead we get this output:
```
+--------------------------------------------------+--------------------------------------------------+
|COUNTS                                            |AVERAGE_VALUES                                    |
+--------------------------------------------------+--------------------------------------------------+
|1042                                              |17.713051823416507                                |
|10000                                             |18.5667                                           |
|8509                                              |19.30379598072629                                 |
|8511                                              |19.30360709669839                                 |
|8513                                              |19.303418301421356                                |
|8515                                              |19.303229594832647                                |
|8517                                              |19.30304097686979                                 |
```

Not only data points are aggregated in an unexpected way, aggregation function keeps accumulating as time goes by. We set offset as the earliest because we would like to aggregate previous entries within themselves as well. But in the scenario, data points are aggregated in an interested manner, not only that; also aggregations are applied in an accumulated way.

So is there a way where we can apply aggregations the way we expect? Thank you for taking the time to understand our question and helping to us.

**Comment by suhas-satish** [comment]
@emrekuecuek , can you try converting the timestamp to milliseconds?

**Comment by mjsax** [comment]
Cf https://docs.ksqldb.io/en/latest/how-to-guides/use-a-custom-timestamp-column/#timestamps-as-long-values

ksqlDB assume that BIGINT is a timestamp in ms -- if your data contains seconds, it explains it (and why the count is 10,000 instead of 10).

Also note that ksqlDB might emit intermediate result before the window is actually closed. You can try `EMIT FINAL` (instead of `EMIT CHANGES`) to get only final results.

**Comment by emrekuecuek** [comment]
Thank you so much for your effort and great insight information. I will implement your suggestions and examine the results as soon as possible. I tried converting the timestamp to nano-second I think, but I will convert it to milliseconds. In the aggregation part, we noticed that if we select the window as 5 seconds, ksqlDB considers it as 5000 seconds. Everything is multiplied by a thousand and I think timestamp format is probably the issue here. I'll get back to you soon as I try it.

Thank you again.

**Comment by mjsax** [comment]
> I tried converting the timestamp to nano-second

As kslqDB always assumes ms, if you use ns you are off by a factor or 1000x -- similar, if your timestamp are seconds, you are also off by 1000x (just in the other direction).

Closing this ticket for now. Feel free to follow up if necessary.

**Comment by emrekuecuek** [comment]
Hi, just to add a small thing (maybe for other developers who will have the same issue), when you try to convert a timestamp column into another one by creating a new stream with `CREATE STREAM AS SELECT` statement, new stream uses the original streams `ROWTIME` column. So one might need to indicate timestamp column as the new processed one so that aggregation windows are handled properly. I'll leave an example below.

```sql
CREATE STREAM example_stream_ms_ts
    WITH(
        kafka_topic = 'example_stream_ms_ts',
        value_format = 'json',
        timestamp = 'timestamp'
    )
    AS SELECT
        timestamp*1000 AS timestamp,
        sensor_value,
        example_tag
    FROM example_stream
    EMIT CHANGES;
```
Not indicating a timestamp parameter in `CREATE STREAM` query will result in using ROWTIME of example_stream, which is not in ms format. Hence, this solution worked for me. Thank you for all your effort.

**Comment by mjsax** [comment]
Thanks for the follow up! -- Great call out!
