### ISSUE TITLE
TIMESTAMPSUB does not work for singular names of time units, eg. DAY, MINUTE,HOUR 

### ISSUE THREAD

**Issue by SamiShaikh** [confluentinc/ksql#8971]
**Describe the bug**
[timestampsub](https://docs.ksqldb.io/en/0.24.0-ksqldb/developer-guide/ksqldb-reference/scalar-functions/#timestampsub) does not work for singular names of time units, eg. DAY, MINUTE,HOUR. However the docs for [timeunit](https://docs.ksqldb.io/en/latest/reference/sql/time/#time-units) reads it allows singular names, eg DAY, HOUR, MINUTE
Is this a bug or just docs update as plural works for time units eg, DAYS, HOURS, MINUTES?

**To Reproduce**
select rowtime, timestampsub(MINUTE, 1, from_unixtime(rowtime)) from PWCTEST emit changes;
Line: 1, Col: 30: SELECT column 'MINUTE' cannot be resolved.
Statement: select rowtime, timestampsub(MINUTE, 1, from_unixtime(rowtime)) from PWCTEST emit changes;

**Expected behavior**
As per the docs singular minute should work.

**Actual behaviour**
Singular name does not work for time units
Line: 1, Col: 30: SELECT column 'MINUTE' cannot be resolved.
Statement: select rowtime, timestampsub(MINUTE, 1, from_unixtime(rowtime)) from PWCTEST emit changes;

**Comment by suhas-satish** [comment]
@JimGalasyn , would you be able to update docs for this ?

**Comment by JimGalasyn** [comment]
@suhas-satish, tracking with internal ticket DOCS-13323.

**Comment by JimGalasyn** [comment]
@Gerrrr, is this also true for the TIMESTAMPADD, TIMESUB, and TIMEADD functions?

**Comment by Gerrrr** [comment]
@JimGalasyn yeah. The only singular time unit among specified in https://docs.ksqldb.io/en/latest/reference/sql/time/#time-units that works right now is `MILLISECOND`.

**Comment by JimGalasyn** [comment]
Fixed in #8992.
