### ISSUE TITLE
Set the SR config 'auto.register.schemas' to False by default

### ISSUE THREAD

**Issue by spena** [confluentinc/ksql#8995]
This issue is related to the `auto.register.schemas` config from SR. When I execute an INSERT statement, the row serializer attempts to register the stream/table schema in SR. 

First, If the user does not have Write permissions on SR, then the INSERT statement fails with authorization denied. This is a little weird because users don't' necessary need Write perms on SR for inserting data into a Topic. This denied operation is caused by the `auto.register.schemas`.

Second, for multiple schema definitions, the INSERT attempts to register the stream/table schema to SR because it is different from the one available in SR. However, the registration fails because it is not compatible. For multiple schema defs, the `auto.register.schemas` must be set to `false` to make it work.

Thrid, when using `value_schema_id` during CREATE, the `auto.register.schemas` is also set to `false` to make work.

So, if 3 issues are fixes by setting the config to `false, then should we set this to false by default instead?

Also, If the SR schema does not exist, say it was deleted after the stream/table was created, then the INSERT will register the schema again. I am not sure if this is what users expect from INSERT. Maybe they deleted the SR schema for other reasons and now KSQL registers it internally.

I think we should set `auto.register.schemas` to `false` and avoid INSERT to register the schema. We should just make sure that the serializer can serialize a row compatible with the SR schema, which only requires a Read permission.

**Comment by suhas-satish** [comment]
Related: https://github.com/confluentinc/ksql/issues/6091 `New schema version registered on INSERT VALUES`

**Comment by suhas-satish** [comment]
@mjsax , whats the status of the open PRs linked above? What are the next steps here?

**Comment by suhas-satish** [comment]
@bvarghese1 , can you close this issue and open another one with the proposed new approach?

**Comment by bvarghese1** [comment]
Closing this as we cannot turn off the auto.register.schemas setting to False by default as this breaks the changes that were merged in this PR - https://github.com/confluentinc/ksql/pull/9238
Instead tackling this issue - https://github.com/confluentinc/ksql/issues/9438
