### ISSUE TITLE
LATEST_BY_OFFSET work around when using MAP<STRING,STRING>

### ISSUE THREAD

**Issue by adminnz** [confluentinc/ksql#9000]
**Provide details of the setup you're running**
Confluent Cloud ksqlDB version 0.24.0

**Outline your question**
I have a stream which is defined as
`CREATE STREAM NAME_METADATA (NAME STRING KEY, ATTRIBUTES<STRING,STRING>) WITH (KAFKA_TOPIC='metadata_changes', PARTITIONS = 4, VALUE_FORMAT = 'JSON');`

The attributes keys are customer defined, so are not known ahead of time.

I'm trying to produce a materialized view (table) from this which only has the latest ATTRIBUTES per NAME.

```
SELECT
NAME, LATEST_BY_OFFSET(ATTRIBUTES) AS LATEST_ATTRIBUTES
FROM NAME_METADATA
GROUP BY NAME
EMIT CHANGES;
```

But I get "Function 'LATEST_BY_OFFSET' does not accept parameters (MAP<STRING, STRING>).".
I can see there is a change ([PR #8878](https://github.com/confluentinc/ksql/pull/8878)) that has been merged that looks to support this now, but I have no idea when it will be available within confluent cloud.

In the mean time I thought of trying to convert the MAP<STRING,STRING> -> JSON_STRING and use that in the LATEST_BY_OFFSET and then use JSON_RECORDS to get a MAP<STRING,STRING> back, like the following.

```
SELECT
NAME, JSON_RECORDS(LATEST_BY_OFFSET(TO_JSON_STRING(ATTRIBUTES))) AS LATEST_ATTRIBUTES
FROM NAME_METADATA
GROUP BY NAME
EMIT CHANGES;
```
However it appears that the TO_JSON_STRING introduces extra double quotes and slash and so the resulting records do not appear correct in the Confluent Cloud ksqlDB editor.

Original Record:
```
{
    "NAME": "John",
    "ATTRIBUTES":  {
        "KEY_1": "FOO",
        "KEY_2": "BAR"
    }
}
```
Resulting Record using the MAP<STRING,STRING> -> TO_JSON_STRING -> JSON_RECORDS:
```
{
    "NAME": "John",
    "ATTRIBUTES":  {
        "KEY_1": "\"FOO\"",
        "KEY_2": "\"BAR\""
    }
}
```

I tried doing a REPLACE( ATTRIBUTES_JSON_STRING, '\"', '') but it does nothing.
Is there any solution/work around for this?

**Comment by jnh5y** [comment]
@adminnz First, sorry for the trouble.  The fix generalizing `latest_by_offset` should be landing in Confluent Cloud soon.  

I tried out your work around, I have to admit; I do like it.  

The `replace` method is using Java's String.replace method.  The first argument is compiled as a Pattern (https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html).  If you'd like to remove the '\"', you'd need to escape the '\'.

The syntax which worked for me locally was...
```... replace(COLUMN, '\\\"', '') ...```

Can you try that and see if it helps?

**Comment by MetinSeylan** [comment]
could be related with
https://github.com/confluentinc/ksql/pull/8878

**Comment by adminnz** [comment]
@jnh5y It does not appear that REPLACE does anything at all.

I ran the following in the Confluent Cloud ksqlDB editor:
```
SELECT
NAME
, LATEST_BY_OFFSET(TO_JSON_STRING(ATTRIBUTES)) AS WITHOUT_REPLACE
, REPLACE(LATEST_BY_OFFSET(TO_JSON_STRING(ATTRIBUTES)),'\\\"','') AS WITH_REPLACE_OUTSIDE
, LATEST_BY_OFFSET(REPLACE(TO_JSON_STRING(ATTRIBUTES),'\\\"','')) AS WITH_REPLACE_INSIDE

, JSON_RECORDS(LATEST_BY_OFFSET(TO_JSON_STRING(ATTRIBUTES))) AS JSON_NO_REPLACE
, JSON_RECORDS(REPLACE(LATEST_BY_OFFSET(TO_JSON_STRING(ATTRIBUTES)),'\\\"','')) AS JSON_REPLACE_OUTSIDE
, JSON_RECORDS(LATEST_BY_OFFSET(REPLACE(TO_JSON_STRING(ATTRIBUTES),'\\\"',''))) AS JSON_REPLACE_INSIDE
FROM NAME_METADATA
GROUP BY NAME
EMIT CHANGES;
```

And an the output is below:
```
{
  "NAME": "\"JOHN\"",
  "WITHOUT_REPLACE": "{\"KEY_1\":\"FOOFOO\",\"KEY_2\":\"BARBAR\"}",
  "WITH_REPLACE_OUTSIDE": "{\"KEY_1\":\"FOOFOO\",\"KEY_2\":\"BARBAR\"}",
  "WITH_REPLACE_INSIDE": "{\"KEY_1\":\"FOOFOO\",\"KEY_2\":\"BARBAR\"}",
  "JSON_NO_REPLACE": {
    "KEY_1": "\"FOOFOO\"",
    "KEY_2": "\"BARBAR\""
  },
  "JSON_REPLACE_OUTSIDE": {
    "KEY_1": "\"FOOFOO\"",
    "KEY_2": "\"BARBAR\""
  },
  "JSON_REPLACE_INSIDE": {
    "KEY_1": "\"FOOFOO\"",
    "KEY_2": "\"BARBAR\""
  }
}
```

**Comment by jnh5y** [comment]
Sorry about that.  Would you be willing to try again with the original (`REPLACE( ATTRIBUTES_JSON_STRING, '\"', '')` and with a single \ escapcing (`REPLACE( ATTRIBUTES_JSON_STRING, '\"', '')`)?

**Comment by adminnz** [comment]
Well i dont know what is wrong, it really does look like if the resulting strings have a " (double quote) anywhere it will output \".

I added the additional replace outputs (cant do LATEST_BY_OFFSET(ATTRIBUTES) because that doesnt work with MAP).

```
SELECT
  NAME
, ATTRIBUTES AS ATTRIBUTES_ORIGINAL
, TO_JSON_STRING(ATTRIBUTES) AS TO_STRING
, REPLACE(TO_JSON_STRING(ATTRIBUTES),'\\\"','') AS TO_STRING_WITH_REPLACE_1

, REPLACE(TO_JSON_STRING(ATTRIBUTES),'\"','') AS TO_STRING_WITH_REPLACE_2
, REPLACE(TO_JSON_STRING(ATTRIBUTES),'"','') AS TO_STRING_WITH_REPLACE_3

, JSON_RECORDS(TO_JSON_STRING(ATTRIBUTES)) AS TO_STRING_TO_JSON
, JSON_RECORDS(REPLACE(TO_JSON_STRING(ATTRIBUTES),'\\\"','')) AS TO_STRING_WITH_REPLACE_TO_JSON
FROM NAME_METADATA;
```

Results in:

```
{
  "NAME": "\"JOHN\"",
  "ATTRIBUTES_ORIGINAL": {
    "KEY_1": "FOOFOO",
    "KEY_2": "BARBAR"
  },
  "TO_STRING": "{\"KEY_1\":\"FOOFOO\",\"KEY_2\":\"BARBAR\"}",
  "TO_STRING_WITH_REPLACE_1": "{\"KEY_1\":\"FOOFOO\",\"KEY_2\":\"BARBAR\"}",
  "TO_STRING_WITH_REPLACE_2": "{\"KEY_1\":\"FOOFOO\",\"KEY_2\":\"BARBAR\"}",
  "TO_STRING_WITH_REPLACE_3": "{KEY_1:FOOFOO,KEY_2:BARBAR}",
  "TO_STRING_TO_JSON": {
    "KEY_1": "\"FOOFOO\"",
    "KEY_2": "\"BARBAR\""
  },
  "TO_STRING_WITH_REPLACE_TO_JSON": {
    "KEY_1": "\"FOOFOO\"",
    "KEY_2": "\"BARBAR\""
  }
}
```
![image](https://user-images.githubusercontent.com/1552285/163077539-eec927ac-8834-46e6-98cf-a366e02004ef.png)

**Comment by jzaralim** [comment]
Removing the quotes before calling `JSON_RECORDS` won't work, because the result won't be valid JSON.

Unfortunately `JSON_RECORDS` adding extra quotes is a bug. One workaround that I can think of is creating the map with the double quotes first and then removing them:

```
TRANSFORM(JSON_RECORDS(LATEST_BY_OFFSET(TO_JSON_STRING(ATTRIBUTES))), (k, v) => REPLACE(v, '""', '"')) AS LATEST_ATTRIBUTES;
```

(more info on lambdas [here](https://docs.ksqldb.io/en/latest/how-to-guides/use-lambda-functions/))

**Comment by jnh5y** [comment]
@adminnz Good news!  ksqlDB 0.25.1 has been deployed to Confluent Cloud.  With that release, I think you can avoid needing to work around that limitation!

Can you let us know if things are working with the new release?

**Comment by jnh5y** [comment]
@adminnz Good news!  ksqlDB 0.25.1 has been deployed to Confluent Cloud.  With that release, I think you can avoid needing to work around that limitation!

Can you let us know if things are working with the new release?

**Comment by adminnz** [comment]
LATEST_BY_OFFSET(<MAP>) appears to work now. :D

However looking at the results it appears that the extra slash & double quote is also being applied to none aggregate fields, (and were in my previous tests, I just wasn't noticing those because I was focused on the LATEST_BY_OFFSET).


e.g.
Here is the original record published to the source streams topic.
![image](https://user-images.githubusercontent.com/1552285/165395303-dc747d11-58d6-4bc5-81d5-4d0a1cde9704.png)

Here is the resulting ksqldb query:
![image](https://user-images.githubusercontent.com/1552285/165395423-f012891d-2ed3-421b-a298-86bdd76151e6.png)

When consuming the table from a C# client, the NAME is quoted, even though the original record published to the stream topic was not quoted. So is not just a display issue on confluent cloud UI.

**Comment by jnh5y** [comment]
Great!  Glad to hear that LATEST_BY_OFFSET is working!

I wonder if this is happening since you are using JSON for the value_format?

**Comment by jnh5y** [comment]
@adminnz Any more feedback on the quoting issue you are seeing?  I'm going to close this issue; it sounds like you may be hitting a different issue.  Due to that, it may be better to open a new issue to track it.

**Comment by adminnz** [comment]
The latest_by_offset is working. I think you are right in that there is probably another bug in ksqlDB with regards to JSON value formats.
