### ISSUE TITLE
Add Column Defined by Function in Alter Stream Statement throws Error. 

### ISSUE THREAD

**Issue by pbettler-CBeds** [confluentinc/ksql#9019]
**Description**
In attempting to add a column defined with the REGEXP_EXTRACT Function, KSQL throws an error expecting a proper data type instead.  

**To Reproduce**
Steps to reproduce the behavior, include:
1. Using KSQL Version: 0.23.1
2. Create a stream including a VARCHAR column
3. Run ALTER STREAM like so, attempting to REGEXP_EXTRACT on the original column to make a new one:
```
ALTER STREAM RESULT_STREAM 
  ADD STRING_REGEXED REGEXP_EXTRACT('(^[^-]*)', ORIGINAL_STRING);
```

**Expected behavior**
Expecting KSQL to infer the ultimate type of the column to be VARCHAR from the return of the REGEXP_EXTRACT function and to create the column accordingly. 

**Actual behaviour**

1. Error Message: 
`line 4:35: mismatched input ''(^[^-]*)'' expecting {'STRING', INTEGER_VALUE}. Error code: 40001
 `

**Additional context**
Executed using KSQL-Migrations Tool

**Comment by jzaralim** [comment]
@pbettler-CBeds ksqlDB's grammar for `ADD` does not support inferring column types. The syntax for `ALTER...ADD COLUMN` is explained [here](https://docs.ksqldb.io/en/latest/developer-guide/ksqldb-reference/quick-reference/#alter-stream).
