### ISSUE TITLE
CSAS statements fail when `value_schema_id` is specified with `AVRO` schema

### ISSUE THREAD

**Issue by cprasad1** [confluentinc/ksql#9022]
**Describe the bug**
CSAS statements throw an error like:
```
The following value columns are changed, missing or reordered: [`MY_FIELD1` INTEGER, `MY_FIELD2` DOUBLE, `MY_FIELD3` STRING]. Schema from schema registry is [`my_field1` INTEGER, `my_field2` DOUBLE, `my_field3` STRING]
```
when `value_schema_id` is specified in the CSAS statement. Notice that the difference in the 2 schemas is only the capitalization.

**To Reproduce**
Confluent Platform Version: 7.0.1
ksqlDB version: 0.24

- Start up control-center using Confluent Platform: `confluent local services control-center start`
- Set `ksql.schema.registry.url=http://localhost:8081` in `ksql-server.properties`.
- Start ksqlDB.
- Create a topic `avrotest1` in the control center ui (or however you want).
- Register an `AVRO` schema for the value of `avrotest1` by navigating to the `Schema` tab in the control-center UI under the `avrotest1` topic. The schema to register:
```
{
  "doc": "Sample schema to help you get started.",
  "fields": [
    {
      "doc": "The int type is a 32-bit signed integer.",
      "name": "my_field1",
      "type": "int"
    },
    {
      "doc": "The double type is a double precision (64-bit) IEEE 754 floating-point number.",
      "name": "my_field2",
      "type": "double"
    },
    {
      "doc": "The string is a unicode character sequence.",
      "name": "my_field3",
      "type": "string"
    }
  ],
  "name": "sampleRecord",
  "namespace": "com.mycorp.mynamespace",
  "type": "record"
}
```
This schema will have `id=1`.
- Create ksqlDB stream: `create stream avrotest1str with (kafka_topic='avrotest1', value_format='avro');`
- Create another topic `avrotestoutput` using the control center UI.
- Create a CSAS stream:
```
create stream avrotestoutputstr with (kafka_topic='avrotestoutput', value_schema_id=1, value_format='avro') as select * from avrotest1str where my_field1 = 1 emit changes;
```
You will hit an error:
```
The following value columns are changed, missing or reordered: [`MY_FIELD1` INTEGER, `MY_FIELD2` DOUBLE, `MY_FIELD3` STRING]. Schema from schema registry is [`my_field1` INTEGER, `my_field2` DOUBLE, `my_field3` STRING]
```
This happens because [here](https://github.com/confluentinc/ksql/blob/1e1f554b1cdd3ef161542e91ed48dbd3968be8be/ksqldb-engine/src/main/java/io/confluent/ksql/schema/ksql/inference/DefaultSchemaInjector.java#L436) `colA = [MY_FIELD1 INTEGER, MY_FIELD2 DOUBLE, MY_FIELD3 STRING]` and `colB = [my_field1 INTEGER, my_field2 DOUBLE, my_field3 STRING]` which results in the set difference of `colA` and `colB` being non-empty and throwing the exception. The set difference should be blind to the capitalization, and should only check if the names and types are the same regardless of the capitalization.

**Expected behavior**
The CSAS stream gets created with the message:
```
 Message
----------------
 Stream created
----------------
```

**Actual behaviour**
cli error: 
```
The following value columns are changed, missing or reordered: [`MY_FIELD1` INTEGER, `MY_FIELD2` DOUBLE, `MY_FIELD3` STRING]. Schema from schema registry is [`my_field1` INTEGER, `my_field2` DOUBLE, `my_field3` STRING]
```

ksqlDB server logs:
```
	at io.confluent.ksql.schema.ksql.inference.DefaultSchemaInjector.inject(DefaultSchemaInjector.java:137)
	at io.confluent.ksql.statement.InjectorChain.inject(InjectorChain.java:42)
	at io.confluent.ksql.statement.InjectorChain.inject(InjectorChain.java:42)
	at io.confluent.ksql.rest.server.validation.RequestValidator.validate(RequestValidator.java:171)
	at io.confluent.ksql.rest.server.validation.RequestValidator.validate(RequestValidator.java:128)
	at io.confluent.ksql.rest.server.resources.KsqlResource.handleKsqlStatements(KsqlResource.java:293)
	at io.confluent.ksql.rest.server.KsqlServerEndpoints.lambda$executeKsqlRequest$2(KsqlServerEndpoints.java:177)
	at io.confluent.ksql.rest.server.KsqlServerEndpoints.lambda$executeOldApiEndpointOnWorker$23(KsqlServerEndpoints.java:330)
	at io.confluent.ksql.rest.server.KsqlServerEndpoints.lambda$executeOnWorker$22(KsqlServerEndpoints.java:316)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```	

**Additional context**

**Comment by lihaosky** [comment]
When you do `create stream avrotest1str with (kafka_topic='avrotest1', value_format='avro');`, the field names are uppercased in ksqlDB. 

Then you do `create stream avrotestoutputstr with (kafka_topic='avrotestoutput', value_schema_id=1, value_format='avro') as select * from avrotest1str where my_field1 = 1 emit changes;`, it checks the field names from SR matches the ones from ksqlDB which doesn't.

So this is expected behavior.

**Comment by cprasad1** [comment]
@lihaosky but from a customer's POV, they should be able to create the second stream right? as both the streams rely on the same underlying schema for the value subject

**Comment by lihaosky** [comment]
Then the first stream should be created with `value_schema_id`. Without it, it will uppercase the field names.

**Comment by colinhicks** [comment]
Let's close this in favor of the Avro field-casing-specific issue: https://github.com/confluentinc/ksql/issues/2415.

I agree with @lihaosky that the current behavior is expected.
