### ISSUE TITLE
CAST function not processing ISO-8601 timestamps with a trailing 'Z' character

### ISSUE THREAD

**Issue by grtrout** [confluentinc/ksql#9094]
**Describe the bug**
The ksqlDB CAST function is not processing valid ISO-8601 timestamps that have a 'Z' character appended. For example: `2022-04-28T21:44:47.943Z`

**To Reproduce**
Using KSQL version `0.25.1-rc7`, execute the following SQL statement:
```
SELECT
  CAST('2022-04-28T21:44:47.943' AS TIMESTAMP) AS TIMESTAMP_WITHOUT_Z,
  CAST('2022-04-28T21:44:47.943Z' AS TIMESTAMP) AS TIMESTAMP_WITH_Z
FROM ORACLE_FORMATTED_EVENTS;
```

**Expected behavior**
The field `TIMESTAMP_WITH_Z` should be rendered as a TIMESTAMP, just like the field `TIMESTAMP_WITHOUT_Z` (which I added to illustrate this).

**Actual behaviour**
The value is returned as `null` instead of the expected TIMESTAMP value.
```
{
  "TIMESTAMP_WITHOUT_Z": "2022-04-28T21:44:47.943",
  "TIMESTAMP_WITH_Z": null
}
```

**Additional context**
ksqlDB documentation states:
> Conversion fails if text is not in ISO-8601 format.

However, the trailing 'Z' character is a **valid ISO-8601 timestamp**. Per ISO-8601:
> If the time is in UTC, add a Z directly after the time without a space. Z is the zone designator for the zero UTC offset. "09:30 UTC" is therefore represented as "09:30Z" or "T0930Z". "14:45:15 UTC" would be "14:45:15Z" or "T144515Z".

**Workaround**
The workaround I am using is to replace 'Z' with '+0000' since they represent the same thing (i.e., zero UTC offset). The following SQL statement illustrates how I have done this using the REPLACE function in tandem with the CAST function.
```
SELECT
  CAST(REPLACE('2022-04-28T21:44:47.943Z', 'Z', '+0000') AS TIMESTAMP) AS FIXED_TIMESTAMP
FROM ORACLE_FORMATTED_EVENTS;
```

**Comment by colinhicks** [comment]
It looks like the problem is that the parsing logic invoked by the string-to-timestamp cast only looks for timezone offsets from UTC, beginning with `+` or `-`. The parsing logic should be improved to interpret `Z` as zero offset.

https://github.com/confluentinc/ksql/blob/87cd3c727c7a27b717d89f51459a133cfa2d7cad/ksqldb-common/src/main/java/io/confluent/ksql/util/timestamp/PartialStringToTimestampParser.java#L77
