### ISSUE TITLE
0.26 missing in changelog

### ISSUE THREAD

**Issue by raphaelauv** [confluentinc/ksql#9135]
0.26 -> https://hub.docker.com/r/confluentinc/ksqldb-server/tags

is not present in the changelog -> https://docs.ksqldb.io/en/latest/operate-and-deploy/changelog/

and https://github.com/confluentinc/ksql/blob/master/CHANGELOG.md

**Comment by JimGalasyn** [comment]
Fixed in https://github.com/confluentinc/ksql/pull/9080.
