### ISSUE TITLE
Move off deprecated `CACHE_MAX_BYTES_BUFFERING_CONFIG`

### ISSUE THREAD

**Issue by mjsax** [confluentinc/ksql#9139]
We should try to move off the deprecated KS config `CACHE_MAX_BYTES_BUFFERING_CONFIG` as soon as possible.

Cf. https://github.com/confluentinc/ksql/pull/9108#issuecomment-1131975441

Marked this a "blocker" even if it does not block the next release, but we should address before KS drops the config.

**Comment by suhas-satish** [comment]
Setting Is going away in AK 4.0 . AK 3.3 will be the next release. Giving us a few months of runway.

**Comment by jnh5y** [comment]
This change has been reverted in AK.

**Comment by colinhicks** [comment]
Closing this. As noted above, the upstream change was [reverted](https://github.com/apache/kafka/pull/12383), pending a reimplementation of KIP-770. We can reopen this at a later point.
