### ISSUE TITLE
ksql-migration tool fails with INSERT INTO ... VALUES statements

### ISSUE THREAD

**Issue by polevi** [confluentinc/ksql#9146]
The ksql-migrations apply command is not able to process migration file with INSERT INTO .. VALUES statements:

docker run --rm -v .../ksql:/ksql -w /ksql confluentinc/ksqldb-cli ksql-migrations apply -c ./ksql-migrations.properties -a
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Validating current migration state before applying new migrations
Loading migration files
1 migration file(s) loaded.

Applying migration version 5: populate table laboratory
./migrations/V000005__populate_table_laboratory.sql contents:
INSERT INTO laboratory(laboratoryId, laboratoryName) VALUES('123', 'The Lab');
Failed to execute sql: INSERT INTO laboratory(laboratoryId, laboratoryName) VALUES('123', 'The Lab');. Error: io.confluent.ksql.api.client.exception.KsqlClientException: The ksqlDB server accepted the statement issued via executeStatement(), but the response received is of an unexpected format. The executeStatement() method is only for 'CREATE', 'CREATE ... AS SELECT', 'DROP', 'TERMINATE', and 'INSERT INTO ... AS SELECT' statements.

**Expected behavior**
INSERT INTO .. VALUES statements are supported according to the spec https://docs.ksqldb.io/en/latest/operate-and-deploy/migrations-tool/

**Comment by jzaralim** [comment]
A lot of the migration tool bugs (#8280, #8014) are caused by our use of regex in the parser. We could continue fixing these issues each time they arise, but I think we should just scrap all the regex and just use the ksqldb parser exclusively. Originally we wanted to implement a separate parser in order to avoid having the dependency, but we still ended up using it anyway to parse connector statements. Instead of having this dependency for a few specific purposes, why not just use it for everything?

cc @suhas-satish

**Comment by suhas-satish** [comment]
@jzaralim , do you have a sense of the level of effort to "scrap all the regex and just use the ksqldb parser exclusively" and the risk of regressions? Based on that we can bring this to the Q3 planning prioritization conversation. 
 
cc: @colinhicks , @mjsax

**Comment by polevi** [comment]
@jzaralim Extra spaces before the opening parentheses helped, thanks

**Comment by lizchurch** [comment]
@jzaralim thanks for your help that worked!  Might be worth the extra work to to avoid using regex, I have found a lot of truth in that saying when you use regex to solve a problem now you have 2 problems.  I also find regex causes about  2x bugs to troubleshoot.  Thanks again for your assistance!

**Comment by jzaralim** [comment]
@suhas-satish The drawback is with compatibility between different versions of the migration tool and the ksqldb server. The migration tool parser was designed to be lenient, to avoid forcing the user to upgrade every time the ksqlDB grammar changes. For example, let's say in the future, we include `NOT NULL` syntax. With regex, old versions of the migration tool can still run statements like `CREATE STREAM s (col1 INT NOT NULL)...`. But if we reuse the ksql parser, then we force the user to upgrade to the latest version of the migration tool.

IMO this is reasonable to expect the user to do. This is also how the CLI works, and we know that in a lot of most cases, the CLI version could be a few versions older than the server version and still work.

**Comment by suhas-satish** [comment]
got it. Thanks for the explanation @jzaralim. It makes sense to unify the parsers and get the migration tool to adopt the mainstream ksql parser to keep things in-sync. Our deprecation path on new grammar should be backward compatible with a handful of older client versions. So yes this makes sense. Lets discuss prioritization in our next weekly meeting.
