### ISSUE TITLE
Handle tombstone records in join that calls function(s)

### ISSUE THREAD

**Issue by lucasprograms** [confluentinc/ksql#9164]
**Provide details of the setup you're running**
KSQL 0.25.1

**Outline your question**
When joining two streams on multiple columns, e.g.,
```
CREATE TABLE my_table AS
SELECT
  a.thing
  , b.other_thing
FROM
  a
  JOIN b ON CONCAT_WS('__', a.metadata_1 , CAST(a.metadata_2 as varchar)) = CONCAT_WS('__', b.metadata_1 , CAST(b.metadata_2 as varchar))
....
```
it will throw an error when dealing with tombstone records. 
```
[2022-06-01 20:48:13,875] ERROR {"type":1,"deserializationError":null,"recordProcessingError":{"errorMessage":"Error computing new key from expression CONCAT_WS('__', METADATA_1, CAST(METADATA_2 AS STRING))","record":null,"cause":["java.lang.NullPointerException"]},"productionError":null,"serializationError":null,"kafkaStreamsThreadError":null} (processing.CTAS_MY_TABLE_13.LeftSourceKeyed:44)
```

I am not clear on how to get this to either work with or ignore these null-valued records. Is that possible?

**Comment by pgaref** [comment]
Hey @lucasprograms thanks for reporting this! 
Sounds like you could get rid of null-valued records be performing a filter before the join but I want to understand the problem a bit better.

You are describing a 2-stream join on multiple columns -- I successfully tested locally something like:
``
CREATE STREAM s1 (c1 VARCHAR, c2 INTEGER)
  WITH (kafka_topic='s1', value_format='json');
  
  CREATE STREAM s2 AS
  SELECT * FROM s1 EMIT CHANGES;

-- add some data points

CREATE STREAM s4 AS
  SELECT *
  FROM s1
  JOIN s2 WITHIN 5 MINUTES
  ON CONCAT_WS('__',s1.c1, CAST(s1.c2 AS varchar)) = CONCAT_WS('__', s2.c1, CAST(s2.c2 AS varchar)) EMIT CHANGES;
``
However, on the example above I see a table / materialized view with no emit. Can you please provide some details about the actual input and queries? A few steps to reproduce this would go a long way :)
