### ISSUE TITLE
ksql-migration tool fails with CREATE SOURCE CONNECTOR 

### ISSUE THREAD

**Issue by javiervelamindcurv** [confluentinc/ksql#9220]
**Describe the bug**
ksql-migration tool returns this error when you try to create a connector

Error: io.confluent.ksql.api.client.exception.KsqlClientException: Received 400 response from server: No auth header(s) provided. To use ksqlDB connector integration in Confluent Cloud, please supply a Confluent Cloud API key and secret via the request headers 'X-Confluent-API-Key' and 'X-Confluent-API-Secret', respectively.. Error code: 40000

if you add header's file, now the error is always:
Validation error: Unauthorized. (I tried several API Keys)

**To Reproduce**
KSQL version: 0.26.0 

Create a sql file V000001__Initial_setup.sql add:

```
CREATE SOURCE CONNECTOR `connector` WITH(
    "connector.class"='CosmosDbSink',
    "name"='connector',
    "input.data.format"='JSON',
    "kafka.auth.mode"='KAFKA_API_KEY',
    "kafka.api.key"='KEY',
    "kafka.api.secret"='SECRET',
    "topics"='TOPIC',
    "connect.cosmos.connection.endpoint"='ENDPOINT',
    "connect.cosmos.master.key"='KEY',
    "connect.cosmos.databasename"='DATABASE',
    "connect.cosmos.containers.topicmap"='DATABASE#CONTAINER',
    "cosmos.id.strategy"='ProvidedInValueStrategy',
    "tasks.max"='1');

```

Execute command **ksql-migrations apply -a -c ksql-migrations.properties** 

**Expected behavior**
ksql must create the connector

**Actual behaviour**
When you execute the command **ksql-migrations apply -a -c ksql-migrations.properties** it returns this error:

Error: io.confluent.ksql.api.client.exception.KsqlClientException: Received 400 response from server: No auth header(s) provided. To use ksqlDB connector integration in Confluent Cloud, please supply a Confluent Cloud API key and secret via the request headers 'X-Confluent-API-Key' and 'X-Confluent-API-Secret', respectively.. Error code: 40000

I added a header's file and now the error is always:
Validation error: Unauthorized. (I tried several API Keys)

If you execute the sql from ksql editor in confluent cloud. It creates the connector correctly.

**Comment by javiervelamindcurv** [comment]
Working. You must use cloud api.

**Comment by jvcalderon** [comment]
Hi @javiervelamindcurv.
What do you mean? Have you made any change in the connector definition in KSQLDB? just change the key and secret?...
