### ISSUE TITLE
Ksql migration tool fails when using create with if not exists condition

### ISSUE THREAD

**Issue by entigo-mart-erlenheim** [confluentinc/ksql#9253]
**Describe the bug**
Ksql migration tool fails when using create table statement with a if not exists condition. Possibly only happens when the table already exists as the ksql client fails to parse the received result in that case.

**To Reproduce**
Using docker image: confluentinc/ksqldb-server:0.26.0

migrations/V000001__Baseline.sql

```
create table if not exists tasks
(
    taskId varchar primary key
) with (kafka_topic='tasks', value_format='json', partitions=1);
```

Using command:
`ksql-migrations apply -c ./ksql-migrations.properties -a`

**Expected behavior**
Applying migration should succeed.

**Actual behaviour**
Tool output:

```
Validating current migration state before applying new migrations
Loading migration files
1 migration file(s) loaded.
Applying migration version 1: Baseline
./migrations/V000001__Baseline.sql contents:
create table if not exists tasks
(
    taskId varchar primary key
) with (kafka_topic='tasks', value_format='json', partitions=1);

Failed to execute sql: create table if not exists tasks
(
    taskId varchar primary key
) with (kafka_topic='tasks', value_format='json', partitions=1);. Error: io.confluent.ksql.api.client.exception.KsqlClientException: The ksqlDB server accepted the statement issued via executeStatement(), but the response received is of an unexpected format. The executeStatement() method is only for 'CREATE', 'CREATE ... AS SELECT', 'DROP', 'TERMINATE', and 'INSERT INTO ... AS SELECT' statements. Use the createConnector() method instead.
Execution time: 1.1870 seconds
```

**Comment by jzaralim** [comment]
@entigo-mart-erlenheim Are both the server and the migration tool versions 0.26.0?

**Comment by entigo-mart-erlenheim** [comment]
> @entigo-mart-erlenheim Are both the server and the migration tool versions 0.26.0?

I used the same migration tool that was inside the confluentinc/ksqldb-server Docker image. I assume it's the same version in that case.
