### ISSUE TITLE
Functions which return Maps cannot be dereferenced.

### ISSUE THREAD

**Issue by jnh5y** [confluentinc/ksql#9313]
**Describe the bug**

A query like 
```SELECT K, JSON_RECORDS(colors_obj)['Red'] AS COLORS FROM test;``` results in an error like 
`Cannot get name for `JSON_RECORDS` 1 times.`

This is a regression introduced by https://github.com/confluentinc/ksql/commit/bd903477.

**Comment by agavra** [comment]
@jnh5y this can be closed, right?

**Comment by jnh5y** [comment]
Yes!
