### ISSUE TITLE
What's the purpose of the "Project-Last-changelog" internal topic?

### ISSUE THREAD

**Issue by alonpr** [confluentinc/ksql#9316]
What's the purpose behind the ***-Project-Last-changelog** internal topic in table-table joins?
It looks like writing into it happens just before writing into the sink topic so what state store basically this changelog topic backs?

**Comment by suhas-satish** [comment]
@mjsax , do you know ?

**Comment by mjsax** [comment]
The sink topic cannot be used as changelog (it's a limitation of Kafka Streams: https://issues.apache.org/jira/browse/KAFKA-6035).

Thus, the topic in question is the changelog of the final result of the query. (Closing this. Feel free to follow up if you have more questions.)

**Comment by alonpr** [comment]
@mjsax I'm just trying to wrap my head around it, why the final result of the query needs a changelog?
