### ISSUE TITLE
Protobuf maps nulls to default values in Streams

### ISSUE THREAD

**Issue by sagimedina1** [confluentinc/ksql#9333]
**Describe the bug**
`LATEST_BY_OFFSET` is not ignoring null values when using Protobuf.
I tested the same scenario with JSON, and everything worked as expected.

**To Reproduce**
Steps to reproduce the behavior, include:
1. Run docker compose up for [cp-all-in-one v7.2.1](https://raw.githubusercontent.com/confluentinc/cp-all-in-one/7.2.1-post/cp-all-in-one/docker-compose.yml)
2. Create a stream:
```
CREATE STREAM TEST_USERS_PROTO_STREAM (
    id VARCHAR KEY,
    name VARCHAR,
    city VARCHAR,
    other_number INT
) WITH (
    KAFKA_TOPIC='test_users_proto',
    VALUE_FORMAT='PROTOBUF',
    PARTITIONS=16
);
```
3. Insert the data:
```
INSERT INTO TEST_USERS_PROTO_STREAM VALUES ('X','I AM X',null,1);
INSERT INTO TEST_USERS_PROTO_STREAM VALUES ('X','I AM NEW X',null,2);
INSERT INTO TEST_USERS_PROTO_STREAM VALUES ('X',null,'LONDON',null);
```
4. Create a table:
```
CREATE TABLE TEST_USERS_PROTO_TABLE AS
SELECT id,
       LATEST_BY_OFFSET(name) AS name,
       LATEST_BY_OFFSET(city) AS city,
       LATEST_BY_OFFSET(other_number) AS other_number
FROM TEST_USERS_PROTO_STREAM
GROUP BY id
    EMIT CHANGES;
```
5. Check the results:
```
select * from TEST_USERS_PROTO_TABLE;
```
**Expected behavior**
a table with a single row and the following data:
ID=X, NAME=I AM NEW X, CITY=LONDON, OTHER_NUMBER=2

**Actual behaviour**
a table with a single row and the following data:
ID=X, NAME=, CITY=LONDON, OTHER_NUMBER=0

**Additional context**
The very same process done with JSON and works as expected:
```
CREATE STREAM TEST_USERS_STREAM (
    id VARCHAR KEY,
    name VARCHAR,
    city VARCHAR,
    other_number INT
) WITH (
    KAFKA_TOPIC='test_users',
    VALUE_FORMAT='JSON',
    PARTITIONS=16
);

INSERT INTO TEST_USERS_STREAM VALUES ('X','I AM X',null,1);
INSERT INTO TEST_USERS_STREAM VALUES ('X','I AM NEW X',null,2);
INSERT INTO TEST_USERS_STREAM VALUES ('X',null,'LONDON',null);

CREATE TABLE TEST_USERS_TABLE AS
SELECT id,
       LATEST_BY_OFFSET(name) AS name,
       LATEST_BY_OFFSET(city) AS city,
       LATEST_BY_OFFSET(other_number) AS other_number
FROM TEST_USERS_STREAM
GROUP BY id
    EMIT CHANGES;

select * from TEST_USERS_TABLE;
```

**Comment by jnh5y** [comment]
Hi @sagimedina1, many times Protobuf does not model nulls and instead nulls are mapped to default values.  For strings, the default value is the empty string, and for numbers, the default value is 0.

The issue is not actually with any function (like `LATEST_BY_OFFSET`).  You can check this by looking at the data in the stream itself:


```
ksql> select * from TEST_USERS_PROTO_STREAM;
+------------------------------------------+------------------------------------------+------------------------------------------+------------------------------------------+
|ID                                        |NAME                                      |CITY                                      |OTHER_NUMBER                              |
+------------------------------------------+------------------------------------------+------------------------------------------+------------------------------------------+
|X                                         |I AM X                                    |                                          |1                                         |
|X                                         |I AM NEW X                                |                                          |2                                         |
|X                                         |                                          |LONDON                                    |0                                         |```

**Comment by sagimedina1** [comment]
Hi @jnh5y, I respect your point, but I can't entirely agree with it. **Protobuf supports optional fields**.
In GolLang, for example, if you define something as "optional", it will generate a struct with a pointer to the type
( from example the line ``optional string name = 2;`` will convert to ``Name        *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
``
That means that I can send "nil" as a value. There are also some other methods that I could find online like:
https://itnext.io/protobuf-and-null-support-1908a15311b6

**Comment by jnh5y** [comment]
Hi @sagimedina1 fair point.  I suppose what I'm trying to say is that there is either a limitation with how ksqlDB handles nullable columns with Protobuf or there are some changes which need to be made to give folks control over it.  

By chance, could you get the Protobuf definition which is being generated by ksqlDB and published in SR?  (It sounds like you may have SR enabled.)

**Comment by suhas-satish** [comment]
@colinhicks , can you chime in here of what the expected behaviour should be in ksqlDB ?

**Comment by colinhicks** [comment]
Update: I had overlooked that we introduced a knob to control the wrapping behavior in https://github.com/confluentinc/ksql/pull/8934, with the internal `unwrapPrimitives` property. Primitives are used for new queries after ksqlDB 0.24. The previous, wrapping behavior is used for queries created by older versions. The `unwrapPrimitives` property is not user-configurable, however.

**Comment by sagimedina1** [comment]
Hi, I have done an additional test - I sent protobuf messages to a new topic (Schema Registry enabled) with "optional" fields using the GoLang client. Then I used the topic the same way (I created a stream in ksql connected topic that the golang client created) - and the results were the same, and the problem still occurred. 
I will try next to change the schema inside the schema registry with `google.protobuf.StringValue`

**Comment by lucasbru** [comment]
I checked the schema registration code, and there are settings (in `ProtobufData`) to control this behavior, called `wrapper.for.nullables` or `optional.for.nullables`, respectively. `unwrapPrimitives` doesn’t enable/disable these two settings, but `wrapper.for.raw.primitives`, which is yet another thing that only applies to single-column records.

We could either expose the settings to the user, or just enable one of them from now on. I'm not sure yet about the compability implications of this.
