### ISSUE TITLE
Single key (de)serialization

### ISSUE THREAD

**Issue by alonpr** [confluentinc/ksql#9375]
https://docs.ksqldb.io/en/latest/reference/serialization/#deserialization-of-single-keys

> ksqlDB assumes that any single key is unwrapped, which means that it's not contained in an outer record or object.

Is there any difference then, for single keys, between (de)serialization with JSON vs KAFKA?

**Comment by agavra** [comment]
yes there is a difference, the encoding is slightly different between the two formats. For example, `JSON` will encode a string using `"` (`"foo"`) while `KAFKA`'s String serializer will not (`foo`). They are pretty similar though!

LMK if that helped.

**Comment by alonpr** [comment]
@agavra - I think that I actually meant asking if it makes any difference for the **de**-serialization, for example (foo) or ("foo") can both be de-serialized with KAFKA or JSON format and as long as it's a KEY_FORMAT of a single key then shouldn't be any difference or limitation no matter which one was used, is that correct?

**Comment by agavra** [comment]
@alonpr it does matter, you can deserialize both but if you deserialize `"foo"` with JSON you'll get `foo` and if you deserialize it with Kafka you'll get `"foo"`
