### ISSUE TITLE
Roadmap for KSQL

### ISSUE THREAD

**Issue by rburton** [confluentinc/ksql#939]
Any plans on creating a roadmap for new scoped out features? e.g., joining streams

**Comment by rmoff** [comment]
@rburton stream-stream joins are almost here! They'll be in 5.0 with a preview release soon. 

For roadmap in general I don't think there's anything other than the issues here on GH.

**Comment by apurvam** [comment]
As @rmoff , there is no public roadmap at the moment, and no plans to publish one either. The new KLIP page should give a hint of what's to come, similar to how it works in Kafka.

I am going to close this now, please reopen if you have any further questions.

**Comment by jasonkuhrt** [comment]
@apurvam could you post a link to that KLIP page here?

**Comment by gAmUssA** [comment]
@jasonkuhrt here you go https://github.com/confluentinc/ksql/tree/master/design-proposals

**Comment by MichaelDrogalis** [comment]
Just wanted to update this issue -- our roadmaps are generally public now. We're keeping the milestones section of GitHub up to date to signal what's coming down the pike :) https://github.com/confluentinc/ksql/milestones

**Comment by jasonkuhrt** [comment]
thanks for the follow up

**Comment by IvanVas** [comment]
> Just wanted to update this issue -- our roadmaps are generally public now. We're keeping the milestones section of GitHub up to date to signal what's coming down the pike :) https://github.com/confluentinc/ksql/milestones

Thanks!
