### ISSUE TITLE
Add tooling to help users use KSQL against AK with ACLs

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#948]
With reference to #914.

KSQL can currently be run against an Apache Kafka cluster that is locked down with ACLs. However, it is not easy. It requires the user to work out what ACLs need to be set by either looking at error messages, or by first running a statement against an open cluster to see what groups and topics are created.

KSQL should provide tooling to list the ACLs a statement will require. Ideally, the tooling should either interact directly with AK to set the ACLs, or output something that can be used to quickly set the ACLs, i.e. we should try to avoid just outputting a list of 22 required ACLs and then require the user to go through one-by-one setting them up.

Such tooling may be of less use if we can fix #949

**Comment by apurvam** [comment]
Note heroku has such a tool for Kafka streams for exactly the same reason: https://devcenter.heroku.com/articles/kafka-streams-on-heroku#basic-kafka-plans

**Comment by big-andy-coates** [comment]
Won't fix. Return on investment low, given that KIP-290 is heading for AK 2.0 release. So users, moving forward, will be able to use ACLs on prefixed resource paths to provide tighter security
