### ISSUE TITLE
`SimpleAclAuthorizer` makes it hard to use interactive KSQL on locked down Kafka cluster.

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#949]
With reference to the findings in  #914.

The `SimpleAclAuthrorizer` supports saying a principle has access to <any> topic, using the '*' resource name, but does not support partial wildcards such as `ksl_query_*` resource names.

Partial wildcards, or something similar, would mean a small set of well defined ACLs could enable KSQL to work well with an locked-down Kafka cluster, giving the KSQL user permissions on all the groups and changelog / repartition topics it requires.

Fixing this may negate the importance / use of #948

**Comment by big-andy-coates** [comment]
kafka.next is to have hierarchical subspaces for topics - this will likely help with this. Though need to check what is proposed and if consumer groups will also be covered.

**Comment by apurvam** [comment]
I think the way to fix this is to fix the `SimpleAcrlAuthorizer` to support partial wildcards. The kafka.next hierarchical topics are meant to help with geo distribution of topics, not with ACLs.

**Comment by big-andy-coates** [comment]
[KIP-290](https://cwiki.apache.org/confluence/display/KAFKA/KIP-290%3A+Support+for+wildcard+suffixed+ACLs) has been accepted into AK 2.0 release to fix the authorizer. Once coded, we'll need to update our tests and docs to reflect this.

**Comment by big-andy-coates** [comment]
With KIP-290 on its way this item is done.
