### ISSUE TITLE
Confluent Cloud WINDOW emit FINAL 

### ISSUE THREAD

**Issue by NickSchouten** [confluentinc/ksql#9555]
We recently needed to write a confluent cloud ksql query that needed a hopping window with EMIT FINAL. 
example:

`SELECT 
 FIELD,
 COUNT_DISTINCT(OTHERFIELD) as `c` 
FROM ATABLE 
WINDOW HOPPING (SIZE 30 MINUTES, ADVANCE BY 1 MINUTE, RETENTION 3 DAYS)
 GROUP BY FIELD
 EMIT FINAL;
`

If you try to do this in confluent you will get the following error message:
Suppression is currently disabled. You can enable it by setting ksql.suppress.enabled to true

We could find little to no documentation on how to actually do this in confluent cloud. Until we randomly tried 
`KSQL_KSQL_SUPPRESS_ENABLED=true confluent ksql create <name> --api-key <api-key> --api-secret <api-secret>` 

So we wanted to provide this info to people googling.

**Comment by agavra** [comment]
For people who show up here via googling, this solution doesn't actually work - I believe it was just coincidence that we rolled out support for `EMIT FINAL` to confluent cloud just yesterday evening 😉 

Originally it was intentionally disabled, and you cannot override server configurations via the confluent CLI.

**Comment by NickSchouten** [comment]
Hahaha, ok great example of some questionable causal logic then 😂 

Thanks for the correction and for the continuous improvements!
