### ISSUE TITLE
Deprecating table rows over time

### ISSUE THREAD

**Issue by filidorwiese** [confluentinc/ksql#9563]
Hi!

I work for an airport. We have a Kafka topic with flight update messages (partitioned by flight-number+date+direction). Using KsqlDB I've created a stream and a table to create a materialized view for the purpose of an up-to-date flight schedule.

Simplified it looks something like this:

```
CREATE STREAM `flights` (
    scheduled_date INT,
    scheduled_time VARCHAR,
    flight_direction VARCHAR,
    main_flight_designator VARCHAR
)
WITH (kafka_topic='flights', value_format='json');

CREATE TABLE `flights-schedule` WITH (KEY_FORMAT='JSON') AS
SELECT main_flight_designator as `main_flight_designator`,
       scheduled_date,
       flight_direction as `flight_direction`,
       LATEST_BY_OFFSET(FROM_DAYS(scheduled_date)) as `scheduled_date`,
       LATEST_BY_OFFSET(scheduled_time, false) as `scheduled_time`,
    FROM `flights`
        GROUP BY main_flight_designator, scheduled_date, flight_direction
EMIT CHANGES;
```
This accumulates state over time as expected:

```
ksql> SELECT * FROM `flights-schedule`;
+----------------------------------------+----------------------------------------+----------------------------------------+----------------------------------------+----------------------------------------+
|main_flight_designator                  |SCHEDULED_DATE                          |flight_direction                        |scheduled_date                          |scheduled_time                          |
+----------------------------------------+----------------------------------------+----------------------------------------+----------------------------------------+----------------------------------------+
|RE556                                   |19250                                   |D                                       |2022-09-15                              |13:33:17                                |
|AF1235                                  |19250                                   |D                                       |2022-09-15                              |15:33:17                                |
|EZ345                                   |19250                                   |A                                       |2022-09-15                              |14:33:17                                |
|KL1234                                  |19250                                   |A                                       |2022-09-15                              |13:38:17                                |
|KL1235                                  |19250                                   |D                                       |2022-09-15                              |14:28:17                                |
|XD735                                   |19250                                   |D                                       |2022-09-15                              |14:17:17                                |
|AF1234                                  |19251                                   |A                                       |2022-09-16                              |13:48:17                                |
|AF1235                                  |19251                                   |D                                       |2022-09-16                              |15:48:17                                |
|XXX                                     |19250                                   |A                                       |2022-09-15                              |13:48:17                                |
|EZ346                                   |19250                                   |D                                       |2022-09-15                              |15:43:17                                |
|RE555                                   |19250                                   |A                                       |2022-09-15                              |13:03:17                                |
|XD734                                   |19250                                   |A                                       |2022-09-15                              |13:33:17                                |
|AF1234                                  |19250                                   |A                                       |2022-09-15                              |14:48:17                                |
|MZ1234                                  |19250                                   |D                                       |2022-09-15                              |14:12:17                                |
|PL122                                   |19250                                   |A                                       |2022-09-15                              |14:02:17                                |
```

However, our application is actually not interested in flights that are in the past. These rows are however indefinitely persisted in the changelog and in the underlaying rocksdb instance. I'm not too worried about the ever-increase storage requirements since the amount of data per row is actually very small, but I am worried about performance decreasing over time.

I have two questions;
- Is there some way (or future plans) to be able to define how long a row should be kept in state? Some sort of table row retention configuration perhaps? I've scoured the internet and couldn't find a clear answer.
- Is the performance of a SQL query statement such as `SELECT * FROM flights-schedule WHERE scheduled_date = '2022-09-15';` impacted by the total amount of rows in the table? And thus, does this increase over time cause a degrading performance of our application? Or is that negligible?

Thanks for your insights!

**Comment by agavra** [comment]
You may want to look at windowed `GROUP BY` clauses: https://docs.ksqldb.io/en/latest/concepts/time-and-windows-in-ksqldb-queries/#windows-in-sql-queries this can help both of your questions. For the first, you can set the retention you want on windows. For the second, you can issue pull queries using `WINDOWSTART` and `WINDOWEND` to efficiently narrow down the amount of data you scan.

Though to answer your specific questions - (1) we don't have support for something like that today, but the concept of a TTL is definitely common in SQL databases and we have considered it (https://github.com/confluentinc/ksql/issues/3519). For (2), you are correct - unless your `WHERE` clause involves only equality on the keys, it will scan the entire table - so larger tables would degrade your query performance.

LMK if this helps!

**Comment by filidorwiese** [comment]
Thanks for your suggestions! TTL for table rows is indeed what I'm looking for. Until then, maybe WINDOW-ing combined with  `WINDOWSTART` and `WINDOWEND` might work to improve the performance if the store grows over time. However, I'm having a difficult time to apply it to my use-case.

See, in my case, I'd need to `WINDOW` based on `SCHEDULED_DATE` (INT of days since epoch) instead of on event/ingest-timestamps (since a flight update might be send days in advance). So how should I write a `WINDOW` statement like that? Something with `WITH(TIMESTAMP=...)` I would recon, but still not easy to do with the data I have.

If `WINDOW`-ing per `SCHEDULED_DATE` would be possible, then in the pull-query I could execute a statement like:

```
SELECT *
  FROM `flights-schedule`
  WHERE WINDOWSTART = 19250 AND WINDOWEND = 19250;
```
to get the flights for a certain date in store.

Which would always perform consistently when compared with a statement such as:

`SELECT * FROM flights-schedule WHERE SCHEDULED_DATE = '19250';`

which would slow down over time having to search the entire store.

Correct?
