### ISSUE TITLE
Support Bytes to UUID UDF Function

### ISSUE THREAD

**Issue by pkgonan** [confluentinc/ksql#9639]
Background
* For high-volume processing, Relational Databases typically store UUIDs as binary(16) type. 
* If you use Debezium, which is famous for CDC Source Connector, it converts MySQL Binary Type into a Type called BYTES with Avro Serializer and sends it to Kafka. The toUUID Function is required to properly restore BYTES data stored in Kafka in the form of UUID String, which is the original data, and load it through the Sink Connector.

Purpose
* Support BYTES to UUID UDF Function

**Comment by nateab** [comment]
fixed by #9640
