### ISSUE TITLE
What is the release date for the next version of 0.28.2-ksqldb?

### ISSUE THREAD

**Issue by pkgonan** [confluentinc/ksql#9657]
Hi. Currently, the last released version of ksqlDB is 0.28.2-ksqldb. 

When is the next release date? I'd like to add a PR that updates the documentation before that release.

Feature PR
* https://github.com/confluentinc/ksql/pull/9640

**Comment by pkgonan** [comment]
@JimGalasyn @vpapavas @lihaosky @jnh5y 
Hi. Looking at the PR(https://github.com/confluentinc/ksql/pull/9652), it looks like you are currently working on a 0.29 release. 

The feature PR written in the current issue body was merged a few hours ago and we will be adding documentation for that feature PR soon. 

When is the 0.29 release scheduled?

**Comment by vpapavas** [comment]
Hi @pkgonan !

The 0.29 release was cut on September 14. This means that code that was merged on master as of that date will be part of 0.29. Your feature will be part of the next release, 0.30

**Comment by pkgonan** [comment]
Hi @vpapavas 

Thanks for your reply. 
So, when will 0.30 be released and available? I'm curious about the approximate release date.

**Comment by nateab** [comment]
@pkgonan the tentative release date for 0.30 is january 2023

**Comment by pkgonan** [comment]
Thank you very much!

**Comment by pkgonan** [comment]
@nateab 
Hi. Is the release confirmed in January 2023? We are waiting for this feature.

**Comment by nateab** [comment]
@pkgonan 0.29 has been delayed to january, I believe 0.30 is targeting around march now

**Comment by pkgonan** [comment]
@nateab @vpapavas @JimGalasyn @lihaosky @jnh5y 
Hi!

It's been 2023-04, but only released until ksqlDB 0.28.3.

We are Confluent paying customers and need this feature quickly. We've been waiting for months, but the release has been delayed, so we're getting back to you.

Question 1. Will this feature be included in ksqlDB 0.30.0?
Question 2. When will ksqlDB 0.30.0 be released?

**Comment by mjsax** [comment]
The next release will be 0.29, and it should include this fix. \cc @vcrfxia @aliehsaeedii for visibility.

**Comment by pkgonan** [comment]
@mjsax 
Hi. Thank you for your reply.

I understand that the PR below will be released on 0.29. (https://github.com/confluentinc/ksql/pull/9640)

Then I wonder when 0.29 will be released.

cc) @vcrfxia @aliehsaeedii

**Comment by vcrfxia** [comment]
Hi @pkgonan , the 0.29 release is in-progress. Should be less than a month out, assuming no unexpected surprises.
