### ISSUE TITLE
ksql query SHOW STREAMS is not working on the latest version on kubernetes

### ISSUE THREAD

**Issue by abdaziz** [confluentinc/ksql#9674]
**Describe the bug**
ksqldb latest version installed on kubernetes, the query to SHOW the list of STREAMS not working
ksql> SHOW STREAMS; 
at index 2
![ksql](https://user-images.githubusercontent.com/5955327/198727405-85bbd3a5-1918-4b62-b564-41177755cf9f.png)

**To Reproduce**
KSQLDB the latest version on kubernetes
Steps to reproduce the behavior, include:
run SQL QUERY: SHOW STREAMS;

**Expected behavior**
SHOW THE LIST OF STREAMS

**Comment by suhas-satish** [comment]
@abdaziz , when you say latest version, can you specify if you're running it in Confluent cloud or confluent platform (CP)? Either specify the ksqlDB 0.XX version number or the CP release version number?

**Comment by abdaziz** [comment]
Hello suhas-satish,
Thanks for your reply, finally i found my issue.
Here was my mistake: I upgraded ksqldb-server to the latest version(0.28.2) and forgat to upgrade the kdsqldb-cli as well (so the cli remain on version 0.8.1).
Since i upgraded the kdsqldb-cli to the latest version no more issue.
This issue can be closed.
