### ISSUE TITLE
Tumbling Window with Emit Final not producing any results

### ISSUE THREAD

**Issue by AlexMad88** [confluentinc/ksql#9688]
Hello I am kind of new still to ksqlDB, I created a tumbling windowed table with EMIT FINAL. The goal I am trying to achieve is aggregate all my data for a certain timeframe and emit the final results, once the window has closed. For some reason it produces no results when I check the topic. When I create the the table with EMIT CHANGES it works just fine but I don't want it to emit right away. Any suggestion to why this is happening? I am using ksqlDB/Confluent Cloud to create this.

`CREATE OR REPLACE TABLE X_PROCESSING_TIMES WITH 
(KAFKA_TOPIC = 'x_processing_times_topic', PARTITIONS=1, REPLICAS=3, FORMAT='JSON')
AS SELECT 
	ID,
	MAX(PROCESSING_TIME) AS MAX_PROCESSING_TIME,
	AVG(PROCESSING_TIME) AS AVG_PROCESSING_TIME,
	MIN(PROCESSING_TIME) AS MIN_PROCESSING_TIME
FROM STREAM_PROCESSING_TIMES
WINDOW TUMBLING (SIZE 10 SECONDS, RETENTION 120 SECONDS, GRACE PERIOD 10 SECONDS)
GROUP BY ID
EMIT FINAL;`

The window reads from a stream. Any help would be appreciated.

**Comment by mjsax** [comment]
Time advance only if data is flowing, because time is not based on wall-clock but event-time. Hence, if there is no new input data with larger timestamps, stream-time stops and the window is not closed (no matter how long you wait in wall-clock time).
