### ISSUE TITLE
ui is not working : http://localhost:8080/index.html not found

### ISSUE THREAD

**Issue by gjimher** [confluentinc/ksql#969]
I copied ksql-experimental-ui-0.1.war to ./ui and it was unzipped to ./ui/expanded, but index.html is not found.

I got it working changing KqslRestApplication.java: 
  Resource.newClassPathResource(UI_FOLDER + EXPANDED_FOLDER)
to
  Resource.newResource(UI_FOLDER + EXPANDED_FOLDER)

**Comment by dguy** [comment]
This should be fixed by: https://github.com/confluentinc/ksql/issues/951

**Comment by apurvam** [comment]
@gjimher please reopen if #951 didn't fix your issue.

**Comment by gjimher** [comment]
I works fine! thanks
