### ISSUE TITLE
KSQL cli should warn user more clearly if connection to KSQL server at startup fails

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#970]
If ksql-server is not running, KSQL launches with only a WARNING. However, it's a pretty fatal error if the server doesn't exist. 

```
Robin@asgard02 ~> ksql

**************** WARNING ******************
Remote server address may not be valid:
Error issuing GET to KSQL server
Caused by: java.net.ConnectException: Connection refused (Connection refused)
Caused by: Could not connect to the server.
*******************************************


                  ===========================================
                  =        _  __ _____  ____  _             =
                  =       | |/ // ____|/ __ \| |            =
                  =       | ' /| (___ | |  | | |            =
                  =       |  <  \___ \| |  | | |            =
                  =       | . \ ____) | |__| | |____        =
                  =       |_|\_\_____/ \___\_\______|       =
                  =                                         =
                  =  Streaming SQL Engine for Apache Kafka® =
                  ===========================================

Copyright 2017 Confluent Inc.

CLI v0.5, Server v<unknown> located at http://localhost:8080

Having trouble? Type 'help' (case-insensitive) for a rundown of how things work!

ksql> show topics;
Error issuing POST to KSQL server
Caused by: java.net.ConnectException: Connection refused (Connection refused)
Caused by: Could not connect to the server.
ksql>
```

Either

1.  move the `WARNING` to after the boilerplate launch text (so that it's obvious and not easy to miss), and change it to an `ERROR`
2. Abort on launch if cannot connect to ksql-server

**Comment by blueedgenick** [comment]
we always have the option to change the connection from within the running cli, so it's probably not FATAL enough to require exiting. Maybe adding a little instructional help to the WARNING that's already printed (and moving it below the ascii-art to make it more prominent as suggested ?) - would suffice. Something like "Please check the server address and try again. You can change to another KSQL Server at any time by typing `server http://my-server:8088`"

**Comment by rmoff** [comment]
*bump* can we look at implementing this? 

> move the WARNING to after the boilerplate launch text (**so that it's obvious and not easy to miss**), and change it to an ERROR

**Comment by miguno** [comment]
@big-andy-coates Didn't we just improve this in a recent PR of yours (targeting the `master` branch)?

**Comment by big-andy-coates** [comment]
PR raised with a fix
