### ISSUE TITLE
various internal topics not correctly following naming conventions

### ISSUE THREAD

**Issue by TheDarkFlame** [confluentinc/ksql#9767]
**Describe the bug**
I created a headless server with ksql.service.id set, however Ksqldb still creates topics with the naming as below:
 _confluent-ksql-<ksql.service.id>_config
_confluent-ksql-<ksql.service.id>query_CTAS_<table name>_1-Aggregate-GroupBy-repartition
_confluent-ksql-<ksql.service.id>query_CTAS_<table name>_1-Aggregate-Aggregate-Materialize-changelog
 

note: I used an aggregation in my topics (after which I am reading the outputs, code for reference may be found here: https://github.com/confluentinc/ksql/issues/9747#issuecomment-1380008337 )

**Expected behavior**
1. that all topics are named as <ksql.service.id><other stuff>
2. control over the topic names which will be assigned by aggregations so that in clusters where topic creation is disallowed, they can manually be assigned.

**Comment by TheDarkFlame** [comment]
Did a lot more digging.

it looks like this would be solved by:
https://github.com/confluentinc/ksql/issues/4954

**Comment by suhas-satish** [comment]
Not currently planned on the road map
