### ISSUE TITLE
json_items scaler function not available.....how to parse json_string to ksqldb array

### ISSUE THREAD

**Issue by techsayright** [confluentinc/ksql#9786]
Highlight a mistake, omission or area requiring improvement.  Please provide a link to the appropriate area of documentation and provide as much detail about what you think needs to change as possible.

**Comment by suhas-satish** [comment]
@Gerrrr , do you know a workaround for the user?

**Comment by Gerrrr** [comment]
@techsayright Can you please elaborate on the problem you are solving and what you have already tried?

**Comment by techsayright** [comment]
@ I have json_array but when i tried to explode it with explode function it gives warning like it takes only ksql array....so i need to parse this json_array to ksqldb array and for that i go through the official github page of ksql where i found json_items function which converts json_array to ksql array. But when i gonna implement it, it gives function no found error.....so do you have any solution for that

**Comment by techsayright** [comment]
> @techsayright Can you please elaborate on the problem you are solving and what you have already tried?

 I have json_array but when i tried to explode it with explode function it gives warning like it takes only ksql array....so i need to parse this json_array to ksqldb array and for that i go through the official github page of ksql where i found json_items function which converts json_array to ksql array. But when i gonna implement it, it gives function no found error.....so do you have any solution for that

**Comment by Gerrrr** [comment]
`JSON_ITEMS` will be available in the 0.29 release. The latest available release is 0.28.3. There was a typo in our docs - I am fixing it in https://github.com/confluentinc/ksql/pull/9802.

**Comment by techsayright** [comment]
okay.
