### ISSUE TITLE
Docker hub missing tag for 0.28.3

### ISSUE THREAD

**Issue by lucasprograms** [confluentinc/ksql#9788]
**Describe the bug**
Docker hub missing tag for 0.28.3 ([available tags](https://hub.docker.com/r/confluentinc/ksqldb-server/tags))

**To Reproduce**
Steps to reproduce the behavior, include:
1. `docker pull confluentinc/ksqldb-server:0.28.3`

**Expected behavior**
Image for 0.28.3 exists under 0.28.3 tag

**Actual behaviour**
Image does not exist

**Additional context**
Examples such as [this](https://docs.ksqldb.io/en/latest/operate-and-deploy/installation/install-ksqldb-with-docker/#ksqldb-interactive-server-settings) include the 0.28.3 tag in the example

**Comment by mjsax** [comment]
0.28.3 was never release to the community (due to a glitch in the release process) -- it was only released to Confluent Cloud. 

We don't intent to release 0.28.3 to the community any longer, as we are working on 0.29.0 already.

**Comment by maxschmeling** [comment]
> 0.28.3 was never release to the community (due to a glitch in the release process) -- it was only released to Confluent Cloud.
> 
> We don't intent to release 0.28.3 to the community any longer, as we are working on 0.29.0 already.

Just FYI, the [Quickstart](https://ksqldb.io/quickstart.html#quickstart-content) isn't so quick, since the commands given do not work (`docker-compose.yml` references `0.28.3`). I also haven't been able to get it to work even after changing it to `0.28.2`, but I had to get past the version thing first.

After that, I get this error when running `docker exec -it ksqldb-cli ksql http://ksqldb-server:8088` (not sure if it's related to the version downgrade?)
```*************************************ERROR**************************************
Remote server at http://ksqldb-server:8088 does not appear to be a valid KSQL
server. Please ensure that the URL provided is for an active KSQL server.

The server responded with the following error:
Error issuing GET to KSQL server. path:/info
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException:
	Connection refused: ksqldb-server/172.18.0.4:8088
Caused by: Could not connect to the server. Please check the server details are
	correct and that the server is running.
********************************************************************************```

**Comment by vcrfxia** [comment]
> I also haven't been able to get it to work even after changing it to 0.28.2

Hey @maxschmeling , did you see any errors in your ksql server logs (from the docker output) when you tried this? The error message makes it sound like the server wasn't able to start. The quickstart works for me on 0.28.2 so I'm wondering if maybe something in your local setup (e.g., server port already taken) prevented your ksqlDB server from properly starting.

**Comment by maxschmeling** [comment]
I was able to use a project based on the quickstart that a coworker had setup. It may have just been something to do with my initial failures getting my environment in a weird state.

**Comment by vcrfxia** [comment]
Thanks for confirming! I will go ahead and close this ticket then, as the quickstart has also been updated to say 0.28.2 rather than 0.28.3.
