### ISSUE TITLE
displayWelcomeMessage closes System.console and log4j messages are lost

### ISSUE THREAD

**Issue by gjimher** [confluentinc/ksql#986]
I am not sure if it is intended behaviour. 

In dev environment (log4j.properties used) logging is lost after KsqlRestApplication.displayWelcomeMessage call:

    try (PrintWriter writer =
             new PrintWriter(new OutputStreamWriter(System.out, StandardCharsets.UTF_8))) {

closes System.out

**Comment by big-andy-coates** [comment]
Nope, I don't think that is intentional. Thanks for reporting @gjimher !
