### ISSUE TITLE
Which EC2 Instance Type is Suitable for ksqlDB?

### ISSUE THREAD

**Issue by Rap70r** [confluentinc/ksql#9866]
Hello,

Which ec2 instance type is most suitable to run ksqlDB to handle heavy load and large topics?

Thank you

**Comment by suhas-satish** [comment]
General sizing guidelines are here - https://docs.ksqldb.io/en/latest/operate-and-deploy/capacity-planning/ 
You can pick an EC2 instance that has resources close to the minimum specifications described above and add more according to your workload

**Comment by Rap70r** [comment]
Thank you, @suhas-satish.
