### ISSUE TITLE
Does ksqlDb support recursive types for JSON schema?

### ISSUE THREAD

**Issue by andresmonc** [confluentinc/ksql#9867]
Does ksqlDb support recursive JSON schemas? There's an explicit message in the docs that it doesn't for AVRO
`ksqlDB doesn't support creating streams or tables from a topic that has a recursive Avro schema.`
but does the same apply to JSON Schemas? I'm getting `java.lang.StackOverflowError` when trying to create a stream using my JSON schema and I'm wondering if that's the cause?

**Comment by mjsax** [comment]
No it doesn't, so yes, it should explain the `StackOverflowError`.

**Comment by farhan-triplelift** [comment]
@mjsax please update your documentation or error response so others don’t incur wasting time trying to figure out what this general error means. I encountered this issue myself and had no idea that this was not supported.
