### ISSUE TITLE
Aggregation table continue to count data rather than recount

### ISSUE THREAD

**Issue by qq276772555** [confluentinc/ksql#9888]
I created a aggregation table 

```
create table loginTable(
id varchar parmary key,
name varchar
) with h (kafka_topic='loginTopic',value_format='JSON');


create table aggLoginTable as 
select id,count(*) as count from loginTable group by id emit changes;
```
There are some data in aggLoginTable 
[{'id':'3615601258430410034','count':20}  ]

For some reason,I need add a new field in loginTopic .So I recreate  aggLoginTable .I did not remove the theme automatically generated by aggLoginTable.

When I insert a new piece of data, I want to continue to counting to get 21, not  recounting to get 21.

If i set property 'auto.offset.reset' to 'earliest',the newly created aggLoginTable will count the total number 21 from the first one.
[{'id':'3615601258430410034','count':21}  ]

If i set property'auto.offset.reset' to 'latest',only one newly inserted entry is counted.
[{'id':'3615601258430410034','count':20} ,{'id':'3615601258430410034','count':1} ]

What am I supposed to to do?

**Comment by mjsax** [comment]
It's not possible to keep the old count, and continue.

When you do a `DROP TABLE` statement, the data will be gone, and re-processing from scratch (using "earliest") is the only way to do it.
