### ISSUE TITLE
Created Stream has null values but the parent topic has values

### ISSUE THREAD

**Issue by Owen706** [confluentinc/ksql#9910]
Hello, 

I am facing an issue as I have a topic named orders_topic with the following fields:
 _{
  "status_timestamp": "2023-05-22T16:39:25Z",
   "appointment_start_date": "2023-05-15T08:00:00Z",
   "appointment_end_date": "2023-05-15T11:30:00Z"
 }_

Also, I have my schema defined as Type: JSON Schema as seen below:
_{
  "$id": "https://example.com/schemas/order_schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
  "appointment_end_date": {
      "description": "Appointment end date-time..",
      "type": "string"
    },
    "appointment_start_date": {
      "description": "Appointment start date-time.",
      "type": "string"
    },
   "status_timestamp": {
      "description": "The timestamp when the status was last updated.",
      "format": "date-time",
      "type": "string"
    }

The issue I am having is while my data on my topic is having data-time values, my corresponding fields in my stream as seen below is showing null
 _{
  "status_timestamp": "2023-05-22T16:39:25Z",
   "appointment_start_date": null,
   "appointment_end_date": null
 }_

See the create stream syntax which I used:

CREATE STREAM orders_stream ( `status_timestamp` STRING,  `appointment_start_end` STRING, `appointment_end_date` STRING ) WITH ( KAFKA_TOPIC='orders_topic', KEY_FORMAT='KAFKA', VALUE_FORMAT='JSON');

Could you let me know what could be the issue, as the topic has these values but the stream is having them populated as null?

**Comment by cadonna** [comment]
@Owen706 I am sorry you are having issues with your streams!
It is indeed weird that only the one of the three values is non-null.

I have a couple of questions to better understand the situation.
1. What is exactly the key and the value of the records in topic `orders_topic`?
2. How did you verify the records that show the nulls in your stream?
3. Do you use schema registry to manage your schemas?

**Comment by cadonna** [comment]
@Owen706 Thanks for letting us know!
